### ISSUE TITLE
CA1008: Compile error with DevDiv WorkItem reference

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#1032]
#### Analyzer package
Microsoft.ApiDesignGuidelines.Analyzers.UnitTests

#### Analyzer
CA1008

#### Repro steps
[A test](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.ApiDesignGuidelines.Analyzers/UnitTests/EnumsShouldHaveZeroValueTests.cs#L24) contains the following code:
```csharp
[System.Flags]
public enum E4
{
    A4 = 0,
    B4 = (uint)2  // Not a constant
}
```
The line with comment results in:
```
error CS0266: Cannot implicitly convert type 'uint' to 'int'. An explicit conversion exists (are you missing a cast?)
```

This test is decorated with DevDiv WorkItem ID 836193. Can someone from within Microsoft check if this explains the comment? I would like to know if this compile error is intentional or a mistake. If intentional, I would like to add a descriptive comment about what is going on here.

**Comment by mavasani** [comment]
DEVDIV 836193 has the following repro steps, which seems unrelated to the compiler error, which doesn't seem intentional error:

```
There are a bunch of issues in the current CodeGen APIs that are affecting the fixes:
 
1) Fixer for CA1008 CSharp_EnumsShouldZeroValueFlagsRename
: CodeGen APIs don't preserve the explicit enum field initializers if the default values are the same. For example:
 
[System.Flags]
public enum E2
{
A2 = 0,
B2 = 1
}
 
fixed code:
[System.Flags]
public enum E2
{
None,
B2
}
 
CodeGen APIs need to retain the explicit initializers for untouched field symbols.
 
2) Same test above has CodeGen issue that fields which have initializers with casts are not added by CodeGenService.CreateNamedTypeDeclaration API
 
For example:
[System.Flags]
public enum E4
{
A4 = 0,
B4 = (uint)2
}

Fixed code:
 
[System.Flags]
public enum E4
{
None
}
 
 
3) CodeGen APIs also don't seem to retain the trivia attached to original type nodes attribute list. Failing test VisualBasic_EnumsShouldZeroValueFlagsRename_AttributeListHasTrivia
 
<System.Flags> _
Private Enum E
A = 0
B = 1
End Enum


Fixed code:
<System.Flags>
Private Enum E
None
B
End Enum
```

**Comment by bkoelman** [comment]
@mavasani Thanks for looking this up. All three issues from the DevDiv item do no longer apply (see fixer unittest). Please consider closing the DevDiv item also once this fix is merged.
