### ISSUE TITLE
Missing reference to System.Resources.ResourceManager

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#1039]
#### Analyzer package

Microsoft.CodeAnalysis.Analyzers
#### Analyzer

RS1007: UseLocalizableStringsInDescriptor
#### Repro steps

The code in [this test](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Test/MetaAnalyzers/UseLocalizableStringsInDescriptorTests.cs#L75) and [this test](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Test/MetaAnalyzers/UseLocalizableStringsInDescriptorTests.cs#L108) cause the next compile errors:

```
Test0.cs(10,66): error CS0012: The type 'ResourceManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Test0.vb(11) : error BC30652: Reference required to assembly 'System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' containing the type 'ResourceManager'. Add one to your project.
```

The type `System.Resources.ResourceManager` is in mscorlib, but this probably needs a NuGet reference?

**Comment by mavasani** [comment]
We should probably define this type in source for unit tests for this analyzer (just like other unit tests).

**Comment by bkoelman** [comment]
I tried adding this in the test-source:

```csharp
namespace System.Resources
{
    public class ResourceManager
    {
    }
}
```

It does not make the error go away. Probably because the dependency is in an external assembly, not in the test-source itself.

What I think is going on here: 
`DiagnosticDescriptor` has two constructors: one with all strings, the other with Title and Description as `LocalizableString`. This test passes a `LocalizableString` for title parameter, but string for description. Because `LocalizableString` has an implicit conversion from string, the compiler is expected to pick the non-string constructor overload, in which case the analyzer-under-test must remain silent.

So I tried adding those directly in the test-source:
```csharp
namespace Microsoft.CodeAnalysis
{
    public abstract class LocalizableString
    {
        public static explicit operator string (LocalizableString localizableResource)
        {
            throw new NotImplementedException();
        }

        public static implicit operator LocalizableString(string fixedResource)
        {
            throw new NotImplementedException();
        }
    }

    public sealed class LocalizableResourceString : LocalizableString
    {
        public LocalizableResourceString(string nameOfLocalizableResource, object resourceManager, Type resourceSource)
        {
        }
    }
}
```

But now the test fails with:
```
error CS1503: Argument 2: cannot convert from 'Microsoft.CodeAnalysis.LocalizableString' to 'string'
```

So, the compiler is not picking up my implicit conversion to `LocalizableString`. Maybe because `LocalizableString` is defined now in multiple assemblies...?

**Comment by srivatsn** [comment]
Is this addressed already? @bkoelman's PR that catches compiler errors in tests would cause this test to fail otherwise right?

**Comment by bkoelman** [comment]
These tests are currently disabled. Fix is needed.

**Comment by mavasani** [comment]
I don't see any tests skipped with bug, and we are also moving towards using a new test framework `Microsoft.CodeAnalysis.Testing`.
