### ISSUE TITLE
Mark NuGet packages with developmentDependency

### ISSUE THREAD

**Issue by flcdrg** [dotnet/roslyn-analyzers#1048]
NuSpec supports the [developmentDependency element](http://docs.nuget.org/create/nuspec-reference).

It seems to me that Analyzer NuGet packages should have this element set in their nuspec files as analyzers are a development dependency eg. not required by the target assembly to execute.

**Comment by TheloniousFonk** [comment]
Hi,
I just installed FxCopAnalyzers on a project and when I generate a nuget package with that project FXCopAnalyzers is not flagged as a developmentDependency in the nuspec file. Any idea?

Steps to repro: 
- create a dummy project in VS2015.
- Add nuget package FXCopAnalyzers
- nuget spec / nuget pack "myproject.csproj"
- resulting myproject.nuspec contains : 
<package id="Microsoft.CodeAnalysis.FxCopAnalyzers" version="1.2.0-beta2" targetFramework="net46" /> (and other analyzers)
Any help would be greatly appreciated.
Thanks!

**Comment by koljada** [comment]
I have exactly the same issue with version 2.9.2. FXCopAnalyzers packages do not have `developmentDependency="true"` attribute inside `packages.config`(my target framework is `net472`).
