### ISSUE TITLE
CA2222 fires on default constructor

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/roslyn-analyzers#1068]
#### Analyzer package

Microsoft.ApiDesignGuidelines.Analyzers
#### Analyzer

DoNotDecreaseInheritedMemberVisibility
#### Repro steps

`
public class SomeClass
{
  internal SomeClass() { }
}
`
#### Expected behavior

Should not fire, because 
1. the class does not inherit anything
2. this is the default constructor that should be allowed to be made less visible compared to the outer type.
#### Actual behavior

Fires

**Comment by mavasani** [comment]
Should be fixed with https://github.com/dotnet/roslyn-analyzers/pull/1102
