### ISSUE TITLE
[VB] Convert Return to Exit Sub, when used in Sub

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/roslyn-analyzers#1073]
Convert the following usage of `Return` within a `Sub` to `Exit Sub`.

``` vb
Sub Foo()
  If cond Then Return
 ' other stuff
End Sub
```

to

``` vb
Sub Foo()
  If cond Then Exit Sub
 ' other stuff
End Sub
```

**Comment by mavasani** [comment]
This is not really a code quality improvement, and would better be implemented either in Roslyn as an IDE analyzer or some other style based analyzer package.
