### ISSUE TITLE
CA2214 complains about InitializeComponent methods in components

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#1074]
#### Analyzer package

Example: Microsoft.QualityGuidelines.Analyzers
#### Analyzer

Example: DoNotCallOverridableMethodsInConstructorsAnalyzer
#### Repro steps

Create a class that derives from System.Configuration.Install.Installer

If the constructor calls InitializeComponent which the VS designer would, then CA2214 fires. The rule currently special cases winforms controls but it should likely special case all Components.

**Comment by ZaHgO** [comment]
I have the same problem with DevExpress.XtraReports they are Components but not WinForms Controls.
