### ISSUE TITLE
List of analysers and rules for roslyn-analyzers

### ISSUE THREAD

**Issue by vinimal** [dotnet/roslyn-analyzers#1077]
#### Analyser package

*.Analyzers
#### Feature/documentation request

List of the names of the analysers and the available rules per analyser. The list can be fixed or generated.

@mavasani

**Comment by mavasani** [comment]
@vinimal Do we still need this list?

**Comment by vinimal** [comment]
@mavasani Yes, this would be needed for the integration in Oacr. Many thanks!

**Comment by mavasani** [comment]
@vinimal We now package ruleset files with an entry for every analyzer rule in each analyzer NuGet package. See https://github.com/dotnet/roslyn-analyzers/pull/1718. Will that meet your requirements?

**Comment by mavasani** [comment]
Closing as we now ship both rulesets and documentation files in the NuGet package, which has entries for for all rules implemented in the package.
