### ISSUE TITLE
 Can I configure a report to be generated after build with list of violations?

### ISSUE THREAD

**Issue by vengi83644** [dotnet/roslyn-analyzers#1079]
Similar to what we could do in the FxCop desktop application.

FxCopCmd /f:SomeAssembly.dll /r:"C:\Rules Directory\SomeRules.dll" /o:OutputFile.xml

I want to get this output to use in the CI for my projects.

**Comment by gortok** [comment]
Same. Similar question: How do I get this program working with a CI Build tool?

**Comment by mavasani** [comment]
Yes, you can specify command line switch errorlog to generate json output of diagnostics.

**Comment by mavasani** [comment]
Closing this assuming the `/errorlog` switch resolved your question.

**Comment by vengi83644** [comment]
@mavasani  Can you mention a sample here ?

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn/blob/master/docs/compilers/Error%20Log%20Format.md
