### ISSUE TITLE
NullReference exception running 

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-analyzers#1083]
#### Analyzer package

Microsoft.Composition.Analyzers

#### Analyzer

DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer

#### Repro steps

I couldn't get a simplified repro here and mine is a bit convoluted (see below for the debug info though)

1. Open solution from https://github.com/dotnet/roslyn-project-system
2. Add a reference to Microsoft.VisualStudio.ProjectSystem.VS.Implementation
3. Add a class that consumes anything from that assembly

#### Expected behavior

Build successful with whatever message the analyzer has.

#### Actual behavior

Build error:

Error	AD0001	Analyzer threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS	E:\dotnet\roslyn-project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\CSC	1	N/A

Debugging through it the null reference comes from here:

private static void ReportDiagnostic(SymbolAnalysisContext symbolContext, INamedTypeSymbol exportedType, AttributeData problematicAttribute)
        {
            // Attribute '{0}' comes from a different version of MEF than the export attribute on '{1}'
            var diagnostic = Diagnostic.Create(Rule, problematicAttribute.ApplicationSyntaxReference.GetSyntax().GetLocation(), problematicAttribute.AttributeClass.Name, exportedType.Name);
            symbolContext.ReportDiagnostic(diagnostic);
        }

problematicAttribute.ApplicationSyntaxReference is null, presumably because the issue is flagged from the referenced assembly and not the local sources. Looks like that needs to be null checked and defaulted to Location.None if there will be cases where that property can be null.

**Comment by mavasani** [comment]
This also leads to an AD0001 where the attribute might be applied on a base type in other project in the solution: https://github.com/dotnet/roslyn-analyzers/issues/1115#issue-212930597
