### ISSUE TITLE
Code analysis CA2101 Message Cannot be Removed

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#1089]
Reported through [VSFeedback](https://developercommunity.visualstudio.com/content/problem/5600/code-analysis-ca2101-message-cannot-be-removed.html)

During code analysis, I am given several CA2101 messages that tell me to use CharSet.Unicode on a struct I've defined. After adding that property to the StructLayout attribute and recompiling, the same messages come back. The attached file will reproduce the issue. 

----------------

Verify that this doesn't happen with the roslyn analyzers.

**Comment by mavasani** [comment]
Requested the customer to provide a repro and verify on 2.0.0-beta2 analyzer package.

**Comment by jinujoseph** [comment]
Have not heard back from customer, re-open if the issue still persist

**Comment by GF-Huang** [comment]
Similar issue.

![image](https://user-images.githubusercontent.com/4510984/106026764-2cd7c100-6105-11eb-8a76-a5be4d3ef7dc.png)

Win10 20H2
VS2019 16.8.4
.NET 5
