### ISSUE TITLE
Add new analyzer to validate that return value from function is used

### ISSUE THREAD

**Issue by tomekjanicki** [dotnet/roslyn-analyzers#1101]
Try to do something similar to ReturnValueUsageAnalyzer in https://richiban.uk/2016/03/17/roslyn-analyzers/

I created the issue in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2274 but was advised to move here. 

It is a CA1806, but it is not working as expected i.e. it can't raise warning or error during

        public string GetData()
        {
            return "Something important";
        }

        public void ElsewhereInTheSystem()
        {
            GetData();
        }

**Comment by mavasani** [comment]
We should add an editorconfig option to allows users to configure this rule.

**Comment by Evangelink** [comment]
@mavasani Which kind of option are you thinking about?

- Report on all methods returning something? In case we go for this, I am wondering if it wouldn't be better (it could be an addition) to introduce some method attribute for this.

- List of method signatures from whose the return shall be used?

- Something else?

**Comment by mavasani** [comment]
We already have an built-in IDE analyzer for this now, IDE0058: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueExpressionStatementTests.cs

**Comment by Jehoel** [comment]
* What purpose does IDE0058 serve when CA1806 does the same thing?
* Is there any difference? If so, then what? And why isn't the difference documented?
* Why does the documentation for both [CA1806](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1806) and [IDE0058](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0058) completely ignore each other?

Feels to me like both analysis rules were written by independent teams completely ignorant of each other's work.
