### ISSUE TITLE
CA1031 on using ExceptionDispatchInfo

### ISSUE THREAD

**Issue by saxenark** [dotnet/roslyn-analyzers#1106]
VS2015

Compile the code snippet below (partial code)

        catch (Exception e)
        {
           // some processing
            exceptionDispatchInfo = ExceptionDispatchInfo.Capture(e);
        }

        // some more processing
        exceptionDispatchInfo?.Throw();
This code compiles but Code Analysis throws up CA1031
Warning	CA1031	Modify 'FeatureController.Initialize()' to catch a more specific exception than 'Exception' or rethrow the exception.

This warning should probably be suppressed by the analyzer if possible.

**Comment by mavasani** [comment]
Unfortunately, we cannot identify this without dataflow analysis. I would recommend just adding a source suppression.
