### ISSUE TITLE
CA2241 Treats repeated use of same placeholder as distinct

### ISSUE THREAD

**Issue by flcdrg** [dotnet/roslyn-analyzers#1109]
#### Analyzer package

System.Runtime.Analyzers

#### Analyzer

ProvideCorrectArgumentsToFormattingMethods

#### Repro steps

```
string.Format("{0} and {0}", "blah");
```
#### Expected behavior

No warning

#### Actual behavior
CA2241 warning generated

**Comment by jinujoseph** [comment]
Thanks for your contribution, Closed via #1110
