### ISSUE TITLE
DeclarePublicAPIAnalyzer should be multi-targeting aware

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#1113]
#### Analyzer package

Roslyn.Diagnostics.Analyzers

#### Analyzer

RS0016: DeclarePublicAPIAnalyzer 

#### Problem statement

I have a .NET SDK style multi-targeting project. Each target may get a different set of public API exposed based on the capabilities of the target platform. 

How can I get this analyzer to allow me to specify a different PublicAPI.Shipped.txt file for each target framework?

**Comment by mavasani** [comment]
@drewnoakes mentioned he will update the analyzer documentation on how to setup the project file to enable this scenario - https://github.com/dotnet/roslyn-analyzers/issues/2621
