### ISSUE TITLE
Add an analyzer to prevent duplicate element initializations

### ISSUE THREAD

**Issue by evildour** [dotnet/roslyn-analyzers#1114]
#### Analyzer package

Microsoft.QualityGuidelines.Analyzers

#### Analyzer

AvoidDuplicateElementInitialization (suggested)

#### Repro steps

When doing something like this (perhaps as a copy/paste bug)

```csharp
var x = new Dictionary<int, string>
{
    [1] = "a",
    [2] = "b",
    [2] = "c"
};
```

the 2nd element will be overwritten with the 3rd.

#### Expected behavior

A warning should be generated if the same constant parameter(s) are used to initialize the same index of an object.

#### Actual behavior

No warning is generated.

Note: I have already written a prototype of this analyzer for C# and would be willing to rewrite it for this repo and submit a PR for it.

**Comment by evildour** [comment]
ping?

**Comment by jskeet** [comment]
cc @DustinCampbell - Dustin, is this something you've seen in any other analyzer?

**Comment by DustinCampbell** [comment]
Nope -- not something I've seen before. Good idea!

**Comment by nvankesteren** [comment]
I've seen the [PVS-Studio analyzer](https://www.viva64.com/en/pvs-studio/) doing [this kind of stuff](https://www.viva64.com/en/t/0068/). Very cool.

**Comment by 333fred** [comment]
I could see a limited fixer for scenarios like `1, 2, 2, 3 -> 1, 2, 3, 4`, but figuring out which one to change seems like an exercise in futility. I'm going to close this now that the analyzer implementation is checked in. FYI @jinujoseph.
