### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers gives Compiler warnings in VisualStudio 2017

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/roslyn-analyzers#1117]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)  (latest stable release 1.1.0)

#### Repro steps

1.  Install latest Nuget package [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)  (version 1.1.0) in a .Net Core project (e.g. library)
2.) Build the project

#### Expected behavior
No compiler warnings/errors.
#### Actual behavior
6 Compiler Warnings (maybe due to [this?](http://stackoverflow.com/a/31572009/1810304))

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Users\chris\.nuget\packages\system.runtime.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.Analyzers.dll : Could not load file or assembly 'System.Runtime.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)	ConsoleApp1	C:\Users\chris\Desktop\RadarLiveX2\Source\ConsoleApp1\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Users\chris\.nuget\packages\system.runtime.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.CSharp.Analyzers.dll : Could not load file or assembly 'System.Runtime.CSharp.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)	ConsoleApp1	C:\Users\chris\Desktop\RadarLiveX2\Source\ConsoleApp1\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Users\chris\.nuget\packages\system.runtime.interopservices.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.InteropServices.Analyzers.dll : Could not load file or assembly 'System.Runtime.InteropServices.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)	ConsoleApp1	C:\Users\chris\Desktop\RadarLiveX2\Source\ConsoleApp1\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Users\chris\.nuget\packages\system.runtime.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.CSharp.Analyzers.dll: Could not load file or assembly 'file:///C:\Users\chris\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\4feec8c2d472452ababd87ff69e822a9\53\System.Runtime.CSharp.Analyzers.dll' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)	ConsoleApp1		1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Users\chris\.nuget\packages\system.runtime.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.Analyzers.dll: Could not load file or assembly 'file:///C:\Users\chris\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\4feec8c2d472452ababd87ff69e822a9\55\System.Runtime.Analyzers.dll' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)	ConsoleApp1		1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8034	Unable to load Analyzer assembly C:\Users\chris\.nuget\packages\system.runtime.interopservices.analyzers\1.0.0\analyzers\dotnet\cs\System.Runtime.InteropServices.Analyzers.dll: Could not load file or assembly 'file:///C:\Users\chris\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\4feec8c2d472452ababd87ff69e822a9\54\System.Runtime.InteropServices.Analyzers.dll' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)	ConsoleApp1		1	Active

**Comment by mavasani** [comment]
Can you please try 1.2.0-beta2 packages?

**Comment by mavasani** [comment]
Please re-activate if this reproes with latest packages.

**Comment by ChristophB125** [comment]
Using 1.2.0-beta2 there are even more problems because the package itself throws (see below), therefore I will activate a new issue
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'System.Runtime.Analyzers.CSharpAvoidZeroLengthArrayAllocationsAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'IOperation' is disabled.'.	RadarLive.SutConfiguration	C:\GitRepos\MyProject\SubFolder\CSC	1	Active
