### ISSUE TITLE
CA2213 triggered incorrectly when only CA1001 should get triggered

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/roslyn-analyzers#1122]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)  (latest stable release 1.1.0)

#### Analyzer

[CA1001 ](https://msdn.microsoft.com/en-us/library/ms182172.aspx) : TypesThatOwnDisposableFieldsShouldBeDisposable
[CA2213 ](https://msdn.microsoft.com/en-us/library/ms182328.aspx) : DisposableFieldsShouldBeDisposed

#### Repro steps

Create a .Net Core project and build it using dotnet clean; dotnet restore; dotnet build
Use the code example from the official documentation for [CA1001](CA1001):

    public class NoDisposeMethod
    {
        FileStream newFile;

        public NoDisposeMethod()
        {
            newFile = new FileStream(@"c:\temp.txt", FileMode.Open);
        }
    }

#### Expected behavior

Get only CA1001 because it is documented [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.ApiDesignGuidelines.Analyzers/Microsoft.ApiDesignGuidelines.Analyzers.md) and I get this also in .Net 4.5.2
#### Actual behavior

Get CA1001 AND CA2213

**Comment by mavasani** [comment]
Did you try prerelease package?

**Comment by ChristophB125** [comment]
Yes, and in the beta2 package2 this behaviour did not occur, therefore the bug was raised for 1.1.0 only.
Note that the beta2 package produces tons more warnings, therefore I would never use beta2.

**Comment by mavasani** [comment]
We rewrote large number of rules from 1.1.0 to 1.2.0-beta2 and also added lot of new ones. So anything that doesn't repro on latest prerelease is going to be resolved as Not Repro. If you are seeing unexpected diagnostics with prerelease package, please file bugs on them.

**Comment by mavasani** [comment]
Closing this issue as it does not repro on 1.2.0-beta2. Please file separate bugs on other issues you are seeing on the beta2.
