### ISSUE TITLE
When to expect a new NuGet Packages release

### ISSUE THREAD

**Issue by sonnemaf** [dotnet/roslyn-analyzers#1125]
When can we expect new NuGet Packages released? There are a lot of bug fixes on the 1.2.0-beta2 version which is almost 1 year old. I would love to have a new version which solves the 'Gathering suggestions' messagebox problem. I expected a new release with the new VS2017.

**Comment by mavasani** [comment]
We expect to release new NuGet packages very soon. Note that these packages will be based on Microsoft.CodeAnalysis 2.0.0 API, and hence will only work on VS2017.

Tagging @jinujoseph

**Comment by BGrojer** [comment]
Is that still based on this repo or another one?

**Comment by mavasani** [comment]
This is still based on this repo - we are currently validating the NuGet packages built out of the repo and hope to finish it this week and then publish.

**Comment by jinujoseph** [comment]
Release: https://github.com/dotnet/roslyn-analyzers/releases/tag/v2.0.0-beta1 
Nuget Package: http://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.0.0-beta1
