### ISSUE TITLE
How to consume locally built analyzers?

### ISSUE THREAD

**Issue by pakdev** [dotnet/roslyn-analyzers#1127]
Is there some trick to build/consume locally built analyzers, @mavasani or @sharwell? I recently made a change to one of the System.Runtime.Analyzers and rebuilt the NuGets with `msbuild src\Packaging\Packaging.proj /p:Configuration=Release`. When I try to analyze my project with this new package, though, I get:

error CS8033: The assembly C:\...\System.Runtime.Analyzers.dll does not contain any analyzers

Note: I had to manually place Microsoft.CodeAnalysis.*.dll and System.Collections.Immutable next to the analyzer before it would "run", too

**Comment by pakdev** [comment]
I did some debugging with fuslogvw, and it appears that msbuild 14 always loads Microsoft.CodeAnalysis.dll 1.3.1. I think this is conflicting with the version 2.0.0 that I'm loading next to my analyzer, since [CS8033 can fire when](https://github.com/dotnet/roslyn/issues/2683) "there is a mismatch between assembly version of Microsoft.CodeAnalysis.dll referenced by the analyzer vs used by the analyzer host." Can the latest version of these analyzers only be used within VS2017?

**Comment by mavasani** [comment]
@pakdev We recently move the repo forward to Microsoft.CodeAnalysis 2.0.0 packages, and we rely on the unshipped IOperation APIs, which have changed between 1.3.1 and 2.0.0, so yes you will need to move to VS2017 for development on this repo.

However, for non-IOperation analyzers, we should be able to run analyzers built against higher version of MS.CA packages (2.0.0) on lower versions of VS (Dev14) as there should be no breaking API changes. @srivatsn @tmeschter I believe we supported this scenario, but I can't recall how the redirects used to work. Do you recall?

**Comment by pakdev** [comment]
Just to be clear: I have no problem building these analyzers with VS2017, but I want to run them in a VS2015 environment. 

So you're saying the non-IOperation analyzers with MS.CA 2.0.0 should run in Dev14, but the IOperation analyzers won't?

**Comment by mavasani** [comment]
Yes, IOperation is still not shipped as a public API and has had breaking changes since 1.3.1 and we expect more to come post 2.0.0. You should use version 1.2.0-beta2 of analyzer packages for VS2015. 1.2.0-beta3 (not published yet) will work only against VS2017. We will need to change the analyzer package version to reflect the VS version that it is tied with. We need to have VS version specific analyzer packages until IOperation ships as a public API, at which point it cannot have breaking changes.

**Comment by tmeschter** [comment]
@mavasani When we implemented analyzer support in VS2015 there was no way to know what, if any, breaking changes would occur with Roslyn 2.0.0. So While VS2015 Update 3 redirects versions of Microsoft.CodeAnalysis.* lower than 1.3.1, it does not do that for higher versions. So nothing built against 2.0.0 will work with VS2015.

In general analyzers should target the lowest version of the Microsoft.CodeAnalysis.* packages that provides the necessary API. I think, ideally, our `IOperation`-based analyzers would be in their own assemblies that target 2.0.0, and the rest should target 1.0.0.
