### ISSUE TITLE
Support VS2015

### ISSUE THREAD

**Issue by pakdev** [dotnet/roslyn-analyzers#1135]
As discovered in [this issue](https://github.com/dotnet/roslyn-analyzers/issues/1127), the latest version of master produces analyzers that do not work in VS2015. Now teams that have not yet switched to VS2017 must revert commits c457f57, 872974d, 9528f66, da63c31, and 5760a48 and manage potential future merge conflicts that depend on them. There needs to be a way to build this project with either 1.x or 2.x MS.CA

**Comment by mavasani** [comment]
Support matrix: https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019#fxcopanalyzers-package-versions
