### ISSUE TITLE
roslyn-analyzers does not build out of the box using provided instructions

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/roslyn-analyzers#1137]
#### Repro steps

1. Clone the repository
2. Install NuGet packages: `powershell -executionpolicy bypass src\.nuget\NuGetRestore.ps1`
3. Build: `msbuild src\Analyzers.sln`

#### Expected behavior

Solution builds

#### Actual behavior

Every project gets  `error MSB4066: The attribute "Sdk" in element <Import> is unrecognized`

#### Suspected issue

Perhaps MSBuild 14 is to blame. Running the restore script shows
`MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.`
and immediately returns. It appears that the script did nothing.
Perhaps the restore script was about to pull `Microsoft.NET.Sdk` from nuget but didn't, and this causes the error that I see.

The solution appears to restore and build successfully in VS2017

Edit: I have dev14 and a few dev15 installed side by side

**Comment by srivatsn** [comment]
Are you using a VS2017 command prompt to invoke msbuild? It does look like msbuild 14 is the one in path - try `where msbuild` to confirm. MSBuild 15 will be inside your ProgramFiles\Microsoft VisualStudio\2017\Enterprise\MSBuild

**Comment by AmadeusW** [comment]
Yes, this happens in command line. I'll switch to MSBuild 15 and post an update

**Comment by jinujoseph** [comment]
@AmadeusW, you can also run 'msbuild /t:restore src\Analyzers.sln' to restore.
I have updated the instruction as well.

Please reopen the issue if the issue still persists.

**Comment by AmadeusW** [comment]
Thank you. It worked for me when I invoked it from the VS2017 developer command prompt
