### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers not working in Visual Studio 2017 for .Net Core projects

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/roslyn-analyzers#1151]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)  (latest pre-release 1.2.0-beta2 or the latest release 1.1.0)

#### Repro steps

1.  Install Nuget package [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)  in a .Net Core project (e.g. library). The version can be either the latest pre-release 1.2.0-beta2 or the latest release 1.1.0 (in both cases it will not work but the errors are different)
2. Build the project in Visual Studio

#### Expected behavior
I expect to get CA warnings (the same ones that one gets by doing a `dotnet restore; dotnet build` on the project)
#### Actual behavior
The package itself throws and loads of warnings appear in the warning window. An example is (for the latest 1.2.0beta2)

Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'System.Runtime.Analyzers.CSharpAvoidZeroLengthArrayAllocationsAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'IOperation' is disabled.'.	RadarLive.SutConfiguration	C:\GitRepos\MyProject\SubFolder\CSC	1	Active

The errors for the latest release 1.1.0 were already described in #1117.

**Comment by mavasani** [comment]
You need to enable IOperation for your project using the following property: '<Features>IOperation</Features>'. These Analyzers are based on IOperation API which are still under development.

**Comment by ChristophB125** [comment]
@mavasani  Can you please provide documentation on how to do that?

**Comment by svick** [comment]
To enable `IOperation`, add `<Features>IOperation</Features>` to your csproj.

**Comment by pareshjoshi** [comment]
Anyone has got this working? I followed the same process, but still when build with some rules violations in place, it does not fail.

dotnet build log isn't verbose enough to get more details.

**Comment by 333fred** [comment]
@pareshjoshi, this is a very old issue that describes a problem with a pre-release version of the analyzers. If you've followed https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages and are still having issues, please open a new issue.

**Comment by RealDotNetDave** [comment]
I'm still having the issue with the latest version of the analyzers.
