### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers: Missing documentation about warnings that are disabled by default

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/roslyn-analyzers#1152]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)

#### Analyzer

[CA1021](https://msdn.microsoft.com/en-us/library/ms182126.aspx) : AbstractTypesShouldNotHaveConstructors

#### Repro steps

This is a follow up from #1121 which was closed because  CA1012 warning is apparently disabled by default. There is no documentation about which warnings that are disabled by default and also some of the documentation links are broken (on the main GitHub page and also the one specific to CA1012 [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.ApiDesignGuidelines.Analyzers/Microsoft.ApiDesignGuidelines.Analyzers.md))

**Comment by jinujoseph** [comment]
Several of the msdn pages don’t have a vb code conversion showing the warning for example : https://msdn.microsoft.com/en-us/library/ms182159.aspx

**Comment by mavasani** [comment]
@gewarren Added this documentation: https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status?view=vs-2019#unported-rules

**Comment by mavasani** [comment]
We also have documentation [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md) which has "Enabled" column which probably solves your concern for ported rules.
