### ISSUE TITLE
CA1801 has false positives when using dictionary initializers

### ISSUE THREAD

**Issue by dfederm** [dotnet/roslyn-analyzers#1156]
#### Analyzer package
Microsoft.Maintainability.Analyzers

#### Analyzer
ReviewUnusedParametersAnalyzer

#### Repro steps

The follow code causes a false positive of 1801 to appear
![image](https://cloud.githubusercontent.com/assets/6445614/25315667/ce2291dc-280d-11e7-8b49-7460f42139fb.png)

While this code does not
![image](https://cloud.githubusercontent.com/assets/6445614/25315669/de0271da-280d-11e7-88d0-301e5e527e28.png)

**Comment by TheBeardedLlama** [comment]
I can confirm this is still a bug.
I have a similar issue when the parameter is used in a Func body. Using `pragma disable` for now.

I'm running latest beta of FxCop with a core project in VS2017.

Please let me know if you require more information and what that would be

**Comment by TheBeardedLlama** [comment]
@dfederm may I suggest that you edit the title to something more generic? Something along the lines of false positives when a parameter is used in an initialisation body... not sure what
It would make it more generic and indicate to the guys that this a wider issue that applies to more cases.

**Comment by sharwell** [comment]
> I have a similar issue when the parameter is used in a Func body.

Do you have an example of this that can be included as a unit test to make sure it doesn't reappear after it's fixed?

**Comment by TheBeardedLlama** [comment]
Of course; here's an actual block of code throwing the warning with some objects anonymised to protect the innocent ;)

        public static async Task<XUser> GetXUser(this IMemoryCache memoryCache, string adUsername, HttpClient httpClient, XOptions xOptions)
        {
            if (!string.IsNullOrWhiteSpace(adUsername))
            {
                var adUsernameWithoutDomain = adUsername;
                var backslashIndex = adUsernameWithoutDomain.IndexOf('\\');
                var requestUri = new UriBuilder(xOptions.UsersApiUri);

                if (backslashIndex > 0)
                {
                    adUsernameWithoutDomain = adUsernameWithoutDomain.Substring(backslashIndex + 1);
                }

                requestUri.Path = string.Concat(requestUri.Path, "/", adUsernameWithoutDomain);

                return await memoryCache.GetOrCreateAsync(adUsername, GetUserFactory);

                async Task<XUser> GetUserFactory(ICacheEntry cacheEntry)
                {
                    cacheEntry.SetSlidingExpiration(TimeSpan.FromMinutes(xOptions.SlidingCacheExpiration));

                    XUser xUser = null;

                    var response = await httpClient.GetAsync(requestUri.Uri);

                    if (response.IsSuccessStatusCode)
                    {
                        var json = await response.Content.ReadAsStringAsync();

                        xUser = JsonConvert.DeserializeObject<xUser>(json);
                    }

                    return xUser;
                }
            }
            else
            {
                return null;
            }
        }

**Comment by TheBeardedLlama** [comment]
@mavasani why is this noise?
This is a genuine bug and it's *still* present

**Comment by mavasani** [comment]
@TheBeardedLlama 

1. This issue does not repro anymore. Can you please try https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.0-beta1 on [VS15.5 RTW](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes)?
2. `Noise` label indicates issues where analyzer is giving false reports and creating noise for the users, who are forced to suppress it in source. It is still a bug and we will work towards fixing issues marked with this label.

**Comment by TheBeardedLlama** [comment]
Oh I see, thank you for the clarification @mavasani!
Perception is king!
I did see there was a new beta, but I haven't tried yet.
I will try it and then post an update here.

**Comment by TheBeardedLlama** [comment]
@mavasani yes I can confirm that this is no longer an issue.

Many thanks for fixing team! :smile:
