### ISSUE TITLE
Build from source starts VS Migration wizard

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#1170]
#### Repro steps

1. git clean -xdf
1. msbuild /t:restore RoslynAnalyzers.sln
1. Open RoslynAnalyzers.sln in VS2017 Community v15.1 (26403.7)

#### Expected behavior
Solution loads without popup.

#### Actual behavior
Migration Wizard starts, which applies changes in project Microsoft.NetCore.VisualBasic.Analyzers.
```
- <Project>
+ <Project ToolsVersion="15.0">
```
And the .sln version header is updated:
```
- VisualStudioVersion = 15.0.26228.0
+ VisualStudioVersion = 15.0.26403.7
```

Then the solution builds without errors.

**Comment by mavasani** [comment]
Tagging @srivatsn - I presume this is due to missing VB templates for the new SDK based projects. This is fixed in latest internal builds, but is there a public workaround?

**Comment by srivatsn** [comment]
You should just change your sln file and put in the CPS guid to bypass the selector. See https://github.com/dotnet/project-system/pull/1900 for a similar change to the project system repo.
