### ISSUE TITLE
CA1802 (use const instead of static readonly) incorrectly fires if it's an interpolated string

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-analyzers#1175]
#### Analyzer

Example: UseLiteralsWhereAppropriate

#### Repro steps

1. Write a field with static readonly Blah = @"{DateTime.Now}"

#### Expected behavior

CA1802 doesn't fire.

#### Actual behavior

It does.

**Comment by jinujoseph** [comment]
https://github.com/dotnet/roslyn/pull/19062/files re-enable the analyzer

**Comment by 333fred** [comment]
Waiting on IOp support for interpolated strings.

**Comment by mavasani** [comment]
This should be fixed both in Roslyn master (IOperationWithChildren) and features/ioperation (IInterpolatedStringExpression).

**Comment by mavasani** [comment]
Verified no repro on latest VS1017.5 preview build with latest analyzer package https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.Net.RoslynDiagnostics/2.6.0-beta1-62231-02

**Comment by ArtyomGilevich** [comment]
Hello! I'm currently able to reproduce this issue on VS15.9.7.
