### ISSUE TITLE
Question: Current version as nuget

### ISSUE THREAD

**Issue by cristianmad** [dotnet/roslyn-analyzers#1178]
Hi, 

We are currently using Visual Studio 2017 and v 1.2.0-beta 2 of the analyzers for our projects. I do not believe that a newer version has been released since then (1+ year ago).

Is there a nuget feed where you guys store nuget packages of the current analyzers? (following maybe nightly builds). 
I understand that they would not be officially released. I would still like to test them (if available).

Alternatively, is there a way for me to generate them using the code submitted in the repo? I was able to compile the solution, but I couldn't find a way to generate the nuget packages.

Thanks,
 Cristian

PS: Keep up the good work! 👍

**Comment by mavasani** [comment]
@cristianmad We are planning to upload the 2.0.0-beta1 packages in a day or two to NuGet. We are doing the final testing of the NuGet packages.

Tagging @jinujoseph

**Comment by cristianmad** [comment]
Sounds great, 

Thanks!

Cristian

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-analyzers/releases/tag/v2.0.0-beta1 has been published on NuGet.

**Comment by mavasani** [comment]
http://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.0.0-beta1
