### ISSUE TITLE
Change the namespaces of our analyzers to match the analyzer package name

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1181]
We are still using the old namespace names (such as Microsoft.ApiDesignGuidelines.Analyzers.XXX) for analyzers and their unit tests even after the refactoring. We should change these to reflect the current analyzer package name.

Note that we haven't still merged the resource files from original packages. We should also merge all the resource strings within a project to also lie under same namespace and also get rid of the `CustomToolNamespace` property added to the embedded resources in all analyzer project files.

**Comment by mavasani** [comment]
Tagging @333fred and @jinujoseph - I think we should do this for our 15.3 VSIX as otherwise configuration in the ruleset editor (which lists rules by the namespace) is going to be confusing.

**Comment by jinujoseph** [comment]
ya i agree, we saw this yesterday it was very confusing

**Comment by 333fred** [comment]
👍 Trying to figure out where the analyzers were defined was seriously annoying.
