### ISSUE TITLE
PublicAPI analyzer doesn't handle type forwards of generic types correctly

### ISSUE THREAD

**Issue by jasonmalinowski** [dotnet/roslyn-analyzers#1192]
If you type forward a generic type, the public API entry will say something like `Foo<>` instead of `Foo<T>` and then not list members. I suspect there's a trivial bug where it's not handling the open generic type correctly.

**Comment by Youssef1313** [comment]
@jasonmalinowski I wrote a small test and got the correct result:

![image](https://user-images.githubusercontent.com/31348972/113408809-5684c100-93b0-11eb-9935-a6970e57b2a7.png)

Are you still able to reproduce this?

**Comment by Youssef1313** [comment]
Ok figured out I should have used `IEnumerable<>` in the test instead of a specifying a type parameter.
