### ISSUE TITLE
Get rid of Props file in Microsoft.Net.RoslynDiagnostics package in-order to support packageref

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1199]
As reported by @srivatsn 

Today if this package is referenced from .net core projects, it causes following issues 
- Since the props imported the analyzers but also because the package pulls in the other analyzer packages and they include it as well, now there are two copies of the analyzer being pulled in.
-  The props file uses a property called RoslyndiagnosticsVersion which is not defined in the package – so just including it as a package ref blows up because it can’t find those analyzers.
- It also used NuGetPackageRoot\ but that variable is supposed to already have a trailing slash.

**Comment by mavasani** [comment]
This will get done as part of https://github.com/dotnet/roslyn-analyzers/issues/1750
