### ISSUE TITLE
Analyzer exception in error list when attempting to fix CA1821: Remove empty finalizers

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn-analyzers#1211]
#### Analyzer package

Ruleset provided for testpass, along with Microsoft.CodeAnalysis.FxCopAnalyzers.Setup.vsix from 20170522.2

####

CA:1821: Remove Empty Finalizers

#### Repro steps

1. Create a VB Console App and add the ruleset.
2. Make sure CA1821 is enabled
3. Add an new class file and add the following finalizer:
```
Protected Overrides Sub Finalize()
End Sub
```
4. Make sure the warning pops up.
5. Start adding code inside the finalizer to make it not empty
#### Expected behavior
You're able to remove the warning
#### Actual behavior
The following exception appears when you start typing:
```
Warning	AD0001	Analyzer 'Microsoft.CodeQuality.VisualBasic.Analyzers.QualityGuidelines.BasicRemoveEmptyFinalizersAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

**Comment by mattscheffer** [comment]
@mavasani @jinujoseph 

This is for the VSIX test work.

**Comment by jinujoseph** [comment]
@mattscheffer , does it work for C# ?

**Comment by jinujoseph** [comment]
@333fred , can you take a look

**Comment by mattscheffer** [comment]
@jinujoseph That's correct. No crash in C#.
