### ISSUE TITLE
Rewrite the Analyzer Implementation to use IOpertion API 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1214]
- [ ] [CA1821](https://github.com/dotnet/roslyn-analyzers/issues/1176#issuecomment-304150350) : blocked by dotnet/roslyn#17861

**Comment by mavasani** [comment]
This is now not blocked, we can move it to use IOperation.

**Comment by Evangelink** [comment]
@mavasani Could you confirm that the idea is also to get rid of the syntax checks to only rely on operations? If so, does it seems right for you to use a `RegisterOperationBlockStartAction` then a couple of `RegisterOperationAction` that would detect valid children and finally a `RegisterOperationBlockEndAction` that would decide whether or not to report based on the flag?
