### ISSUE TITLE
False CA1801 reports (remove unused parameter) for methods used as event handlers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1218]
We have lot of false reports of CA1801 on Roslyn.sln for cases where a method is used as an event handler and hence defines certain unused parameter for matching the signature of the handler. We should not fire CA1823 for such methods. For example, see [OnReferenceLocationsChanged](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/Dashboard/DashboardViewModel.cs,ab4429c8bc38ab31,references), which is reference in the constructor [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/InlineRename/Dashboard/DashboardViewModel.cs,46) and cannot have a different signature.

**Comment by 333fred** [comment]
Also firing on methods marked with `Obsolete`

**Comment by mavasani** [comment]
And also firing on implicitly declared parameter symbols. For example, we fire the following diagnostic on [this](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,244) setter: `Warning	CA1801	Parameter value of method set_Features is never used. Remove the parameter or use it in the method body.`

**Comment by mavasani** [comment]
Probably we should ignore methods that just throw a NotImplementedException?

**Comment by 333fred** [comment]
@mavasani I'm going to open a separate issue for the `NotImplementedException`, as it's currently blocked in `IOperation`.

**Comment by 333fred** [comment]
Fixed in #1221.
