### ISSUE TITLE
Remove unused field (CA1823) reported for fields marked with FieldOffsetAttribute

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1219]
```
[FieldOffset(8)]
private readonly long _longValue;
```

We should not fire for fields with this attribute.

**Comment by sharwell** [comment]
💭 Actually for structs with fields using this attribute, it should be fine. The place where I'd be more concerned is when the struct uses `LayoutKind.Sequential`, since removing an "unused" field could produce breaking runtime changes.
