### ISSUE TITLE
Remove dependency on Microsoft.CodeAnalysis internal types from test utilities

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn-analyzers#1225]
Analyzer Test.Utilities project depends on having access to internal types of Microsoft.CodeAnalysis. That's very fragile since these Roslyn types can change any time.

**Comment by mavasani** [comment]
Yes, I tried to do this effort a while ago but it needed quite a few cascaded changes, so I gave up. We should do this soon.

**Comment by mavasani** [comment]
@tmat  Is this still valid? I thought we ported the required internal utilities to our utilities project...

**Comment by tmat** [comment]
There is still this: https://github.com/dotnet/roslyn-analyzers/blob/af8c297b65db728debfda84555a515298a3ee9ab/src/Test.Utilities/Directory.Build.targets#L3

**Comment by genlu** [comment]
I have removed the target file above
https://github.com/dotnet/roslyn-analyzers/pull/2255

**Comment by genlu** [comment]
Well, I spoke too soon. Ended up keeping it because we have to keep the project referencing Roslyn 2.9.0
