### ISSUE TITLE
Analyzers : Localization support 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1230]
Blocked on https://github.com/dotnet/xliff-tasks/issues/18

**Comment by jinujoseph** [comment]
Loc support added via https://github.com/dotnet/roslyn-analyzers/pull/1258 
@nguerrera , whats the next step here to send the files to loc team for translation ?

**Comment by mavasani** [comment]
@jinujoseph What needs to happen here?

**Comment by jinujoseph** [comment]
@nguerrera , just followed up on this and should just get done in couple of weeks , moving this to 15.6 to keep a track of.

**Comment by mavasani** [comment]
This is now done.
