### ISSUE TITLE
Find all unused refs/types/members.

### ISSUE THREAD

**Issue by omariom** [dotnet/roslyn-analyzers#1237]
I'd like to be able to find all the unused references, types and members in a project or a solution and have them in separate list (so I can work through all of them).
It don't have to be very fast, I am ok to have a cup of covfefe while VS searches for them.

**Comment by mavasani** [comment]
This is not related to analyzers or analyzer in this repo. This is a VS feature, so kindly report it on https://github.com/dotnet/roslyn/issues.
