### ISSUE TITLE
remove IsInvalid extension method once https://github.com/dotnet/roslyn/pull/20436 checked in

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn-analyzers#1244]
we should remove our own implementation of IsInvalid once https://github.com/dotnet/roslyn/pull/20436 is checked in.

**Comment by jinujoseph** [comment]
@heejaechang this was taken care right ?

**Comment by heejaechang** [comment]
@jinujoseph I think it is still there

**Comment by heejaechang** [comment]
@jinujoseph actually, looks like @333fred removed it. 

https://github.com/dotnet/roslyn-analyzers/commit/c3374d19836d3f989ac891992b9f12a1d1549cc2
