### ISSUE TITLE
Using public API codefix doesn't save adds to the file unless the API.txt file is open

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn-analyzers#1246]
Repro:

1. Open Roslyn.sln or Compilers.sln.
2. Add a public API, like a member to Optional.cs in CodeAnalysis.
3. Use the codefix analyzer to add the member to the Unshipped public API.
4. Hit Save All.

Expected:

Changes to the public API text file will be saved.

Actual:

Changes are not saved. If the file is opened in VS you can see the edits and then save the file, but otherwise the changes are not saved.

**Comment by amcasey** [comment]
As a consequence, VS (which knows about the change) and msbuild (which doesn't) produce different errors.

**Comment by mavasani** [comment]
Both has changed in this analyzer for quite a while. Most likely a Roslyn regression for any changes to additional files.

**Comment by mavasani** [comment]
Does not repro anymore
