### ISSUE TITLE
Upload a 2.6.0-beta version of Microsoft.Net.RoslynDiagnostics to MyGet

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-analyzers#1250]
Project System currently depends on the 2.3.0-beta1 version of this package and is trying to move forward to Roslyn 2.6.0-beta. However, this results in the following failure:
```
error CA9999: Version mismatch between the analyzer package 'Microsoft.CodeQuality.Analyzers-2.3.*' and Microsoft.CodeAnalysis '2.6.0.0'. Certain analyzers in this package will not run until the version mismatch is fixed. Analyzers in this package are preview version and are tied to a specific API version of Microsoft.CodeAnalysis. Please switch your analyzer NuGet package/VSIX to a matching version of the Microsoft.CodeAnalysis.
```

As such, a new version of the package that has a matching semantic version to the current master branch in Roslyn should be provided.

**Comment by tannergooding** [comment]
FYI. @jinujoseph, @mavasani

**Comment by tannergooding** [comment]
FYI. @jasonmalinowski, in case this has impact on the 2.6.0->2.5.0 change

**Comment by mavasani** [comment]
@jinujoseph Needs to move the analyzers repo to latest Roslyn package and bump up our version and then release a new NuGet package.

**Comment by tannergooding** [comment]
Looks like the repo was moved to the latest version yesterday: https://github.com/dotnet/roslyn-analyzers/pull/1251 and https://github.com/dotnet/roslyn-analyzers/pull/1252

So I think we just need packages now (looks like existing ones have been going to 'roslyn-tools' feed). @heejaechang, let me know if you need upload permissions.

**Comment by heejaechang** [comment]
it is already there. 

https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.Net.RoslynDiagnostics

**Comment by tannergooding** [comment]
Thanks, I didn't realize we had a separate feed for roslyn-analyzers.
