### ISSUE TITLE
Multiple analysers throwing MissingMethodException (Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInParameterOrder())

### ISSUE THREAD

**Issue by kierenj** [dotnet/roslyn-analyzers#1256]
#### Analyzer package

Unknown - how do I tell?  My projects don't reference any directly.

#### Analyzer

`SpecifyIFormatProviderAnalyzer`
`ProviderCorrectArgumentsToFormattingMethodsAnalyzer`
`NormalizeStringsToUppercaseAnalyzer`
`InstantiateArgumentExceptionsCorrectlyAnalyzer`
`DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCorrectDirectlyAnalyzer`
`CSharpAvoidZeroLengthArrayAllocationsAnalyzer`
`CallGCSurpressFinalizeCorrectlyAnalyzer`
`ImplementIDisposableCorrectlyAnalyzer`

#### Repro steps

1. Building my solution

I realise this may not be super helpful.  The code can't be shared publicly or without NDA, and it might take some time to prepare a repro case.  Before I do that, is there anything obvious I can try?

#### Expected behavior

No build warnings (or analysers giving warnings as expected)

#### Actual behavior

Example build warning

```
Warning	AD0001	Analyzer 'System.Runtime.Analyzers.SpecifyIFormatProviderAnalyzer' threw an exception of type 'System.MissingMethodException' with message 'Method not found: 'System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Semantics.IArgument> Microsoft.CodeAnalysis.Semantics.IHasArgumentsExpression.get_ArgumentsInParameterOrder()'.'.	
```

**Comment by 333fred** [comment]
Can you share a bit more about your build environment? Specifically VS version and Analyzers version. It sounds like you're using an older version of the analyzers (perhaps 1.2.0?) and a new compiler.

**Comment by 333fred** [comment]
Also see https://github.com/dotnet/roslyn-analyzers/issues/1198.

**Comment by 333fred** [comment]
As for how to tell, at least one of your projects should be referencing one of our nuget packages. At the version I'm guessing you have, we had the analyzers split by assembly names. So you should see references to things like `System.Runtime.Analyzers`, or other similar namespaces.

**Comment by kierenj** [comment]
I've done a find-in-files and can't find any references within any project files themselves, although analyzers do show under "references" in VS.  The various nuspec/project.assets.json files have loads of references in however, so maybe it's a referenced package which in turn references them?

http://imgur.com/a/6czwM

One random find-in-files result is this - could this package be the cause?

```json
      "Microsoft.ApplicationInsights.AspNetCore/1.0.1": {
        "dependencies": {
          "Desktop.Analyzers": "1.2.0-beta2",
          "Microsoft.ApiDesignGuidelines.Analyzers": "1.2.0-beta2",
          "Microsoft.ApplicationInsights": "2.1.0",
          "Microsoft.AspNetCore.Hosting.Abstractions": "1.1.1",
          "Microsoft.AspNetCore.Http.Abstractions": "1.1.1",
          "Microsoft.AspNetCore.Mvc.ViewFeatures": "1.1.2",
          "Microsoft.CodeAnalysis.Analyzers": "1.2.0-beta2",
          "Microsoft.Composition.Analyzers": "1.2.0-beta2",
          "Microsoft.Extensions.Configuration": "1.1.1",
          "Microsoft.Extensions.DiagnosticAdapter": "1.0.0",
          "Microsoft.Extensions.Logging.Abstractions": "1.1.1",
          "Microsoft.Maintainability.Analyzers": "1.2.0-beta2",
          "Microsoft.QualityGuidelines.Analyzers": "1.2.0-beta2",
          "Roslyn.Diagnostics.Analyzers": "1.2.0-beta2",
          "System.Collections.Immutable.Analyzers": "1.2.0-beta2",
          "System.Runtime.Analyzers": "1.2.0-beta2",
          "System.Runtime.InteropServices.Analyzers": "1.2.0-beta2",
          "System.Threading.Tasks.Analyzers": "1.2.0-beta2"
        },
        "runtime": {
          "lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll": {}
        }
      },
```

If so, should I have referenced in a different way (it's just `<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="1.0.1" />`)?  Is that package spec'd incorrectly?  Or just a side-effect of using early release stuff?

VS version - Pro 2017 Preview, 15.3.0 Preview 3.0

**Comment by 333fred** [comment]
Yeah, that's the issue. The package appears to be incorrectly exposing the analyzer packages transitively. I opened https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/495 for that issue.

**Comment by 333fred** [comment]
@kierenj, looks like the 1.0.2 version of that package fixed the issue, see https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/272.

**Comment by kierenj** [comment]
Thanks very much for the help in tracking it down @333fred.   Should we meet I owe you a beer :beer:
