### ISSUE TITLE
New analyzer: DiagnosticDescriptor should specify helpLinkUri

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1270]
Most analyzers in [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) and [dotnet/roslyn](https://github.com/dotnet/roslyn) are missing critical user documentation in the form of a `helpLinkUri` passed to the `DiagnosticDescriptor`. A new analyzer should be created as part of the meta analyzers package which reports a diagnostic when users fail to provide this information.

:link: This issue relates to the automated enforcement of documentation bug #1269.

**Comment by mavasani** [comment]
This is a useful analyzer diagnostic that can go into Microsoft.CodeAnalysis.Analyzers package.
