### ISSUE TITLE
Seeing "An instance of analyzer Microsoft.NetFramework.CSharp.Analyzers.CSharpImplementSerializationMethodsCorrectlyAnalyzer cannot be created"

### ISSUE THREAD

**Issue by MrClyfar** [dotnet/roslyn-analyzers#1280]
**Environment**
Microsoft Visual Studio Professional 2017
Version 15.2 (26430.16) Release
VisualStudio.15.Release/15.2.0+26430.16
Microsoft .NET Framework
Version 4.7.02046

Microsoft Code Analysis 2017
Version 2.3.0.62003

**Symptom**
When building any solution/project, the "Error List" shows the following exception for many of the  "AD1000" warning rows

```
Warning	AD1000
An instance of analyzer Microsoft.NetFramework.CSharp.Analyzers.CSharpImplementSerializationMethodsCorrectlyAnalyzer cannot be created from C:\USERS\JASON\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_C721678C\EXTENSIONS\EKF4BSCF.4SO\Microsoft.NetFramework.CSharp.Analyzers.dll: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..			1	Active	Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
-----
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

There are some warnings which appear to be normal e.g.

```
Warning	CA1060
Move P/Invokes to native methods class
```

But there are much more of the "AD1000" warnings listed. I'm not sure why I'm getting an assembly load exception - is there something I need to install?

**Comment by 333fred** [comment]
Are you running our Analyzer extension or using our 2.3.0 analyzer packages? If so, it's not supported on VS 15.2, it's only supported on Update 3 or later, which is currently in preview.

**Comment by MrClyfar** [comment]
Yeah I'm running

Looking at NuGet, I can see things like

```
Microsoft.CodeAnalysis.FxCopAnalyzers v1.1.0
System.Runtime.Analyzers v1.1.0
Microsoft.AnalyzerPowerPack v1.1.0
```

I don't see anything v2.3.0 installed.

**Comment by 333fred** [comment]
Yes, that's correct. I'm going to close the issue, please feel free to ask any other questions or open a new issue if you see more problems after update 3.
