### ISSUE TITLE
The Microsoft.CodeQuality.Analyzers "more info" link is 404

### ISSUE THREAD

**Issue by LordMike** [dotnet/roslyn-analyzers#1285]
The More info link on the Readme for `Microsoft.CodeQuality.Analyzers` leads to a 404 page on Github.

#### Analyzer package
N/A

#### Analyzer
N/A

#### Repro steps
N/A

#### Expected behavior
N/A

#### Actual behavior
N/A

**Comment by mavasani** [comment]
We should fix this @jinujoseph

**Comment by mavasani** [comment]
Also check for links on other analyzer packages.

**Comment by mavasani** [comment]
Verified other hyperlinks are fine, just this one is broken.
