### ISSUE TITLE
Write on-boarding document for Roslyn-Analyzer Package 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1310]
https://github.com/dotnet/sdk/issues/1086 

mention 
https://stackoverflow.com/questions/45678861/whats-the-latest-version-of-roslyn-my-analyzer-can-target-if-i-support-vs2015/45680699#45680699

**Comment by mavasani** [comment]
@jinujoseph @kuhlenh Who should take this up?

**Comment by thebothead** [comment]
This ticket has not moved in a while.  Any updates here?

**Comment by thebothead** [comment]
For anyone waiting for this I found this article as well:
https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/

**Comment by mavasani** [comment]
@thebothead If you are looking for specific version of analyzer package to install for given VS version, please see https://github.com/dotnet/roslyn-analyzers/#recommended-version-of-analyzer-packages.

**Comment by jinujoseph** [comment]
cc @kuhlenh

**Comment by kuhlenh** [comment]
@mavasani do you have the final list of analyzers that we're having on-by-default?

**Comment by mavasani** [comment]
> do you have the final list of analyzers that we're having on-by-default?

NuGet or VSIX? We are not changing the defaults for NuGet (unless we get feedback about noise), but we should surely enable more in VSIX.

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2026
