### ISSUE TITLE
CA1822 falsely triggered on members that use dynamic objects.

### ISSUE THREAD

**Issue by jtemperv** [dotnet/roslyn-analyzers#1311]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers (v2.3.0-beta1)

#### Analyzer

MarkMembersAsStatic

#### Repro steps

See attached repro project: [RoslynAnalyzers.CA1822.ExpressionBodiedMembers.zip](https://github.com/dotnet/roslyn-analyzers/files/1362712/RoslynAnalyzers.CA1822.ExpressionBodiedMembers.zip)

#### Expected behavior
No CA1822 violation.

#### Actual behavior
A CA1822 violation is raised. The error does not appear in the Error List in Visual Studio 2017, but is reported in the Build Output window and the project build is cancelled with error:

> 1>...\RoslynAnalyzers.CA1822.ExpressionBodiedMembers\RoslynAnalyzers.CA1822.ExpressionBodiedMembers\ApplicationConfiguration.cs(15,23,15,60): error CA1822: Member ApplicationInsightsInstrumentationKey does not access instance data and can be marked as static (Shared in VisualBasic)

Probably caused by the dynamic object reference in the arguments of the invoked member.

**Comment by mavasani** [comment]
Likely fixed in latest bits, validate and close.

**Comment by 333fred** [comment]
Confirmed, this no longer repros.
