### ISSUE TITLE
Getting strange Analyzer errors in VS2017: string property 'not serializable'

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1312]
Ported from https://developercommunity.visualstudio.com/content/problem/105817/getting-strange-analyzer-errors-in-vs2017-string-p.html

----------------

Severity Code Description Project File Line Suppression State
Error AD0001 Analyzer 'Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer' threw an exception of type 'System.ArgumentException' with message 'Reported diagnostic with ID 'CA2235' is not supported by the analyzer.
Parameter name: diagnostic'. PermServer.Entities 1 Active

That failure seems to be the cause of this:

Severity Code Description Project File Line Suppression State
Error CA2235 Field ParameterValue is a member of type FileOpenInvalidQueryParameterException which is serializable but is of type string which is not serializable 

When is a string property 'not serializable'?

using VS 2017 Enterprise v 15.3.3

The exception class this is being flagged in has been used for years, analyzed without warnings in all prior versions of VS going back to at least 2010, maybe even 2008.

**Comment by mavasani** [comment]
We seem to be already handling this case: https://github.com/dotnet/roslyn-analyzers/blob/5d1759cee1cd38990cbf222b97ba46efbcf058e8/src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs#L268

Please try with the latest analyzer package on latest VS release: https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages

**Comment by RobinHSanner** [comment]
Funny how stuff that was closed out years ago just keeps popping up.  I'm getting this analyzer warning with the release version of .NET Core 3 and the latest analyzer.

**Comment by mavasani** [comment]
Can you please try with latest package: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.6?

**Comment by Slaviusz** [comment]
.NetCore 3.1.1, VS 2019, FxCopAnalyzers 2.9.8 (but also without) and still this message pops up as a warning for a solution when a class has [Serializable] attribure.

**Comment by thargy** [comment]
Also seeing this
