### ISSUE TITLE
Using Microsoft Code Analysis 2017 VSIX on TFS 2015 Build Agent?

### ISSUE THREAD

**Issue by k-vekos** [dotnet/roslyn-analyzers#1315]
If my team is using the Microsoft Code Analysis 2017 VSIX extension solution for code analysis (for our ASP .NET Core v2.0 project) how can we execute the code analysis and report findings when the solution is built from TFS 2015?

We are using an MSBuild build step for compilation as the Visual Studio Build step will not recognize VS2017 which is required for our solution.

**Comment by mavasani** [comment]
@k-vekos Microsoft Code Analysis 2017 VSIX extension is only meant for live analysis while typing in VS on VS2017.3. To enable execution of FxCopAnalyzers rules that are in this extension during a command line build you should use the FxCopAnalyzers nuget package. See https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages for further details on recommended package version to use for different VS/compiler version.
