### ISSUE TITLE
CA1825 AvoidZeroLengthArrayAllocationsFixer should not attempt to look for a variable declaration 

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1337]
#### Analyzer package

Microsoft.NetCore.Analyzers

#### Analyzer

AvoidZeroLengthArrayAllocationsFixer

#### Description

Cause of https://github.com/dotnet/roslyn-analyzers/issues/1298

The fixer should not assume that the `new int[0]` expression is being assigned in a variable declaration of some sort. e.g. It could be passed as an argument to a method call, be passed into an attribute, or used in an assignment that's not a declaration. The element type of the array should also be inferred from the expression itself even if there is a declaration present: in `object[] arr = new string[0]`, we want to replace it with `Array.Empty<string>()`, not `Array.Empty<object>()`.

**Comment by 333fred** [comment]
@jamesqo we don't need a separate issue for the cause of another issue, just putting the comment there and fixing is fine.
