### ISSUE TITLE
Ability to disable Code Analysis for some platform or TargetFramework

### ISSUE THREAD

**Issue by shibaev** [dotnet/roslyn-analyzers#1341]
Use attached multi-framework project:
[AnalyzeMultiTarget.zip](https://github.com/dotnet/roslyn-analyzers/files/1454449/AnalyzeMultiTarget.zip)

I want to run Code Analysis only for .NET 4.0 and in Release configuration. I tried different approaches:
1. Apply Condition for TargetFramework or Configuration to PackageReference in csproj. E.g.:
```
<ItemGroup Condition="'$(TargetFramework)'=='net40'">
  <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.3.0-beta1" />
</ItemGroup>
```
2. Apply Condition to CodeAnalysisRuleSet
3. Use `<RunCodeAnalysis>false</RunCodeAnalysis>` property like old version of Code Analysis.

Neither option work.

In our real project we target almost the same code base to 3 frameworks. And Code Analysis takes significant time even for one version. So we only need to to run Code Analysis in "Installer" configuration for the most complete version of code (for full .NET Framework).

**Comment by mavasani** [comment]
Adding @tmeschter for guidance on whether this can be accomplished with the new project system.

**Comment by shibaev** [comment]
Found one workaround (rather a hack) that partially works:
1. Use dummy ruleset to suppress all warnings by default. Provide real ruleset for Release and .NET 4.0. Like that:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net40</TargetFrameworks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    
    <CodeAnalysisRuleSet>DisableAllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet Condition="'$(TargetFramework)'=='net40'">AnalyzeMultiTarget.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.3.0-beta1" />
  </ItemGroup>
  
  <PropertyGroup>
    <Features>IOperation</Features>
  </PropertyGroup>
</Project>
```

2. Unfortunately, empty (all rules disabled) DisableAllRules.ruleset is ignored now. We need to explicitly list all rules to suppress. E.g. for demo application attached here:
```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="New Rule Set" Description=" " ToolsVersion="15.0">
  <Rules AnalyzerId="Microsoft.Analyzers.ManagedCodeAnalysis" RuleNamespace="Microsoft.Rules.Managed">
    <Rule Id="CA1707" Action="None" />
  </Rules>
</RuleSet>
```

With such trick CA errors are only reported for Release configuration and .NET 4.0 version. However, Code Analysis is still run for other versions, just ignores suppressed rules.

**Comment by tmeschter** [comment]
@shibaev Different `<CodeAnalysisRuleSet>` properties for different targets/platforms/configurations is how I would suggest you approach this.

I think the reason `DisableAllRules.ruleset` isn't disabling the rules is that you also have

```
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
<WarningsAsErrors />
```

So `DisableAllRules.ruleset` might turn everything off, and then `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` basically turns them back on as it is a general setting that applies to both the "built in" compiler diagnostics and the ones from analyzers.

Note that if all the rules for a particular diagnostic are suppressed, the diagnostic won't be run at all. @mavasani That's the still the way it works, right?

**Comment by mavasani** [comment]
> Note that if all the rules for a particular diagnostic are suppressed, the diagnostic won't be run at all. @mavasani That's the still the way it works, right?

Yes, that is correct. Thanks Tom!

**Comment by mavasani** [comment]
@shibaev Is this issue good to close now?

**Comment by shibaev** [comment]
I will check on our real project and let you know if it works.

Anyway, that cannot be a fundamental solution. Currently, I must put the following to DisableAllRules.ruleset:
```
<Rules AnalyzerId="Microsoft.Analyzers.ManagedCodeAnalysis" RuleNamespace="Microsoft.Rules.Managed">
    <Rule Id="CA1000" Action="None" />
    <Rule Id="CA1001" Action="None" />
     .... // a bunch or rules here
    <Rule Id="CA5122" Action="None" />
</Rules>
```
At some point you will add some new rule and that fragile project configuration will break - Code Analysis begin to run in all configuration.

That is strange why do you perform analysis when ruleset is empty:
```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="New Rule Set" Description=" " ToolsVersion="15.0" />
```

Ideally, need a simple way to completely disable analysis. E.g. if ruleset is absent or empty. Or if some csproj property (like "RunCodeAnalysis") is false.

**Comment by mavasani** [comment]
@shibaev Kindly file a separate feature request on https://github.com/dotnet/roslyn/issues. This issue is not related to analyzers in this repo.

**Comment by shibaev** [comment]
Ok, thank you for pointing me out.
