### ISSUE TITLE
Ability treat Code Analysis warnings as errors

### ISSUE THREAD

**Issue by shibaev** [dotnet/roslyn-analyzers#1342]
Microsoft.CodeAnalysis.FxCopAnalyzers - do we have ability to treat Code Analysis warnings as errors?
With old version of Code Analysis it was possible via <CodeAnalysisTreatWarningsAsErrors> option in csproj.

You can use attached project - Code Analysis warning does not fail build process.
[AnalyzeMultiTarget.zip](https://github.com/dotnet/roslyn-analyzers/files/1454475/AnalyzeMultiTarget.zip)

**Comment by mavasani** [comment]
Yes, you can do this by either specifying explicit severity for each ID in a ruleset OR use /warnaserror on compiler command line so all compiler and analyzer diagnostics are errors.

**Comment by mavasani** [comment]
You can also specify the MSBuild property `WarningsAsErrors` in project file, see https://msdn.microsoft.com/en-us/library/bb629394.aspx

**Comment by shibaev** [comment]
Thanks, sorry for bothering you with that issue. Forgot to set WarningsAsErrors option in demo project.
