### ISSUE TITLE
CA1707 (Identifiers should not contain underscores) Should not trigger on methods annotated as tests

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-analyzers#1354]
We should probably support at least the frameworks that live unit testing supports here. In the roslyn-analyzers repo, we hit 928 instances of this being flagged.

**Comment by mavasani** [comment]
In past the recommendation has always been to turn this off for test projects, but your suggestion seems like a good alternative to reduce noise.

**Comment by sharwell** [comment]
I think I prefer the approach of @mavasani here.

**Comment by mavasani** [comment]
Best approach here is for the test libraries/frameworks to write and ship DiagnosticSuppressors along with it to programattically suppress all false positives.
