### ISSUE TITLE
CA1801 (unused parameter) fired for obsolete property setter with stub implementation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1357]
This rule files for http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,245

```
        /// <summary>
        /// A set of strings designating experimental compiler features that are to be enabled.
        /// </summary>
        [Obsolete]
        protected internal ImmutableArray<string> Features
        {
            get
            {
                throw new NotImplementedException();
            }
            protected set
            {
                throw new NotImplementedException();
            }
        }
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1801	Parameter value of method set_Features is never used. Remove the parameter or use it in the method body.	CodeAnalysis	c:\roslyn\src\Compilers\Core\Portable\Compilation\CompilationOptions.cs	245	Active
```

Should we avoid flagging this case?

**Comment by 333fred** [comment]
I think we should. @sharwell, any opinion?

**Comment by sharwell** [comment]
I think it makes sense to avoid reporting a warning for methods that always throw `NotImplementedException` or `NotSupportedException`.

**Comment by sharwell** [comment]
💭 It might make sense to do a full pass and consider which warning never really make sense in `Obsolete` methods.

**Comment by 333fred** [comment]
Talked with @sharwell offline. He misread the intent of https://github.com/dotnet/roslyn-analyzers/issues/1220, so I'll resurrect that PR, which will fix this bug. Separately, we should look at other warnings on methods annotated with `Obsolete`.
