### ISSUE TITLE
CA1806 (Do not ignore method results) reports in tests verifiying exceptions

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1369]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

DoNotIgnoreMethodResultsAnalyzer: https://msdn.microsoft.com/en-us/library/ms182273.aspx

#### Repro steps

1. git clone https://github.com/JamesNK/Newtonsoft.Json
2. Install latest FxCopAnalyzers package https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.0-beta1-62315-01 to the solution
3. Open test source file `\Src\Newtonsoft.Json.Tests\Linq\JsonPath\JPathParseTests.cs` and verify bunch of CA1806 diagnostics reported for tests such as:

```
        [Test]
        public void BadCharactersInIndexer()
        {
            ExceptionAssert.Throws<JsonException>(() => { new JPath("Blah[[0]].Two.Three[1].Four"); }, @"Unexpected character while parsing path indexer: [");
        }

```

Note the report is correct, but I am wondering if we can handle the case of being inside a lambda passed to a method that verifies `Throws` for some exception type.

**Comment by mavasani** [comment]
@333fred @sharwell @jinujoseph @kuhlenh Thoughts? 

This is one of the rules that we turned on by default in our VSIX.

**Comment by sharwell** [comment]
I see two potential options:

1. Add `_ =` (a discard)
2. Suppress the warning for the last statement of a lambda passed to `ExceptionAssert.Throws` (NUnit), `Assert.Throws` (xUnit), or whatever MSTest offers for this

**Comment by mavasani** [comment]
Executed this on https://github.com/dotnet/project-system and almost all instances of this rule are for tests validating exceptions.

We either need to call this rule out as a non-test project rule (so disable via ruleset for test projects) OR avoid such false reports. I do not think it is acceptable to add in source suppressions for each of these violations, as they are just too many.

**Comment by sharwell** [comment]
@mavasani My option 2 would be an automatic suppression in the analyzer, no user action required.

**Comment by mavasani** [comment]
Ah, I misread it as requiring user suppression. I agree with option 2.

**Comment by 333fred** [comment]
Looks like MSTest doesn't have a method for this like x/NUnit, but instead has the `ExpectedException` annotation. I'll also support ignoring the last statement of a method if it has that annotation.
