### ISSUE TITLE
Fixer for CA1309 does not support FixAll

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1380]
#### Analyzer package

Microsoft.NetCore.Analyzers

#### Analyzer

UseOrdinalStringComparison.Fixer

#### Repro steps

![image](https://user-images.githubusercontent.com/10605811/32973167-ed60f16a-cbaa-11e7-88fe-0184a877b017.png)

**Comment by Evangelink** [comment]
Looks like a stale issue, the fixer is a `BatchFixer`.
