### ISSUE TITLE
Fixer for CA2231 has no FixAll support

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1381]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

OverloadOperatorEqualsOnOverridingValueTypeEquals.Fixer.cs

**Comment by Evangelink** [comment]
@mavasani I am not sure if adding multiple issues in the same code and setting `NumberOfFixAllIterations` to `1` is enough but if so then there is already a fix all for this rule (see the linked PR).

**Comment by mavasani** [comment]
Yep, seems support has been added now: https://github.com/dotnet/roslyn-analyzers/blob/9f12ebfd51403990c574d732ce1e4a5c31d8dc19/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/OverloadOperatorEqualsOnOverridingValueTypeEquals.Fixer.cs#L81
