### ISSUE TITLE
Audit all fixers in repo for missing FixAll support and add unit tests

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1382]
I found 2 cases where we have a code fix, but no FixAll support: https://github.com/dotnet/roslyn-analyzers/issues/1380 and https://github.com/dotnet/roslyn-analyzers/issues/1381. Additionally there are no FixAll unit tests in our repo. @ivanbasov is planning to add some FixAll test infrastructure support, and we should use that to ensure that we have FixAll tests for every single code fix that we ship.

**Comment by mavasani** [comment]
Tagging @jinujoseph @kuhlenh

**Comment by sharwell** [comment]
StyleCop Analyzers runs a Fix All test automatically for every code fix test.

**Comment by mavasani** [comment]
> StyleCop Analyzers runs a Fix All test automatically for every code fix test.

We should do that too..

**Comment by mavasani** [comment]
Found one more: https://github.com/dotnet/roslyn-analyzers/issues/1395

At this point, I am going to write an analyzer to warn when a CodeFixer does not override GetFixAllProvider.

**Comment by sharwell** [comment]
@mavasani Consider an exception in the analyzer has [`NoCodeFixAttribute`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/NoCodeFixAttribute.cs) applied to it.

**Comment by mavasani** [comment]
@sharwell I was planning to write an operation analyzer that fires if the fixer invokes RegisterCodeFix (or related) method, but does not override GetFixAllProvider.

**Comment by sharwell** [comment]
@mavasani 👍 That would even handle cases like this: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/90b322ac8b0ed6f4067c7a99e80cc834134ad54e/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/DocumentationRules/SA1649CodeFixProvider.cs#L27-L32

**Comment by mavasani** [comment]
Audit is done, we have an analyzer to detect missing FixAll support and https://github.com/dotnet/roslyn-analyzers/issues/1420 tracks adding unit tests.
