### ISSUE TITLE
Fix message for CA2222 to match FxCop

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1383]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

DoNotDecreaseInheritedMemberVisibilityAnalyzer 
#### Repro steps

This needs to be fixed: https://github.com/dotnet/roslyn-analyzers/blob/af8c297b65db728debfda84555a515298a3ee9ab/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx#L372

#### Expected behavior
Diagnostic message from FxCop: `Make {0} non-private, mark it as final, or seal its declaring type. This method was originally defined in base class '{1}'.`

#### Actual behavior
Diagnostic message: `Do not decrease inherited member visibility`

**Comment by mavasani** [comment]
Depends on our decision for https://github.com/dotnet/roslyn-analyzers/issues/1378

**Comment by 333fred** [comment]
CA2222 is being removed, tracking with https://github.com/dotnet/roslyn-analyzers/issues/1378.
