### ISSUE TITLE
Implement Async005: PropogateCancellationTokensWhenPossible

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1387]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

PropogateCancellationTokensWhenPossible

**Comment by jamesqo** [comment]
I am opening this issue since I would like to be the one to implement this. @333fred / @mavasani, can you please assign me?

**Comment by mavasani** [comment]
Async usage analyzers are no longer in the repo
