### ISSUE TITLE
PDB files are not loaded when debugging VSIX

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1389]
After merging the latest changes to `master`, I noticed that it's now possible to debug the VSIX that gets outputted. However, Visual Studio still isn't loading the appropriate debugging symbols, so none of the breakpoints I set are hit:

<img width="960" alt="no_symbols" src="https://user-images.githubusercontent.com/9159214/32994561-1a32ac00-cd37-11e7-8104-1d9e39c7564a.PNG">

**Comment by tmat** [comment]
Are the PDBs are included in the VSIX?

**Comment by tmat** [comment]
Actually, with the very latest master the PDBs should be embedded again.

**Comment by tmat** [comment]
@jamesqo Could you try again with the latest master? I made some changes that should address this.

**Comment by mavasani** [comment]
Closing this as per Tomas' comments above. @jamesqo kindly let us know if you are still facing this issue.

**Comment by jamesqo** [comment]
@tmat I'm still facing this problem after re-cloning the repo and doing a fresh build, unfortunately.

**Comment by 333fred** [comment]
@tmat? @jamesqo are you sure you're up to date? I know Tomas did fix a bug here, I've been able to debug since then.

**Comment by jamesqo** [comment]
@333fred Well, I've rebased and all so I'm pretty sure I have the latest bits. Do you know of a way to see what MSBuild is doing so I can look into the issue for myself?

**Comment by tmat** [comment]
Have you tried to delete your VS extension directory (```%USERPROFILE%\AppData\Local\Microsoft\VisualStudio\15.0_*RoslynDev```) before rebuilding?

This is what I see:
![image](https://user-images.githubusercontent.com/41759/33918961-00cce44c-df6b-11e7-9281-0f8c6085bca3.png)

```build -log``` produces a binary log to ```artifacts\debug\log```
