### ISSUE TITLE
CA1801 false reports for importing constructors

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1393]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

ReviewUnusedParameters

#### Repro steps

Project system repo has numerous importing constructors which have parameters just to ensure the corresponding objects get loaded. For example, see https://github.com/dotnet/project-system/blob/7257a618f673c798b214955d9baff11d5c2bcbb3/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/PropertyPages/ExecutableLaunchSettingsUIProvider.cs#L18. We should try to avoid such false reports.

**Comment by mavasani** [comment]
@jinujoseph @sharwell @333fred Thoughts?

**Comment by jinujoseph** [comment]
i agree

**Comment by sharwell** [comment]
I currently disagree. When I look at that method, the conclusion I arrive at is "this type is obviously more expensive than necessary for composition; removing the parameter will improve performance with no negative side effect since it isn't used."

**Comment by mavasani** [comment]
Adding @davkean for his view - I see this pattern very commonly used across CPS and project system code base.

**Comment by sharwell** [comment]
Outside of whatever CPS is doing, this is a case where CA1801's value goes beyond simply usage and actually can help users maintain a lean code base. I would expect CPS to need suppressions and documentation to explain these uses, since it's otherwise unclear to a reader.

**Comment by mavasani** [comment]
> I would expect CPS to need suppressions and documentation to explain these uses

@davkean Does this seem reasonable to you?

**Comment by jinujoseph** [comment]
i worry about the noise , and hence getting suppressed for all scenario.

**Comment by mavasani** [comment]
I personally feel presence of `[ImportingConstructor]` attribute is essentially conveying that I am importing this for a specific reason (one of which is for force loading the parameter objects), and forcing user to add suppression unnecessarily clutters the code.

**Comment by sharwell** [comment]
I would propose deferring this issue and see if it hits other projects. It (leaving it enabled with the current behavior) may prove to not be an issue after all.

**Comment by mavasani** [comment]
This is no longer an issue after https://github.com/dotnet/roslyn-analyzers/pull/2638 - users can use discard symbol names for such parameters.
