### ISSUE TITLE
CA1822 (Mark member as static) fires for almost every unit test

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1399]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

MarkMembersAsStaticAnalyzer

#### Repro steps

Open an unit test project which has unit test methods with [Fact] attribute.

#### Expected behavior
No CA1822.

#### Actual behavior
CA1822 for every single unit test

**Comment by mavasani** [comment]
This is causing extremely large number of false reports (80%+ of all CA diagnostics on project-system repo).

**Comment by mavasani** [comment]
We can consider calling this non-test project rule, but there are actual real violations in helper methods in test projects that this rule is able to report. I would prefer us taking a shot at reducing noise here.

**Comment by 333fred** [comment]
We took the approach of excluding unit tests from CA1806 in https://github.com/dotnet/roslyn-analyzers/issues/1369, we should do the same here.
