### ISSUE TITLE
CA2227 (Collection properties should be read only) needs a better message

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1401]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

Example: IdentifiersShouldNotMatchKeywords

#### Repro steps

See https://github.com/dotnet/roslyn-analyzers/blob/af8c297b65db728debfda84555a515298a3ee9ab/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx#L409

The message seems to match the title. We should fix it to be more descriptive and match the FxCop message:
```
Change '{0}' to be read-only by removing the property setter.
```

**Comment by jamesqo** [comment]
@mavasani I'll grab this.
