### ISSUE TITLE
Consider turning on CA1063 (Implement IDisposable Correctly) by default in both nuget and VSIX

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1407]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0-beta1-62322-01](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeQuality.Analyzers/2.6.0-beta1-62322-01)

#### Analyzer

ImplementIDisposableCorrectlyAnalyzer

#### Suggestion

I think the rule is very useful and @333fred has recently fixed bunch of issues in the implementation.

**Comment by mavasani** [comment]
I have a PR out for this: https://github.com/dotnet/roslyn-analyzers/pull/1463

**Comment by jinujoseph** [comment]
closed via https://github.com/dotnet/roslyn-analyzers/pull/1463
