### ISSUE TITLE
CA1823 warning disappears after navigation

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/roslyn-analyzers#1410]
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers

#### Analyzer

Avoid unused private fields

#### Repro steps

1. Open https://github.com/shadowsocks/shadowsocks-windows
2. Install analyzer package and enable CA1823. Build the project
3. Navigate the only CA1823 warning to line 106 in UnitTest.cs:        
 private static object locker = new object();
The warning is valid as a FAR doesn't pull up any other instances of locker.
#### Expected behavior
The warning stays.
#### Actual behavior
The warning disappeared either after navigating to the warning location or running a FAR to check if the warning was valid.

**Comment by mavasani** [comment]
@mattscheffer Thanks for filing the issues. Any issue where diagnostic disappears or is flaky in error list/editor is likely an underlying Roslyn bug. Kindly port them over to https://github.com/dotnet/roslyn/issues/

**Comment by mattscheffer** [comment]
@mavasani Gotcha, I'll port this and #1408 over there.
