### ISSUE TITLE
Update nameof analyzer to warn when passing a string that does not match any parameters in scope

### ISSUE THREAD

**Issue by chborl** [dotnet/roslyn-analyzers#1419]
#### Analyzer package
Microsoft.CodeQuality.Analyzers

#### Analyzer
UseNameofInPlaceOfString

#### Suggestion
Currently, the nameof analyzer is only triggered when the string literal that is passed to the `ParamName` parameter matches a parameter in scope.  In this case we can apply a fix because we know what the intended parameter is.  

For `ArgumentNullException` and `ArgumentException` methods, we should give a warning in the case where a string literal is passed to the `ParamName` parameter, but it does not match any parameters in scope.  We can't apply a fix because we don't know what the intended parameter is but it is highly likely this string is intended to match a parameter in scope.

**Comment by Evangelink** [comment]
Regarding the code fix for this, I think we could suggest the parameter tested in the enclosing if statement. Most of the time argument exception are used in a pattern like `if (condition on paramName) throw ArgumentXXXException(nameof(paramName));` (e.g. `if (paramName != null) throw ArgumentNullException(nameof(paramName));`).

**Comment by Evangelink** [comment]
@chborl I was looking at the available rules and I think that [ca2208](https://docs.microsoft.com/visualstudio/code-quality/ca2208) aleady does what you are asking for.

Also tagging @sharwell in case you were thinking of a different behavior?

**Comment by Evangelink** [comment]
I made some test and I confirm the rule is doing what was suggested.
