### ISSUE TITLE
Missing dependency on Microsoft.CodeAnalysis when upgrading Microsoft.CodeAnalysis.FxCopAnalyzers to v2.6.0-beta1

### ISSUE THREAD

**Issue by jherby2k** [dotnet/roslyn-analyzers#1425]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers , version [2.6.0-beta1]

#### Repro steps

Upgrade .NET Core 2.0 project from 2.3.0-beta1 to 2.6.0-beta1.

#### Expected behavior

Success

#### Actual behavior

Hundreds of warnings complaining about missing Microsoft.CodeAnalysis, Version=2.6.0.0. This package isn't identified as a dependency, wasn't used by 2.3.0-beta1 and AFAICT it doesn't target netstandard or netcore (tries to pull in a ton of unwanted dependencies if I add it).

**Comment by mavasani** [comment]
@jherby2k Thanks for the report. Which version of Visual Studio are you currently on? See the https://github.com/dotnet/roslyn-analyzers/blob/master/README.md#recommended-version-of-analyzer-packages for some guidance.

**Comment by jherby2k** [comment]
This is because I'm on an Visual Studio 2017 15.4.5 isn't it? I just read that advice. you can close it.

**Comment by mavasani** [comment]
Thanks!
