### ISSUE TITLE
Audit all FxCop ported analyzers to ensure FxCop compat with the analyzed API surface (private/protected/public)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1432]
#### Analyzer

OverrideMethodsOnComparableTypes, ImplementIDisposableCorrectly 

#### Expected behavior
Only fires on public API surface to match FxCop

#### Actual behavior
Fires even on internal types.

Given that lot of people have different opinions on whether FxCop behavior was correct or not, we should come up with list of rules that violate FxCop compat and discuss if they need to be fixed or retain the different behavior (for example Sam and I believe ImplementIDisposableCorrectly should run on entire API surface by default, even though FxCop only executed it on public API surface).

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-analysis

**Comment by mavasani** [comment]
Design rules to audit:

AbstractTypesShouldNotHaveConstructors
AssembliesShouldHaveValidStrongNames
AvoidEmptyInterfaces
AvoidExcessiveParametersOnGenericTypes
AvoidNamespacesWithFewTypes
AvoidOutParameters
CollectionsShouldImplementGenericInterface
ConsiderPassingBaseTypesAsParameters
DeclareEventHandlersCorrectly
DeclareTypesInNamespaces
DefaultParametersShouldNotBeUsed
DefineAccessorsForAttributeArguments
DesignIntrospectionRule
DesignRuleUtilities
DoNotCatchGeneralExceptionTypes
DoNotDeclareProtectedMembersInSealedTypes
DoNotDeclareStaticMembersOnGenericTypes
DoNotDeclareVirtualMembersInSealedTypes
DoNotDeclareVisibleInstanceFields
DoNotExposeCollectionsDesignedForInternalImplementation
DoNotHideBaseClassMethods
DoNotNestGenericTypesInMemberSignatures
DoNotOverloadOperatorEqualsOnReferenceTypes
DoNotPassTypesByReference
DoNotRaiseExceptionsInUnexpectedLocations
EnumeratorsShouldBeStronglyTyped
EnumsShouldHaveZeroValue
EnumStorageShouldBeInt32
ExceptionsShouldBePublic
GenericMethodsShouldProvideTypeParameter
GlobalSuppressions
ICollectionImplementationsHaveStronglyTypedMembers
ImplementIDisposableCorrectly
ImplementStandardExceptionConstructors
IndexersShouldNotBeMultidimensional
InterfaceMethodsShouldBeCallableByChildTypes
ListsAreStronglyTyped
MarkAssembliesWithAssemblyVersion
MarkAssembliesWithClsCompliant
MarkAssembliesWithComVisible
MarkAttributesWithAttributeUsage
MarkEnumsWithFlags
MembersShouldNotExposeCertainConcreteTypes
ModuleSuppressions
MovePInvokesToNativeMethodsClass
NestedTypesShouldNotBeVisible
OverloadOperatorEqualsOnOverloadingAddAndSubtract
OverrideMethodsOnComparableTypes
PropertiesShouldNotBeWriteOnly
ProvideObsoleteAttributeMessage
ReplaceRepetitiveArgumentsWithParamsArray
StaticHolderTypesShouldBeSealed
StaticHolderTypesShouldNotHaveConstructors
StringUriOverloadsCallSystemUriOverloads
TypesShouldNotExtendCertainBaseTypes
TypesThatOwnDisposableFieldsShouldBeDisposable
TypesThatOwnNativeResourcesShouldBeDisposable
UriParametersShouldNotBeStrings
UriPropertiesShouldNotBeStrings
UriReturnValuesShouldNotBeStrings
UseEventsWhereAppropriate
UseGenericEventHandlerInstances
UseGenericsWhereAppropriate
UseIntegralOrStringArgumentForIndexers
UsePropertiesWhereAppropriate
ValidateArgumentsOfPublicMethods

**Comment by mavasani** [comment]
@jinujoseph Seems like we have large number of ported analyzers not matching FxCop behavior (I have just analyzed design rules for now).

**Comment by mavasani** [comment]
I will file a separate issue for each case.

**Comment by heejaechang** [comment]
"ImplementIDisposableCorrectly should run on entire API surface by default"

wouldn't that be annoying? how about putting them as different rule? I use Dispose as RAII many time and don't want to make it complex for no reason.

**Comment by mavasani** [comment]
@heejaechang Agreed, and @davkean had the same request as yours. For now, I am going to switch it to match default FxCop behavior and open a separate issue to discuss if that needs to be changed.

We should also consider prioritizing AnalyzerOptions work so end users can configure this based on their preference.

**Comment by davkean** [comment]
Adding code to a product that is never used or called, just for the purpose of satisfying an FxCop rule wastes everyone's time.

**Comment by mavasani** [comment]
Usage rules to audit:

Rule Name |     FxCop |  Analyzer | Notes         |
-------------|-----------|-----------|--------------|
AttributeStringLiteralsShouldParseCorrectly | All | |
CallBaseClassMethodsOnISerializableTypes | All | |
CallGCSuppressFinalizeCorrectly | All | |
CollectionPropertiesShouldBeReadOnly | Public| |
DisposableFieldsShouldBeDisposed | All | |
DisposableTypesShouldDeclareFinalizer | All | |
DoNotCallOverridableMethodsInConstructors | All | |
DoNotDecreaseInheritedMemberVisibility | Non-Public | |
DoNotIgnoreMethodResults | All | |
DoNotMarkEnumsWithFlags | Public | |
DoNotMarkServicedComponentsWithWebMethod | All | |
DoNotRaiseExceptionsInExceptionClauses | All | |
DoNotRaiseReservedExceptionTypes | All | |
DoNotShipUnreleasedResourceFormats | All | |
FinalizersShouldBeProtected | All | |
FinalizersShouldCallBaseClassFinalizer | All | |
ImplementISerializableCorrectly | Public | |
ImplementSerializationConstructors | Public | |
ImplementSerializationMethodsCorrectly | All | |
InitializeLocalsBeforeUse | All | |
InitializeValueTypeStaticFieldsInline | All | |
InstantiateArgumentExceptionsCorrectly | All | |
LiteralsShouldBeSpelledCorrectly | All | |
MarkAllNonSerializableFields | All | |
MarkISerializableTypesWithSerializable | All | |
MarkWindowsFormsEntryPointsWithStaThread | All | |
MembersShouldDifferByMoreThanReturnType | Public | |
NonConstantFieldsShouldNotBeVisible | Public | |
OperationsShouldNotOverflow | Public | |
OperatorOverloadsHaveNamedAlternates | Public | |
OperatorsShouldHaveSymmetricalOverloads | Public | |
OverloadOperatorEqualsOnOverridingValueTypeEquals | Public | |
OverrideEqualsOnOverloadingOperatorEquals | All | |
OverrideGetHashCodeOnOverridingEquals | All | |
PassSystemUriObjectsInsteadOfStrings | Public | |
ProvideDeserializationMethodsForOptionalFields | All | |
RethrowToPreserveStackDetails | All | |
ReviewUnusedParameters | All | |
TestForNaNCorrectly | All | |
UsageRuleUtilities | All | |
UseManagedEquivalentsOfWin32Api | All | |
UseParamsForVariableArguments | Public | |

**Comment by mavasani** [comment]
Performance rules to audit:

Rule Name |     FxCop |  Analyzer | Notes         |
-------------|-----------|-----------|--------------|
AvoidExcessiveLocals | All | |
AvoidUncalledPrivateCode | Non-Externally Visible | |
AvoidUninstantiatedInternalClasses | Non-Externally Visible | |
AvoidUnsealedAttributes | All | |
AvoidUnusedPrivateFields | Non-Externally Visible | |
DoNotCastUnnecessarily | All | |
InitializeReferenceTypeStaticFieldsInline | All | |
MarkAssembliesWithNeutralResourcesLanguage | All | |
MarkMembersAsStatic | All | |
OverrideEqualsAndOperatorEqualsOnValueTypes | Externally Visible | |
PreferJaggedArraysOverMultidimensional | All | |
PropertiesShouldNotReturnArrays | Externally Visible| |
RemoveEmptyFinalizers | All | |
RemoveUnusedLocals | All | |
TestForEmptyStringsUsingStringLength | All | |
UseLiteralsWhereAppropriate | Non-Externally Visible | |

**Comment by mavasani** [comment]
Maintainability rules to audit:

Rule Name |     FxCop |  Analyzer | Notes         |
-------------|-----------|-----------|--------------|

AvoidExcessiveClassCoupling | All | Not Ported |
AvoidExcessiveComplexity | All | Not Ported |
AvoidExcessiveInheritance | All | Not Ported |
AvoidUnmaintainableCode | All | Not Ported |
ReviewMisleadingFieldNames | All | Not Ported |
VariableNamesShouldNotMatchFieldNames | All | Not Ported |

**Comment by mavasani** [comment]
**Globalization Rules:** All FxCop rules and analyzers operate on executable code, hence are not relevant for this audit.

**Comment by mavasani** [comment]
**Security rules**:

Rule Name |     FxCop |  Analyzer | Notes         |
-------------|-----------|-----------|--------------|
AptcaMethodsShouldOnlyCallAptcaMethods | All | Not Ported |
AptcaTypesShouldOnlyExtendAptcaBaseTypes | Externally Visible | Not Ported |
ArrayFieldsShouldNotBeReadOnly | Externally Visible | Not Ported |
CallGCKeepAliveWhenUsingNativeResources | All | Not Ported |
CatchNonClsCompliantExceptionsInGeneralHandlers | All | Not Ported |
DoNotDeclareReadOnlyMutableReferenceTypes | Externally Visible | Not Ported |
DoNotIndirectlyExposeMethodsWithLinkDemands | All | Not Ported |
MethodSecurityShouldBeASupersetOfType | All | Not Ported |
PointersShouldNotBeVisible | Externally Visible | Not Ported |
ReviewDeclarativeSecurityOnValueTypes | All | Not Ported |
ReviewDenyAndPermitOnlyUsage | All | Not Ported |
ReviewImperativeSecurity | All | Not Ported |
ReviewSuppressUnmanagedCodeSecurityUsage | All | Not Ported |
ReviewVisibleEventHandlers | Externally Visible | Not Ported |
SealMethodsThatSatisfyPrivateInterfaces | Externally Visible | Externally Visible |
SecureAsserts | All | Not Ported |
SecuredTypesShouldNotExposeFields | All | Not Ported |
SecureSerializationConstructors | All | Not Ported |
StaticConstructorsShouldBePrivate | All | Not Ported |
TypeLinkDemandsRequireInheritanceDemands | Externally Visible | Not Ported |
WrapVulnerableFinallyClausesInOuterTry | All | Not Ported |

**Comment by mavasani** [comment]
**Interoperability rules**:

Rule Name |     FxCop |  Analyzer | Notes         |
-------------|-----------|-----------|--------------|
AutoLayoutTypesShouldNotBeComVisible | Externally Visible | Not Ported |
AvoidInt64ArgumentsForVB6Clients | Externally Visible | Not Ported |
AvoidNonPublicFieldsInComVisibleValueTypes | Externally Visible | Not Ported |
AvoidOverloadsInComVisibleInterfaces | Externally Visible | Not Ported |
AvoidStaticMembersInComVisibleTypes | All | Not Ported |
CallGetLastErrorImmediatelyAfterPInvoke | All | Not Ported |
ComRegistrationMethodsShouldBeMatched | All | Not Ported |
ComRegistrationMethodsShouldNotBeVisible | Externally Visible | Not Ported |
ComVisibleTypeBaseTypesShouldBeComVisible | Externally Visible | Not Ported |
ComVisibleTypesShouldBeCreatable | Externally Visible | Not Ported |
DeclarePinvokesCorrectly | All | Not Ported |
DoNotUseAutoDualClassInterfaceType | Externally Visible | Not Ported |
MarkBooleanPInvokeArgumentsWithMarshalAs | All | Not Ported |
MarkComSourceInterfacesAsIDispatch | All | Not Ported |
PInvokeEntryPointsShouldExist | All | Not Ported |
PInvokesShouldNotBeVisible | Externally Visible | Externally Visible |

**Comment by mavasani** [comment]
**Naming rules**:

Rule Name |     FxCop |  Analyzer | Notes         |
-------------|-----------|-----------|--------------|
BaseCompoundWordRule | All |  |
CompoundWordsShouldBeCasedCorrectly | Externally Visible |  |
DoNotNameEnumValuesReserved | Externally Visible |  |
DoNotPrefixEnumValuesWithTypeName | Externally Visible |  |
EventsShouldNotHaveBeforeOrAfterPrefix | Externally Visible |  |
FlagsEnumsShouldHavePluralNames | Externally Visible |  |
IdentifiersShouldBeCasedCorrectly | All |  |
IdentifiersShouldBeSpelledCorrectly | Externally Visible |  |
IdentifiersShouldDifferByMoreThanCase | Externally Visible |  |
IdentifiersShouldHaveCorrectPrefix | Externally Visible  |   |
IdentifiersShouldHaveCorrectSuffix | Externally Visible  |   |
IdentifiersShouldNotContainTypeNames | Externally Visible  |   |
IdentifiersShouldNotContainUnderscores | Externally Visible  |   |
IdentifiersShouldNotHaveIncorrectPrefix | Externally Visible  |   |
IdentifiersShouldNotHaveIncorrectSuffix | Externally Visible  |   |
IdentifiersShouldNotMatchKeywords | Externally Visible |   |
OnlyFlagsEnumsShouldHavePluralNames | Externally Visible |  |
ParameterNamesShouldMatchBaseDeclaration | Externally Visible |  |
ParameterNamesShouldNotMatchMemberNames | Externally Visible |  |
PropertyNamesShouldNotMatchGetMethods | Externally Visible |  |
ResourceStringCompoundWordsShouldBeCasedCorrectly | Externally Visible |  |
ResourceStringsShouldBeSpelledCorrectly | All |  |
TypeNamesShouldNotMatchNamespaces | Externally Visible |  |
UsePreferredTerms | All |  |

**Comment by mavasani** [comment]
All the FxCop rules and corresponding analyzers have now been audited and the last PR to fix the naming analyzers is https://github.com/dotnet/roslyn-analyzers/pull/1448.

**Comment by mavasani** [comment]
This is now done.
