### ISSUE TITLE
InvalidCastException in AvoidUninstantiatedInternalClassesAnalyzer

### ISSUE THREAD

**Issue by ADWILS-MSFT** [dotnet/roslyn-analyzers#1447]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0-beta1](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0-beta1)

#### Analyzer

AvoidUninstantiatedInternalClassesAnalyzer

#### Repro steps

Add an Uninstantiated Internal class.

#### Expected behavior

Produces warning/error.

#### Actual behavior

15>CSC : error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.Maintainability.AvoidUninstantiatedInternalClassesAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceMethodTypeParameterSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'.

Encountered on Beta 1 and tried the daily Beta 2, both exhibited the behavior.

**Comment by mletterle** [comment]
Also getting this for `Microsoft.CodeQuality.Analyzers.Maintainability.ReviewUnusedParametersAnalyzer`
