### ISSUE TITLE
2.6.0-beta2 issue: CS8032 - Cannot create an abstract class warning

### ISSUE THREAD

**Issue by jherby2k** [dotnet/roslyn-analyzers#1456]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.0-beta2]

#### Analyzer

CS8032	An instance of analyzer Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.AvoidEmptyInterfacesAnalyzer cannot be created from <package_path>\microsoft.codequality.analyzers\2.6.0-beta2\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll: Cannot create an abstract class.

#### Repro steps

1. Update .NET standard 2.0 projects from 2.6.0-beta1 to 2.6.0-beta2
2. Observe above error

#### Expected behavior
no warnings (and these projects do not contain any empty interfaces, FYI)

#### Actual behavior
An instance of analyzer Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.AvoidEmptyInterfacesAnalyzer cannot be created from <package_path>\microsoft.codequality.analyzers\2.6.0-beta2\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll: Cannot create an abstract class.

**Comment by mavasani** [comment]
@jherby2k [AvoidEmtyInterfacesAnalyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/AvoidEmptyInterfaces.cs#L16) is a sealed class, but was an [abstract class](https://github.com/dotnet/roslyn-analyzers/commit/560f1793a787883d426d03a05ea4219e3f0e7b95#diff-3893d9c18e1287d72e8b053f9f036200) in 2.6.0-beta1. Seems like you have some older bits. Can you try git clean, restore and restart VS?

**Comment by jherby2k** [comment]
That was not a smooth upgrade, but yes – after removing all my bin and obj folders and clearing the nuget cache for good measure, then restarting VS… issues resolved. You can close this. Thanks.

Sent from Mail for Windows 10

**Comment by mavasani** [comment]
@jherby2k Thank you!
