### ISSUE TITLE
Write unit tests for new implementation of Async analyzers / port old tests

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1460]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

AsyncXXX analyzers

#### Description

I've been implementing the Async005 analyzer in my spare time over the last couple of weeks. I noticed it's a bit brain-consuming to interleave between writing the analyzer / adding unit tests for it. I think that it'll be easier for me to write the tests for each analyzer first in order to specify how it works, then implement it, instead of trying to do both at the same time.

**Comment by mavasani** [comment]
Async usage analyzers are no longer maintained in this repo.
