### ISSUE TITLE
Assign CA range IDs and category to Async analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1465]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0-beta2](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0-beta2)

#### Analyzer

Bunch of them with RuleID = "Async00X". We need to assign them a proper category and range ID when they are implemented.

**Comment by mavasani** [comment]
Also remove the source suppressions added to the repo of the following form (these will be added in a soon to be sent PR):

```
#pragma warning disable RS1018 // DiagnosticId for analyzers must be in specified format. https://github.com/dotnet/roslyn-analyzers/issues/1465
```

**Comment by jamesqo** [comment]
@mavasani I would like for this issue to be resolved so my PRs that implement some Async analyzers can move forward. As a question, what is the criteria for determining whether a set analyzers get their own ID range? Also, do the ID numbers carry any significance, or do you just assign the next available range to new analyzers?

Is there anything wrong with the [existing categories](https://github.com/dotnet/roslyn-analyzers/blob/569bd373a4831d3035597197e02980b57602a7f2/src/Unfactored/AsyncPackage/AsyncPackage.md) the Async analyzers have?

**Comment by mavasani** [comment]
@jamesqo We probably don't want to introduce a new `Library` category, you can use `Design` for now. Also please use IDs in the range for each category, instead of `AsyncXXX`: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/DiagnosticCategoryAndIdRanges.txt

**Comment by mavasani** [comment]
Async usage analyzers no longer in the repo
