### ISSUE TITLE
Determine if AvoidDuplicateElementInitiailization should apply to VB

### ISSUE THREAD

**Issue by evildour** [dotnet/roslyn-analyzers#1469]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

AvoidDuplicateElementInitiailization

Currently it only applies to C#. Determine whether it should be used with VB as well. It really depends on whether object initializers support setting indexed properties in VB (this is an open question from https://github.com/dotnet/roslyn-analyzers/pull/1142).

**Comment by mavasani** [comment]
Marking this as Won't fix until we get user requests.
