### ISSUE TITLE
Async005 analyzer: Avoid firing on uninitialized CancellationToken locals/parameters in scope

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1476]
#### Analyzer

PropagateCancellationTokensWhenPossible

#### Description

We need to call `SemanticModel.AnalyzeDataFlow` and use the relevant properties off the returned `DataFlowAnalysis` to determine whether the local/parameter we're examining is uninitialized. If it's uninitialized, don't offer a codefix with it as that will result in a compiler error.

Enable the test cases [here]() and [here]() and fix the analyzer accordingly. The method that should be changed for the fix is `IsUsableCancellationToken`.

**Comment by mavasani** [comment]
Async usage analyzers are no longer in this repo.
