### ISSUE TITLE
Implement analyzers from Unfactored/AsyncPackage

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1477]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

This is an umbrella issue I'm opening for all of the Async analyzers that need to be ported to use the new IOperation APIs, in order to link to them from the tests.

@mavasani I saw in a different issue that you're planning to rename the IDs of the Async analyzers. What will be their new IDs?

- [ ] Async001
- [ ] Async002
- [ ] Async003
- [ ] Async004
- [ ] Async005
- [ ] Async006

**Comment by mavasani** [comment]
> I saw in a different issue that you're planning to rename the IDs of the Async analyzers. What will be their new IDs?

We should decide the IDs before enabling these rules.

**Comment by mavasani** [comment]
@srivatsn @jinujoseph @dotnet/roslyn-analysis I do not have any context/history on these rules - does anyone know when we designed these async rules? Are there any design notes? I just see the rule titles at https://github.com/dotnet/roslyn-analyzers/blob/master/src/Unfactored/AsyncPackage/AsyncPackage.md, but could not find any further documentationon these.
@jamesqo We need more clarity on the design before we start writing tests/implementing these rules.

**Comment by sharwell** [comment]
:memo: [DotNetAnalyzers/AsyncUsageAnalyzers](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers) has some initial work on the subject.

**Comment by mavasani** [comment]
Async usage analyzers have been removed from this repo.
