### ISSUE TITLE
[Proposal] Async005-like meta analyzer: Propagate CancellationTokens off of contexts

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1481]
#### Analyzer package

Microsoft.CodeAnalysis.Analyzers

#### Analyzer

PropagateCancellationTokensOffOfContextWhenPossible (proposed name)

#### Description

Roslyn provides different contexts to an analyzer as it analyzes various things, e.g. `OperationAC`, `SymbolAC`, `SyntaxNodeAC`. Each of these contexts has a `CancellationToken` property that the developer is expected to feed to any CancellationToken-accepting methods. We should create an analyzer similar to Async005 (PropagateCancellationTokensWhenPossible) that detects when such a context is in scope, and fires if a CancellationToken-accepting method is not provided a token.

**Comment by mavasani** [comment]
Async package analyzers have been removed from the repo.

**Comment by thomaslevesque** [comment]
> Async package analyzers have been removed from the repo.

So where are they now? Are they still maintained somewhere? I need Async005, but I can't find it anywhere...
