### ISSUE TITLE
Should the IOperation-based Async003/004 analyzers be merged?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1482]
/cc @333fred, @mavasani 

I noticed that in the original implementation, the Async003/004 diagnostics were both handled by the same analyzer: https://github.com/dotnet/roslyn-analyzers/blob/6ff9c17d8fc05fae8b1c48b7a4d25b1e080f0b97/src/Unfactored/AsyncPackage/AsyncPackage/AsyncLambdaAnalyzer.cs. Is there any reason that for the IOperation-based analyzer skeletons, they have been separated into two different analyzers? Since they share a lot of logic, it seems reasonable to keep them under one analyzer.

**Comment by mavasani** [comment]
Stale analyzers, not in the repo anymore...
