### ISSUE TITLE
[Proposal] Warn when a variable is null-checked after it is known not to be null

### ISSUE THREAD

**Issue by jamesqo** [dotnet/roslyn-analyzers#1488]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

DoNotNullCheckNonNullVariable (proposed name)

#### Description

When a variable that is known to be non-null is checked for null, issue a warning at the site of the null check. e.g.

```cs
public void M(string s)
{
    if (s == null) {
        throw new ArgumentNullException(nameof(s));
    }

    int i1 = s != null ? s.Length : 0; // warning
    int i2 = s?.Length ?? 0; // warning
}
```

#### Things to consider

- Whether particular methods should be specially recognized when analyzing nullness. e.g. `string.IsNullOrEmpty(s)` or helper classes that check for null, `Requires.NotNull(s, nameof(s))`

**Comment by mavasani** [comment]
Should be addressed with https://github.com/dotnet/roslyn-analyzers/pull/1637
