### ISSUE TITLE
CA1010 should analyze IDictionary as well

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-analyzers#1490]
Currently, CA1010 only reports on IList, ICollection, and IEnumerable implementations missing the generic version. We should also look into reporting on dictionary types as well. The original FxCop implementation disregards dictionary types "to reduce noise", http://index/?query=CollectionsShouldImplemen&rightProject=DesignRules&file=CollectionsShouldImplementGenericInterface.cs&line=24, but we should investigate if this will actually make the analyzer more noisy.

**Comment by jamesqo** [comment]
I'd be glad to take on this issue.

> we should investigate if this will actually make the analyzer more noisy.

How would we test that? Is there a reference codebase we run these analyzers on (e.g. Roslyn)

**Comment by 333fred** [comment]
We generally run the analyzers over large codebases. 2 that we use regularly are roslyn and json.net.

**Comment by mavasani** [comment]
We can possibly add an editorconfig option to enable configuration of types for which this should be flagged.

**Comment by Evangelink** [comment]
@mavasani are you thinking about a switch option or a list of extra types to check for (this could include user defined types)?
