### ISSUE TITLE
CA1068 shouldn't fire on extensions methods of CancellationToken

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#1491]
#### Analyzer

CA1068 

#### Repro steps

1. See: https://github.com/dotnet/project-system/pull/3060/files/cf65d664b047803252fba07115fcd6244db30531#diff-ecae52b00e17f99d88602b6fbfe7cb74R35

``` C#

internal static CancellationTokenRegistration Register(this CancellationToken token, string foobar)
{
}

```

#### Expected behavior

Not to fire

#### Actual behavior

Fires

**Comment by sharwell** [comment]
👍

**Comment by jamesqo** [comment]
Seems like this will be an easy fix; I can grab this.
