### ISSUE TITLE
.net core code metrics

### ISSUE THREAD

**Issue by livarcocc** [dotnet/roslyn-analyzers#1499]
_From @EncoderPtd on December 13, 2017 4:3_

As we know there's a useful function for .net projects:
Analyze -> Calculate Code Metrics
It can give out some detailed information of the project.

May i ask if it is now supported for .net core projects? I can't find it. :)
Which repository should this issue be placed in?

_Copied from original issue: dotnet/cli#8228_

**Comment by livarcocc** [comment]
Is this a Code Metric supported in VS?

@jinujoseph is this supported by analyzers?

**Comment by livarcocc** [comment]
_From @EncoderPtd on December 13, 2017 4:50_

Yeah, it's in VS, provides calculation of code lines and some code relation analysis.

**Comment by mavasani** [comment]
Code metrics is a feature implemented on legacy FXCop Introspection engine. Making CodeMetrics work for .net core projects would require the FXCop assembly resolution to work these assemblies. Unless we are planning to add special analyzers that implement similar analysis as code metrics engine (which might probably be lesser work, but still is non-trivial).

**Comment by nenadvicentic** [comment]
Hi! Is there any update on this feature? Or alternative solution?

**Comment by mavasani** [comment]
We are currently investigating adding this support in Dev16.0 P1. I will keep this issue updated with any new information.

**Comment by mavasani** [comment]
Fixed with an internal checkin. This support should be available in Dev16 Preview1.

**Comment by eluchsinger** [comment]
@mavasani so what do I need to do to use this?

**Comment by mavasani** [comment]
@eluchsinger You will need to wait for the first public preview of Dev16 before you can get this support in VS.

**Comment by mavasani** [comment]
@eluchsinger Alternatively, you can use our ported `Metrics.exe` command line tool to generate an xml code metrics report. See https://developercommunity.visualstudio.com/solutions/305903/view.html for details.
