### ISSUE TITLE
Microsoft CodeAnalysis OOM Exception

### ISSUE THREAD

**Issue by chillryan** [dotnet/roslyn-analyzers#1503]
I've reported this issue through the visual studio feedback tool [see link](https://developercommunity.visualstudio.com/content/problem/174842/visual-studio-155-crashes-when-switching-git-branc.html) but figured I'd try my chances posting here.

I'm using the Code Analysis 2017 extension for VS 2017 15.5. In looking at the stack trace, I can only assume that since the extension is running inside the devenv process, when its analysis a loaded solution, it hits the OOM. 

Since I've hit this situation a very frequent basis, I've disabled solution analysis for C# projects hoping that will help. I'll report back here if there are any changes or comment on the visual studio feedback link posted prior.

**Comment by mavasani** [comment]
Thanks @chillryan. Issue has been ported to https://github.com/dotnet/roslyn/issues/24055
