### ISSUE TITLE
Roslyn Public API analyzer tool passes invalid configuration

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/roslyn-analyzers#1506]
In this PR: https://github.com/dotnet/roslyn/pull/24023

A few changes were made to rename an API. Thus adding `*REMOVED*` entries in the `Unshipped.txt` file, and adding new entries for the new API. To guard against breaking compatibility, the removed APIs were added again to source.

I expected the tool to fail, as the `Unshipped.txt` file has `*REMOVED*` entries that still exists in source, but the tool didn't. It was passing and jenkins was green. The tool should be modified to handle this case.

**Comment by Evangelink** [comment]
Could you please confirm that the intent of this ticket is to create a new rule in `DeclarePublicApiAnalyzer` that will report a diagnostic on all members declared as removed in the api files but are still present in the code?
