### ISSUE TITLE
CA1820 incorrectly fires in LINQ expressions

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn-analyzers#1508]
#### Analyzer package

Microsoft Code Analysis, version 2.6.0.6241303

#### Analyzer

CA1820

#### Repro steps

Consider the following program:

    using System.Linq;

    class C
    {
        void M(IQueryable<string> strings)
        {
            var q = from s in strings
                    where s == ""
                    select s;
        }
    }

#### Expected behavior

CA1820 is not raised. Indeed, the comparison to `""` happens in a LINQ expression.

#### Actual behavior

CA1820 is raised:

    Test for empty strings using 'string.Length' property or 'string.IsNullOrEmpty' method instead of an Equality check.	
    Comparing strings by using the String.Length property or the String.IsNullOrEmpty method is significantly faster than using Equals.

Given that the comparison happens in a LINQ expression, there is no way to tell if using string.Length will be faster or not. In fact, it is very much possible that the LINQ provider will not be able to translate a comparison to String.Length.

Note that [U2U1100](https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1100.md) from the [U2U Consult Performance Analyzers for C# 7](https://marketplace.visualstudio.com/items?itemName=vs-publisher-363830.U2UConsultPerformanceCodeAnalyzersforC7) does not have this problem.

**Comment by Evangelink** [comment]
@mavasani Do you think that's overkill to exclude all cases where the parent is a query syntax or a query method? Doing so all queries, even on simple collections, will start to ignore the issue. This could be tweaked by checking that the left type is `IQueryable`. WDYT?

**Comment by KrisVandermotten** [comment]
This is not about `IQueryable<T>`, nor about query syntax, but rather about [expression trees](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/).
