### ISSUE TITLE
CA1003 false positive and bad message

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn-analyzers#1509]
#### Analyzer package

Microsoft Code Analysis, version 2.6.0.6241303

#### Analyzer

CA1003

#### Repro steps

Create a WPF project. In there, add the following class:

    using System.Windows;

    public class Example : UIElement
    {
        public static readonly RoutedEvent ExpandedEvent = EventManager.RegisterRoutedEvent(
            "Expanded", RoutingStrategy.Bubble, typeof(RoutedEventHandler), typeof(Example));

        public event RoutedEventHandler Expanded
        {
            add { AddHandler(ExpandedEvent, value); }
            remove { RemoveHandler(ExpandedEvent, value); }
        }
    }

#### Expected behaviour

No diagnostics are reported.

#### Actual behaviour

A diagnostics is reported on the `Expanded` identifier, with description `Remove {0} and replace its usage with EventHandler<T>`

Note that there are two problems here:
- a diagnostic should not be reported, as there is absolutely nothing the developer can do to avoid the diagnostic (other than suppress it)
- the message contains `{0}`

**Comment by mavasani** [comment]
Adding @sharwell @333fred as this seems to be very similar to https://github.com/dotnet/roslyn-analyzers/issues/1325 and [this comment](https://github.com/dotnet/roslyn-analyzers/issues/1325#issuecomment-345441878) from Sam clarifies our stance - `RoutedEventHandler` is not a generic event handler and hence doesn't follow recommended guidelines. You should suppress this diagnostic if you feel there is no alternate implementation for you that follows the guidelines.

I will send a PR to fix the second issue: `the message contains {0}`

**Comment by KrisVandermotten** [comment]
I thought the guideline was not to create new types for event handlers, but to use `EventHandler<T>` instead of creating new types. Here however, we are not creating a new type, we are using an existing one.

That is also what makes this different from #1325. There a new type is created (that violates a guideline).

[The documentation for CA1003](https://docs.microsoft.com/nl-be/visualstudio/code-quality/ca1003-use-generic-event-handler-instances) seems to be clear. From the example:

    // This delegate violates the rule.
    public delegate void CustomEventHandler(object sender, CustomEventArgs e);

    public class CustomEventArgs : EventArgs
    {
        public string info = "data";
    }

In my example, no delegate type was defined. A fortiori, I did not define a delegate that violates a rule.

The fix in #1515 is wrong. In my original example, it will create a diagnostic on the event with a message that says `Remove Expanded and replace its usage with EventHandler<T>`. That makes absolutely no sense.

In the example from the CA1003 documentation however, a diagnostic should be reported on `CustomEventHandler`, with the message saying `Remove CustomEventHandler and replace its usage with EventHandler<T>`. That makes sense.

**Comment by mavasani** [comment]
@KrisVandermotten You are absolutely correct, our analyzer implementation seems to be incorrect and does not match the documentation. I also double checked the legacy FxCop implementation and the analyzer only flags explicit delegate declarations, not event symbols itself. I will update the PR to fix the analyzer to match the documentation and legacy FxCop behavior

**Comment by mavasani** [comment]
I looked further at the history of this analyzer and verified this analyzer got added with https://github.com/dotnet/roslyn-analyzers/pull/830. We tried to combine CA1003 and CA1009 (which fires for incorrect signature of delegate used as an event handler), which probably led to incorrect implementation. I will clean this up, thanks @KrisVandermotten

**Comment by mavasani** [comment]
@KrisVandermotten I have a PR out to fix this: https://github.com/dotnet/roslyn-analyzers/pull/1517. I verified the diagnostic is no longer reported for your repro.
