### ISSUE TITLE
CA1822 should not fire for methods used in delegate constructors

### ISSUE THREAD

**Issue by KrisVandermotten** [dotnet/roslyn-analyzers#1511]
#### Analyzer VSIX

Microsoft Code Analysis, version 2.6.0.6241303

#### Analyzer

CA1822

#### Repro steps

Consider this code:

    public sealed class MyAnalyzer : DiagnosticAnalyzer
    {
        public override void Initialize(AnalysisContext context)
        {
            context.RegisterSyntaxNodeAction(AnalyzeForEachStatement,
                ImmutableArray.Create(SyntaxKind.ForEachStatement));
        }

        private void AnalyzeForEachStatement(SyntaxNodeAnalysisContext context)
        {
        }
    }

#### Expected behavior

No CA1822 is reported.

#### Actual behavior

CA1822 is reported. The messages says:

> Member AnalyzeForEachStatement does not access instance data and can be marked as static (Shared in VisualBasic)
> Members that do not access instance data or call instance methods can be marked as static (Shared in Visual Basic). After you mark the methods as static, the compiler will emit nonvirtual call sites to these members. This can give you a measurable performance gain for performance-sensitive code.

This is simply not true. The compiler will not emit any call, because there are no call sites. More importantly, making the method static will significantly reduce the performance of the call. For more information and a benchmark, see [U2U1003](https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1003.md).

**Comment by KrisVandermotten** [comment]
> so whether they are instance or not, nonvirtual calls are emitted.

Actually, the C# compiler does emit a `callvirt` instruction when calling instance methods because of the implied null check, if the method is called. In my example, there is no call site. The only calls to the method are through the delegate.

> Are you implying that instance members should be preferred to static members because of this?

Yes, if and only if they are called through delegates.

Consider this method:

    static IEnumerable<int> Filter(IEnumerable<int> source) => source.Where(i => i > 6);

The compiler will generate a method for the lambda `i => i > 6`. This will be an instance method, for performance reasons, even though it could easily be static. When executed on - say - a very long int[], the performance difference is significant.

Why would that be any different if we choose to give that method a name?

> I doubt method calls contribute significant overhead to most programs.

I would agree, for most programs, but according to that argument, CA1822 should not exist, at least not in the Performance category. But it exists, so it better be correct.

**Comment by jamesqo** [comment]
> Actually, the C# compiler does emit a callvirt instruction when calling instance methods because of the implied null check, if the method is called. In my example, there is no call site. The only calls to the method are through the delegate.

IIRC `callvirt` doesn't necessarily mean a virtual call. I can't find where I read that, but quoting from https://blogs.msdn.microsoft.com/ericgu/2008/07/02/why-does-c-always-use-callvirt/:

> Peter Golde did some testing to see what the perf impact was of always using callvirt, and it was small enough that we decided to make the change. 

> When executed on - say - a very long int[], the performance difference is significant.

If you are executing it on a very long `int[]` then you should be writing a manual for-loop?

> CA1822 should not exist, at least not in the Performance category.

OK, then maybe it should be moved to a different category like Maintainability.

**Comment by KrisVandermotten** [comment]
> IIRC callvirt doesn't necessarily mean a virtual call.

Indeed, it does not. I never said it did. But we're on a tangent. The point is that the message claims that making this method static will improve performance, were in fact it is just the opposite.

> OK, then maybe it should be moved to a different category like Maintainability.

Then people will make the change because Microsoft said it's Good for Maintainability. Is it? But again, that's a tangent.

The point is that making a method static is good for performance, if the method is not called though a delegate, but bad for performance when it is.

**Comment by KrisVandermotten** [comment]
See also [Code generation differences compared to previous compilers](https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CodeGen%20Differences.md) in the Roslyn documentation:

> non-lifting Lambda expressions are now implemented as an instance methods on singleton display classes. Since the entry point to the delegate is the instance "Invoke" method, it is cheaper at runtime to dispatch delegate invocations to the underlying implementing method if such method is also an instance method with exactly same formal signature as "Invoke".
