### ISSUE TITLE
Following Getting Started doesn't work

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/roslyn-analyzers#1531]
Following the steps described in the Getting Stared section of https://github.com/dotnet/roslyn-analyzers/blob/master/README.md doesn´t work.
Namely: `msbuild RoslynAnalyzers.sln`, `cibuild.cmd`, and `msbuild BuildAndTest.proj`

The output of running `msbuild RoslynAnalyzers.sln` can be seen here: https://gist.github.com/alfredmyers/4b93a27af706a3a1a70ce2bcbe3b9456

**Comment by 333fred** [comment]
@alfredmyers thanks for letting us know, the instructions are out of date. I'll submit a PR to update shortly, but for now just run `build.cmd` from the command line and it should build just fine.

**Comment by alfredmyers** [comment]
Running `build.cmd` results in:

```
C:\Code\GitHub\dotnet\roslyn-analyzers>build
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Users\v-algary\.nuget\packages\RoslynTools.RepoToolset\1.0.0-beta-62503-02\tools\Build.proj
```

**Comment by 333fred** [comment]
@tmat?

**Comment by tmat** [comment]
You need to run `restore` before `build`. I have updated the doc:

https://github.com/dotnet/roslyn-analyzers/pull/1536/commits/5da5d19f6a0739074d20e7bf05393e5769fbbc75

**Comment by tmat** [comment]
Actually I'm mistaken. Restore is done by ```build``` automatically.

**Comment by 333fred** [comment]
@alfredmyers can you try cleaning the repo and your nuget cache and trying again? Running `build` is working for me.

**Comment by alfredmyers** [comment]
My knowledge of NuGet is kind of limited, so I'm probably doing something wrong. But I resolved the issue downloading the nuget package manually and copying its folder contents to `%USERPROFILE%\.nuget\packages\RoslynTools.RepoToolset\1.0.0-beta-62503-02\`
