### ISSUE TITLE
VSTS build fails after updating to 2.6.0

### ISSUE THREAD

**Issue by johnweeder** [dotnet/roslyn-analyzers#1533]
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers, version 2.6.0(https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

Updated nuget from 1.1.0 to 2.6.0 in a C# .NET Framework 4.6.1 class library project. 

VSTS builds now fail with the following errors.

#### Repro steps

1. Create C# .NET Framework 4.6.1 assembly with Microsoft.AspNetCore.Mvc 2.0.0 nuget. (which will indirectly include Razor and then Code Analysis).
2. Create VSTS build
3. Attempt build... fails.

These are the full set of packages in my assembly.

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FluentValidation" version="7.3.4" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Antiforgery" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Authentication.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Authentication.Core" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Authorization" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Authorization.Policy" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Cors" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Cryptography.Internal" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.DataProtection" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.DataProtection.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Diagnostics.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Hosting.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Hosting.Server.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Html.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Extensions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Http.Features" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.JsonPatch" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Localization" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Abstractions" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.ApiExplorer" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Core" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Cors" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.DataAnnotations" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Formatters.Json" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Localization" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Razor" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.Razor.Extensions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.RazorPages" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.TagHelpers" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Mvc.ViewFeatures" version="2.0.2" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Razor" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Razor.Language" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Razor.Runtime" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.ResponseCaching.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Routing" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.Routing.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.StaticFiles" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.AspNetCore.WebUtilities" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Analyzers" version="1.1.0" targetFramework="net461" developmentDependency="true" />
  <package id="Microsoft.CodeAnalysis.Common" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.CSharp" version="2.6.1" targetFramework="net461" />
  <package id="Microsoft.CodeAnalysis.Razor" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.CSharp" version="4.4.1" targetFramework="net461" />
  <package id="Microsoft.DotNet.PlatformAbstractions" version="2.0.4" targetFramework="net461" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Caching.Memory" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Configuration.Json" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.DependencyModel" version="2.0.4" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Composite" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Embedded" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Hosting.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Localization" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Localization.Abstractions" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.ObjectPool" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Options" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.Primitives" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Extensions.WebEncoders" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.Net.Http.Headers" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.NETCore.Platforms" version="2.0.1" targetFramework="net461" />
  <package id="Microsoft.Win32.Registry" version="4.4.0" targetFramework="net461" />
  <package id="NETStandard.Library" version="2.0.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net461" />
  <package id="Newtonsoft.Json.Bson" version="1.0.1" targetFramework="net461" />
  <package id="Swashbuckle.AspNetCore.Swagger" version="1.1.0" targetFramework="net461" />
  <package id="Swashbuckle.AspNetCore.SwaggerGen" version="1.1.0" targetFramework="net461" />
  <package id="Swashbuckle.AspNetCore.SwaggerUI" version="1.1.0" targetFramework="net461" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net461" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net461" />
  <package id="System.Collections" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net461" />
  <package id="System.Collections.Immutable" version="1.4.0" targetFramework="net461" />
  <package id="System.ComponentModel.Annotations" version="4.4.1" targetFramework="net461" />
  <package id="System.Console" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.4.1" targetFramework="net461" />
  <package id="System.Diagnostics.FileVersionInfo" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.StackTrace" version="4.3.0" targetFramework="net461" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net461" />
  <package id="System.Dynamic.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net461" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq" version="4.3.0" targetFramework="net461" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net461" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="net461" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net461" />
  <package id="System.Reflection.Metadata" version="1.5.0" targetFramework="net461" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.4.0" targetFramework="net461" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net461" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.AccessControl" version="4.4.1" targetFramework="net461" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net461" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net461" />
  <package id="System.Security.Cryptography.Xml" version="4.4.1" targetFramework="net461" />
  <package id="System.Security.Principal.Windows" version="4.4.1" targetFramework="net461" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encoding.CodePages" version="4.4.0" targetFramework="net461" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net461" />
  <package id="System.Text.Encodings.Web" version="4.4.0" targetFramework="net461" />
  <package id="System.Threading" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Parallel" version="4.3.0" targetFramework="net461" />
  <package id="System.Threading.Thread" version="4.3.0" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.4.0" targetFramework="net461" />
  <package id="System.Xml.ReaderWriter" version="4.3.1" targetFramework="net461" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XPath" version="4.3.0" targetFramework="net461" />
  <package id="System.Xml.XPath.XDocument" version="4.3.0" targetFramework="net461" />
</packages>

#### Expected behavior
Clean build

#### Actual behavior
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerAttributeAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticDescriptorCreationAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.Analyzers.FixAnalyzers.FixerWithFixAllAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.Analyzers.InternalImplementationOnlyAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpReportDiagnosticAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerFieldsAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpRegisterActionAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC (0, 0)
CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer cannot be created from d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by mavasani** [comment]
@johnweeder Which version of VS or compiler toolset are you using? Please choose the analyzer package version as per https://github.com/dotnet/roslyn-analyzers/#recommended-version-of-analyzer-packages

**Comment by mavasani** [comment]
Kindly re-activate if you are seeing this issue on 2.6.0 analyzer packages on VS 2017.5 RTW or later.

**Comment by johnweeder** [comment]
This issue does **NOT** arise on my local development machine running 15.5.4.
This issue **DOES** arise on VSTS builds.

1) I do NOT have codeanalysis enabled 
2) Something attempts to load this assembly anyway during the build (d:\a\1\s\packages\Microsoft.CodeAnalysis.Analyzers.2.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll : Could not load file or assembly...) and 
3) The build is loading from the **PACKAGES** folder instead of from the build tools.

(https://github.com/dotnet/roslyn-analyzers/files/1643953/CsProjAndPackagesConfig.zip)
[CsProjAndPackagesConfig.zip]

Please note that I am not even using Code Analysis during the builds. It is disabled in all assemblies.

This error only happens, apparently, because the assembly being built includes (indirectly via MVC) the 2.6.0 Microsoft.CodeQuality.Analyzers as a nuget. Only this particular assembly fails. All others build. If I revert to the 1.x version, the VSTS build works again.

**Comment by mavasani** [comment]
@johnweeder Can you try to add a NuGet package reference to https://www.nuget.org/packages/Microsoft.Net.Compilers/2.6.1 to your project? This will ensure that the compiler toolset used to build your project will always be the same, regardless of what VS or VSTS build is installed.

**Comment by johnweeder** [comment]
I will try this. Please give me an hour or so. I am at lunch right now.

**Comment by johnweeder** [comment]
@mavasani Adding the Microsoft.Net.Compiler 2.6.0 resolved the issue on VSTS. Thank you.

**Comment by mavasani** [comment]
@Mattacks You cannot get best of both the worlds here. You can either configure your project to use a fixed compiler toolset or always use the compiler toolset that comes along with compiler/VS installed in the box. If you want to make sure that all the developers on the repo are always building the project with the **same** compiler toolset, you should take the former approach. If you want to always dogfood the latest version of the compiler toolset, you need to request all the developers on the repo to use a compiler/VS version which is **equals or higher** then the version of compiler APIs that the analyzer package was built against. So, for example, if your project references version 2.6.0 of FxCop analyzers package, you need to make sure that development on your repo happens on VS 15.5 or later (VS15.5 has compiler version 2.6).

**Comment by appcoreopc** [comment]
awesome! works for me.
