### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by ActionJ4ckson** [dotnet/roslyn-analyzers#1548]
Hey folks

I am unable to install the VSIX extension on Visual Studio Community 2017 v15.4.0. Am I missing anything?  

Microsoft Code Analysis 2017, version [2.6.0.6241303]
(https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2017)

![untitled](https://user-images.githubusercontent.com/27288270/35266417-4cb7d8ea-0049-11e8-944c-3e9fb02584eb.png)

Error Log:
23-Jan-18 2:18:12 PM - Searching for applicable products...
23-Jan-18 2:18:12 PM - Found installed product - Global Location
23-Jan-18 2:18:12 PM - Found installed product - ssms
23-Jan-18 2:18:12 PM - Found installed product - Visual Studio Community 2017
23-Jan-18 2:18:12 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

Thanks in advance
AJ

**Comment by 333fred** [comment]
@ActionJ4ckson, you must have 15.5 or greater for the extension to be installable.

**Comment by ActionJ4ckson** [comment]
@333fred Ahh I see. Thanks buddy.
