### ISSUE TITLE
CA1024 False-positive when class implements IXmlSerializable

### ISSUE THREAD

**Issue by x3ntrix** [dotnet/roslyn-analyzers#1551]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

CA1024: Use properties where appropriate

#### Repro steps

Create a class that implements IXmlSerializable:

    public class Example : IXmlSerializable
    {
        public XmlSchema GetSchema()
        {
            return null;
        }

        public void ReadXml(XmlReader reader) {...}

        public void WriteXml(XmlWriter writer) {...}
    }

#### Expected behavior

No warning is shown for GetSchema(). 

#### Actual behavior

A warning is shown for GetSchema().

When the method declaration comes from an interface, maybe it would make sense to show this warning only in the interface and never in the implementing classes. This would solve this issue and potentially similar issues. If user has a reason to use a method instead of a property, he would just need to suppress the warning once in the interface and not in all implementations.

**Comment by sharwell** [comment]
The general approach used in StyleCop Analyzers is to report the diagnostic only on the original definition.

* It seems obvious that methods with `override` should not ever report CA1024
* It seems reasonable that methods implementing an interface method should not report CA1024
