### ISSUE TITLE
Is the testing framework something that can be packaged up

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/roslyn-analyzers#1574]
As a general question, the code used to test the analyzers in this repo would really valuable to people writing their own analyzers as a framework to test their analyzers. 

Is there a way this can be packaged up and reused? Right now there are some internal methods that are not available for use outside of this repo.

**Comment by mavasani** [comment]
@hvanbakel Thank you for the feedback. This is surely something valuable, but I am not sure how early we can deliver this. If you want this delivered soon, please feel free to pick this up and submit a PR. Thanks!

**Comment by dnperfors** [comment]
Any advice on how this has to be done?
I was looking at the other projects, but they are analysers, so this isn't going to work for the test.utilities.

I was thinking about creating a Test.Utilities.Package project that adds the Roslyn.Test.Utilities.dll to a nuget package. But instead of adding it to the 'analysers' target directory, it should go to the 'lib' target directory.

**Comment by sharwell** [comment]
@dnperfors I would strongly encourage starting with the test framework in StyleCop Analyzers over the one here. We've made a tremendous number of bug fixes and usability improvements in it.

**Comment by JohanLarsson** [comment]
There is also [Gu.Roslyn.Asserts](https://www.nuget.org/packages/Gu.Roslyn.Asserts/)

**Comment by mavasani** [comment]
@hvanbakel @dnperfors As mentioned by others, there are multiple different analyzer projects, which are good starting point/references for such work. I personally feel such a test utilities package belongs in the Roslyn repo. Any new Microsoft.CodeAnalysis features or public APIs that get added in future will automatically get test infrastructure support when unit tests are added in Roslyn, and the test package is most likely to be in sync most of the time with least maintenance overhead. Feel free to open an issue in [Roslyn repo](https://github.com/dotnet/roslyn/issues/new) to start discussion around this.

**Comment by sharwell** [comment]
@JohanLarsson your repo is in our list of references for future stabilization of a better test infrastructure. It definitely cleans up some things that we missed in StyleCop Analyzers.

**Comment by mavasani** [comment]
We now have `Microsoft.CodeAnalysis.Testing` NuGet package for this.
