### ISSUE TITLE
Analyze exceptional code paths in CA2000 (dispose objects before losing scope)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1580]
Initial implementation will not report diagnostics if disposable objects are not disposed on exceptional code path. We should fix this once we move to compiler's CFG.

**Comment by mavasani** [comment]
@Bartolomeus-649 - Can you please state your repro steps? Did you explicit add a NuGet package reference to `Microsoft.CodeAnalysis.FxCopAnalyzers` or `Microsoft.CodeQuality.Analyzers.Exp` OR executed _"Run Code Analysis"_, i.e. legacy binary FxCop? I believe we should be handling the repro you mentioned in https://developercommunity.visualstudio.com/content/problem/210774/code-analysis-warning-ca2000-triggers-for-dynamic.html in our analyzer NuGet package. If not, I would track this issue with a different issue on this repo.

**Comment by Bartolomeus-649** [comment]
I just selected to run/use "Microsoft all rules" from the project settings -> Code Analysis, and then "Run code analysis" from the "Analyze" menu in Visual Studio Pro (15.5.7).

**Comment by mavasani** [comment]
@Bartolomeus-649 - that is legacy FxCop based CodeAnalysis. Can you instead try executing the analysis by adding a NuGet package reference to https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.1-beta1-62706-01 and then doing a "Build"? Don't execute "Run Code Analysis" after adding the above NuGet package - executing the build should invoke the necessary analysis while building itself.

**Comment by Bartolomeus-649** [comment]
Seem to solve the problem, but it triggers for async methods returning disposable objects.
Also it seem to be project-based, and I can't find any way to config it once for the entire solution

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/2162, available in 2.9.x package
