### ISSUE TITLE
Fix CA1822 (Mark member as static) instances in RoslynAnalyzers.sln - there are 300+ instances

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1584]
Disable via our ruleset, enable once these violations are fixed.

**Comment by mavasani** [comment]
Lot of these seem to be in non-shipping projects. I am going to attempt to fix these in shipping projects.

**Comment by mavasani** [comment]
Closing this out as this rule is not important to enable for non-shipping/test projects.

**Comment by sharwell** [comment]
I fixed these locally but the changes depend on #1612 so I'm waiting to submit it separately.
