### ISSUE TITLE
Meta-analyzer to recommend users to configure generated code analysis and enable concurrent execution

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1592]
#### Analyzer package

Microsoft.CodeAnalysis.Analyzers

#### Analyzer

I propose that the analyzer should have 2 rules:
1. Recommend explicit invocation of `AnalysisContext.ConfigureGeneratedCodeAnalysis` in the `Initialize` method. This rule should be enabled by default.
2. Recommend enabling concurrent execution with `AnalysisContext.EnableConcurrentExecution` in the `Initialize` method. This rule should probably be disabled by default to reduce noise for beginners. Authors who understand the consequences/requirements for enabling it can enforce it on their projects.

We should also have code fixes with FixAll support for these rules.

**Comment by reduckted** [comment]
Has this already been done? I'm getting analyzer warnings about these things, which I assume comes from here:

* https://github.com/dotnet/roslyn-analyzers/blob/7ad9f725f22c7f5a9e8f70a5ebe6e5fd4c14d8d6/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/ConfigureGeneratedCodeAnalysisAnalyzer.cs
* https://github.com/dotnet/roslyn-analyzers/blob/7ad9f725f22c7f5a9e8f70a5ebe6e5fd4c14d8d6/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/EnableConcurrentExecutionAnalyzer.cs

**Comment by sharwell** [comment]
This was fixed by https://github.com/dotnet/roslyn-analyzers/pull/2346
