### ISSUE TITLE
Update docs.microsoft.com documentation for CA2213 (DisposableFieldsShouldBeDisposed)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1593]
FxCop implementation for this rule reported CA2213 only for those fields which were assigned a locally created disposable object within the containing type methods/initializers. This reduced noise for cases where the containing type did not own the dispose responsibility for certain disposable fields. We are matching this implementation in porting this rule to the analyzer.

We need to update https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed to explicitly state this in the rule description.

**Comment by mavasani** [comment]
@jinujoseph - can we get the docs team to do this?

**Comment by jinujoseph** [comment]
@BillWagner  , can you help here pls

**Comment by gewarren** [comment]
That is my topic so I'll update it.

BTW there is a link at the bottom of all the Visual Studio docs where you can enter GitHub issues against the docs - that would be a better place to log the issue in the future.

**Comment by mavasani** [comment]
I see the note has already been added. Closing this issue...
