### ISSUE TITLE
Remove workaround in AnalysisEntityFactory for a possible IOperation bug

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1602]
See unit test `MemberReferenceInQueryFromClause_Disposed_NoDiagnostic` (added with https://github.com/dotnet/roslyn-analyzers/pull/1600/commits/84627cea7805f4999f071d37fe21b73a69141ccf)

```
using System;
using System.Collections.Immutable;
using System.Linq;

class A : IDisposable
{
    public void Dispose()
    {
        throw new NotImplementedException();
    }
}

class B: IDisposable
{
    public C C { get; }
    public void Dispose()
    {
        throw new NotImplementedException();
    }
}

class C
{
    public ImmutableArray<A> ArrayOfA { get; }
}

class Test
{
    void M1(ImmutableArray<B> arrayOfB)
    {
        var x = from b in arrayOfB
            from a in b.C.ArrayOfA
            select a;
        var y = new A();
        y.Dispose();
    }
}
```

IOperation for `b` in `from a in b.C.ArrayOfA` has `OperationKind.None` with no children and null type. This seems incorrect. A workaround has been added to `AnalysisEntityFactory`.

This issue tracks:
1. Filing a corresponding bug in Roslyn, after confirming it is indeed a bug.
2. Remove the workaround in `AnalysisEntityFactory` after we move to Roslyn bits with the fix.

**Comment by mavasani** [comment]
Tagging @AlekseyTs - I will try to create a minimal IOperation unit test for this and file a bug in Roslyn.

**Comment by Evangelink** [comment]
@mavasani what's the status on this ticket?
