### ISSUE TITLE
Deploying to RoslynDev breaks integration tests for dotnet/roslyn

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1619]
This repository needs to deploy to an experimental instance not named `RoslynDev`, or it interferes with integration tests in dotnet/roslyn (by reporting warnings that are not otherwise reported during the editing experience).

https://github.com/dotnet/roslyn-analyzers/blob/05d3235976278fdf4861db255985d2154fff9975/Directory.Build.props#L31

**Comment by Evangelink** [comment]
Is there still something to do here? If so can we use any name for the new instance?

Tagging @sharwell

**Comment by mavasani** [comment]
I have not seen any concerns reported by any developers about this, so I am fine to not do anything here.
