### ISSUE TITLE
List of rules not yet ported from VS Code Analysis (FxCop)?

### ISSUE THREAD

**Issue by Gav-Brown** [dotnet/roslyn-analyzers#1624]
Hi, Is there a list of the rules which have not yet been ported from Visual Studio Code Analysis to FxCopAnalyzers.2.6.0?

I've compiled this list:

Important:

CA1049: Types that own native resources should be disposable
CA2100: Review SQL queries for security vulnerabilities
CA2213: Disposable fields should be disposed
CA2218: Override GetHashCode on overriding Equals
CA2220: Finalizers should call base class finalizer
CA2221: Finalizers should be protected
CA2224: Override equals on overloading operator equals

Nice to have:

CA1031: Do not catch general exception types
CA1800: Do not cast unnecessarily
CA1804: Remove unused locals
CA1811: Avoid uncalled private code

Others:

CA1002
CA1004
CA1005
CA1006
CA1007
CA1009
CA1011
CA1013
CA1020
CA1021
CA1023
CA1025
CA1026
CA1035
CA1038
CA1039
CA1045
CA1046
CA1047
CA1048
CA1053
CA1057
CA1059
CA1062
CA1302
CA1303
CA1400
CA1402
CA1403
CA1404
CA1405
CA1406
CA1407
CA1408
CA1409
CA1410
CA1411
CA1412
CA1413
CA1415
CA1501
CA1502
CA1504
CA1505
CA1506
CA1600
CA1700
CA1701
CA1702
CA1703
CA1709
CA1712
CA1713
CA1719
CA1722
CA1809
CA1900
CA1901
CA1903
CA2003
CA2004
CA2006
CA2102
CA2103
CA2104
CA2105
CA2106
CA2107
CA2108
CA2111
CA2112
CA2114
CA2115
CA2116
CA2117
CA2118
CA2120
CA2121
CA2122
CA2123
CA2124
CA2126
CA2130
CA2131
CA2132
CA2133
CA2134
CA2135
CA2136
CA2137
CA2138
CA2139
CA2140
CA2141
CA2142
CA2143
CA2144
CA2145
CA2146
CA2147
CA2149
CA2151
CA2202
CA2204
CA2210
CA2223
CA2228
CA2230
CA2233
CA5122

**Comment by 333fred** [comment]
You can search the issues in this repo for the `FxCop-Port` label, https://github.com/dotnet/roslyn-analyzers/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AFxCop-Port. Those issues that are labeled `Needs-Fixer` have had the rule itself ported, but don't have a quick-fix created. Issues that are just labeled `FxCop-Port` still need to be ported in their entirety.

**Comment by jinujoseph** [comment]
yes and some reference to old documents here https://github.com/dotnet/roslyn-analyzers/tree/master/docs/FxCopPort

**Comment by Gav-Brown** [comment]
@333fred Thanks for the description of the labels. Very useful to know.
@jinujoseph Thanks for the pointer to the docs. It would be nice to update RulesInventory.csv to show the state of each rule but agree the label search works well.
Cheers
