### ISSUE TITLE
Audit usages of ISymbolExtensions.IsImplementationOfInterfaceMember

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1627]
See https://github.com/dotnet/roslyn-analyzers/issues/1625, where we intended to invoke `ISymbolExtensions.IsOverrideOrImplementationOfInterfaceMember` to check if a given symbol implements an interface member or overrides an implementation of an interface member, but instead invoked `ISymbolExtensions.IsImplementationOfInterfaceMember`. We need to check if any direct or transitive calls to `ISymbolExtensions.IsImplementationOfInterfaceMember` are intentional or not.

**Comment by Evangelink** [comment]
@mavasani It seems that there are only 3 usages of `IsImplementationOfInterfaceMember` and they all seem good. Could you double check (it should be quick)?

**Comment by Evangelink** [comment]
ping @mavasani

**Comment by mavasani** [comment]
Yep, I agree with your assessment.
