### ISSUE TITLE
How to create custom rules with CodeAnalysis on DotNet Core project

### ISSUE THREAD

**Issue by SebEic** [dotnet/roslyn-analyzers#1636]
Sorry, I'm not sure to be in the right place to ask...
I'm trying to find a way to do some custom rules with CodeAnalysis on DotNet Core project.

I know that we can do it on Framework 4.6. Currently, I've all of my rules on DLL and in my ruleset file:

<RuleHintPaths>
   <Path>%ProgramFiles(x86)%\eic\Visual Studio 2015\CodeAnalysis</Path>
   <Path>%ProgramFiles%\eic\Visual Studio 2015\CodeAnalysis</Path>
</RuleHintPaths>

I've tried to find some tutorials to do it but I can only find tuto for Framework 4.6.

I also tried to run the FxCopCmd.exe on my .Net Core DLL. I get the error message "Unable to identify the platform..."
The same command on DLL with Framework 4.6 works fine.

Is there an issue between CodeAnalysis and .NET Core Project ?
May be someone has some sample to share...

**Comment by yingfangdu** [comment]
In fact, I am able to create a customized rule and make it as a nuget package, and deploy it in a target framework Net 4.5.2 project. It runs perfectly.

While now I am curious how it works as the Microsoft.codeAnalysis 2.0 and above only supports 4.6 target framework.

Note: I use VS 2017.

**Comment by SebEic** [comment]
Yes, deployed a customized rule in a target framework Net 4.5.2 works fine. But have you tried to deploy it in a target .Net Core 2.0? 
On my side, I can't.
I've tried to use the fxCopCmd like this:
/f:SomeAssembly.dll /r:"C:\Rules Directory\SomeRules.dll" /o:OutputFile.xml

It works fine on target framework 4.X.X but again when I tried on target .Net Core 2.0, I get an error: unable to identify the platform of the DLL.

My goal is to create custom rules in DLL so that I can do what we do in framework 4.X: 
```
<RuleHintPaths>
   <Path>%ProgramFiles(x86)%\eic\Visual Studio 2017\CodeAnalysis</Path>
</RuleHintPaths>
```

**Comment by mavasani** [comment]
@SebEic FxCopCmd is not supported on .NetCore/.NetStandard projects. You should add a NuGet package reference to https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/ and then edit your project file to add the following property to set your msbuild project file:

```
<PropertyGroup>
   <CodeAnalysisRuleSet>MyRules.ruleset</CodeAnalysisRuleSet>
</PropertyGroup>
```

Executing a project build in Visual Studio or msbuild command line will invoke the analyzers along with the build, and they will respect your ruleset preferences. Please re-open the issue if you are still blocked.
