### ISSUE TITLE
Cannot get the correct type info of ObservableCollection

### ISSUE THREAD

**Issue by yingfangdu** [dotnet/roslyn-analyzers#1645]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.7.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.7.0)

#### Analyzer

Example: 
GetTypeInfo of ObservableCollection type

#### Expected behavior
The result shows ErrorType.

#### Actual behavior
It should show the correct type.

**Comment by yingfangdu** [comment]
![capture](https://user-images.githubusercontent.com/9310605/37935321-e40020b2-3105-11e8-8dbe-939c63608731.PNG)

**Comment by mavasani** [comment]
This issue is not related to the analyzer packages. You can probably start by filing an issue on https://github.com/dotnet/roslyn/issues/new if you are still hitting this.
