### ISSUE TITLE
Public API checker does not distinguish properties from methods

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-analyzers#1651]
_From @gafter on June 9, 2015 23:8_

The public API checker does not distinguish between

``` cs
public int Foo { get; }
```

and

``` cs
public int get_Foo();
```

even though this affects (compile-time) clients.

_Copied from original issue: dotnet/roslyn#3407_

**Comment by jinujoseph** [comment]
_From @jasonmalinowski on March 29, 2018 23:15_

@mavasani Should we move this to roslyn-analyzers somewhere?

**Comment by jinujoseph** [comment]
_From @mavasani on March 29, 2018 23:16_

Yes, we should port it to roslyn-analyzers.

**Comment by Evangelink** [comment]
@mavasani Is it still a relevant issue? Looking at the content of https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.AnalyzerUtilities/PublicAPI.Unshipped.txt#L4 it seems that there is a distinction between methods and properties.

**Comment by mavasani** [comment]
Yes, closing this issue - seems to be a stale one.
