### ISSUE TITLE
CA1711 incorrectly reports type names ending with "Dictionary" that inherit from IDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by pakdev** [dotnet/roslyn-analyzers#1656]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

IdentifiersShouldNotHaveIncorrectSuffixAnalyzer

#### Repro steps

1. Create a type like the following: `public class MyGenericDictionary : IDictionary<string, string>`
2. Observe CA1711 diagnostic

#### Expected behavior

No diagnostic. [CA1711](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1711-identifiers-should-not-have-incorrect-suffix) lists "Dictionary" as an allowed suffix if the type inherits from System.Collections.Generic.IDictionary<TKey,TValue>

#### Actual behavior

Diagnostic

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/1658
