### ISSUE TITLE
When will the results of Milestone 15.6 be released?

### ISSUE THREAD

**Issue by j2jensen** [dotnet/roslyn-analyzers#1675]
There were some important bugs fixed in Milestone 15.6, which was closed on February 20, but there hasn't been a NuGet package update (not even a beta) since January 12. Why haven't these changes made it to NuGet yet? Is there any estimate on when that might happen?

I don't mean to be impatient, but I wanted to make sure this wasn't just overlooked.

**Comment by mavasani** [comment]
Yes, hopefully today. Meanwhile, you can reference the package from [this](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers) myget feed.
