### ISSUE TITLE
DTOs and CA1819 (and CA2227)

### ISSUE THREAD

**Issue by yaireclipse** [dotnet/roslyn-analyzers#1705]
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

[CA1819: Properties should not return arrays](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1819-properties-should-not-return-arrays)

#### Expected behavior
In the [`When to Suppress Warnings` section](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1819-properties-should-not-return-arrays#when-to-suppress-warnings) of the [CA1819: Properties should not return arrays](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1819-properties-should-not-return-arrays) documentation page, I expected that [Data Transfer Object classes (DTOs)](https://en.wikipedia.org/wiki/Data_transfer_object) would be noted as candidates for suppressing this rule.

#### Actual behavior
DTOs are not mentioned as candidates for warning suppression.

For example, I have a `byte` array that represensts some binary data. In the [`How to Fix Violations` section](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1819-properties-should-not-return-arrays#how-to-fix-violations), it is sugeested to

> either make the property a method or change the property to return a collection.

Making a property method might make the false impression that the DTO may hold, or even hide, some behavior behind getting and setting the property, which is not the typical case for DTOs.

Changing the property to return a collection, such as `List`, has two problems:
1.  It's awkward to use a `List<byte>` for binary data. Typically collections are used when each element in the collection is an independent instance, while here it's just raw data that will  makes sense only after some processing will take place.
2.  I'd just run into [CA2227 - Collection properties should be read only](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only). If I omit the `set;` from the property definition (or make it `private set;`), Json.NET is not able to deserialize into the DTO (admittedly, this could be solved by using `ICollection`, and then FxCop allows leaving the `public` setter, but still, `ICollection<byte>` really makes me scratch my head :) ).

I tried a third approach though - using a `struct` instead.  
Unfortunately, I then ran into [CA1815 - Override equals and operator equals on value types](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1815-override-equals-and-operator-equals-on-value-types). I really don't want to implement these for just a DTO. Trying to write as little code as possible for a DTO :)  
Also, I ran into [CA1051 - Do not declare visible instance fields](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1051-do-not-declare-visible-instance-fields).

All-in-all, IMHO, DTOs should be acknowledged as a legitimate exception to [CA1819: Properties should not return arrays](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1819-properties-should-not-return-arrays).

I couldn't yet think of a rule that would exclude only DTOs, maybe combined with the class name postfixed with `Dto`. That would jumping ahead anyway. But at least, if any of what I wrote here sounds reasonable, the exception could be added to the docs.

Also, I don't want to push it :), but DTOs might be a legitimate exception for [CA2227 - Collection properties should be read only](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only) as well.

Thanks for the good job, we benefit a lot out of it!
Yair

**Comment by levhaikin** [comment]
Hi,

I have the same problem. Would be nice to at least push it into the docs as a legitimate exception.

Joining @yaireclipse - thanks for the good job - we do benefit from it a lot!
Lev.

**Comment by mavasani** [comment]
@yaireclipse @levhaikin Thanks. The recommendation sounds reasonable to me. @dotnet/roslyn-analysis, any objections? Otherwise, I will port this to a documentation bug so it can be documented on docs.microsoft.com.

**Comment by mavasani** [comment]
Filed https://github.com/MicrosoftDocs/visualstudio-docs/issues/1367 to update the documentation.

**Comment by thomaslevesque** [comment]
IMO there should also be an exception for `byte[]` properties. `byte[]` is the standard type to represent binary data, and using any other type for this would be confusing. I think CA1819 shouldn't be triggered for `byte[]`.
