### ISSUE TITLE
CA1812 Shouldn't Fire for DebuggerTypeProxy

### ISSUE THREAD

**Issue by dcwuser** [dotnet/roslyn-analyzers#1708]
To change how a class is displayed in the VS debugger, one defines a type proxy and then adds the DebuggerTypeProxy attribute to the original class, so that the proxy class determines what is displayed by VS instead of the original class. It is natural to make the proxy class internal, since it is not intended to be part of the API surface. (VS finds and instantiates it via reflection.) When one does this, the proxy class triggers a CA1812 warning "XXX is an internal class that is apparently never instantiated."

I propose that if an internal class is referenced in any DebuggerTypeProxy attribute in an assembly, it should not trigger CA1812.

**Comment by KalleOlaviNiemitalo** [comment]
In my ASP.NET Web API (not ASP.NET Core) application, I got a CA1812 warning for `internal class RawStringBinder : IModelBinder`, which I use only in `[FromUri(BinderType = typeof(RawStringBinder))]`. So yes, I'd like the analyzer to recognize `typeof(...)`.

**Comment by Evangelink** [comment]
I think that the `DebuggerTypeProxy` makes sense. Regarding the `FromUri` I cannot find the doc for the old api so I am not entirely sure.

It might be too strong but we could also think about considering types declared in a `typeof` invocation of an attribute to always be instantiated, WDYT?

Tagging @sharwell and @mavasani

**Comment by KalleOlaviNiemitalo** [comment]
> Regarding the `FromUri` I cannot find the doc for the old api so I am not entirely sure.

In ASP.NET Web API, [`System.Web.Http.FromUriAttribute`](https://github.com/aspnet/AspNetWebStack/blob/39d3064baf13181f5718ec5d85ba644b47d0704b/src/System.Web.Http/FromUriAttribute.cs) inherits the `BinderType` property from [`System.Web.Http.ModelBinding.ModelBinderAttribute`](https://github.com/aspnet/AspNetWebStack/blob/39d3064baf13181f5718ec5d85ba644b47d0704b/src/System.Web.Http/ModelBinding/ModelBinderAttribute.cs), which eventually gets an instance of that type from `IDependencyResolver.GetService` or `Activator.CreateInstance`.

**Comment by Evangelink** [comment]
Thanks @KalleOlaviNiemitalo so it also makes sense to support this attribute.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/runtime/pull/39126> added `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]` to the `Type type` and `string typeName` parameters of the `DebuggerTypeProxyAttribute` constructors. The analyzer could recognize [DynamicallyAccessedMembersAttribute](<https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.dynamicallyaccessedmembersattribute?view=net-5.0> "DynamicallyAccessedMembersAttribute Class (System.Diagnostics.CodeAnalysis) | Microsoft Docs") and suppress the CA1812 warning, at least if any of the `DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors` bits is set.

For the sake of code that targets framework versions lower than .NET 5 though, the analyzer should recognize `DebuggerTypeProxyAttribute` and `System.Web.Http.ModelBinding.ModelBinderAttribute` as well.

**Comment by Evangelink** [comment]
@KalleOlaviNiemitalo I have moved your 2 suggestions as different thread so that this one can move forward.
