### ISSUE TITLE
Link to the current rule documentation on docs.microsoft.com

### ISSUE THREAD

**Issue by cremor** [dotnet/roslyn-analyzers#1709]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version 2.6.0

#### Analyzer

Every analyzer that has a documentation page linked.

#### Repro steps

1. Open the help page of any rule, either by clicking on "View help" in the context menu of a rule in the solution explorer or by clicking the linked rule id in the error list or quick action popup.

#### Expected behavior

It should directly open the newest documentation page on docs.microsoft.com, e.g. https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1000-do-not-declare-static-members-on-generic-types

#### Actual behavior

It opens the old (Visual Studio 2015) documentation on msdn.microsoft.com, e.g. https://msdn.microsoft.com/en-us/library/ms182139.aspx. At least that page offers a link to the new documentation, but still, this is an additional click that shouldn't be needed.

**Comment by 333fred** [comment]
This was fixed in https://github.com/dotnet/roslyn-analyzers/pull/1542, and will be in the next release.
