### ISSUE TITLE
Write a meta-analyzer to flag analyzers that use VB/C# compiler reserved diagnostic IDs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1727]
See https://github.com/dotnet/roslyn/issues/25748 for more details and previous attempt to put such an diagnostic in the compiler itself

**Comment by Evangelink** [comment]
@mavasani so the idea here is to report on diagnostic ids with the following patterns: `CA|CS|BC|RS` and then digits, is that it?

**Comment by mavasani** [comment]
We only want to flag CS and BC prefixes followed by and integral suffix as they would clash with C# and VB compiler diagnostic IDs respectively. No other prefixes should be flagged.

**Comment by sharwell** [comment]
We would also flag the special diagnostic ID `format` since it's tied into the core formatter.

**Comment by mavasani** [comment]
@Evangelink based on the discussions at https://github.com/dotnet/roslyn/issues/40351, I think your original suggestion of flagging even CA IDs seems reasonable. I think we should make this rule configurable so end users can tweak the banned regex to their own preference. For example, a repo might want to outright enforce that only a certain prefix and length of ID be used.

We have a very similar rule which allows users to provide a custom additional file to enforce the category and rule ID mapping, rule ID prefix and format: https://github.com/dotnet/roslyn-analyzers/blob/9c08642f76abffb8cce34aa1971a046e69ce710d/src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzerTests.cs#L419-L664. We should be able to utilize or refactor a bunch of this analyzer to add the new functionality.

**Comment by Evangelink** [comment]
@mavasani So to sum it up, I need to create a new analyzer which by default will handle:
- `CA` + 4 digits
- `CS` + 4 digits
- `BC` + 5 digits
- `format` + ???

Nothing hardcoded for `RS`

It will also allow users to provide a regex as ID check for each category. Does it need to be in the `.editorconfig` or as a separate file like `DiagnosticCategoryAndIdRanges.txt`?

**Comment by mavasani** [comment]
@Evangelink I think we should start with a simple analyzer that just flags CA, BC and CS diagnostics. I don't think you need to check specific digit count after the prefix, but just that it is a number. Let's leave adding configurability as a separate follow-up item, if we get customer requests.

For flagging the CA diagnostics, you probably need to add a hardcoded list of assembly names that shouldn't be flagged, which should include `Microsoft.CodeQuality.Analyzers`, `Microsoft.NetCore.Analyzers`, `Microsoft.NetFramework.Analyzers` and also all of their C# and VB analyzer assembly names.
