### ISSUE TITLE
Warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created

### ISSUE THREAD

**Issue by elmojo** [dotnet/roslyn-analyzers#1729]
#### Message
warning CS8032: An instance of analyzer Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer cannot be created from C:\Users\{username}\.nuget\packages\microsoft.entityframeworkcore.analyzers\2.1.0\analyzers\dotnet\cs\Microsoft.EntityFrameworkCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..

#### Analyzer package

Microsoft.EntityFrameworkCore.RawSqlStringInjectionDiagnosticAnalyzer

#### Package Version
dotnet version
2.0.2

Microsoft.EntityFrameworkCore.Analyzers
2.1.0.18136

#### Diagnostic ID

CS8032

#### Repro steps

1. Create new dotnet core application.
2. Add the following to the *.csproj file:
`  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0" />
  </ItemGroup>`
3. Build.
4. Warning CS8032 should present itself.

#### Expected behavior
No warnings

#### Actual behavior
Warnings thrown

**Comment by thepirat000** [comment]
same here

**Comment by 333fred** [comment]
@elmojo @thepirat000 this repo does not own that set of analyzers, that's at https://github.com/aspnet/EntityFrameworkCore. However, looking at the error message, it appears that those analyzers depend on a newer version of roslyn than is in 2.0, you'll likely need to update to 2.1.

**Comment by 333fred** [comment]
Feel free to comment, but I'm going to close this as we don't own that set of analyzers.

**Comment by MihailDobrev** [comment]
Is there a fix to this, I have the same error?

**Comment by 333fred** [comment]
@MihailDobrev you likely need to update the dotnet version you're using. If that doesn't fix it, I suggest opening an issue on the repository I linked above.

**Comment by surfmuggle** [comment]
In my case the *.csproj file contained a reference to a version that was not installed. 

I changed
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0">
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.0" />
```
to this

```
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.*">
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.*" />
```


This did the trick
