### ISSUE TITLE
C# Core Guideline

### ISSUE THREAD

**Issue by magol** [dotnet/roslyn-analyzers#1731]
(This repository is probably not the right place to ask this question, but I cannot find any better place. Please refer to the correct place, if any)

For the C++ world, it is a [C++ Core Guideline](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines). For some of the guidelines it is analysis in Visual Studio, but many of the guidelines are more of a philosophical nature.

I can not find any similar resource for C# that have the same level of detail and big scope. I suggest to create a GIT repository to start collect suggestion from the community and build a **C# Core Guideline**.

**Comment by mavasani** [comment]
Ported to https://github.com/dotnet/csharplang/issues/1779
