### ISSUE TITLE
Remove fragile logic in IOperation analyzers that rely on specific operation tree shape

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1737]

**Comment by Evangelink** [comment]
@mavasani Is the idea of this ticket to replace all operation calls to `WithoutFullyImplicitOperations`?

**Comment by sharwell** [comment]
@mavasani I'd love to see an article-style explanation of how that analyzer ended up in a situation where in broke, how and why it broke, and lessons learned. As a user which much less experience in these analyzers, it's hard to have confidence that I wouldn't be making the same mistakes.

**Comment by Evangelink** [comment]
@mavasani is it possible to get a little more info about what needs to be done for this ticket?

**Comment by mavasani** [comment]
I think this is a difficult item to audit - basically needs reviewing each IOperation analyzer whose functionality relies on specific operation kinds or IOperation sub-interface for either its ancestor node or descendant node. I am fine if we close this out and tackle each customer report and rely on unit tests to guard against such breaks.

**Comment by mavasani** [comment]
Lets close this one for now..
