### ISSUE TITLE
Delete the Microsoft.Net.RoslynDiagnostics package

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1750]
Roslyn was the only consumer, and has now switched to directly referencing other analyzer packages (see dotnet/roslyn#29020). Updates to the **Microsoft.Net.RoslynDiagnostics** package no longer need to be maintained/published.

**Comment by mavasani** [comment]
@jmarolf If required, feel free to just do the work on the project system side here - I can do the required work on the analyzers as a follow up change.

**Comment by jmarolf** [comment]
Working with @drewnoakes 	to get us off this package.  We'll let you know when we've moved off

**Comment by drewnoakes** [comment]
We're no longer using `Microsoft.Net.RoslynDiagnostics` in dotnet/project-system.
