### ISSUE TITLE
Implemented version CA1724 does not match its official description

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/roslyn-analyzers#1753]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Diagnostic ID

[CA1724](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1724-type-names-should-not-match-namespaces)

#### Issue

The official description of this ID is:

> Type names should not match the names of namespaces that are defined in the .NET Framework class library. Violating this rule can reduce the usability of the library.

This analyzer implements quite a bit more than that.

It will warn about namespace matches from within the current project. That is a perfectly reasonable thing to warn about, but having it use the same code as Framework collisions is less useful, since the priority must be the same.

It will also warn about having a type name that matches some poorly chosen namespace name in some dependency of a dependency. That is a lot less useful. I really don't care if one of my type names happens to match a random namespace of a deeply nested dependency. Yet either I must disable this rule entirely or add a bunch of suppressions.

**Comment by mavasani** [comment]
Another related issue: https://github.com/dotnet/roslyn-analyzers/issues/1673

**Comment by mavasani** [comment]
We should possibly use a different rule ID for the [non-system/default rule](https://github.com/dotnet/roslyn-analyzers/blob/2858e1048ea2d4738bd94af33ad44855b291140f/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs#L28) and also update the implementation to only report it for source type/namespace, and also only consider externally visible types.

**Comment by mavasani** [comment]
Alright, so I played around a bit more with legacy FxCop implementation and see that even that implements 2 separate rules: one for system namespaces and one for namespaces in your project. We match the implementation, and we cannot change the ID used for the latter rule as that would void existing in-source suppressions for latter case.

However, I believe we should still fix https://github.com/dotnet/roslyn-analyzers/issues/1673, which is a valid issue to reduce noise. I am going to close this issue as Won't Fix for compat reason. @KevinCathcart Hopefully, the noise reduction from https://github.com/dotnet/roslyn-analyzers/issues/1673 aids you a bit more.

**Comment by mavasani** [comment]
Filed https://github.com/MicrosoftDocs/visualstudio-docs/issues/1362 to update documentation for CA1724 to include additional scenarios covered by the rule implementation.
