### ISSUE TITLE
Shipping story for Metrics.exe

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#1756]
https://github.com/dotnet/roslyn-analyzers/pull/1754 ports Metrics.exe that shipped from VS2010-VS2015 for code metrics report generation. The PR does not package or publish the exe. For now, the customers have to build the repo locally and produce the exe. If this is not sufficient and we have enough customer requests, we need to sign/package/publish this exe.

- [ ] Localization
- [ ] Unit tests
- [ ] Signing
- [ ] Packaging
- [ ] Publishing

**Comment by pjmagee** [comment]
I would say even provide a NuGet package not an .exe so I can use the API to crunch the metrics by opening a Solution using the Roslyn/MSBuild open solution API and then passing that into the Metrics analyzer instead of using an exe.

**Comment by mwisebaker** [comment]
Any ETA on this? I can't generate the executable from the source code because I'm restricted by Execution Policy within my enterprise.

**Comment by pjmagee** [comment]
@mwisebaker  you're a developer, and you cant build a solution and execute it?

**Comment by mwisebaker** [comment]
@pjmagee The instructions don't say "Build the solution and execute it", they include some PowerShell commands that I can't run because the code isn't signed and my organization locks down my execution context. Why the snarky comment?

**Comment by mavasani** [comment]
Tagging @jinujoseph and @vatsalyaagrawal - we still working on the best shipping vehicle for this tool. Will post an update here once we know more. Thanks for your patience.

**Comment by pjmagee** [comment]
@mavasani  Is a NuGet package that can be used on top of the Roylsn/MsBuild tools Workspace API still an option for this tool?

**Comment by mavasani** [comment]
@pjmagee That is what precisely I was thinking this morning - shipping an MSBuild task dll that enables metrics generation. Let me play around with it and get back to you. Thanks!

**Comment by mavasani** [comment]
FYI: I have a [PR](https://github.com/dotnet/roslyn-analyzers/pull/2030) out for this. Please take a look and let me know if it suffices your needs or not.

**Comment by mavasani** [comment]
NuGet package to try out is available here: https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeMetrics

**Comment by mavasani** [comment]
NuGet package has been renamed and published to NuGet.org: https://www.nuget.org/packages/Microsoft.CodeAnalysis.Metrics/
