### ISSUE TITLE
CA1012 not reported for internal types

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#1777]
Currently CA1012 is not reported for `internal` types. This analyzer supports a common pattern, and the current exclusion leaves the analyzer insufficient for enforcing practices so team members are forced to fill in the gaps manually. We should consider expanding this analysis to no longer consider this exclusion.

https://github.com/dotnet/roslyn-analyzers/blob/2858e1048ea2d4738bd94af33ad44855b291140f/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/AbstractTypesShouldNotHaveConstructors.cs#L46

**Comment by mavasani** [comment]
Most of the rules were initially implemented without externally visible checks. However, this led to lot of customer complaints about behavioral difference and compat break from old FxCop. I think the ideal approach would be to have the default settings match FxCop but make the analyzer customizable by the end user through analyzer options. That is however a big work item, which needs generic string key-value pair analyzer options to be threaded to the analyzers, not just additional files.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/1952 enables adding this configuration option. I will do so once that PR is merged in.

**Comment by mavasani** [comment]
This is now configurable: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#analyzed-api-surface
