### ISSUE TITLE
Standardize HelpLinkUris for rule documentation

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#1779]
Hello @jinujoseph @gewarren @mavasani ,

Manish suggested I open a issue here for standardizing help links for rules (e.g. should they all be aka.ms links, or docs.microsoft.com?), and if they should be aka.ms links, who creates and owns the aka.ms short URLs?

**Comment by sharwell** [comment]
Related to https://github.com/dotnet/roslyn-analyzers/issues/1269?

**Comment by dotpaul** [comment]
I think we've settled on docs.microsoft.com links without a language.
