### ISSUE TITLE
Test.Utilities.CodeFixRunner.GetNewDiagnostics -- please help figure out how it detects new diagnostics

### ISSUE THREAD

**Issue by mykolav** [dotnet/roslyn-analyzers#1787]
Hello,
Could someone please give me a hand here.  

I've stumbled across `Test.Utilities.CodeFixRunner.GetNewDiagnostics` and struggling to understand how the method is supposed to detect new compiler diagnostics potentially introduced by the code-fix under test.

Here is the method's code
```csharp
static IEnumerable<Diagnostic> GetNewDiagnostics(IEnumerable<Diagnostic> diagnostics, IEnumerable<Diagnostic> newDiagnostics) {
    Diagnostic[] oldArray = diagnostics.OrderBy(d => d.Location.SourceSpan.Start).ToArray();
    Diagnostic[] newArray = newDiagnostics.OrderBy(d => d.Location.SourceSpan.Start).ToArray();

    int oldIndex = 0;
    int newIndex = 0;

    while (newIndex < newArray.Length) {
        if (oldIndex < oldArray.Length && oldArray[oldIndex].Id == newArray[newIndex].Id) {
            ++oldIndex;
            ++newIndex;
        } else {
            yield return newArray[newIndex++];
        } } }
 ```
Given the code, let's consider a case where after ordering by `SourceSpan.Start`
- `oldArray` contains diagnostics with ids `9011; 9001; 9005`
- `newArray` contains diagnostics with ids `9001; 9005`. I.e. application of the code-fix under test resolved a warning.
- the way `GetNewDiagnostics` performs comparison of the two arrays, it seems it will yield `9001; 9005` as the new compiler diagnostics.

Is my understanding of how `GetNewDiagnostics` works in the above scenario correct?
If so, is it actually the expected behavior?

Thank you,
Mykola.

**Comment by mavasani** [comment]
You should be using `Microsoft.CodeAnalysis.Testing` NuGet package for the test framework. @sharwell when do we plan to publish the NuGet package for it on nuget.org?

**Comment by sharwell** [comment]
@mavasani The package is already published through MyGet and ready for use.
