### ISSUE TITLE
Make security warnings for unsafe deserialization APIs

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#1790]
There should be security warnings for using potentially unsafe deserialization APIs, e.g. BinaryFormatter.

**Comment by dotpaul** [comment]
First set of APIs I'll be targeting:
- BinaryFormatter
- JavaScriptSerializer
- LosFormatter
- NetDataContractSerializer
- ObjectStateFormatter

**Comment by mavasani** [comment]
@dotpaul - Is this complete?

**Comment by dotpaul** [comment]
Let's say the first set is done. Rules in the range of CA2300-CA2330 cover:
- BinaryFormatter
- LosFormatter
- NetDataContractSerializer
- ObjectStateFormatter
- JavaScriptSerializer
- Newtonsoft Json.NET

If anyone would like more deserializers covered, please open new issues. Thanks!
