### ISSUE TITLE
Visual Studio fails to recognize any diagnostic in a custom analyzer package

### ISSUE THREAD

**Issue by taori** [dotnet/roslyn-analyzers#1792]
#### Analyzer package
Private one in local nuget

My analyzer cannot be scanned correctly for some reason apparently.

In an attempt to fix this i copied what is done at xunit.analyzers - Downgrade all packages in hopes of being compatible with the runtime of VS, to exclude that as source of error.

While those analyzers used to work at some point when they were references in PCL projects, they now can be referenced but appear empty if referenced from netstandard projects. Oddly enough they don't work in .net projects anymore either after changing to the new csproj SDK.

Is there some documentation i have missed out on, to get this to work?

![image](https://user-images.githubusercontent.com/5545184/44673561-31778700-aa2c-11e8-8b29-343a98f1a6b7.png)

**Comment by mavasani** [comment]
@taori Can you please port this to https://github.com/dotnet/roslyn/issues? The issues in this repo are primarily tracking bugs in analyzers implemented within the repo itself. Thanks.

**Comment by taori** [comment]
ok. on it
