### ISSUE TITLE
Add security diagnostic for DefaultDllImportSearchPathsAttribute

### ISSUE THREAD

**Issue by morganbr** [dotnet/roslyn-analyzers#1806]
By default, P/Invokes using ```DllImportAttribute``` probe a number of directories, including the current working directory for the library to load. This can be a security issue for certain applications, leading to [dll hijacking](https://resources.infosecinstitute.com/dll-hijacking-attacks-revisited/#gref). If a developer applies [DefaultDllImportSearchPathsAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultdllimportsearchpathsattribute) to the P/Invoke or the assembly, they can control where P/Invokes load from and avoid dangerous paths. It would be useful to have a diagnostic for assemblies with P/Invokes that checks whether they have ```DefaultDllImportSearchPathsAttribute``` and warns otherwise.

**Comment by mavasani** [comment]
Tagging @dotpaul for triage

**Comment by Zenexer** [comment]
Pinging you for https://github.com/dotnet/dotnet-api-docs/issues/3205
