### ISSUE TITLE
Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.ImplementIDisposableCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' 

### ISSUE THREAD

**Issue by MS-TimothyMothra** [dotnet/roslyn-analyzers#1815]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers

#### Package Version

v2.6.1

#### Diagnostic ID

Error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.ImplementIDisposableCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

#### Repro steps

1. Download project: https://github.com/Microsoft/ApplicationInsights-dotnet
2. Build my project
3. If someone wants to contact me, I can give you access to our VSTS builds.

#### Expected behavior

Report all errors in my code without exception.

#### Actual behavior

Analyzer throws a null ref exception

**Comment by MS-TimothyMothra** [comment]
Got another one in the same repo.

- CA1063: Implement IDisposable correctly
- CA2213: Disposable Fields Should Be Disposed

The fix for this is to disable the Rule number in your *.ruleset file.

**Comment by petedavis** [comment]
This might seem silly, but found one cause of this.

Someone had removed the need for dispose after removing a member variable, then resharper said that this method should be made static as it doesnt access any member variables.

Then we had the null reference exception thrown on the build server.

This was the offending code:
```
public void Dispose(){
    Dispose(true)
}

protected static void Dispose(bool disposing)
{
    if (!disposing) return;
}
```
