### ISSUE TITLE
Classes implementing IDataReader should not have have enumerable diagnostics

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-analyzers#1818]
Analyzer package: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
Package Version: 2.6.2-beta2
Diagnostic ID: CA1010, CA1710

When implementing DbDataReader, IDataReader, or maybe even the base interface IDataRecord, it's rare to treat it as a collection even though IEnumerable is a base interface of IDataRecord. The name of a data reader should not end with 'Collection' and implementing the generic `IEnumerable<>` is not possible since the schema varies at runtime.

Repro code:

```c#
public sealed class CustomDbDataReader : DbDataReader
{
    // Ordinary DbDataReader implementation 
}
```

> CA1010 Collection 'CustomDbDataReader' directly or indirectly inherits 'IEnumerable' without implementing 'IEnumerable\<T>'. Publicly-visible collections should implement the generic version to broaden usability.

> CA1710 Rename CustomDbDataReader to end in 'Collection'.

**Comment by Evangelink** [comment]
@mavasani I was starting to tackle this issue when I realized that it might be better to ask for a `DataReader` suffix instead of skipping data reader classes. WDYT?

**Comment by Evangelink** [comment]
@mavasani I'd like your input here before doing a PR in a direction or another.

**Comment by Evangelink** [comment]
@mavasani ping

**Comment by Evangelink** [comment]
@mavasani Same here. With the decision on #3065 I think this issue shall be addressed.

**Comment by mavasani** [comment]
This rule is now configurable: https://github.com/dotnet/roslyn-analyzers/pull/3148

**Comment by jnm2** [comment]
@mavasani Are classes implementing `IDataReader` now excluded from these diagnostics out of the box?

**Comment by Evangelink** [comment]
They are not but you now can add a custom suffix. @mavasani I actually didn't allow empty string, it might be better to allow it to help providing the exclusion feature.

**Comment by mavasani** [comment]
That sounds reasonable - might be worth also taking a compat break and having the default value for [exclude-indirect-base-types](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#exclude-indirect-base-types) be `true`, given that seems to be a more reasonable behavior.

**Comment by Evangelink** [comment]
@mavasani This can now be closed.

@jnm2 This is now excluded by default.
