### ISSUE TITLE
Build results in many CS8032 warnings

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn-analyzers#1825]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Diagnostic ID

CS8032

#### Repro steps

1. Opened a single-project solution in VS 2017 (15.8.2).
1. Add reference to Microsoft.CodeAnalysis.FxCopAnalyzers
1. Build

NOTE: Project targets .NET 4.6 and includes NuGet references to Microsoft.CodeDom.Providers.DotNetCompilerPlatform v1.0.2 and Microsoft.Net.Compilers v1.3.2.

#### Expected behavior

CS8032 issues do not appear.

#### Actual behavior

132 CS8032 issues appear

![image](https://user-images.githubusercontent.com/1784452/45636915-bd4e6300-ba6e-11e8-8f32-e800f3a4038e.png)
![image](https://user-images.githubusercontent.com/1784452/45636943-d8b96e00-ba6e-11e8-95ff-24175c6674b9.png)
![image](https://user-images.githubusercontent.com/1784452/45636960-e7078a00-ba6e-11e8-91f4-578d290fcd0d.png)
![image](https://user-images.githubusercontent.com/1784452/45636992-f686d300-ba6e-11e8-84be-a6b9e65e40dd.png)

**Comment by mavasani** [comment]
This seems to be by design. You are referencing `Microsoft.Net.Compilers v1.3.2`, which uses an older C# compiler then the one required by FxCop analyzers Nuget package v2.6.1. You should either move to Microsoft.Net.Compilers >= v2.6.1 OR use an older FxCop analyzer package as per https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2017#fxcopanalyzers-package-versions

**Comment by MisinformedDNA** [comment]
The link provided does not say anything about compiler versions, it only references VS versions.

Also, if analyzers require a minimum version of the compiler to behave correctly, shouldn't there be a NuGet dependency set up?

**Comment by IrisClasson** [comment]
We are having the same problem and can't find anything in the documentation that helps resolve the issue. Any pointers?

**Comment by sharwell** [comment]
@IrisClasson Can you open a new issue with your specific error?

**Comment by TanvirArjel** [comment]
@mavasani You did not answer the @MisinformedDNA's question which is also my question too as I am  also facing the same problem. What `FxCop analyzers `version should I use if my project referencing `Microsoft.Net.Compilers v1.3.2` as I cannot update `Microsoft.Net.Compilers` version?
