### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by bhupi196** [dotnet/roslyn-analyzers#1879]
I am  using Windows 7 64 bit PC 
Roslyn API version **2.6.2**
.Net Version **4.6.1**

For every new script it takes 4-5 seconds to compile, Please let me know a work around.

Following is one code sample which I am trying to run.

```
var script = CSharpScript.Create<object>("System.Console.WriteLine(\"Something\");");
script.Compile();
```

**Comment by mavasani** [comment]
@bhupi196 This issue belongs to a different repo: https://github.com/dotnet/roslyn. Can you please move the bug there and close this one?
