### ISSUE TITLE
How add CodeFix to general rule (not custom)

### ISSUE THREAD

**Issue by alex1815** [dotnet/roslyn-analyzers#1885]
Question:

#### Diagnostic ID
[CA1307](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca1307-specify-stringcomparison?view=vs-2017)

I'm trying to add custom Code Fix to general rule CA1307 (specify StringComparison). I want to add unit tests, but I didn't find how I can specify analyzer for CA1307.

![image](https://user-images.githubusercontent.com/11064818/48263836-7eb6a280-e438-11e8-877f-2066c6333fb1.png)

Could you please clarify:
Can I add custom code fix for general rule? If yes, could you please share how I can get the name of diagnostic class for general rules (CA1307 in current case)?

**Comment by sharwell** [comment]
The analyzer is this one:

https://github.com/dotnet/roslyn-analyzers/blob/bcf2215966b9ba579111287cadf03727ea33fece/src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/SpecifyStringComparisonTests.cs#L14

**Comment by alex1815** [comment]
Thanks!

**Comment by alex1815** [comment]
@sharwell do we have same analyzer for .net 461 version, not for Core?

**Comment by mavasani** [comment]
> do we have same analyzer for .net 461 version, not for Core?

.NetCore analyzers package is valid for both NetCore projects and NetFramework projects, so this analyzer will also execute when the FxCop analyzers NuGet package is added to a .net 461 project.

**Comment by alex1815** [comment]
@mavasani got it, thanks
