### ISSUE TITLE
CA1812 (Avoid uninstantiated internal classes) doesn't account for internal types used in other assembly

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#1893]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.6.2

#### Diagnostic ID

Example: CA1812
#### Repro steps

See src/Utilities/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataSymbolMap.cs in roslyn-analyzers's features/dataflow branch, for example.

#### Expected behavior

The rule doesn't fire when an internal class is used by another assembly (I guess the best approximation is if there's an InternalsVisibleToAttribute somewhere?)

#### Actual behavior

The rule fires.

**Comment by mavasani** [comment]
On further investigation, it seems there is not much we can do here. The false positive is coming in a source file in a shared project, which is used by around 8-10 projects, such that the type is instantiated/used in about half of them. The warning is correctly reported in rest of the projects that do not use this type, and suppression seems like the correct approach here.
