### ISSUE TITLE
Rules with similar goals but different approaches may result in duplicate diagnostics

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#1901]
CA3001 and CA2100 both are looking SQL injection vulnerabilities, but have different approaches.

---
Can you try this test code with the both CA2100 and your rule being added here enabled? Just want to make sure we don't fire dupes of same issue with different rule ID. If we do, please file a separate tracking issue so we can clean up and remove the overlap with a future PR.

_Originally posted by @mavasani in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MjI5MjIzMzgw/timeline/more_items_

**Comment by dotpaul** [comment]
@mavasani what did you have in mind for de-duping?

My initial feeling is duplicates are acceptable.

**Comment by mavasani** [comment]
> My initial feeling is duplicates are acceptable.

I would say only if they are for different rules, such that at most one is enabled by default. A default analyzer package should not fire multiple diagnostics with different ID for the same underlying issue.

**Comment by mavasani** [comment]
@dotpaul - I think we can close this issue until we receive actual customer complaints about duplicates. Does that sound reasonable to you?

**Comment by dotpaul** [comment]
Yes, let's close.
