### ISSUE TITLE
Suppress in source as an attribute should be one option.

### ISSUE THREAD

**Issue by srdjanjovcic** [dotnet/roslyn-analyzers#1902]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.2

#### Diagnostic ID

All code analysis rules.

#### Repro steps

1. Create a project which violates some CA rule.
2. Compile.
3. Use quick action "Suppress > In Source..."
4. Notice that it uses `#pragma disable … #pragma enable` pair.

#### Expected behavior

I would expect that "suppress in source..." would insert `[SuppressMessage]` attribute, same as "suppress in suppression file" does. `[SuppressMessage]` attribute can be placed on members, too, like this:

  [SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>")]

At least, it should be an option:

* Suppress > In source as a \#pragma directive...
* Suppress > In source as an attribute...
* Suppress > In suppression file...

**Comment by mavasani** [comment]
This was considered during the initial implementation of the suppression code fix provider. However, it was felt that this was adding too many alternatives to do the same operation. It was decided that we will provide one fix to suppress "inline" in source using pragmas (which would also be applicable to compiler diagnostics) and one fix to suppress in source adding suppress message attributes to a global suppressions file that does not pollute the current source file. As a workaround for local suppress message attribute suppression, which is uncommon, user can generate the global one, then cut and paste the generated attribute to the desired symbol and remove the `Target` and `Scope` strings in the attribute.

**Comment by mavasani** [comment]
@srdjanjovcic This issue belongs to the roslyn repo. The analyzer package does not provide this code fix, this code fix is implemented for all suppressible diagnostics in Visual Studio itself.

@jaredpar Can you please port this issue to roslyn repo and mark it as `Area-IDE`?

**Comment by maboivin** [comment]
Any update on this issue? Our internal code styles also recommend using the SuppressMessage attribute over the #pragma directive.  We have moved from the static code anlaysis to the FxCop analyzers (and many oithers) since legacy code analysis is deprecated in VS2019 and we would really like the option to use the SupressMessage attribute.

**Comment by mavasani** [comment]
This issue does not belong to this repo. Kindly port it to the roslyn repo if you still require this and the workaround is not acceptable.
