### ISSUE TITLE
CA1508 incorrect in catch or finally block when exception thrown (VB)

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn-analyzers#1921]
#### Analyzer package

Microsoft.CodeQuality.Analyzers.Exp

#### Package Version

v2.6.3-beta1.18611.3

#### Diagnostic ID

CA1508 - Remove or refactor conditions to avoid dead code

#### Repro steps

This code incorrectly reports CA1508 twice:

- `Is writer IsNot Nothing` (claims always true)
- `Is stream IsNot Nothing` (claims always false)

I believe neither claim is correct due to potential for early exit in case of exceptions. They are correct in the no-exception case. Flow analysis needs to consider exceptions.

https://github.com/dotnet/project-system/blob/0e77773302b329e1cbc71bb419b6f523a8a6b2b2/src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationProperties.vb#L704-L722

#### Expected behavior

No diagnostic.

#### Actual behavior

Diagnostic.

**Comment by drewnoakes** [comment]
Another example, this time in a catch block:

https://github.com/dotnet/project-system/blob/0e77773302b329e1cbc71bb419b6f523a8a6b2b2/src/Microsoft.VisualStudio.Editors/MyApplication/MyApplicationCodeGenerator.vb#L115

Claims `BufPtr.Equals(IntPtr.Zero)` is always true.

**Comment by mavasani** [comment]
@drewnoakes I would recommend you disable CA1508 from the 2.6.XXX package, as the implementation in that package was primarily for experimental purposes. The implementation in 2.9.XXX package (not yet publishes) is based on dataflow analysis using compiler's CFG APIs and should have much less false positives.

**Comment by drewnoakes** [comment]
Ok, thanks for letting me know. I'll stop filing bugs against it then.
