### ISSUE TITLE
Detect bad use of async code?

### ISSUE THREAD

**Issue by phatcher** [dotnet/roslyn-analyzers#1928]
If you are writing a library using explicitly waiting on a Task using Result can result in deadlocks, e.g. ASP.NET due to the result not getting back to the invoking thread.

Is there an existing analyser that would find such code e.g.

```
pubic Task<string> FooAsync()
{
    // Whatever logic goes here, sample for now
    return Task.FromResult("Hello");
}

public string Foo()
{
    // This is bad!
    return FooAsync().Result;
}
```

**Comment by mavasani** [comment]
Tagging @AArnott - is this case covered in VS threading analyzers?

**Comment by AArnott** [comment]
Yes. Our [VSTHRD002 rule](https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD002.md) catches this case.

**Comment by AArnott** [comment]
@phatcher You can install these analyzers via the Microsoft.VisualStudio.Threading.Analyzers nuget package.

**Comment by mavasani** [comment]
Closing this issue - @phatcher let us know if you need more assistance here.

**Comment by phatcher** [comment]
@AArnott Thanks for the info

**Comment by phatcher** [comment]
@AArnott Is this available as a VSIX so I don't have to modify all my projects?

**Comment by AArnott** [comment]
No. But you can file an issue over at https://github.com/Microsoft/vs-threading/issues/new/choose to ask for a VSIX. Yours is the first request we've heard for it.

**Comment by AArnott** [comment]
@phatcher I'm not sure whether we'll ship it yet, but here is the change to build a VSIX with the threading analyzers in it:
https://github.com/Microsoft/vs-threading/pull/452
