### ISSUE TITLE
CA1305 triggers with invariant formats

### ISSUE THREAD

**Issue by scalablecory** [dotnet/roslyn-analyzers#1949]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.2

#### Diagnostic ID

CA1305

#### Repro steps

Some standard string formats are invariant, for instance, the date time "o" (round-trip) specifies:

> Because the "O" or "o" standard format specifier conforms to an international standard, the formatting or parsing operation that uses the specifier always uses the invariant culture and the Gregorian calendar.

Other types have similar standard format strings.

Using one of these should either not trigger the CA1305 warning, or perhaps a note should be added to the warning stating it is intentionally being caught for consistency purposes.

**Comment by mavasani** [comment]
@scalablecory The [suppression suggestion](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1305-specify-iformatprovider?view=vs-2017#when-to-suppress-warnings) for this rule already mentions: `It is safe to suppress a warning from this rule when it is certain that the default format is the correct choice, and where code maintainability is not an important development priority`. I am not sure if this is explicitly required in the diagnostic message.
