### ISSUE TITLE
FxCop rule CA2000: Dispose objects before losing scope

### ISSUE THREAD

**Issue by Jm-Fox** [dotnet/roslyn-analyzers#1997]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.2

#### Diagnostic ID

[CA2000](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2017)

#### Repro steps

1. Clone https://github.com/Jm-Fox/NetCoreCodeAnalysis
2. Open CodeAnalysis.sln (I used VS 2017.9)
3. In the solution explorer, right click on **Solution 'CodeAnalysis' (2 projects)** and select **Analyze** > **Run Code Analysis on Solution**

#### Expected behavior

A CA2000 issue is expected on the method CodeAnalysis.Methods.CA2000 in the NetCore project.

#### Actual behavior

No CA2000 issue is found on the NetCore project.

#### Priority

This is very important to me and my employer. Failing to properly dispose objects can introduce bugs to production systems, and not having automated checks for disposing objects is a serious reason not to move code from .net framework to .net core.

See also https://github.com/dotnet/roslyn-analyzers/issues/1948

Edit:
Removed "Example" where I had not changed the issue template.

**Comment by mavasani** [comment]
This seems to be due https://github.com/dotnet/roslyn-analyzers/issues/1580 - our current implementation only handles missing dispose on non-exceptional path. Implementing this would likely require implementing path sensitive analysis: https://github.com/dotnet/roslyn-analyzers/issues/1581

Tagging @jinujoseph and @vatsalyaagrawal as this would probably need at least one or two weeks of dev work.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/2162, available in 2.9.x package
