### ISSUE TITLE
The feature "flow-analysis" is deactivated

### ISSUE THREAD

**Issue by twsl** [dotnet/roslyn-analyzers#2003]
#### Analyzer package

Example: [Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

Example: v2.9.0-beta1-63118-01 and v2.6.3

#### Diagnostic ID

Example: AD0001

#### Repro steps

I have no idea, why this error occurs.

#### Expected behavior
None, I guess.

#### Actual behavior
Throwing a couple of `System.InvalidOperationException` in different methods with the message 

> The feature "flow-analysis" is deactivated

I have no idea, where to activate that feature or where to find that feature and couldn't find a solution

**Comment by carlos-quintero** [comment]
> You can add the following property group to your MSBuild project file:
> 
> ```
> <PropertyGroup>
>   <Features>flow-analysis</Features>
> </PropertyGroup>
> ```

While that solves the problem, where is it documented?  And even if documented somewhere, I think it is a bad user experience.
