### ISSUE TITLE
Add doc links to ported security queries

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#2021]
Need to add help link URLs for ported security queries:
- CA5358
- CA5359

Also need to ensure someone writes documentation first.  :-)

---
Do we have a bug tracking add a documentation link? @dotpaul, are we using the bug you file for security rules to track this one too?

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/1991/files_

**Comment by mavasani** [comment]
Tracked with https://github.com/dotnet/roslyn-analyzers/issues/2552 and https://github.com/dotnet/roslyn-analyzers/issues/2553
