### ISSUE TITLE
Using Metrics.exe

### ISSUE THREAD

**Issue by vinijmoura** [dotnet/roslyn-analyzers#2022]
I'm using "Generate Code Metrics Data" link (https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017) to create all metrics on diferent projects.

I create a respective exe Metrics and run command line. But there are diferent outputs between command and Visual Studio. See examples:

Visual Studio:

![vs](https://user-images.githubusercontent.com/8333012/51408907-59849580-1b47-11e9-999a-6fa652203299.png)

Command Line:

![cmd](https://user-images.githubusercontent.com/8333012/51408915-62756700-1b47-11e9-87ec-c6f726eb863b.png)

Any problems here?

**Comment by mavasani** [comment]
This is similar to https://github.com/dotnet/roslyn-analyzers/issues/2017. Code Metrics in VS2017 is based on MSIL analysis and gives the IL based data, the numbers should match if you use VS2019 preview1 or later. Metrics.exe performs source based analysis and hence produces code metrics based on source. If you want to generate metrics data that matches VS2017, you can try building Metrics.exe in [legacy mode](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017#legacy-mode). Note that the numbers will not match precisely but will be much closer to VS2017 code metrics window.

**Comment by vinijmoura** [comment]
I generated Metrics.exe using legacy mode. My attchments reflected them.

**Comment by mavasani** [comment]
@vinijmoura Ah, didn't realize that - numbers seem mostly identical except cyclomatic complexity and lines of code. Lines of code is a tricky metric, as VS2017 analyzer pure MSIL instructions, and metrics does source based analysis to count number of [IOperations](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/IOperation.cs,17), which may not always match the MSIL instruction count. Also do you have any lambdas or local functions in your project? It is a known issue that VS2017 completely ignores those for metrics computation, but Metrics.exe counts them. There are some other minor differences, but I would need a repro project to perform a conclusive analysis.

**Comment by mavasani** [comment]
Closing this issue, kindly re-open if you have more information or repro project to assist investigations.

**Comment by mavasani** [comment]
Update: https://github.com/MicrosoftDocs/visualstudio-docs/issues/3979
