### ISSUE TITLE
Create a one step UI to enable analyzers in Visual Studio/VS Code/DotNet

### ISSUE THREAD

**Issue by lucabol** [dotnet/roslyn-analyzers#2023]
It is complicated today to figure out which one are the official msft analyzers and install them.

Something along the lines of: in VS, an ‘Enable analyzers’ checkbox under ‘Project Properties/Build’. In CLI, ‘dotnet enable-analyzers’ or ‘dotnet add msft-analyzers’ or similarly obvious command.

**Comment by MelbourneDeveloper** [comment]
^^^^ This guy

A programmer should be cajoled in to using code analysis from the first step of creating a project. It should be simple and straight forward to turn errors on or off, and programmers should be able to get easy information about the code rule in the same spot where they turn it on or off - kind of like this:

![image](https://user-images.githubusercontent.com/16697547/52614922-5d59cc80-2ee7-11e9-82fd-b94b7ac707aa.png)

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal

**Comment by mavasani** [comment]
https://github.com/dotnet/project-system/pull/5094 adds support to Code Analysis property page to view/install/uninstall/search Microsoft recommended FxCop analyzers package.

![image](https://user-images.githubusercontent.com/10605811/61562356-01f7b180-aa26-11e9-8e3c-32ea08f08a62.png)

![image](https://user-images.githubusercontent.com/10605811/61562365-0623cf00-aa26-11e9-831f-338155f8c562.png)

**Comment by MelbourneDeveloper** [comment]
@mavasani yes!

**Comment by mavasani** [comment]
This should be available with VS2019 16.3 release.
