### ISSUE TITLE
Clean up Nuget to make it obvious which analyzers package to install 

### ISSUE THREAD

**Issue by lucabol** [dotnet/roslyn-analyzers#2024]
The current problems are:
1.	There are dozens Analyzers packages on Nuget with vaguely similar names, all coming from msft (i.e. I installed the Microsoft.CodeAnalysis first, which didn’t work).
2.	The Description field on Nuget, for most of the analyzers, just repeats the name of the package without explaining what it is for (i.e. Microsoft.CodeQuality.Analyzers).

I recommend removing/obsoleting other packages and/or adding meaningful Description field text.

**Comment by MelbourneDeveloper** [comment]
I'm still not sure which ones I'm supposed to use...
