### ISSUE TITLE
Freshen up the Readme for the Github repo to make it look like it is the important starting place for everything analyzers related.

### ISSUE THREAD

**Issue by lucabol** [dotnet/roslyn-analyzers#2025]
The current Readme reads more like a collection of links to other projects or the status page for a porting exercise (from FxCop). This is one of the first landing pages for search engines, so it is important.

For inspiration: look at any of the Reames [here](https://github.com/matiassingers/awesome-readme).

**Comment by TKharaishvili** [comment]
@lucabol is absolutely right!

This is only the second most important roslyn repo and it has no description and a confusing first paragraph.

The paragraph says that the repo was originally created to figure out the design of the analysis api. Is this still the main goal of the project? To me it looks more like a collection of recommended roslyn analyzers.

Overall, all this makes this project look abandoned. You guys should absolutely find time to improve it.

**Comment by Andrew-Webb** [comment]
The most important thing right now for this repo.  I asked some other devs; they are as confused as I am re. the modern face of code analysis, especially wrt .NET Core projects.

**Comment by mavasani** [comment]
The repo has been revised/rewritten by the PMs to have much better documentation and pointers to relevant docs.microsoft.com hyperlinks. Kindly re-open if this is still unclear.
