### ISSUE TITLE
Craft a blog post in a very visible place title ‘History and Roadmap for Code Analyzers in Visual Studio’

### ISSUE THREAD

**Issue by lucabol** [dotnet/roslyn-analyzers#2026]
It would be useful to have something to point customers to describing msft overall strategy for analyzers:
1. History
2. Rationale
3. Roadmap

**Comment by MelbourneDeveloper** [comment]
Absolutely!!! 100%

I was just saying this yesterday. This is part of a bigger problem of educating people about code analyzers and why they are necessary. I wrote this [blog post](https://christianfindlay.wordpress.com/2019/02/11/c-code-rules-part-1/) yesterday and wanted to fill in a section on how the code analyzers have gotten to the point that they have, but to be honest, the team responsible for code analyzers hasn't done a good job of communicating to developers what the code analyzers are, how to use them, and why they are now a NuGet package. I'm not trying to point the finger here. I'm just saying that code analyzers are far more important than people understand.

I'm hoping that the analyzers have now settled down, and Microsoft can promote them and direct every single programmer toward using them as a basic code quality measure in every project.

**Comment by Andrew-MSFT** [comment]
Thanks for the comment, this is something that is absolutely on our radar.  We need to finish documenting our new features in 2019 before it GA's, then this is next in the priority list.

cc: @mikadumont

**Comment by mavasani** [comment]
@mikadumont I believe you were already writing such a blog-post?

**Comment by Evangelink** [comment]
@mikadumont @mavasani It's been over a year, I don't know if there is something you do plan to do about it but I think this ticket could be closed as `Won't Fix`.

**Comment by mavasani** [comment]
@mikadumont @jmarolf already wrote blog posts about analyzers in the .NET SDK, and we have very good official documentation also on this top at docs.microsoft.com:

## Blogs

- https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/
- https://devblogs.microsoft.com/dotnet/how-to-write-a-roslyn-analyzer/
- https://devblogs.microsoft.com/dotnet/write-better-code-faster-with-roslyn-analyzers/

## Documentation

- https://docs.microsoft.com/dotnet/fundamentals/code-analysis/overview
- https://docs.microsoft.com/visualstudio/code-quality/install-net-analyzers
- https://docs.microsoft.com/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers
- https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers

**Comment by mavasani** [comment]
Closing this issue.
