### ISSUE TITLE
SpecializedEnumerableCreationAnalyzer does not support concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2038]
https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Roslyn.Diagnostics.Analyzers/Core/SpecializedEnumerableCreationAnalyzer.cs#L50-L51

**Comment by mavasani** [comment]
We should probably also implement this meta-analyzer: https://github.com/dotnet/roslyn-analyzers/issues/1592 and enforce it strictly in our repos.

**Comment by sharwell** [comment]
Yep, I'm seeing several minutes of CPU time building Roslyn.sln hitting this lock.
