### ISSUE TITLE
MetaCompilationAnalyzer does not support concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2041]
https://github.com/dotnet/roslyn-analyzers/blob/ba6242e405da3dba1f85d73d18c50bfb8eb7c846/src/MetaCompilation.Analyzers/Core/DiagnosticAnalyzer.cs#L311-L314

**Comment by mavasani** [comment]
Not relevant after https://github.com/dotnet/roslyn-analyzers/pull/3699
