### ISSUE TITLE
AsyncMethodNamesShouldEndInAsyncAnalyzer does not support concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2044]
https://github.com/dotnet/roslyn-analyzers/blob/ba6242e405da3dba1f85d73d18c50bfb8eb7c846/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/AsyncMethodNamesShouldEndInAsync.cs#L36-L38

**Comment by mavasani** [comment]
None of the async analyzers in the repo are implemented. We need to delete them.
