### ISSUE TITLE
ReviewUnusedParametersAnalyzer does not support concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2053]
https://github.com/dotnet/roslyn-analyzers/blob/ba6242e405da3dba1f85d73d18c50bfb8eb7c846/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs#L45-L46

**Comment by Youssef1313** [comment]
This was fixed in #3223.
I think it can be closed now.

@sharwell @mavasani
