### ISSUE TITLE
MarkMembersAsStaticAnalyzer does not support concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2055]
https://github.com/dotnet/roslyn-analyzers/blob/ba6242e405da3dba1f85d73d18c50bfb8eb7c846/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs#L42-L43

**Comment by Evangelink** [comment]
@sharwell Is there any particular way to test that the new implementation is ok to be run concurrently? I am asking this question because it seems to me that except from the collection type `HashSet` the rest of the implementation looks alright.

**Comment by mavasani** [comment]
This analyzer needs to be re-written as a symbol start analyzer. When we do so, we should ensure it is written in a thread safe way.

**Comment by Evangelink** [comment]
Fixed by #3234
