### ISSUE TITLE
DoNotUseInsecureDtdProcessingInApiDesignAnalyzer does not support concurrent execution

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2067]
https://github.com/dotnet/roslyn-analyzers/blob/ba6242e405da3dba1f85d73d18c50bfb8eb7c846/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessingInApiDesign.cs#L29-L30

**Comment by Youssef1313** [comment]
Fixed https://github.com/dotnet/roslyn-analyzers/pull/4601
