### ISSUE TITLE
FxCop rule CA1801: Review unused parameters, suppression does not work out.

### ISSUE THREAD

**Issue by Varsha1610** [dotnet/roslyn-analyzers#2087]
Analyzer package:
 Microsoft.CodeAnalysis.FxCopAnalyzers
https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers

 Package Version
 Example: v2.6.2

 Diagnostic ID:
[CA1801](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters?view=vs-2017)

 Repro steps:
1. Enable the rule and mark it as 'Error' on violation in ruleset file.
For a simple repro I have written a sample piece of code below.
 public static class TestClass
 {
   // This method violates the rule.
     [SuppressMessage("Microsoft.Performance", "CA1801:Avoid unused parameters"]
     public static string GetSomething(int first, int second)
      {
            return first.ToString(CultureInfo.InvariantCulture);
        }   
 }

Description of the issue: The rule CA1801 violation occurs in this method GetSomething( ) as the parameter second is not used. 
For a complete program and rule set file please check
https://github.com/AsraKouser/18011823
**This is a problem in our code base so my company wants this to be fixed as soon as possible, so that this violation fades away when we apply suppress code.

 Expected behavior:
 After applying the suppression message as mentioned in the code above, the violation should fade away  with this syntax.

 Actual behavior:
Even after the usage of suppress message the error is still present.
In certain cases the error will dissolve after a while, however this will fail all our build jobs, we want a fix for this issue such that error is not reported on suppression from the first build.

![1801violation](https://user-images.githubusercontent.com/47105083/51973282-435dca00-24a3-11e9-9109-27ff20f91a50.jpg)

**Comment by mavasani** [comment]
Can you execute an explicit "Build" command and then change the "Build + Intellisense" combo box to "Build Only" and confirm the error list behavior? Does it still show the diagnostic?

**Comment by mavasani** [comment]
Unable to reproduce

![vs2017 9_norepro](https://user-images.githubusercontent.com/10605811/52357794-a5f71e80-29eb-11e9-8d17-d2ea99eca234.gif)
