### ISSUE TITLE
Enable IDE0055 (formatting) in CI for VB projects

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2095]
https://github.com/dotnet/roslyn-analyzers/pull/2093 is blocked due to VB projects failing to build with IDE0055 violations in generated assembly attributes file. So, I am going to disable the formatting analyzer for VB projects until we can resolve it and unblock the PR.

**Comment by sharwell** [comment]
The steps to unblock this are listed in https://github.com/dotnet/roslyn/issues/33008#issuecomment-459714307

**Comment by Evangelink** [comment]
@mavasani If I got things right this issue seems to have been solved.

**Comment by Evangelink** [comment]
ping @mavasani

**Comment by mavasani** [comment]
@Evangelink This issue still needs to be resolved: https://github.com/dotnet/roslyn-analyzers/blob/393cbf2149d1b136cef35c78608f4e3818f8b628/src/Directory.Build.props#L20-L27
