### ISSUE TITLE
Fxcop analyzers with Azure pipeline

### ISSUE THREAD

**Issue by saxenark** [dotnet/roslyn-analyzers#2100]
Hi,

I would like to know if there is support for publishing FxCop Analyzer results/trends for builds done using Azure pipeline, and the YAML for the same if possible.

I am using msbuild with Visual Studio 2017 for ASP.NET project and contemplating using Azure pipeline for our CI/CT.

Thanks,
Anubhav.

**Comment by sukhans** [comment]
Hi Anubhav,

Short Answer - Not yet.

Long Answer
We have an External facing Extension available at https://secdevtools.azurewebsites.net/ which allows you to run a few Security checks in your Azure DevOps pipeline. 
However, it is in Private Preview and only available to try once customers sign an NDA with Microsoft.

Secondly, it does not have FXCop or Roslyn available as tools to be run via the Extension. We are internally discussing the work/timeline to enable Roslyn for External users. I do not believe we have a date for it, yet.

**Comment by mavasani** [comment]
Resolving this issue as external.
