### ISSUE TITLE
Convert previously ported security analyzers to use IOperation

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#2103]
There may be performance gains with using IOperation APIs over syntax / semantic APIs.

Related: #1075 

Uses `SyntaxNodeExtensions.GetDeclaredOrReferencedSymbol()` or `SecurityDiagnosticHelpers.GetNonEmptyParentName()`:
- [x] DoNotUseInsecureCryptographicAlgorithmsAnalyzer
- [x] DoNotUseInsecureDtdProcessingAnalyzer
- [x] DoNotUseInsecureDtdProcessingInApiDesignAnalyzer
- [x] DoNotUseInsecureXSLTScriptExecutionAnalyzer

**Comment by mavasani** [comment]
Thanks @dotpaul. I believe extensions such as https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/Extensions/SyntaxNodeExtensions.cs#L9 are evil and should be removed.

**Comment by mavasani** [comment]
@dotpaul - CA3075 let me know if you will be able to get to this soon. Otherwise, I can take this up to address the performance concern.

**Comment by mavasani** [comment]
Seems like CA3075 is doing extremely large number of invocations of `context.Compilation.GetSemanticModel`, `GetSymbolInfo` and `GetDeclaredOrReferencedSymbol` helper. All of these have extremely bad performance implications.

1. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L280-L282
2. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L329
3. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L401
4. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L474
5. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L556
6. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L688-L692
7. https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L706

**Comment by dotpaul** [comment]
@mavasani If you have easy fixes for CA3075, go for it.  I'll try to get around to rewriting the XML rules after Json.NET rules (should have everything I want from PropertySetAnalysis by then).

**Comment by mavasani** [comment]
This is done.
