### ISSUE TITLE
Consider moving AsyncPackage into DotNetAnalyzers/AsyncUsageAnalyzers

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#211]
The [DotNetAnalyzers/AsyncUsageAnalyzers](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers) project is a single-topic repository intended to contain analyzers to help developers write asynchronous code. The functionality in the AsyncPackage portion of this repository could be migrated to that repository instead to streamline the long-term development and release cycle for these analyzers.

**Comment by lgolding** [comment]
We are working on a proposal to reorganize the analyzers in the Roslyn-analyzers repo. We will address this question as part of that proposal.

@michaelcfanning This is a general problem when an analyzer can fall into two categories. Please address this as part of your proposal.

**Comment by mavasani** [comment]
Stale issue, we do not have async usage analyzers in the repo anymore.
