### ISSUE TITLE
CA1502 - AvoidExcessiveComplexity - Doesn't Work

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/roslyn-analyzers#2110]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers

This is a really fundamental code rule.

#### Package Version

Example: v2.6.3

#### Diagnostic ID

CA1502

#### Repro steps

```cs
using System;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "type", Target = "~T:ClassLibrary1.ClassLibrary1.ClassLibrary1.ColumnDataType")]

namespace ClassLibrary1
{
    namespace ClassLibrary1
    {
        namespace ClassLibrary1
        {
            public enum ColumnDataType
            {
                Date,
                DateTime,
                Boolean,
                Decimal,
                Integer,
                Text,
                Long,
                Varchar,
                Xml,
                UniqueIdentifier,
                Numeric,
                Byte,
                Geometry
            }

            public static class SqlGenerationOptions
            {
                public static bool SupportsDate { get; internal set; }
                public static bool SupportsBit { get; internal set; }
                public static bool SupportsDecimal { get; internal set; }
                public static string IntegerTypeToken { get; internal set; }
                public static string LongTypeToken { get; internal set; }
                public static bool SupportsVarchar { get; internal set; }
                public static bool SupportsXml { get; internal set; }
                public static bool SupportsUniqueIdentifier { get; internal set; }
                public static bool SupportsTinyInt { get; internal set; }
                public static bool SupportsGeometry { get; internal set; }
                public static string NoCaseTextType { get; internal set; }
                public static int? MaxVarcharLength { get; internal set; }
            }

            public class SomeClass
            {
                public string GetSqlDataType(ColumnDataType type, int length, int precision, int scale)
                {
                    string retVal;

                    var noCaseTextType = !string.IsNullOrEmpty(SqlGenerationOptions.NoCaseTextType) ? SqlGenerationOptions.NoCaseTextType : "text";

                    switch (type)
                    {
                        case ColumnDataType.Date:
                            retVal = SqlGenerationOptions.SupportsDate ? "date" : "TEXT";
                            break;

                        case ColumnDataType.DateTime:
                            retVal = SqlGenerationOptions.SupportsDate ? "datetime" : "TEXT";
                            break;

                        case ColumnDataType.Boolean:
                            retVal = SqlGenerationOptions.SupportsBit ? "bit" : "INTEGER";
                            break;

                        case ColumnDataType.Decimal:
                            retVal = SqlGenerationOptions.SupportsDecimal ? $"decimal({precision},{scale})" : "TEXT";
                            break;

                        case ColumnDataType.Integer:
                            retVal = SqlGenerationOptions.IntegerTypeToken;
                            break;

                        case ColumnDataType.Long:
                            retVal = SqlGenerationOptions.LongTypeToken;
                            break;

                        case ColumnDataType.Text:
                            retVal = noCaseTextType;
                            break;

                        case ColumnDataType.Varchar:
                            retVal = SqlGenerationOptions.SupportsVarchar ? GetVarCharDeclaration(length) : noCaseTextType;
                            break;

                        case ColumnDataType.Xml:
                            retVal = !SqlGenerationOptions.SupportsXml ? !SqlGenerationOptions.SupportsVarchar ? noCaseTextType : GetVarCharDeclaration(SqlGenerationOptions.MaxVarcharLength.Value) : "xml";
                            break;

                        case ColumnDataType.UniqueIdentifier:
                            retVal = SqlGenerationOptions.SupportsUniqueIdentifier ? "uniqueidentifier" : noCaseTextType;
                            break;

                        case ColumnDataType.Numeric:
                            retVal = "numeric";
                            break;

                        case ColumnDataType.Byte:
                            retVal = SqlGenerationOptions.SupportsTinyInt ? "tinyint" : SqlGenerationOptions.IntegerTypeToken;
                            break;

                        case ColumnDataType.Geometry:
                            retVal = SqlGenerationOptions.SupportsGeometry ? "geometry" : noCaseTextType;
                            break;

                        default:
                            throw new Exception(type + " is not a valid data type");
                    }

                    return retVal;
                }

                private string GetVarCharDeclaration(object value)
                {
                    throw new NotImplementedException();
                }

                private string GetVarCharDeclaration(int length)
                {
                    throw new NotImplementedException();
                }
            }           
        }
    }
}

```

![image](https://user-images.githubusercontent.com/16697547/52614156-e7546600-2ee4-11e9-919d-39b1b2d48b8d.png)

#### Expected behavior

The method GetSqlDataType should have an unacceptable level of cyclomatic complexity (26). It should allow a maximum of 25.

#### Actual behavior

No error/warning

**Comment by mavasani** [comment]
The analyzer computes the code complexity to be 25, instead of 26 :). As soon as you add an additional conditional, such as say the highlighted if statement below, the analyzer does report a diagnostic:

![image](https://user-images.githubusercontent.com/10605811/53268236-5460bc00-369a-11e9-8d17-3fe58b218251.png)

I feel this is an acceptable behavior from the analyzer, please re-open with justification if you disagree.

**Comment by MelbourneDeveloper** [comment]
@mavasani sorry but that's not the behavior I get:

I can't get this rule to trigger at all.

![image](https://user-images.githubusercontent.com/16697547/53268522-701b9f00-373a-11e9-984c-7c14db0194be.png)

**Comment by MelbourneDeveloper** [comment]
@mavasani also, are you aware that code metrics are broken in Visual Studio right now?

I can't actually see the cyclomatic complexity.

![image](https://user-images.githubusercontent.com/16697547/53268598-a9540f00-373a-11e9-842d-e2dc4f64dc73.png)

**Comment by mavasani** [comment]
@MelbourneDeveloper The rules are disabled by default in the analyzer package. See the second paragraph at https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017

_In addition, you can install a NuGet package that includes four code metrics analyzer rules: CA1501, CA1502, CA1505, and CA1506. These rules are disabled by default, but you can enable them from Solution Explorer or in a rule set file.**_

You should install https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/, then enable the rule via a ruleset file, say `MyRules.ruleset` with following ruleset entry:
```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Rules" Description="Rules" ToolsVersion="16.0">
  <Rules AnalyzerId="Microsoft.CodeQuality.Analyzers" RuleNamespace="Microsoft.CodeQuality.Analyzers">
    <Rule Id="CA1502" Action="Warning" />
  </Rules>
</RuleSet>
```

Your project file should have the following property:
```
  <PropertyGroup">
    <CodeAnalysisRuleSet>MyRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```

**Comment by MelbourneDeveloper** [comment]
@masavani is this required to trigger CA1502?

**Comment by MelbourneDeveloper** [comment]
Why isn't it turned on by default? How do I know which rules are turned on by default?

**Comment by mavasani** [comment]
Yes, all 4 code metrics rules are disable by default.

**Comment by mavasani** [comment]
> Why isn't it turned on by default? How do I know which rules are turned on by default?

This can lead to substantial noise for customers who don't really care about code metrics. Do you feel a more detailed step-by-step documentation around how to enable these rules will help? Tagging @gewarren as well.

Another alternative is to publish a standalone `Microsoft.CodeAnalysis.MetricsAnalyzers` package that have these rules enabled by default.

**Comment by mavasani** [comment]
Tagging @jinujoseph @vatsalyaagrawal for https://github.com/dotnet/roslyn-analyzers/issues/2110#issuecomment-466535853

**Comment by MelbourneDeveloper** [comment]
@masavani there is a lot to unpack here. @gewarren. 

What this really highlights is that there really needs to be a GUI so that the user can clearly see what is turned on and what isn't. 

However, the fact that the code metrics are now broke by default in visual studio is actually a big bug. They used to work fine without turning on any code analysis. New users won't know about this. It's just an item in the menu. They have no idea that this is tied to code analysis.

**Comment by mavasani** [comment]
By the way, we also include a rulesets that enables all Maintainability rules provided in the package. For example, `%USER_FOLDER%\.nuget\packages\microsoft.codequality.analyzers\2.6.3\rulesets\MaintainabilityRulesEnabled.ruleset` contains the following:

```
<RuleSet Name="Maintainability Rules Enabled with default action" Description="All Maintainability Rules are enabled with default action. Maintainability Rules with IsEnabledByDefault = false are force enabled with default action. Rules from a different category are disabled." ToolsVersion="15.0">
   <!-- Maintainability Rules -->
   <Rules AnalyzerId="Microsoft.CodeQuality.Analyzers" RuleNamespace="Microsoft.CodeQuality.Analyzers">
      <Rule Id="CA1501" Action="Warning" />          <!-- Avoid excessive inheritance -->
      <Rule Id="CA1502" Action="Warning" />          <!-- Avoid excessive complexity -->
      <Rule Id="CA1505" Action="Warning" />          <!-- Avoid unmaintainable code -->
      <Rule Id="CA1506" Action="Warning" />          <!-- Avoid excessive class coupling -->
      <Rule Id="CA1509" Action="Warning" />          <!-- Invalid entry in code metrics rule specification file -->
   </Rules>
   <Rules AnalyzerId="Microsoft.CodeQuality.CSharp.Analyzers" RuleNamespace="Microsoft.CodeQuality.CSharp.Analyzers">
      <Rule Id="CA1507" Action="Warning" />          <!-- Use nameof to express symbol names -->
   </Rules>
   <Rules AnalyzerId="Microsoft.CodeQuality.VisualBasic.Analyzers" RuleNamespace="Microsoft.CodeQuality.VisualBasic.Analyzers">
      <Rule Id="CA1507" Action="Warning" />          <!-- Use nameof to express symbol names -->
   </Rules>

   ...
```

The default rule configuration (enabled/disabled) is in another ruleset alongside it in the same folder: ``%USER_FOLDER%\.nuget\packages\microsoft.codequality.analyzers\2.6.3\rulesets\MaintainabilityRulesDefault.ruleset` which contains the following:

```
<RuleSet Name="Maintainability Rules with default action" Description="All Maintainability Rules with default action. Rules with IsEnabledByDefault = false or from a different category are disabled." ToolsVersion="15.0">
   <!-- Maintainability Rules -->
   <Rules AnalyzerId="Microsoft.CodeQuality.Analyzers" RuleNamespace="Microsoft.CodeQuality.Analyzers">
      <Rule Id="CA1501" Action="None" />             <!-- Avoid excessive inheritance -->
      <Rule Id="CA1502" Action="None" />             <!-- Avoid excessive complexity -->
      <Rule Id="CA1505" Action="None" />             <!-- Avoid unmaintainable code -->
      <Rule Id="CA1506" Action="None" />             <!-- Avoid excessive class coupling -->
      <Rule Id="CA1509" Action="None" />             <!-- Invalid entry in code metrics rule specification file -->
   </Rules>
   <Rules AnalyzerId="Microsoft.CodeQuality.CSharp.Analyzers" RuleNamespace="Microsoft.CodeQuality.CSharp.Analyzers">
      <Rule Id="CA1507" Action="Warning" />          <!-- Use nameof to express symbol names -->
   </Rules>
   <Rules AnalyzerId="Microsoft.CodeQuality.VisualBasic.Analyzers" RuleNamespace="Microsoft.CodeQuality.VisualBasic.Analyzers">
      <Rule Id="CA1507" Action="Warning" />          <!-- Use nameof to express symbol names -->
   </Rules>

   ...
```

**Comment by mavasani** [comment]
> However, the fact that the code metrics are now broke by default in visual studio is actually a big bug. They used to work fine without turning on any code analysis. New users won't know about this. It's just an item in the menu. They have no idea that this is tied to code analysis.

@MelbourneDeveloper can you clarify what you mean by broke by default? 
`Calculate Code Metrics` command in Visual Studio IDE still works as before and brings up the Code Metrics results window which lists the metrics in GUI.
Analyzers package with code metrics rules is just an alternative approach to compute and enforce Code metrics during build/CI, which can happen in VS or on command line.

![image](https://user-images.githubusercontent.com/10605811/53269718-73614d00-369e-11e9-8f4f-bad058584f96.png)

**Comment by mavasani** [comment]
Documentation at https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017 clearly mentions 3 alternate ways to compute code metrics:

1. `Calculate code metrics` command in VS IDE (parity with previous VS versions).
2. `Microsoft.CodeAnalysis.FxCopAnalyzers` NuGet package with code metrics rules disabled by default, which can be enabled via a ruleset file to enforce on CI.
3. `Microsoft.CodeAnalysis.Metrics` NuGet package or Metrics.exe command line tool to generate a code metrics report xml file

**Comment by MelbourneDeveloper** [comment]
@mavasani you are seeing completely different results to me. I will try to document this up for you.

**Comment by MelbourneDeveloper** [comment]
@mavasani is there an email address, or slack I can contact you on so I can separate all these issues and talk to you about them one by one?

**Comment by mavasani** [comment]
@MelbourneDeveloper What version of VS are you using? That might be the disconnect.. I am on the latest VS2019 Preview3 version https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

**Comment by MelbourneDeveloper** [comment]
@mavasani I'm on VS 2017 15.8.7

I'm sorry , but there's not much point testing in Vs2019. It's just a preview release.

**Comment by MelbourneDeveloper** [comment]
@mavasani here is an example of what I am talking about. This is a fresh .NET Framework library. No code rules. No Fx Cop:

![image](https://user-images.githubusercontent.com/16697547/53270559-2766e480-3740-11e9-831d-88fa245b52a1.png)

This is the same thing, but .NET Standard:

![image](https://user-images.githubusercontent.com/16697547/53270572-3352a680-3740-11e9-9869-080ceb75280c.png)

This is a huge bug, because users will have no idea why the functionality has changed from .NET Framework to .NET Standard.

**Comment by mavasani** [comment]
Ah that might be the reason - we completely rewrote Code Metrics from MSIL based analysis using the legacy CCI/FxCop binary analysis engine to modern Roslyn based source analysis model. This allowed us to share code between the 3 different alternative implementations mentioned above, and also enforce on CI as analyzers which run during build. I suspect you may want to try out VS2019 preview3 if you really want to try out code metrics.

Note that there is a *huge* additional plus in the new VS2019 implementation: All three approaches work on .NetStandard/.NetCore projects in VS2019, which was not the case for the old implementation targeted only to .NetFramework. Maybe that will convince you to try it out :)

**Comment by MelbourneDeveloper** [comment]
@mavasani I've been working with code for a long time. I am really invested in trying to get them to work. I am trying to document them up [here](https://christianfindlay.wordpress.com/2019/02/11/c-code-rules-part-1/). Can we have a chat about this outside GitHub?

**Comment by mavasani** [comment]
> This is a huge bug, because users will have no idea why the functionality has changed from .NET Framework to .NET Standard.

Yep, old implementation never supported .NET Standard/.NetCore - hence the rewrite to source based analysis in VS2019, which should work seamlessly independent of the project type/target framework.

**Comment by mavasani** [comment]
> Can we have a chat about this outside GitHub?

Sure, you can email me at `mavasani@microsoft.com`

**Comment by MelbourneDeveloper** [comment]
@mavasani , just so I understand this correctly, in order to enable CA1502, I would have to enable a ruleset, and include it like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Rules" Description="Rules" ToolsVersion="16.0">
  <Rules AnalyzerId="Microsoft.CodeQuality.Analyzers" RuleNamespace="Microsoft.CodeQuality.Analyzers">
    <Rule Id="CA1502" Action="Warning" />
  </Rules>
</RuleSet>
```

Is that correct?

But, as far as I understand, rulesets do not work in Visual Studio 2017 - .NET Standard/.NET Core. We have been instructed to install the FxCop Nuget pacakage, and then disable the warnings that we don't want to be told about. 

If I understand you correctly, you are saying that this is fixed in Visual Studio 2019, but in order words, CA1502 cannot be used in Visual Studio 2017. Is this correct, or am I missing something?

**Comment by mavasani** [comment]
> just so I undestand this correctly, in order to enable CA1502, I would have to enable a ruleset, and include it like this:

Yes, that is correct. Note you also need to manually edit the project file to add the ruleset to it, see the last part of https://github.com/dotnet/roslyn-analyzers/issues/2110#issuecomment-466533461.

> But, as far as I understand, rulesets do not work in Visual Studio 2017 - .NET Standard/.NET Core. We have been instructed to install the FxCop Nuget pacakage, and then disable the warnings that we don't want to be told about.

Rulesets are fully supported for .NET Standard/.NET Core in all versions of VS. It is just that the new project system for .NET Standard/.NET Core projects did not add the Code Analysis property page and other UI entry points to add ruleset to a project. See https://github.com/dotnet/project-system/issues/266 tracking adding that property page for new project system.

> If I understand you correctly, you are saying that this is fixed in Visual Studio 2019, but in order words, CA1502 cannot be used in Visual Studio 2017. Is this correct, or am I missing something?

No that is not correct. CA1502 does not work on NetCore/NetStandard projects in VS2017, it works on regular NetFramework projects.

> Please confirm that rulesets do not work in Visual Studio 2017.

This is not correct. Rulesets work completely fine and are fully supported on all project types/targets from VS2015 onwards. They work fine both in VS IDE and C#/VB compiler command line.

**Comment by MelbourneDeveloper** [comment]
@mavasani just clarifying:

> CA1502 does not work on NetCore/NetStandard projects in VS2017

Correct? There is no workaround?

**Comment by mavasani** [comment]
@jinujoseph  actually corrected me, and the true statement is:

_`Calculate Code Metrics` command does not work for NetCore/NetStandard projects in VS2017 or prior versions. This has been fixed in VS2019 and works identical for all C#/VB project types/target frameworks.
However, note that the two other alternate approaches to compute code metrics (analyzer NuGet package and command line Code metrics generation) do work fine for NetCore/NetStandard projects even in VS2017._

**Comment by MelbourneDeveloper** [comment]
@mavasani my question is about CA1502.

Is it possible to get it working for .NET Core / .NET Standard without Visual Studio 2019?

**Comment by mavasani** [comment]
> Is it possible to get it working for .NET Core / .NET Standard without Visual Studio 2019?

Yes, you can install Microsoft.CodeAnalysis.FxCopAnalyzers NuGet package, and enable CA1502 via the ruleset as I mentioned above, and it will flag violations.

**Comment by MelbourneDeveloper** [comment]
@mavasani Bingo! This works. This definitely needs to be part of the documentation. I will write this up in my blog.

![image](https://user-images.githubusercontent.com/16697547/53275711-3c4b7400-3750-11e9-872a-dfef3e07b73c.png)

**Comment by mavasani** [comment]
Awesome!

Note that with the analyzer package, the thresholds for the code metric rules on which they fire are also configurable:

1. Add a text file to your project named `CodeMetricsConfig.txt`: https://github.com/dotnet/roslyn-analyzers/blob/3bb0de8da1b17cdd2f8e39af52510a6083f1abff/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/CodeMetricsAnalyzer.cs#L43, with contents such as below, which makes CA1502 fire on complexity more than 10:
```
CA1502: 10
```
2. Mark it as an additional file in the msbuild project file: https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md#passing-an-individual-file
```
<ItemGroup>
  <AdditionalFiles Include="CodeMetricsConfig.txt" />
</ItemGroup>
```

**Comment by MelbourneDeveloper** [comment]
@mavasani thats's good to know! 

What about the dictionary file? There used to be a way to define custom words to suppress spelling error problems. 

Are spelling errors getting picked up these days?

**Comment by mavasani** [comment]
Filed https://github.com/MicrosoftDocs/visualstudio-docs/issues/2746 for Code metrics rule configuration documentation.

**Comment by mavasani** [comment]
> What about the dictionary file? There used to be a way to define custom words to suppress spelling error problems.
Are spelling errors getting picked up these days?

No, the naming rules haven't been ported yet: https://github.com/dotnet/roslyn-analyzers/issues?q=is%3Aopen+is%3Aissue+label%3AFxCop-Port-Blocked-NamingService. We have an old [PR](https://github.com/dotnet/roslyn-analyzers/pull/1111) that unblocks them and adds the word dictionary logic, but it is blocked due to implementation concerns (it is non-portable and uses a native Windows MS Office spell checker binary, so will not work on NetCore/NetStandard).

**Comment by MelbourneDeveloper** [comment]
@mavasani no problem. They are quite important. Resharper is very good at picking up spelling mistakes - even in comments. I'm trying to move away from using Resharper and Rider. FxCop is the key ingredient for being able to do this.
