### ISSUE TITLE
CA1714 false positive

### ISSUE THREAD

**Issue by abelykh0** [dotnet/roslyn-analyzers#2111]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.3

#### Diagnostic ID

[CA1714 Flags enums should have plural names](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1714-flags-enums-should-have-plural-names)

#### Repro steps

1. Create a public enum CellsetAxis

#### Expected behavior
No warning

#### Actual behavior
Warning	CA1714	Flags enums should have plural names

**Comment by mavasani** [comment]
I am not sure if CellsetAxis is a word, but I presume Humanizer flagged it as singular given Axis is singular.

**Comment by abelykh0** [comment]
Invalid, closing. Sorry.
