### ISSUE TITLE
Include attribute source in pdb

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2124]
If I understand the change well, the project referencing the analyzer package will include the file contained in the package?

If that is so, this will break Source Link validation because the file is not in the source directory, so it won't be source linked.
To fix it we should embed the source file in the PDB.

_Originally posted by @tmat in https://github.com/dotnet/roslyn-analyzers/pull/2122#issuecomment-463751763_

**Comment by genlu** [comment]
@tmat Just did a quick search around on how this can be done. It seems adding the item below to the [target file](https://github.com/dotnet/roslyn-analyzers/blob/master/nuget/PerformanceSensitive.Analyzers/Microsoft.PerformanceSensitive.Analyzers.targets) would address the sourcelink issue?

```xml
<Target Name="EmbedSources" BeforeTargets="CoreCompile">
   <ItemGroup>
      <EmbeddedFiles Include="$(PerformanceSensitiveAttributePath)" Condition="Exists($(PerformanceSensitiveAttributePath))" />
   </ItemGroup>
</Target>
```

**Comment by tmat** [comment]
Yup, adding to `EmbddedFiles` will do. Defining a target is not necessary though. You can just add to this ItemGroup next to the `Compile` item:

https://github.com/dotnet/roslyn-analyzers/pull/2122/files#diff-1fac7d702dd77a099bf78f7bdf760928R9

You can also hoist `Exists($(PerformanceSensitiveAttributePath))` condition to the ItemGroup itself.
