### ISSUE TITLE
Consider replacing WellKnownTypes with WellKnownTypeProvider everywhere

### ISSUE THREAD

**Issue by dotpaul** [dotnet/roslyn-analyzers#2132]
As it is now, `WellKnownTypes` just wraps `Compilation.GetTypeByMetadataName()` calls.  It doesn't seem like a terribly necessary layer of abstraction.

We could replace usages of `WellKnownTypes` with `WellKnownTypeProvider`.  Then at least we can have our own cache of `INamedTypeSymbols`.

**Comment by Evangelink** [comment]
@dotpaul Is there anything left to do to consider this issue as closed?

**Comment by sharwell** [comment]
I believe this was started by #2871 and finally fixed by #2932.

**Comment by dotpaul** [comment]
I think we can close this particular issue, and open a new issue if needed for considering banning `Compilation.GetTypeByMetadataName`. Thanks again @Evangelink !
