### ISSUE TITLE
LINQ syntax artificially inflates class coupling counts for CA1506

### ISSUE THREAD

**Issue by j2jensen** [dotnet/roslyn-analyzers#2133]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.6.3

#### Diagnostic ID

[CA1506](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1506-avoid-excessive-class-coupling?view=vs-2017)

#### Repro steps

Use a block of LINQ code:

    using System.Collections.Generic;
    using System.Linq;

    public static class Ca1506Tester
    {
        public static IEnumerable<int> TestCa1506()
        {
            var ints = new[] { 1, 2 };
            return from a in ints
                   from b in ints
                   from c in ints
                   from d in ints
                   from e in ints
                   from f in ints
                   from g in ints 
                   from h in ints
                   from i in ints
                   from j in ints
                   from k in ints
                   from l in ints
                   from m in ints
                   from n in ints
                   from o in ints
                   from p in ints
                   select p;
        }
    }

#### Expected behavior

In terms of code maintainability, this method is really only coupled with a handful of types (`Enumerable`, `IEnumerable<>`, `Array`, and `int`. It shouldn't trigger CA1506.

#### Actual behavior

CA1506 is triggered with a message like this:
> error CA1506: 'TestCa1506' is coupled with '60' different types from '4' different namespaces. Rewrite or refactor the code to decrease its class coupling below '41'.

Of course this example is a little contrived, but in normal methods if someone were writing a linq query navigating across object models rather than ints, LINQs tendency to artificially inflate the numbers will add to whatever natural class coupling is involved and quickly push a method or a class over its reasonable threshold.

As an implementation detail, we know that each `from` is translated to a `SelectMany` call that creates a new anonymous type. I suspect that each of these anonymous types adds a class coupling that gets counted by the rule. I don't know if it's possible to differentiate these auto-generated anonymous types from other types, but it seems like it may be reasonable to exclude anonymous types from class coupling counts generally.

**Comment by mavasani** [comment]
> it seems like it may be reasonable to exclude anonymous types from class coupling counts generally

I completely agree. Code over [here](https://github.com/dotnet/roslyn-analyzers/blob/afb82254fa022b4624c794469bf45acd17dec3fd/src/Utilities/Compiler/CodeMetrics/MetricsHelper.cs#L249) that adds named types to couple types should be updated to ignore anonymous types and/or compiler generated types. Probably also need a test [here](https://github.com/dotnet/roslyn-analyzers/blob/afb82254fa022b4624c794469bf45acd17dec3fd/src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/CodeMetricsAnalyzerTests.cs) and [here](https://github.com/dotnet/roslyn-analyzers/blob/afb82254fa022b4624c794469bf45acd17dec3fd/src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/CodeMetricsComputationTests.cs)

**Comment by j2jensen** [comment]
FYI I have a proposed fix for this ready, but am blocked on a build issue. https://github.com/dotnet/roslyn-analyzers/issues/3184

**Comment by j2jensen** [comment]
I found time tonight to add a test to `CodeMetricsAnalyzerTests.cs`. Ready for another review.
