### ISSUE TITLE
Error installing FxCop

### ISSUE THREAD

**Issue by TranstecJasonD** [dotnet/roslyn-analyzers#2142]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers

#### Package Version

v2.6.3

#### Repro steps

1. Created new WinForms VB project
2. Install package

#### Expected behavior

No errors.

#### Actual behavior

Install succeeds, but has errors. Maybe related to #1423 .

`Attempting to gather dependency information for package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3' with respect to project 'WindowsApp1', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 85.42 ms
Attempting to resolve dependencies for package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3'
Resolved actions to install package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3'
Retrieving package 'Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.3' from 'nuget.org'.
Retrieving package 'Microsoft.CodeQuality.Analyzers 2.6.3' from 'nuget.org'.
Retrieving package 'Microsoft.NetCore.Analyzers 2.6.3' from 'nuget.org'.
Retrieving package 'Microsoft.NetFramework.Analyzers 2.6.3' from 'nuget.org'.
Retrieving package 'Text.Analyzers 2.6.3' from 'nuget.org'.
Adding package 'Microsoft.CodeQuality.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.CodeQuality.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.CodeQuality.Analyzers.2.6.3' to 'packages.config'
Executing script file 'C:\Temp\WindowsApp1\packages\Microsoft.CodeQuality.Analyzers.2.6.3\tools\install.ps1'...
Successfully installed 'Microsoft.CodeQuality.Analyzers 2.6.3' to WindowsApp1
Adding package 'Microsoft.NetCore.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.NetCore.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.NetCore.Analyzers.2.6.3' to 'packages.config'
Executing script file 'C:\Temp\WindowsApp1\packages\Microsoft.NetCore.Analyzers.2.6.3\tools\install.ps1'...
Successfully installed 'Microsoft.NetCore.Analyzers 2.6.3' to WindowsApp1
Adding package 'Microsoft.NetFramework.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.NetFramework.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.NetFramework.Analyzers.2.6.3' to 'packages.config'
Executing script file 'C:\Temp\WindowsApp1\packages\Microsoft.NetFramework.Analyzers.2.6.3\tools\install.ps1'...
Successfully installed 'Microsoft.NetFramework.Analyzers 2.6.3' to WindowsApp1
Adding package 'Text.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Text.Analyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Text.Analyzers.2.6.3' to 'packages.config'
Executing script file 'C:\Temp\WindowsApp1\packages\Text.Analyzers.2.6.3\tools\install.ps1'...
Successfully installed 'Text.Analyzers 2.6.3' to WindowsApp1
Adding package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3' to folder 'C:\Temp\WindowsApp1\packages'
Added package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3' to 'packages.config'
Executing script file 'C:\Temp\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\tools\install.ps1'...
Join-Path : Cannot find path 'C:\Temp\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\analyzers' becau
se it does not exist.
At C:\Temp\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\tools\install.ps1:3 char:28
+ $analyzersPaths = Join-Path <<<<  (Join-Path (Split-Path -Path $toolsPath -Parent) "analyzers" ) * -Resolve
    + CategoryInfo          : ObjectNotFound: (C:\Temp\Windows...2.6.3\analyzers:String) [Join-Path], ItemNotFoundExce 
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Temp\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\tools\install.ps1:8 char:18
+     if (Test-Path <<<<  $analyzersPath)
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Temp\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\tools\install.ps1:38 char:39
+     $languageAnalyzersPath = join-path <<<<  $analyzersPath $languageFolder
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom 
   mand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Temp\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.3\tools\install.ps1:39 char:18
+     if (Test-Path <<<<  $languageAnalyzersPath)
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Successfully installed 'Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.3' to WindowsApp1
Executing nuget actions took 5.48 sec
Time Elapsed: 00:00:05.9774434
========== Finished ==========`

**Comment by mavasani** [comment]
This has been fixed in latest 2.6.4-beta1 packages available on myget: https://dotnet.myget.org/gallery/roslyn-analyzers

```


Attempting to gather dependency information for package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1' with respect to project 'WindowsApp2', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 483.43 ms
Attempting to resolve dependencies for package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1'
Resolved actions to install package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1'
  GET https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Text.Analyzers/2.6.4-beta1.19121.1+3c8bb88b
  GET https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.4-beta1.19121.1+3c8bb88b
  GET https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.CodeAnalysis.VersionCheckAnalyzer/2.6.4-beta1.19121.1+3c8bb88b
  GET https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.NetCore.Analyzers/2.6.4-beta1.19121.1+3c8bb88b
  GET https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.NetFramework.Analyzers/2.6.4-beta1.19121.1+3c8bb88b
  GET https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.CodeQuality.Analyzers/2.6.4-beta1.19121.1+3c8bb88b
  OK https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.CodeAnalysis.VersionCheckAnalyzer/2.6.4-beta1.19121.1+3c8bb88b 217ms
Installing Microsoft.CodeAnalysis.VersionCheckAnalyzer 2.6.4-beta1.19121.1.
  OK https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Text.Analyzers/2.6.4-beta1.19121.1+3c8bb88b 275ms
Installing Text.Analyzers 2.6.4-beta1.19121.1.
  OK https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.4-beta1.19121.1+3c8bb88b 338ms
  OK https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.NetFramework.Analyzers/2.6.4-beta1.19121.1+3c8bb88b 362ms
Installing Microsoft.NetFramework.Analyzers 2.6.4-beta1.19121.1.
Installing Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.4-beta1.19121.1.
  OK https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.NetCore.Analyzers/2.6.4-beta1.19121.1+3c8bb88b 477ms
  OK https://dotnet.myget.org/F/roslyn-analyzers/api/v2/package/Microsoft.CodeQuality.Analyzers/2.6.4-beta1.19121.1+3c8bb88b 448ms
Installing Microsoft.CodeQuality.Analyzers 2.6.4-beta1.19121.1.
Installing Microsoft.NetCore.Analyzers 2.6.4-beta1.19121.1.
Adding package 'Microsoft.CodeAnalysis.VersionCheckAnalyzer.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.CodeAnalysis.VersionCheckAnalyzer.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.CodeAnalysis.VersionCheckAnalyzer.2.6.4-beta1.19121.1' to 'packages.config'
Executing script file 'C:\repos\WindowsApp1\packages\Microsoft.CodeAnalysis.VersionCheckAnalyzer.2.6.4-beta1.19121.1\tools\install.ps1'...
Successfully installed 'Microsoft.CodeAnalysis.VersionCheckAnalyzer 2.6.4-beta1.19121.1' to WindowsApp2
Adding package 'Microsoft.CodeQuality.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.CodeQuality.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.CodeQuality.Analyzers.2.6.4-beta1.19121.1' to 'packages.config'
Executing script file 'C:\repos\WindowsApp1\packages\Microsoft.CodeQuality.Analyzers.2.6.4-beta1.19121.1\tools\install.ps1'...
Successfully installed 'Microsoft.CodeQuality.Analyzers 2.6.4-beta1.19121.1' to WindowsApp2
Adding package 'Microsoft.NetCore.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.NetCore.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.NetCore.Analyzers.2.6.4-beta1.19121.1' to 'packages.config'
Executing script file 'C:\repos\WindowsApp1\packages\Microsoft.NetCore.Analyzers.2.6.4-beta1.19121.1\tools\install.ps1'...
Successfully installed 'Microsoft.NetCore.Analyzers 2.6.4-beta1.19121.1' to WindowsApp2
Adding package 'Microsoft.NetFramework.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.NetFramework.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.NetFramework.Analyzers.2.6.4-beta1.19121.1' to 'packages.config'
Executing script file 'C:\repos\WindowsApp1\packages\Microsoft.NetFramework.Analyzers.2.6.4-beta1.19121.1\tools\install.ps1'...
Successfully installed 'Microsoft.NetFramework.Analyzers 2.6.4-beta1.19121.1' to WindowsApp2
Adding package 'Text.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Text.Analyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Text.Analyzers.2.6.4-beta1.19121.1' to 'packages.config'
Executing script file 'C:\repos\WindowsApp1\packages\Text.Analyzers.2.6.4-beta1.19121.1\tools\install.ps1'...
Successfully installed 'Text.Analyzers 2.6.4-beta1.19121.1' to WindowsApp2
Adding package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1' to folder 'C:\repos\WindowsApp1\packages'
Added package 'Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1' to 'packages.config'
Executing script file 'C:\repos\WindowsApp1\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.6.4-beta1.19121.1\tools\install.ps1'...
Successfully installed 'Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.4-beta1.19121.1' to WindowsApp2
Executing nuget actions took 2.18 sec
Time Elapsed: 00:00:02.7812265
========== Finished ==========
```
