### ISSUE TITLE
CA1016 false positive

### ISSUE THREAD

**Issue by abelykh0** [dotnet/roslyn-analyzers#2143]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.3

#### Diagnostic ID

[CA1016](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1016-mark-assemblies-with-assemblyversionattribute)

#### Repro steps

1. Build project from here https://github.com/abelykh0/FxCopIssue using VS2017 15.9.7

#### Expected behavior
No warning

#### Actual behavior
Warning	CA1016	Mark assemblies with assembly version

**Comment by RobSiklos** [comment]
Strange - if you take out all the CSHTML files (so it's a regular compile instead of `RazorCoreCompile`), the warning does not fire. Either way, it's a false positive, since if you look at the resulting assembly, the AssemblyVersion attribute is clearly present.

**Comment by RobSiklos** [comment]
@mavasani Any update on this one? We're still seeing it in the latest 2.9.4 beta. Thanks!
