### ISSUE TITLE
Can you please update extension in marketplace?

### ISSUE THREAD

**Issue by Krakean** [dotnet/roslyn-analyzers#2147]
Subj.
Currently, on visual studio marketplace this extension has 2.6.0 version. Can you please update it to 2.6.3? Or may be release 2.6.4 (its ~200 commits since 2.6.3, after all) and update it on marketplace?

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2034
