### ISSUE TITLE
Ensure DisposeAnalysis does not flag using declarations

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2152]
Due to https://github.com/dotnet/roslyn/issues/32100, there will no IOperation indicating using declarations in IOperation tree or ControlFlowGraph. We need to make sure we bail out successfully for dispose analysis for using declarations.

**Comment by mavasani** [comment]
We will apply a workaround for this in 2.9.x release, and revert the workaround once we move to a Microsoft.CodeAnalysis version that contains the fix for  dotnet/roslyn#32100

**Comment by mavasani** [comment]
Workaround has been added. Reverting the workaround is blocked on compiler bug.

**Comment by Evangelink** [comment]
Ticket on compiler side is closed. @mavasani Shall we simply revert the workaround you have put in place?

**Comment by mavasani** [comment]
Yep, please do ensure we have tests validating/unskipped for the behavior.
