### ISSUE TITLE
Code Analysis Security Rules CA2100 and CA2105 are not working in Asp.net Core project

### ISSUE THREAD

**Issue by mrlokeshagarwal** [dotnet/roslyn-analyzers#2157]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.3

#### Diagnostic ID

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2100-review-sql-queries-for-security-vulnerabilities?view=vs-2017
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2105-array-fields-should-not-be-read-only?view=vs-2017

#### Repro steps

1. Adding a new .Net Core 2.0 project
2. Adding Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.3 package into project
3. Setting the Severity of CA2100 and CA2105 as Error
4. Adding code to produce CA2100 or CA2105
5. Running Code analysis on this project

#### Expected behavior
Code Analysis should show CA2100 or CA2105 as violation (Error) and Error should be thrown
#### Actual behavior
Nothing happens and Code successfully builds.

**Comment by mavasani** [comment]
CA2105: Dupe of https://github.com/dotnet/roslyn-analyzers/issues/484, which has been Won't fix with the justification in the notes in that issue.

CA2100: Has been implemented in 2.9.x version of the package, which has not been released yet. You can try a pre-release version from this feed: https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers

**Comment by mavasani** [comment]
Tagging @dotpaul as well

**Comment by mrlokeshagarwal** [comment]
@mavasani : I am getting following error while using FxCopAnalyzer pre-release version:

'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'.

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn-analyzers/issues/2003#issuecomment-453661844

**Comment by mrlokeshagarwal** [comment]
That worked Thanks....
One more question..
Do we have some information about which of the following rules are not supported in FxCopAnalyzer 2.6.3 version?

https://docs.microsoft.com/en-us/visualstudio/code-quality/rule-set-reference?view=vs-2017

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn-analyzers/pull/1718#issuecomment-396423976. Also tagging @gewarren in case we have this information somewhere on docs.microsoft.com.

**Comment by mrlokeshagarwal** [comment]
Following documentation says that FxCopAnalyzers support all security rules, but i doubt if all of them works:

https://docs.microsoft.com/en-us/visualstudio/code-quality/security-rules-rule-set-for-managed-code?view=vs-2017

**Comment by mrlokeshagarwal** [comment]
@mavasani : #1718 does not have information if CA2100 or CA2105 are supported by FxCopAnalyzer 2.6.3. Now it is very difficult to tell somebody that FXCopAnalyzer is  analyzing and reporting all the security warning/ errors. Is there a way to know which security rules are supported by FxCopAnalyzer 2.6.3 and which will be available in future release?

**Comment by mavasani** [comment]
@mrlokeshagarwal A missing entry in the `SecurityRulesDefault.ruleset` in the rulesets folder for FxCop analyzers package indicates that rule has not been implemented in that package. I verified 
CA2100 or CA2105 are not implemented in 2.6.3 (and no entry in `SecurityRulesDefault.ruleset`). However, the entry for CA2100 is indeed present in `\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.0-beta1.19119.1\rulesets\SecurityRulesDefault.ruleset`, which confirms its presence in this package:

```<Rule Id="CA2100" Action="Warning" />          <!-- Review SQL queries for security vulnerabilities -->```

**Comment by mavasani** [comment]
I also noted that the latest 2.9.x pre-release package for https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers is showing up as one from last July (2.9.0-beta1-63118-01), but we actually published a newer one last week (2.9.0-beta1.19119.1+858ae74c). @mrlokeshagarwal can you try the later one? I have requested @JoeRobich to help fix the incorrect latest prerelease package on myget.

**Comment by mrlokeshagarwal** [comment]
@mavasani : Thanks for your reply. I checked and noticed that most of the security rules mentioned in following URLs are not implemented then:

https://docs.microsoft.com/en-us/visualstudio/code-quality/security-rules-rule-set-for-managed-code?view=vs-2017

**Comment by mavasani** [comment]
@mrlokeshagarwal Note that large number of those rules have been cut as either they are not relevant anymore or not important enough. See https://github.com/dotnet/roslyn-analyzers/blob/master/docs/FxCopPort/RulesInventory.csv for notes on the rules and let us know if there is rule that you feel is super important, not deprecated and still not been ported. Tagging @dotpaul as well.

**Comment by mavasani** [comment]
For example, I know for sure that rules related to transparent code have surely been deprecated.

**Comment by mrlokeshagarwal** [comment]
When (2.9.0-beta1.19119.1+858ae74c) will be available as stable version?

**Comment by mavasani** [comment]
We are working on last few set of features and performance/functionality bugs. Hopefully in a month or so.

**Comment by mrlokeshagarwal** [comment]
Thanks @mavasani , Can we add "CA2210: Assemblies should have valid strong names" as a part of this release as i cannot see it right now?

**Comment by mavasani** [comment]
CA2210 has been deprecated and cut. See https://github.com/dotnet/roslyn-analyzers/issues/532

**Comment by mavasani** [comment]
More specifically: https://github.com/dotnet/roslyn-analyzers/issues/532#issuecomment-206584299

**Comment by mavasani** [comment]
Closing this issue as there is nothing else actionable here, and we have separate issues to track further feature requests.

**Comment by gewarren** [comment]
@mrlokeshagarwal We have a new page that tracks all the rules that have been ported to FxCop analyzers. SEe https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status?view=vs-2019.
