### ISSUE TITLE
NullReferenceException in CSharpRethrowToPreserveStackDetailsAnalyzer

### ISSUE THREAD

**Issue by RobSiklos** [dotnet/roslyn-analyzers#2167]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
and
[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v2.6.3, v2.6.4-dev, and [v2.9.0-beta1-63118-01](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeQuality.Analyzers)

#### Diagnostic ID

CSharpRethrowToPreserveStackDetailsAnalyzer

#### Repro steps

Reproduced using VS 15.9.4 and VS 16.0.0 Preview 4.

1. New c# project
1. Add Microsoft.CodeAnalysis.FxCopAnalyzers package (or Microsoft.CodeQuality.Analyzers if using .net core)
1. Run the analyzer against the following code:

```
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        private void CSharpRethrowToPreserveStackDetailsAnalyzer_Fail(Exception exception)
        {
            try
            {
            }
            catch
            {
                var finalException = new InvalidOperationException("barf", exception);
                throw finalException;
            }
        }
    }
}
```

#### Expected behavior
Analyzer runs properly

#### Actual behavior

> Warning  AD0001  Analyzer 'Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines.CSharpRethrowToPreserveStackDetailsAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.   ClassLibrary1  1   Active   Analyzer 'Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines.CSharpRethrowToPreserveStackDetailsAnalyzer' threw the following exception:
> 'Exception occurred with following context:
> Compilation: ClassLibrary1
> SyntaxTree: C:\Users\robs\Documents\Visual Studio\Projects\ClassLibrary1\Class1.cs
> SyntaxNode: throw finalException; [ThrowStatementSyntax]@[1521..1542) (45,16)-(45,37)
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines.CSharpRethrowToPreserveStackDetailsAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44\`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple\`2 data)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action\`1 analyze, TArg argument, Nullable\`1 info)
> \-----
> '.

**Comment by RobSiklos** [comment]
Problem is here: https://github.com/dotnet/roslyn-analyzers/blob/93d734cc0550f2a19f90bfb2824cd6d4da5e1829/src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRethrowToPreserveStackDetails.cs#L44

`catchClause.Declaration` is `null`.

**Comment by RobSiklos** [comment]
@genlu, @mavasani - just want to draw your attention to this one, since it's crashing the analyzers, and looks like it hasn't been triaged yet.

**Comment by genlu** [comment]
@RobSiklos Thanks for the feedback! I will take a look.
