### ISSUE TITLE
CA1508 (AvoidDeadConditionalCode) false positives

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2180]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.0-beta1.19158.2+85a05d0e)

#### Package Version

Example: 2.9.0-beta1.19158.2+85a05d0e

#### Diagnostic ID

Example: [CA1508](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers.Exp/Microsoft.CodeQuality.Analyzers.Exp.md#ca1508-avoid-dead-conditional-code)

#### Repro steps

1. Checkout https://github.com/mavasani/roslyn-analyzers/commit/46b462b69d862615d9ae383c369d17f45fd68962 from https://github.com/mavasani/roslyn-analyzers/tree/Dogfood
2. Restore and build solution

#### Actual behavior
CA1508 false positives:
- [ ] Identical nested null checks separated by a lock: https://github.com/dotnet/roslyn-analyzers/blob/ac2cae9dd4807007e7ae0d25884a3d734703636d/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs#L150
- [ ] Comparison of properties accessed of different indexed instances, for example `matches[1].Item2 == SpanEndString` is flagged in https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/tools/AnalyzerCodeGenerator/template/src/Test/Utilities/MarkupTestFile.cs#L92
- [ ] Compiler generated null check for disposable allocation within a using statement is flagged: https://github.com/mavasani/roslyn-analyzers/commit/f61555f8ba0937b584b5aee8bc6f0bb15e70ce99#diff-31e3f1f9cf668cc6e0fde9ca921d6568R71

**Comment by neolution-ch** [comment]
Thanks for updating @mavasani. But we noticed, the rule even seems to not exist anymore

![image](https://user-images.githubusercontent.com/5662575/63838892-896a0600-c97e-11e9-974c-6bbb2b478d6c.png)
