### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers output to xml

### ISSUE THREAD

**Issue by saxenark** [dotnet/roslyn-analyzers#2188]
Hi,

Is it possible to output the analyzer result to an XML which can be published by a Jenkins plugin? I am using VS 2017 with dotnet core 2.2

Thanks

**Comment by mavasani** [comment]
You can use /errorlog compiler switch OR ‘ErrorLog’ msbuild property to specify a json file to which all diagnostics are logged. See https://github.com/dotnet/roslyn/blob/master/docs/compilers/Error%20Log%20Format.md
