### ISSUE TITLE
Status of the XmlDocumentationComments.Analyzers Package

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/roslyn-analyzers#2194]
The XmlDocumentationComments.Analyzers package has not been updated since 2016 and I'm unable to figure out if it's been replaced by a different one or something else?

**Comment by mavasani** [comment]
This package has been deprecated and the rules within it have been moved to different package(s). Which specific rule are you looking for?

**Comment by SamuelEnglard** [comment]
Any having to do with XML documentation.

**Comment by mavasani** [comment]
Tagging @sharwell - I believe your best bet for xml documentation related syntax analyzers is [StypeCopAnalyzers](https://www.nuget.org/packages/StyleCop.Analyzers/1.1.1-rc.114)

**Comment by sharwell** [comment]
We also have [DotNetAnalyzers.DocumentationAnalyzers](https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers) with some additional rules and refactorings.

**Comment by SamuelEnglard** [comment]
I tried [StyleCop.Analyzers](https://www.nuget.org/packages/StyleCop.Analyzers/1.1.1-rc.114) but getting it down to just the documentation rules was driving me nuts. I'll need to give [DotNetAnalyzers.DocumentationAnalyzers](https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers) a look, thanks!

**Comment by SamuelEnglard** [comment]
I'm using [DotNetAnalyzers.DocumentationAnalyzers](https://www.nuget.org/packages/DotNetAnalyzers.DocumentationAnalyzers) for now so I'm closing this.

**Comment by sharwell** [comment]
@SamuelEnglard please feel free to file issues on that repository if you think of new rules that could be valuable.
