### ISSUE TITLE
PublicApiAnalyzer Fix All duplicate entries for partial types

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2195]
#### Analyzer package

Example: DotNetAnalyzers.PublicApiAnalyzer

#### Package Version

Example: 2.9.0-beta1.19162.2+321600d1

#### Repro steps

Tested in Visual Studio 2017 version 15.9.8.

1. Create a public partial type with parts in multiple files
1. Delete the contents of the Public API files
1. Apply a Fix All operation to add all the missing APIs

#### Expected behavior

The partial type appears once in PublicAPI.Unshipped.txt.

#### Actual behavior

The partial type appears once in PublicAPI.Unshipped.txt for each part.

**Comment by mavasani** [comment]
@drewnoakes @genlu we have had bunch of reports of this duplicate entries issue now..

**Comment by RussKie** [comment]
Hitting this issue now adding the analyser to the winforms repo, pretty annoying.

**Comment by josh-degraw** [comment]
Also still having this issue. Note that at least in my experience, it not only adds an entry for the class for each part, but also if there's no explicit constructor it also adds a constructor entry for each type part found.

**Comment by josh-degraw** [comment]
Any traction on this at all? It's been a year since this issue was posted and still no resolution, even with the `Urgency-Soon` tag.
