### ISSUE TITLE
Update repo's Readme with information about new analyzer packages

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2198]
Current names:
- [x] Microsoft.CodeAnalysis.BannedApiAnalyzers
- [x] Microsoft.CodeAnalysis.PublicApiAnalyzers
- [ ] Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers

**Comment by Evangelink** [comment]
@mavasani Are you planning to do some work on this? If not it's probably better to close it.

**Comment by mavasani** [comment]
We should add this information in the repo readme

**Comment by Evangelink** [comment]
As far as I can tell PublicApiAnalzyers is already listed here (https://github.com/dotnet/roslyn-analyzers/blob/master/README.md#microsoftcodeanalysispublicapianalyzers) and PerformanceSensitiveAnalyzers is not yet available publicly so I don't see much to do.

**Comment by mavasani** [comment]
Sounds good, thanks for checking.
