### ISSUE TITLE
Can't access the gitter chat room

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn-analyzers#2199]
I can't access the gitter chat room mentioned in the readme.

The link is taking me to the page displaying this:
![image](https://user-images.githubusercontent.com/4363170/54234869-7460fe00-4529-11e9-8826-6737170b191f.png)

**Comment by mavasani** [comment]
Not sure if anyone in the team is active on gitter anymore :) Is that correct @jinujoseph?

@TKharaishvili Did you have any specific question we can answer?

**Comment by TKharaishvili** [comment]
@mavasani 
Shouldn't the link be removed from readme in that case?

This question comes from the fixer I was implementing for another issue.
I was analyzing the following linq extension method call in both C# and VB
```C#
someList.First()
```
When getting the corresponding `IInvocationExpression` the `Arguments` array contained one element for the C# version and no elements for the VB version. I'm not really sure how big a problem this really is, but it does seem to violate Liskov's substitution principle.

My question is - is accessing the `Arguments` array the correct way of getting the expression the extension method was invoked on? (The `someList` part in this case) And if not, what is the correct way?

**Comment by TKharaishvili** [comment]
Ok, so I found the answer to my question documented in one of Roslyn issues - https://github.com/dotnet/roslyn/issues/23625

But I'll keep this issue open, 'cause I still think the gitter link should be removed from readme if it's no longer active.

**Comment by genlu** [comment]
I have removed the link
