### ISSUE TITLE
Unlist/Delete/Rename Text.Analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2200]
This package does not match the naming conventions used by other packages published from this repo (prefixed with `Microsoft.`) and also has no implemented analyzers as of now. We should remove the package dependency to it from FxCop analyzers NuGet package, unlist the package from NuGet.org, and in future when we bring up rules in it, add back the dependency with a better name.

**Comment by JoeRobich** [comment]
All versions of Text.Analyzers have been unlisted from NuGet.org

**Comment by flcdrg** [comment]
This has broken the usage of Microsoft.CodeAnalysis.FxCopAnalyzers 2.6.0-beta2 (which the the support version of analyzers for VS 2015).

Now, adding this to a 2015 project results in version 2.6.4 of Text.Analyzers being imported, which then fails as this newer version is not compatible with 2015.

**Comment by JoeRobich** [comment]
Hi @flcdrg,

Sorry for causing you trouble. I have relisted the 2.6.0-beta2 Text.Analyzers package, but it may take a little time to propagate. Please let us know if it gives you anymore problems.

-Joey
