### ISSUE TITLE
Can't suppres CA1724 and CA1812 in Source or In Suppression file from UI

### ISSUE THREAD

**Issue by xmarshal** [dotnet/roslyn-analyzers#2216]
#### Analyzer package

 [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.3 v2.9.0-beta1

#### Diagnostic ID

[CA1724](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1724-type-names-should-not-match-namespaces?view=vs-2019)
[CA1812](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1812-avoid-uninstantiated-internal-classes?view=vs-2019)

#### Expected behavior
be able to suppress warnings from UI in source or in Suppression file from UI
#### Actual behavior
no way to suppress warnings

**Comment by xmarshal** [comment]
![ca1724](https://user-images.githubusercontent.com/20635560/54492202-fe78e000-48f6-11e9-9a44-f2f1cfd5b985.png)

**Comment by mavasani** [comment]
Can you switch the error list filter from “Build+Intellisense” to “Intellisense” and try right clicking from error list again? Note that Build diagnostics are not suppresible. Also note that you can suppress diagnostics by double clicking in error list and then in the editor invoke the light bulb menu with Ctrl + . Keys to see the suppression menu items.

**Comment by xmarshal** [comment]
Ctrl + . key not provide Supress CA..... =>menu items

**Comment by xmarshal** [comment]
![ca1812](https://user-images.githubusercontent.com/20635560/54494129-c202af80-4909-11e9-8a5a-fba8f2c6ee87.png)

**Comment by xmarshal** [comment]
if I use [SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")] in code it works.

**Comment by xmarshal** [comment]
and why if I choose Suppress in Source suppressions available only with pragma

**Comment by xmarshal** [comment]
what can I do next?

**Comment by mavasani** [comment]
Does this work if you downgrade CA1724 to a warning instead of an error?

**Comment by xmarshal** [comment]
for CA1724 and CA1812 its no helps

**Comment by mavasani** [comment]
The issue seems to be CA1724 and CA1812 are both compilation end analyzers, and we don't run them in live analysis anymore, primarily because they are expensive for live analysis and need the whole compilation to be analyzed before diagnostics are reported. https://github.com/dotnet/roslyn-analyzers/issues/2267 tracks rewriting CA1812 as a non-compilation end analyzer, which should fix the issue for that diagnostic. For CA1724, unfortunately you will have to manually add suppressions.

**Comment by nguyenphuphi33** [comment]
I would be nice to have an example of how to suppress this manually in the GlobalSuppressions.cs file?
