### ISSUE TITLE
Unit tests not working correctly

### ISSUE THREAD

**Issue by TKharaishvili** [dotnet/roslyn-analyzers#2233]
If you go to one of the fixer test classes, for example - `TestForEmptyStringsUsingStringLengthFixerTests` and change the expected output for one of the unit tests, the test will still succeed. (Giving a false positive)

I think the following line is to blame for this -
https://github.com/dotnet/roslyn-analyzers/blob/master/src/Test.Utilities/CodeFixTestBase.cs#L173

This might be a serious problem as the validity of pull requests is checked by running those tests.

**Comment by mavasani** [comment]
@TKharaishvili thanks for the report. This might have broken with one of my recent branch merges. Would you be up for submitting a PR to fix it? Otherwise, I can get to it tomorrow.

**Comment by TKharaishvili** [comment]
@mavasani sure

**Comment by TKharaishvili** [comment]
@mavasani here's the PR - https://github.com/dotnet/roslyn-analyzers/pull/2234

I hope I've made the correct change.

**Comment by TKharaishvili** [comment]
Since the PR was accepted I'm closing the issue.
