### ISSUE TITLE
Suppressed in code with SuppressMessageAttribute do not working

### ISSUE THREAD

**Issue by xmarshal** [dotnet/roslyn-analyzers#2235]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.3

#### Diagnostic ID

Any

#### Repro steps

1. Compile projetc with any CA issue
2. Select Supress in Source 

#### Expected behavior
diagnostic issue suppressed in code with SuppressMessageAttribute
#### Actual behavior
diagnostic issue suppressed in code with pragma

**Comment by genlu** [comment]
@xmarshal Just to clarify, are you using ErrorList in Visual Studio to suppress the diagnostics? 
@heejaechang This behavior is by design, right?

**Comment by xmarshal** [comment]
@genlu I use "Microsoft.CodeAnalysis.FxCopAnalyzers", use Resharper, use VS sugession and use ErrorList, for all methods I can't supress in Source with SuppressMessageAttribute

**Comment by Gav-Brown** [comment]
@xmarshal For Visual Studio this will be resolved by dotnet/Roslyn#17218

**Comment by mavasani** [comment]
@Gav-Brown is correct. Resolving as external.
