### ISSUE TITLE
Metrics.MetricsOutputWriter null reference exception on vb.net projects

### ISSUE THREAD

**Issue by mscham** [dotnet/roslyn-analyzers#2242]
\src\Tools\MetricsOutputWriter.cs
head branch

This might be because I pointed metric.exe at a vb.net solution that's been upgraded through different versions of .net for a decade...

Several of my vb.net projects end up with weird namespaces of xxx.xxx.My.MyComputer or xxx.xxx.My.MyProject.  These pseudo? elements (no code files) get passed into MetricsOutputWriter.WriteMetricData and end up causing an exception in writeHeader().
They enter the case statement there and match on SymbolKind.Property.
Then a nullref exception gets thrown on the following line because location.SourceTree is null:
writer.WriteAttributeString("File", location.SourceTree.FilePath); 

I wrapped this line in a null check and the exe was able to successfully process all my projects.

#### Expected behavior
Metrics.exe writes all metric data to output xml file for all projects when pointed at a solution file.
#### Actual behavior
Metrics.exe output throws an exception while writing output file.

**Comment by genlu** [comment]
@mscham Thanks for report this issue! Could you please explain what does this mean?

>Several of my vb.net projects end up with weird namespaces of xxx.xxx.My.MyComputer or xxx.xxx.My.MyProject.

**Comment by mscham** [comment]
For example the output of the Metrics tool shows them as below.  I
substituted 'UNKNOWN' for the File values in the Method element to work
around the issue.
But these projects don't have these classes defined - there are no code
files and text search across the projects returns no hits for these types
or any of their members.
I thought it might be something to do with Application.myapp files
generated by visual studio but that doesn't seem to be the case since there
are some projects that do not wind up with these MyApplication, MyComputer,
etc... types.
The namespaces for these always show up as <AssemblyName>.My, so for
example Core.dll would wind up with a namespace of  Core.My that would have
all these phantom types.

              <NamedType Name="MyApplication">
                <Metrics>
                  <Metric Name="MaintainabilityIndex" Value="100" />
                  <Metric Name="CyclomaticComplexity" Value="1" />
                  <Metric Name="ClassCoupling" Value="0" />
                  <Metric Name="DepthOfInheritance" Value="2" />
                  <Metric Name="LinesOfCode" Value="0" />
                </Metrics>
              </NamedType>
              <NamedType Name="MyComputer">
                <Metrics>
                  <Metric Name="MaintainabilityIndex" Value="100" />
                  <Metric Name="CyclomaticComplexity" Value="1" />
                  <Metric Name="ClassCoupling" Value="0" />
                  <Metric Name="DepthOfInheritance" Value="3" />
                  <Metric Name="LinesOfCode" Value="0" />
                </Metrics>
                <Members>
                  <Method Name="Sub MyComputer.New()" File="UNKNOWN"
Line="1">
                    <Metrics>
                      <Metric Name="MaintainabilityIndex" Value="100" />
                      <Metric Name="CyclomaticComplexity" Value="1" />
                      <Metric Name="ClassCoupling" Value="0" />
                      <Metric Name="LinesOfCode" Value="0" />
                    </Metrics>
                  </Method>
                </Members>
              </NamedType>
              <NamedType Name="MyProject">
                <Metrics>
                  <Metric Name="MaintainabilityIndex" Value="100" />
                  <Metric Name="CyclomaticComplexity" Value="4" />
                  <Metric Name="ClassCoupling" Value="8" />
                  <Metric Name="DepthOfInheritance" Value="0" />
                  <Metric Name="LinesOfCode" Value="0" />
                </Metrics>
                <Members>
                  <Property Name="Property MyProject.Computer As
MyComputer" File="UNKNOWN" Line="1">
                    <Metrics>
                      <Metric Name="MaintainabilityIndex" Value="100" />
                      <Metric Name="CyclomaticComplexity" Value="1" />
                      <Metric Name="ClassCoupling" Value="1" />
                      <Metric Name="LinesOfCode" Value="0" />
                    </Metrics>
                    <Accessors>
                      <Method Name="Property Get MyProject.Computer() As
MyComputer" File="UNKNOWN" Line="1">
                        <Metrics>
                          <Metric Name="MaintainabilityIndex" Value="100" />
                          <Metric Name="CyclomaticComplexity" Value="1" />
                          <Metric Name="ClassCoupling" Value="1" />
                          <Metric Name="LinesOfCode" Value="0" />
                        </Metrics>
                      </Method>
                    </Accessors>
                  </Property>
                  .....
              <NamedType Name="MyWebServices">
                <Metrics>
                  <Metric Name="MaintainabilityIndex" Value="100" />
                  <Metric Name="CyclomaticComplexity" Value="7" />
                  <Metric Name="ClassCoupling" Value="1" />
                  <Metric Name="DepthOfInheritance" Value="1" />
                  <Metric Name="LinesOfCode" Value="0" />
                </Metrics>
                <Members>
                  <Method Name="Function MyWebServices.Equals(o As Object)
As Boolean" File="UNKNOWN" Line="1">

**Comment by genlu** [comment]
Hmm, would you be able to provide a repro project for us to investigate?

**Comment by mscham** [comment]
https://github.com/mscham/metrics-demo

I included the output of running the tool against the project.
Again 'UNKNOWN' in the output file would signal where Metrics would
normally error out.

The project/solution was created with vs2015, that might be important...I
don't know.
