### ISSUE TITLE
Analyzer (version 2.9) thows exceptions in warning AD0001 concerning Feature 'Flow-Analysis

### ISSUE THREAD

**Issue by JRBonnema** [dotnet/roslyn-analyzers#2244]
#### Analyzer package

After installing version 2.9.0 on one of my projects (.Net Framework 4.72) today I get many warnings AD0001 that the analyzer is throwing exceptions. In 2.6.3 there was no sign of this. I don't understand why this is happening.  

CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'.

**Comment by slubowsky** [comment]
See https://github.com/dotnet/roslyn-analyzers/issues/2243

**Comment by 333fred** [comment]
@JRBonnema what verison of VS are you using?

**Comment by JRBonnema** [comment]
333fred : VS 2017 : version 15.9.10

**Comment by genlu** [comment]
v2.9.1 is published to nuget.org. The required feature flag is now added in analyzer's props file, which should avoid this issue when using VS 15.9. Please give it a try. Thanks!

**Comment by JRBonnema** [comment]
genlu : I upgraded to v2.9.1 and the problem is solved now. As far as I'm concerned you can close the issue.

**Comment by robsonj** [comment]
I still see the issue with v2.9.1

**Comment by genlu** [comment]
@robsonj That's odd. The props file included in 2.9.1 packages should all contains the feature flag. Could you crack open the nupkg file for the package you were referencing (they are just zip file with a different suffix) and check the *.props file under build sub-directory? Do you see the the property like below at the bottom of the file?

```
  <PropertyGroup>
    <Features>$(Features);flow-analysis</Features> 
  </PropertyGroup>
```

**Comment by hudecekd** [comment]
Hello I have similar problem. I have 2.9.1 version. **PropertyGroup** is in prop file. I have found out that only one project uses **Microsoft.CodeAnalysis.FxCopAnalyzers** but all other projects which referenc this "base" project automatically use Code Analysis too. Maybe it is feature?
In any case I can see this error
Warning	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'

I have added nuget package **Microsoft.CodeAnalysis.FxCopAnalyzers** to all other projects, did clean rebuild and exception is gone. Maybe it will help you.

**Comment by mavasani** [comment]
You need to add the NuGet package reference with PrivateAssets ‘All’. See https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by hudecekd** [comment]
Thanks mavasani for that. I didn't know about it. Still it serves as a point how to simulate exception in analyzer so maybe it can help to track error in analyzer.

**Comment by genlu** [comment]
@hudecekd What version of VS are you using? Also what version of compiler package are you using (if you are using the toolset compiler instead of the one in-box)?

**Comment by hudecekd** [comment]
VS 2017
Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.1
I have set PrivateAssets to "all" and add nuget package Microsoft.CodeAnalysis.FxCopAnalyzers to all projects and warning is gone. So I think you can reproduce it when you have projectA which references projectB and projectB uses Microsoft.CodeAnalysis.FxCopAnalyzers and PrivateAssets is not set.

**Comment by laurentiustamate94** [comment]
@imaramos you can define a `Build.props` in which you include the packages you want.
in csproj you will have
```xml
    <None Update="{PROJECT_NAME}.props">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>build\</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </None>
```

and then in the `{PROJECT_NAME}.props` file you will have
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

In this way you will not declare the dependecy in the NuGet package you are building but you will end up including it at build in the targeted csproj and the restore will kick in. Hope this solves your problem 🤞
