### ISSUE TITLE
FxCop is throwing strange warnings with new release v2.9.0

### ISSUE THREAD

**Issue by GammaFour** [dotnet/roslyn-analyzers#2248]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers
#### Package Version

v2.9.0

#### Diagnostic ID

2>CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'.
2>CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'.

#### Repro steps

1. Download new v2.9.0 package on top of a project with no errors and no warnings.
2. Compile
3. Get warnings.

#### Expected behavior

No warnings when running on clean code.  At the very least, if there's a problem with my code, then tell me what line the problem is on and what the problem is.

**Comment by slubowsky** [comment]
See https://github.com/dotnet/roslyn-analyzers/issues/2243

**Comment by genlu** [comment]
v2.9.1 is published to nuget.org. The required feature flag is now added in analyzer's props file, which should avoid this issue when using VS 15.9. Please give it a try. Thanks!
