### ISSUE TITLE
MarkMembersAsStatic should not use a compilation end analyzer

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2267]
#### Diagnostic ID

CA1822

#### Repro steps

1. Write code that would flag CA1822
2. Open the code in Visual Studio

#### Expected behavior

CA1822 appears in the IDE.

#### Actual behavior

CA1822 is not reported because the analyzer relies on compilation end actions.

**Comment by mavasani** [comment]
We have an issue to convert it to SymbolStart/End analyzer.

**Comment by sharwell** [comment]
@mavasani Yes, that's my intent for this issue. I was not able to find a duplicate though.

**Comment by Evangelink** [comment]
@mavasani @sharwell I don't see how we can keep the handling of `internal` members by moving to a symbol start/end analyzer. Is the idea to have 2 parts to this analyzer? One for `private` using the new approach and to keep the compilation end for `internal`?

**Comment by Evangelink** [comment]
@mavasani Looks like the rewrite was already done and this is a stale ticket.
