### ISSUE TITLE
CA1062: False positive after a null check

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/roslyn-analyzers#2277]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Package Version

2.9.1

#### Diagnostic ID

CA1062

#### Repro steps

It incorrectly flags filterValue as needing a parameter check for null. In this example, filterValue  is checked for null and an exception is thrown.

Interestingly, it only complains about filterValue on the second to last line. Other uses of filterValue do not report an error. (This was tested by commenting out said line.)

        public string ApplyAnonymousFilterValue(object filterValue, FilterOptions filterOptions, bool useSecondSlot = false)
        {
            if (filterValue == null)
                throw new ArgumentNullException(nameof(filterValue), $"{nameof(filterValue)} is null.");

            var ignoreNullProperties = filterOptions.HasFlag(FilterOptions.IgnoreNullProperties);
            var parts = new string[m_Entries.Length]; ;
            bool found = false;

            if (filterValue is IReadOnlyDictionary<string, object>)
            {
                foreach (var item in (IReadOnlyDictionary<string, object>)filterValue)
                {
                    var keyFound = false;
                    for (var i = 0; i < m_Entries.Length; i++)
                    {
                        ref var entry = ref m_Entries[i];

                        if (string.Equals(entry.Details.ClrName, item.Key, StringComparison.OrdinalIgnoreCase)
                            || string.Equals(entry.Details.SqlName, item.Key, StringComparison.OrdinalIgnoreCase))
                        {
                            var value = item.Value ?? DBNull.Value;

                            if (value == DBNull.Value)
                            {
                                if (!ignoreNullProperties)
                                    parts[i] = ($"{entry.Details.QuotedSqlName} IS NULL");
                            }
                            else
                            {
                                entry.ParameterValue = value;
                                if (!useSecondSlot)
                                    entry.UseParameter = true;
                                else
                                    entry.UseParameter2 = true;
                                parts[i] = ($"{entry.Details.QuotedSqlName} = ?");
                            }

                            found = true;
                            keyFound = true;
                            break;
                        }
                    }
                    if (m_StrictMode && !keyFound)
                        throw new MappingException($"Strict mode was enabled, but property {item.Key} could be matched to a column in {m_Name}. Disable strict mode or remove the item from the dictionary.");
                }
            }
            else
            {
                foreach (var property in MetadataCache.GetMetadata(filterValue.GetType()).Properties.Where(p => p.MappedColumnName != null))
                {
                    var propertyFound = false;
                    for (var i = 0; i < m_Entries.Length; i++)
                    {
                        ref var entry = ref m_Entries[i];

                        if (entry.Details.ClrName.Equals(property.MappedColumnName, StringComparison.OrdinalIgnoreCase))
                        {
                            var value = property.InvokeGet(filterValue) ?? DBNull.Value;

                            if (value == DBNull.Value)
                            {
                                if (!ignoreNullProperties)
                                    parts[i] = ($"{entry.Details.QuotedSqlName} IS NULL");
                            }
                            else
                            {
                                entry.ParameterValue = value;
                                if (!useSecondSlot)
                                    entry.UseParameter = true;
                                else
                                    entry.UseParameter2 = true;
                                parts[i] = ($"{entry.Details.QuotedSqlName} = ?");
                            }

                            found = true;
                            propertyFound = true;
                            break;
                        }
                    }
                    if (m_StrictMode && !propertyFound)
                        throw new MappingException($"Strict mode was enabled, but property {property.Name} could be matched to a column in {m_Name}. Disable strict mode or mark the property as NotMapped.");
                }
            }

            if (!found)
                throw new MappingException($"None of the properties on {filterValue.GetType().Name} could be matched to columns in {m_Name}."); <------

            return string.Join(" AND ", parts.Where(s => s != null));
        }

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/2345
