### ISSUE TITLE
CA2213: Unable to suppress error

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/roslyn-analyzers#2279]
#### Analyzer package

Microsoft.NetCore.Analyzers

#### Package Version

2.9.1

#### Diagnostic ID

CA2213

#### Repro steps

Unable to suppress errors from this rule.

In my case, I have the field `readonly DataTable m_Schema;` which can be returned from the class via a property getter and thus should not be disposed by this class. Essentially it holds, but does not 'own' the DataTable.

**Comment by mavasani** [comment]
> Unable to suppress errors from this rule.

Can you please expand on this? You should be able to add a pragma warning or SuppressMessageAttribute to suppress the reported CA2213 violation

**Comment by Grauenwolf** [comment]
When I right click on that error, I'm not given the option to add a supression.

Other errors work as expected. 

I don't think I tried manually adding a supression.

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/11371
