### ISSUE TITLE
CA2242 (Test for NaN correctly) is reported in generated code

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2293]
`TestForNaNCorrectlyAnalyzer` should explicitly configure its generated code behavior. If the current behavior is kept, no change is needed to the tests. If the behavior is changed so the warning is _not_ reported in generated code, the tests should be updated to use `CSharpCodeFixVerifier` instead of `CSharpSecurityCodeFixVerifier` (and similar for VB).

**Comment by Evangelink** [comment]
I am happy to take care of this issue. Is it ok to ignore generated code behavior? Shall it be discussed?

**Comment by sharwell** [comment]
@mavasani What is your preference here?

**Comment by mavasani** [comment]
I am fine either way. Ignoring in generated code seems fine to me.

**Comment by sharwell** [comment]
@Evangelink You are good to go on this 🎉
