### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of string: 0; "DoNotReferSelfInSerializableClass"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2299]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Do Not Refer Self In Serializable Class

File Name:
Microsoft.NetCore.Analyzers\Core\Security\xlf\SystemSecurityCryptographyResources.xlf

Resource ID:
0; "DoNotReferSelfInSerializableClass"

Query:
Is self localizable, referring "to itself"? What does it refer to?

**Comment by dotpaul** [comment]
Hrm, the source should probably be: "Do Not Refer To Self In Serializable Class"

"Self" is localiziable; it's referring to the class (that's serializable).

**Comment by PDostalek** [comment]
Thanks
