### ISSUE TITLE
Alex Turner README edits

### ISSUE THREAD

**Issue by zoepetard** [dotnet/roslyn-analyzers#230]
- cannot be represented syntactically --> if the syntactic representation is insufficient 
- step 1: comma: diagnostics, as an analyzer
- step 4: call YOUR analysis method
- choose either function or method
- opening parenthesis
- indicate in the steps that analysis method is the meat
- under packaging, 1st paragraph is not formatted correctly
- .Net compiler PLATFORM SDK

**Comment by daking2014** [comment]
1

**Comment by daking2014** [comment]
@zoepetard To close this issue you have to say "Fixes #220"
