### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of string: 0; "DoNotDisableSchUseStrongCryptoMessage"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2300]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
{0} disables TLS 1.2 and enables SSLv3

File Name:
Microsoft.NetCore.Analyzers\Core\Security\xlf\SystemSecurityCryptographyResources.xlf

Resource ID:
0; "DoNotDisableSchUseStrongCryptoMessage"

Query:
Would you please advise what will replace {0}?

**Comment by dotpaul** [comment]
Usually it's "SetSwitch", the name of a method.

**Comment by PDostalek** [comment]
Thanks for your reply. I´ll provide the meaning to vendor.
