### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of string: 0; "DuplicateSymbolsInPublicApiFilesMessage"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2301]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
The symbol '{0}' appears more than once in the public API files.

File Name:
Microsoft.NetCore.Analyzers\Core\Security\xlf\SystemSecurityCryptographyResources.xlf

Resource ID:
0; "DuplicateSymbolsInPublicApiFilesMessage"

Query:
What is public, the API or the files?

**Comment by genlu** [comment]
@PDostalek 
Definition of public API can be found here: https://en.wikipedia.org/wiki/Open_API
And "files" in this context, are two text files on disk this feature uses.

**Comment by PDostalek** [comment]
Thanks for confirmation
