### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of string: 0; "SymbolIsBannedMessage"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2303]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
The symbol '{0}' is banned in this project{1}

File Name:
Microsoft.CodeAnalysis.BannedApiAnalyzers\Core\xlf\BannedApiAnalyzerResources.xlf

Resource ID:
0; "SymbolIsBannedMessage"

Query:
What does the second placeholder refer to? Assuming the project name for now, please confirm or advise.

**Comment by genlu** [comment]
The second placeholder will be whatever the user of the analyzer specified in their public API files. It is not for project name. There's no need (or even possible) to localize that,

See the linked below for more details
https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md

**Comment by PDostalek** [comment]
Thanks for an advice.
