### ISSUE TITLE
CA2213 False positive when Dispose is implemented in .Designer.cs file

### ISSUE THREAD

**Issue by appel1** [dotnet/roslyn-analyzers#2306]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

2.9.1

#### Diagnostic ID

CA2213

#### Repro steps

Create a .net framework console app project.
Add FxCopAnalyzers
Add a Windows Service, for example Service1
Add a field with a disposable type to Service1.cs
Modify Dispose(bool) in Service1.Designer.cs to dispose 

#### Expected behavior
Does not trigger CA2213

#### Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA2213	'Service1' contains field 'timer' that is of IDisposable type 'Timer', but it is never disposed. Change the Dispose method on 'Service1' to call Close or Dispose on this field.	ConsoleApp1	ConsoleApp1\Service1.cs	33	Active

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/2348
