### ISSUE TITLE
Create a `WithWarningsAsErrors` extension method for testing

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2311]
This extension method could replace all uses of this pattern in tests:

https://github.com/dotnet/roslyn-analyzers/blob/2f94c36db114d8ab2517939c01e4390806c95cdb/src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/OverrideEqualsOnOverloadingOperatorEqualsTests.Fixer.cs#L63-L71

**Comment by Evangelink** [comment]
Are you thinking about some extension method for the `Test` class so that we will do something like:

```csharp
await new VerifyCS.Test
{
...
}.WithWarningsAsErrors().RunAsync();
```

or are you thinking about an extension for the solution?

```csharp
SolutionTransforms = 
{ 
     (solution, projectId) => solution.WithWarningsAsErrors(projectId)
}
```

or maybe even some kind of static function?

**Comment by sharwell** [comment]
I'm not actually sure this is still required, considering we can use the `CompilerDiagnostics` enumeration.

**Comment by Evangelink** [comment]
If I am not mistaken there are only 2 or 3 usages of this syntax at the moment so I would say it's up to you.

**Comment by Evangelink** [comment]
@sharwell Globally do you have any preference between using the full syntax for most of the behaviors or creating helper for common pattern? For example, what's your preference between

```csharp
await VerifyCS.Test {}.WithEditConfig(content)
```

and

```csharp
await VerifyCS.Test
{
	TestState =
	{
		Sources = {},
		AdditionalFiles = { (".editorconfig", content) }
	}
}
```
?

**Comment by sharwell** [comment]
For now I was leaning toward the full syntax with intent to review the situation after all the tests are converted and see how common specific patterns are. The full syntax is more verbose, but is also consistent and provides "one right way" to do nearly everything.

**Comment by Evangelink** [comment]
I am fine with the full syntax approach and if things change you could reopen this ticket later on.

**Comment by Evangelink** [comment]
@mavasani @sharwell My understanding is that there is nothing left to do here and the ticket can be closed.
