### ISSUE TITLE
Do not do -> Consider doing: Ex. CA2007, ConfigureAwait

### ISSUE THREAD

**Issue by GitTorre** [dotnet/roslyn-analyzers#2368]
#### Diagnostic ID
CA2007: Do not directly await a Task without calling ConfigureAwait

#### Recommendation
I understand that it makes sense in the context of UI thread, with the task continuation running on any available threadpool thread versus bound to the caller’s (to prevent UI blocking…), however there are in fact legitimate cases where this rule doesn’t apply in context. Anyway, should this rule read "do not do x” versus “consider doing y”? In fact, this should be the general pattern unless x is always a bad idea.

Unfortunately, static analysis can often lead to developers blindly following the suggestions, especially when they read “do not do this or that”. 

Perhaps we should err on the side of not using “do not do x” unless such a statement is provably always true for x.

**Comment by jinujoseph** [comment]
Suggestion from @gewarren 
CA2007: Consider calling ConfigureAwait on the awaited task

**Comment by sharwell** [comment]
I believe this rule should be removed in favor of the analyzers in Microsoft/vs-threading.

**Comment by mavasani** [comment]
This rule is already shipping with FxCop analyzers and has been documented on docs.microsoft.com as well. I would like to retain the rule and just adjust the wording as suggested by @gewarren.

**Comment by sharwell** [comment]
That seems roughly in line with the principle of wording based on default severity:

* 'may': info
* 'should': warning
* 'must': error

Can we think of a wording that uses 'should' for this?

**Comment by GitTorre** [comment]
I am in favor of the wording suggested by @gewarren. "Should" implies that in most cases, it makes sense. Is this actually the case? Does it make sense in most cases?

In general, it would be nice if FxCop analyzers would link to relevant articles to increase understanding and help developers decide what to do based on this knowledge - and in their solution context. Even though, for example, the C++ Core Check guidelines can sometimes be confusing, at least most of the recommendations include links to the related rule in the C++ Guidelines web site (which unfortunately can sometimes also confuse...). You can then decide that you "should" take the advice or that it doesn't really apply (or that you still don't quite understand).

FWIW, I have seen very few examples of ConfigureAwait being applied in most cases when await is used in all the modern C# code I've read and/or reviewed. This rule will confuse unless it is made clear when it actually applies and why it's important to follow suit in such cases. Instructing developers that they should do x when doing y is the same thing as saying don't do y without doing x. "Consider" is best here, in my opinion, and further providing a link to more useful information will inform developers who are now *considering* what to do in the context of their code now that they have learned something new.

...Charles
