### ISSUE TITLE
Cheaply check namespace

### ISSUE THREAD

**Issue by zoepetard** [dotnet/roslyn-analyzers#237]
We want a cheap check that we are in the correct file. (So that this analyzer will not run every time you try to write a different analyzer.)

One possibility: 
Solution Explorer --> NewTemplateAnalyzer --> Properties --> Build --> General -->
Set "Condition compilation symbols" to TUTORIAL for example.

@tmeschter Any suggestions for other ways to do this?

**Comment by daking2014** [comment]
2

**Comment by daking2014** [comment]
@jepetty @zoepetard Using a compilation symbol causes our tests to become unrunnable because none of them have the compilation symbol that I would be checking for.

@tmeschter Do you have any ideas about this?
