### ISSUE TITLE
PerformanceSensitiveAttribute conflicts with IVTs

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2371]
#### Analyzer package

Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers

#### Package Version

Example: 3.0.0-beta2.19218.3+e96bad97

#### Diagnostic ID

n/a

#### Repro steps

1. Create a project First, which has IVT visible to Second
2. Create a project Second, with a reference to First
3. Install the analyzer package in both projects

#### Expected behavior

No warnings.

#### Actual behavior

> Warning CS0436 The type 'PerformanceSensitiveAttribute' in 'C:\Users\sam\.nuget\packages\microsoft.codeanalysis.performancesensitiveanalyzers\3.0.0-beta2.19218.3\build\PerformanceSensitiveAttribute.cs' conflicts with the imported type 'PerformanceSensitiveAttribute' in 'Microsoft.CodeAnalysis, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Using the type defined in 'C:\Users\sam\.nuget\packages\microsoft.codeanalysis.performancesensitiveanalyzers\3.0.0-beta2.19218.3\build\PerformanceSensitiveAttribute.cs'.

**Comment by genlu** [comment]
This should be resolved by setting `PerformanceSensitiveAttribute` to true only at the root of IVT tree.

See https://github.com/dotnet/roslyn/blob/master/eng/targets/Settings.props#L139
```xml
  <!-- 
    Don't inject PerformanceSensitiveAttribute source by default to avoid duplicate definitions caused by IVT.
    This needs to be set to true in projects at the root of IVT trees, in order for PerformanceSensitiveAnalyzers to work.
  -->
  <PropertyGroup Condition="'$(GeneratePerformanceSensitiveAttribute)' == ''">
    <GeneratePerformanceSensitiveAttribute>false</GeneratePerformanceSensitiveAttribute>
  </PropertyGroup>
```
