### ISSUE TITLE
NRE CancellationTokenParametersMustComeLastAnalyzer

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/roslyn-analyzers#2379]
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Package Version

2.6.2-beta2

#### Diagnostic ID

AD0001

```
error AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.CancellationTokenParametersMustComeLastAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [F:\workspace\_work\1\s\src\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj]
```

Windows Desktop Release_32 - [Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=161907&view=logs) - Attempt 1

**Comment by mavasani** [comment]
@JoeRobich Do we have a call stack for the crash? I don't see this failure in your linked test logs.

**Comment by JoeRobich** [comment]
@mavasani Sorry, I shouldn't have called out the test logs above. The failure occurred during the build itself. Looking at the build.binlog from that build it doesn't seem to provide any additional details.

**Comment by mavasani** [comment]
Thanks. I am going to have to resolve this as a no-repro until we can get at least a call stack for the crash.
