### ISSUE TITLE
ThirdPartyNotices.rtf lacks the license notice for Humanizer

### ISSUE THREAD

**Issue by asmichi** [dotnet/roslyn-analyzers#2386]
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/)

#### Package Version

v2.9.2

#### Description

[ThirdPartyNotices.rtf](https://github.com/dotnet/roslyn-analyzers/blob/master/assets/ThirdPartyNotices.rtf) lacks [the license notice for Humanizer](https://github.com/Humanizr/Humanizer/blob/master/LICENSE), specifically the part below, making redistribution of the package illegal in a strict sense.

I noticed this while mirroring the package in my internal feed. Sorry if I overlooked something.

> ==============================================================================
> 
> Inflector (https://github.com/srkirkland/Inflector)
> The MIT License (MIT)
> Copyright (c) 2013 Scott Kirkland
> 
> ==============================================================================
> 
> ByteSize (https://github.com/omar/ByteSize)
> The MIT License (MIT)
> Copyright (c) 2013-2014 Omar Khudeira (http://omar.io)
> 
> ==============================================================================

**Comment by mavasani** [comment]
@ivanbasov Do we plan to fix this soon in this repo?
