### ISSUE TITLE
Generic causes CA0052 and CA0055 errors

### ISSUE THREAD

**Issue by scottbommarito** [dotnet/roslyn-analyzers#2390]
I'm working on a project (https://github.com/NuGet/NuGetGallery) and we use `Analyze -> Run Code Analysis` in Visual Studio to analyze our code.

We discovered that, after adding a new file, `Run Code Analysis` began to emit CA0052 and CA0055 errors: https://github.com/NuGet/NuGetGallery/commit/ab20a7ef5fa8612526fbe04338f3e00e240492b6

Upon further investigation, it seems like a generic on one of our classes caused the failure. We did some refactoring and removed the generic and the errors stopped: https://github.com/NuGet/NuGetGallery/commit/90eb3cfa9a525d674187d9da2b3843651796d084

The generic that caused the failure is syntactically valid and `Run Code Analysis` should not have any issues processing the project because of it. If the generic violates some rule, I would expect that it would throw a more appropriate error instead of the two that it threw which didn't seem to be relevant at all.

**Comment by mavasani** [comment]
@scottbommarito Kindly refer to [this](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2019#if-you're-an-fxcop-user...) documentation to migrate from legacy post-build analysis executed by `Analyze -> Run Code Analysis` to FxCop analyzers, which does source based analysis during command line build and typing in VS and also offers code fixes.

**Comment by scottbommarito** [comment]
@mavasani - is `Run Code Analysis` no longer being maintained? We would prefer not to migrate to a new static analysis tool because it is a large undertaking for our project.

**Comment by mavasani** [comment]
@scottbommarito It is a much lower priority for us, given an alternate and much better analysis model is now available and is fully supported by us. By the way, did you try your original scenario on VS2019 or is it on an earlier version of VS?

**Comment by scottbommarito** [comment]
@mavasani - that's fair. We do plan on migrating eventually but we'd like to postpone doing so. The scenario failed in VS2019.

**Comment by mavasani** [comment]
Closing this issue as the repo only tracks new source based Roslyn FxCop analyzers.
