### ISSUE TITLE
CA2000 DisposeObjectsBeforeLosingScope: InvalidOperationException with message 'Feature 'Flow-Analysis' is disabled.'

### ISSUE THREAD

**Issue by IlyaGrebnov** [dotnet/roslyn-analyzers#2398]
#### Analyzer package

CA2000 Microsoft.NetCore.Analyzers.Runtime.DisposeObjectsBeforeLosingScope

#### Package Version

v2.9.2 (upgrading from 2.6.3)

#### Diagnostic ID

CA2000 Microsoft.NetCore.Analyzers.Runtime.DisposeObjectsBeforeLosingScope

#### Repro steps

N/A

#### Expected behavior

I was able to pin point issue just to this rule. Other rules is working fine. Version of rule from 2.6.3 is also fine. Adding '<Features>$(Features);Flow-Analysis</Features>' explicitly to project doesn't resolves this.

#### Actual behavior

Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposeObjectsBeforeLosingScope' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'.	Common.Core	C:\rdnext\AzureUX\ResourceStack\src\common\core\CSC	1	Active

**Comment by mavasani** [comment]
@IlyaGrebnov Are you sure you have version 2.9.2 and not 2.9.1? We explicitly added the `flow-analysis` feature flag in the `.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.2\build\Microsoft.CodeAnalysis.FxCopAnalyzers.props` file that we drop into the package, and which gets imported in the MSBuild project file. I just verified it has the following property group at the end of the file:

```
<PropertyGroup>
    <Features>$(Features);flow-analysis</Features> 
</PropertyGroup>
```

**Comment by IlyaGrebnov** [comment]
Yes I am sure. I also tried to add 'flow-analysis' and 'Flow-Analysis' (in case it case sensitive) directly to csprog. No luck. I also notice issue is specific to this rule. If I suppress CA2000 from rules file I see no issues.

**Comment by mavasani** [comment]
Seems like something else within your project file (or imported targets/props) is resetting the Features property. Can you perform a diagnostic build (`msbuild.exe /v:diag`) and check the value of the Features property passed to the csc command line?

**Comment by mavasani** [comment]
@IlyaGrebnov Any luck in trying to get a diagnostic build to figure out what is causing the Features property to get reset for you?

**Comment by IlyaGrebnov** [comment]
I was not able to pin point the problem, but we migrated our build system to CBT which resolved this issue. So this is likely something to do with our setup.

**Comment by IlyaGrebnov** [comment]
I have consistent repro with 2.9.2 version of package.

![image](https://user-images.githubusercontent.com/773346/58044751-6a451800-7af5-11e9-8e87-6407444b67de.png)

**Comment by mavasani** [comment]
Can you please execute a verbose (`/v:diag`) msbuild invocation and check what target is overwriting the `Features` MSBuild property to clear out the "flow-analysis" value specified in the package.

**Comment by mavasani** [comment]
Closing this issue as feature flag is no longer required on VS2019.
