### ISSUE TITLE
Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by shubham26S** [dotnet/roslyn-analyzers#2409]
**Version Used**: 
2.9.2
**Steps to Reproduce**:

0. Use .Net standard 2.0
1. Inherit IDisposable interface
2. Implement Dispose() and Dispose(Boolean) methods

**Expected Behavior**:
No error
**Actual Behavior**:
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

**Comment by mavasani** [comment]
@shubham26S Can you please provide repro code from your project?

**Comment by mavasani** [comment]
@shubham26S Ping for a repro...

**Comment by mavasani** [comment]
@shubham26S I am unable to repro this after trying out different samples for a while. Kindly re-open with a more concrete repro sample if you have one. Thanks!

**Comment by jonhughes** [comment]
I get this error 100% of the time on one of my projects (in Visual Studio 2019 using the .NET 4.0 Framework). Company policy prohibits me posting the project code here, but I'm willing to work with you to try to resolve it. In addition, I don't know how to re-open the bug.

**Comment by mavasani** [comment]
@jonhughes Which version of the analyzer package are you referencing?

**Comment by jonhughes** [comment]
Microsoft.CodeAnalysis.FxCopAnalyzers is version 2.9.7.

**Comment by mavasani** [comment]
Can you try the latest version 3.0.0?

**Comment by jonhughes** [comment]
That worked! Sorry I hadn't noticed there was a newer version.
