### ISSUE TITLE
Unexpected resource strings being passed to the security helper

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2421]
See https://github.com/dotnet/roslyn-analyzers/pull/2417#discussion_r280875749

[GetResourceString](https://github.com/dotnet/roslyn-analyzers/blob/020a095feae4881ea5a13f8ed40c56e478f6a67a/src/Microsoft.NetCore.Analyzers/Core/Security/Helpers/SecurityHelpers.cs#L79) helper method is only expecting resource strings from `MicrosoftNetCoreSecurityResources`, but rules deriving from `UseXmlReaderBase` are passing in resource strings from `SystemSecurityCryptographyResources`.

**Comment by mavasani** [comment]
@dotpaul @LLLXXXCCC I believe this is now fixed?

**Comment by dotpaul** [comment]
Yep.
