### ISSUE TITLE
Question: Can I write a roslyn analyzer with VS 2019?

### ISSUE THREAD

**Issue by Korporal** [dotnet/roslyn-analyzers#2426]
This is a plain question (not a bug or issue report hence no tech details). I was beginning to read this:

https://www.meziantou.net/2018/12/17/writing-a-roslyn-analyzer

When I discovered that (it seems) VS 2019 has no such template nor could I search for one successfully in the IDE.

Thanks

**Comment by 333fred** [comment]
@korporal I believe that the tutorial you linked is missing the crucial step of installing the .NET compiler platform sdk, which is an optional component in the installer. If you look at the image in the article, you'll see that the option to install that component is checked. That should bring in the analyzer templates and the syntax tree visualizer.

**Comment by Korporal** [comment]
@333fred - Thanks for pointing this out. However I'm having trouble (I'm no beginner by the way) with the installer. When I originally installed VS 2019 (Enterprise) I checked the box on the left "Visual Studio extension development" but did not check the ".Net Compiler Platform SDL".

Now, when I attempt to select it the checkbox gets checked and the installer summary says 0KB is required. Now in that UI all I can do is press "Close", there's no "Continue" or anything. Yes, I can select either "Install while downloading" or "Download all, then install" but no matter which I choose I can't seem to actually get it to install the component.

If I do press "Close" the UI closes and that's the end of that.

In the main installer pane (which lists VS versions and offers Update, Launch, More) I see no sign of activity or anything, if I close that pane (top right X) and leave it again nothing happens.

I left it all night then started VS 2019 and the component was again unchecked, not installed.

Finally (and this looks like poor design in the installer UI) when I open the installer and scroll to the icon/image for "Visual Studio extension development" I must click that image in order to select it and see what components are installed but doing that unchecks the checkbox on the image and if I did not notice it doing that I can select components and then unwittingly uninstall the feature!

This is frankly terrible, if I get time  I may submit this to the VS issue site but this takes up a lot of time especially when trying to explain it all clearly.

**Comment by 333fred** [comment]
@Korporal the dropdowns on the right side of the installer can be opened and closed without having to select and unselect the entire scenario. Alternatively, you could use the `Individual Components` tab, though as that has no search functionality it's painful.

As to the checkbox, I wasn't able to repro that one locally. When I select an individual component such as the SDK, the button on the modify page changes from "Close" to "Modify". If you have the time, you can use the report feedback button from within the installer, which will make sure that the logs are collected so that the installer team can take a look.

**Comment by francisminu** [comment]
I have the same question. I created a couple of analyzers in Visual Studio 2017 as a starter and thought I will migrate to 2019 once I have some samples ready. Now that I am done with the samples, and tried to do the same in VS 2019, I do not see an option as in VS 2017 'Analyzer with code fix' in VS 2019.

Thanks,
Minu

**Comment by 333fred** [comment]
@francisminu as mentioned, you need to install the `.NET Compiler Platform SDK` component before you will see the templates.

**Comment by francisminu** [comment]
I already installed the .NET Compiler platform SDK in Visual Studio 2019 and it still doesn't show the option to create an Analyzer. But it comes up in 2017.

**Comment by francisminu** [comment]
They did not show up as such. i upgraded my VS today to th latest version and then typed Analyzer and it showed up. Not sure why it does not show up under Extensions. Thanks anyways @333fred

**Comment by Siderite** [comment]
I am having the same problem.

**Comment by 333fred** [comment]
@Siderite please open a new issue on https://github.com/dotnet/roslyn-sdk. This issue has been closed.
