### ISSUE TITLE
[loc][Query][roslyn-analyzers] Localizability of "ExportedPartsShouldHaveImportingConstructorDescription" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2455]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Exported parts should have [ImportingConstructor]

File Name:
Roslyn.Diagnostics.Analyzers\Core\xlf\RoslynDiagnosticsAnalyzersResources.xlf

==========================================
Query:
Are the elements like [ImportingConstructor], [Obsolete] localizable?

0; "ExportedPartsShouldHaveImportingConstructorDescription"
0; "ExportedPartsShouldHaveImportingConstructorTitle"
0; "ImportingConstructorShouldBeObsoleteDescription"
0; "ImportingConstructorShouldBeObsoleteMessage"
0; "ImportingConstructorShouldBeObsoleteTitle"

**Comment by mavasani** [comment]
Tagging @sharwell

**Comment by sharwell** [comment]
No, those elements are not localizable.

**Comment by PDostalek** [comment]
Thanks!
