### ISSUE TITLE
Question: Is there a way to disable a rule using .editorconfig

### ISSUE THREAD

**Issue by yufeih** [dotnet/roslyn-analyzers#2456]
In ruleset xml, a rule can be disabled using `<Rule Id="CA1032" Action="None" />`, but `.editorconfig` does not seem to have this functionality.

**Comment by mavasani** [comment]
This support does not exist as of today, but is coming in very soon. @jinujoseph @jasonmalinowski can provide more details on the timelines.

**Comment by mavasani** [comment]
Also tagging @agocke @jaredpar from the compiler team.

**Comment by mavasani** [comment]
Closing as external - support for editorconfig to configure diagnostic severities is unrelated to this repo, but Roslyn repo.
