### ISSUE TITLE
Consider a analyser to make taking value types by value in extension methods explicit

### ISSUE THREAD

**Issue by john-h-k** [dotnet/roslyn-analyzers#2475]
( cc @CyrusNajmabadi )

Currently, writing
```public void Method(this SomeValueType value)``` does not provide a warning, but takes `SomeValueType` by value rather than reference. Changing the signature from `this` to `ref this` takes it byref. While this can often be the desired behaviour, it is also an easy source for bugs where byref behaviour is expected. I suggest an analyser which warns when taking a value type by value in an extension method unless an attribute, e.g `ByValAttribute`, or similar, is applied to mute the warning. `ref` does not induce a warning because it is already explicit.

**Comment by Evangelink** [comment]
I prefer the suggestion from @maxkoshevoi. @john-h-k, @mavasani is it ok for you?

**Comment by mavasani** [comment]
Yes, we can use https://github.com/dotnet/roslyn-analyzers/issues/3535 to track this.
