### ISSUE TITLE
AD0001 - Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed

### ISSUE THREAD

**Issue by ambujs** [dotnet/roslyn-analyzers#2476]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.2

#### Diagnostic ID

'Microsoft.NetCore.Analyzers.Runtime.DisposableFieldsShouldBeDisposed' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'.

#### Repro steps

1. VS v15.9.12
1. FxCopAnalyzers v2.9.2

#### Expected behavior
Build without errors & warnings

#### Actual behavior
Getting the above warning

I have tried suggestions in other issues like adding:
```
<PropertyGroup>
<Features>IOperation</Features>
</PropertyGroup>
```

and 
```
<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.2">
<PrivateAssets>all</PrivateAssets>
</PackageReference>
```

**Comment by mavasani** [comment]
@ambujs Can you do a diagnostic/detailed msbuild invocation and check the value of `features` command line argument to csc.exe? I believe your issue is similar to https://github.com/dotnet/roslyn-analyzers/issues/2398, something in your imported props or targets is overwriting the Features property.

**Comment by ambujs** [comment]
Here's the csc.exe command being executed:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;DEBUG;NETCOREAPP;NETCOREAPP2_2 /errorendlocation /preferreduilang:en-US`

I can also see this in the log:
`/features:IOperation`

**Comment by mavasani** [comment]
@ambujs - so seems like something else is overwriting the MSBuild property to `<Features>IOperation</Features>`, ignoring the flow-analysis setting. Can you figure out which task/target is doing so and delete that property setting? IOperation feature is not under the feature flag in 15.9, and hence you do not need to set it.

**Comment by mavasani** [comment]
@ambujs - Actually, looking at your command line it seems `/features` is not even being passed to the command line. I would expect `/features:flow-analysis` on the csc command line for it to work properly.

**Comment by mavasani** [comment]
Also note that if you can move to VS2019 (RTW or Update1), then you don't even need the feature flag. The package will just work.

**Comment by ambujs** [comment]
@mavasani ah yes, you are right! Further down in the csproj file I had this:
`<PropertyGroup>
<CodeAnalysisRuleSet>..\main.ruleset</CodeAnalysisRuleSet>
<Features>IOperation</Features>
<NoWarn></NoWarn>
</PropertyGroup>`

After removing the following line, I can build correctly!
`<Features>IOperation</Features>`

Thanks for your help!

**Comment by mavasani** [comment]
Great, thanks!
