### ISSUE TITLE
 [loc][Query][roslyn-analyzers] Localizability of "DoNotUseWeakKDFAlgorithm" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2483]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Do Not Use Weak Key Derivation Function Algorithm

File Name:
Microsoft.NetCore.Analyzers\Core\Security\xlf\SystemSecurityCryptographyResources.xlf

==========================================
Query:
Is it a message calling the user not to use this algorithm (please do not use...) or a UI option (say, a checkbox) where you can choose whether to use or not to use this option?

**Comment by mavasani** [comment]
@dotpaul @LLLXXXCCC for help

**Comment by dotpaul** [comment]
The former.

**Comment by PDostalek** [comment]
Thanks for confirmation
