### ISSUE TITLE
[loc][Query][roslyn-analyzers] Localizability of "DoNotUseWeakKDFAlgorithmDescription"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2484]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Some implementations of the Rfc2898DeriveBytes class allow for a hashAlgorithm to be specified in the constructor parameter or overwritten in HashAlgorithm property. If this exists, then it should be used with SHA-256 or higher as the hashAlgorithm parameter.

File Name:
Microsoft.NetCore.Analyzers\Core\Security\xlf\SystemSecurityCryptographyResources.xlf

==========================================
Query:
What does "this" stand for "class"?

**Comment by dotpaul** [comment]
"this" refers to "the constructor parameter or overwritten in HashAlgorithm property", but lemme change the string to be:

Some implementations of the Rfc2898DeriveBytes class allow for a hash algorithm to be specified in a constructor parameter or overwritten in the HashAlgorithm property. If a hash algorithm is specified, then it should be SHA-256 or higher.

**Comment by dotpaul** [comment]
Updating string in #2487

**Comment by PDostalek** [comment]
Many thanks
