### ISSUE TITLE
[loc][Query][roslyn-analyzers] Localizability of "DoNotUseWeakKDFAlgorithmMessage"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2485]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
{0} created with a weak hash algorithm. Use SHA256, SHA384, or SHA512 to create a strong key from a password

File Name:
Microsoft.NetCore.Analyzers\Core\Security\xlf\SystemSecurityCryptographyResources.xlf

==========================================
Query:
What does {0} stand for?

**Comment by mavasani** [comment]
@dotpaul @LLLXXXCCC for help

**Comment by dotpaul** [comment]
{0} will be the name of a type/class, e.g. Rfc2898DeriveBytes.

**Comment by PDostalek** [comment]
Thanks
