### ISSUE TITLE
Null-Conditional Operator used to call Dispose() causes CA2213

### ISSUE THREAD

**Issue by HSyr** [dotnet/roslyn-analyzers#2486]
Although `Dispose `is called (using Null-Conditional Operator) on `MemoryStream` I got warning _CA2213: Disposable fields should be disposed_ after running Code Analysis.

```c#
public class DisposableTest : IDisposable
{
  public MemoryStream memoryStream = new MemoryStream();

  public void Dispose ()
  {
    Dispose( true );
    GC.SuppressFinalize( this );
  }

  protected virtual void Dispose ( bool disposing )
  {
    if ( disposing )
      // Warning CA2213  'DisposableTest' contains field 'DisposableTest.memoryStream' that
      // is of IDisposable type: 'MemoryStream'. Change the Dispose method on
      // 'DisposableTest' to call Dispose or Close on this field.
      memoryStream?.Dispose();
  }
}
```

Version: Visual Studio Community 16.0.4

**Comment by mavasani** [comment]
@HSyr - Can you please let us know how you are running the analysis? Are you explicitly executing "Run Code Analysis" command in VS or setting "RunCodeAnalysis" MSBuild property to true in your project file? Both of these modes invoke the legacy binary based FxCop, which is on the path to deprecation, and the issue you mention here is a known issue with that tool.

I would instead recommend you migrate to using FxCop Analyzers (new source based analysis) following the documentation here: https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2019. We have specifically addressed the issue you mention here in FxCop analyzers.

**Comment by HSyr** [comment]
Yes, I did run "Run Code Analysis" from VS. I also installed VSIX analyzers. So I use both, although the former is obsolete.

**Comment by mavasani** [comment]
Ah, in that case the false positive is coming from legacy FxCop. Can you instead use the FxCop analyzers NuGet package?

**Comment by mavasani** [comment]
Closing this issue as legacy FxCop is not going to get fixed anymore.
