### ISSUE TITLE
Roslyn analyzer for comparing symbols

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-analyzers#2493]
As part of https://github.com/dotnet/roslyn/issues/35933, symbol equality is going to change to only include things that were in the language in c# 7.3, and we're going to start requiring using explicit comparators when comparing `ITypeSymbol`s. This is going to affect a few different scenarios:

1. Straight comparisons of symbols should use a comparator so that they are explicit about what type of comparison they want.
2. Dictionaries should use a comparator, as by default symbols with differing nested nullabilities will be considered equal for the purposes of being keys.
3. Anything that calls `GetHashCode()` will likely be doing the wrong thing in some cases.

**Comment by mavasani** [comment]
Tagging @sharwell

**Comment by sharwell** [comment]
@333fred I implemented RS1024 (Compare symbols correctly) to handle the original comparison rules. We can modify that to handle the new rules as well.

**Comment by 333fred** [comment]
@ryzngard

**Comment by Evangelink** [comment]
@333fred So if I got things right we need to extend `RS1024 (Compare symbols correctly)` to report a diagnostic on:
- calls to `GetHashCode`,
- new instances of `Dictionary` and `HashSet` (maybe more collections?) using symbols as the implementation will use hash code

Anything else?

**Comment by 333fred** [comment]
More collections would be good. Also using the `==` operator.

**Comment by Evangelink** [comment]
`==` is already handled by the current version of the analyzer if I am not mistaken.

**Comment by Evangelink** [comment]
I am doing the implementation at the moment and I am wondering if it's better to have a list of known collection types or do go for a more generic approach where we actually look at all object creation of a collection (inherits from ienumerable) where there is an overload with a `IEqualityComparer` overload and that no argument or type `SymbolEqualityComparer` is passed by. Any preference?

We may also want to handle some builders (especially for immutable types), WDYT?

**Comment by ryzngard** [comment]
The list I had originally made for things where you need IEqualityComparer. This doesn't include Immutable builders, but is a good starting point. I think for now a hardcoded list is better than having to search constructors or methods that take `IEqualityComparer` 

### `System.Linq.Enumerable<ISymbol>`
- Contains
- Distinct
- GroupBy
- GroupJoin
- Intersect
- Join
- SequenceEqual
- ToDictionary
- ToHashSet
- ToLookup
- Union

### `Dictionary<ISymbol, T>`
- Constructor

### `HashSet<ISymbol>`
- Constructor
