### ISSUE TITLE
CA1712 - Defaults to error instead of warning

### ISSUE THREAD

**Issue by MrMikeJJ** [dotnet/roslyn-analyzers#2494]
#### Analyzer package
Microsoft.CodeQuality.Analyzers included from Microsoft.CodeAnalysis.FxCopAnalyzers

#### Package Version
Example: v2.9.2

#### Diagnostic ID
CA1712
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1712-do-not-prefix-enum-values-with-type-name

#### Repro steps
Choose Ruleset "Microsoft All Rules"
Make the rule fire
Can provide sample code if required

#### Expected behavior
Warning to be raised

#### Actual behavior
Error is raised

**Comment by mavasani** [comment]
@dotnet/roslyn-analysis I accidentally committed the fix to this bug directly into master when I intended to create a new patch branch and then create a PR from GitHub website. Is there a repo setting that will prevent such accidental commits to master from the GitHub website?

Additionally, please review https://github.com/dotnet/roslyn-analyzers/commit/577e2742e7d1e119d1165a1c4e026f3f9fa37059 which fixed this bug - the change itself was pretty trivial.
