### ISSUE TITLE
'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn-analyzers#2502]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.2

#### Diagnostic ID

[CA2100](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2100-review-sql-queries-for-security-vulnerabilities?view=vs-2019)

#### Repro steps

This is in a .NET Core console app.

I couldn't repro it, but the code file includes these classes:

    public abstract class GBase
    {
        public abstract bool MyProperty
        {
            get;
            protected set;
        }

        public abstract void DoX();
    }

    public class GClass : GBase
    {
        public GClass()
        {
            this.MyProperty = true;
        }

        public override void DoX() { }

        public override bool MyProperty
        {
            get;
            protected set;
        }
    }

#### Expected behavior

No exception from this analyzer.

#### Actual behavior

AD0001 shows in the Error List. Details:

'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw the following exception:

Exception occurred with following context:
Compilation: A1
IOperation: PropertyReference
SyntaxTree: c:\vsprojects\A1\A1\Program.cs
SyntaxNode: this.MyProperty [MemberAccessExpressionSyntax]@[1243..1258) (62,12)-(62,27)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Analyzer.Utilities.Extensions.ISymbolExtensions.IsOverrideOrImplementationOfInterfaceMember(ISymbol symbol, ISymbol interfaceMember)
   at Analyzer.Utilities.Extensions.ISymbolExtensions.IsOverrideOrImplementationOfInterfaceMember(ISymbol symbol, ISymbol interfaceMember)
   at Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities.<>c__DisplayClass7_1.<Initialize>b__4(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__51_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

**Comment by gewarren** [comment]
I can share the project with you if necessary.

**Comment by mavasani** [comment]
Thanks, I am going to try and repro it locally, otherwise I can add a defensive check around the code causing NRE.

**Comment by mavasani** [comment]
@gewarren Did you hit the NRE while editing code OR the code had some syntax/semantic errors? From the stack and method implementation, it seems like this can occur only for error code. I am trying to get a minimal repro...

**Comment by gewarren** [comment]
@mavasani I'm not really sure. I did have CA1801 set to Error instead of Warning and after building, the Error List showed an error for CA1801 for the 'args' parameter of 'main'. I didn't see any other errors though.
