### ISSUE TITLE
Move NuGet authoring project Microsoft.FxCopAnalyzers over from dotnet/roslyn

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn-analyzers#251]
Need to find and move the project that builds Microsoft.FxCopAnalyzers nuget package from dotnet.roslyn. It pulls in System.Runtime.Analyzers, System.InteropServices.Analyzers and Microsoft.AnalyzerPowerPack.

**Comment by mavasani** [comment]
Taking this up as part of generation of new analyzer nuget packages.
