### ISSUE TITLE
CA1031 (DoNotCatchGeneralExceptionTypes) flags all catch handlers that use exception type instead of variable

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2518]
#### Analyzer package

Latest FxCop analyzers package on myget

#### Diagnostic ID

Example: [CA1716](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1716-identifiers-should-not-match-keywords)

#### Repro steps

```
using System;

public class Class1
{
    void M()
    {
        try
        {
        }
        catch (OperationCanceledException)
        {
            // Comment
        }
    }
}
```

#### Expected behavior
No CA1031

#### Actual behavior

![image](https://user-images.githubusercontent.com/10605811/58963888-d31dc880-8762-11e9-88f3-34f2782d9da4.png)

**Comment by mavasani** [comment]
We should also fix the diagnostic to only span the catch header, not the entire catch block.

**Comment by JeremyCaney** [comment]
I'm not sure exactly when this was reintroduced, but I'm using `Microsoft.CodeAnalysis.FxCopAnalyzers` 3.0.0 and I am encountering this bug, even though it was resolved for previous versions. Was this issue inadvertently reintroduced? 

Just to make sure this wasn't specific to the particular exception I was trying to catch, I've tried using the exact exception reported in this issue:

```cs
using System;
public class Class1
{
    void M()
    {
        try
        {
        }
        catch (OperationCanceledException)
        {
            // Comment
        }
    }
}
```

This yields the following message:

> `CA1031`: Modifiy 'M' to catch a more specific exception type, or rethrow the exception.

Is anyone else able to reproduce with 3.0.0?

**Comment by mavasani** [comment]
Can you check if you have installed the “Microsoft CodeAnalysis 2019” VSIX extension? If so, please uninstall it.

**Comment by JeremyCaney** [comment]
@mavasani: Aha! I _do_ have that installed, but because it was also version 3.0.0, I didn't think anything of it. But I now see that the versions aren't aligned between the extension and the NuGet package. Thank you! That resolved this issue for me.
