### ISSUE TITLE
CA2213 false positive in 2.9.3

### ISSUE THREAD

**Issue by zmanbb** [dotnet/roslyn-analyzers#2532]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.3 (Latest)

#### Diagnostic ID

[CA2213](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed)

#### Repro steps

I am getting false positives on fields that cannot be disposed because their value is not instantiated locally:

` public class MyObject
    {
        private readonly Image image = Resources.time_frame_24;
    }
}`

#### Expected behavior

The warning should not be generated

#### Actual behavior

The warning is generated

**Comment by Gav-Brown** [comment]
It looks like v2.9.3 (VS 2019) enables the old `Managed Binary Analysis` (FXCop) rules even though `RunCodeAnalysis` is `false` in the .csproj file and all the rules are disabled.

**Comment by Gav-Brown** [comment]
Ignore. I assumed it was the old FXCop rules as the .ruleset in Visual Studio didn't show any new rules. I suspect the ruleset editor has a bug...

**Comment by dkalbertson** [comment]
I looked into fixing this. However, I'm curious about the use case here. In this case, you're initializing a class level instance reference field with a static resource. You could declare it as a static readonly Image (or use the resource directly rather than caching the reference to it) to avoid the rule violation.

`public class MyObject { private static readonly Image image = Resources.time_frame_24; } }`

The rule could, however, be updated to check if the field's initializer is static. I'd like @mavasani's opinion on this.

**Comment by mavasani** [comment]
Agree with @dkalbertson. Another option is to define it as an auto-property `private Image Image => Resources.time_frame_24;`. A private instance field generally indicates ownership of the instance assigned to it is with the containing type's runtime instance.

**Comment by zmanbb** [comment]
@dkalbertson:
> You could declare it as a static readonly Image

If you see my sample, the field is already declared as static readonly and it still generates the violation.

The reason for caching the reference is the resource is used on more than one occasion and caching it in as class level reference simplifies the possible change of the resource.

As this kind of usage is clearly not direct violation of the rule, it should be at least described in the documentation.

**Comment by sharwell** [comment]
> the field is already declared as static readonly and it still generates the violation

You have it declared as `readonly`, but you haven't declared it `static`. This is the problem.

**Comment by zmanbb** [comment]
Yikes, I should put my good glasses on... I totally overlooked the missing `static` modifier.

What do you propose for the final solution? I have to upgrade a larger solution and I don't want to do all the fixing twice.

**Comment by mavasani** [comment]
Closing the issue as the analyzer behavior seems reasonable, and what remains is a logistical question on how to apply the fix on your code base.
