### ISSUE TITLE
Building projects with roslyn fxcop analysers nuget dependency never completes

### ISSUE THREAD

**Issue by DeveloperScottW** [dotnet/roslyn-analyzers#2535]
We modified a solution so that projects use the fxcop nuget dependency for code analysis, rather than the deprecated implementation. Local builds in VS2019 complete in seconds, but the build task in azure never finishes and instead times out after an hour.

I deploy a private agent in your local machine, check whether the project could build in the private agent, and it almost burned up my laptop.

"C:\Program Files (x86)\Microsoft Visual Studio\2019\...\Roslyn\VBCSCompiler.exe" Ramped up to 10GB of ram in 20 minutes and sat around 85-98% CPU.

After killing the process

"C:\Program Files (x86)\Microsoft Visual Studio\2019\...\Roslyn\csc.exe" Started up and rampted up to 5GB of ram in 5 minutes and sat around 85-98% CPU. before I killed that process. the only related error I could find was below. When I tried to access the attached files, they did not exist.

I've included the Roslyn logs along with the build logs.

#### Package Version

Example: v2.9.2

#### Repro steps

Add Microsoft.CodeAnalysis.FxCopAnalyzers.2.9.2 nuget to project, on a web service application.
Set Desktop as a Build agent
Create build pipeline on MS VS Devops
add task to publish build - MSBuild task with arguments:
    /p:RunCodeAnalysis=false /p:DeployOnBuild=true /p:OutputPath="\Temp\<Folder>" /p:DebugSymbols=true /p:DebugType=pdbonly <Folder>.csproj

start build process with Desktop as agent.

#### Expected behavior

Compile as it does on Desktop.

#### Actual behavior

Times out and consumes 70-90% CPU and over 10GB memory

**This issue was reported on developercommunity.visualstudio.com and requested it be brought up here:** 

#### jingzhu yan [MSFT]
----------------------------------------------------------------------------
I checked your logs, the build was struck in Build/Publish IS Website step.

In that step, you built Perspective.IntegrationServices.IISHosting\Integration.csproj.

For Roslyn/csc.exe is spiking the CPU over 90% and the memory usage continues to grow well over 10GB,

Can you create an issue here: https://github.com/dotnet/roslyn-analyzers/issues

https://developercommunity.visualstudio.com/content/problem/579129/visual-studio-2019-build-with-roslyn-analysers-nev.html?childToView=595978#comment-595978
----------------------------------------------------------------------------

[logs_6311.zip](https://github.com/dotnet/roslyn-analyzers/files/3273789/logs_6311.zip)
![18996](https://user-images.githubusercontent.com/12259807/59226718-e086e880-8b90-11e9-9b37-654577fcd384.png)
![21876](https://user-images.githubusercontent.com/12259807/59226719-e11f7f00-8b90-11e9-9c0e-91480f50c1b1.png)
[server.18996.log](https://github.com/dotnet/roslyn-analyzers/files/3273790/server.18996.log)
[server.21876.log](https://github.com/dotnet/roslyn-analyzers/files/3273791/server.21876.log)

**Comment by mavasani** [comment]
@DeveloperScottW Would you be able to try out package 2.9.3, which has bunch of performance fixes for the analyzers on top of 2.9.2. If you can still repro the issue, can you please a performance trace/repro project for investigation? Thanks!

**Comment by sharwell** [comment]
@DeveloperScottW if the performance problems continue, please submit a performance trace following the steps described at https://aka.ms/reportPerf.

**Comment by DeveloperScottW** [comment]
Thank you Sam and Manish,

I upgraded the package to 2.9.3, and found that the local build pined my
cpu without going through Azure-DevOps build agent.
It appears to be the same issue.

At this point, we have uninstalled
the Microsoft.CodeAnalysis.FxCopAnalyzers, and the build succeeds without
issue.
One consideration is, that our project has 7500 warning that are flagged
and need to be addressed.

Thanks again

Scott

**Comment by mavasani** [comment]
> I upgraded the package to 2.9.3, and found that the local build pined my
cpu without going through Azure-DevOps build agent.
It appears to be the same issue.

Would you be able to provide a performance trace following the steps Sam mentioned above?

**Comment by DeveloperScottW** [comment]
We have parked this issue for now.  If I have bandwidth I will try to
provide a performance trace.

**Comment by mavasani** [comment]
Closing this issue for now. Kindly re-open when you are able to provide a repro or performance trace for it to be actionable.
