### ISSUE TITLE
Broken link for CA1067

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn-analyzers#2538]
The link for CA1067 http://go.microsoft.com/fwlink/?LinkId=734909 on https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md redirects to https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.ApiDesignGuidelines.Analyzers/docs/reference/CA1067_OverrideObjectEqualsWhenImplementingIEquatableOfT.md which doesn't exist.

The link is also missing from https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status

**Comment by mavasani** [comment]
Blocked on https://github.com/MicrosoftDocs/visualstudio-docs/issues/3459

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by mavasani** [comment]
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1067?view=vs-2019
