### ISSUE TITLE
CA1303 causes project build failure if the offending string literal contains new line characters

### ISSUE THREAD

**Issue by dkalbertson** [dotnet/roslyn-analyzers#2574]
#### Analyzer package

 [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.3

#### Diagnostic ID

[CA1303](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1303-do-not-pass-literals-as-localized-parameters)

#### Repro steps

1. In a C# project, with any method that takes a string as a parameter: (i.e. void Foo(string message);)
1. Pass a string literal that has a new line character in it  (i.e. "Breaking\nString") to method Foo as below
Foo("Breaking\nString")

#### Expected behavior
CA1303 issue reported

#### Actual behavior
Project fails to build with error "csc.exe" exited with code 1"

Setting build output level to "Diagnositc" identified the issue.

**Comment by Gav-Brown** [comment]
It looks like v2.9.3 (VS 2019) enables the old `Managed Binary Analysis` (FXCop) rules even though `RunCodeAnalysis` is `false` in the .csproj file and all the rules are disabled.

**Comment by mavasani** [comment]
@dkalbertson Looks like a valid bug report for a new rule added in 2.9.3 package
@Gav-Brown - I am not sure I understand your claim, kindly clarify.

**Comment by Gav-Brown** [comment]
@mavasani Thanks. I assumed it was the old FXCop rules as the .ruleset in Visual Studio didn't show any new rules. I suspect the ruleset editor has a bug...

**Comment by dkalbertson** [comment]
@mavasani I've created a pull request that contains a fix for this. The string literal now get sanitized by replacing any newline characters with a space.

**Comment by mavasani** [comment]
@dkalbertson Thank you for your contribution! I have merged the PR.

**Comment by dkalbertson** [comment]
Great! Thank You!
