### ISSUE TITLE
Very slow build with Winforms project

### ISSUE THREAD

**Issue by gradyal** [dotnet/roslyn-analyzers#2576]
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers

#### Package Version

v2.9.3 (Latest)

#### Diagnostic ID

N/A

#### Repro steps

1. Setup Winforms project
2. Install Microsoft.CodeAnalysis.FxCopAnalyzers
3. Build solution

#### Expected behavior
Build should be fast

#### Actual behavior
Build is very slow

#### Additional context:
I went to the Microsoft Build conference in May and spoke with several developers about this (at the Winforms booth and the Visual Studio booth) and the recommendation was to submit an issue here. I was originally using the "stopwatch" approach to time the builds, but I've since come across an extension called BuildVision which measures each project's elapsed build time.

My solution layout:
![image](https://user-images.githubusercontent.com/5721295/59389173-4b702500-8d33-11e9-9ae3-88e23a2855d0.png)

With Microsoft.CodeAnalysis.FxCopAnalyzers installed, after clean and building solution, here is output from BuildVision (note Winforms build time of nearly **_1 minute_**):
![image](https://user-images.githubusercontent.com/5721295/59389236-778ba600-8d33-11e9-9767-f3bd6794887e.png)

After removing FxCopAnalyzers (and all dependent analyzers such as VersionCheck, CodeQuality, NetCore, NetFramework), clean and build solution, here is output from BuildVision (note Winforms build time of **_6 seconds_**):
![image](https://user-images.githubusercontent.com/5721295/59389387-c9ccc700-8d33-11e9-9578-27238db0ed5c.png)

The above was run on a Winforms project that has been around for about a year now on .NET Framework 4.7.2. I also tried the same on a brand new Winforms project and the build time went from 2 seconds (without FxCopAnalyzers) to 15 seconds (with the analyzers)

Let me know if I can provide any additional information.

**Comment by sharwell** [comment]
@gradyal Can you point me at a branch that contains the enabled analyzers so I can profile it?

**Comment by gradyal** [comment]
@sharwell Unfortunately the repository is private. Would it help for me to setup a public repo for the newer project I mentioned above?

**Comment by sharwell** [comment]
@gradyal Sorry for the confusion; I was thinking you were talking about the [dotnet/winforms](https://github.com/dotnet/winforms) project. For your case, if you could follow the steps in https://aka.ms/reportPerf it would be a big help. Then put a link to the developer community issue here and I can review it. It will probably be sufficient to send a recording of just the "after" case. If the answer isn't obvious from that I'll let you know.

**Comment by gradyal** [comment]
@sharwell Sure, I'll give that a shot

**Comment by gradyal** [comment]
@sharwell Just submitted. Here's the link: https://developercommunity.visualstudio.com/content/problem/605246/very-slow-build-with-winforms-project-and-fxcop-an.html

**Comment by sharwell** [comment]
@gradyal Can you try disabling CA3075 and CA1062? They are the two slowest rules and may get you close enough to move forward with the rest.

**Comment by gradyal** [comment]
@sharwell Wow! That helped quite a bit. Brought the Winforms project build time down to about 10 seconds. Thank you!

**Comment by mavasani** [comment]
I will investigate the root cause of the performance issue in CA3075 and CA1062 - it is likely due to interprocedural analysis.

**Comment by sharwell** [comment]
@mavasani Note that CA3075 is 4-5x slower than CA1062, and is *by far* the slowest rule in this repository. The second slowest item at about half the cost of CA3075 was the monitor contention for rules that aren't setting EnableConcurrentExecution.

**Comment by mavasani** [comment]
Thanks @sharwell. Tagging @dotpaul as the owner of CA3075. I believe the root cause is https://github.com/dotnet/roslyn-analyzers/issues/2103.

**Comment by mavasani** [comment]
FYI: I have fixed the performance issue with CA3075 with https://github.com/dotnet/roslyn-analyzers/pull/2595. Will work on CA1062 perf tuning now.
