### ISSUE TITLE
Different ruleset between project code analysis settings an analyzers

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/roslyn-analyzers#259]
I've got this strange situation where the Analyzers use a different ruleset from the project. 
If I go into project properties -> Code Analysis -> RuleSet it has ruleset A.
If I right-click the analyzers node -> open active ruleset -> ruleset B

Is this on purpose? I have seen this work correctly as well (using the same ruleset). 

For what it's worth, I'm using an imported props file which sets the ruleset. It works fine in the project properties, here it always references the correct one.

**Comment by tmeschter** [comment]
@hvanbakel Can you check the project file to see if the `<CodeAnalysisRuleSet>` property is defined anywhere?

**Comment by hvanbakel** [comment]
Yes, it is defined in a props file which is added by a nuget package. This ruleset is used by the project properties which is correct.

I'm importing multiple nuget packages however (each of them defines a props file with a ruleset). in the install of the nuget package I remove the old props file so the most specific is always used. Each derived package adds additional rules to check.

**Comment by tmeschter** [comment]
@hvanbakel Why do the NuGet packages provide a .ruleset file? Doesn't that prevent the owner of the project from specifying their own?

**Comment by hvanbakel** [comment]
This is an internal set of rules, so by installing the package they're enabled by default. The user can theoretically still select it themselves but that's outside of our control.

What struck me is that this works perfectly for the build, but not for the IDE so it looks like the behavior is different.

**Comment by tmeschter** [comment]
@hvanbakel The diagnostic analyzer itself can specify a default severity, and whether or not it is enabled by default. The .ruleset file isn't needed for that.

Regardless, there is clearly a bug here, but it isn't related to the analyzers hosted in this repo. [dotnet/roslyn](https://github.com/dotnet/roslyn) would be a more appropriate place for this issue, and I'm going to move it over there.
