### ISSUE TITLE
Make CA1303 configurable or split it

### ISSUE THREAD

**Issue by x3ntrix** [dotnet/roslyn-analyzers#2602]
#### Analyzer package

[Microsoft.NetCore.Analyzers](https://www.nuget.org/packages/Microsoft.NetCore.Analyzers/)

#### Package Version

v2.9.3 (Latest)

#### Diagnostic ID

[CA1303](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1303-do-not-pass-literals-as-localized-parameters?view=vs-2019)

#### Repro steps

1. Create a new exception instance and pass a literal string to 'message' parameter

#### Expected behavior
It would be nice if this rule could ignore exceptions. 

#### Actual behavior
Warning is reported because string is not retrieved from a resource table.

I'm not sure if there are already rules that can be configured, so this might not be an option. But splitting the rule into two, one for localization of exception and one for the remaining cases, might be a viable option.

**Comment by airbreather** [comment]
We would also appreciate the ability to treat constructor parameters on types that inherit from `System.Exception` differently from all other places that currently raise this diagnostic.

For exceptions that our application throws itself, either:
1. They get caught further up and presented as nicely formatted error messages to the user, or
1. They indicate that our code has made an incorrect assumption and needs to be changed.

In the former case, the message is irrelevant.  In the latter case, the contents of the message are intended to be read by my team; even our end users who speak fluent English are typically not equipped to resolve the issue, so what typically happens is we get a copy-paste of a screenshot of the last-chance error dialog that we pop up as the application is on its way out the door.

It would be very awkward if this dialog were in a language that my team doesn't understand 😓.

It would be nice to keep the diagnostics for other situations, though.

**Comment by KrisVandermotten** [comment]
I agree.

[As Krzysztof Cwalina puts it](https://blogs.msdn.microsoft.com/kcwalina/2007/01/30/how-to-design-exception-hierarchies/):

> Usage errors need to be communicated to the human developer calling the routine. The exception type is not the best way to communicate errors to humans. The message string is a much better way.

Therefore, message strings for these types of exceptions need to be in a language understood by the developers, not the language of the end user.

Furthermore, I believe that any system that sends unhandled exception messages (or worse, call stacks) across a network to a caller may have a security problem. So why would we then localize those messages in the language of the calling user?

**Comment by KrisVandermotten** [comment]
I don't understand how #2640 solves this issue.

Are we supposed to list the constructors of all types that inherit from `System.Exception` to our .editorconfig file?

**Comment by mavasani** [comment]
Thanks, added a different option: https://github.com/dotnet/roslyn-analyzers/pull/2642/files#diff-0dc34fda02de9acf20e36dedb5fe1f26R1500

`dotnet_code_quality.excluded_type_names_with_derived_types = T:System.Exception`
