### ISSUE TITLE
IDE0068 - How do I disable it forever?

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/roslyn-analyzers#2618]
Hi,
How do I disable specific analysis on a global level - not solution/project level, I want it gone on my system. Something like how you configure runtime exception handling via CTRL+ALT+E. 

When FxCop analyzers were being used, this used to be quite simple to configure via the Code Analysis tab. But now with .NET Core projects (esp. library projects), there is no such option. In fact, the Code Analysis page in the Project Properties says that the page is deprecated and will be removed.

**Comment by mavasani** [comment]
@sujayvsarma You can disable IDE analysis via an editorconfig. IDE0068 does not have a code style option, so what you are requesting is only supported per project or solution. In very near future, we will support your scenario, I will post an update here once it is supported.

**Comment by sujayvsarma** [comment]
More detailed directions please.

**Comment by mavasani** [comment]
For now, you need to use a code analysis ruleset or nowarn to disable a specific diagnostic ID for a project or solution. You can read more about rulesets here: https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2019

**Comment by sujayvsarma** [comment]
It's a .NET Core Class Library project, so there is no "Code analysis" tab shown for the project. Also, which of these match IDE0068 ?

![image](https://user-images.githubusercontent.com/7371750/59993187-ec80a900-966c-11e9-97e0-a2054fd25992.png)

**Comment by sujayvsarma** [comment]
Also, I have this turned off in `GlobalSuppressions.cs`. But the message is still there in the Errors List

**Comment by mavasani** [comment]
Even for .NetCore projects you can create a custom ruleset and set the project's MSBuild `CodeAnalysisRuleSet` property to this file. THe file should have an entry which sets Action for `IDE0068` to `None`.

**Comment by mavasani** [comment]
Closing the issue as IDExxxx diagnostics are not added by packages in this repo. Refer to https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2019 for using rulesets to disable analyzer diagnostics.

**Comment by brian-reichle** [comment]
@sujayvsarma

> Also, which of these match IDE0068 ?

None of them, they are all related to various FxCop rules. IDE analyzers generally don't show in that 'ruleset designer'. If you edit the underlying ruleset xml (the only way to go) you can manually disable the rule.

```
<RuleSet Name="Foo">
  <Rules AnalyzerId="Microsoft.CodeAnalysis.Features" RuleNamespace="Microsoft.CodeAnalysis.Features">
    <Rule Id="IDE0068" Action="None" />
  </Rules>
</RuleSet>
```
