### ISSUE TITLE
Fix for PublicApiAnalyzer adds one row per partial part.

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#2620]
```cs
public static partial class C
{
}
```

```cs
public static partial class C
{
}
```

Think above should be enough to repro, not sure if they must be in separate documents.
The fix adds two rows to `PublicAPI.Unshipped.txt`

Then `RS0025` correctly warns that it appears more than once.

**Comment by mavasani** [comment]
Verified that the fix itself adds just the single entry, but a FixAll in document (or project if the partial types are split across files) adds duplicate entries.

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2195
