### ISSUE TITLE
PublicAPIAnalyzer does not function in MSBuild 14

### ISSUE THREAD

**Issue by Digmaster** [dotnet/roslyn-analyzers#2626]
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApianalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/)

#### Package Version

v2.9.3 (Latest)

#### Diagnostic ID

N/A

#### Repro steps

1. Create a project which should create a warning.
2. Build using an old msbuild binary (in my case 14.0.24723.2).

#### Expected behavior
Warnings being generated.

#### Actual behavior
No warnings whatsoever.

In particular, if this dependency is expected, I'm wondering why. I have no qualms with creating a private fork without this dependency (as StyleCop analyzers function correctly in msbuild 14, I'd expect this analyzer could work the same), however some guidance for why this dependency exists would be very appreciated.

**Comment by mavasani** [comment]
Tag @sharwell - I believe this analyzer requires Microsoft.CodeAnalysis 1.2.x, which is a specific update on top of Dev14.

**Comment by Evangelink** [comment]
@sharwell @mavasani Do you plan to do some work on this issue?

**Comment by sharwell** [comment]
@Digmaster if you add the following in your code, what error message is printed when you run with MSBuild 14? This will tell us the compiler version in question so we can narrow this down.

```
#error version
```

**Comment by Evangelink** [comment]
Ping @Digmaster

**Comment by mavasani** [comment]
Closing as no response from the issue author.
