### ISSUE TITLE
Codefix for RS0036: Public API files must exist

### ISSUE THREAD

**Issue by Digmaster** [dotnet/roslyn-analyzers#2628]
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApianalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/)

#### Package Version

v2.9.3 (Latest)

#### Diagnostic ID

[RS0036](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

#### Repro steps

1. Create a new project
2. Add the PublicAPIAnalyzers nuget
3. Do not add PublicAPI.Shipped.txt or PublicAPI.Unshipped.txt

#### Expected behavior
A warning is created, and a codefix can be used to automatically fix the warning by creating the files.

#### Actual behavior
The warning is created (per PR [2627](https://github.com/dotnet/roslyn-analyzers/pull/2627)), however no codefix exists.

**Comment by mavasani** [comment]
Actually, on second thought, I am not sure where the code fix will light up given the RS0036 diagnostic has no location. @genlu thoughts?

**Comment by mavasani** [comment]
This is no longer necessary based on https://github.com/dotnet/roslyn-analyzers/issues/2622
