### ISSUE TITLE
RunCodeAnalysis=false still trigger analyzer warnings/errors

### ISSUE THREAD

**Issue by heaths** [dotnet/roslyn-analyzers#2652]
Seemingly related to #1341 we are setting `RunCodeAnalysis=false` in some cases, but still get, for example, SA* errors. The workaround in #1341 is a lot of work DevOps has to do just to work around not honoring a property that has existed for a long time to disable code analysis. Wouldn't it be more appropriate to respect the `RunCodeAnalysis` property?

**Comment by heaths** [comment]
After posting this, I stumbled upon dotnet/roslyn#23591 but it's been open for a while with no updates.

**Comment by mavasani** [comment]
`RunCodeAnalysis` is unrelated to execution of Roslyn code analyzers. It only controls execution of legacy post-build code analysis (FxCopCmd), which is on path to deprecation. See https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers-faq?view=vs-2019#does-the-run-code-analysis-command-run-fxcop-analyzers

The only way for you to turn off all analyzers would be to use the workaround mentioned [here](https://github.com/dotnet/roslyn/issues/23591#issuecomment-507802134), until there is an actual MSBuild property that is respected by compiler build task.
