### ISSUE TITLE
Port fixes from BannedApiAnalyzer to RestrictedIVTAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2655]
We should port https://github.com/dotnet/roslyn-analyzers/pull/2515 and https://github.com/dotnet/roslyn-analyzers/pull/2516

**Comment by drewnoakes** [comment]
Is there a reason we cannot pull out the common code between these analyzers? The proposed namespace isolation analyzer in #2161 could utilise this as well.
