### ISSUE TITLE
Would like to have a Rule to check that a Function Result is not ignored

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/roslyn-analyzers#2667]
To foster functional programming I would like to have a Rule that by default checks that the Result of a Function is either used or explicitly ignored e.g. by assigning it to a dummy Variable: 
`Func(x) ` should result in a Warning 
`var _ = Func(x) ` should be fine. 

This should avoid wrong usage. 

I know that this can be achieved using the [Pure] Attribute or the [MustUseReturnValue] of Resharper, but I don't want to unnecessarily annotate thousands of Functions with these Attributes, but rather except certain Methods from this. 

To this purpose I would add an Attribute similar to [NeedNotUseReturnValue] or [HasSideEffects("list the side effects")] to allow ignoring the results of impure Methods (and especially fluent Interfaces which usually have Return Values AND Side Effects)

I would offer to write such a rule. 
What do you think?

**Comment by SpocWeb** [comment]
Update: I found a partial Workaround: 
By promoting the IDE Warnings IDE0058 and IDE0060 to Errors I get Errors for Expressions with ignored Results. Unfortunately this forces me to explicitly ignore the result using e.g. _ = ... at each instance which is not too bad though. Still, an Attribute like the proposed [NeedNotUseReturnValue] or [HasSideEffects("list the side effects")] would be nice to get rid of these unnecessary warnings.

**Comment by mavasani** [comment]
Going to mark this as external as the IDE analyzers are implemented in the roslyn repo. Feel free to file a feature request in that repo if you feel the attribute based approach is desirable.
