### ISSUE TITLE
CA1820:Test for empty strings using string length should not fire on VB code

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#2684]
The analysis for CA1820 is wrong for VB and its recommendation fix "replace with string.Length" can introduce null references. VB's string comparisons already do both a null and Length check under the covers,

``` VB
         If appConfigOrProjectFile <> "" Then
                filesToCheckOut.Add(appConfigOrProjectFile)
            End If
```

**Comment by mavasani** [comment]
The analysis is correct. Probably the code fix should have a null check OR we should have 2 code fixes: one which adds a null check before length check and another one with just the length check.

**Comment by davkean** [comment]
VB string comparisons always call this method: http://index/?query=CompareString&rightProject=Microsoft.VisualBasic&file=Helpers%5COperators.vb&line=939, which does a length check. The analysis isn't correct.
