### ISSUE TITLE
CA1062 fires even if parameter is checked for null using null propagation operator

### ISSUE THREAD

**Issue by bittusarkar** [dotnet/roslyn-analyzers#2689]
For the following dummy code, FxCop reports a "CA1062: Validate arguments of public methods" error although the method parameter is checked for `null` using the null propagation operator. Ideally, it should not report this error. Now I have to split this into two `null` checks to bypass the error.

```
public void TestMethod(TestClass testObject)
{
    if (testObject?.TestProperty == null)
    {
        throw new ArgumentException(...);
    }
    
    DoSomethingWith(testObject.TestProperty);
}
```

**Comment by mavasani** [comment]
@bittusarkar Can you please clarify how are you running your analysis? Are you executing `Run Code Analysis` or setting `RunCodeAnalysis` msbuild property OR are you using the [latest](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.4-beta1.final) FxCop analyzers NuGet package? Note that the former has been [deprecated](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2019), and you should be using the FxCop analyzers package.

**Comment by mavasani** [comment]
I tried the following simple repro with the latest FxCopAnalyzers NuGet package and confirmed no CA1062 fires for it:

```csharp
public class TestClass
{
    public object TestProperty { get; set; }
    public void TestMethod(TestClass testObject)
    {
        if (testObject?.TestProperty == null)
        {
            throw new Exception();
        }

        DoSomethingWith(testObject.TestProperty);
    }

    private void DoSomethingWith(object o) { var x = o.ToString(); }
}
```
