### ISSUE TITLE
DeclarePublicApiFix crashes with NRE

### ISSUE THREAD

**Issue by TimothyMothra** [dotnet/roslyn-analyzers#2690]
#### Analyzer package

Microsoft.CodeAnalysis.PublicApiAnalyzers

#### Package Version
v2.9.3

#### Diagnostic ID

RS0016	Symbol 'implicit constructor for _' is not part of the declared API.	

#### Repro steps

1. Clicking on "Show potential fixes"
1. Click "Add implicit constructor to public api"
1. Error "DeclarePublicApiFix" encountered an error and has been disabled."

#### Expected behavior

I would expect it to add the constructor to my public api file.

#### Actual behavior

> 
> System.AggregateException : One or more errors occurred. ---> Object reference not set to an instance of an object.
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
>    at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
> ---> (Inner Exception #0) System.NullReferenceException : Object reference not set to an instance of an object.
>    at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyTextDocumentChange(DocumentId documentId,SourceText newText)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyAdditionalDocumentTextChanged(DocumentId documentId,SourceText newText)
>    at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
>    at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
>    at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
>    at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
>    at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
>    at async Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ApplyAsync(<Unknown Parameters>)<---
>

**Comment by mavasani** [comment]
@MS-TimothyMothra Can you provide repro code on which you executed the code fix?

**Comment by MS-TimothyMothra** [comment]
@mavasani 
We use this analyzer in the ApplicationInsights BaseSDK repo https://github.com/microsoft/ApplicationInsights-dotnet

Something unique about our project, we're targeting multiple frameworks (net45;net46;netstandard1.3;netstandard2.0). Each framework can have unique apis, so [we actually have a txt file per framework.](https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/PublicAPI/Microsoft.ApplicationInsights.dll)

I'm using Visual Studio 2019 (v16.1.6).
I was applying multiple fixes at a time and after the one or two fixes, the Analyzer stopped applying new fixes.

To get this to work I had to restart Visual Studio and use the analyzer against one framework at a time until that framework was 100% compliant. 


---
My team loves this tool. Thank you :)

**Comment by MS-TimothyMothra** [comment]
If you want to try to repro, look at our develop branch before this commit: https://github.com/microsoft/ApplicationInsights-dotnet/pull/1176

**Comment by mavasani** [comment]
Closing as this is a very old issue. Kindly re-open on roslyn repo if you see it again.
