### ISSUE TITLE
Deploy analyzer extensions to a different hive

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn-analyzers#275]
Right now building our analyzer extensions deploys them to the RoslynDev hive, which is the same hive used by extensions built from [dotnet/roslyn](https://github.com/dotnet/roslyn). This means a bad set of extensions built out of dotnet/roslyn could prevent VS from loading when trying to debug analyzers from dotnet/roslyn-analyzers (see #274).

To avoid this, we should deploy the analyzer extensions to the RoslynAnalyzers hive instead.

**Comment by srivatsn** [comment]
We should update  the readme file with the name of the hive and instructions to debug.

**Comment by mavasani** [comment]
This hasn't been a noticeable problem off late, closing until we get any feedback this is required.
