### ISSUE TITLE
AD0001: NRE in Microsoft.NetFramework.Analyzers.DoNotUseInsecureDtdProcessingAnalyzer

### ISSUE THREAD

**Issue by RickKra** [dotnet/roslyn-analyzers#2753]
#### Analyzer package

Microsoft.NetFramework.Analyzers

#### Package Version

2.9.4-beta1.final

#### Diagnostic ID

[AD0001]Analyzer   'Microsoft.NetFramework.Analyzers.DoNotUseInsecureDtdProcessingAnalyzer'   threw an exception of type 'System.NullReferenceException' with message   'Object reference not set to an instance of an object.'.

#### Repro steps

Used this analyzer on a run against the Visual Studio repo and it failed on src\dp\src\tools\XmlLanguageService\src\SchemaService\KnownSchemas.cs.

#### Expected behavior

Analyze the file

#### Actual behavior

Threw an exception.

#### Notes

This was investigated by Manish Vasani, who said:

Likely the faulty code is below, which has an “as expression” which is not followed by a null check before member access:

https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs#L582-L584

IConversionOperation conv = expression.Value as IConversionOperation;

if (SecurityDiagnosticHelpers.IsXmlSecureResolverType(conv.Operand.Type, _xmlTypes))

**Comment by chewiiieee** [comment]
**Testcase**
Create file whatever.vb file in VStudio 16.2.1 (Enterprise).
Module foo
    Public Sub LoadXmlSafe(xmlresolvr As XmlResolver, inputUri As String)
        Dim doc As New XmlDocument()
        doc.XmlResolver = xmlresolvr
    End Sub
End Module

**Workaround**:
Module foo
    Public Sub LoadXmlSafe(xmlresolvr As XmlResolver, inputUri As String)
        Dim doc As New XmlDocument() With {.XmlResolver = Nothing}
    End Sub
End Module
