### ISSUE TITLE
New rules are not showing in Visual Studio ruleset editor

### ISSUE THREAD

**Issue by Gav-Brown** [dotnet/roslyn-analyzers#2757]
#### Visual Studio Version

Visual Studio 2019 v16.2.1

#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

But may apply to any analyser.

#### Package Version

v2.9.4 (Latest)

#### Diagnostic ID

All new rules introduced in between `v2.6.3` and `v2.9.4`

#### Repro steps

1. Using v2.6.3, create a ruleset with all rules enabled and set to Error (for example)
2. Upgrade to v2.9.4
3. Open ruleset in Visual Studio editor

#### Expected behaviour

1. New rules would be shown
2. New rules would have default values i.e. not set to Error

#### Actual behaviour

1. New rules are not shown

Due to this I can't see what new rules have been added, or enable or disable them as required.
Note that any upgrade prior to v2.6.3 always showed the new rules in the VS ruleset editor.

Also, due to #2473, even if they were shown I wouldn't know what they were.

Both these issues make managing rulesets tricky.

![Ruleset](https://user-images.githubusercontent.com/36932614/62839630-1ecd8080-bc84-11e9-9668-8a9d248613f9.png)

**Comment by Gav-Brown** [comment]
Example of the ruleset I am using. Though applies to any.
[CodeAnalysis.AllRulesEnabled.ruleset.txt](https://github.com/dotnet/roslyn-analyzers/files/3490451/CodeAnalysis.AllRulesEnabled.ruleset.txt)

**Comment by mavasani** [comment]
Can you try on latest 16.3 preview build? I believe this has been fixed.

**Comment by Gav-Brown** [comment]
@mavasani Thanks. I'll retest and close once 16.3 has been released.

**Comment by mavasani** [comment]
![image](https://user-images.githubusercontent.com/10605811/63552535-b33dab80-c4ec-11e9-93ca-5ea2f5225770.png)

Fixed in VS2019 16.3
