### ISSUE TITLE
Roslyn-specific analyzer projects do not use meta-analyzers

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#277]
Ported from https://github.com/dotnet/roslyn/issues/3636

That is, the RoslynDiagnosticAnalyzers project (and the related C#- and VB-specific projects) does not make use of Microsoft.CodeAnalysis.Analyzers. If they did, we wouldn't have run into https://github.com/dotnet/roslyn/issues/3626 -- the problem would have been caught ahead of time.

**Comment by mavasani** [comment]
This seems to be fixed in the new solution.
