### ISSUE TITLE
FxCop CA2235 is unaware of [NonSerialized] attribute

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#279]
Ported from https://github.com/dotnet/roslyn/issues/4591

-----------------

Hello,

using "Microsoft.CodeAnalysis.FxCopAnalyzers" v1.0.1, I get a false positive for rule CA2235.
My field has the [NonSerialized] applied, but it still reports a violation of CA2235:

        [NonSerialized]
        //// ReSharper disable once MemberCanBePrivate.Global
        //// ReSharper disable once UnassignedField.Global
        public Action<string> SomeAction;

Best regards,
Ralf

**Comment by fmoliveira** [comment]
A similar issue has been reported at dotnet/roslyn#3801 and fixed in #261 .

**Comment by srivatsn** [comment]
Verified that this is fixed.
