### ISSUE TITLE
Metrics.exe : generated Xml does not distinguish nested types.

### ISSUE THREAD

**Issue by RachelDavids** [dotnet/roslyn-analyzers#2804]
Microsoft.CodeAnalysis.Metrics

https://www.nuget.org/packages/Microsoft.CodeAnalysis.Metrics/

v2.9.4 (Latest)

When reviewing the generated XML for my project, for which several classes have a nested private structure(all with the same name), the nested types are not qualified in any way.

This makes it difficult to determine which nested class belongs to which parent. 

Further, if there is a name clash between outer/inner class names, this becomes much more difficult to resolve.

Would it be possible to make the Name attribute include the parent name e.g. ParentName.InnerName?

**Comment by mavasani** [comment]
@RachelDavids That would be a single line change over here: https://github.com/dotnet/roslyn-analyzers/blob/3f44df7de96267a2b0bf7a4ba6a0086fc560fc18/src/Tools/MetricsOutputWriter.cs#L63

Would you be willing to contribute a PR for the fix, so you can even validate the fix works for your case?

**Comment by Evangelink** [comment]
@RachelDavids There is an open PR, if you want to take a couple of minutes to check this solves the issue you are facing that would be nice.

**Comment by RachelDavids** [comment]
@Evangelink @mavasani When using the View Code metrics option in visual studio, the nested types are listed separately, but simply qualified with the parent eg. Type.NestedType When a Nested Type has a nested Type this continues e.g. Type.NestedType.NestedType etc.
This would be my preferred option.

**Comment by mavasani** [comment]
I agree with @RachelDavids
