### ISSUE TITLE
CA1801: Exempt parameters documented "The parameter is not used"

### ISSUE THREAD

**Issue by peteroupc** [dotnet/roslyn-analyzers#2805]
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) v2.9.4.

Exempt a parameter from CA1801, "Review unused parameters", if the parameter is documented with the text "The parameter is not used." or its equivalent in other languages.  This is the exact text used when exempting documentation elements from duplicate checks by StyleCop, and this text already signals that the parameter in question is intentionally unused.

Example:

    /// <summary>This is a test.</summary>
    /// <param name='param'>The parameter is not used.</param>
    public static void Test(int param) {
    }

**Comment by mavasani** [comment]
There is no such convention that a comment with a specific text should indicate a suppression - this gets especially confusing when comments are localized. A better approach is to port the logic used in Roslyn's implementation of this analyzer to allow using special parameter names to indicate discard parameters: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs,333

Let us use this issue to track porting this logic.

**Comment by peteroupc** [comment]
In case you're not familiar, here is the StyleCop Analyzers rule making an exception for "The parameter is not used": [SA1625: Element documentation must not be copied and pasted](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/57821a1c4d014e8d80b3e236ff444e0e30d8a112/documentation/SA1625.md); [implementation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1625ElementDocumentationMustNotBeCopiedAndPasted.cs).

**Comment by mavasani** [comment]
@peteroupc Every third party analyzer package has the freedom to define its own heuristics for bailing out or not reporting diagnostics. It is not feasible to keep all analyzer packages in sync in terms of the heuristics used.

**Comment by peteroupc** [comment]
Note that StyleCop Analyzers is far from a "third-party analyzer package" in relation to this one &mdash; at least it seems to me.  I agree that this would not be so relevant if the relation between Roslyn Analyzers and StyleCop Analyzers weren't as close as it is.

**Comment by mavasani** [comment]
@peteroupc I am not sure how you came to that conclusion. For example, does StyleCop analyzer respect Roslyn's heuristic for marking unused parameter: http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs,333. Majority of analyzer packages available out there have lot of overlapping rules, I am sure StyleCop analyzers has overlap with Roslyn's inbuilt IDE code style rules and some of the analyzers in this repo - it is not possible to make these implementations uniform. I would suggest that anyone using multiple analyzer packages should not expect uniformity between identical rules in packages. Instead, when you come across overlapping rules, you should choose a particular implementation that suits you better and disable the other one through ruleset file or nowarn entry.

**Comment by mavasani** [comment]
Seems like https://github.com/dotnet/roslyn-analyzers/pull/2638 already ensures that parameters named as `_`, `_1`, `_2`, etc. are already treated as special discard parameter names.
