### ISSUE TITLE
New rule: Using nameof(...) correctly in ArgumentException constructor

### ISSUE THREAD

**Issue by mareklinka** [dotnet/roslyn-analyzers#2810]
A split off issue from [corefx/issues/40739](https://github.com/dotnet/corefx/issues/40739) to track the suggested rule

`ArgumentException arguments. Find places where nameof(…) is passed as the first (rather than second) argument to ArgumentException.`

I'd like to include this in a small hackathon coming up this weekend and so I'd like to get some guidance and/or suggestions where best to start.

I expect this situation should be relatively straightforward to detect but I haven't worked with Roslyn APIs in quite some time so any advice would be greatly appreciated.

To start, I think the analyzer should cover both `ArgumentException` constructors that take the parameter name:

```
public ArgumentException (string message, string paramName);
public ArgumentException (string message, string paramName, Exception innerException);
```

The detection should then look at the first argument, evaluate whether it's a `nameof(...)` call targeting any parameter of the containing method, and if so, report a warning.

Some questions that come to mind:
1. Do we want an automated fix for this? If so, what would be the preferred fix? Just swap the first and second argument? What if both are `nameof(...)` calls?
2. Do we want to cover also exceptions derived from `ArgumentException`? This might get complicated for custom exception types - we would need to track the `nameof(...)` value flow from the custom exception ctor all the way down to the `ArgumentException` ctor.
3. Detection rules have severities, if I remember correctly - I assume this rule should be reported as a warning by default?

**Comment by KrisVandermotten** [comment]
I have a rule such as this one implemented over a year ago, and I'm willing to contribute. As for what it does, these are its unit tests:

            [TestMethod]
            public void TestThrowArgumentNullExceptionExpressionNamesAnExistingParameter()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            string s = a ?? throw new ArgumentNullException(nameof(a));
        }
    }
    ";
                Verify(test).HasDiagnostics(0);
            }

            [TestMethod]
            public void TestThrowArgumentExceptionStatementNamesAnExistingParameter()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentException(""blahblahblah"", nameof(a));
        }
    }
    ";
                Verify(test).HasDiagnostics(0);
            }

            [TestMethod]
            public void TestArgumentNullExceptionNamesAnExistingParameter()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentNullException(nameof(a));
        }
    }
    ";
                Verify(test).HasDiagnostics(0);
            }

            [TestMethod]
            public void TestArgumentExceptionWithoutParameters()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentException();
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,15): error U2U2031: When throwing an ArgumentException, include the name of an existing parameter in the exception")
                    .IsFixedBy(test);
            }

            [TestMethod]
            public void TestArgumentNullExceptionWithoutParameters()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentNullException();
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,15): error U2U2031: When throwing an ArgumentNullException, include the name of an existing parameter in the exception")
                    .IsFixedBy(test);
            }

            [TestMethod]
            public void TestArgumentExceptionWithoutParameterName()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentException(""blahblahblah"");
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,15): error U2U2031: When throwing an ArgumentException, include the name of an existing parameter in the exception")
                    .IsFixedBy(test);
            }

            [TestMethod]
            public void TestArgumentNullExceptionExpressionWithoutParameteName()
            {
                const string test = @"
    using System;

    class C
    {
        public C(string p)
        {
            P = p ?? throw new ArgumentNullException();
        }

        public string P { get; }
    }
    ";
                const string testfix = @"
    using System;

    class C
    {
        public C(string p)
        {
            P = p ?? throw new ArgumentNullException(nameof(p));
        }

        public string P { get; }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,24): error U2U2031: When throwing an ArgumentNullException, include the name of an existing parameter in the exception")
                    .IsFixedBy(testfix, allowNewCompilerDiagnostics: true);
            }

            [TestMethod]
            public void TestArgumentNullExceptionStatementInIfWithoutParameteName()
            {
                const string test = @"
    using System;

    class C
    {
        public C(string p)
        {
            if (p == null)
            {
                throw new ArgumentNullException();
            }
        }
    }
    ";
                const string testfix = @"
    using System;

    class C
    {
        public C(string p)
        {
            if (p == null)
            {
                throw new ArgumentNullException(nameof(p));
            }
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(10,19): error U2U2031: When throwing an ArgumentNullException, include the name of an existing parameter in the exception")
                    .IsFixedBy(testfix, allowNewCompilerDiagnostics: true);
            }

            [TestMethod]
            public void TestArgumentNullExceptionStatementInElseWithoutParameteName()
            {
                const string test = @"
    using System;

    class C
    {
        public C(string p)
        {
            if (null != p)
            {
            }
            else
            {
                throw new ArgumentNullException();
            }
        }
    }
    ";
                const string testfix = @"
    using System;

    class C
    {
        public C(string p)
        {
            if (null != p)
            {
            }
            else
            {
                throw new ArgumentNullException(nameof(p));
            }
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(13,19): error U2U2031: When throwing an ArgumentNullException, include the name of an existing parameter in the exception")
                    .IsFixedBy(testfix, allowNewCompilerDiagnostics: true);
            }

            [TestMethod]
            public void TestArgumentExceptionNamesANonExistingParameter()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentException(""blahblahblah"", ""nonexisting"");
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,15): error U2U2031: When throwing an ArgumentException, include the name of an existing parameter in the exception")
                    .IsFixedBy(test);
            }

            [TestMethod]
            public void TestArgumentNullExceptionNamesANonExistingParameter()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentNullException(""nonexisting"");
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,15): error U2U2031: When throwing an ArgumentNullException, include the name of an existing parameter in the exception");
            }

            [TestMethod]
            public void TestArgumentNullExceptionWithDynamicMessage()
            {
                const string test = @"
    using System;

    class C
    {
        public void M(string a)
        {
            throw new ArgumentNullException(""the string '"" + a + ""' is too short"");
        }
    }
    ";
                Verify(test).HasDiagnostics(
                    "Test.cs(8,15): error U2U2031: When throwing an ArgumentNullException, include the name of an existing parameter in the exception");
            }

            [TestMethod]
            public void TestArgumentOutOfRangeExceptionInSwitchStatement()
            {
                const string test = @"
    enum Color { Red, Green, Blue }

    class C
    {
        void M(Color color)
        {
            switch(color)
            {
                case Color.Red:
                case Color.Green:
                case Color.Blue:
                    break;
                default:
                    throw new System.ArgumentOutOfRangeException();
            }
        }
    }
    ";
                const string testfix = @"
    enum Color { Red, Green, Blue }

    class C
    {
        void M(Color color)
        {
            switch(color)
            {
                case Color.Red:
                case Color.Green:
                case Color.Blue:
                    break;
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(color));
            }
        }
    }
    ";
                Verify(test).HasDiagnostics(1).IsFixedBy(testfix, allowNewCompilerDiagnostics: true);
            }

            [TestMethod]
            public void TestCreateAndThrowArgumentNullException()
            {
                const string test = @"
    using System;

    class C
    {
        public void CreateAndThrowArgumentNullException(string name)
        {
            throw new ArgumentNullException(name);
        }
    }";
                Verify(test).HasDiagnostics(0);
            }
        }

Hopefully, these can help the discussion moving forward.

**Comment by Youssef1313** [comment]
Shouldn't this be handled by CA2208 (if not already handled)

**Comment by mavasani** [comment]
Yes, this may likely have been handled in CA2208 by @buyaa-n's recent updates to that analyzer. Buyaa, can you please verify/triage?

**Comment by mavasani** [comment]
@buyaa-n Feel free to port it to dotnet/runtime for triage if you feel this is not already covered by your enhancements to CA2208

**Comment by buyaa-n** [comment]
There is an existing analyzer/fixer for [nameof(...)](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1507) which is more generic not only for ArgumentException and covering the above scenario. I think all scenarios in this issue are covered by [ArgumentException analyzer](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208) and[ nameof(...)](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1507) analyzers

**Comment by buyaa-n** [comment]
> @buyaa-n Feel free to port it to dotnet/runtime for triage if you feel this is not already covered by your enhancements to CA2208

@mavasani i don't see any scenario not covered with updated [ArgumentException analyzer](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208) and existing [ nameof(...)](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1507) analyzers, gonna close this issue, thanks
