### ISSUE TITLE
For VB Contract.ThrowIfNull does not supress CA1062 and String should should not warn CA1062

### ISSUE THREAD

**Issue by paul1956** [dotnet/roslyn-analyzers#2815]
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.9.4 (Latest)

#### Diagnostic ID
 CA1062 

#### Repro steps
        <Fact>
        Public Shared Sub VBNothing()
            Assert.True(NothingTest1(Nothing))
        End Sub

        Public Shared Function NothingTest1(X As String) As Boolean
            Contract.ThrowIfFalse(X Is Nothing) ' Contract.ThrowIfTrue(X Is Nothing)  produces same issue
            Return X.IsEmptyNullOrWhitespace
        End Function
#### Expected behavior
 CA1062 should not warn on X, in VB a Nothing String is equal to ""
#### Actual behavior
Warns

**Comment by paul1956** [comment]
There are 2 issues here, the recommended fix
1) Using Contract to test for Null (Nothing in VB) does not suppress this warning as stated in documentation for CS1062.
2) For String in VB this warning is never needed, it will never throw an exception referencing off it in VB, in fact that is a normal way to tests for Nothing or String.Empty .

**Comment by mavasani** [comment]
@paul1956 I did not find a definition for `Contract.ThrowIfFalse`. Are you referring to the custom helper in Roslyn? We have the below test which verifies Contract checks work for VB: https://github.com/dotnet/roslyn-analyzers/blob/a9b86aadc80a604fb14351a84771525af62797d7/src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/ValidateArgumentsOfPublicMethodsTests.cs#L1295-L1333

**Comment by mavasani** [comment]
> For String in VB this warning is never needed, it will never throw an exception referencing off it in VB, in fact that is a normal way to tests for Nothing or String.Empty

@paul1956 Following code seems to throw a NullReferenceException for me.
![image](https://user-images.githubusercontent.com/10605811/64459962-15caa600-d0ae-11e9-9545-c4f18a3221be.png)
Additionally, I noticed that even legacy FxCop reported the same CA1062 for dereference off a String parameter without a null check. Am I missing something?

**Comment by paul1956** [comment]
I stand corrected,  I am getting 1,000's of errors on VB strings after installing  but I use an extension on Contract not System.Diagnostics.Contracts.Contract.Requires(x IsNot Nothing), If I use that I don't get the warning. I think the Documentation needs to be clearer. If I replace the extension with             Contracts.Contract.Requires(X IsNot Nothing), the warning go away. Just saying "Use a contract is not clear enough. I will close, there is already an issue against documentation.
