### ISSUE TITLE
CA1068 (CancellationTokenParametersMustComeLast) should be configurable to allow not flagging public APIs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#2851]
Analyzer should ideally respect [api_surface](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#analyzed-api-surface) editorconfig option for end user configuration.

**Comment by Evangelink** [comment]
@mavasani Could you add a `Breaking Change` label and flag this ticket. 

The rule used to report for private members but after this change it will stop reporting. I think this is an acceptable change but it would be nice to explicitly call out these changes in the release notes. I think that's even more important that this repo is not really following the semantic versioning so from a user point of view, it's hard to tell whether or not I can safely update.
