### ISSUE TITLE
StyleCop needs Microsoft.Analysis

### ISSUE THREAD

**Issue by R-Murison** [dotnet/roslyn-analyzers#2858]
Environment VisualStudio 2019 (and 2017 have looked at it in both with the same reults)

I have been upgrading our StyleCop to StyleCop.Analyzers.1.1.118
Usually this works fine on 4 other projects I have done it for so far. 
However on our WebUI project
I am getting the error on some but not all StyleCop warnings.

"cannot be created from D:\Dev\Git\prism-web-ui\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis"

When StyleCop.Analyzer has no dependencies.
I tried adding the Latest Microsoft.CodeAnalysis but that has no effect.

I also read that FxCop has exactly the same issue With FxCop
https://github.com/dotnet/roslyn-analyzers/issues/1785
I tried the suggested fix and applied that to StyleCop.Analyzers.1.1.118 but that did solve the issue.
I changed:
  ```
`<ItemGroup>`
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll"/>
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll"/>
  </ItemGroup>
```
to:
 ```
 <ItemGroup>
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll">
      <PrivateAssets>all</PrivateAssets>     
    </Analyzer>
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll">
      <PrivateAssets>all</PrivateAssets>
    </Analyzer>
  </ItemGroup>
```
As it did not work I reverted the change but I still cannot use StyleCop.Analyzers.1.1.118 on this project.

**Comment by mavasani** [comment]
Tagging @sharwell. @R-Murison would you be able to port this issue to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues?

**Comment by R-Murison** [comment]
Transfered to the right project
