### ISSUE TITLE
Add support for SuppressMessageAttribute.MessageId

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [dotnet/roslyn-analyzers#2865]
There is no option to avoid consequent violation to suppressed rule applied to method. To do so analyzers should support [_MessageId_](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute.messageid?view=netframework-4.8#System_Diagnostics_CodeAnalysis_SuppressMessageAttribute_MessageId) property.

    [SuppressMessage("SomeCat", "SomeRule")]
    void SomeMethod()
    {
     // line violating SomeRule
    } 

Relevant articles:
1. [SuppressMessageAttribute Class](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute?view=netframework-4.8)
2. Suppress code analysis warnings/[Suppress selective violations within a method body](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#suppress-selective-violations-within-a-method-body)

Further more if _MessageId_ is specified _SuppressMessageAttribute_ is ignored, i.e. error is report anyway (by _Managed Binary Analysis_).

`[SuppressMessage("SomeCat", "SomeRule, MessageId = "someVar")]`

**Comment by mavasani** [comment]
@JiriCepelkaFirstLineSoftware This issue should be ported to https://github.com/dotnet/roslyn/issues. Also note that MessageId was supported by suppressions for [legacy FxCop](https://docs.microsoft.com/en-us/visualstudio/code-quality/static-code-analysis-for-managed-code-overview?view=vs-2019) but has never been supported for [Roslyn analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019). It is unlikely that support will be added unless you cite a strong reason why you need it.

**Comment by mavasani** [comment]
Note that https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#suppress-selective-violations-within-a-method-body feature was relevant for legacy FxCop as it did IL based analysis. With Roslyn analyzers, you can use #pragma based suppressions to suppress diagnostics on specific source lines.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
For me pragma directive is not working.

    public void MultiDispose()
    {
    #pragma warning disable CA2202
      using (var ms = new MemoryStream())
      {
        using (var streamWriter = new StreamWriter(ms))
        {
        }
      }
    #pragma warning restore CA2202
    }

**Comment by JiriCepelkaFirstLineSoftware** [comment]
For me pragma directive is not working – VS 2017 Community 15.9.16.

public void MultiDispose()
{
#pragma warning disable CA2202
  using (var ms = new MemoryStream())
  {
    using (var streamWriter = new StreamWriter(ms))
    {
    }
  }
#pragma warning restore CA2202
}

**Comment by mavasani** [comment]
Please see https://github.com/dotnet/roslyn/issues/38827#issuecomment-534727723
