### ISSUE TITLE
CA1824 should detect NeutralLanguage defined in csproj file

### ISSUE THREAD

**Issue by starkcolin** [dotnet/roslyn-analyzers#2868]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
v2.9.5-beta1.final (Latest)

#### Diagnostic ID

[CA1824](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca1824-mark-assemblies-with-neutralresourceslanguageattribute)

#### Repro steps

1. Define NeutralLanguage in a csproj file, as per https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

#### Expected behavior
No warning is shown

#### Actual behavior
Warning is shown

**Comment by Evangelink** [comment]
@starkcolin this seems to be ok with 2.9.8

**Comment by Evangelink** [comment]
@mavasani I think the error is solved and so ticket can be closed.
