### ISSUE TITLE
Microsoft.NetCore.Analyzers.Security.DoNotHardCodeEncryptionKey throws InvalidCastException

### ISSUE THREAD

**Issue by BrunoJuchli** [dotnet/roslyn-analyzers#2870]
#### Analyzer package

Probably [Microsoft.NetCore.Analyzers](https://www.nuget.org/packages/Microsoft.NetCore.Analyzers/2.9.4)

Source file is: https://github.com/dotnet/roslyn-analyzers/blob/3e4ef017b0a83b1330527b35aa2781bbca927e0d/src/Microsoft.NetCore.Analyzers/Core/Security/DoNotHardCodeEncryptionKey.cs

#### Package Version

2.9.4 (Latest non-pre)

#### Diagnostic ID

AD0001

#### Repro steps

1. Upgrade Analyzer from 2.9.3 to 2.9.4
1. run build
1. observe error

#### Expected behavior

No exception is thrown.

#### Actual behavior

Build fails with

> CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotHardCodeEncryptionKey' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberFieldSymbolFromDeclarator' to type 'Microsoft.CodeAnalysis.IMethodSymbol'.'.

**Comment by BrunoJuchli** [comment]
@mavasani 
How do I find out which line of code is causing this? Is there a roslyn-analyzers log or something? How would I go about debugging this, if necessary?

**Comment by mavasani** [comment]
Can you try 2.9.5-beta1.final? I believe this has already been fixed.

**Comment by BrunoJuchli** [comment]
@mavasani 
I just did & you are right. It's been fixed.
