### ISSUE TITLE
Way to suppress CA1062 for only Controller Action Results instead of whole assembly?

### ISSUE THREAD

**Issue by ideoclickVanessa** [dotnet/roslyn-analyzers#2890]
#### Analyzer package
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
v2.9.5

#### Diagnostic ID
[CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods)

#### Repro steps
Models and FluentValidators:
```
public sealed class StoreContext
{
	public int StoreID { get; set; }
}

public sealed class StoreContextValidator : AbstractValidator<StoreContext>
{
	public StoreContextValidator()
	{
		RuleFor(x => x.StoreID).NotEmpty().GreaterThan(0);
	}
}

public sealed class DateRangeContext
{
	public DateTimeOffset EndDate { get; set; }
	public DateTimeOffset StartDate { get; set; }
}

public sealed class DateRangeContextValidator : AbstractValidator<DateRangeContext>
{
	public DateRangeContextValidator()
	{
		RuleFor(x => x.EndDate).NotEmpty().GreaterThanOrEqualTo(x => x.StartDate);
		RuleFor(x => x.StartDate).NotEmpty().LessThanOrEqualTo(x => x.EndDate);
	}
}
```
Controller Action Result:
```
[HttpGet("performance")]
[ProducesResponseType(typeof(GetPerformanceFiltersApiResponse), StatusCodes.Status200OK)]
public async Task<ActionResult<GetPerformanceFiltersApiResponse>> GetPerformanceFiltersAsync([FromQuery]StoreContext storeContext,
	[FromQuery]DateRangeContext dateRangeContext)
{
	Models.PerformanceFilterLists filters =
		await filterService.GetPerformanceFiltersAsync(storeContext.StoreID, dateRangeContext.StartDate, dateRangeContext.EndDate);
	GetPerformanceFiltersApiResponse response = autoMapper.Map<GetPerformanceFiltersApiResponse>(filters);

	return Ok(response);
}
```

#### Expected behavior
With the use of the Fluent Validation validators, the storeContext and dateRangeContext params are guaranteed to not be null by the time they reach the Controller Action Result.  Therefore, ideally CA1062 would not throw a false positive.  At the very least please provide a way to suppress the warning for Controller Action Results while allowing the warning for the rest of the assembly.
#### Actual behavior
CA1062 falsely flags this line twice for possible nulls:
```
await filterService.GetPerformanceFiltersAsync(storeContext.StoreID, dateRangeContext.StartDate, dateRangeContext.EndDate);
```

_Migrated this issue from: 
https://github.com/MicrosoftDocs/visualstudio-docs/issues/4030
as the somewhat unhelpful response I received there makes me think that there currently is not a way to disable the CA1062 warning just for Controller Action Results and not the whole assembly._

**Comment by mavasani** [comment]
@ideoclickVanessa Can you try to exclude the controller symbol from CA1062 analysis by trying https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-symbol-names? For example, adding an editorconfig with following option would suppress it for any symbol named Controller.

`dotnet_code_quality.CA1062.excluded_symbol_names = Controller`

You probably want to use a fully qualified name for the symbol to restrict the bail out to specific type .

**Comment by ideoclickVanessa** [comment]
Adding
`dotnet_code_quality.CA1062.excluded_symbol_names = FilterController`
to the project's .editorconfig file did suppress the warning for that specific controller.

I was hoping
`dotnet_code_quality.CA1062.excluded_symbol_names = ControllerBase`
would disable it for all of my controllers since they are derived from ControllerBase; however, this does not seem to suppress the warning.
`dotnet_code_quality.CA1062.excluded_symbol_names = Controller`
also does not seem to work even though all of my controllers end with Controller in their names.

It is a bit unwieldy to list/manage all of my existing controllers in the .editorconfig file. Is there a wildcard pattern I should be using?

**Comment by mavasani** [comment]
We can extend CA1062 to start respecting https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-type-names-with-derived-types.

**Comment by nibblesnbits** [comment]
Shouldn't this warning ignore all `async` methods?  I recently started using the pattern [mentioned here](https://rules.sonarsource.com/csharp/tag/async-await/RSPEC-4457) which is tedious, but I find their justification valid.

**Comment by Evangelink** [comment]
`CA1062` correctly respects the `excluded_symbol_names` and `excluded_type_names_with_derived_types` user option so I am going to close this ticket.
