### ISSUE TITLE
Build hangs after upgrading to 2.9.5

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#2900]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.5 (Latest)

#### Diagnostic ID

N/A

#### Repro steps

After upgrading from 2.9.4 to 2.9.5 one of my builds hangs. How do I diagnose the issue?

#### Expected behavior
Build completes.

#### Actual behavior
Build hangs and never completes.

**Comment by mavasani** [comment]
1. Would you be able to provide a repro project/solution to investigate?
2. Otherwise, can you try to disable dataflow based rules by copying DataflowDefault.ruleset from inside the NuGet package to your project folder, changing all Dataflow rules to have Action=None, and using it as your project ruleset? If that helps we can try to dig deeper into narrowing the rule with the issue.

**Comment by avivanoff** [comment]
Correction. Build took 1 hour 53 minutes instead of 22 seconds when run with **RunAnalyzersDuringBuild=false**.

**Comment by avivanoff** [comment]
Disabling Dataflow rules fixes the problem.

**Comment by mavasani** [comment]
Wondering if its the same issue as https://github.com/dotnet/roslyn-analyzers/issues/2750. Can you try adding an editorconfig option to turn off interprocedural analysis with dataflow rules enabled (https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md):

dotnet_code_quality.interprocedural_analysis_kind = None

Note that root causing the dataflow performance issue would need some kind of a repro project.

**Comment by mavasani** [comment]
Also, if you are unable to provide a repro, would it be possible for you to selectively turn on one Dataflow rule at a time for us to know which exact rule has the issue?

**Comment by avivanoff** [comment]
The rules that takes forever is "CA5390: Do Not Hard Code Encryption Key".

**Comment by mavasani** [comment]
@avivanoff Seems like the rule is disabled by default: https://github.com/dotnet/roslyn-analyzers/blob/3e4ef017b0a83b1330527b35aa2781bbca927e0d/src/Microsoft.NetCore.Analyzers/Core/Security/DoNotHardCodeEncryptionKey.cs#L18. Did you turn on this rule explicitly with your ruleset?

Tagging @dotpaul @LLLXXXCCC - it may be an issue with Tainted analysis still being too aggressive in when to run DFA OR could be an underlying performance issue with DFA that needs to be fixed.

**Comment by avivanoff** [comment]
Yes, I did. It is a good rule.

What I just found is that this rule does not seem to work. The folowing code should trigger it,. right?
```
using (var aes = Aes.Create())
{
    aes.Key = new Byte[] { 1, 2, 3 };
}

```

**Comment by mavasani** [comment]
> Yes, I did. It is a good rule.

Great, I was just confirming if users will run into this performance issue from the default configuration or not.

Can file a separate issue for the functional bug? @dotpaul @LLLXXXCCC can comment/take a look at that issue. Thanks!

**Comment by avivanoff** [comment]
@dotpaul, @LLLXXXCCC, a new [issue](https://github.com/dotnet/roslyn-analyzers/issues/2905) was created.

**Comment by avivanoff** [comment]
Just to be clear. CA5390 causes no issues with 2.9.4.

**Comment by dotpaul** [comment]
@avivanoff Would you mind trying https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/2.9.6-beta1.19510.4+fb3ada28 ?

I expect it to be slower than 2.9.4, but should actually finish.

**Comment by avivanoff** [comment]
Looks good in 2.9.7.

**Comment by dotpaul** [comment]
#2987 also addresses this
