### ISSUE TITLE
regression: PR1958, OutputKind has no effect with shared .editorconfig

### ISSUE THREAD

**Issue by InternetPseudonym** [dotnet/roslyn-analyzers#2910]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.6

#### Diagnostic ID

[CA2007](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007-do-not-directly-await-task?view=vs-2019)

#### Repro steps

1. use shared .editoconfig file for solution with several project as outlined [here](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019#shared-configuration)
2. [configure ](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007-do-not-directly-await-task?view=vs-2019#configurability)[OutputKind ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.outputkind?view=roslyn-dotnet) **A** and setup one of the projects as type **B**
3. inside project of type **B**, `await` async method **without** using `.ConfigureAwait(bool)`
3. observe warning inside of projects of type A **and** B

#### Expected behavior

no warning for projects of type B

#### Actual behavior

warning for all types

**Comment by mavasani** [comment]
I am unable to repro this. For example, adding `dotnet_code_quality.CA2007.output_kind = ConsoleApplication` in a class library project does suppress CA2007. Can you please try latest version 3.0.0?
