### ISSUE TITLE
Avoid 'Opt' suffix in nullable-enabled code

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2920]
This will help with cleaning up the code base after nullable reference types is adopted.

https://github.com/dotnet/roslyn/pull/39053#discussion_r333089641

**Comment by Evangelink** [comment]
@sharwell I have a couple of questions related to this rule:

1. Shall we restrict the analysis to parameters and fields?

2. Is there a nice way to detect the nullable option?

3. Is it a roslyn-specific rule or do you think this shall be more global?

**Comment by Evangelink** [comment]
I have noticed the `NullableSemanticAnalysisEnabled` property but it's `internal`.
