### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of 0; "DefinitelyDisableHttpClientCRLCheck"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#2939]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Definitely disable HttpClient certificate revocation list check

File Name:
Microsoft.NetCore.Analyzers\Core\xlf\MicrosoftNetCoreAnalyzersResources.xlf

==========================================
Query:
Please confirm this is imperative (~Please definitely disable) and NOT infinitive (This function will definitely disable) ?

**Comment by sharwell** [comment]
@mavasani Can you take a look at this?

**Comment by mavasani** [comment]
Tagging @dotpaul

**Comment by dotpaul** [comment]
Sorry, that string is weird and I thought it was fixed before being merged. Lemme update it before trying to localize it.

**Comment by dotpaul** [comment]
I've updated the string to read: "HttpClients should enable certificate revocation list checks" in the 2.9.x branch. Is that the branch being localized?

**Comment by PDostalek** [comment]
Currently , we are using "master" branch for localization purposes. Other branches would have delay I think.

**Comment by dotpaul** [comment]
Okay, I'll have to watch for the localization commits and merge them to 2.9.x.  Hopefully I'll get the above mentioned string update into "master" in next couple of days.
