### ISSUE TITLE
Feature request: "lock(this)" should also be reported as bad practice

### ISSUE THREAD

**Issue by alaendle** [dotnet/roslyn-analyzers#294]
Maybe it could be added to CA2002 as discussed long time ago (see attached link)?
I think the reasons why this is bad are obvious - see also http://blogs.msdn.com/b/springboard/archive/2008/07/30/lock-this-bad-locking-patterns.aspx.

https://social.msdn.microsoft.com/Forums/en-US/42d85262-0611-4a81-be2d-e76b66734e92/lockthissynclock-me-and-fxcopca?forum=vstscode

**Comment by adraut** [comment]
Looks like this already implemented.  https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotLockOnObjectsWithWeakIdentity.cs

**Comment by alaendle** [comment]
Please excuse the late response, but I've tested v2.9.4 of the analyser suite - and this is definitely not implemented; so please reopen.

**Comment by KalleOlaviNiemitalo** [comment]
Microsoft has archived the blog to <https://docs.microsoft.com/archive/blogs/msdn/springboard/lockthis-bad-locking-patterns>.
