### ISSUE TITLE
Ban the use of Compilation.GetTypeByMetadataName

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#2953]
We need to enable BannedApiAnalyzers on this repository, and ban the use of Compilation.GetTypeByMetadataName. Existing uses have already been updated, but we don't want more to slip in with future pull requests.

**Comment by sharwell** [comment]
@drewnoakes can you help is get this implemented?

**Comment by drewnoakes** [comment]
Sure, please review PR #2962.

**Comment by sharwell** [comment]
@drewnoakes Thank you so much!!
