### ISSUE TITLE
CA1710 triggers on IReadOnlyDictionary<> to add "Collection"

### ISSUE THREAD

**Issue by RobinHood70** [dotnet/roslyn-analyzers#2955]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.6 (Latest)

#### Diagnostic ID

[CA1710](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca1710)

#### Repro steps

1. Create a class which implements IReadOnlyDictionary<TKey, TValue>.
2. Refresh analyzer warnings, if necessary, and examine them.

#### Expected behavior
CA1710 should either not trigger, or trigger asking for the name to end with "Dictionary", depending on the class name.

#### Actual behavior
CA1710 triggers asking to rename the class to end with "Collection".

**Comment by RobinHood70** [comment]
This may be a regression of some kind, because I know this was an issue in the distant past (possibly pre-Roslyn), then it was fixed. Now, it seems to be triggering again.

**Comment by RobinHood70** [comment]
While it's a bit of an edge case, if the rule doesn't already do so, it should check for conflicting naming recommendations and either not trigger, or allow either possibility. Take, for example, this class declaration:

`public class ReadOnlyKeyedCollection<TKey, TItem> : IReadOnlyDictionary<TKey, TItem>, IReadOnlyList<TItem>`

**Comment by Evangelink** [comment]
@mavasani In the light of your last comment on #3065 I think this issue shall be addressed and I think we could also handle `IImmutableDictionary`, WDYT?

**Comment by Evangelink** [comment]
Actually there is no need for `IImmutableDictionary` once we have `IReadonlyDictionary`.
