### ISSUE TITLE
CA1721: Don't warn if either property or method is obsolete, or both are

### ISSUE THREAD

**Issue by peteroupc** [dotnet/roslyn-analyzers#2956]
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers), version 2.9.6.

CA1721 should not apply to a member/property pair if either or both of them have the ObsoleteAttribute.  The presence of this attribute already indicates that use of a member is discouraged.  Notably, if _either_ the property or the member has the ObsoleteAttribute, it usually means that its use is discouraged and the other is preferred.

The following illustrates this:

```
[Obsolete("Use GetPropertyValue instead.")]
public int PropertyValue { get; }

public int GetPropertyValue() {
   // Exception thrown for illustration; the real
   // version would have non-trivial code.
   throw new NotImplementedException();
}
```

(In cases like this, `PropertyValue` came first, then `GetPropertyValue` was added later with the same implementation, usually because the implementation of `PropertyValue` was not trivial enough for a property, then `PropertyValue` was deprecated.)

Currently, code like the one above triggers CA1721 when it shouldn't.

**Comment by Evangelink** [comment]
@mavasani I can handle this ticket if it also makes sense to you.

**Comment by mavasani** [comment]
Sounds reasonable to me!
