### ISSUE TITLE
Incorrect concatenation of fragmented strings

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#2976]
There is an issue similar to https://github.com/dotnet/roslyn/issues/39411 on `DeclarePublicApiFix.cs` on the line 273 ` title = string.Format(CultureInfo.InvariantCulture, titleFormat, "document", fixAllContext.Document.Name);`.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn-analyzers/pull/2960/files#r338674918_

**Comment by Evangelink** [comment]
@sharwell I was having a look at this issue and I couldn't really see the link with the Roslyn issue referenced. The only "problem" I can see is that the fix title isn't translated:
https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs#L261-L302

Am I missing something?

**Comment by sharwell** [comment]
There should be three different title strings, each of which is placed in the resources file for translation:

1. `Add all items in document '{0}' to the public API`
1. `Add all items in project '{0}' to the public API`
1. `Add all items in the solution to the public API`

The resource string should be used as appropriate in each case.
