### ISSUE TITLE
CA1308 has surprising advice here

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#2984]
```cs
private static string M(bool b, string s) => b ? s.ToLowerInvariant() : s.ToUpperInvariant();
```

**Comment by StingyJack** [comment]
Why make people do so much work just to understand your point?

Try to explain the advice it gives that you find surprising, and why it is surprising to you.

**Comment by JohanLarsson** [comment]
@StingyJack good feedback, I'll try to improve. Closing this and writing a better issue when I see it next time. Just did a dump when I saw `CA1308` where I did not expect it, could not afford much context switch.
