### ISSUE TITLE
Use parameterized perma links for diagnostic help links

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn-analyzers#2991]
Analyzers currently use hard-coded URLs for help links:
https://github.com/dotnet/roslyn-analyzers/blob/7ad9f725f22c7f5a9e8f70a5ebe6e5fd4c14d8d6/src/Microsoft.NetCore.Analyzers/Core/Runtime/CallGCSuppressFinalizeCorrectly.cs#L36

We should
1)	Create perma link for each analyzer we own parameterized with diagnostic id (`https://docs.microsoft.com/visualstudio/code-quality/` with diagnostic ID as a parameter).
2)	Update our analyzers to use that link instead of hardcoded URL.
3)	Recommend customers to either use URLs to github repos that they control (assuming github will stay around), or some service that provides perma links.

**Comment by mavasani** [comment]
This is now implemented in the repo for all CA rules. Each rule is required to call the below helper to create DiagnosticDescriptors (enforced with BannedApiAnalyzer), which auto-generates the help link based on the ID: https://github.com/dotnet/roslyn-analyzers/blob/998a93ee83ce253cb307880c5d4b37048e4a4483/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L14-L45
