### ISSUE TITLE
Link in BinaryFormatter analyzer is broken

### ISSUE THREAD

**Issue by JesperTreetop** [dotnet/roslyn-analyzers#3003]
The help link [in the BinaryFormatter analyzer](https://github.com/dotnet/roslyn-analyzers/blob/c9d6579f31fd4ad45f3d23187189657343b395a4/src/Microsoft.NetCore.Analyzers/Core/Security/DoNotUseInsecureDeserializerBinaryFormatterMethods.cs#L25) - `https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2300-do-not-use-insecure-deserializer-binaryformatter` is broken. It lands on a 404 page with suggestions, one of which (for me) is the right link. This is likely the case for many other similar links. Ideally the team in charge of maintaining the documents [should make the previous URL keep working by redirecting](https://www.w3.org/Provider/Style/URI).

**Comment by dotpaul** [comment]
Thanks for reporting @JesperTreetop ! It looks like @eddynaka already fixed this. Please let us know if you come across any other broken links.
