### ISSUE TITLE
CA1054 reports that I should use a Uri type, even though the parameter is clearly named with "Url"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#3009]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/804594/ca1054-reports-that-i-should-use-a-uri-type-even-t.html)._

---
URI and URL are not interchangeable things.

This is happening after I added the new FxCop roslyn analyzer package to a project. I have to either configure a bunch of suppressions or disable the CA rule. Neither are optimal.

---
#### Visual Studio Feedback System on 11/3/2019, 10:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/4/2019, 08:58 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by StingyJack** [comment]
@vatsalyaagrawal  the OP needs a different closure status like "closed - transferred"

**Comment by Evangelink** [comment]
Hi @StingyJack, I am not sure to really understand the problem you are facing. Would you mind giving us a little more context and explanations?

**Comment by StingyJack** [comment]
@Evangelink there were screenshot attached to the original report. I think I had a function param called `baseURL` that this was complaining about. 

I didn't have any "Uri' names

**Comment by Evangelink** [comment]
Quoting the doc (maybe it wasn't the same when you have opened the ticket)

> A type declares a method with a string parameter whose name contains "uri", "Uri", "urn", "Urn", "url", or "Url" and the type does not declare a corresponding overload that takes a `System.Uri` parameter.

So it does seem correct to me.

**Comment by StingyJack** [comment]
I went looking in the code a while back and found it's including URL. The message makes no mention of that though.

**Comment by Evangelink** [comment]
The latest message and descriptions looks to me:

- message: `Change the type of parameter {0} of method {1} from string to System.Uri, or provide an overload to {1} that allows {0} to be passed as a System.Uri object.`

- description: `If a method takes a string representation of a URI, a corresponding overload should be provided that takes an instance of the URI class, which provides these services in a safe and secure manner.`

The title and analyzer class name might be updated to something more generic to avoid confusion for end-users. Although I am not sure how this could be done. Maybe `URI-like parameters should not be strings`?

@mavasani WDYT?

**Comment by StingyJack** [comment]
My parameter is named `someUrl`, not `someUri`. I shouldn't get a warning for u.r.-eye when I'm using a u.r.-elle.

**Comment by Evangelink** [comment]
If you look at the definitions you will see that both `URL` and `URN` are specific cases of `URI` so for me everything's alright.

**Comment by StingyJack** [comment]
I like your suggestion of "Uri-like", but that still doesnt resolve the problem that the rule complains about a thing, but does not require that thing be fixed. It only requires that I provide an additional alternate implementation that takes a different type. I guess thats technically a different issue. I just hadnt read that far into the error message when I logged this.

**Comment by Evangelink** [comment]
If you do add an overload with a `Uri` parameter then the rule [CA2234](https://docs.microsoft.com/visualstudio/code-quality/ca2234?view=vs-2019) will kick-in and suggest that you use it instead of the string overload. Of course, you will have to ensure the rule is enabled on your solution/project.

Let me know if I still haven't got the full extent of your comments.

**Comment by StingyJack** [comment]
I think you get it.

**Comment by Evangelink** [comment]
@mavasani let me know if you are ok with the change and I will submit a PR.
