### ISSUE TITLE
UseNameofInPlaceOfString: Add coverage for early return

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3023]
📝 We should make sure this early return line of the analyzer is still covered by tests:

https://github.com/dotnet/roslyn-analyzers/blob/1fa5f5c1167500b93bbebc301f240edde60effce/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/UseNameofInPlaceOfString.cs#L64-L67

_Originally posted by @sharwell in https://github.com/dotnet/roslyn-analyzers/pull/3005_

**Comment by Evangelink** [comment]
@sharwell FYI I spend some time yesterday night trying to find a way to enter this condition but because of the previous early return conditions and the fact that the operation action isn't called back when the method signature is invalid, I couldn't find anyway to create a case that would enter this branch. You might have better ideas than me so feel free to have a look when you have some spare time.

In case you cannot find a way to enter this branch, do you think that it should be removed? I am always unsure when writing analyzer because somehow having the analyzer crashing would be nice as it would indicates that something changed (or there was actually a scenario to get there) and so the code/test could be improved. And at the same time, that's always a bad user experience to have AD0001 warnings.

**Comment by Evangelink** [comment]
Relates to #3115

**Comment by Evangelink** [comment]
@mavasani I think this shall be marked as blocked until the we have the nullability annotation from roslyn. Based on the discussions it is quite likely that this cannot be null and so the only job here would be to remove the if condition.

**Comment by Youssef1313** [comment]
@Evangelink It can be null in the rare case of using `__arglist`. This is covered in the following IOperation test in roslyn.

https://github.com/dotnet/roslyn/blob/0902d19aaba441d98fe5432274e5a2554353cc8d/src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs#L1409

**Comment by Youssef1313** [comment]
The condition is still unreachable. The argument type will never be of `SpecialType.System_String` if it's an `__arglist`. It looks okay to  remove the check.
