### ISSUE TITLE
Code analysis misdetects IReadOnlyDictionary as collection for CA1710/CA1711

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#303]
Ported from https://github.com/dotnet/roslyn/issues/4133

We need to ensure that our analyzer implementation for CA1710/CA1711 accounts for IReadOnlyDictionary as a valid dictionary base type.

**Comment by lgolding** [comment]
This is a bug in the FxCop implementation which we must take care to fix when we write the Roslyn implementation.

**Comment by RobinHood70** [comment]
Unless I'm missing something somewhere, this issue still occurs, both in VS 2015/C# 6 and VS 2017/C# 7.
