### ISSUE TITLE
Azure ARM sourcecontrol step fails to load analyzers

### ISSUE THREAD

**Issue by LiquidPT** [dotnet/roslyn-analyzers#3056]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

I've tried all of these with the same result:
v2.9.7 (Latest)
v2.9.0
v2.6.4

#### Diagnostic ID

[CS8032] An instance of analyzer Microsoft.NetCore.Analyzers.Runtime.SpecifyCultureInfoAnalyzer cannot be created from D:\home\.nuget\microsoft.netcore.analyzers\2.9.0\analyzers\dotnet\cs\Microsoft.NetCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

#### Repro steps

1. Follow the [instructions](https://github.com/microsoft/iomt-fhir/blob/master/docs/ARMInstallation.md) here to deploy to Azure using the ARM template: 
2. Use the "personal/liquidpt/code-analysis" branch (it has added the code analysis reference back to the projects)
3. Pray that the source control step actually works

#### Expected behavior
Source is deployed to the Azure app functions

#### Actual behavior
Source deploy fails with a list of errors similar to:

CSC : error CS8032: An instance of analyzer Microsoft.NetCore.Analyzers.Security.DoNotUseInsecureDeserializerNetDataContractSerializerMethods cannot be created from D:\home\.nuget\microsoft.netcore.analyzers\2.9.0\analyzers\dotnet\cs\Microsoft.NetCore.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by mavasani** [comment]
Closing based on the offline thread where this was resolved.
