### ISSUE TITLE
Change the behavior of CA1710

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3065]
Currently the rule [CA1710](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1710) will look at all base types and interfaces and might suggest a suffix based on an hard-coded dictionary mapping some base types to some suffix.

I would like to suggest a new behavior for this rule. I think the rule should look only at the base type or the interfaces declared (if no base type) and not look at a higher level. IMO there is no point going up in the hierarchy because each level is doing a specialization and is the only one that shall be respected. For example, in this case `public class MyDbReader : IDataReader`, it seems rather bad to suggest to the user to suffix the class with `Collection` (because `IDataReader` implements `IEnumerable`) or in this case `public class MyReadOnlyDictionary<TKey, TValue> : IReadOnlyDictionary<TKey, TValue>` to suggest `Collection`. This change won't prevent having some hard-coded mapping for the suffix but would solve some inconsistencies induced by the current implementation.

If we need to keep the compatibility with the current behavior for some users, we could add some configuration to let the user select the mode he wants.

In addition to the previous change, I'd like to suggest (maybe again through some configuration) an extension to this rule to not only suggest a prefix based on the hard-coded list but on the base type or first interface to enforce some specialization. For example, `public class MyReader : DbDataReader` would raise an issue suggesting the name to end with `DbDataReader`, `public class C : IDictionary, IEnumerable, IFoo` would suggest the class name to end with `Dictionary` (first interface).

WDYT?

Relates to/overrules issues #2955 and #1818.

**Comment by mavasani** [comment]
@Evangelink Sounds reasonable to me to make this rule configurable.

**Comment by Evangelink** [comment]
@mavasani Sorry for the double work but can you let me know which points you agree with?

1. Only look at first level and not higher levels

2. Add an option to keep current behavior (is it required?)

3. Add an option to let user specify extra types for which the rule will report

4. Add an option to always report based on first base class or interface. This could be quite noisy for types implementing `ICloneable`, `IEquatable`, `IComparable`... Maybe those shall be excluded when the new option is selected.

**Comment by mavasani** [comment]
@Evangelink I think we should start with the following:

1. Do not change anything in the default behavior of the rule.
2. Add an editorconfig option to list the names of the named types and corresponding required suffix, such that types deriving or implementing it need to have that suffix.
3. Potentially add another editorconfig option to prevent walking more then one level down the base type and interface chain when suggesting suffixes.

**Comment by Evangelink** [comment]
@mavasani Any preferences for the syntax of the option list for point 2?

**Comment by mavasani** [comment]
Added a comment on your PR. I think we should use the existing format: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-type-names-with-derived-types

**Comment by Bouke** [comment]
I think it would be good to document this breaking change in the release notes for v3. I was taken by surprise and it took me a while to find this change.

**Comment by Evangelink** [comment]
@Bouke That's a good remark! Sorry for the trouble! I did said so in the PR turning the option on by default but forgot to update the doc. https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/issues/77
