### ISSUE TITLE
Uninstalling does not remove dependencies

### ISSUE THREAD

**Issue by IrisClasson** [dotnet/roslyn-analyzers#3066]
Apologies if this is the wrong repo, or if this is expected behavior when uninstalling this package. We installed the wrong version of the package in our system, and after uninstalling weren't able to install an older version. Uninstall left behind a package that checks the version (Microsoft.CodeAnalysis.VersionCheckAnalyzer). 

#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 

#### Diagnostic ID

N/A

#### Repro steps

1. Install version 2.9.8
2. Uninstall
3. Install 2.9.0

#### Expected behavior

2.9.8 packages uninstalled
2.9.0 installed

#### Actual behavior
Error message when trying to install older version:

Unable to resolve dependencies. 'Microsoft.CodeAnalysis.VersionCheckAnalyzer 2.9.8' is not compatible with 'Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.0 constraint: Microsoft.CodeAnalysis.VersionCheckAnalyzer (= 2.9.0)'.

**Comment by mavasani** [comment]
I am unable to repro this on latest VS2019 16.5 preview drop. Kindly re-open if you are still hitting this.

**Comment by natilivni** [comment]
This happens to me as well. how do I remove the dependencies manually?
