### ISSUE TITLE
Re-enable nullable warning CS8717

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3070]
This issue tracks reverting https://github.com/dotnet/roslyn-analyzers/pull/3061/commits/ab6cb9bbbc86d1d6a503fcafc3e565b85eef2571 once we can move the following to version 3.5.0 or greater: https://github.com/dotnet/roslyn-analyzers/blob/ea44ea568c0d5e9cfa9ed7e687836b9882ac184b/eng/Versions.props#L24

**Comment by Evangelink** [comment]
@mavasani Is there anything prevent to bump version to `3.5.0-beta3-final`?

**Comment by mavasani** [comment]
Nope, go for it and make sure to remove any `CS8717` suppressions in the repo.

**Comment by sharwell** [comment]
@Evangelink When I tried updating to 3.5.0-beta2-final in #3291, the CI failed. I'm hoping you have more luck!

**Comment by Evangelink** [comment]
I am not lucky :)

It seems that the version of MSBuild / Visual Studio on the CI agent is not recent enough (should be 16.3+). I think someone at Microsoft will have to update the agent(s), it doesn't seem to be something on the build scripts.
