### ISSUE TITLE
Analyzer CA1710 Feature request: Set custom suffix

### ISSUE THREAD

**Issue by SirIntellegence** [dotnet/roslyn-analyzers#3072]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.7 (Latest)

#### Diagnostic ID
CA1710 // Identifiers should have correct suffix

#### Repro steps
I think it would be nice if we could add out own suggested suffix for classes that extend a class. For example, I have a class I call `AbstractCharSequence` (that implements IEnumerable), and I want to be able to possibly attach an attribute to it that would suggest that sub-classes should have the suffix of "CharSequence" instead of Collection. Is that a possible feature to add?

**Comment by mavasani** [comment]
Agreed, this seems like a reasonable configuration request. Tagging @Evangelink in case you are interested.

**Comment by Evangelink** [comment]
Relates to #3065

**Comment by Evangelink** [comment]
Fixed by #3148 

(@mavasani this ticket can be closed)
