### ISSUE TITLE
Feature Request: IDE0067/CA2000 - Exclude only certain types

### ISSUE THREAD

**Issue by CortiWins** [dotnet/roslyn-analyzers#3085]
I think both IDE0067 and CA2000 are too valuable to turn off.

However, sometimes types that don't really have unmanaged ressources implement IDisposable for whatever reasons. I cant change those classes, they are part of a library. I can exclude them but manually setting pragmas around hundreds and more cases is really detrimental to the readability of the code.

**My wish:**
Being able to configure IDE0067 and CA2000 to exclude types, like they exclude Task.

PS:
The type in question is HalconDotNet.HTuple. Pretty niche, i know.

**Comment by mavasani** [comment]
I think we should extend https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-symbol-names to even skip flagging excluded symbols.

**Comment by mavasani** [comment]
Tagging @Evangelink in case you are interested in picking up this feature request.

**Comment by Evangelink** [comment]
@mavasani `IDE0067` is not available in this repository. Regarding `CA2000` the option is already available
https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/Runtime/DisposeObjectsBeforeLosingScope.cs#L90

I think the ticket can be closed (or moved to Roslyn for `IDE0067`).

**Comment by mavasani** [comment]
@Evangelink Existing check in dispose rule checks `containingMethod.IsConfiguredToSkipAnalysis`, but the request here is to be able to skip dispose violations on instantiation of specific disposable types.

**Comment by Evangelink** [comment]
Do you think that I should keep the disposable helper as-is and only post-filter calls? Also the option syntax allows to exclude methods signature, does this mean that types  returned by those calls shall be considered safe?

**Comment by mavasani** [comment]
Let us start only by considering the type itself as non-disposable, not the return values of methods within that type. I think it would be fine to just change DisposeAnalysisHelper to consider such types as non-disposable so that all dispose analysis rules ignore such types.

**Comment by mavasani** [comment]
This should now be configurable with the following .editorconfig option: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-symbol-names

Thanks @Evangelink
