### ISSUE TITLE
Remove class DiagnosticAnalyzerTestBase

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3089]
As a follow-up action of #3052 and #3057 we could get rid of the `DiagnosticAnalyzerTestBase` class.

**Comment by mavasani** [comment]
@Evangelink This would be really good to take up once https://github.com/dotnet/roslyn-analyzers/pull/3052 is merged. New PRs still seem to be adding tests based on this base class.
