### ISSUE TITLE
System.Runtime.Analyzers nuget package contains unsigned binaries

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-analyzers#309]
System.Runtime.Analyzers (1.1.0-beta1-20150812-01) contains delay/test signed binaries.

**Comment by tmeschter** [comment]
@tannergooding That builds predates at least some of the work needed to setup signing in this repo (e.g., commit 025982832969c89db9459abfde3b7463f73a4763 went in on August 12th, and 058df6d8fa2474ed1caed2aa1d08a286abca8ac3 and 75bcc0fed721169ee9baa2680d3615678eaa6c54 went in the next day).

Could you try a later build?

**Comment by tannergooding** [comment]
@tmeschter, the build in question is published to the public NuGet feed (https://www.nuget.org/packages/System.Runtime.Analyzers/1.1.0-beta1-20150812-01).

**Comment by tmeschter** [comment]
@tannergooding And there's nothing we can do about that one, except replace it with something that *has* been signed. My point being that this issue has probably been fixed.

**Comment by lgolding** [comment]
The version mentioned above is the latest one on NuGet.org. We need to verify that new builds are signed, and get a later build up on NuGet.org.

**Comment by srivatsn** [comment]
This has been verified and we've uploaded 1.1
