### ISSUE TITLE
Multiple issues with CA2213: Disposable fields should be disposed

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-analyzers#310]
**Issue 1:** CA2213 is recommended for a static member, which requires special consideration for disposal as it is not necessarily locked to a specific objects lifetime (in the example code below, the instance is tied to the lifetime of an object, if we are disposing of that object in particular).

**Issue 2:** CA2213 persist even after applying the quick fix

**Issue 3:** CA2213 recommends `type.Dispose()` rather than `type?.Dispose()` (which can potentially break for instances of a reference type if it is `null`)

**Issue 4:** CA2213 recommends the quick fix be applied to the public Dispose method, even when implanting the standard Dispose pattern: `protected virtual void Dispose(bool disposing)` (which can potentially break code that requires different disposal for interop code)

**Issue 5:** CA2213 has no concept of a 'thread-safe' dispose model, which is actually simple in most cases: `var foo = System.Threading.Interlocked.Exchange(ref _foo, null); foo?.Dispose()`.

**Example Code:**
```
using System;
using System.Threading;

class Application : IDisposable
{
    private static Application _current;

	public static Application Current
	{
	    get
	    {
		    return _current;
	    }
	}
	
	public Application()
	{
	   if (Interlocked.CompareExchange(ref _current, this, null) != null)
	   {
	       throw new InvalidOperationException("Only a single application may exist per System.AppDomain.");
	   }
	}
	
	~Application()
	{
	    Dispose(false);
	}
	
	protected virtual void Dispose(bool disposing)
	{
	    var current = Interlocked.CompareExchange(ref _current, null, this);
		current?.Dispose();
	}
	
    public void Dispose()
	{
	    Dispose(true);
		GC.SuppresFinalize(this);
	}
}
```

**Comment by tmeschter** [comment]
@tannergooding Since these are largely unrelated issues, could you split them out?

**Comment by srivatsn** [comment]
We've decided to cut CA2213 given it's very high noise to signal ratio (https://github.com/dotnet/roslyn-analyzers/issues/695)
