### ISSUE TITLE
DiagnosticCategoryAndIdRanges - Rule CA2210

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3101]
In [DiagnosticCategoryAndIdRanges.txt](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt#L6) line 6 it is written that `Design` rules should have an ID between `CA1000` and `CA1099` and on line 11 that `Usage` rules have IDs between `CA2200` and `CA2299`.

I have seen in #532 that the rule won't be ported to the analyzer but as the ID is reserved (was used), I think it would be better to update the text file to add the special ID on line 6 and remove it from line 11.

WDYT?

**Comment by mavasani** [comment]
Sounds reasonable.
