### ISSUE TITLE
'ImplementSerializationConstructorsFixer' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by Danghor** [dotnet/roslyn-analyzers#3103]
**Version Used**: 
Microsoft.NetCore.Analyzers 2.9.8

**Steps to Reproduce**:

1. Create a class with the following content:
 ```csharp
using System;

namespace Analyzer
{
    [Serializable]
    public class CalculateCodeRefactoringException : Exception
    {
        public CalculateCodeRefactoringException() { }

        public CalculateCodeRefactoringException(string message) : base(message) { }

        public CalculateCodeRefactoringException(string message, Exception innerException) : base(message, innerException) { }
    }
}
```
2. (CA2229 Diagnostic is shown)
3. `CalculateCodeRefactoringException` is squiggled. Hover over the class name, click on the little arrow next to the light bulb that appears and hover over the proposed code fix "Implement Serialization constructor"

**Expected Behavior**:
The proposed code fix is shown and no exception occurs.

**Actual Behavior**:
The proposed code fix is shown, but an exeption occurs and an error message is displayed at the top of Visual Studio.

`Sequence contains more than one element`

```
System.InvalidOperationException : Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at async Microsoft.NetCore.Analyzers.Runtime.ImplementSerializationConstructorsFixer.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by mavasani** [comment]
I believe this was already fixed with https://github.com/dotnet/roslyn-analyzers/commit/0d39c49f914be2985f4b41291b18f6601c0f19ea#diff-241870104e1dc0695bc9312b6635066d. Do you happen to also have the [VS2019 Code Analysis VSIX](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2019) installed by any change?

**Comment by Danghor** [comment]
Yes, I do have that installed. I'm going to test whether that triggers the error.

**Comment by Danghor** [comment]
No error message shown with Microsoft Code Analysis 2019 Version 3.0.0.1925803.
Seems to be fixed.
