### ISSUE TITLE
False positive for CA1806

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#3104]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/823030/false-positive-for-ca1806.html)._

---
Error being displayed on the `WriteToDmm` method call which is marked `void`:

```
        [Pure]
        private string QueryForDmmModel()
        {
            WriteToDmm("*IDN?");  // CA1806
            string data = ReadStringFromDmm();
            string model = data. Split(',')[1];

return $"HP {model}";
        }

[Pure]
       private void WriteToDmm(string cardCommand) => m_hpDmm.Write(cardCommand);
```

---
#### Visual Studio Feedback System on 11/17/2019, 07:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 11/18/2019, 07:28 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Seems like we need to tweak this: https://github.com/dotnet/roslyn-analyzers/blob/6d265703c1ccd10176dc77e768412cf1422f9153/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/DoNotIgnoreMethodResults.cs#L204

**Comment by mavasani** [comment]
Tagging @Evangelink

**Comment by Evangelink** [comment]
@mavasani I cannot reproduce the issue using the following test code:

```csharp
using System.Diagnostics.Contracts;

public class A
{
    public int Write(string s) => 42;
}

public class B
{
    [Pure]
    private void WriteToDmm(string s) => new A().Write(s);
}
```

**Comment by mavasani** [comment]
@Evangelink CA1806 is reported at the callsite of `WriteToDmm`. You need to add one to your test case.

**Comment by Evangelink** [comment]
I am stupid v.v

**Comment by drewnoakes** [comment]
Does it make sense to allow `[Pure]` on a `void`-returning method? I don't think it does. Perhaps a new analyzer for this would help.

**Comment by Evangelink** [comment]
@drewnoakes Looking at the description of the [attribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute?view=netframework-4.8)

> Indicates that a type or method is pure, that is, it does not make any visible state changes.

That seems ok for me to mark a `void` method as `Pure` as it indicates that the method won't change any of the visible state.
