### ISSUE TITLE
Reimplement VB fixer for CA1052

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#311]
Ported from https://github.com/dotnet/roslyn/issues/3546

---

The existing VB fixer (which is at the moment disabled) marks a static holder class as NotInheritable. We need to think some more about whether this is the right fix, and then re-enable it.

**Comment by mavasani** [comment]
Closing feature requests with no customer feedback..

**Comment by Youssef1313** [comment]
@mavasani This issue was tracking a disabled fixer. Consider re-opening.

https://github.com/dotnet/roslyn-analyzers/blob/b148fa89c974a72c28184931767835709f34d1fa/src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicStaticHolderTypes.Fixer.vb#L22-L28
