### ISSUE TITLE
Add code analyzer to VSIX project

### ISSUE THREAD

**Issue by xp-development** [dotnet/roslyn-analyzers#3112]
I have created a VSIX project with a tool window. Now I want to show some information during developing of the current code in this tool window. I want to analyze the source code with a roslyn code analyzer and show the data in my window (publish subscribe pattern).
I wrote a roslyn code analyzer and I wrote a tool window, but it is not possible for me to put it both in **one** VSIX project and start debugging.

How can I integrate the code analyzer to my VSIX project?

**Comment by mavasani** [comment]
I don't believe this scenario is supported via analyzers, which are only meant to analyze source trees and compilations and report diagnostics. I believe your request would be similar to https://github.com/dotnet/roslyn/issues/19 - workspace or VS public API to analyze documents/projects/solutions with incremental analysis.
