### ISSUE TITLE
Meta analyzer to flag use of Compilation.GetSemanticModel inside diagnostic analyzers

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3114]
We have seen tons of performance issues in sub-optimally written analyzers that end up creating completely new semantic models by invoking `Compilation.GetSemanticModel`. This leads the compiler to rebind the entire file, and doing it multiple times (say with SyntaxNode callbacks) can be a performance hog. For example, https://github.com/dotnet/roslyn-analyzers/issues/2576 identified this can lead a 4x-5x slowdown. With nullability flow analysis in place inside the compiler, this can be even worse.

We should write an analyzer that flags use of this API inside a diagnostic analyzer. Implementation of this analyzer should potentially be a sub-type of [DiagnosticAnalyzerCorrectnessAnalyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticAnalyzerCorrectnessAnalyzer.cs).

**Comment by mavasani** [comment]
Tagging @Evangelink

**Comment by kzu** [comment]
So, what is the replacement for an analyzer that actually does need to access symbol info to report accurate diagnostic?

**Comment by mavasani** [comment]
Diagnostic description in error list, when expanded, should give the info:
https://github.com/dotnet/roslyn-analyzers/blob/8bc7b0bf842d3fee3ee8595e783828f8c4ee448e/src/Microsoft.CodeAnalysis.Analyzers/Core/CodeAnalysisDiagnosticsResources.resx#L395

**Comment by mavasani** [comment]
In general, it is always better performance wise to switch to RegisterOperationAction for semantic analysis of executable code and RegisterSymbolAction for semantic analysis of symbols and non-executable parts of the code.

**Comment by kzu** [comment]
Got it. Thanks!
