### ISSUE TITLE
Remove all DiagnosticResult.CompilerError(...).WithMessage(enuMessageString)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3116]
It seems quite a few tests have been recently edited to use ENU message strings for expected compiler diagnostics. This prevents running these tests on different locales. This issue tracks removing all such ENU message strings in expected diagnostics.

**Comment by sharwell** [comment]
We should just run these tests with the culture set to en-US, similar to how the compiler tests run.

**Comment by mavasani** [comment]
Those compiler tests *really* need en-US locale for validation. I don't see any need to validate compiler diagnostic messages in our repo.

**Comment by Evangelink** [comment]
@mavasani This can be closed.
