### ISSUE TITLE
Public API needs to handle duplicate entries

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn-analyzers#312]
Duplicate entries in the shipped / unshipped file cause the public analyzer to throw in the constructor.  This exception is unhandled and will cause the compiler to ignore the analyzer going forward.  This is 100% silent.  

The exception should be handled and result in an error being emitted.

**Comment by tmeschter** [comment]
The exception occurs in this constructor, which is called by the compilation start action:
https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn/Core/ApiDesign/DeclarePublicAPIAnalyzer.Impl.cs#L70
