### ISSUE TITLE
CA1707 should not trigger on MSFT required naming conventions

### ISSUE THREAD

**Issue by StingyJack** [dotnet/roslyn-analyzers#3121]
...like all the methods that would be in a Global.asax. Changing the names would break functionality, and we shouldn't have to suppress them all the time. I don't have a computer handy at the moment, but I imagine win/web form control event handlers like `btnOk_Click` would be triggering this as well.

Analyzers that complain about these default or required conventions feel unfinished and are more likely to be uninstalled or deactivated as fast as they were installed.

**Comment by Evangelink** [comment]
If the event handler is private it shouldn't be much of a problem to rename `btnOk_Click` to something like `OnButtonOkClicked`.

**Comment by StingyJack** [comment]
You cant do that with something like [Application_Start() or Application_Error()](https://docs.microsoft.com/en-us/previous-versions/ms178473%28v%3dvs.140%29#life-cycle-events-and-the-globalasax-file) though

**Comment by Evangelink** [comment]
@StingyJack Yep you are totally right for web methods. I don't recall the name but there were special method names for UWP and WPF.

@mavasani Is it ok for you if we fix this?

**Comment by mavasani** [comment]
Yes, sounds reasonable to add exclusions.

**Comment by Evangelink** [comment]
On the second thought, in addition to the global.asax convention based methods, I am wondering if it wouldn't be a good idea to add an editorconfig option to prevent raising on event handler methods. I am not a big fan of event handler methods having underscore in their names but I have seen a _LOT_ of companies using this convention. WDYT?

**Comment by StingyJack** [comment]
I think if you go that route then unit tests need to be considered also.

**Comment by Evangelink** [comment]
Good point!

**Comment by StingyJack** [comment]
@mavasani why did you close this?

**Comment by 333fred** [comment]
Because he merged a pr that fixed it. https://github.com/dotnet/roslyn-analyzers/pull/3156

**Comment by Evangelink** [comment]
And regarding the events and tests, it was decided not to do anything at the moment (see https://github.com/dotnet/roslyn-analyzers/pull/3156#issuecomment-571616975)
