### ISSUE TITLE
Undetected CS0266 in foreach loop

### ISSUE THREAD

**Issue by k1ll3r8e** [dotnet/roslyn-analyzers#3129]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

Example: [CS0266](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0266)

#### Repro steps

1. Using .Net Framework 4.6
2. Create a abstract base class.
3. Derive from it and cast the derived type back to the base type.
4. Use a wrong/not implemented interface in the foreach clause.

---
    public override bool CopyTo(string destination, FileTransferEventHandler transferEventHandler, CancellationToken cancellationToken)
    {
        if (string.IsNullOrEmpty(destination)) throw ExFactory.ArgumentNullOrEmpty(nameof(destination), typeof(string));

        TransferMessage msg = new TransferMessage(TransferMode.Copy, Client.ID, FullName, destination, TransferState.Pending);
        transferEventHandler?.Invoke(Client.ID, new FileTransferEventArgs(Client.ID, msg));
        if (Exists)
        {
            ADirectoryInfo dest = new ADirectoryInfo(Client, destination);
            if (!dest.Exists)
            {
                dest.Create(true);
                dest.Refresh();
            }
            if (dest.Exists)
            {
                //
                // Here should the CS0266 raised.
                //
                foreach (IFileSystemCache fsi in GetItems(cancellationToken))
                {
                    //...
                }
                msg.UpdateState(TransferState.Done);
                transferEventHandler?.Invoke(Client.ID, new FileTransferEventArgs(Client.ID, msg));
                return true;
            }
        }
        msg.UpdateState(TransferState.Error);
        transferEventHandler?.Invoke(Client.ID, new FileTransferEventArgs(Client.ID, msg));
        return false;
    }
---

Here are the signatures:
---
    public abstract class AFileSystemInfo
    {
        //...
    }

    public IEnumerable<AFileSystemInfo> GetItems(CancellationToken cancellationToken)
    {
        //...
    }

    public class FileSystemCache : IFileSystemCache
    {
        //...
    }

    public interface IFileSystemCache : ISerializable
    {
        //...
    }
---

#### Expected behavior

The CS0266 should be detected. This could lead to enormous problems if you have a really big project where you change for example, some internal logic's from an interface to an abstract base class.

#### Actual behavior

The CS0266 is currently not detected. Even the compiler doesn't throw an error... The project compiles fine and crashes at run time. (Found this during refactoring of some base classes.)

**Comment by mavasani** [comment]
This seems to be a request for enhancing the compiler diagnostic. Kindly report this on https://github.com/dotnet/roslyn
