### ISSUE TITLE
Analyzer for repeated enumeration

### ISSUE THREAD

**Issue by vatsalyaagrawal** [dotnet/roslyn-analyzers#3133]
Identify cases where an IEnumerable is iterated   over multiple times.

**Comment by drewnoakes** [comment]
A challenging case for this analyzer:

```c#
public int M(IEnumerable<int> e)
{
    Requires.NotNull(e, nameof(e));

    return e.First();
}
```

How can you know that `Requires.NotNull` doesn't enumerate the object yet `Enumerable.First` does?

**Comment by mavasani** [comment]
@genlu In case you are interested in writing a new dataflow based analyzer.

**Comment by vatsalyaagrawal** [comment]
Duplicate #3946
