### ISSUE TITLE
In web api, if I call a post or put method inside a get method, it should give an error or warning

### ISSUE THREAD

**Issue by vibhu12345** [dotnet/roslyn-analyzers#3144]

**Comment by carlossanlop** [comment]
Can you please add a more detailed description?

We need usage examples of the APIs that would be affected by this rule.

**Comment by Youssef1313** [comment]
dotnet/aspnetcore maintains their own set of analyzers.

@captainsafia Is the request here clear enough for you to move forward in dotnet/aspnetcore?

**Comment by captainsafia** [comment]
@Youssef1313 I believe what is proposed here is a duplicate of the issue that is filed in https://github.com/dotnet/aspnetcore/issues/35727

**Comment by Youssef1313** [comment]
Thanks @captainsafia

Closing as a duplicate of dotnet/aspnetcore#35727
