### ISSUE TITLE
Roslyn.Diagnostics.Analyzers.Setup doesn't seem to deploy properly

### ISSUE THREAD

**Issue by jcouv** [dotnet/roslyn-analyzers#3153]
I tried to validate a roslyn analyzer locally by deploying it into Visual Studio (see [discussion](https://github.com/dotnet/roslyn-analyzers/pull/3125#discussion_r363536357)). But the new diagnostic and fix didn't appear.

I suspect it is a setup issue, because I put a `throw` statement in the existing `DeclarePublicAPI` analyzer and it didn't show up when I deployed that code to VS.

**Comment by mavasani** [comment]
@jcouv Is this still valid? It seems to work fine for me..

**Comment by jcouv** [comment]
Not sure. Let's close and I'll re-open if I encounter again. Thanks
