### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "BinaryFormatterDeserializeMaybeWithoutBinderSetMessage"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#3171]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The method '{0}' is insecure when deserializing untrusted data without a SerializationBinder to restrict the type of objects in the deserialized object graph.

File Name:
Microsoft.NetCore.Analyzers\Core\xlf\MicrosoftNetCoreAnalyzersResources.xlf

==========================================
What's deserialized - object or graph?

0; "BinaryFormatterDeserializeMaybeWithoutBinderSetMessage"
0; "BinaryFormatterDeserializeWithoutBinderSetMessage"
0; "JavaScriptSerializerMaybeWithSimpleTypeResolverMessage"
0; "JavaScriptSerializerWithSimpleTypeResolverMessage"
0; "NetDataContractSerializerDeserializeMaybeWithoutBinderSetMessage"
0; "NetDataContractSerializerDeserializeWithoutBinderSetMessage"

**Comment by dotpaul** [comment]
"object graph" as in a "graph of objects" (so I guess "graph").

**Comment by PDostalek** [comment]
Thx for reply
