### ISSUE TITLE
[loc][Query][Roslyn] Localizability of 0; "DefinitelyUseCreateEncryptorWithNonDefaultIV"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#3172]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Do not use CreateEncryptor with non-default IV

File Name:
Microsoft.NetCore.Analyzers\Core\xlf\MicrosoftNetCoreAnalyzersResources.xlf

==========================================
Query:
Shoud it be translated as "Please do not use CreateEncryptor with non-default IV"?

**Comment by dotpaul** [comment]
We have lots of strings in the form of "Do not blah blah blah" as an imperative. I'd say this one should be translated the same way as the others.
