### ISSUE TITLE
Prefer private/public fields in EditorConfig

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#3178]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/842310/scope-for-net-naming-conventions-for-editorconfig.html)._

---
<p>Is it possible to distinguish the scope for .editorconfig naming rules?</p> <p>I'd like to allow public fields in structs:</p><pre><code>public struct MyStruct {     public int StructField; } </code></pre> <p>But disallow public fields in classes:</p><pre><code>public class MyClass {     public int ClassField; } </code></pre> <p>Is this possible using .editorconfig naming rules?</p> <p>Back link: <a href="https://github.com/MicrosoftDocs/visualstudio-docs/issues/4400" target=_blank>https://github.com/MicrosoftDocs/visualstudio-docs/issues/4400</a></p>

---
#### Visual Studio Feedback System on 12/4/2019, 00:30 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### Kendra Havens [MSFT] on 1/3/2020, 06:49 PM: 

<p>Currently, you are not able to prefer private or public fields per type via the EditorConfig. In your second example for disallowing public fields in classes, would you want it to show a warning or just a message?</p>
<p>Thank you for helping Visual Studio improve!</p>

#### Luke on 1/3/2020, 11:48 PM: 

<p>I'd prefer a warning (which can be configured to be considered as an error which can prevent the project from being built).</p>

**Comment by Evangelink** [comment]
@mavasani Is it something we should work on? If so it seems more a code style rule to me so should be under the IDEXXX scope, isn't it?

**Comment by mavasani** [comment]
@Evangelink This seems related to [CA1051](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051): `Do not declare visible instance fields`. This analyzer also allows users to exclude structs from analysis via an editorconfig option `dotnet_code_quality.CA1051.exclude_structs = true`, see https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#exclude-structs. However, it seems the [doc page](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051#configurability) for CA1051 does not mention this option. Would you be able to open an issue/PR on dotnet/docs to address this?

I think once that is done, we can close this issue. Customer will need to do the following steps to get this analysis:

1. Enable or install .NET analyzers (CAxxxx rules) by following the steps at https://docs.microsoft.com/visualstudio/code-quality/install-net-analyzers
2. Escalate CA1051 to a build warning by adding editorconfig entry `dotnet_diagnostic.CA1051.severity = warning`
3. Add `dotnet_code_quality.CA1051.exclude_structs = true` to only flag public fields in classes

**Comment by Evangelink** [comment]
Doc PR filled.

**Comment by mavasani** [comment]
Thanks @Evangelink - closing this issue.
