### ISSUE TITLE
Build.cmd fails: Failed to locate Visual Studio

### ISSUE THREAD

**Issue by j2jensen** [dotnet/roslyn-analyzers#3184]
I'm hoping to contribute to this project, but I've had a few hiccups preventing me from doing so, which might prevent other people from contributing as well.

#### Repro steps

1. I followed the instructions for [Getting Started](https://github.com/dotnet/roslyn-analyzers#getting-started) in the Readme.

#### Expected behavior
Expected the .\Build.cmd command to succeed.

#### Actual behavior
Here's the output:

> dotnet-install: .NET Core SDK version 2.1.503 is already installed.
> dotnet-install: Adding to current process PATH: "C:\Source\Open Source\roslyn-analyzers\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
> Failed to locate Visual Studio (exit code '0').  Ensure you have all required Visual Studio components (Microsoft.Component.MSBuild, Microsoft.VisualStudio.Component.VSSDK, Microsoft.Net.Component.4.6.TargetingPack, Microsoft.VisualStudio.Component.Roslyn.Compiler).

Nothing in the Getting Started section mentions needing to install Visual Studio components in a certain way. I tried installing components into Visual Studio separately, but still never got this error to go away. 

I was able to open the solution in Visual Studio directly, and the only build error I got was in `ReportDiagnosticExtensions.cs`: the `switch` expression seemed to be unable to recognize that `null` should get turned into a nullable `ReportDiagnostic?` [here](https://github.com/dotnet/roslyn-analyzers/blob/9986046249ac2011aa649a24556858c221bc94b9/src/Utilities/Compiler/Extensions/ReportDiagnosticExtensions.cs#L30). I was able to fix it by adding an explicit cast, but I'm wondering if I'm just missing an updated C# compiler or SDK or something (possibly related to the error mentioned above).

Finally, while 1160 unit tests are passing (in visual studio), 5416 are failing. As far as I can tell, they're pretty much all null reference exceptions, mostly from the Microsoft.CodeAnalysis.Workspace.Options property getter.

I have a fix for [an issue](https://github.com/dotnet/roslyn-analyzers/issues/2133) that I'd like to submit as a pull request. The tests which appear to be relevant to the code I'm changing are passing. But since the Readme explicitly asks to make sure _all_ the tests are passing via the Build and Test commands, I don't feel like I can create a PR without figuring this out. Is there something I'm missing, which ought to be added to the Readme?

**Comment by mavasani** [comment]
@j2jensen Which build of VS are you on? I would recommend installing the latest VS2019 build from https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes and then choosing at least the following workloads in install:

1. .NET desktop development
2. .NET Core cross-platform development
3. Visual Studio extension development

**Comment by j2jensen** [comment]
I was on the latest version of Visual Studio, but I didn't have ".NET desktop development" or "Visual Studio extension development" workloads installed.  Adding those via the Visual Studio installer got past the issue I was seeing.

It would probably be good to add that recommendation to the Readme.

**Comment by mavasani** [comment]
Thanks, added with https://github.com/dotnet/roslyn-analyzers/pull/3195
