### ISSUE TITLE
Merge excluded_symbol_names and excluded_type_names_with_derived_types

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3189]
I can see a couple of rules that could benefit from having the exclude derived types and I am wondering whether it would be better to have the other rules also supporting the `excluded_type_names_with_derived_types` in addition to the `excluded_symbol_names`. Or if it would be better to have some syntax that would mean strict or with derived. Note that I think that it could make sense also for methods/properties to help handling overrides or interface implementation. In this case, we could merge the 2 options.

**Comment by mavasani** [comment]
@Evangelink Is this issue still valid?

**Comment by Evangelink** [comment]
Well it doesn't seem to be something requested by other users so I would say no but in theory my comment is still valid. Most of the rules where we have the `excluded_symbol_names` could be extended to exclude the type and its derivatives. 

In case you think that's worth keeping open and/or discussing, I am not sure having the two options is the best way forward. Maybe we could update the convention to tweak the prefix (or add a suffix): `excluded_symbol_names = T:A.B.C` excludes only the type `C` in the namespace `A.B`, and `excluded_symbol_names = T+derived:A.B.C` or `excluded_symbol_names = T:A.B.C+derived` means `C` and derived types. Or whatever the syntax we want to use.

**Comment by Evangelink** [comment]
I am closing this issue as with #3893 I have understood that the 2 APIs are not meant to be called directly but through some aggregating API. Hence rules automatically support both syntaxes, this is a lack of documentation.
