### ISSUE TITLE
FxCop rules factoring proposal

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#319]
Visual Studio today ships with 300+ CodeAnalysis rules for managed code in the box and they are all written as binary analysis rules using the FxCop engine. The rules in the FxCop folder of this repo are the beginnings of an effort to rewrite some of these rules using Roslyn's source analysis. However thinking of this effort a faithful rewriting of FxCop rules leads to the wrong mindset because of the following reasons:
- FxCop originally started as a "Framework Cop" and had rules about API design and BCL usability but since FxCop the name was also conflated with the binary analysis technology, it became the name for all the different kinds of rules that ship in VS. So FxCop means different things to different people.
- FxCop also means nothing to many people. VS's customers just see a mass of CodeAnalysis rules and there's no mention of FxCop anywhere in VS and all they are interested in is getting some guidance from static analysis. However they can't figure out which of the 300+ rules matter to them as there's no good grouping of the rules (other than the category which is rather generic).
- A large majority of the rules that are in VS today were written about 10 years ago. Platforms and guidelines have evolved significantly since then. Many of the rules either don't make sense or aren't that valuable anymore. 

The proposal here is to stop thinking about these rules as FxCopAnalyzers and instead to look at the inventory of rules that exist today and to factor them along API\purpose boundaries. As part of this exercise, identify the rules that are actually high value and only implement those as analyzers and instead of re-implementing low-value rules, add new rules that actually fills the gap created in the last 10 years and serve the API\purpose of these analyzers (eg: rules about async or ImmutableCollections etc.)

## Factoring principles
- In the spirit of [Code-Aware libraries](https://channel9.msdn.com/Events/Build/2015/3-725), if a rule is about the usage of a specific API and the rule doesn't make sense if that API is not referenced, then that rule should ship with that API. For example, rules about `ImmutableArray` (which lives in System.Collections.Immutable.dll) should live in a System.Collections.Immutable.Analyzers.dll which would get pulled in by the System.Collections.Immutable nuget package.
  - A given type could exist in different .NET assemblies among the various flavors of .NET frameworks that exist today. Which one do we choose? We should choose the [.NET Core](http://blogs.msdn.com/b/dotnet/archive/2014/11/12/net-core-is-open-source.aspx) version of the types as those assemblies are more granular and intend to ship as nuget packages. We could always have a consolidated nuget package for other less granular frameworks.
- When the rules are not about any APIs but are guidelines, then we should organize the rules about the intended purpose of those guidelines. For eg, some rules might be guidelines for API authors to produce consistent APIs but those rules might not make sense in a test assembly. As another example - there maybe some rules about restricting the expressiveness of the language in order to gain some perf advantage. Such rules would only apply in a specific context where that tradeoff is acceptable and hence shipping that as a single package is useful.

## Analyzer packages
The list of all the rules that ship in VS and some other FxCop\Roslyn rules that we know of is in this [RulesInventory.csv](https://github.com/dotnet/roslyn-analyzers/blob/master/RulesInventory.csv) file (which thanks to GitHub is searchable). That file also has a first draft of a proposed factoring of the analyzers. 

### API analyzer packages
There are rules about types in the following contract assemblies:
- **System.Runtime.Analyzers** - This package already exists
- **System.Runtime.InteropServices.Analyzers** Analyzers about interop\marshalling. This package already exists.
- **System.Security.Cryptography.Algorithms** - New package - contains analyzers with guidelines about Crypto algorithms' usage.
- **System.Xml** - New package - contains analyzers about types dealing with XML across System.Xml.* contracts.
- **DesktopAnalyzers** - These are analyzers about APIs that are present in the desktop .NET Framework but not in the new .NET Core set. Since the .NET framework isn't available in a piecemeal fashion, there's not much value in breaking this down further.
- **Microsoft.CodeAnalysis.Analyzers** - This package already exists. It contains rules about using the Roslyn APIs correctly.

### Theme based analyzer packages
- **Microsoft.Api.Design.Guidelines** - This package contains guidelines for authoring libraries which contain public APIs. The advantage of factoring it out this way is that one could simply install this analyzer for real APIs and not for executables and test projects reducing noise significantly. 
- **Microsoft.Maintainability** - This package contains rules that contains metrics-based and heuristics-based rules to assess complexity, maintanability and readability. 
- **Text.Analyzers** - This package contains rules that analyze code as text for spelling violations. 

For completeness, there is also a package in the table  called **Roslyn.Internal.Analyzers** which contains rules about some internal types in the Roslyn codebase meant as guidelines for Roslyn contributors as opposed to Roslyn consumers.

## What to port?
Aside from the factoring, the csv file also has some telemetry that has been reported through VS about number of violations and suppressions for many of the rules. We should use that as one data point in identifying whether a rule is high-value. Of course some of those numbers could have been reported long ago and so a subjective evaluation of the usefulness of a rule will be needed. Over the next few weeks, we will populate the Port? column with yes\no values. 

## Feedback
Please provide feedback about the plan, the factoring, individual rules, rules that should be rewritten, rules that should be cut and\or anything else.

**Comment by lgolding** [comment]
Per our discussion in triage this morning, I'll copy the text to a Markdown file in the repo, and then close this issue.
