### ISSUE TITLE
Is there any way I can add to CA1304's list of ignored calls?

### ISSUE THREAD

**Issue by Crono1981** [dotnet/roslyn-analyzers#3204]
I have a type that wraps a `ResourcesManager` object. The type has two methods, each wrapping a call to  `GetString` method. One of the method has a `CultureInfo` argument, the other have not and uses `GetString` without a specific culture, hence falls on the thread's current culture.

Now the CA1304 documentation specifies that calls to `ResourcesManager.GetString` are ignored by the rule. But since I'm wrapping the call under a different method, the analyzer now warns me about a possible problem with calling the method without a `CultureInfo` argument, even though having a different result depending on culture is the point.

I understand why this happens and that the rule can't possibly know about my API's intent. However, I don't want to disable the rule every time I'm using the method, nor do I want to ignore it as a whole in my projects.

Is there any way I can add the Wrapper.MethodThatCallsGetString method to the list of calls that CA1304 ignores? An attribute, perhaps?

Thanks.

**Comment by Evangelink** [comment]
That seems easy to add this rule to [excluded_symbol_names](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-symbol-names). 

Tagging @mavasani

**Comment by mavasani** [comment]
Sounds reasonable to make this rule configurable as @Evangelink suggested.
