### ISSUE TITLE
Test framework - difference in expected diagnostics

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3206]
Doing some cleanup in the tests I have noticed that the behavior of `Microsoft.CodeAnalysis.CSharp.Testing.XUnit.CodeFixVerifier` and `Test.Utilities.CSharpCodeFixVerifier` is different. The same is true for the `VisualBasic` pendant.

For example, in the class `DoNotMixAttributesFromDifferentVersionsOfMEFTests`, the test `NoDiagnosticCases_UnresolvedTypes` will return 2 diagnostics with the first verifier and only 1 with the second. In the class `PartsExportedWithMEFv2MustBeMarkedAsSharedTests`, the test `NoDiagnosticCases_UnresolvedTypes` will return 5 diagnostics with the first and none with the second.

These 2 tests are the only failing tests but I suspect that we might have more non-failing tests impacted by this difference.

Tagging @sharwell as you know quite a lot on the test framework.

**Comment by sharwell** [comment]
> For example, in the class DoNotMixAttributesFromDifferentVersionsOfMEFTests, the test NoDiagnosticCases_UnresolvedTypes will return 2 diagnostics with the first verifier and only 1 with the second. In the class PartsExportedWithMEFv2MustBeMarkedAsSharedTests, the test NoDiagnosticCases_UnresolvedTypes will return 5 diagnostics with the first and none with the second.

MEF 2 is brought in by the code analysis reference:

https://github.com/dotnet/roslyn-analyzers/blob/a03ebdb9ee611448c109feaef55ebc0204af73f9/src/Test.Utilities/AdditionalMetadataReferences.cs#L13-L15

This set of reference assemblies is the default for `CSharpCodeFixVerifier`, but not for the core test library.
