### ISSUE TITLE
Custom build package always on 42.42.424242

### ISSUE THREAD

**Issue by tnoiretisa** [dotnet/roslyn-analyzers#3225]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Repro steps

1. Get last sources
2. Build

#### Expected behavior
Get 2.9.8 version on analyzer

#### Actual behavior
Get 42.42.424242

**Comment by RussKie** [comment]
This is by design. Locally built versions will always be 42.42.42.42.
2.9.8 version is assigned to a release package at build time.

**Comment by tnoiretisa** [comment]
Have you any workaround to have real number on local compilation please ?

**Comment by mavasani** [comment]
@tnoiretisa I think the following should help:

`msbuild /m /v:m /p:Configuration=Release /p:DotNetUseShippingVersions=true`

**Comment by tnoiretisa** [comment]
Thanks you :) it's work !
