### ISSUE TITLE
Allow wildcard symbol for exclude_symbol_names options

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3242]
Once #3233 is merged, I think that it would make sense to update the [excluded_symbol_names](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#excluded-symbol-names) option to allow the wildcard pattern.

**Comment by mavasani** [comment]
@Evangelink This would be good to implement, but we need to ensure that it does not cause a perf hit.

**Comment by Evangelink** [comment]
Yes! Let's try to have the other PR merged first and then we will have to see how to assess the perf impact. Do you have any set of projects we could use to see performance degradation?

**Comment by Evangelink** [comment]
@mavasani When working on #3211 I have realized that since we have merged #3233 all the rules now support wildcard patterns, this is just an undocumented behavior. How do you want to proceed with that?
