### ISSUE TITLE
Unable to install Microsoft.CodeAnalysis.FxCopAnalyzers on asp.net core 3.1

### ISSUE THREAD

**Issue by DurgaPrasadReddyV** [dotnet/roslyn-analyzers#3250]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Repro steps

1. Create an asp.net core 3.1 project
2. Try to install the Microsoft.CodeAnalysis.FxCopAnalyzers package

#### Expected behavior

Install the nuget package

#### Actual behavior

The feed 'nuget.org [https://api.nuget.org/v3/index.json]' lists package 'Microsoft.NetFramework.Analyzers.2.9.8' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.
Unable to find package 'Microsoft.NetFramework.Analyzers.2.9.8'.

**Comment by mavasani** [comment]
Verified that https://www.nuget.org/packages/Microsoft.NetFramework.Analyzers/2.9.8 is available for download, so might be a temporary NuGet/internet glitch. Can you retry after some time?

**Comment by DurgaPrasadReddyV** [comment]
Thank you @mavasani . Looks like it indeed was the issue. I am able to install it now.
