### ISSUE TITLE
Microsoft.CodeAnalysis.PublicApiAnalyzers incorrect placement of updated nullable API

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn-analyzers#3253]
Copied from https://github.com/dotnet/winforms/pull/2778#issuecomment-580061460

#### Analyzer package

[Microsoft.CodeAnalysis.PublicApiAnalyzers](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.PublicApiAnalyzers)

#### Package Version

3.0.0-beta2.20077.2

#### Diagnostic ID

`RS0036`

#### Repro steps

1. Generate an API, record in in `PublicAPI.Shipped.txt`
2. Enable nullability
3. Update the API to nullable syntax
4. Use the analyzer auto-fix
5. Observe the API changes are recorded to `PublicAPI.Shipped.txt` replacing the existing entry.

#### Expected behavior

The updated API are generated in `PublicAPI.Unshipped.txt` and all existing API in `PublicAPI.Shipped.txt` remain in tact.

#### Actual behavior

`PublicAPI.Shipped.txt` updated instead of `PublicAPI.Unshipped.txt`. This is incorrect since we haven't shipped the NRT decorated API.

![image](https://user-images.githubusercontent.com/4403806/73416202-41ee0880-4368-11ea-8f2d-8772b39322c8.png)
![image](https://user-images.githubusercontent.com/4403806/73416241-6813a880-4368-11ea-9876-d5713b620f1f.png)

**Comment by sharwell** [comment]
I feel pretty strongly that the current behavior is correct. The annotated API has not shipped, but the API _contract_ has shipped and it doesn't change by the addition of nullable annotations. The file is being updated in place to add missing information about something that already shipped.

**Comment by mavasani** [comment]
I agree with @sharwell. @RussKie I thought from your original comment that adding a completely new API with nullable annotations and then attempting the code fix added the entry directly to shipped API file.

**Comment by RussKie** [comment]
Thank you for the feedback, I suppose it makes sense.

**Comment by sharwell** [comment]
@RussKie With that said, if the shipped API _has annotations_ and the annotations _changed_, it would make sense to apply that change in the unshipped file, or at least have the option of doing so.

**Comment by RussKie** [comment]
I checked it, this scenario appears to work correctly
![image](https://user-images.githubusercontent.com/4403806/73501355-ba60d200-4419-11ea-8089-e19f2793ec01.png)

**Comment by RussKie** [comment]
I'm now seeing the reverse - NRT-enabled API are recorded into the "unshipped" file -> https://github.com/dotnet/winforms/pull/2824

Has this changed?

**Comment by sharwell** [comment]
@RussKie it didn't change intentionally
