### ISSUE TITLE
 [loc][Query][Roslyn] Localizability of 0; "AnnotatePublicApiDescription"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#3263]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
All public types and members should be declared with nullability annotations in PublicAPI.txt. This draws attention to API nullability changes in the code reviews and source control history, and helps prevent breaking changes.

File Name:
PublicApiAnalyzers\Core\Analyzers\xlf\PublicApiAnalyzerResources.xlf

==========================================
Query:
Please confirm we should use the below translation of "annotation".
Definition: A note or comment attached to an asset to provide related information. 

Affected IDs:

0; "AnnotatePublicApiDescription"
0; "AnnotatePublicApiMessage"
0; "EnableNullableInProjectToThePublicApiTitle"
0; "EnableNullableInTheSolutionToThePublicApiTitle"
0; "ShouldAnnotateApiFilesDescription"
0; "ShouldAnnotateApiFilesMessage"

**Comment by Evangelink** [comment]
Ping @mavasani

**Comment by mavasani** [comment]
I think that sounds reasonable. By adding nullable annotations to public API files, we are adding nullability related extra information to the public API signatures.

**Comment by PDostalek** [comment]
Thanks for confirmation
