### ISSUE TITLE
Remove the MinimalImplementations.IAsyncDisposable class and use Microsoft.Bcl.AsyncInterfaces instead

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3276]
Prior to the TFM change, we should remove the MinimalImplementations.IAsyncDisposable class and add a NuGet reference to Microsoft.Bcl.AsyncInterfaces instead.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn-analyzers/pull/3273_

**Comment by Evangelink** [comment]
Shall we get rid of all the minimal implementation?

**Comment by sharwell** [comment]
> Shall we get rid of all the minimal implementation?

Ideally, yes. Referencing the true packages produces more accurate tests.
