### ISSUE TITLE
CA2101 is reported when APTCA is not applied

### ISSUE THREAD

**Issue by carlreinke** [dotnet/roslyn-analyzers#3280]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

[CA2101](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2101)

#### Repro steps

1. Create a method with `DllImport` having `BestFitMapping = true` and a string parameter with `MarshalAs(UnmanagedType.LPStr)`.
2. Ensure the `AllowPartiallyTrustedCallers` attribute is not applied to the assembly.

#### Expected behavior

CA2101 should not be reported when the `AllowPartiallyTrustedCallers` attribute is not applied to the assembly.

Cause of CA2101 is documented as:
> A platform invoke member **allows for partially trusted callers**, has a string parameter, and does not explicitly marshal the string.

If the behavior of the analyzer is as expected then the documentation (Cause and Example) should be corrected.

#### Actual behavior

CA2101 is reported.

**Comment by sharwell** [comment]
> AllowPartiallyTrustedCallers

This entire concept has been eliminated from .NET Core, so there's no longer a need for it to influence the behavior of rules. My recommendation is to either enable the rule if you would like to use it, or disable it if you don't want to use it.

We should update the documentation to more clearly state that `AllowPartiallyTrustedCallers` does not impact this rule behavior.
