### ISSUE TITLE
What is the quickest way to onboard to the PublicApiAnalyzer?

### ISSUE THREAD

**Issue by TimothyMothra** [dotnet/roslyn-analyzers#3322]
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Question

I want to onboard my product to the PublicApiAnalyzer. 
I pick a project to start with, add the NuGet package, and added empty text files. 
Now I have 160 build errors, great!

Is there a quick way to apply all of these codefixes or do I need to apply each one individually?

For context, our product is 17 packages, each targeting 2-4 frameworks.

**Comment by TimothyMothra** [comment]
I think I just answered my own question.
Sharing here for anyone else with the same question...


- First, edit the project to temporarily target only 1 framework.
- Build once to get the list of errors.
- Click first error and navigate to constructor/method/etc...
- Hover and click **Show potential fixes**.

![image](https://user-images.githubusercontent.com/28785781/75280882-1c1b1e80-57c3-11ea-93d4-b4c3413ab0fc.png)

- Click the link, **Fix all occurrences in Project**

![image](https://user-images.githubusercontent.com/28785781/75280844-0ad21200-57c3-11ea-8c8c-805d2f3b9be9.png)

- Review the Preview Changes dialog and click Apply

![image](https://user-images.githubusercontent.com/28785781/75280968-3fde6480-57c3-11ea-9b4b-9fbca64e7462.png)

**Comment by mavasani** [comment]
Thanks @TimothyMothra. Closing this issue...

**Comment by TimothyMothra** [comment]
@mavasani, can you tag this issue with the "publicapianalizer" tag so this can be easily found?

When looking for this answer, that's the first thing i did. :)
