### ISSUE TITLE
Update dataflow analysis to use the helper for serialization ctor and GetObjectData

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3331]
See https://github.com/dotnet/roslyn-analyzers/pull/3321#commitcomment-37507346 and following comments.

It was decided to keep the current check

https://github.com/dotnet/roslyn-analyzers/blob/5be2c0cf63a36b43a2736587c02c37a83dfa41e1/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/ParameterValidationAnalysis/ParameterValidationAnalysis.ParameterValidationDataFlowOperationVisitor.cs#L287-L306

instead of using the helper for the time being. When ready for a potential breaking change, let's update the code to use the helper.

**Comment by Evangelink** [comment]
@mavasani Is it something you could discuss at some meeting?

**Comment by Evangelink** [comment]
@mavasani Is it ok to use the helper here now?

**Comment by mavasani** [comment]
Seems fine to me.
