### ISSUE TITLE
Convert CA2012 (UseValueTasksCorrectly) to use the DFA framework

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#3332]
The rule as introduced in https://github.com/dotnet/roslyn-analyzers/pull/3001 uses a hand-rolled dataflow analysis to track ValueTask instances returned from methods.  We should try to get it into the shared dataflow analysis framework in the repo.
https://github.com/dotnet/roslyn-analyzers/pull/3001#discussion_r384112264

**Comment by mavasani** [comment]
Closing this out - we can get to this if/when need arises.
