### ISSUE TITLE
[BannedApiAnalyzers] Attribute detection and out parameter detection.

### ISSUE THREAD

**Issue by indy-singh** [dotnet/roslyn-analyzers#3333]
#### Analyzer package:
[Microsoft.CodeAnalysis.BannedApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.BannedApiAnalyzers/)

#### Package Version:
`<package id="Microsoft.CodeAnalysis.BannedApiAnalyzers" version="2.9.8" targetFramework="net472" developmentDependency="true" />`

#### Repro steps
```csharp
namespace Foo
{
    public class BannedPlayground
    {
        public void Execute()
        {
            Pet pet;
            Enum.TryParse("dog", true, out pet); // I want to ban this
            Enum.TryParse("dog", out pet); // I want to ban this

            var thing = new Thing();
            var value = 0;
            thing.TryParse("dog", true, value); // this can be detected
            thing.TryParse("dog", value); // this can be detected
        }
    }

    [ProtoContract()] // I want to ban this
    public class RequestA
    {

    }

    [ProtoContract(IsGroup = true)] // I want to allow/enforce this
    public class RequestB
    {

    }

    public enum Pet
    {
        Unknown = 0,
        Cat = 1,
        Dog = 2
    }

    public class Thing
    {
        public void TryParse<T>(string a, bool flag, T value) => Console.WriteLine();

        public void TryParse<T>(string a, T value) => Console.WriteLine();
    }
}
```

BannedSymbols.txt:-
```
M:System.Enum.TryParse``1(System.String,System.Boolean,``0);nope
M:System.Enum.TryParse``1(System.String,``0);nope

M:Foo.Thing.TryParse``1(System.String,System.Boolean,``0);nope
M:Foo.Thing.TryParse``1(System.String,``0);nope

M:ProtoBuf.ProtoContractAttribute.#ctor;nope
```

#### Expected behavior
I would expect compile time warnings/errors.

#### Actual behavior
It doesn't break the build.

We've been using this library to great effect since it's discovery. But there are a couple of scenarios that we would like to cover in particular projects that we have been unable to figure out the syntax.

I don't know if our syntax is incorrect or if the analyser needs to be handle these cases. In the case of `System.Enum.TryParse` I'm sure the `out` is currently not detected at all. As if I stub out my own method signature without the `out` parameter I can detect it.

In the case of `ProtoContract` we want to enforce this for this reason: https://github.com/protobuf-net/protobuf-net/issues/301#issuecomment-370178685. Basically for us, the only valid use of `ProtoContract` is `[ProtoContract(IsGroup = true)]`.

Any ideas?

Thanks,
Indy

**Comment by KalleOlaviNiemitalo** [comment]
## `out` or `ref` parameter

Use an `@` sign after the type of the parameter:

```
M:System.Enum.TryParse``1(System.String,System.Boolean,``0@);yeah
M:System.Enum.TryParse``1(System.String,``0@);yeah
```

That is documented in [ID string format](https://github.com/dotnet/csharplang/blob/master/spec/documentation-comments.md#id-string-format). You can also find these strings by adding temporary XML documentation comments:

```C#
/// <seealso cref="Enum.TryParse{TEnum}(string, bool, out TEnum)" />
/// <seealso cref="Enum.TryParse{TEnum}(string, out TEnum)"/>
```

and then enabling XML documentation file output in the project properties, which generates:

```XML
<member name="M:Foo.BannedPlayground.Execute">
  <seealso cref="M:System.Enum.TryParse``1(System.String,System.Boolean,``0@)" />
  <seealso cref="M:System.Enum.TryParse``1(System.String,``0@)"/>
</member>
```

## Property of attribute

I don't think the banned API analyzer supports your scenario. The easiest solution might be to implement your own analyzer for this.

If the banned API analyzer were extended to support this, would you expect it to warn about code that constructs an instance of the attribute type at run time and does not set the property:

```C#
public static void Demo()
{
    Attribute attr = new ProtoContractAttribute();
    Console.WriteLine(attr.ToString());
}
```

**Comment by indy-singh** [comment]
Ahhh, I see. I've been using https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md as my guide, but I completely missed this line:-

> For details on ID string format, please refer to "Documentation comments"

Thanks for helping me out.

Cheers,
Indy
