### ISSUE TITLE
Adopt MIT license

### ISSUE THREAD

**Issue by kryptine** [dotnet/roslyn-analyzers#3334]
This repository should use the MIT license [for consistency with dotnet/roslyn](https://github.com/dotnet/roslyn/commit/0d04884c243978cdd609e219fdb63cb58ebec69d)

**Comment by Evangelink** [comment]
Licensing issue has a low technical complexity but a quite big importance for end-users, I think this and the related issue #3347 should have a high priority. Let me know if I can help.

**Comment by Evangelink** [comment]
Ping @mavasani

**Comment by Evangelink** [comment]
Ping @mavasani

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn-analyzers/pull/5306
