### ISSUE TITLE
CA1716 Not warning

### ISSUE THREAD

**Issue by jjhayworth** [dotnet/roslyn-analyzers#3349]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

[CA1716](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1716-identifiers-should-not-match-keywords)

#### Repro steps

1. Create a C# project.
2. Install FxCop Analyzers
3. Create an identifier with a name of a Visual basic keyword, such as the following
`public int AddHandler { get; set; }`

#### Expected behavior
Warning
#### Actual behavior
No warning

**Comment by Evangelink** [comment]
@jjhayworth The member should be `virtual`, `abstract` or an interface implementation, see: https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldNotMatchKeywords.cs#L176-L184

**Comment by jjhayworth** [comment]
@Evangelink Ah, didn't see that, my apologies.
