### ISSUE TITLE
Create analyzer to detect calls to SemanticModel.GetDeclaredSymbol() with fields and other invalid syntax

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn-analyzers#336]
Using [`SemanticModel.GetDeclaredSymbol()`](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpSemanticModel.cs,a9611eff063ce71a,references) will always return null for certain pieces of syntax. According to the comments this is the case for `GlobalStatementSyntax`, `IncompleteMemberSyntax`, and `BaseFieldDeclarationSyntax`.   

In order to guide new people using the API, we should provide an analyzer that checks for invalid calls to `GetDeclaredSymbol()` and issues a warning. (In particular the field syntax can be confusing for people who don't realize fields consist of multiple variables).

**Comment by Evangelink** [comment]
Although I like rules helping you to use an API correctly, I think these use cases are rare.
