### ISSUE TITLE
Per-symbol severity for CA2000 (and possibly others)

### ISSUE THREAD

**Issue by lostmsu** [dotnet/roslyn-analyzers#3369]
I am looking into setting severity level per type for CA2000. Specifically, I want a particular type to emit CA2000 errors, and leave the rest to be warnings. Is this possible?

**Comment by Evangelink** [comment]
I am afraid it is not. @mavasani This would be a global change for which there needs to be a discussion but I can see some value in allowing a per type/symbol specific severity.

**Comment by mavasani** [comment]
No this aspect is not configurable - you can configure specific diagnostic IDs to have different severities for any chosen file and/or directory in editorconfig, but you cannot configure severity for each diagnostic instance based on options.

**Comment by Evangelink** [comment]
@mavasani Do you think it's possible that things evolve to allow a per-symbol severity or do you think that's unlikely? If unlikely maybe the ticket shall be closed.

**Comment by mavasani** [comment]
Agreed, this is likely not going to be implemented.
