### ISSUE TITLE
Custom analyzer silently fails builds, only "csc.exe exited with code 1" is printed

### ISSUE THREAD

**Issue by EikeStein** [dotnet/roslyn-analyzers#3402]
#### Analyzer package

Custom analyzer published to private NuGet feed. Works for any open files and with the setting "Enable full solution analysis" also for closed files, as long as the project is not build.

#### Repro steps

1. Analyzer is installed via nuget package from private artifact nuget feed in Azure DevOps
2. Analyzer works as expected for open files (errors get displayed in the Error List window)
3. Building the project removes the error from the custom analyzer from the Error List and no output is generated (e.g. AnalyzerXYZ reported: "warning xyzxyz" or something similar, build just fails)
4. After the build has failed only "csc.exe exited with code 1" appears in the Error List with no further information or reason. 

#### Expected behavior
The error from the analyzer should be reported in either the output window (especially for CI) or at least in the Error List window - preferable both. The error should not disappear after a build has failed.

![grafik](https://user-images.githubusercontent.com/11982172/77080101-34184380-69f9-11ea-8fcd-6cf5d4fa0783.png)

#### Actual behavior
No information/reason for the failed build is given anywhere
![grafik](https://user-images.githubusercontent.com/11982172/77080468-98d39e00-69f9-11ea-81df-4e8c2c07b04e.png)

![grafik](https://user-images.githubusercontent.com/11982172/77080631-cfa9b400-69f9-11ea-82c7-deade9d327c0.png)

**Comment by Evangelink** [comment]
@EikeStein Is it a custom version of the analyzer in this repo or is it a new analyzer independent from this repo? Reading your description makes me think this issue is for `roslyn`.

**Comment by mavasani** [comment]
Yes, this looks a compiler bug. @sharwell can you port to Roslyn repo?

**Comment by EikeStein** [comment]
@Evangelink yes this is a custom analyzer that is not working as expected. I thought this repo was kind of the starting point for all analyzer concerns, sorry for that! Porting this issue would be great :)

**Comment by EikeStein** [comment]
I have already created the issue in the other repo, so no porting is required
