### ISSUE TITLE
Consider revisiting or improving the wildcard matching algorithm

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3403]
1. Consider revisiting this code for code refactoring/cleanup for easier future maintenance.

2. Consider tuning the cache size and hit/misses here to improve performance.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/3233_

**Comment by mavasani** [comment]
Thank you @Evangelink
