### ISSUE TITLE
Do not return null from non-async Task method

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3407]
Hi there,

I don't think such rule exists in the current codebase (or I failed to find it). Returning null from a non-async `Task` method will result in a null pointer at runtime but everything is fine at compile-time.

Non-compliant code:

```csharp
public Task<Person> GetPersonAsync(string name)
{
	// some code
    return null; 
}
```

Compliant code:

```csharp
public Task<Person> GetPersonAsync(string name)
{
	// some code
    return Task.FromResult<Person>(null);
}
```

The probability of such code is quite low but I saw something similar in a couple of places.

**Comment by mavasani** [comment]
@Evangelink We have decided to move all the threading/async related analyzers to https://github.com/microsoft/vs-threading/tree/master/src/Microsoft.VisualStudio.Threading.Analyzers. Please feel free to move the issue there or check if the rule already exists in that package.

**Comment by Evangelink** [comment]
Moved to https://github.com/microsoft/vs-threading/issues/593
