### ISSUE TITLE
ThreadStatic fields should not be initialized inline

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3408]
When a field is annotated with `ThreadStatic`, it is unique across threads and since a class' static initializer is only invoked from the first thread created it means that the other threads will have the type default value.

**Comment by mavasani** [comment]
@Evangelink another issue that likely needs to be moved to threading analyzers repo.

**Comment by Evangelink** [comment]
https://github.com/microsoft/vs-threading/issues/594
