### ISSUE TITLE
IdentifiersShouldHaveCorrectSuffixAnalyzer AD0001

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3414]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

3.0.0-beta2.20170.4

#### Issue

```
Error	AD0001	Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldHaveCorrectSuffixAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

I don't have any stacktrace in my IDE, is there any option somewhere I can switch?

**Comment by mavasani** [comment]
Hmm how did you encounter this? Was it from build or live analysis? Expanding the IDE live analysis diagnostic in error list should always give you a callstack and richer exception information

**Comment by mavasani** [comment]
Wondering if the issue here is that BaseType can be null:

https://github.com/dotnet/roslyn-analyzers/blob/6a5f5a1c43df75b824c57335f8b1929e24a966e6/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs#L129-L131

https://github.com/dotnet/roslyn/blob/d2e50fd781d236530fbfc3ff29c24f99fedbe755/src/Compilers/Core/Portable/Symbols/ITypeSymbol.cs#L29-L34

```csharp
        /// <summary>
        /// The declared base type of this type, or null. The object type, interface types,
        /// and pointer types do not have a base type. The base type of a type parameter
        /// is its effective base class.
        /// </summary>
        INamedTypeSymbol? BaseType { get; }
```

**Comment by Evangelink** [comment]
> Hmm how did you encounter this? Was it from build or live analysis? Expanding the IDE live analysis diagnostic in error list should always give you a callstack and richer exception information

I am using the last pre-release nuget package. And I don't have any expand option which is why I was asking.

![image](https://user-images.githubusercontent.com/11340282/77450204-41677080-6df3-11ea-93df-608444706032.png)

Regarding the location you are pointing to, yeah that seems like a bug.

**Comment by mavasani** [comment]
Tag @sharwell - seems like this is an AD0001 from command line build. Support to have context information was added in https://github.com/dotnet/roslyn/pull/35871, but likely MSBuild output filters out extra info?

**Comment by mavasani** [comment]
Switching to MSBuild build output verbosity to detailed shows the exception information:

```
1>    CSC : warning AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldHaveCorrectSuffixAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
1>    Exception occurred with following context:
1>    Compilation: Microsoft.CodeAnalysis.AnalyzerUtilities
1>    ISymbol: IDataFlowAnalysisResult (NamedType)
1>    System.NullReferenceException: Object reference not set to an instance of an object.
1>    at Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldHaveCorrectSuffixAnalyzer.TryGetTypeSuffix(IEnumerable`1 typeSymbols, ImmutableDictionary`2 hardcodedMap, SymbolNamesWithValueOption`1 userMap, SuffixInfo& suffixInfo)
1>    at Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldHaveCorrectSuffixAnalyzer.<>c__DisplayClass11_0.<AnalyzeCompilationStart>b__0(SymbolAnalysisContext saContext)
1>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__48_1(ValueTuple`2 data)
1>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
1>    -----
1>    Suppress the following diagnostics to disable this analyzer: CA1710
```

**Comment by mavasani** [comment]
This NRE seems to be occur very commonly on just released https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/3.0.0-beta2.final. I will send out a fix and try to release a 3.0.0-beta3.final with a fix soon.

**Comment by Evangelink** [comment]
Thank you for the fix and sorry to have miss this case when doing the implementation.

**Comment by mavasani** [comment]
No worries @Evangelink! Thanks for your help.
