### ISSUE TITLE
Dead Link for CA1509 in Key

### ISSUE THREAD

**Issue by jjhayworth** [dotnet/roslyn-analyzers#3416]
#### Repro steps

1. Open a web browser.
2. Go to the [rule key](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md) page in the repo.
3. Click on CA1509's hyperlink.

#### Expected behavior
Relevant page loads.
#### Actual behavior
[404](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1509)

**Comment by Evangelink** [comment]
Duplicate #2543

**Comment by Youssef1313** [comment]
The link works now.

**Comment by mavasani** [comment]
Thanks!
