### ISSUE TITLE
Async/await-Transactions

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/roslyn-analyzers#3419]
It seems you can't use transactions when you use ConfigureAwait(false). It would be great to have an analyser who could catch this situation.

**Comment by stephentoub** [comment]
> It seems you can't use transactions when you use ConfigureAwait(false).

Can you elaborate? Repro? Issue link?

**Comment by Bartolomeus-649** [comment]
https://www.thinktecture.com/en/entity-framework-core/use-transactionscope-with-caution-in-2-1/

**Comment by stephentoub** [comment]
That's not because of ConfigureAwait(false); there's no guarantee even without ConfigureAwait(false) that you'll be on the same thread.  The issue highlighted in that post is that all of the relevant transactions need to use TransactionScopeAsyncFlowOption.Enabled.

**Comment by Bartolomeus-649** [comment]
are you saying that there's no issue or problems with using transactions and ConfigureAwait(false)?

**Comment by stephentoub** [comment]
Yes, I'm saying I'm not aware of any issues with using transactions and ConfigureAwait(false).  If you want to use transactions and async, the transactions all need to be created with TransactionScopeAsyncFlowOption.Enabled; at that point it doesn't matter what thread you're on.  If you don't specify TransactionScopeAsyncFlowOption.Enabled for all of the relevant transactions, then things are likely to not work regardless of ConfigureAwait(false)... the only way they might happen to still work is if you were guaranteed by other means that you were going to be on the same thread, but generally the only way you'd be confident of that is if you were running on, say, the UI thread, writing app-level code in, say, a button-click event handler, at which point you shouldn't be using ConfigureAwait(false) anyway, as doing so would make it such that your UI interactions would be likely to fail.

**Comment by Bartolomeus-649** [comment]
Ohh, so you mean that there's no need for an analyser to check if transactions are set up the correct way when using ConfigureAsync(false), because you could just tell everybody never make any mistakes and always ues everything exactly they correct way?
This is a brilliant idea!! No One ever make any more mistakes any more. You want send out an email and let everyone know before we scrap all analysers, or should we just get rid of them right away?

**Comment by stephentoub** [comment]
Thank you for your sarcasm.

No, I'm saying that checking for ConfigureAwait(false) is the wrong thing to check for.  If you want an analyzer, it should be checking that TransactionScopeAsyncFlowOption.Enabled is used.

You can remove all use of ConfigureAwait(false) from your code, and still hit the problem you cited.  With or without ConfigureAwait(false), there is no guarantee for the target function that it'll be running on the same thread after the await it was before the await.

If there's a bug here, it's not related to ConfigureAwait(false), it's related to not using TransactionScopeAsyncFlowOption.Enabled.

**Comment by Bartolomeus-649** [comment]
How do you use TransactionScopeAsyncFlowOption.Enabled in .NET 4.5?

**Comment by stephentoub** [comment]
It was introduced in 4.5.1.  async/await and transactions do not mix well until 4.5.1.  Again, nothing to do with ConfigureAwait(false).

**Comment by Bartolomeus-649** [comment]
So, how did you use Transactions before .NET 4.5.1, when there were no TransactionScopeAsyncFlowOption.Enabled? 
Still think the problem is whether you set TransactionScopeAsyncFlowOption.Enabled or not?
What async related problems are there with transactions when you use ConfigureAwait(**true**)?

**Comment by stephentoub** [comment]
> So, how did you use Transactions before .NET 4.5.1, when there were no TransactionScopeAsyncFlowOption.Enabled?

async/await were introduced along with .NET Framework 4.5.  Using transactions with async/await in .NET Framework 4.5 was unsupported.  Then TransactionScopeAsyncFlowOption.Enabled was introduced in .NET Framework 4.5.1 to enable them to be used together.

> Still think the problem is whether you set TransactionScopeAsyncFlowOption.Enabled or not?

Yes.

> What async related problems are there with transactions when you use ConfigureAwait(true)?

The same problems as when you use ConfigureAwait(false) or don't use ConfigureAwait at all.

**Comment by Bartolomeus-649** [comment]
Are you saying that transactions were completely unsupported before .NET 4.5.1, and should never, under any circumstances be used?
Because if you could, under some circumstances, use transactions before .NET 4.5.1, their success can hardly be tied to whether you use TransactionScopeAsyncFlowOption.Enabled or not, right?

This code 
```cs
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Transactions;

public class Program
{
	private static string indent = "";
	public static async Task<int> Main()
	{
		bool awaitCfg = false;
		await DoTest(awaitCfg);
		WriteMessage("=================================================\n\n\n");

		awaitCfg = true;
		await DoTest(awaitCfg);


		Console.ReadKey();
		return 0;
	}

	private static async Task DoTest(bool awaitCfg)
	{
		try
		{
			WriteMessage($"Before with ConfigureAwait({awaitCfg})");
			indent = ("").PadLeft(4);
			int result = await DoAsyncTransaction(awaitCfg).ConfigureAwait(awaitCfg);
			WriteMessage($"Result with ConfigureAwait({awaitCfg}): {result}");
		}
		catch (Exception ex)
		{
			Console.ForegroundColor=ConsoleColor.Red;
			WriteMessage($"Exacption with ConfigureAwait({awaitCfg}): {ex.ToString()}");
			Console.ResetColor();
		}
		finally
		{
			indent = "";
			WriteMessage($"After with ConfigureAwait({awaitCfg})");
		}
	}

	private static async Task<int> DoAsyncTransaction(bool awaitCfg)
	{
		using (var tx = new TransactionScope())
		{
			int result = await AsyncMethod(awaitCfg).ConfigureAwait(awaitCfg);
			tx.Complete();

			return 39 + result;
		}
	}

	private static async Task<int> AsyncMethod(bool awaitCfg)
	{
		await Task.Delay(500).ConfigureAwait(awaitCfg);
		return 3;
	}

	private static void WriteMessage(string message)
	{
		Console.WriteLine($"{indent}{message}");
	}
}
```

Produces this output
```
Before with ConfigureAwait(False)
    Exacption with ConfigureAwait(False): System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created.
   at System.Transactions.TransactionScope.Dispose()
   at Program.<DoAsyncTransaction>d__3.MoveNext() in C:\Users\Hakan\source\repos\TestAsyncTransactions\TestAsyncTransactions\Program.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Program.<DoTest>d__2.MoveNext() in C:\Users\Hakan\source\repos\TestAsyncTransactions\TestAsyncTransactions\Program.cs:line 29
After with ConfigureAwait(False)
=================================================



Before with ConfigureAwait(True)
    Result with ConfigureAwait(True): 42
After with ConfigureAwait(True)
```

So, here we have code that works with .NET 4.5, and where `TransactionScopeAsyncFlowOption.Enabled`  is not used, and where `ConfigureAwait(true)` works, while with `ConfigureAwait(false)` fail.
Since `TransactionScopeAsyncFlowOption.Enabled` does not even exist in .NET 4.5, and this sample clearly proves that Transactions are problematic when you use `ConfigureAwait(false)`, I still think

> It would be great to have an analyser who could catch this situation.

**Comment by stephentoub** [comment]
> So, here we have code that works with .NET 4.5, and where TransactionScopeAsyncFlowOption.Enabled is not used, and where ConfigureAwait(true) works, while with ConfigureAwait(false) fail.

It's not showing what you think it's showing.  Try changing your beginning `bool awaitCfg = false` to be `bool awaitCfg = true`, and you'll see it fails.  The way you structured your test, the first test starts on the main thread and will complete on a thread pool thread, so regardless of whether you use ConfigureAwait(true) or ConfigureAwait(false), it's going to fail.  Then for the subsequent awaits, you're on a thread pool thread, so whether it passes your test is based on whether the continuation happens to run on the same thread pool thread or not.

> this sample clearly proves that Transactions are problematic when you use ConfigureAwait(false)

It does not.

**Comment by Bartolomeus-649** [comment]
hummm.....your arguments and knowledge of this is annoyingly good.
Does this behave differently on ASP.NET?

**Comment by stephentoub** [comment]
> Does this behave differently on ASP.NET?

Nope.

**Comment by Bartolomeus-649** [comment]
Strange, we have a huge website using transactions, which worked fine. When we added ConfigureAwait(false) we got "System.InvalidOperationException: A TransactionScope must be disposed on the same thread that it was created." exceptions all over the place. When we then changed them to ConfigureAwait(true) everything started working again, and it is running like hat right now without any problems.

**Comment by stephentoub** [comment]
If you're using async/await with transactions in .NET 4.5 / without TransactionScopeAsyncFlowOption.Enabled, there's a really good chance you have bugs, even if you're not aware of it, whether those bugs being exceptions like the above that are silently being ignored somewhere, or more insidious issues, like operations you didn't expect to be part of a transaction actually being part of some entirely unrelated one (anything that ran on the thread pool thread for arbitrary unrelated work items between the time the transaction was created and completed).

Regardless, in "a huge website", there's lots of possibility for one thing to indirectly impact another.  For example, ASP.NET in .NET Framework 4.5 uses a SynchronizationContext to flow state associated with the current request, like HttpContext.Current.  If you use ConfigureAwait(false), you're explicitly saying "I don't need that", so if you then try to access such resources, things could go south quickly, and that could result in some kind of chain reaction that could influence transactions.

You'll need to debug through to understand why it's happening.  I'm going to close this issue, though, as there's nothing wrong with using ConfigureAwait(false) with transactions.  Thanks.
