### ISSUE TITLE
UseValueTasksCorrectlyAnalyzer throws NullReferenceException when storing a ValueTask in variable

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/roslyn-analyzers#3433]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

3.0.0-beta3.final (latest pre-release)

#### Repro steps
```cs
using System.IO;
using System.Threading.Tasks;

public class C
{
    private static ValueTask Main()
    {
        var stream = Stream.Null;
        var result = stream.DisposeAsync();
        return result;
    }
}

```

#### Expected behavior
UseValueTasksCorrectlyAnalyzer doesn't throw an exception.

#### Actual behavior
UseValueTasksCorrectlyAnalyzer throws a NullReferenceException.
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	DotNetCoreConsoleProject		1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: DotNetCoreConsoleProject
IOperation: Invocation
SyntaxTree: D:\Documents\work\Projects\TestSolution\DotNetCoreConsoleProject\DotNetCoreProgram.cs
SyntaxNode: stream.DisposeAsync() [InvocationExpressionSyntax]@[170..191) (8,21)-(8,42)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer.CountConsumptions(BasicBlock block, ISymbol valueTaskSymbol)
   at Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer.HandleAtypicalValueTaskUsage(OperationAnalysisContext operationContext, INamedTypeSymbol debugType, IOperation operation, IInvocationOperation invocation)
   at Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer.<>c__DisplayClass9_0.<Initialize>b__1(OperationAnalysisContext operationContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__59_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

#### Note
If I write a code that does not storing in variable, then UseValueTasksCorrectlyAnalyzer doesn't throw an exception:
```cs
using System.IO;
using System.Threading.Tasks;

public class C
{
    private static ValueTask Main()
    {
        var stream = Stream.Null;
        return stream.DisposeAsync();
    }
}
```

**Comment by stephentoub** [comment]
@mavasani, I naively believed IntelliSense here:
![image](https://user-images.githubusercontent.com/2642209/77650850-59013f00-6f42-11ea-9dcb-0dd4871590c3.png)
but it's wrong; it not only can be null here, it is null here in this path, hence the error.

Has this Roslyn assembly already been annotated for nullable reference types?  If yes, IOperator.Parent is annotated incorrectly.  If no, why is IntelliSense making any declarations about whether it's null or not?

**Comment by mavasani** [comment]
Tagging @333fred `IOperation` API surface has not been annotated in Roslyn. This is a known work item. However, I believe this is likely an IDE bug that quick info is showing that `op.Parent` is not null. @sharwell @jasonmalinowski any ideas?

**Comment by sharwell** [comment]
@stephentoub You were hitting dotnet/roslyn#36983. The semantic model does not distinguish between oblivious types and non-null types, so until changes are made to the compiler our only options are to remove this feature or to show incorrect information in cases of oblivious code.

**Comment by stephentoub** [comment]
> so until changes are made to the compiler our only options are to remove this feature or to show incorrect information in cases of oblivious code.

From my perspective, showing incorrect information is worse than showing nothing at all.

This also seems a lot simpler than the cases shown in that issue; there's no assignment here... I'm hovering over the oblivious property itself and it's telling me it's not null.  That's fundamentally flawed.

> 'Parent' may or may not be null here.

How is that helpful?  If it may or may not be null, it may be null.
