### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of 0; "PreferNull

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#3438]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

File Name Live Page Extended | String Resource ID | Full Source String
-- | -- | --
Roslyn.Diagnostics.Analyzers\Core\xlf\RoslynDiagnosticsAnalyzersResources.xlf | 0;   "PreferNullLiteralCodeFix" | Use   'null' instead of 'default'

 Query:
Do the below strings refer to some function that will use 'null' instead of 'default', or is that a request to the user that he or she should use 'null' instead of 'default' (like 'please use null and please don't use default')? The intent of the strings is unclear.

0; "PreferNullLiteralCodeFix"
Use 'null' instead of 'default'

0; "PreferNullLiteralDescription"
Use 'null' instead of 'default' for reference types.

0; "PreferNullLiteralMessage"
Use 'null' instead of 'default' for reference types

0; "PreferNullLiteralTitle"
Prefer null literal

**Comment by sharwell** [comment]
It is a request that the user use 'null', and not use 'default'

**Comment by PDostalek** [comment]
thanks for reply
