### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers.md and horizontal scrolling

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/roslyn-analyzers#3460]
Could https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md be laid out vertically instead of horizontally?

To read the useful Description column, you got to scroll to bottom of page, and then scroll horz... and then you lose the context of what rule id etc.

GH readme pages are so narrow, it seems better to try and lay out vertically instead of horizontally.

**Comment by Evangelink** [comment]
Any example of what it could look like?

**Comment by Andrew-Webb** [comment]
[CA1000](https://docs.microsoft.com/visualstudio/code-quality/ca1000)

**Title** - Do not declare static members on generic types

**Category** - Design

**Enabled** - True

**Severity** - Warning

**Code Fix** - False

**Description** 

When a static member of a generic type is called, the type argument must be specified for the type. When a generic instance member that does not support inference is called, the type argument must be specified for the member. In these two cases, the syntax for specifying the type argument is different and easily confused.

----

[CA1001](https://docs.microsoft.com/visualstudio/code-quality/ca1001)

**Title** - Types that own disposable fields should be disposable

**Category** - Design

**Enabled** - True

**Severity** - Warning

**Code Fix** - True

**Description** 

A class declares and implements an instance field that is a System.IDisposable type, and the class does not implement IDisposable. A class that declares an IDisposable field indirectly owns an unmanaged resource and should implement the IDisposable interface.

----

**Comment by Evangelink** [comment]
@mavasani On the second thought I am actually wondering if this file is not redundant with the docs pages. Some points like default status and whether it has a code fix are valuable info that would deserve to be on the public doc.

**Comment by Evangelink** [comment]
@mavasani do you plan to keep this file in addition to the official doc?

**Comment by Evangelink** [comment]
@mavasani I can do the refactoring but I am not sure about the support of 2 docs.

**Comment by mavasani** [comment]
> do you plan to keep this file in addition to the official doc?

Yes, the docs page get outdated very soon, are not specific to a particular release and are only for porting status. The md files are shipped with each package release with info about rules shipping in that package.

**Comment by Evangelink** [comment]
I cannot find the script generating the file but it doesn't seem to be manually edited, @mavasani could you point me to the script? Or confirm it is manually edited.

**Comment by mavasani** [comment]
It’s auto generated here: https://github.com/dotnet/roslyn-analyzers/blob/7b0798b7a2a270cbcde86ab525d917a3a8026b71/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs#L212

Invoked post-build step here: https://github.com/dotnet/roslyn-analyzers/blob/7b0798b7a2a270cbcde86ab525d917a3a8026b71/eng/GenerateAnalyzerNuspec.targets#L25

Target enabled when running pack on the NuGet projects in the repo here: https://github.com/dotnet/roslyn-analyzers/blob/7b0798b7a2a270cbcde86ab525d917a3a8026b71/nuget/Directory.Build.targets#L4

You can locally get these re-generated by running “msbuild /t:pack” on both solutions at our repo root.
