### ISSUE TITLE
CA1305 on bool.ToString()

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/roslyn-analyzers#3465]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8

#### Diagnostic ID

[CA1305](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1305)

#### Repro steps

While the actual code is different, sematically it's `bool b; string s = b.ToString();`.

#### Expected behavior

No warning.

#### Actual behavior

CA1305.

According to documentation, Boolean.ToString() can only return one of two values: "True" or "False". Provided documentation is correct, CA1305 on Boolean.ToString() is erroneous.

**Comment by Evangelink** [comment]
Duplicates #2394 (tagging @mavasani)

**Comment by Evangelink** [comment]
Ping @mavasani

**Comment by Evangelink** [comment]
@mavasani Ticket can be closed.
