### ISSUE TITLE
[Proposal] Naming convention for Roslyn analyzer projects

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn-analyzers#347]
Today analyzers in this repo adopt various conventions/styles for things like naming/folder-structure/etc. We should agree on a consistent style for analyzers here. This thread is created for discussion and documentation on this issue.

**Comment by mavasani** [comment]
Couple of proposals for generated stub unit test files:

1. Generate stubs for helper methods for diagnostic verification - for example:
    ```c#
        private static DiagnosticResult GetCSharpResultAt(int line, int column, params string[] messageArguments)
        {
            var message = string.Format(SystemRuntimeAnalyzersResources.InitializeStaticFieldsInlineMessage, messageArguments);
            return GetCSharpResultAt(line, column, [RuleName]Analyzer.RuleId, message);
        }

        private static DiagnosticResult GetBasicResultAt(int line, int column, params string[] messageArguments)
        {
            var message = string.Format(SystemRuntimeAnalyzersResources.InitializeStaticFieldsInlineMessage, messageArguments);
            return GetBasicResultAt(line, column, [RuleName]Analyzer.RuleId, message);
        }
    ```

2. Generate at least 2 stub unit tests with naming/implementation guideline:
    ```c#
#region Unit tests for no analyzer diagnostic

        [Fact]
        public void VerifyNoDiagnostic()
        {
            VerifyCSharp(@"
<TODO: Fill in no-diagnostic code snippet>
");
            VerifyBasic(@"
<TODO: Fill in no-diagnostic code snippet>
");
        }

#end region

#region Unit tests for analyzer diagnostic(s)

        [Fact]
        public void VerifyDiagnostic()
        {
            VerifyCSharp(@"
<TODO: Fill in code snippet>
",
            GetCSharpResultAt(line:0, column:0)); // TODO: Provide correct line, column and message arguments for expected diagnostic.

            VerifyBasic(@"
<TODO: Fill in code snippet>
",
            GetBasicResultAt(line:0, column:0)); // TODO: Provide correct line, column and message arguments for expected diagnostic.
}

#end region
    ```

**Comment by genlu** [comment]
@mavasani your first proposal seems reasonable, but adding code stubs as in the second one might cause the test to fail/crash. Maybe add them as comments instead?

**Comment by genlu** [comment]
Here's the current directory structure and file naming convention for an analyzer project:
```
-- [Analyzer.Name].Analyzers
 |-- Core
   |-- [Analyzer.Name].Analyzers.csproj
   |-- [Analyzer.Name].Analyzers.nuspec
   |-- [AnalyzerName]AnalyzersResources.resx
   |-- [AnalyzerName]AnalyzersResources.Designer.cs
   |-- [RuleName].cs
   |-- [RuleName].Fixer.cs
   |-- DiagnosticCategory.cs
   |-- [Analyzer.Name].Analyzers.props
   |-- Misc. Files (install.ps1, uninsall.ps1, packages.config, etc.)
 |-- CSharp
   |-- [Analyzer.Name].CSharp.Analyzers.csproj
   |-- CSharp[RuleName].cs
   |-- CSharp[RuleName].Fixer.cs
   |-- [Analyzer.Name].CSharp.Analyzers.props
 |-- VisualBasic
   |-- [Analyzer.Name].VisualBasic.Analyzers.vbproj
   |-- Basic[RuleName].vb
   |-- Basic[RuleName].Fixer.vb
   |-- [Analyzer.Name].VisualBasic.Analyzers.props
 |-- UnitTests
   |-- [Analyzer.Name].Analyzers.UnitTests.csproj
   |-- [RuleName]Tests.cs
   |-- CSharp[RuleName]Tests.Fixer.cs
 |-- Setup
   |-- [Analyzer.Name].Analyzers.Setup.csproj
 |-- NuGet
   |-- [Analyzer.Name].Analyzers.NuGet.proj
```

**Comment by genlu** [comment]
Here's the in-code naming convention:

code struct  | naming convention
--------------- | -------------
Analyzer/CodeFix namespace |  [Analyzer.Name].Analyzers
Language-agnostic analyzer type | [RuleName]Analyzer
Language-agnostic CodeFix type | [RuleName]Fixer
CSharp analyzer type | CSharp[RuleName]Analyzer
CSharp CodeFix type | CSharp[RuleName]Fixer 
VB analyzer type| Basic[RuleName]Analyzer
VB CodeFix type | Basic[RuleName]Fixer
UnitTests namespace | [Analyzer.Name].Analyzers.UnitTests
UnitTests type for each analzyer | [RuleName]Tests
UnitTests type for each CodeFix | [RuleName]FixerTests

**Comment by sharwell** [comment]
:exclamation: Analyzers and code fixes cannot be placed in the same assembly.

**Comment by srivatsn** [comment]
Analyzers and fixers can be placed in the same assembly but the analyzer types themselves shouldn't reference anything from workspaces. We only instantiate the types that implement DiagnosticAnalyzer in the compiler and ignore everything else. All the existing analyzers we have today have both analyzers and fixers in the same assembly.

**Comment by sharwell** [comment]
@srivatsn With analyzers and fixers in the same assembly, it's basically trivial to introduce dependencies on workspaces that are impossible to detect through unit tests. This is a serious design flaw that caused a number of bugs in StyleCop.Analyzers before we finally figured out how to stop them for good. The only way to be sure the analyzers will work is to separate the assemblies. This is a case where all the existing code happens to do it wrong; we should work to correct those over time but make sure new analyzers are done correctly from the start.

**Comment by mavasani** [comment]
Done
