### ISSUE TITLE
More CA1710 (Identifiers should have correct suffix) more configurable

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/roslyn-analyzers#3476]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8

#### Diagnostic ID

CA1710: Identifiers should have correct suffix

#### Repro steps

1. Create a class `FooValidator` that inherits from `AbstractValidator<Foo>` (from the FluentValidation library)

#### Expected behavior

No warning

#### Actual behavior

CA1710: Rename `FooValidator` to end in 'Collection'

---

This is because `AbstractValidator<T>` implements `IEnumerable<IValidationRule>`, but it's not conceptually a collection. I could suppress the warning, but I have many validators, so it's not convenient.
And I'd rather not disable CA1710 globally, because it's a generally useful diagnostic.

What I'd like is to be able to disable it **only for some suffixes** (e.g. 'Collection' in this case)

**Comment by Evangelink** [comment]
With the analyzer v3+ the issue will disappear :)
The analyzer was tuned to stop reporting on indirect inheritance by default: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#exclude-indirect-base-types

Note that you could also enforce the `Validator` suffix if you want by using this (also new) option: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#additional-required-suffixes

**Comment by thomaslevesque** [comment]
@Evangelink nice, thanks! Any ETA for v3? I see that several betas have already been released

**Comment by Evangelink** [comment]
Tagging @mavasani for the ETA.

**Comment by mavasani** [comment]
Probably another week or so...

**Comment by thomaslevesque** [comment]
Great, thanks!

Closing this issue, then (unless you think the requested feature is still useful... feel free to reopen)
