### ISSUE TITLE
Port rules to IOperation API once we move to Microsoft.CodeAnalysis 1.2

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#348]
We need to look at ported FxCop rules and see if they would be better implemented as IOperation analyzers (for example, see https://github.com/dotnet/roslyn-analyzers/pull/341#discussion_r44172553).

**Comment by srivatsn** [comment]
List of rules that are currently written as Syntax analyzers:

- System.Runtime.Analyzers
  - [ ] CA2201 : DoNotRaiseReservedExceptionTypes
  - [ ] CA1820  : TestForEmptyStringsUsingStringLength
  - [ ] CA2002 : DoNotLockOnObjectsWithWeakIdentity
  - [ ] CA1309 : UseOrdinalStringComparison

- System.Runtime.InteropServices.Analyzers
  - [ ] RS0015: AlwaysConsumeTheValueReturnedByMethodsMarkedWithPreserveSigAttribute

- Microsoft.QualityGuidelines.Analyzers
  - [ ] CA1810\CA2207 : InitializeStaticFieldsInline
  - [ ] CA2200 : RethrowToPreserveStackDetails

- Desktop.Analyzers
  - [ ] CA2153: DoNotCatchCorruptedStateExceptions
  - [ ] CA5350\CA5351: DoNotUseInsecureCryptographicAlgorithms

**Comment by mavasani** [comment]
Lets do this opportunistically whenever we are touching the relevant analyzers.
