### ISSUE TITLE
Incorrect suggestion when NULL is not being validated

### ISSUE THREAD

**Issue by jaimestuardo** [dotnet/roslyn-analyzers#3503]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (latest release)

#### Diagnostic ID

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019

#### Repro steps

For example, this method:

        public static string Truncate(this string value, int maxChars)
        {
            return value.Length <= maxChars ? value : value.Substring(0, maxChars) + "...";
        }

#### Expected behavior

Not validating "value" because this is an extension method. If "value" is null, that method will never be called because a null reference exception will be thrown before.

#### Actual behavior

Currently, this warning is shown:

"validate that the parameter "value" is not NULL before using it"

**Comment by mysteryx93** [comment]
Actually, the extension method will still be called on a null object (I just learnt this)
https://stackoverflow.com/questions/5459427/why-allow-extension-methods-on-null-objects

**Comment by mavasani** [comment]
Yes, this is by design. If you'd like to exclude extension method 'this' parameter validation from CA1062, please use the following editorconfig option: https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#exclude-extension-method-this-parameter
