### ISSUE TITLE
CA1062 on List Validated by Helper Method and Accessed with For Each

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/roslyn-analyzers#3505]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (latest release)

#### Diagnostic ID

Example: [CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019)

#### Repro steps

I've created helper methods to validate parameters as such

    /// <summary>
    /// Provides helper methods to validate parameters.
    /// </summary>
    internal static class ArgHelper
    {
        /// <summary>
        /// Validates whether specific value is not null, and throws an exception if it is null.
        /// </summary>
        /// <param name="value">The value to validate.</param>
        /// <param name="name">The name of the parameter.</param>
        internal static void ValidateNotNull(object value, string name)
        {
            if (value == null)
            {
                throw new ArgumentNullException(name);
            }
        }

        /// <summary>
        /// Validates whether specific value is not null or empty, and throws an exception if it is null or empty.
        /// </summary>
        /// <param name="value">The value to validate.</param>
        /// <param name="name">The name of the parameter.</param>
        internal static void ValidateNotNullOrEmpty(string value, string name)
        {
            ValidateNotNull(value, name);
            if (string.IsNullOrEmpty(value))
            {
                ThrowArgumentNullOrEmpty(name);
            }
        }

        /// <summary>
        /// Validates whether specific listt is not null or empty, and throws an exception if it is null or empty.
        /// </summary>
        /// <param name="value">The value to validate.</param>
        /// <param name="name">The name of the parameter.</param>
        internal static void ValidateListNotNullOrEmpty<T>(IEnumerable<T> value, string name)
        {
            ValidateNotNull(value, name);
            if (!value.Any())
            {
                ThrowArgumentNullOrEmpty(name);
            }
        }

        /// <summary>
        /// Throws an exception of type ArgumentException saying an argument is null or empty.
        /// </summary>
        /// <param name="name">The name of the parameter.</param>
        internal static void ThrowArgumentNullOrEmpty(string name)
        {
            throw new ArgumentException(string.Format(CultureInfo.InvariantCulture, Resources.VideoFileAndAudioFileNull, name), name);
        }
    }

For string values, it's working fine, but when I'm having CA1062 when
1. Using a list
2. Validating in a sub-method (calling ValidateNotNull directly solves it, although it is called within ValidateListNotNullOrEmpty)
3. Using For Each (I get no error on "files.Count()")

Here's a method that causes CA1062; uncommenting ValidateNotNull removes the warning.

    public void TestMethod(IEnumerable<string> files)
    {
        // ArgHelper.ValidateNotNull(files, nameof(files));
        ArgHelper.ValidateListNotNullOrEmpty(files, nameof(files));

        var a = files.Count();
        foreach (string item in files)
        {
        }
    }

#### Expected behavior

There should be no warning.

#### Actual behavior

It throws CA1062

**Comment by mysteryx93** [comment]
Now I've created this method

    public static class Preconditions
    {
        /// <summary>
        /// Validates whether specific value is not null, and throws an exception if it is null.
        /// </summary>
        /// <param name="value">The value to validate.</param>
        /// <param name="name">The name of the parameter.</param>
        public static T CheckNotNull<T>(T value, string name)
        {
            if (value == null)
            {
                throw new ArgumentNullException(name);
            }
            return value;
        }
    }

If this helper class is located in a different project, then it raises CA1062; but if it's located within the same project, then is no warning. I don't think the location of the helper class should matter.

**Comment by mavasani** [comment]
> If this helper class is located in a different project, then it raises CA1062; but if it's located within the same project, then there is no warning. I don't think the location of the helper class should matter.

This is by design. The analyzer cannot perform analysis across assemblies. Please use the following configuration option to mark your null-check validation method: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062?view=vs-2019#null-check-validation-methods
