### ISSUE TITLE
Should CA1305 detect invariant formats and not trigger?

### ISSUE THREAD

**Issue by Bouke** [dotnet/roslyn-analyzers#3507]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (latest release)

#### Diagnostic ID

Example: [CA1305](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1305?view=vs-2017#when-to-suppress-warnings)

#### Repro steps

`DateTimeOffset.Now.ToString("o")`

#### Expected behavior

CA1305 should not warn as "o" isn't culture specific:

> Because the "O" or "o" standard format specifier conforms to an international standard, the formatting or parsing operation that uses the specifier always uses the invariant culture and the Gregorian calendar.

#### Actual behavior

CA1305 is triggered and the suppression suggestion applies:

> It is safe to suppress a warning from this rule when it is certain that the default format is the correct choice, and where code maintainability is not an important development priority.

#### See also
This was previously also reported in https://github.com/dotnet/roslyn-analyzers/issues/1949, however the possibility of just _not triggering_ wasn't discussed. Instead of blindly adding `CultureInfo.InvariantCulture` everywhere or when suppressing false positives becomes the norm, the analyzer's added value decreases.

**Comment by Evangelink** [comment]
It makes sense to me. The docs are not 

| Method | Invariant format | Doc |
|--------|------------------|-----|
| DateTime.ToString | o, O, r, R, s, u | [standard-date-and-time-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) |
| DateTimeOffset.ToString | o, O, r, R, s, u | [standard-date-and-time-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) |
| TimeSpan.ToString | c | [standard-timespan-format-strings](https://docs.microsoft.comdotnet/standard/base-types/standard-timespan-format-strings) |

Is it right? Am I missing something?

@mavasani Could you confirm you are fine with this modification?

**Comment by mavasani** [comment]
Sounds good to me. Tagging @stephentoub @bartonjs in case they see any issues in implementing this suggestion.

**Comment by bartonjs** [comment]
It seems like a reasonable change to me, as well.
