### ISSUE TITLE
CA1308 when explicitely using ToLowerInvariant

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/roslyn-analyzers#3519]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (latest release)

#### Diagnostic ID

Example: [CA1308](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1308?view=vs-2019)

#### Repro steps

    public static string FileWithExt(string file, string ext) => file + "." + ext.ToLowerInvariant();

#### Expected behavior

I explicitly want lowercase file extensions, everything is good.

#### Actual behavior

CA1308, replace ToLowerInvariant with ToUpperInvariant

In cases where I want to compare two values, this make sense -- but when I specifically want lowercase, it shouldn't complain.

**Comment by Evangelink** [comment]
@mysteryx93 I understand your comment but I am not sure how we could tune the rule to actually detect such case.

**Comment by mavasani** [comment]
Yes, this is by design.

1. You should add an in-source suppression with a justification comment at each place you want to explicitly use `ToLowerInvariant` OR
2. You should disable this rule for your project if you are not concerned about this potential globalization issue.
