### ISSUE TITLE
New rule proposal: Detect duplicated strings

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3524]
Detect all string literals not assigned to a constant and report on duplicated ones. I suggest to limit the lookup at the project level but we could think of having an extension to limit at the class/file-level.

**Comment by Evangelink** [comment]
@mavasani Could you confirm you are fine with this rule?

**Comment by drewnoakes** [comment]
@Evangelink what would the benefit be of such a rule? Tidiness?

From a performance standpoint there's no gain: https://sharplab.io/#v2:EYLgdgpgLgZgHgGiiATgVzAHwAICYCMAsAFB4DMABAN4kV0UDGA9mAM5QXb4AMFAyvgoBeCgCIAlmCgQUkACaiA3LXrM2HLrz65hYydNkQFy4vU74AbOa2UREqTPlKVdLlZQQAhnJYAbAJ7W/AAsuvYGTiZmLpy4OjSmZvRcAJwAFABKEDAyEGAMEACiAI5onr6saQII/LgAlHVRSa746Vk5HvlFpeWV1fxkDU3NqZnZuV0lZRVV+DV8wUMxZqPtEwVTvbM14Y5GokuJI61jHXkbPTP9mgB0AJIOsmmidwByACqFGa+FACKiN3eTAAMkwAO4yB4AN08KHEnikaQahzMAF8SKigA=

Also, making strings `const` means that changes in another library are only picked up if the consumer is recompiled, as such strings are copied into the consumer's compilation output. For some kinds of strings, `static readonly` is a better fit.

**Comment by Evangelink** [comment]
@drewnoakes I am pretty sure that I read an article a couple of years ago that was stating that not all strings were interned and so it was better to use `const` or `static readonly` but maybe this is wrong.

**Comment by Evangelink** [comment]
I cannot find it back so maybe I got confused and read it for another tech stack or I don't know...
