### ISSUE TITLE
Ideas for resources (resx) analyzers

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3525]
Add a new analyzer for roslyn-analyzers that will check for resources keys and values.

## Rules for keys

1. Key should end with `Title`, `Message`, `Description` or `CodeFixTitle`.

## Rules for values

1. If the value is linked to a title or message key, then it shouldn't end with a period '.'.

2. If the value is linked to a description, it should end with a period '.'.

3. Placeholders should be surrounded with single-quotes.

Tagging @mavasani for other ideas.

**Comment by Evangelink** [comment]
Regarding keys, for rules with different messages, the current pattern is `MessageSomeText` and `MessageSomeOtherText`, could we use something else that would make it easier to have an automated detection? Like `Message_SomeText` or `SomeTextMessage`?

The analyzer could also be checking for `[Something]` or `[SomethingAttribute]` and report on it as this is a C# syntax.

**Comment by mavasani** [comment]
@Evangelink - do you think the rule for keys would be possibly to enforce? I do foresee resource strings outside these 4 buckets? The core concern for me is that it would not be possible to add a source suppression for these cases as it is defined in a resx file.

**Comment by mavasani** [comment]
@Evangelink - I'd say lets start with the analyzer that enforces what you suggested for rule values for now.

**Comment by Evangelink** [comment]
@mavasani What about reporting on calling site instead of resource definition?

**Comment by mavasani** [comment]
> What about reporting on calling site instead of resource definition?

Ah, that seems to be a good idea :) Please do add a good description, and if possible a code fix. I am presuming you would anyways need such an analyzer to require the resx file passed in as an additional file so you can have code fixes that automatically fix the issue instead of manual fixes.

**Comment by mavasani** [comment]
@Evangelink Feel free to get started here. Note that analysis of resx files is a pretty desired bucket of rules. For example, finding duplicate resx strings, flagging unused resx strings, etc. would be super helpful as well.

**Comment by Evangelink** [comment]
@mavasani It'd be nice if we could define the next steps for this analyzer, it seems to be pretty important.

**Comment by mavasani** [comment]
Yeah, hoping to get to it this week...
