### ISSUE TITLE
Add unit tests for RS0015 analyzer

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn-analyzers#353]

**Comment by tmeschter** [comment]
@genlu Which one is RS0015?

**Comment by genlu** [comment]
It’s under Roslyn Diagnostics.

RS0015: Always consume the value returned by methods marked with PreserveSigAttribute
PreserveSigAttribute indicates that a method will return an HRESULT, rather than throwing an exception. Therefore, it is important to consume the HRESULT returned by the method, so that errors can be detected. Generally, this is done by calling Marshal.ThrowExceptionForHR.
Category: Reliability
Severity: Warning

**Comment by srivatsn** [comment]
Part of #701
