### ISSUE TITLE
CA1822 triggers on default ASP.NET Core API project

### ISSUE THREAD

**Issue by rickardp** [dotnet/roslyn-analyzers#3546]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (latest release)

#### Repro steps

1. Create new ASP.Net web application
2. Add package reference to analyzer (Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Expected behavior

No analyzer warnings

#### Actual behavior

 CA1822 (Member ConfigureServices does not access instance data and can be marked as static) and (CA1822: Member Configure does not access instance data and can be marked as static) on the unmodified project

On the controller
warning CA1822: Member Get does not access instance data and can be marked as static

These are false warnings as they follow an implicit contract mandated by ASP.NET.

For these analyzers to be useful, I think they need to consider e.g. [HttpGet] attribute and also the class sent to hostBuilder.UseStartup<>.

**Comment by Evangelink** [comment]
Relates to #3835

**Comment by Evangelink** [comment]
Fixed by #3875
