### ISSUE TITLE
New CA security rules missing documentation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3548]
Identified from https://github.com/dotnet/roslyn-analyzers/pull/3539/files#diff-f2ad3dd91a83a8b48ef9f29ed318ac8f, following security rules need to add documentation at https://docs.microsoft.com/visualstudio/code-quality:

- [x] CA5359 | https://docs.microsoft.com/visualstudio/code-quality/ca5359 | Do Not Disable Certificate Validation |
- [x] CA5360 | https://docs.microsoft.com/visualstudio/code-quality/ca5360 | Do Not Call Dangerous Methods In Deserialization |
- [x] CA5362 | https://docs.microsoft.com/visualstudio/code-quality/ca5362 | Do Not Refer Self In Serializable Class |
- [x] CA5365 | https://docs.microsoft.com/visualstudio/code-quality/ca5365 | Do Not Disable HTTP Header Checking |
- [x] CA5366 | https://docs.microsoft.com/visualstudio/code-quality/ca5366 | Use XmlReader For DataSet Read Xml |
- [x] CA5367 | https://docs.microsoft.com/visualstudio/code-quality/ca5367 | Do Not Serialize Types With Pointer Fields |
- [x] CA5368 | https://docs.microsoft.com/visualstudio/code-quality/ca5368 | Set ViewStateUserKey For Classes Derived From Page |
- [x] CA5374 | https://docs.microsoft.com/visualstudio/code-quality/ca5374 | Do Not Use XslTransform |
- [x] CA5375 | https://docs.microsoft.com/visualstudio/code-quality/ca5375 | Do Not Use Account Shared Access Signature |
- [x] CA5376 | https://docs.microsoft.com/visualstudio/code-quality/ca5376 | Use SharedAccessProtocol HttpsOnly |
- [x] CA5377 | https://docs.microsoft.com/visualstudio/code-quality/ca5377 | Use Container Level Access Policy |
- [x] CA5379 | https://docs.microsoft.com/visualstudio/code-quality/ca5379 | Do Not Use Weak Key Derivation Function Algorithm |
- [x] CA5382 | https://docs.microsoft.com/visualstudio/code-quality/ca5382 | Use Secure Cookies In ASP.Net Core |
- [x] CA5383 | https://docs.microsoft.com/visualstudio/code-quality/ca5383 | Ensure Use Secure Cookies In ASP.Net Core |
- [x] CA5384 | https://docs.microsoft.com/visualstudio/code-quality/ca5384 | Do Not Use Digital Signature Algorithm (DSA) |
- [x] CA5385 | https://docs.microsoft.com/visualstudio/code-quality/ca5385 | Use Rivest–Shamir–Adleman (RSA) Algorithm With Sufficient Key Size |
- [x] CA5387 | https://docs.microsoft.com/visualstudio/code-quality/ca5387 | Do Not Use Weak Key Derivation Function With Insufficient Iteration Count |
- [x] CA5388 | https://docs.microsoft.com/visualstudio/code-quality/ca5388 | Ensure Sufficient Iteration Count When Using Weak Key Derivation Function |
- [x] CA5390 | https://docs.microsoft.com/visualstudio/code-quality/ca5390 | Do not hard-code encryption key |
- [x] CA5391 | https://docs.microsoft.com/visualstudio/code-quality/ca5391 | Use antiforgery tokens in ASP.NET Core MVC controllers |
- [x] CA5392 | https://docs.microsoft.com/visualstudio/code-quality/ca5392 | Use DefaultDllImportSearchPaths attribute for P/Invokes |
- [x] CA5393 | https://docs.microsoft.com/visualstudio/code-quality/ca5393 | Do not use unsafe DllImportSearchPath value |
- [x] CA5394 | https://docs.microsoft.com/visualstudio/code-quality/ca5394 | Do not use insecure randomness |
- [x] CA5395 | https://docs.microsoft.com/visualstudio/code-quality/ca5395 | Miss HttpVerb attribute for action methods |
- [x] CA5396 | https://docs.microsoft.com/visualstudio/code-quality/ca5396 | Set HttpOnly to true for HttpCookie |
- [x] CA5399 | https://docs.microsoft.com/visualstudio/code-quality/ca5399 | HttpClients should enable certificate revocation list checks |
- [x] CA5400 | https://docs.microsoft.com/visualstudio/code-quality/ca5400 | Ensure HttpClient certificate revocation list check is not disabled |
- [x] CA5401 | https://docs.microsoft.com/visualstudio/code-quality/ca5401 | Do not use CreateEncryptor with non-default IV |
- [x] CA5402 | https://docs.microsoft.com/visualstudio/code-quality/ca5402 | Use CreateEncryptor with the default IV  |

**Comment by dotpaul** [comment]
Thank you for the docs, @LLLXXXCCC !

**Comment by mavasani** [comment]
Thanks a lot @LLLXXXCCC - really appreciate completing this one!!
