### ISSUE TITLE
New .NET5 analyzer CA rules missing documentation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3549]
Identified from https://github.com/dotnet/roslyn-analyzers/pull/3539/files#diff-f2ad3dd91a83a8b48ef9f29ed318ac8f, following .NET5 analyzer rules added by the runtime team need to add documentation at https://docs.microsoft.com/visualstudio/code-quality:

- [ ] CA1830 | https://docs.microsoft.com/visualstudio/code-quality/ca1830 | Prefer strongly-typed Append and Insert method overloads on StringBuilder. |
- [ ] CA1831 | https://docs.microsoft.com/visualstudio/code-quality/ca1831 | Use AsSpan or AsMemory instead of Range-based indexers when appropriate |
- [ ] CA1832 | https://docs.microsoft.com/visualstudio/code-quality/ca1832 | Use AsSpan or AsMemory instead of Range-based indexers when appropriate |
- [ ] CA1833 | https://docs.microsoft.com/visualstudio/code-quality/ca1833 | Use AsSpan or AsMemory instead of Range-based indexers when appropriate |
- [ ] CA1834 | https://docs.microsoft.com/visualstudio/code-quality/ca1834 | Consider using 'StringBuilder.Append(char)' when applicable. |
- [ ] CA2008 | https://docs.microsoft.com/visualstudio/code-quality/ca2008 | Do not create tasks without passing a TaskScheduler |
- [ ] CA2012 | https://docs.microsoft.com/visualstudio/code-quality/ca2012 | Use ValueTasks correctly |
- [ ] CA2013 | https://docs.microsoft.com/visualstudio/code-quality/ca2013 | Do not use ReferenceEquals with value types |
- [ ] CA2014 | https://docs.microsoft.com/visualstudio/code-quality/ca2014 | Do not use stackalloc in loops. |
- [ ] CA2015 | https://docs.microsoft.com/visualstudio/code-quality/ca2015 | Do not define finalizers for types derived from MemoryManager<T> |
- [ ] CA2247 | https://docs.microsoft.com/visualstudio/code-quality/ca2247 | Argument passed to TaskCompletionSource constructor should be TaskCreationOptions enum instead of TaskContinuationOptions enum. |

**Comment by Evangelink** [comment]
@mavasani All docs you were mentioning have been handled.
