### ISSUE TITLE
New CA rules needing documentation

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3550]
_**Excluded the security rules (#3548) and rules added by runtime team (#3549)**_

Identified from https://github.com/dotnet/roslyn-analyzers/pull/3539/files#diff-f2ad3dd91a83a8b48ef9f29ed318ac8f, following analyzer rules need to add documentation at https://docs.microsoft.com/visualstudio/code-quality:

- [x] CA1066 | https://docs.microsoft.com/visualstudio/code-quality/ca1066 | Type {0} should implement IEquatable<T> because it overrides Equals |
- [x] CA1067 | https://docs.microsoft.com/visualstudio/code-quality/ca1067 | Override Object.Equals(object) when implementing IEquatable<T> |
- [x] CA1069 | https://docs.microsoft.com/visualstudio/code-quality/ca1069 | Enums values should not be duplicated |
- [x] CA1070 | https://docs.microsoft.com/visualstudio/code-quality/ca1070 | Do not declare event fields as virtual |
- [x] CA1508 | https://docs.microsoft.com/visualstudio/code-quality/ca1508 | Avoid dead conditional code |
- [x] CA1509 | https://docs.microsoft.com/visualstudio/code-quality/ca1509 | Invalid entry in code metrics rule specification file |
- [x] CA1826 | https://docs.microsoft.com/visualstudio/code-quality/ca1826 | Do not use Enumerable methods on indexable collections. Instead use the collection directly |
- [x] CA1827 | https://docs.microsoft.com/visualstudio/code-quality/ca1827 | Do not use Count() or LongCount() when Any() can be used |
- [x] CA1828 | https://docs.microsoft.com/visualstudio/code-quality/ca1828 | Do not use CountAsync() or LongCountAsync() when AnyAsync() can be used |
- [x] CA1829 | https://docs.microsoft.com/visualstudio/code-quality/ca1829 | Use Length/Count property instead of Count() when available |
- [x] CA2009 | https://docs.microsoft.com/visualstudio/code-quality/ca2009 | Do not call ToImmutableCollection on an ImmutableCollection value |
- [x] ~~CA2010 | https://docs.microsoft.com/visualstudio/code-quality/ca2010 | Always consume the value returned by methods marked with PreserveSigAttribute |~~ See https://github.com/dotnet/roslyn-analyzers/pull/3581
- [x] CA2011 | https://docs.microsoft.com/visualstudio/code-quality/ca2011 | Avoid infinite recursion |
- [x] CA2244 | https://docs.microsoft.com/visualstudio/code-quality/ca2244 | Do not duplicate indexed element initializations |
- [x] CA2245 | https://docs.microsoft.com/visualstudio/code-quality/ca2245 | Do not assign a property to itself. |
- [x] CA2246 | https://docs.microsoft.com/visualstudio/code-quality/ca2246 | Assigning symbol and its member in the same statement. |

**Comment by mavasani** [comment]
@Evangelink Would you be able to add documentation for the rules that you have recently contributed or are in process of contributing? I can take up documenting the rest of the rules from above..

**Comment by Evangelink** [comment]
Now that's a big list! Yeah sure I'll try to help you!

**Comment by mavasani** [comment]
@Evangelink Would you be able to create doc PRs for `CA1069` and `CA1070`? You can look at https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6459 and https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6468 for examples.

**Comment by Evangelink** [comment]
@mavasani The 2 PRs links are broken.

**Comment by mavasani** [comment]
Ah, @Evangelink that is because those are PRs to the internal docs repos, which needs MSFT permissions. You can search for the `ruleid.md` docs at https://github.com/MicrosoftDocs/visualstudio-docs/tree/master/docs/code-quality for the ones that are checked in the issue description. These are the ones that got added in the internal repo and then merged back to public docs repo.

**Comment by mavasani** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1066.md
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1067.md

**Comment by mavasani** [comment]
Your PR would also need to update a few tables. For example: https://github.com/MicrosoftDocs/visualstudio-docs/search?q=CA1066&unscoped_q=CA1066

**Comment by mavasani** [comment]
@Evangelink The only 2 remaining rules are CA1069 and CA1070. I am going to take these up and finish this work item.

**Comment by mavasani** [comment]
All rules have docs or open PRs to add doc.
