### ISSUE TITLE
DoNotCopyValue class has CS8600 warnings

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3558]
![image](https://user-images.githubusercontent.com/11340282/80386473-b709a500-88a7-11ea-88e7-057e7881df23.png)

**Comment by mavasani** [comment]
@sharwell

**Comment by sharwell** [comment]
@Evangelink Those results would appear if you build with an old version of the compiler. It should not occur with 16.5 and newer.

**Comment by Evangelink** [comment]
I have Microsoft Visual Studio Community 2019 Version 16.5.4

**Comment by Evangelink** [comment]
@sharwell Is there anything I can do/check?

**Comment by sharwell** [comment]
I'll compare the results I get with `#error version` in IDE and command line builds.

**Comment by sharwell** [comment]
@Evangelink the new handling of `var` was introduced in 16.6 Preview 1. You'll want to update to that version or newer.

**Comment by sharwell** [comment]
Fixed by setting the compiler version in the build
