### ISSUE TITLE
CA1506 how to have the list of coupled types

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3559]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0-beta3.final (latest pre-release)

#### Diagnostic ID

Example: [CA1506](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1506)

#### Question

How can I get the list of types that are counted as coupled to my current type? I suspect there might be something wrong but I cannot see which types count as coupled.

**Comment by Evangelink** [comment]
If it's not possible to have this list, is it ok to update the rule description to list the types? This would help without hurting rule readability as this is only in the description section.

**Comment by mavasani** [comment]
This is possible via the core code metrics computation APIs: https://github.com/dotnet/roslyn-analyzers/blob/2763ec7c3d235319e15c3d5d9db111e1715f9be4/src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/CodeMetricsComputationTests.cs#L342

We can probably add a new command line argument to Metrics.exe to extend the below method to output coupled types: https://github.com/dotnet/roslyn-analyzers/blob/2763ec7c3d235319e15c3d5d9db111e1715f9be4/src/Tools/Metrics/MetricsOutputWriter.cs#L94

Add new switch here: https://github.com/dotnet/roslyn-analyzers/blob/2763ec7c3d235319e15c3d5d9db111e1715f9be4/src/Tools/Metrics/Program.cs#L75

**Comment by ViRuSTriNiTy** [comment]
Issue is marked as answered but I wonder what is the actual answer is here?
