### ISSUE TITLE
Update message for DoNotInvokeDiagnosticDescriptorDescription

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3560]
We shouldn't change this (or at least not in this PR), the code is taking care of adding the space + wrapping in single quotes when needed: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/DoNotInvokeDiagnosticDescriptor.cs#L64

_Originally posted by @Evangelink in https://github.com/dotnet/roslyn-analyzers/pull/3543_

**Comment by Evangelink** [comment]
@mavasani Is it ok to rewrite this using 2 descriptors? Basically there are 2 cases, one where the parent is a `TMemberAccessExpressionSyntax` and one where it isn't.

**Comment by mavasani** [comment]
Yes, that sounds correct. We'll need 2 descriptors with all identical arguments passed to its constructor, except the message string.

**Comment by Evangelink** [comment]
@mavasani Looking at the implementation, I think the rule is a legacy that is unused. There is no test and the rule ID is weird.

**Comment by mavasani** [comment]
@Evangelink This rule was probably written very long ago when we wrote analyzers without tests and never got to writing tests for it :-) haha!! I think this rule was written primarily for Roslyn compiler project, to ensure we don't accidentally realize a constructor. Let me check if it is used/enabled in Roslyn. Otherwise, we may be able to delete it.

**Comment by mavasani** [comment]
Indeed, it is still being used: https://github.com/dotnet/roslyn/blob/d7e493956ffcbf0e932097f6f3e1fa3fa1699087/src/Compilers/CSharp/CSharpCodeAnalysisRules.ruleset#L6

**Comment by mavasani** [comment]
I guess, we need to actually write tests for this analyzer then!

**Comment by Evangelink** [comment]
Interesting! It's probably worth rewriting as operation analyzer too.

**Comment by Evangelink** [comment]
@mavasani I was having a look at this rule and I noticed something strange, we create a diagnostic but we never report it: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/DoNotInvokeDiagnosticDescriptor.cs#L67

I am not sure whether you want this rule to be fixed or if we should delete it? In its current state it's a cpu/ram/time waste.

**Comment by mavasani** [comment]
Yeah, lets delete the rule for now.

> BTW the Diagnostic type looks like a good candidate for the rule on which we should not ignore the return type. WDYT?

Lets open a separate issue. I don't think our repo has moved to the 3.3.x package that needs your change to CA1806 to allow specifying custom user methods.

**Comment by Evangelink** [comment]
The rule description seems to indicate this rule might be important for performance reasons when building an analyzer, isn't it better to have it raise instead? Sorry not to have looked at the description message before.

**Comment by mavasani** [comment]
@Evangelink The rule was only meant to be enabled in Roslyn C# and VB compiler layer, it is not a general rule for all analyzers. Any case - there are no tests, so valid places that will break by removing it as it never reported a diagnostic. I think deleting the rule for now seems reasonable.

**Comment by Evangelink** [comment]
PR #3571 reopen
