### ISSUE TITLE
Update yaml files in repo

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3562]
I think we will want to publish the packages to [`dotnet5`](https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet5) feed, where .NET is publishing product packages. 

If so, let's add this line to README.md and let's update our pipeline to do standard Arcade publishing.

```
Pre-release builds are available from Azure DevOps public feed: 
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json ([browse](https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet5)).
```

To update the pipeline  replace https://github.com/dotnet/roslyn-analyzers/blob/master/azure-pipelines.yml#L11-L78 with https://github.com/dotnet/symreader/blob/master/azure-pipelines.yml#L20-L111 (replace MacOS with Spanish Windows). Add https://github.com/dotnet/symreader/blob/master/azure-pipelines.yml#L138-L143 at the end of the YAML.

Once this is done and merged we will need to setup darc subscription.

There is actually more work to be done: it doesn't seem we are currently mirroring this repo to dnceng internal. We need to do that and set up a new official build there.
We'll also want automatic Arcade updates.

_Originally posted by @tmat in https://github.com/dotnet/roslyn-analyzers/pull/3536#issuecomment-620104227_

**Comment by jmarolf** [comment]
fixed in https://github.com/dotnet/roslyn-analyzers/pull/3619
