### ISSUE TITLE
New analyzer: Use value before assigning it

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3567]
The idea behind this analyzer is to ensure that a value is read/used before being re-assigned to something else. Maybe we would want this rule to target only arguments/parameters to avoid change in a side-effect call.

```csharp
public class C
{
	public void M(int i)
	{
		i = 2; // Diagnostic - value isn't used/read before being reassigned
		i = i + 2; // ok
	}

	public void M()
	{
		var x = GetSomething();
		x = 42; // Diagnostic
	}
}
```

**Comment by mavasani** [comment]
@Evangelink This diagnostic is already implemented in VS IDE as IDE0059, which is now also available for build enforcement in https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.CodeStyle
