### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bidolah** [dotnet/roslyn-analyzers#3585]
Not sure that it's the correct place for this issue. 

FxCop 3.0 support Visual Studio 2019 or later, but we need to change information for Visual Studio 2017 because it does not support FxCop 3.0

![image](https://user-images.githubusercontent.com/9832538/80698195-caed1b00-8ae2-11ea-99ad-3cf02d2c2870.png)

https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019

**Comment by mavasani** [comment]
Thanks- you can actually file issues on the documentation page itself and a PR contributing the fix to the Docs repo would be even better.
