### ISSUE TITLE
"Project Site" link on NuGet.org points to wrong site.

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn-analyzers#359]
For example, the "Project Site" link on https://www.nuget.org/packages/System.Runtime.InteropServices.Analyzers/ points to http://msdn.com/roslyn, which redirects to http://github.com/dotnet/roslyn.

We should be directing users back to http://github.com/dotnet/roslyn-analyzers instead.

**Comment by lgolding** [comment]
@tmeschter Hi Tom, this is assigned to me. I don't know anything about how to get the necessary privilege to update the page, or how to do it once I have the privilege. Can you point me to the necessary info? Thanks, Larry

**Comment by srivatsn** [comment]
The page gets that information from the package itself and I think [this line in our targets file](https://github.com/dotnet/roslyn-analyzers/blob/master/build/Targets/Analyzers.NuGet.Settings.targets#L8) needs to change.

**Comment by lgolding** [comment]
Y'know, I searched the string `http://msdn.com/roslyn` in VS and got no matches. It does a poor job of searching in project files. Thanks.
