### ISSUE TITLE
RS0036 and RS0041 for constructor with inner class parameter

### ISSUE THREAD

**Issue by kevinoid** [dotnet/roslyn-analyzers#3596]
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers)

#### Package Version

v3.0.0 (Latest)

<details>
<summary><code>dotnet --info</code></summary>

    .NET Core SDK (reflecting any global.json):
     Version:   3.1.201
     Commit:    b1768b4ae7
    
    Runtime Environment:
     OS Name:     debian
     OS Version:  
     OS Platform: Linux
     RID:         debian-x64
     Base Path:   /usr/share/dotnet/sdk/3.1.201/
    
    Host (useful for support):
      Version: 3.1.3
      Commit:  4a9f85e9f8
    
    .NET Core SDKs installed:
      3.1.201 [/usr/share/dotnet/sdk]
    
    .NET Core runtimes installed:
      Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
    
    To install additional .NET Core runtimes or SDKs:
      https://aka.ms/dotnet-download

</details>

#### Diagnostic ID

[RS0036](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md)
[RS0041](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md)

#### Repro steps

1. In an empty directory, create the following files:
    `Class1.cs`:
    ```csharp
    public class Class1
    {
        protected Class1(Builder builder)
        {
        }
    
        public class Builder
        {
        }
    }
    ```
    `PublicAPI.Shipped.txt`:

        #nullable enable

    `PublicAPI.Unshipped.txt`:

        #nullable enable
        Class1
        Class1.Builder
        Class1.Builder.Builder() -> void
        Class1.Class1(Class1.Builder! builder) -> void

    `Example.csproj`:
    ```xml
    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
      </PropertyGroup>
    
      <ItemGroup>
        <AdditionalFiles Include="PublicAPI.Shipped.txt" />
        <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
      </ItemGroup>
    
      <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.0.0">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
      </ItemGroup>
    
    </Project>
    ```
2. `dotnet build`

#### Expected behavior

Build completes successfully without warnings.

#### Actual behavior

Build produces the following warnings:

    Class1.cs(3,15): warning RS0041: Symbol 'Class1' uses some oblivious reference types. [/tmp/example/Example/Example.csproj]
    Class1.cs(3,15): warning RS0036: Symbol 'Class1' is missing nullability annotations in the declared API. [/tmp/example/Example/Example.csproj]

Since nullable reference types are enabled, I assume all reference types are non-nullable rather than oblivious.  If `Builder` is moved out of `Class1` and `PublicAPI.Unshipped.txt` updated appropriately, the error disappears, which supports this assumption.

Any thoughts?

Thanks,
Kevin

**Comment by mavasani** [comment]
@jcouv for guidance

**Comment by jcouv** [comment]
@kevinoid @mavasani 
Yes, this is a known issue with that version of the publicAPI analyzer, which relates to nested types. I repro'ed with the sample project your provided, and then updated the analyzer package reference to `3.3.0-beta1.final` and that fixed the problem.
I'll go ahead and close a fixed. Please let us know if you run into any more problems. Thanks

**Comment by kevinoid** [comment]
Thanks @jcouv.  I can confrm that `3.3.0-beta1.final` fixes the issue for me.

**Comment by AArnott** [comment]
Even after picking up the fix, there's a problem:

The problematic entries are flagged as missing from the PublicAPI.txt files, even though they are in the PublicAPI.Shipped.txt file:

```
~static Microsoft.VisualStudio.VisualStudioServices.VS2019_4.get -> Microsoft.VisualStudio.VisualStudioServices.VS2019_4Services!
~static Microsoft.VisualStudio.VisualStudioServices.VS2019_5.get -> Microsoft.VisualStudio.VisualStudioServices.VS2019_5Services!
~static Microsoft.VisualStudio.VisualStudioServices.VS2019_6.get -> Microsoft.VisualStudio.VisualStudioServices.VS2019_6Services!
```

When I apply the code fix to 'add' them (even though they're already there) new ones are added by the code fixer to the PublicAPI.Unshipped.txt file:

```
static Microsoft.VisualStudio.VisualStudioServices.VS2019_4.get -> Microsoft.VisualStudio.VisualStudioServices.VS2019_4Services!
static Microsoft.VisualStudio.VisualStudioServices.VS2019_5.get -> Microsoft.VisualStudio.VisualStudioServices.VS2019_5Services!
static Microsoft.VisualStudio.VisualStudioServices.VS2019_6.get -> Microsoft.VisualStudio.VisualStudioServices.VS2019_6Services!
```

But the original ones are left behind!

**Comment by mavasani** [comment]
Tagging @jcouv

**Comment by AArnott** [comment]
Another VS2019_7 member was in Unshipped that started with `~` (due to the original bug) and the code fixer similarly added a *new* VS2019_7 entry right next to it in the same file, that simply lacked the tilde.

What I expect is that instead of adding new entries, the code fix removes the tilde on the existing entries.
Manually correcting this works: the analyzer is satisfied. So it seems to just be a bug in the code fixer.

**Comment by AArnott** [comment]
This isn't just about removing tildes. It seems that *any* change to NRT annotations results in a *new* line being added to PublicAPI.Unshipped.txt instead of the existing entry being updated.

**Comment by mavasani** [comment]
@jcouv Would you prefer to re-open this issue or prefer if @AArnott opens a separate one for fixing the code fixer?

**Comment by jcouv** [comment]
Please open a separate issue so that I don't get mixed up between scenarios.

But just to clarify, while a change from oblivious to annotated/not-annotated can be done in-place, a change from annotated/not-annotated to some different annotations is intentionally treated as an API change (addition and removal, just like changing a type).

**Comment by AArnott** [comment]
Thanks. There was no removal. It just added a near duplicate. I'll open a new issue.

**Comment by AArnott** [comment]
Well, I can't reproduce it in a simple repo. So never mind. Thanks.
