### ISSUE TITLE
New Analyzer: Warn when calling Enumerable.Cast<T>/OfType<T> with incompatible types

### ISSUE THREAD

**Issue by fowl2** [dotnet/roslyn-analyzers#3608]
The following will always throw an `InvalidCastException` at runtime:

`new int[] { 1 }.Cast<string>().ToList();`
`new float[] { 1f }.Cast<double>().ToList();`
`new int[] { 1 }.Cast<long>().ToList();`

Perhaps worse, this will return an enumerable that fully enumerates the source and then returns *no items silently*:

`enumerableOfApple.OfType<Orange>()`

Both of these situations are likely to be a mistake.

I'd never played with Roslyn before but I thought it'd be fun so I [hacked together something](https://github.com/fowl2/roslyn-analyzers/blob/EnumerableCasts/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotCallEnumerableCastThatWillFailAnalyzer.cs). The rules seem quite complex so I have no confidence I got it right - or even if it's possible to spot 100% of cases - but it seems to be able to pick up the most obvious problems and I think that's still valuable. 

Also, naming things and writing descriptive messages is really hard 😅.

An interesting thing I learnt was that enums can be cast to/from their underlying type and to other enums with the same underlying type this way, but numeric types can't be. I guess the numeric type conversions must be a language thing and so the compiled `Cast<T>()` can't know them.

Anyway I hope this is useful, even just for the idea.

Thanks

PS. It's amazing how good the getting started docs are here! (The comments in the code are a little sparse though ;))

**Comment by Evangelink** [comment]
@fowl2 Do you want to give it a go and we will give some feedback or do you want me to take care of this one?

**Comment by fowl2** [comment]
I'll give it a go! Created draft PR #4328 to gather feedback.

**Comment by buyaa-n** [comment]
The API Proposal https://github.com/dotnet/runtime/issues/33770 ready for review

**Comment by carlossanlop** [comment]
The API proposal has been approved, @fowl2
