### ISSUE TITLE
Write a tool to create issues for porting FxCop analyzers

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#361]
Write a tool that reads the spreadsheet `RulesInventory.csv`, and files an issue for each analyzer that has been marked for porting but has not yet been ported.

In future we could imagine generalizing this tool. Suppose we created a multi-project VS template for a new analyzer project and provided with it an empty spreadsheet. Developers could fill out the spreadsheet with the analyzers the want for their analyzer package, run the tool, and populate their list of issues. For now we'll hard-code everything for this particular spreadsheet format and this particular porting effort.

**Comment by sharwell** [comment]
I created the issues by hand for StyleCop Analyzers. They were pretty minimal, such as DotNetAnalyzers/StyleCopAnalyzers#144, but it got the job done.

The place where we used a tool was creating the stub analyzer classes so new contributors wouldn't have to think about where to place the implementation for particular rules:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1624PropertySummaryDocumentationMustOmitSetAccessorWithRestrictedAccess.cs

**Comment by lgolding** [comment]
Yes, we also used a stub generator for the FxCop rules. I think this will be a useful tool though, and it's mostly done, so I'll keep on keeping on.
