### ISSUE TITLE
 CA1012: Confusing name "Abstract types should not have constructors"

### ISSUE THREAD

**Issue by fowl2** [dotnet/roslyn-analyzers#3632]
The rule is called "Abstract types should not have constructors", but appears to actually mean "Abstract types should not have **public** constructors" or perhaps "constructors visible to non-derived types".

It would be great of the name/title of this rule could be made more clear.

from https://github.com/MicrosoftDocs/visualstudio-docs/issues/4952

related: [Check for protected internal constructors in CA1012](https://github.com/dotnet/roslyn-analyzers/issues/3358)

**Comment by Evangelink** [comment]
@mavasani WDYT? This feels indeed a bit weird when the issue does raise on some code.

**Comment by mavasani** [comment]
Sounds reasonable. I thought I already saw another issue with the same feedback...
