### ISSUE TITLE
Feature Request: Functions ending in Async that are not Async should have a warning

### ISSUE THREAD

**Issue by loligans** [dotnet/roslyn-analyzers#3636]
A function that ends with the postfix `Async` that is not actually async should have a `warning` or `suggestion` that recommends removing the `Async` postfix from the name.

`public void DoSomethingAsync();` - should receive a recommendation to remove the `Async` postfix.

**Comment by mavasani** [comment]
@AArnott @jmarolf

**Comment by leoniDEV** [comment]
You can already do this using naming convention, you can configure it throug the Visaul studio UI in [Code Style Preference](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019):
![naming_convention](https://i.stack.imgur.com/IKjSQ.png)

or though [.editorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2019)

**Comment by loligans** [comment]
Ahh yes I see. Thank you @leoniDEV

**Comment by AArnott** [comment]
This is also available in [`VSTHRD200`](https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md).
