### ISSUE TITLE
Suggestion: Rule like CA1305 for DateTime/DateTimeOffset

### ISSUE THREAD

**Issue by kevinoid** [dotnet/roslyn-analyzers#3640]
#### Analyzer package

[Microsoft.NetCore.Analyzers](https://www.nuget.org/packages/Microsoft.NetCore.Analyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

[CA1305](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1305)

#### Repro steps

CA1305 is not currently triggered by calls to [`DateTime.ToShortDateString()`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.toshortdatestring) and similar methods, because there is no `DateTime.ToShortDateString(IFormatProvider)` (see dotnet/runtime#24121).

Since [`DateTime.ToShortDateString`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.toshortdatestring) is specified to have the same behavior as calling [`DateTime.ToString(String)`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring) with `"d"`, it is likely to cause the same issues as calling that function directly, which would raise CA1305.  Is there any interest in extending CA1305 or adding a similar rule to cover these methods?

Thanks for considering,
Kevin

**Comment by MaStr11** [comment]
Duplicate of #1911

**Comment by kevinoid** [comment]
I agree.  Good catch @MaStr11!  Closing in favor of #1911.
