### ISSUE TITLE
UseValueTasksCorrectlyAnalyzer throws ArgumentNullException

### ISSUE THREAD

**Issue by DavidZidar** [dotnet/roslyn-analyzers#3642]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

CA2012 UseValueTasksCorrectlyAnalyzer

#### Repro steps

```
using System;
using System.Threading.Tasks;

class C
{
    public void GuardThenAssignVariable()
    {
        if (false) throw new Exception();
        var vt = Helpers.ReturnsValueTask();
    }
}
```

#### Expected behavior
UseValueTasksCorrectly should not throw.

#### Actual behavior
An async method with a guard clause that throws an exception in combination with storing `ValueTask` in a variable causes UseValueTasksCorrectlyAnalyzer to throw `ArgumentNullException`.

It seems that `block.FallThroughSuccessor.Destination` is `null` when handling the fall through successor since it is a throw expression which results in the call to `seen.TryGetValue` throw
`ArgumentNullException` because the key is a null value.

**Comment by stephentoub** [comment]
Thanks for reporting this.

**Comment by DavidZidar** [comment]
No problem!
