### ISSUE TITLE
Can not remove Analyzers

### ISSUE THREAD

**Issue by natilivni** [dotnet/roslyn-analyzers#3659]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Repro steps

1. Install FxCopAnalyzers using Nuget
2. Revert project files so that package is removed by git

#### Expected behavior

Analyzers should be removed from the dependencies

#### Actual behavior

Analyzers are still in dependencies and can not be removed.

**Comment by mavasani** [comment]
@natilivni Thanks for the report. This issue belongs to http://github.com/dotnet/project-system. Can you please transfer the issue?

**Comment by natilivni** [comment]
moved to https://github.com/dotnet/project-system/issues/6222
