### ISSUE TITLE
Add analyzer that warns about redundant fields initialization

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn-analyzers#3674]
There are cases where C# compiler is not able to optimize out redundant fields initialization. 

```c#
class C
{
    static object o = new object ();
    static bool b = false;
}
```

The simple example is extracted from https://github.com/dotnet/roslyn/issues/43652

**Comment by mavasani** [comment]
This is already implemented as IDE0052 for  private fields that are written but not read. It currently only handles instance fields but can potentially be enhanced. It is also available for CI enforcement in CodeStyle NuGet package.
