### ISSUE TITLE
dotnet_diagnostic vs dotnet_code_quality prefix

### ISSUE THREAD

**Issue by tmds** [dotnet/roslyn-analyzers#3678]
https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md uses the `dotnet_code_quality` prefix. Should this be `dotnet_diagnostic`?

All .editorconfig files in the microsoft.codeanalysis.fxcopanalyzers 3.0.0 package use the `dotnet_diagnostic` prefix.

**Comment by mavasani** [comment]
These are separate prefixes used and owned by different part of toolchain:

-  dotnet_diagnostic: used by compiler to configure properties for all analyzer and compiler diagnostics.

- dotnet_code_quality: Used by a specific code analysis (CA) analyzer package that contains options specific to code quality CA rules in this package.

**Comment by tmds** [comment]
Thanks. I got confused by having to set `severity` with `dotnet_diagnostic` prefix, and other settings with `dotnet_code_quality` prefix. It makes more sense now.
