### ISSUE TITLE
Is MethodKindEx class redundant?

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3682]
I don't get the purpose of the [MethodKindEx](https://github.com/dotnet/roslyn-analyzers/blob/afb82254fa022b4624c794469bf45acd17dec3fd/src/Utilities/Compiler/Extensions/MethodKindEx.cs) class.

It has the following constant:

```csharp
public const MethodKind LocalFunction = (MethodKind)17;
```

Which will ALWAYS have the same value as `MethodKind.LocalFunction`, so why it exists? why not just use `MethodKind.LocalFunction` and simply delete `MethodKindEx`?

**Comment by sharwell** [comment]
It's part of the light-up layer for projects that build against older versions of Roslyn.
