### ISSUE TITLE
RS0005 doesn't trigger for `CodeAction.Create`

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3684]
Please do no use `CodeAction.Create` - this should have fired [RS0005](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/RoslynDiagnosticIds.cs#L11), but seems it does not (please file an issue for that).

Use the pattern like this: https://github.com/dotnet/roslyn-analyzers/blob/79c2638f54b9e7ef0a3954cc838ec4c13ea63c1f/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OverrideEqualsOnOverloadingOperatorEquals.Fixer.cs#L65-L72

https://github.com/dotnet/roslyn-analyzers/blob/79c2638f54b9e7ef0a3954cc838ec4c13ea63c1f/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OverrideEqualsOnOverloadingOperatorEquals.Fixer.cs#L46-L51

_Originally posted by @mavasani in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjY4NTUwOTAwOnYy/pull_request_review_threads/discussion_

**Comment by sharwell** [comment]
This is by design. RS0005 does not apply to Roslyn.Diagnostics.Analyzers.

**Comment by mavasani** [comment]
Ah, thanks for the clarification @sharwell. Sorry for the confusion @Evangelink

**Comment by sharwell** [comment]
Correction: it doesn't apply for anything in this entire repository. It only applies to analyzers implemented in dotnet/roslyn.

**Comment by mavasani** [comment]
> it doesn't apply for anything in this entire repository. It only applies to analyzers implemented in dotnet/roslyn.

Why doesn't it apply to code fixes for CA rules implemented in this repo?

**Comment by Evangelink** [comment]
> Why doesn't it apply to code fixes for CA rules implemented in this repo?

Good question, it seems like a good fit for this repo if we do need to comply to this rule.

**Comment by Evangelink** [comment]
@mavasani @sharwell I am not sure to understand if there is (or not) something mis-behaving and something to fix here. If everything is as designed then we could close the ticket.

**Comment by sharwell** [comment]
This rule serves only one purpose: work around a bug in an internal Microsoft tool that only a small number of people ever even have access to. There is a remote possibility that it would impact something with this repository, but even if that is the case I believe that tool should be fixed if it matters that much, rather than continue to deviate from community analyzer best practices by applying this rule.

**Comment by Evangelink** [comment]
Ok so I don't think there is any point in keeping this ticket open. I will close it. @mavasani if you disagree with me please feel free to re-open.
