### ISSUE TITLE
[CA1508] False positive for "string.IsNullOrWhiteSpace(stringValue)"

### ISSUE THREAD

**Issue by TobiasSekan** [dotnet/roslyn-analyzers#3685]
**Version Used**: 
Microsoft Visual Studio Community 2019 Preview
Version 16.7.0 Preview 1.0

**Steps to Reproduce**:
```csharp
public void MakeCoolThings(object value)
{
    if(value is string stringValue)
    {
        // CA1508 -> string.IsNullOrWhiteSpace(stringValue) is always false
        if(string.IsNullOrWhiteSpace(stringValue))
        {
            // do cool stuff here
        }
    }

    // other cool stuff
}

// test with
// MakeCoolThings("\n\n");
```

**Expected Behavior**:
no CA1508

**Actual Behavior**:
CA1508 -> string.IsNullOrWhiteSpace(stringValue) is always false

**Comment by TobiasSekan** [comment]
Hello,

I used `Microsoft.CodeAnalysis.FxCopAnalyzers (3.0.0)`

![2020-05-29 07_39_03-PowerCalculator](https://user-images.githubusercontent.com/17874713/83225197-84d9b480-a17f-11ea-8e8b-6fa5965c5146.png)

The Error window say `CA1508` came from `Microsoft.CodeQuality.Analyzers`

![2020-05-29 07_41_21-PowerCalculator](https://user-images.githubusercontent.com/17874713/83225340-d7b36c00-a17f-11ea-87cf-9f43207e473b.png)

**Comment by Youssef1313** [comment]
It seems that the rule is disabled by default, and there are some known false positives.

https://github.com/dotnet/roslyn-analyzers/issues/2250#issuecomment-477667568

**Comment by Evangelink** [comment]
I have added a unit test for it and I can confirm there is a false-positive. 

@mavasani Looking at `DataFlowOperationVisitor.PerformPredicateAnalysisCore` https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs#L1557 I am wondering if this line is not the one causing the issue. I am not sure I have the right mental model for how the dataflow visitor is built but I would expect the true part of the `string.IsNullOrEmpty`/`string.IsNullOrWhiteSpace` to generate 2 states to explore: one where the value is null and one where it is not while my understanding is that we only visit applying null here. If I got things right, could you point me to the right direction for how to apply the non-null state?

**Comment by mavasani** [comment]
@Evangelink Our DFA walker will invoke the operation visitor for the Control flow branch related operations twice, with different values for `FlowBranchConditionKind`, once `FlowBranchConditionKind.WhenTrue` and once `FlowBranchConditionKind.WhenFalse`. Hence, each operation visitor doesn't need to split/generate two states, but the DFA walker ensures the split happens.

**Comment by Evangelink** [comment]
@mavasani Sorry I wasn't clear enough. I would expect 3 states to be generated:
- WhenFalse -> not null
- WhenTrue -> null
- WhenTrue -> not null (you can enter this condition without having the value being null, it can be empty or whitespace)

**Comment by mavasani** [comment]
Each control flow path can only have one state, so last two merge to `WhenTrue -> maybe null`. Can you set a breakpoint at the line you mentioned above and verify this is indeed the case on true and false branch visits?

**Comment by Evangelink** [comment]
With my understanding of what I read when debugging I think this is not true. When exploring the `WhenTrue` branch we have a not null state induced by the `is string` pattern and we only try to set null. This is why I have written this message.

**Comment by Evangelink** [comment]
If you have some time to point me in a direction for this, I'd be happy to be able to improve the DFA.
