### ISSUE TITLE
Can't build roslyn-analyzers in Visual Studio

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3687]
I want to get my hands dirty on a big code base, and it looks like roslyn-analyzers is a good place for me to learn. However, I'm having trouble building the repo after cloning it.

I've opened `RoslynAnalyzers.sln` in Visual Studio 2019, but I'm getting much errors like this when I try to build:

![image](https://user-images.githubusercontent.com/31348972/83073071-1c4fe200-a070-11ea-8eaf-d9a2108f6a87.png)

**Comment by mavasani** [comment]
Can you run `restore` from repo root before opening the solution in VS?

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-analyzers#getting-started for details.

**Comment by Youssef1313** [comment]
Thanks @mavasani :)

**Comment by Youssef1313** [comment]
I'm now getting the following errors and warnings:

![image](https://user-images.githubusercontent.com/31348972/83083052-5bd4f900-a085-11ea-8b23-be6c4f920cac.png)

**Comment by mavasani** [comment]
Can you check if you have installed "Microsoft Code Analysis 2019" VSIX extension? If so, please uninstall it.

**Comment by Youssef1313** [comment]
@mavasani Many thanks. These errors are gone.
But I'm confused whether I should build using the Build.cmd file or from inside Visual Studio? or it doesn't matter?
I built in Visual Studio, then tried to run the tests in Visual Studio, and for some reason the tests seem to be stuck and doesn't show any output.
and if I try to open Tests.cmd I get:

> Toolset version 5.0.0-beta.20228.4 has not been restored.

Does it need .NET 5.0 to run?
Why running the tests from Visual Studio was just stuck and didn't ask for .NET 5.0?

**Comment by Youssef1313** [comment]
Although Tests.cmd didn't work for me. But I'll close as I was able to run the tests inside Visual Studio.
