### ISSUE TITLE
Port FxCop rule CA1002: DoNotExposeGenericLists

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#369]
**Title:** Do not expose generic lists

**Description:**

System.Collections.Generic.List&lt;(Of &lt;(T&gt;)&gt;) is a generic collection that is designed for performance, not inheritance. Therefore, List does not contain any virtual members. The generic collections that are designed for inheritance should be exposed instead.

**Dependency:** None

**Notes:**

**Comment by jjhayworth** [comment]
Check source code for [SonarSource implementation of this rule](https://rules.sonarsource.com/csharp/RSPEC-3956)
