### ISSUE TITLE
Unclear README instructions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3697]
This [README](https://github.com/dotnet/roslyn-analyzers/blob/master/src/MetaCompilation.Analyzers/Core/ReadMe.md) file mentions:

```
Instructions

    Ensure you are running Visual Studio 2015 RTM, as this tutorial will not work on older versions of Visual Studio
    Before you begin, go to Tools -> Extensions and Updates -> Online and install .NET Compiler Platform SDK
    Restart Visual Studio
    Open Solution Explorer, if there is a warning about Visual Studio Extensibility Tools, click on it and follow the instructions
    Open Visual Studio Developer Command Prompt navigate to the roslyn-analyzers repository on your machine
    Then type powershell -executionpolicy bypass src\.nuget\NuGetRestore.ps1
    Restart Visual Studio
    Clone the roslyn-analyzers repository on your local machine
etc...
```

- One of steps says: `powershell -executionpolicty bypass src\.nuget\NuGetRestore.ps1`
The path seems to be wrong, this [file](https://github.com/dotnet/roslyn-analyzers/blob/master/tools/AnalyzerCodeGenerator/template/src/.nuget/NuGetRestore.ps1) is in "/tools/AnalyzerCodeGenerator/template/src/.nuget/NuGetRestore.ps1"

- That powershell script references "AllAnalyzers.sln" in it, there is no solution file with that name in the repository.

- At the mentioned step of running `NuGetRestore.ps1`, it indicates that I've already cloned the repo locally (if I haven't, how would I run this powershell script?) However, after two steps, it says: `    Clone the roslyn-analyzers repository on your local machine`

The instructions looks messy, unclear, and outdated (unless I'm missing something)

**Comment by mavasani** [comment]
`MetaCompilation.Analyzers` is a very old intern project, that likely should be deleted from the repo.

**Comment by Youssef1313** [comment]
@mavasani, Ok I'll open a PR to delete it.
