### ISSUE TITLE
[Analyzer Suggestion] When to use/not use var

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3698]
implicit variable declaration using `var` simplifies the code a lot, while keeping its clarity, in cases where the type is duplicated. For example:

```csharp
MyLongClassName myLongClassName = new MyLongClassName(); // looks bad (repeating of the class name).
var myLongClassName = new MyLongClassName(); // Shorter, cleaner, and the variable type is still clear.

MyLongClassName myLongClassName = (MyLongClassName)obj; // looks bad too for the same reason.
var myLongClassName = (MyLongClassName)obj; // Much better!

var myObject = someOtherObject.FunctionCall(); // unclear what type myObject is. We need to check the return type of FunctionCall.
ReturnType myObject = someOtherObject.FunctionCall(); // better, the type is clear now.

int x = 0;
var x = 0;
// both are okay in that case, and it's a matter of preference which can be configurable.
```

If this analyzer is accepted and will be implemented, I think it should be disabled by default. There will be much violations in a large code-base.

Benefits of such analyzer:

- Consistency over code-base on when to use/not use var.
- Readability improvement.

(I'm not sure whether this should be here or in dotnet/roslyn, so feel free to transfer the issue if it's not in the right place)

**Comment by mavasani** [comment]
This is already implemented as IDE0007 and IDE0008 in Roslyn repo. Please take a look at `var preferences` in https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

@Youssef1313 I would recommend opening all code style related analyzer suggestions in the Roslyn repo. This repo is primary focused on code quality/semantic analysis based analyzers.
