### ISSUE TITLE
CA1829 not reporting for ImmutableArray

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3701]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

[CA1829](https://docs.microsoft.com/visualstudio/code-quality/ca1829)

#### Repro steps

![image](https://user-images.githubusercontent.com/31348972/83401967-3427bd00-a406-11ea-80fa-ca05c42ad511.png)

#### Expected behavior

CA1829 is reported in both methods.

#### Actual behavior

CA1829 is reported only in the `int[]` case, but not in `ImmutableArray<int>` case.

**Comment by Youssef1313** [comment]
It seems that there are unit tests for ImmutableArray, so I'm not sure  what's going on that it's not reported in my case

**Comment by mavasani** [comment]
I think this might be fixed now- @Jozkee

**Comment by Youssef1313** [comment]
@mavasani Did you start working on @Jozkee's issue? Because I started trying with it too 😄

**Comment by mavasani** [comment]
@Jozkee re-implemented the analyzer recently, so i’d let him take it up.

**Comment by Jozkee** [comment]
>It seems that there are unit tests for ImmutableArray

I run those tests you mention but those work fine and they seem to assert for the issue that you are reporting. 

I also tried creating a new project, install Microsoft.CodeAnalysis.FxCopAnalyzers v 3.0.0 and I was unable to duplicate this issue locally on my VS.

@mavasani is there something else we can do to verify that we are doing the correct steps?

**Comment by mavasani** [comment]
@Youssef1313 Can you please try this with the latest package from here: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.FxCopAnalyzers&protocolType=NuGet&version=3.3.0-beta1.20302.1

**Comment by Youssef1313** [comment]
It works. Closing.
