### ISSUE TITLE
CA1062 False positive

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3716]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

[CA1062](https://docs.microsoft.com/visualstudio/code-quality/ca1062)

#### Repro steps

I've a small abstract class that represents a chess piece, with the following Equals implementation.

![image](https://user-images.githubusercontent.com/31348972/83964293-66c13200-a8ac-11ea-8d59-594ffa53d1bc.png)

#### Expected behavior

If I'm not missing something, there shouldn't be a warning.

1. Assume the passed `obj` is null.
1. `obj is Piece p` should be false.
1. `!(obj is Piece p)` should be true.
1. The right of the `||` operator won't be evaluated.

#### Actual behavior

A warning is issued.

**Comment by Youssef1313** [comment]
The warning is issued also with simplified inverted if
![image](https://user-images.githubusercontent.com/31348972/83964519-f61b1500-a8ad-11ea-9f2a-c56d9ad69eab.png)

**Comment by Youssef1313** [comment]
If `p.GetType()` is used instead of `obj.GetType()`, the warning doesn't show.
However, I think `obj.GetType()` is still valid and will never throws  a null ref exception due to the first part of the condition.

**Comment by Evangelink** [comment]
I agree that `obj` can't be `null` when reaching the second part of the OR condition. I will need to have a dive in the dataflow but I suspect that the NOT_NULL state not applied back to the `obj` symbolic value.
