### ISSUE TITLE
Port FxCop rule CA1006: DoNotNestGenericTypesInMemberSignatures

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#372]
**Title:** Do not nest generic types in member signatures

**Description:**

A nested type argument is a type argument that is also a generic type. To call a member whose signature contains a nested type argument, the user must instantiate one generic type and pass this type to the constructor of a second generic type. The required procedure and syntax are complex and should be avoided.

**Dependency:** None

**Notes:**

**Comment by paulomorgado** [comment]
This would trigger on `Dictionary<string, List<string>>`, for example.

Is that really bad?

**Comment by Evangelink** [comment]
@mavasani What's your opinion on this rule? The dictionary case listed by @paulomorgado seems quite common and I would be annoyed to have issues reported on this.

I see a couple of solutions:

1. Do not implement this rule. This might be problematic if users were used to have it from the old fxcop.

2. Implement the rule as-is but disabled by default.

3. Implement the rule with a new implementation that would raise on `List<List<T>>` or `IEnumerable<IEnumerable<T>>`... but not on `Dictionary<string, List<string>>`. I think we might want to have a user-option to let users excluding types.

4. Option 3 + adding a user-option to fallback to the old behavior (turned-off by default).

**Comment by paulomorgado** [comment]
The point here is if the rule makes sense at all.

So, instead of this:

```CSharp
Dictionary<string, List<string>>
```

I do this:

```CSharp
public class ListOfString : List<string> { }

Dictionary<string, ListOfString>
```

Is that any better?

**Comment by mavasani** [comment]
I agree with @paulomorgado that this rule seems way to pedantic and overall your code seems to just get worse by following it. Introducing types so the use sites just satisfy this rule is bad software design. I am not inclined towards implementing it unless we see more feedback and valid reasons why someone really wants it. Can we ask the customer who requested this, why they want this rule?

**Comment by Evangelink** [comment]
@mavasani, @paulomorgado I can see some value for specific types. For example, I don't think that having `List<List<int>>` or `Tuple<string, Tuple<int, string>>>` is really desirable in a code base. In one of the place I have worked for there was this ugly type as return type from some "factories" `Tuple<Tuple<Dictionary<string, Dictionary<string, float[]>>, float[]>, Dictionary<string, Dictionary<string, float>>>`. 

> Can we ask the customer who requested this, why they want this rule?
@tom-englert Any feedback to share?

**Comment by paulomorgado** [comment]
@Evangelink, what are you basing your assumptions on?

Do you know how a `Tuple` of 8 or more components is constructed? It's a tuple where the last component is a tuple: [Tuple<T1,T2,T3,T4,T5,T6,T7,TRest>(T1, T2, T3, T4, T5, T6, T7, TRest)](https://docs.microsoft.com/dotnet/api/system.tuple-8)

**Comment by Evangelink** [comment]
@paulomorgado This was just an example. My point is more that if I am creating a PR with `List<List<int>>` I am pretty sure I would get some remark (and I would have done so). Reporting on any kind of generic nesting doesn't seem like a good idea but I still think that some nesting do seem of. Once again, imagine that I am creating a PR and the return type of one of my method is `Tuple<string, Tuple<int, string>>>` would you just see that and say LGTM or would you raise some comment? I would personally because when reading this I don't understand what's the supposed to represent.

**Comment by paulomorgado** [comment]
I wouldn't say LGTM just because you're using `Tuple` as the return type. 😄 

The types should be dictated by what make sense for data and not dictated by cosmetics.

**Comment by Evangelink** [comment]
Per @paulomorgado and @mavasani comments I think this could be closed as won't fix, don't you think?
