### ISSUE TITLE
[Suggestion] Move from 'master' to 'main'

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3721]
Hi,

I have seen quite a lot of the repo's from the dotnet foundation moving away from 'master' to 'main'. Is it something you consider? I could help but there are some parts that will need to be updated on your side.

Cheers

**Comment by Evangelink** [comment]
@mavasani Is there any interest on this ticket? If not then I am ok with closing it.

**Comment by mavasani** [comment]
Tagging @terrajobst

**Comment by Evangelink** [comment]
Sorry for the ping @terrajobst but would you mind giving your opinion here?

**Comment by Evangelink** [comment]
Ping @terrajobst and @mavasani

**Comment by terrajobst** [comment]
Our goal is to move away from master from all .NET repos. We're currently waiting for GitHub to improve the support so that less stuff breaks; we were told they will have something ready by EOY.

**Comment by Youssef1313** [comment]
A guide was added in [dotnet/arcade](https://github.com/dotnet/arcade/blob/master/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md) for the migration. @mavasani Should this process be started?

**Comment by mavasani** [comment]
@terrajobst to make the final call when to migrate dotnet repos.

**Comment by Youssef1313** [comment]
@Evangelink The repo has moved to main today. We can close this :tada:

**Comment by Evangelink** [comment]
Congratz to the team(s)!
