### ISSUE TITLE
Assertion window showing up when building

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn-analyzers#3734]
I synced my branch to the latest bits in master and I suddenly started seeing a window like the one below showing up several times when building the roslyn-analyzers repo. I have to click Ignore 28 times to let the build process continue.

Manish said it could have been caused by "recent changes in CFG/IOperation tree shape or new nodes".

![image](https://user-images.githubusercontent.com/1175054/84191400-4a103000-aa4d-11ea-9339-f166be057be1.png)

**Comment by Evangelink** [comment]
I have the same issue! On my machine they seem to be related to the sln change (see #3745). @carlossanlop could you tell us if you have this sln change on your code?

**Comment by mavasani** [comment]
@Evangelink I am not sure they are related. This issue is when using debug bits of analyzers from this repo to build the repo itself. These are real asserts from product, not related to tooling issues mentioned in #3745

**Comment by Evangelink** [comment]
I don't know if they do relate that's why I was asking if Carlos was facing the same issue. On my side they started at around the same time.

**Comment by carlossanlop** [comment]
@Evangelink My sln file still has the lines that you reported in in #3745. So it's not related.

**Comment by Evangelink** [comment]
It seems ok for me now. @carlossanlop is it also ok for you?

Tagging @mavasani

**Comment by carlossanlop** [comment]
I haven't seen the issue again, and I rebased a couple of times already after I reported the issue. I'll close this issue. We can reopen if we see it again.
