### ISSUE TITLE
Opening the solution with VS 16.6.2 always changes the sln

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3745]
Opening the solution with VS 16.6.2 always results in the sln changed with the following removals

![image](https://user-images.githubusercontent.com/11340282/84397633-2987d780-abff-11ea-959c-2852d64a65fa.png)

Does it need to be committed? Is it a bug?

**Comment by mavasani** [comment]
Hmm not sure about this one - it doesn't seem to happen for our internal 16.7 dogfood builds. Can you try latest 16.7 preview build?

**Comment by Evangelink** [comment]
I don't have the preview VS installed on my machine so it is going to take a bit of time but I will try to see if I can reproduce the issue.

**Comment by Evangelink** [comment]
I have the same error with the preview version but what's funny is that I don't have the same issue on another machine. Random guess, is it possible that a missing workload/feature would cause such behavior?

**Comment by Evangelink** [comment]
FYI I was on a different version of VS on the other machine. Now I have the issue with all the machines. Do you think I shall open a ticket on VS side?

**Comment by Evangelink** [comment]
This is no longer true so I am closing this ticket.
