### ISSUE TITLE
Code Metrics task throwing errors on dlls after dotnet upgradation

### ISSUE THREAD

**Issue by Prateek1584990** [dotnet/roslyn-analyzers#3753]
Code metrics task worked earlier with dotnet core projects. After upgrading the projects to dotnet framework 4.7, code metrics task starting failing with 2 dlls. using long runnner tool, we got the errors as 'could not load file...'. 

We have tried generating latest Metrics.exe by following the steps mentioned here: https://docs.microsoft.com/visualstudio/code-quality/how-to-generate-code-metrics-data. but it is giving below error
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. at Metrics.Program.RunAsync(String[] args, CancellationToken cancellationToken) at Metrics.Program.Main(String[] args) in C:\Metrics\roslyn-analyzers-master\src\Tools\Metrics\Program.cs:line 30 ExitCode ::-532462766

**Comment by Prateek1584990** [comment]
Hi @mavasani , as per your discussions in https://developercommunity.visualstudio.com/content/problem/1019671/code-metrics-task-throwing-errors-on-dlls-after-do.html , 

we have opened this issue, we want the executable to be generated and run it against a project. But we were getting above error.. Let us know how we can resolve the error.

**Comment by Prateek1584990** [comment]
Hi @mavasani  ,

Can we have any resolution to which we are facing.

**Comment by Evangelink** [comment]
@Prateek1584990 I cannot see the screenshot attached in the developercommunity website, are you running the metrics through command-line or Visual Studio? I made a test running the metrics on roslyn analyzers and I do have an error from VS but nothing from command line.

**Comment by Prateek1584990** [comment]
@Evangelink We got error when we tried to run the metrics through command-line.

**Comment by Alex7490** [comment]
Hi
Do you have a solution for this issue? I have the same problem with VS 2019.

**Comment by genlu** [comment]
This is being tracked by the feedback ticket.
