### ISSUE TITLE
Port FxCop rule CA1021: AvoidOutParameters

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#377]
**Title:** Avoid out parameters

**Description:**

Passing types by reference (using out or ref) requires experience with pointers, understanding how value types and reference types differ, and handling methods with multiple return values. Also, the difference between out and ref parameters is not widely understood.

**Dependency:** None

**Notes:**

**Comment by airbreather** [comment]
When/if this happens, please keep dotnet/roslyn#16291 in mind.
