### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [dotnet/roslyn-analyzers#3775]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Id | File Name Live Page Extended | String Resource ID | Full Source String | Extended Description | Answer Needed By
-- | -- | -- | -- | -- | --
51046 | NetAnalyzers\Core\Microsoft.NetCore.Analyzers\xlf\MicrosoftNetCoreAnalyzersResources.xlf | 0;   "RuntimePlatformCheckDescription" | TODO | is TODO localizable? if so, does   it mean "wait for handling"? |  
51048 | NetAnalyzers\Core\Microsoft.NetCore.Analyzers\xlf\MicrosoftNetCoreAnalyzersResources.xlf | 0;   "RuntimePlatformCheckMessage" | TODO Platform checks:'{0}' | is TODO localizable? if so, does   it mean "wait for handling"? |

**Comment by mavasani** [comment]
Sorry, these are temporary resource strings - I will remove them with a new PR.
