### ISSUE TITLE
RS0041 reported in Resources.Designer.cs

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#3793]
```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Warning	RS0041	Symbol 'ResourceManager.get' uses some oblivious reference types.	Gu.Localization (netstandard2.0)	C:\Git\_GuOrg\Gu.Localization\Gu.Localization\Properties\Resources.Designer.cs	40	Build	N/A
```

**Comment by mavasani** [comment]
Tagging @jcouv

**Comment by Youssef1313** [comment]
Looks like it's intentional based on [this](https://github.com/dotnet/roslyn-analyzers/blob/2bc4ddee57716be74aca26d1508391767b05a33d/src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs#L189) comment.

**Comment by jcouv** [comment]
From discussion with @sharwell it is good that we complain about public API issues both in user code and in generated code, so that all issues with the public API surface are visible.

**Comment by sharwell** [comment]
On that note, I do need to update [ResxSourceGenerator](https://github.com/dotnet/roslyn-sdk/pull/552) to add the `#nullable enable` line.

**Comment by bitbonk** [comment]
It is still not clear how this problem can be solved at all. So I created https://github.com/dotnet/roslyn-analyzers/issues/5521

**Comment by bitbonk** [comment]
@sharwell Since this is now closed, do you maybe have a hint on how to solve the problem?
