### ISSUE TITLE
[Documentation question] When to suppress CA2007

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3805]
[CA2007](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007)

> ## When to suppress warnings
>
> You can suppress this warning if you know that the consumer is not a graphical user interface (GUI)

Suppressing the warning = absence of ConfigureAwait = default behavior = ConfigureAwait(true).

However, from my understanding ConfigureAwait should be passed true for GUI, and false for libraries.

The documentation says suppress (equivalent to pass true) if it's NOT GUI.

Does the documentation have an error, or I misunderstand things? :smile:

**Comment by mavasani** [comment]
Seems like documentation has a typo, "not" should not be present

**Comment by Youssef1313** [comment]
@mavasani, Thanks. I'll open a PR now.

**Comment by Youssef1313** [comment]
The docs PR is merged. Closing this.
