### ISSUE TITLE
Have CA1836 omit Span<T>, ReadOnlySpan<T>, Memory<T>, and ReadOnlyMemory<T> from the diagnostics

### ISSUE THREAD

**Issue by Jozkee** [dotnet/roslyn-analyzers#3810]
I agree with the "eye of the beholder" statement, and I think we've proven that this rule no longer benefits _performance_ across the board.  I'd like to make sure we classify the rule differently; I recommend "Maintainability" as the more appropriate category.

I also recommend we have the rule omit `Span<T>`, `ReadOnlySpan<T>`, `Memory<T>`, and `ReadOnlyMemory<T>` from the diagnostics, and we do so in a way that if we find we need to add to the list of excluded types, we can do so easily.  We will want to proactively watch for community feedback on this one too.  We can always dial back to the original set of types that we had identified where this rule was certainly better for performance.

_Originally posted by @jeffhandley in https://github.com/dotnet/runtime/pull/37529#discussion_r439704796_

**Comment by sharwell** [comment]
I'm not sure I agree with the need to _configure_ this rule. Do we have any evidence of a project that disagrees with the code style enforced by this rule, but also has significant use of types that would benefit from the performance side of this? If not, it seems like a more appropriate recommendation would be to simply disable the rule in cases where it is not wanted.

**Comment by Jozkee** [comment]
>Do we have any evidence of a project that disagrees with the code style enforced by this rule, but also has significant use of types that would benefit from the performance side of this?

Isn't the dotnet/runtime repo itself good evidence?

https://github.com/dotnet/runtime/blob/a92f4f02dcbbd76cb9edf682424d001b9eb6d870/src/libraries/System.Private.CoreLib/src/System/Utf8String.Comparison.cs#L86-L94

**Comment by jeffhandley** [comment]
When I suggested we "do so in a way that if we find we need to add to the list of excluded types, we can do so easily," I just meant for the code to be factored such that we could have a single place in the implementation code where the list of excluded types would be managed--I didn't intend for it to be _configurable_.  But, then if we find in the future that we do want to head the configurable route, there'd be a single place in the code already where that could get added in.

@sharwell / @Jozkee - Does that work?

**Comment by Jozkee** [comment]
I'm OK with it but I'm not sure if @sharwell's concern is being addressed. @sharwell could you please confirm?
