### ISSUE TITLE
CA1835 code fixer should leave a null-forgiving operator

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/roslyn-analyzers#3826]
#### Analyzer package
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
v3.3.0-beta1.final (Latest pre-release)

#### Diagnostic ID
[CA1835](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1835)

#### Repro steps
1. Write a following code:
```cs
#nullable enable
using System;
using System.IO;
using System.Threading.Tasks;

public class C
{
    async ValueTask FooAsync(Stream? stream, byte[] buffer)
    {
        await stream!.WriteAsync(buffer, 0, buffer.Length) // CA1835 occurs here
            .ConfigureAwait(false);
    }

    static void Main() { }
}
```
2. Apply `Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'`

#### Expected behavior
The code-fixer leaves a null-forgiving operator on `stream!`

#### Actual behavior
The code-fixer deletes a null-forgiving operator:
```cs
#nullable enable
using System;
using System.IO;
using System.Threading.Tasks;

public class C
{
    async ValueTask FooAsync(Stream? stream, byte[] buffer)
    {
        await stream.WriteAsync(buffer.AsMemory(0, buffer.Length)) // CA1835 occurs here
            .ConfigureAwait(false);
    }

    static void Main() { }
}
```

**Comment by mavasani** [comment]
@carlossanlop

**Comment by carlossanlop** [comment]
Thanks for reporting this, @Tan90909090 
@mavasani I'll take a look as soon as I get some bandwidth.

**Comment by carlossanlop** [comment]
Fix merged.
@mavasani do Roslyn analyzers get shipped on the same cadence as the SDK? Will this fix show up in Preview 1 when it gets shipped?
cc @jeffhandley

**Comment by mavasani** [comment]
> do Roslyn analyzers get shipped on the same cadence as the SDK? Will this fix show up in Preview 1 when it gets shipped?

Changes into master will get shipped with faster cadence as NuGet package: https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/

Additionally, these changes automatically flow into https://github.com/dotnet/roslyn-analyzers/tree/release/6.0.1xx-preview1, which merges into the SDK repo's master branch target .NET 6.0 Preview1.
