### ISSUE TITLE
CA1835 code fixer should add a `using System` directive if it is not written

### ISSUE THREAD

**Issue by Tan90909090** [dotnet/roslyn-analyzers#3827]
#### Analyzer package
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version
v3.3.0-beta1.final (Latest pre-release)

#### Diagnostic ID
[CA1835](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1835)

#### Repro steps
1. Write a following code:
```cs
using System.IO;
using System.Threading.Tasks;

public class C
{
    async ValueTask FooAsync(Stream stream, byte[] buffer)
    {
        await stream.WriteAsync(buffer, 0, buffer.Length) // CA1835 occurs here
            .ConfigureAwait(false);
    }

    static void Main() { }
}
```

2. Apply `Prefer the 'Memory'-based overloads for 'ReadAsync' and 'WriteAsync'`

#### Expected behavior
The code-fixer adds a `using System;` line because a `AsMemory` extension method belongs to `System.MemoryExtensions`.

#### Actual behavior
The code-fixer does not add a `using System;` line:
```cs
using System.IO;
using System.Threading.Tasks;

public class C
{
    async ValueTask FooAsync(Stream stream, byte[] buffer)
    {
        await stream.WriteAsync(buffer.AsMemory(0, buffer.Length)) // CA1835 occurs here
            .ConfigureAwait(false);
    }

    static void Main() { }
}
```
This code has a `CS1061: 'byte[]' does not contain a definition for 'AsMemory' and no accessible extension method 'AsMemory' accepting a first argument of type 'byte[]' could be found (are you missing a using directive or an assembly reference?)`.

**Comment by mavasani** [comment]
@carlossanlop

**Comment by carlossanlop** [comment]
Thanks @Tan90909090 
@mavasani I'll take a look as soon as I get some bandwidth.
