### ISSUE TITLE
CA1508 - AvoidDeadConditionalCode - NeverNullRule not registered

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3829]
I have just noticed that the `SupportedDiagnostics` array doesn't declare the `NeverNullRule`. I have seen that the rules are disabled but that seems weird this descriptor exists but is not registered (especially that there is no comment). https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs#L52

Is it skipped on purpose? If so, could we add a comment? If not is it ok to fix it?

**Comment by mavasani** [comment]
Given both descriptors used in the analyzer register the same RuleId, it will not make much difference registering both or one. We can still make the change you propose for clarity.

**Comment by Evangelink** [comment]
Oh! I understand the link between the ID and the rest of the eco-system but I would have expected the actual descriptor listed in the supported diag to make a difference.

Happy to fix or leave as-is if you think that's better.
