### ISSUE TITLE
CA2249 auto-fix does not include specified StringComparison.Ordinal param

### ISSUE THREAD

**Issue by RobSiklos** [dotnet/roslyn-analyzers#3839]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.3.0-beta1.final

#### Diagnostic ID

[CA2249](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca2249)

#### Repro steps

1. Apply the CA2249 fix on the following code (.NET Core 3.0 class library):

`bool v = s1.IndexOf(s2, StringComparison.Ordinal) >= 0;`

#### Expected behavior

`bool v = s1.Contains(s2, StringComparison.Ordinal);`

#### Actual behavior

`bool v = s1.Contains(s2);`

#### Rationale

The idea is that if a developer bothered to explicitly specify `StringComparison.Ordinal`, it means they thought about what they wanted, instead of just relying on the defaults. Ironically, many of us have been trained to do such a thing by CA itself, via the globalization warnings which required the comparison type to be specified. When converting from `IndexOf` to `Contains`, we don't want to lose this information, and so it should be carried over, to let future developers know that the author didn't just blindly rely on the default.

**Comment by mavasani** [comment]
@pgovind

**Comment by pgovind** [comment]
So, just to be explicit about it, the code-fix is right. The semantics of string.IndexOf vs string.Contains differ. `string.IndexOf` performs a culture-aware comparison while `string.Contains` performs an `Ordinal` comparison. So `s1.Contains(s2, StringComparison.Ordinal)` is the same as `s1.Contains(s2)`. As to whether we want to include the comparison argument always, I wonder what @terrajobst and @bartonjs think?

**Comment by manfred-brands** [comment]
The created code `s1.Contains(s2)` triggers CA1307: Specify StringComparison.

**Comment by mavasani** [comment]
CA1307 is likely due to https://github.com/dotnet/roslyn-analyzers/issues/2581

**Comment by Evangelink** [comment]
@mavasani It seems that there is nothing left to do here too, could you confirm?

**Comment by mavasani** [comment]
Agreed.
