### ISSUE TITLE
Analyzer 'Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null'

### ISSUE THREAD

**Issue by Cyberboss** [dotnet/roslyn-analyzers#3850]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

AD0001

#### Repro steps

1. Clone https://github.com/tgstation/tgstation-server
2. Checkout branch `FixSomeStuff` at commit https://github.com/tgstation/tgstation-server/commit/2938c128ea721805c1335808763d1eb2e1ce37cd
3. Build the project Tgstation.Server.Host in tgstation-server.sln (requires npm in PATH)

#### Expected behavior

Analyzers all pass

#### Actual behavior

Analyzer 'Microsoft.NetCore.Analyzers.Tasks.UseValueTasksCorrectlyAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null'

#### Additional information

This started happening after a commit where I implemented `IAsyncDisposable` in a chain of classes for the first time in the codebase

**Comment by mavasani** [comment]
I believe this is a dupe of https://github.com/dotnet/roslyn-analyzers/issues/3642, but I'll let @stephentoub confirm and close.

**Comment by mavasani** [comment]
@Cyberboss Can you also try latest pre-release: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/3.3.0-beta1.final?

**Comment by Cyberboss** [comment]
That looks to have done the trick. Thanks!
