### ISSUE TITLE
CA1822 should not fire for obsolete APIs

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3857]
![image](https://user-images.githubusercontent.com/10605811/87484217-7b4ec380-c5ea-11ea-8d60-969d622fc076.png)

**Comment by mavasani** [comment]
@Evangelink

**Comment by Evangelink** [comment]
Let me a do a PR, in the meantime, I think that the obsolete case is kinda global, what about having some global exclusion applying for more (all?) rule? Or do you prefer to have them added on the case by case?
