### ISSUE TITLE
CA1822 (make static) should not fire for public properties on XAML backing types

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3858]
https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/MoveToNamespace/MoveToNamespaceDialog.xaml.cs

![image](https://user-images.githubusercontent.com/10605811/87485384-86efb980-c5ed-11ea-800c-ee7b028018f4.png)

**Comment by mavasani** [comment]
@Evangelink

**Comment by Evangelink** [comment]
@mavasani I really feel like properties shall be excluded from the scope of this rule. IMO that's really edge case to define static properties so I would be in favor of having some FNs rather than so many FPs.

In the exact case you are showing I don't see what would prevent the property to be static though. It doesn't prevent binding and resources are static values so the suggestion LGTM.

**Comment by mavasani** [comment]
> I really feel like properties shall be excluded from the scope of this rule. IMO that's really edge case to define static properties so I would be in favor of having some FNs rather than so many FPs.

I believe the rule is designed to flag all members that do not require instance access, but haven't been marked static. It indicates a design flaw as well as a performance issue to define instance members for functionality that is not tied to the instance. The member kind (field/property/event/method) is just implementation detail, and should not affect this analysis.

The core issue here is that various frameworks have defined their own non-declarative mechanisms such as reflection, MEF, etc. to access the members, and have hard coded the static/instance binding flag requirement on the accessed member. XAML requires instance properties on XAML backing types, ASP.NET core assumes public APIs on its public types can be used via reflection, etc. Today, we can skip properties, but tomorrow any of this frameworks might end up defining methods on types and access it in similar fashion, expecting specific signatures, accessibility, shared/instance nature, etc.

Ideal fix here would be there is no change in the analyzer. As you mentioned, the analyzer is absolutely correct. The problem is with each such framework, so it should be these frameworks that should ship a diagnostic suppressor for their hacky, non-declarative, means of accessing members via reflection and relying on their signatures. That is unlikely to happen anytime soon, so meantime we have to put the bail outs in the analyzer.

Also tagging @dotnet/roslyn-analysis for their views.

**Comment by mavasani** [comment]
Coming back to this issue - I think it should be possible to detect if a type is XAML control backing type and bail out completely for it for all members. Do we know what is the best check to detect this?

**Comment by Evangelink** [comment]
I only partially agree, I do think that the member type actually plays a role. For example an auto-property can always be considered as can be make static while it rarely shall be. More generally, and even if I agree with the performance impact, a property, except when it returns a static/constant value is only rarely meant to be static.

> Coming back to this issue - I think it should be possible to detect if a type is XAML control backing type and bail out completely for it for all members. Do we know what is the best check to detect this?

You partially can. You could have your view code-behind inheriting from a non-standard object like `MetroWindow` for `MahApps` or `ReactiveUserControl` for `ReactiveUI`... Besides what about the exact same case you mentioned but on a View Model object, I don't see how it differs and why it shall behave differently.

**Comment by mavasani** [comment]
> For example an auto-property can always be considered as can be make static while it rarely shall be

I see declaring a property as an auto-property to be specifying intent of having a member backed by an instance field, tying it tht e instance and hence requiring it to be an instance member.

> You partially can. You could have your view code-behind inheriting from a non-standard object like MetroWindow for MahApps or ReactiveUserControl for ReactiveUI... Besides what about the exact same case you mentioned but on a View Model object, I don't see how it differs and why it shall behave differently.

I am wondering if we can detect from compilation's assembly references if it contains any XAML or user controls as such and if so, avoid analyzing properties for such an compilation. If not, and this is too open ended, it might mean we have to be super conservative and leave out properties completely as you suggested. It does not make me happy that we have to compromise on the core analysis, which is correct and pretty useful IMO, just because of misuse and incorrect assumptions baked into well known frameworks :(. If we do have to skip properties, public APIs, etc. for this rule, maybe we can make it configurable for users to enable it when they desire?

**Comment by Evangelink** [comment]
Ok let me step back a bit on this rule. Regarding the issue you are mentioning on this ticket, is there any reason not to mark the property as `static` here?

Regarding auto-properties and readonly properties set in the ctor, let me check if they are correctly excluded.

**Comment by mavasani** [comment]
> Regarding the issue you are mentioning on this ticket, is there any reason not to mark the property as static here?

I thought the XAML binding would require an instance property, but let me quickly try it out and see if it works fine with static property.

**Comment by mavasani** [comment]
You are right @Evangelink. This scenario works fine even with static properties! I will close this issue :-).
