### ISSUE TITLE
Port FxCop rule CA1040: AvoidEmptyInterfaces

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#387]
**Title:** Avoid empty interfaces

**Description:**

Interfaces define members that provide a behavior or usage contract. The functionality that is described by the interface can be adopted by any type, regardless of where the type appears in the inheritance hierarchy. A type implements an interface by providing implementations for the members of the interface. An empty interface does not define any members; therefore, it does not define a contract that can be implemented.

**Dependency:** None

**Notes:**

**Comment by rchande** [comment]
This is done.

**Comment by lgolding** [comment]
It was done in PR #738.
