### ISSUE TITLE
CA1069: Indeterministic false positive

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#3871]
#### Analyzer package

?

#### Diagnostic ID

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1069	The enum member 'NIL' has the same constant value '-1' as member 'NIL'.	Microsoft.VisualStudio.ProjectSystem.Managed.VS	C:\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS\Interop\IVsAppId.cs	52	Active

#### Repro steps

This one comes and goes and I cannot pin down why/when it appears.

In this file: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Interop/IVsAppId.cs, I've seen this warning appear for both https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Interop/IVsAppId.cs#L54 and https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Interop/IVsAppId.cs#L283, it fires for no other enum values in that file.

**Comment by mavasani** [comment]
@Evangelink Any ideas?
