### ISSUE TITLE
CA1822 false positives on Entity Framework properties

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#3878]
> 
> 
> As a FYI this is also occurring on Entity Framework properties that are marked get; set; with or without `[NotMapped]` but especially with `{ [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] get; [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)] set; }`

@mavasani How do you want to handle this comment?

_Originally posted by @Evangelink in https://github.com/dotnet/roslyn-analyzers/issues/3835#issuecomment-659715703_

**Comment by juliusfriedman** [comment]
Thank you

**Comment by Evangelink** [comment]
@mavasani The rule is `CA1822` not `CA1812` (I don't have the title change rights).

**Comment by Evangelink** [comment]
Regarding the actual issue itself:

- With another PR we have already fixed the analyzer to prevent reporting an issue on auto-properties marked with attributes so `[MethodImpl(MethodImplOptions.AggressiveInlining)] get;` no longer reports an issue.

- For the `[NotMapped]` I am not sure we shall actually do something. If you have this attribute on a auto-property then you will not have an issue (see previous point), if you do have it on another kind of property then if the content is static you will get an issue but that makes sense to me.

Overall and if I am not missing the original point of the ticket I think we can close it as `Fixed`.

Tagging @juliusfriedman to confirm I didn't miss any point.

**Comment by mavasani** [comment]
Agreed. Let us re-open if required.
