### ISSUE TITLE
Port FxCop rule CA1041: ProvideObsoleteAttributeMessage

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#388]
**Title:** Provide ObsoleteAttribute message

**Description:**

A type or member is marked by using a System.ObsoleteAttribute attribute that does not have its ObsoleteAttribute.Message property specified. When a type or member that is marked by using ObsoleteAttribute is compiled, the Message property of the attribute is displayed. This gives the user information about the obsolete type or member.

**Dependency:** None

**Notes:**

**Comment by srivatsn** [comment]
Implemented analyzer in #842
