### ISSUE TITLE
Microsoft.CodeAnalysis.PublicApiAnalyzers: Setting RS0017 to error, still shown as warning

### ISSUE THREAD

**Issue by dm5xx** [dotnet/roslyn-analyzers#3885]
#### Analyzer package

[Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers)

#### Package Version

v3.0.0 (Latest) or v3.3.0-beta1.final (Latest pre-release)

#### Diagnostic ID

Example: RS0017 C# Symbol is part of the declared API, but is either not public or could not be found

#### Repro steps

1. Add nuget package
2. Add .editorconfig
3. Set dotnet_diagnostic.RS0017.severity = error
4. Remove a Method complete (after adding it to the unshipped.txt)
5. Clean/Rebuild solution

#### Expected behavior
RS0017 is shown as an error, after it has been removed from the public api

#### Actual behavior
RS0017 is shown as a warning. It seems, its impossible to force this to error

Additonal info:
Setting RS0016 or RS0026 to error are recognized correct and shown as changed (error). Setting all to error in .editorconfig, RS0017 is still warning?! Am i doing something wrong?!

**Comment by Evangelink** [comment]
Probably related to #3833

**Comment by dm5xx** [comment]
Setting "WarningAsErrors" in the Project file will help in this case.. So it has something to do with treating .editorconfig or "something is overwriting the .editorconfig-configuration"

**Comment by Evangelink** [comment]
I confirm that I can reproduce the issue. Whatever the severity set, the issue is always raised as a warning.

**Comment by Youssef1313** [comment]
This is a known roslyn issue. https://github.com/dotnet/roslyn/issues/31916

**Comment by mavasani** [comment]
Thanks @Youssef1313!
