### ISSUE TITLE
Port FxCop rule CA1043: UseIntegralOrStringArgumentForIndexers

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#389]
**Title:** Use integral or string argument for indexers

**Description:**

Indexers (that is, indexed properties) should use integral or string types for the index. These types are typically used for indexing data structures and they increase the usability of the library. Use of the Object type should be restricted to those cases where the specific integral or string type cannot be specified at design time.

**Dependency:** None

**Notes:**

**Comment by srivatsn** [comment]
Transitions bootcamp project.
