### ISSUE TITLE
Enable RS0037 and fix related issues

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#3894]
@mavasani What about _just_ keeping the RS0037 suppression, and remove it in a follow-up PR?

_Originally posted by @sharwell in https://github.com/dotnet/roslyn-analyzers/pull/3888#issuecomment-662547329_

**Comment by Evangelink** [comment]
As-soon-as I enable this rule and add the `#nullable enable` to the public api file, then I start having `StackOverflowException` and it's no longer possible to build the solution. Happens in both VS and command line.

**Comment by mavasani** [comment]
I believe this was fixed recently by @jcouv. You will need to update to latest analyzer package.

**Comment by Evangelink** [comment]
Thanks for the tip, sadly it doesn't work (or I am referencing the wrong version `3.3.0-beta3.20365.3`):
![image](https://user-images.githubusercontent.com/11340282/88299208-68cb3d00-cd02-11ea-8412-251b2c9fbb5c.png)

**Comment by jcouv** [comment]
The fix was https://github.com/dotnet/roslyn-analyzers/pull/3847 (merged 7 days ago). I tried looking for 3.3.0-beta3.20365.3 to confirm whether it includes the fix, but could not find it.

@mavasani Do you know what version of the package would include the fix?

**Comment by mavasani** [comment]
You can try latest packages from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Roslyn.Diagnostics.Analyzers&protocolType=NuGet&version=3.3.0-beta3.20373.1&view=versions

**Comment by Evangelink** [comment]
Thank you both of you! I don't know why VS wasn't showing me anything more recent than the version `3.3.0-beta3.20365.3`... I have tried with the latest on your link (i.e. `3.3.0-beta3.20373.1`) and it's working correctly.

**Comment by Evangelink** [comment]
Ok so either we have a pretty big bug or I totally lack the logic to understand what I am supposed to do...

I have:
1. Removed the exclusion in the ruleset
2. Updated the version of the analyzer to avoid the `StackOverflowException`
3. Added `#nullable enable` as the first line of `PublicAPI.Unshipped.txt`
4. Fixed all `RS0036`

And now I have plenty of `RS0016` which recommends me to basically revert the nullability annotation change I have made.

I will link a PR so that you can have a quick repro.

**Comment by jcouv** [comment]
@Evangelink I've checked out your PR https://github.com/dotnet/roslyn-analyzers/pull/3900 locally and did `Restore.cmd` and `Build.cmd`. I'm just seeing a handful of RS0041 (complaining about use of oblivious APIs). That seems reasonable. 
I didn't see RS0016. Let me know if I used incorrect repro steps, or whether you've sorted out the issue already. Thanks

**Comment by Evangelink** [comment]
@jcouv That's interesting, I have checked and through the command line I have the same behavior as you do but when building in VS I have a totally different output:
![image](https://user-images.githubusercontent.com/11340282/88456407-ecf5ff80-ce7d-11ea-8901-76982fac4e00.png)

**Comment by Evangelink** [comment]
Also @jcouv I have spent an hour trying to fix the `RS0041` raised but I can't find the right way to do the fix. As far as I understand, I need to updat the public api file to ensure there is no reference type defined without any nullability definition (either `?` or `!`) but looking at the file it seems ok for the type reported. The only thing is the generic type on the type definition but if I start adding them then I end up with `RS0017` api declared but not found.

**Comment by jcouv** [comment]
@Evangelink I suspect that two different versions of Roslyn are involved in those two scenarios (IDE and MSBuild). I suspect that the error `RS0017` results from using the publicAPI analyzer with an older version of Roslyn (here's a [previous investigation](https://github.com/dotnet/roslyn-analyzers/issues/3260#issuecomment-592675215) on this).

Out of curiosity, could you add `#error version` (prints a diagnostic with Roslyn version) and let me know what versions you get from IDE vs. MSBuild? Also, what version of VS are you using?

@mavasani Is there a way to get a binary log from the IDE build process to confirm what components/versions are involved?

**Comment by jcouv** [comment]
I can see the `RS0017` in error list too, but not when running "build.cmd". I think that's the key to figuring this out.
When I attach to that instance of VS and look at the loaded modules, I see:
- Microsoft.CodeAnalysis.PublicApiAnalyzers.dll (from C:\Users\jcouv\AppData\Local\Temp\VS\AnalyzerAssemblyLoader\3e113613cfd44265ae5a06cc67fd991c\7\Microsoft.CodeAnalysis.PublicApiAnalyzers.dll) with version 3.03.2.37301
- Microsoft.CodeAnalysis.CSharp.dll (from c:\program files (x86)\microsoft visual studio\2019\publicpreview\common7\ide\commonextensions\microsoft\managedlanguages\vbcsharp\languageservices\Microsoft.CodeAnalysis.CSharp.dll) with version 3.700.20.36607

Those versions should be adequate... I'll have to debug through.

**Comment by jcouv** [comment]
I'm trying to debug, but as far as I can tell, the publicAPI analyzer that produces those diagnostics isn't the one in the VS process.

I noticed something else: one of the diagnostics is `RS0017	Symbol '#nullable enable' is part of the declared API, but is either not public or could not be found`. This tells me that an old version of the publicAPI analyzer is getting involved, which doesn't parse `#nullable enable`... I'll try to confirm this hypothesis.

**Comment by jcouv** [comment]
Alright, I made some progress in my investigation. I have a command-line repro that let's me debug the issue.

It looks like two versions of the publicAPI code is getting run.
- version 1 (good): `Microsoft.CodeAnalysis.PublicApiAnalyzers.dll!Microsoft.CodeAnalysis.PublicApiAnalyzers.DeclarePublicApiAnalyzer.Impl.GetDeletedApiList() Line 698	C#` (note that this assembly has version `3.03.2.37301`)
- version 2 (which causes the problem): `Roslyn.Diagnostics.Analyzers.dll!Roslyn.Diagnostics.Analyzers.DeclarePublicAPIAnalyzer.Impl.OnCompilationEnd(Microsoft.CodeAnalysis.Diagnostics.CompilationAnalysisContext context) Line 428	C#`

Looking at `Roslyn.Diagnostics.Analyzers.dll` in my modules window, I see a fairly old version number:
`Roslyn.Diagnostics.Analyzers.dll	Roslyn.Diagnostics.Analyzers.dll	C:\Users\jcouv\.nuget\packages\roslyn.diagnostics.analyzers\2.6.3\analyzers\dotnet\cs\Roslyn.Diagnostics.Analyzers.dll	Yes	N/A	Symbols loaded.	C:\Users\jcouv\AppData\Local\Temp\SymbolCache\Roslyn.Diagnostics.Analyzers.pdb\7aa0635087e04520a8b095935be0e7561\Roslyn.Diagnostics.Analyzers.pdb	34	2.06.319.5902	<Unknown>	00000251CC5B0000-00000251CC5E8000	[9988] csc.exe	[1] csc.exe`

I think this old analyzer is the source of the problem. It's included into the compilation by `/analyzer:C:\Users\jcouv\.nuget\packages\roslyn.diagnostics.analyzers\2.6.3\analyzers\dotnet\cs\Roslyn.Diagnostics.Analyzers.dll`.

I'm not sure how to remove it.

**Comment by Evangelink** [comment]
Hi @jcouv, looks like you made a lot of progresses so I am not sure you do need the info but here they are:

- IDE: `error CS8304: Compiler version: '3.6.0-4.20251.5 (910223b6)'. Language version: preview.`
- Commande line: `error CS8304: Compiler version: '3.7.0-3.20269.11 (eb03bae8)'. Language version: preview.`

Also I wanted to say thank you for the investigation because now I have a good idea of what's wrong, and that seems related to one of my latest change. Basically, in `Version.props` we define the property `RoslynDiagnosticsAnalyzersVersion` with value `3.3.0-beta1.20351.1` (see [here](https://github.com/dotnet/roslyn-analyzers/blob/master/eng/Versions.props#L26), [here](https://github.com/dotnet/roslyn-analyzers/blob/master/eng/Versions.props#L31) and [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Directory.Build.props#L18)) but we had an explicit reference to an older version [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.AnalyzerUtilities/Microsoft.CodeAnalysis.AnalyzerUtilities.csproj#L22). I would say that this last line shall be removed but I am not entirely sure if it might break something (it was most likely added for a good reason which I don't have).

> Also @jcouv I have spent an hour trying to fix the `RS0041` raised but I can't find the right way to do the fix. As far as I understand, I need to updat the public api file to ensure there is no reference type defined without any nullability definition (either `?` or `!`) but looking at the file it seems ok for the type reported. The only thing is the generic type on the type definition but if I start adding them then I end up with `RS0017` api declared but not found.

I made a couple other tests but still cannot understand what's wrong and how I can fix the warning.

**Comment by mavasani** [comment]
> I would say that this last line shall be removed

That seems to be the problem. No project in the repo should explicitly reference a lower version of this package.

**Comment by jcouv** [comment]
@Evangelink You're welcome. Glad we got to the bottom of this mystery :-)
For warning `RS0041` (use of oblivious API), the fix is to put `#nullable enable` in the source file that declares the API and annotate it's reference types (choose between `string` and `string?`).
Also, just to be clear and potentially save you time, there shouldn't be a need to edit the publicAPI text file by hand. The fixers should assist for any necessary situation.

**Comment by mavasani** [comment]
> For warning RS0041 (use of oblivious API), the fix is to put #nullable enable in the source file that declares the API and annotate it's reference types (choose between string and string?).

@jcouv We have nullable enabled the whole repo in shared props file. Do we still need to add ‘#nullable enable’ to individual source file?

**Comment by mavasani** [comment]
Given the whole repo is already nullable enabled, I presume we should require no manual edits to any source file to resolve this issue. It should just need code fix application with FixAll in project.

**Comment by Evangelink** [comment]
> > For warning RS0041 (use of oblivious API), the fix is to put #nullable enable in the source file that declares the API and annotate it's reference types (choose between string and string?).
> 
> @jcouv We have nullable enabled the whole repo in shared props file. Do we still need to add ‘#nullable enable’ to individual source file?

I have tried forcing the `#nullable enable` on the file but I don't see any other issue showing up so I would be even more tempted to say there is a bug with the rule. All the buggy types are generic so I would also say it's probably related to generics.

**Comment by jcouv** [comment]
@Evangelink If you have a fix to remove the old `Roslyn.Diagnostics.Analyzers.dll` analyzer, can you push that into your PR? I will take a look at a couple of remaining RS0041 to advise. If the project already has `<Nullable>enable</Nullable>` then we indeed don't need `#nullable enable` in source.
