### ISSUE TITLE
Port FxCop rule CA1045: DoNotPassTypesByReference

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#391]
**Title:** Do not pass types by reference

**Description:**

Passing types by reference (using out or ref) requires experience with pointers, understanding how value types and reference types differ, and handling methods that have multiple return values. Library architects who design for a general audience should not expect users to master working with out or ref parameters.

**Dependency:** None

**Notes:**

**Comment by jjhayworth** [comment]
Check the source code for the [SonarSource implementation of this rule](https://rules.sonarsource.com/csharp/RSPEC-3874)
