### ISSUE TITLE
Allow configuring CA1822 to exclude public members

### ISSUE THREAD

**Issue by Dreamescaper** [dotnet/roslyn-analyzers#3911]
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v3.0.0 (Latest)

#### Diagnostic ID

CA1822: Mark members as static

#### Expected behavior

Currently CA1822 analyzes all members independently of access modifier (which is suitable in lots of cases). 
Still, that's not very useful if all the public members are considered as Public API, and cannot be changed because of backward compatibility. 
Still, I'd love to have this analyzer enabled for private members. 
Would be great to be able to configure to apply for non-public members only.

**Comment by Evangelink** [comment]
Looks like it is already available but the documentation website is not up-to-date. See [Analyzer Configuration.md#analyzed-api-surface](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#analyzed-api-surface)

**Comment by Evangelink** [comment]
Issue opened on doc side https://github.com/MicrosoftDocs/visualstudio-docs/issues/5629

**Comment by Evangelink** [comment]
Hum there is actually a second, implicit, point to that question. @mavasani Is it possible to somehow like rules suggesting a refactoring to the public api analyzer? The idea being that rules suggesting a signature change would not be raised for api listed in the shipped file.

**Comment by mavasani** [comment]
> Is it possible to somehow link rules suggesting a refactoring to the public api analyzer? The idea being that rules suggesting a signature change would not be raised for api listed in the shipped file.

That seems like a completely different feature request which is applicable to all design rules that can introduce a breaking public API change. Can you please file a separate issue? The CA1822 feature requested originally in this issue  has already been implemented.

**Comment by Evangelink** [comment]
Makes sense!

**Comment by Dreamescaper** [comment]
@Evangelink 
So I added line
`dotnet_code_quality.CA1822.api_surface                                   = private`
to .editorconfig file, but it changed nothing - diagnostic is still triggered for public methods. 
Do I miss anything?

**Comment by mavasani** [comment]
Can you please try latest package from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.FxCopAnalyzers&protocolType=NuGet&version=3.3.0-beta3.20375.1&view=versions

**Comment by Dreamescaper** [comment]
@mavasani 
Yes, it seems to work fine on latest beta, thanks!
