### ISSUE TITLE
Port FxCop rule CA1047: DoNotDeclareProtectedMembersInSealedTypes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#393]
**Title:** Do not declare protected members in sealed types

**Description:**

Types declare protected members so that inheriting types can access or override the member. By definition, sealed types cannot be inherited, which means that protected methods on sealed types cannot be called.

**Dependency:** None

**Notes:**
1. If VB compiler doesn't warn, implement VB analyzer. 2. In any case, implement fixer.

**Comment by pakdev** [comment]
Doesn't [CS0628](https://docs.microsoft.com/en-us/dotnet/articles/csharp/misc/cs0628) cover this?

**Comment by mavasani** [comment]
Yes, hence the note in the description above: `If VB compiler doesn't warn, implement VB analyzer. 2. In any case, implement fixer.`

**Comment by pakdev** [comment]
True, but it's pretty easy to miss that this rule doesn't need to be implemented
