### ISSUE TITLE
CA3075 warns that XmlReader.Create(string) is unsafe even though it delegates to a call that CA3075 considers safe

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-analyzers#3937]
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) 3.3.0-beta2.final, [CA3075](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3075)

These calls both delegate to `XmlReader.Create("x", settings: null, inputContext: null)` and are exactly equivalent:

```cs
// ⚠ CA3075 An insecure overload of XmlReader.Create which does not accept an XmlReaderSettings argument.
//                 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
using var reader = XmlReader.Create("x");
```

```cs
// No warning
using var reader = XmlReader.Create("x", settings: null);
```

**Comment by Evangelink** [comment]
Disclaimer: I am no expert on the subject.

Looking at the rule documentation, I can see

> The XmlReader.Create method is invoked with an insecure XmlReaderSettings instance or no instance at all.

so if the 2 overloads are equivalent, that means this is called with null (i.e. no instance at all) so I think it's ok to have an issue raised.

**Comment by jnm2** [comment]
I think these four things are all interchangeable in meaning and runtime behavior, yet the first has a warning and the rest (properly IMO) do not. They all result in a secure XmlReaderSettings instance being used on both .NET Core and .NET Framework.

- `XmlReader.Create("x")`
- `XmlReader.Create("x", new XmlReaderSettings())`
- `XmlReader.Create("x", settings: null")`,
- `XmlReader.Create("x", settings: null, inputContext: null)`

**Comment by Evangelink** [comment]
@dotpaul Shall we go in the direction of removing the warning for all these cases or the opposite and start raising for the following 3 cases:

- `XmlReader.Create("x", new XmlReaderSettings())`
- `XmlReader.Create("x", settings: null)`
- `XmlReader.Create("x", settings: null, inputContext: null)`

**Comment by jnm2** [comment]
Oh, I finally found what I meant to link above, where we had reported that `new XmlReaderSettings()` was incorrectly flagged even though DTD processing was already prohibited: https://github.com/dotnet/roslyn-analyzers/issues/1591#issuecomment-422036084
Fix: https://github.com/dotnet/roslyn-analyzers/pull/1916 I think this last case was overlooked.

**Comment by dotpaul** [comment]
I'll try to test these cases next week.

**Comment by Evangelink** [comment]
@dotpaul Is there anything left to do here?

**Comment by mavasani** [comment]
I believe github did not auto-close the issue as the PR was not targeting master branch. We should be able to close this one.
