### ISSUE TITLE
Port FxCop rule CA1048: DoNotDeclareVirtualMembersInSealedTypes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#394]
**Title:** Do not declare virtual members in sealed types

**Description:**

Types declare methods as virtual so that inheriting types can override the implementation of the virtual method. By definition, a sealed type cannot be inherited. This makes a virtual method on a sealed type meaningless.

**Dependency:** None

**Notes:**

Error in both C# and VB. Implement fixer.

**Comment by pakdev** [comment]
Covered by [CS0549](https://msdn.microsoft.com/en-us/library/exaxze9s(vs.71).aspx)

**Comment by mavasani** [comment]
Yep, this just needs the fixer.

**Comment by TKharaishvili** [comment]
I wasn't able to find the analyzer for this in the codebase...

**Comment by mavasani** [comment]
Closing this as won't fix. If we need a fixer for CS0549, it should likely be contributed in Roslyn repo.
