### ISSUE TITLE
Port FxCop rule CA1050: DeclareTypesInNamespaces

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#396]
**Title:** Declare types in namespaces

**Description:**

Types are declared in namespaces to prevent name collisions and as a way to organize related types in an object hierarchy.

**Dependency:** None

**Notes:**

Fixes wraps type in namespace and puts you in rename session for the namespace name.

**Comment by nguerrera** [comment]
@lgolding @srivatsn How are we tracking fixers now that we're prioritizing analyzers first. Do I leave the issues open until the fixer is implemented or will we create new issues for fixers?

**Comment by lgolding** [comment]
Leave the issue open and attach the label *Needs-Fixer*. Then we can ask the question "how many analyzers do we have left to write?" by querying for "issue is open AND issue does not have the Needs-Fixer label".

**Comment by jamesqo** [comment]
@333fred I can grab this. Do you know what APIs I can use to start a rename session?

**Comment by sharwell** [comment]
@mavasani I propose resolving the CA1050 code fix as **Won't Fix** in light of dotnet/roslyn#34223.

**Comment by Evangelink** [comment]
ping @mavasani

**Comment by mavasani** [comment]
I agree with @sharwell - closing this issue.
