### ISSUE TITLE
RS0037 fix-all duplicate `#nullable enable` lines if some API baselines exist

### ISSUE THREAD

**Issue by dougbu** [dotnet/roslyn-analyzers#3965]
### Describe the bug

Ran the RS0037 fixer on one of the filtered solutions in dotnet/aspnetcore, built again, and saw up to three RS0024 errors.

### Steps To Reproduce

1. `git clone --recurse-submodules git@github.com:dotnet/aspnetcore.git` # or use https://github.com/dotnet/aspnetcore.git
2. `.\restore.cmd` # to install the .NET SDK and any needed runtimes as well as restore all projects
3. `git switch --detach e13368391b` # ensure only some projects have `PublicApi.*.txt` files
4. `.\src\Analyzers\startvs.cmd` # open default Visual Studio instance on Analyzers.slnf
5. Build the filtered solution e.g. `F6`
6. Run RS0016 fix-all
7. `dir -r PublicApi.Shipped.txt |? {$_.Length -gt 25} |% FullName`

### Expected behavior

All of the `PublicApi.Shipped.txt` files except the one in src\submodules\MessagePack-CSharp\src\MessagePack\ should be essentially empty i.e. only that file should be listed.

### Actual behavior

All `PublicApi.Shipped.txt` files that previously existed in the repo are listed. These files are now invalid due to RS0024 errors.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/)

(Actually using the https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json feed.)

**Version**: 3.3.0-beta3.20405.2

**Diagnostic ID**: [RS0037](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

## Additional context

Ideal would be to remove the need to have `#nullable enable` in the API baseline files at all. See #3962 for more on that.

See also #3957

**Comment by mavasani** [comment]
Tag @jcouv
