### ISSUE TITLE
Port FxCop rule CA1051: DoNotDeclareVisibleInstanceFields

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#397]
**Title:** Do not declare visible instance fields

**Description:**

The primary use of a field should be as an implementation detail. Fields should be private or internal and should be exposed by using properties.

**Dependency:** None

**Notes:**

**Comment by srivatsn** [comment]
PR #740 plans to implement this rule. .

**Comment by srivatsn** [comment]
The right fix is to convert the field to a property and invoking the lightbulb on a field will bring up the "Encapsulate field" refactoring. So no fixer has been implemented for this rule and the stubs have been deleted.
