### ISSUE TITLE
Extend CA1707 rule

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#3984]
Interesting - I presume this is due to the fact that this rule only runs on public API surface by default? If so, we should have a follow-up PR to make this rule support [api_surface](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#analyzed-api-surface) option. Implementation would be as simple as invoking `symbol.MatchesConfiguredVisibility()` extension method instead of `symbol.IsExternallyVisible()`

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/3706_

**Comment by Evangelink** [comment]
Already done.
