### ISSUE TITLE
CA2000 false positive

### ISSUE THREAD

**Issue by APIWT** [dotnet/roslyn-analyzers#4000]
### Describe the bug

The CA2000 rule is throwing a false positive even for very simple cases of `using var disposable = ...`. The bug is only observed inside the IDE (in my case, Rider), but it does not appear at compile time.

### Steps To Reproduce

Please see the attached repro. Use any recent version of Rider (2020.2 or 2020.1.4 will work from my testing) and check the "Errors in Solution" tab with "warnings" selected.

### Expected behavior

I expected the warning not to occur in code analysis when used with a `using` declaration.

### Actual behavior

CA2000 is emitted.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA2000](https://docs.microsoft.com/visualstudio/code-quality/ca2000)

## Additional context

The screenshot attached might be helpful.
[CA2000Repro.zip](https://github.com/dotnet/roslyn-analyzers/files/5069657/CA2000Repro.zip)
<img width="1232" alt="Screen Shot 2020-08-13 at 10 33 59 AM" src="https://user-images.githubusercontent.com/45397889/90147781-8cf1cb00-dd50-11ea-9cd7-fd1958ed2d9f.png">

**Comment by APIWT** [comment]
Cross reported here just in case (but I seriously doubt this is a Rider bug because it disappears if I downgrade Microsoft.CodeAnalysis.FxCopAnalyzers to 3.0.0)
https://youtrack.jetbrains.com/issue/RIDER-49103

**Comment by mavasani** [comment]
@APIWT This seems to be due to your IDE being on older Microsoft.CodeAnalysis assemblies. Verified no repro on VS 2019 16.7.1:

![image](https://user-images.githubusercontent.com/10605811/90148486-37a9bf80-dd38-11ea-80fd-2135cb3813e8.png)

**Comment by APIWT** [comment]
@mavasani Thank you for the quick response! I'll link your comment in the Rider bug report. I really appreciate it.
