### ISSUE TITLE
CA1838 false positive on .NET Framework 4.8

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#4007]
### Describe the bug

CA1838 false positive on .NET Framework 4.8

### Steps To Reproduce

1. Create .NET Framework 4.8 project.
2. Add a P/Invoke call with StringBuilder.
3. Run code analysis.

### Expected behavior
CA1838 should not fire since ArrayPool does not exist in the .NET Framework 4.8.

### Actual behavior
CA1838 fires.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA1838](https://docs.microsoft.com/visualstudio/code-quality/ca1838)

**Comment by mavasani** [comment]
@elinor-fung The analyzer needs to bail out from CompilationStartAction if well-known type `ArrayPool` is not defined in the compilation.

**Comment by elinor-fung** [comment]
Actually, the message might be a bit misleading here. It should probably be `Consider using a character buffer instead`.

The suggestion is really to switch to a buffer - does not need to be from `ArrayPool`. The doc (just merged this morning, so not published yet) points out some different ways for fixing it, only one of which involves `ArrayPool`.

@avivanoff To double check - this rule should be disabled by default.  When I:
- Created a new .NET Framewok project
- Installed the Microsoft.CodeAnalysis.FxCopAnalyzers package (version 3.3.0)
- Added a P/Invoke call with StringBuilder.
- Ran code analysis

CA1838 did not fire - I explicitly enabled the rule and then it fired. When you had it fire, did you explicitly enable it?

**Comment by avivanoff** [comment]
@elinor-fung, yes, I enabled the rule.
