### ISSUE TITLE
Platform names should be in quotes

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn-analyzers#4008]
Since our capitalization for platform names will be off, we should put it in quotes to make it clear that's a dynamic value, rather than being part of the error message.

### Repro

```C#
static class Program
{
    public static void Main()
    {
        Some.WindowsSpecificApi();
    }
}

[SupportedOSPlatform("windows10.0")]
static class Some
{
    public static void WindowsSpecificApi()
    {
    }
}
```

### Expected

> 'WindowsSpecificApi' requires windows 10.0 version or later

### Actual

> 'WindowsSpecificApi' requires 'windows' 10.0 version or later

**Comment by buyaa-n** [comment]
[Fixed](https://github.com/dotnet/roslyn-analyzers/pull/3917/commits/28a7cba35522a24494a41dc66f6b12e52d173512#diff-cff6af5ad11b512db597e4afcb1934adR1435)

**Comment by Evangelink** [comment]
I don't know how things work so I might say something utterly stupid but based upon `[SupportedOSPlatform("windows10.0")]` I would have expected the message to be `'WindowsSpecificApi' requires 'windows10.0' version or later`.

**Comment by buyaa-n** [comment]
Closing as the main issue is solved. 

@Evangelink there is another [issue](https://github.com/dotnet/roslyn-analyzers/issues/4021) you can participate which discussing the messaging improvements
