### ISSUE TITLE
Error message should be grammatically correct

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn-analyzers#4011]
### Repro

```C#
using System.Runtime.Versioning;

[assembly: SupportedOSPlatform("windows7.0")]

static class Program
{
    public static void Main()
    {
        SomeWindowsSpecific.Api1();
        SomeWindowsSpecific.Api2();
    }
}

class SomeWindowsSpecific
{
    [SupportedOSPlatform("windows")]
    [UnsupportedOSPlatform("windows8.1")]
    public static void Api1() { }

    [SupportedOSPlatform("windows")]
    [ObsoletedInOSPlatform("windows8.1")]
    public static void Api2() { }
}
```

### Expected

> 'Api1' is not supported or has been removed since windows 8.1
> 'Api2' has been deprecated since windows 8.1

### Actual

> 'Api1' is not supported or has been removed since windows 8.1 version
> 'Api2' has been deprecated since windows 8.1 version

**Comment by buyaa-n** [comment]
[Fixed](https://github.com/dotnet/roslyn-analyzers/pull/3917/commits/28a7cba35522a24494a41dc66f6b12e52d173512#diff-cff6af5ad11b512db597e4afcb1934adR1441), thanks!
