### ISSUE TITLE
We should validate the syntax for platform names

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn-analyzers#4015]
This related to https://github.com/dotnet/runtime/issues/45851. We should also provide definition-site diagnostics if the syntax of the string passed to the attributes isn't of a valid platform name followed by an optional version.

**Note**: We don't need to handle the universal methods `OperatingSystem.IsPlatform()` and `OperatingSystem.IsPlatformAtLeast()` because the version is a separate argument and https://github.com/dotnet/runtime/issues/45851 will validate that the platform name is known.

**Comment by carlossanlop** [comment]
@buyaa-n @terrajobst was this approved in an API proposal in the runtime repo? If yes, can you please link the issue number?

**Comment by buyaa-n** [comment]
@terrajobst sorry, i am not sure what is this issue adding the proposal in dotnet/runtime#45851, i must be missing something. It seems to me this is covered by dotnet/runtime#45851

**Comment by buyaa-n** [comment]
Solved with https://github.com/dotnet/roslyn-analyzers/pull/4838
