### ISSUE TITLE
[loc][Query][dotnet_roslyn_analyzers] Localizability of strings

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn-analyzers#4029]
### Describe the bug

**String Resource ID:**	0; "AvoidAssemblyGetFilesInSingleFile"
**Source String**:	'{0}' will throw for assemblies embedded in a single-file app.
**Filename**:	NetAnalyzers\Core\Microsoft.NetCore.Analyzers\xlf\MicrosoftNetCoreAnalyzersResources.xlf
**Question**:	What will {0} be replaced with?

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA1716](https://docs.microsoft.com/visualstudio/code-quality/ca1716)

**Comment by Youssef1313** [comment]
I think this is determined by the second argument to CreateDiagnostic call in

https://github.com/dotnet/roslyn-analyzers/blob/4016ef289ceae25ceefe581577ae0000eeb613ef/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Publish/AvoidAssemblyLocationInSingleFile.cs#L101

and

https://github.com/dotnet/roslyn-analyzers/blob/4016ef289ceae25ceefe581577ae0000eeb613ef/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Publish/AvoidAssemblyLocationInSingleFile.cs#L113

**Comment by cristianosuzuki77** [comment]
Thanks.  Is it possible to give an example at this time?

**Comment by mavasani** [comment]
@agocke for help.

**Comment by Youssef1313** [comment]
@cristianosuzuki77 You may check the unit test for examples. The value that will be placed in place of {0} is what's passed to `WithArguments` method.

https://github.com/dotnet/roslyn-analyzers/blob/0c78e1ea111bbe72b97756898bd397f4c26587f5/src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Publish/AvoidAssemblyLocationInSingleFileTests.cs
