### ISSUE TITLE
Port FxCop rule CA1061: DoNotHideBaseClassMethods

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#403]
**Title:** Do not hide base class methods

**Description:**

A method in a base type is hidden by an identically named method in a derived type, when the parameter signature of the derived method differs only by types that are more weakly derived than the corresponding types in the parameter signature of the base method.

**Dependency:** None

**Notes:**

**Comment by mavasani** [comment]
I don't this a fixer can be added here, so closing this out.
