### ISSUE TITLE
Port FxCop rule CA1062: ValidateArgumentsOfPublicMethods

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#404]
**Title:** Validate arguments of public methods

**Description:**

All reference arguments that are passed to externally visible methods should be checked against null.

**Dependency:** Dataflow, use IOperation

**Notes:**

**Comment by srivatsn** [comment]
This rule should play nice with CodeContracts - see issue [here](https://social.msdn.microsoft.com/Forums/en-US/8016ba58-8ae1-483e-90ac-d14a4cb73a7c/ca1062-code-analysis-rule-is-broken-by-code-contracts?forum=codecontracts)
