### ISSUE TITLE
warning AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotContainTypeNames' threw an exception of type 'System.IndexOutOfRangeException' 

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#4052]
Thanks @mavasani 

See these warnings as well 😄 

```
2>C:\Users\david\source\repos\WebApplication2\APIPlayground\Program.cs(27,1,27,6): warning CA1812: <Program>$ is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).
2>CSC : warning AD0001: Analyzer 'Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.IdentifiersShouldNotContainTypeNames' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
```

_Originally posted by @davidfowl in https://github.com/dotnet/aspnetcore/issues/25077#issuecomment-678035542_

**Comment by mavasani** [comment]
@davidfowl do you have a repro to share?

**Comment by davidfowl** [comment]
- Install the latest RC1 from here https://github.com/dotnet/installer#installers-and-binaries
- Clone this https://github.com/davidfowl/CommunityStandUpNet5
- Open it in the dogfood build (Int preview)

BOOM 💥 

![image](https://user-images.githubusercontent.com/95136/90853734-d2edf680-e32f-11ea-9b6e-fcbea62e2b7d.png)

**Comment by kentyman23** [comment]
This was closed even though **_1812_** was never fixed.
