### ISSUE TITLE
CA2225 alternate name is wrong if operator type is SomeType[] (read SomeTypeArray)

### ISSUE THREAD

**Issue by Stiles-X** [dotnet/roslyn-analyzers#4063]
### Describe the bug

Alternate method name for operator is wrong (type missing), if that type is an array such as `byte[]`.

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Create a struct named MyStruct
2. Create an explicit operator method with signature `public static explicit operator byte[](MyStruct myStruct)`
3. Look in the warning window
4. See error `Warning	CA2225	Provide a method named 'To' or 'FromMyStruct' as an alternate for operator op_Explicit`

### Expected behavior

Suggests `ToByteArray` or `FromMyStruct`.

### Actual behavior

Suggests `To` or `FromMyStruct`.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA2225](https://docs.microsoft.com/visualstudio/code-quality/ca2225)

## Additional context

My code is using `byte[]` type operator specifically.

I have done my research and the bug is not the same as #3834. (Though, that bug still exists)

**Comment by Evangelink** [comment]
Shall we have a distinct suffix for arrays, multi-dimensional arrays and jagged arrays?

Tagging @mavasani for your point of view.
