### ISSUE TITLE
[LOC] [Query] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn-analyzers#4064]
### Describe the bug

Please answer the loc question below:
String Resource ID | 0; "DataSetReadXmlAutogeneratedTitle"
-- | --
Source String | Ensure autogenerated class containing DataSet.ReadXml() is not used with untrusted data
Subtenant | dotnet_roslyn_analyzers
Source Control Link |  
Filename | NetAnalyzers\Core\Microsoft.NetCore.Analyzers\xlf\MicrosoftNetCoreAnalyzersResources.xlf
Question | Is "DataSet.ReadXml()" a method? 0; "DataSetReadXmlAutogeneratedTitle" 0; "DataSetReadXmlTitle" 0; "DataTableReadXmlAutogeneratedTitle" 0; "DataTableReadXmlTitle"

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA1716](https://docs.microsoft.com/visualstudio/code-quality/ca1716)

**Comment by dotpaul** [comment]
Yes, "DataSet.ReadXml()" is a method.
