### ISSUE TITLE
CA1801 false positive on top level statements

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn-analyzers#4068]
### Steps To Reproduce

Create any program with top level statements that doesn't use `args` of `Main`.

### Expected behavior

No diagnostic reported.

### Actual behavior

Warning CA1801: The parameter `args` of `<Main>$` is unused.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)
Roslyn include in .NET 5 Preview 8 / VS 16.8P2

**Diagnostic ID**: [CA1801](https://docs.microsoft.com/visualstudio/code-quality/ca1801)

**Comment by mavasani** [comment]
Thanks, https://github.com/dotnet/roslyn-analyzers/pull/4066 should address this.
