### ISSUE TITLE
[LOC] [Query] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn-analyzers#4075]
### Describe the bug

Question about the string "Unsafe DataSet or DataTable type in web deserializable object graph" in the file NetAnalyzers\Core\Microsoft.NetCore.Analyzers\xlf\MicrosoftNetCoreAnalyzersResources.xlf:

Please clarify "web" in "web deserializable object graph". Does the mean "deserializable via the Internet"?
### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA1716](https://docs.microsoft.com/visualstudio/code-quality/ca1716)

**Comment by mavasani** [comment]
@dotpaul

**Comment by dotpaul** [comment]
Yes, "web" means "deserializable via the Internet". Maybe I should've called it "deserializable object graph within a web API".

**Comment by Evangelink** [comment]
@dotpaul Are you taking care of updating the resources?

**Comment by dotpaul** [comment]
> @dotpaul Are you taking care of updating the resources?

Nope.

**Comment by dotpaul** [comment]
If anyone has better ideas for the wording, please suggest. 😀

**Comment by Evangelink** [comment]
For info, the correct rule ID is `CA2356`. Reading the title and the message I actually think that's clear enough as-is and would suggest to close this. If there is still an issue I am pretty sure that some user will complain.
