### ISSUE TITLE
[loc][query] Translation assistance

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn-analyzers#4076]
### Describe the bug

Question about the string "Forward the 'CancellationToken' parameter to methods that take one to ensure the operation cancellation notifications gets properly propagated, or pass in 'CancellationToken.None' explicitly to indicate intentionally not propagating the token." in the file NetAnalyzers\Core\Microsoft.NetCore.Analyzers\xlf\MicrosoftNetCoreAnalyzersResources.xlf:

Could you please give us more context about what "that take one" means? Same for the string 0;"ForwardCancellationTokenToInvocationsTitle".
### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA1716](https://docs.microsoft.com/visualstudio/code-quality/ca1716)

**Comment by mavasani** [comment]
@carlossanlop

**Comment by mavasani** [comment]
@carlossanlop I think it would be better to change the rule title/message to just remove the "that take one" part - that is implicit from the rule.

**Comment by mavasani** [comment]
We should also update the titles in rule documentation: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2016?view=vs-2019

**Comment by Evangelink** [comment]
@carlossanlop Are you taking care of this one?

**Comment by Evangelink** [comment]
Ping @carlossanlop

**Comment by Evangelink** [comment]
@cristianosuzuki77 Are you still blocked on this translation?

**Comment by cristianosuzuki77** [comment]
Please consider closing this issue if you are modifying the string and removing the mention to this "that take one".

**Comment by mavasani** [comment]
Agreed, we should just remove the `that take one` from the message.

**Comment by mavasani** [comment]
@cristianosuzuki77 I see that you closed the issue, but the resource strings are still not fixed: https://github.com/dotnet/roslyn-analyzers/blob/5b9114fd4de2cbfba4b9b3dc979b6f48cf91de6c/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx#L1353-L1361

Re-opening to get the resx strings fixed, I'll create a PR.

**Comment by cristianosuzuki77** [comment]
Apologies.
