### ISSUE TITLE
Port FxCop rule CA1300: SpecifyMessageBoxOptions

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#408]
**Title:** Specify MessageBoxOptions

**Description:**

To correctly display a message box for cultures that use a right-to-left reading order, the RightAlign and RtlReading members of the MessageBoxOptions enumeration must be passed to the Show method.

**Dependency:** None

**Notes:**

**Comment by Youssef1313** [comment]
Best to implement this in https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms.Analyzers

I'll open an issue on dotnet/winforms and close this one.
