### ISSUE TITLE
CA1724 help link defaults to Bing search

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4096]
### Analyzer

**Diagnostic ID**: [CA1724](https://docs.microsoft.com/visualstudio/code-quality/ca1724): `Type names should not match namespaces`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

![image](https://user-images.githubusercontent.com/31348972/91637977-757f3700-ea0c-11ea-8d53-7b0459a9a009.png)

For some reason the help link is a Bing search instead of docs.microsoft.com

**Comment by Evangelink** [comment]
I am facing the same issue with the various rules I have tried. Looks like a bug...

Tagging @mavasani

**Comment by Youssef1313** [comment]
We probably need a single generic test that checks help url for **all** analyzers.

**Comment by Youssef1313** [comment]
The debugger shows the correct url. 
Not sure how to debug the issue then 😄 

![image](https://user-images.githubusercontent.com/31348972/91902637-526db500-eca2-11ea-9449-242e52084e13.png)

**Comment by mavasani** [comment]
@Youssef1313 @Evangelink Links are only valid for diagnostics from intellisense. Diagnostics from build don't currently hook up the descriptor associated with it, they are just generated from parsed build output, which don't have help links. Can you file a separate Roslyn feature request so build diagnostics can find the underlying descriptor based on diagnostic ID so hyperlinks work?

**Comment by Youssef1313** [comment]
@mavasani That's very strange. I actually get the correct URL for other analyzers.

**Comment by mavasani** [comment]
oh okay, then maybe another issue.

**Comment by Youssef1313** [comment]
This is an example where the URL is correct, in case it might be useful to compare the behavior with the incorrect one:

![image](https://user-images.githubusercontent.com/31348972/91904148-babd9600-eca4-11ea-857d-c8af0acc3972.png)

Some analyzers (but that's not the case with CA1724), use `new DiagnosticDescriptor(..)`, these are expected **not** to work correctly, because in that case they may bypass:

https://github.com/dotnet/roslyn-analyzers/blob/cbc39cb77b853506ba1067029f0d9835069ceb3c/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L32

https://github.com/dotnet/roslyn-analyzers/blob/cbc39cb77b853506ba1067029f0d9835069ceb3c/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L44

But with CA1724 it's using the helper method, not `new DiagnosticDescriptor`.

**Comment by mavasani** [comment]
> Some analyzers (but that's not the case with CA1724), use new DiagnosticDescriptor(..), these are expected not to work correctly

All CA analyzers should be using the helper, we also have an analyzer that enforces it.

> But with CA1724 it's using the helper method, not new DiagnosticDescriptor.

Yeah seems like a different issue.

**Comment by Youssef1313** [comment]
> All CA analyzers should be using the helper, we also have an analyzer that enforces it.

https://github.com/dotnet/roslyn-analyzers/blob/39d189ab8b48b3811978edbafdc0aef190025f53/src/Text.Analyzers/Core/IdentifiersShouldBeSpelledCorrectly.cs#L37

**Comment by mavasani** [comment]
Ah, so CA1724 is a CompilationEndAction: https://github.com/dotnet/roslyn-analyzers/blob/889acde2cf6e09530ce0d6a8315324643d4af72f/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypeNamesShouldNotMatchNamespaces.cs#L80

It will never run on live analysis, only on build, so it is the issue I initially thought. This will need a Roslyn feature request to ensure diagnostics from build are hooked up to the the descriptor properties.

**Comment by mavasani** [comment]
@Youssef1313 That package is not shipped and has no supported diagnostics: https://github.com/dotnet/roslyn-analyzers/blob/39d189ab8b48b3811978edbafdc0aef190025f53/src/Text.Analyzers/Core/IdentifiersShouldBeSpelledCorrectly.cs#L182-L193

**Comment by Youssef1313** [comment]
Great. I opened an issue against dotnet/roslyn repo.

**Comment by Youssef1313** [comment]
@Evangelink @mavasani Should I close this? Nothing can be done from the analyzer side. This only requires things to be fixed on roslyn's side.

**Comment by Evangelink** [comment]
I'd say so.
