### ISSUE TITLE
Adjust the error message for CA1309

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn-analyzers#4097]
Currently this shows up as 

```
error CA1309: Use ordinal stringcomparison
```

It should either use the expected API verbatim i.e.

```
error CA1309: Use StringComparison.Ordinal
```

or use plain text
```
error CA1309: Use ordinal string comparison
```

I'd prefer the first.

**Comment by mavasani** [comment]
Agreed. Should be a simple change to update the below resource string and corresponding xlf files: https://github.com/dotnet/roslyn-analyzers/blob/759cbfac86bf985bed87e56651d45e22c8234391/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/MicrosoftNetCoreAnalyzersResources.resx#L210-L212

**Comment by mavasani** [comment]
Actually it seems the analyzer/fixer preserves IgnoreCase: https://github.com/dotnet/roslyn-analyzers/blob/79c2638f54b9e7ef0a3954cc838ec4c13ea63c1f/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/UseOrdinalStringComparison.Fixer.cs#L29-L30

So, we can't use the first form. I'll create a PR to use the second form.
