### ISSUE TITLE
Question: what's the suggested usage between NetAnalyzers and FxCopAnalyzers?

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn-analyzers#4100]
After reading the [post](https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/) in devblog, I've got some questions:

- Is it supported to use the two analyzer packages at the same time?
![image](https://user-images.githubusercontent.com/5644458/91712261-f7609300-ebb9-11ea-9907-863ca81bf40c.png)
After upgrading to .NET 5 Preview 8, there is a warning icon in IDE for FxCopAnalyzers package. I'm afraid there's some conflict between the two packages.

- What's the suggested way to **aggressively opt-in** more **up-to-date analysis**?
FxCopAnalyzers and NetAnalyzers carries many analyzers, and some of them are old and not suitable for .NET 5. The default severity of FxCopAnalyzers looks too aggressive, where NetAnalyzers looks too loose. It's unclear that which rule set is suggested.
I mentioned https://github.com/dotnet/roslyn-analyzers/issues/4002#issuecomment-673561776 . But there are also other analyzers defaults to a different severity level like CA1305.

**Comment by mavasani** [comment]
@huoyaoyuan Thank you for reporting the issue.

> Is it supported to use the two analyzer packages at the same time?
1. The set of CA analyzers that ship in FxCop analyzers package and NetAnalyzers in the .NET SDK are currently identical. So you don't need both set.
2. FxCopAnalayzers NuGet package explicitly turns off built-in NetAnalyzers in the SDK and ensures no duplicate analysis. The warning icon in the package seems unrelated, I am not sure why it is showing up for you.

> aggressively opt-in more up-to-date analysis

This is a very good point, and I believe lot of customers would want a more aggressive opt-out mode. One simple trick that you can use is define `dotnet_analyzer_diagnostic.severity = warning` in your .editorconfig. This will default all enabled by default analyzers in your project to be warning by default. However, note that this will not turn of disabled analyzers, similar to the feature requested here: https://github.com/dotnet/roslyn/issues/47046. We do have many disabled analyzers to keep the NetAnalyzers shipping in the box conservative, and lot of folks would want a single entry to turn on the applicable ones. I think it is reasonable to consider adding an MSBuild property similar to `AnalysisLevel` that enables switching analyzers from opt-in conservative mode to an opt-out aggressive mode. Let's track this feature request with this issue.
