### ISSUE TITLE
CA3075 DoNotUseInsecureDtdProcessing - false positive when using a serializer which delegates to another serializer after setting the safe properties

### ISSUE THREAD

**Issue by bichuga** [dotnet/roslyn-analyzers#4106]
### Analyzer

**Diagnostic ID**: [CA3075](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3075?view=vs-2019): `Unsafe overload of 'Deserialize' method`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 4.72 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [net472](https://dotnet.microsoft.com/download/dotnet-framework/net472)

### Describe the bug

CA3075 fires a false positive violation when calling Deserialize on our SafeXmlSerializer implementation of XmlSerializer. Our implementation explicity sets DtdProcessing.Prohibit and XmlResolver to null and then delegates to base.Deserialize. 

### Steps To Reproduce

     private readonly SafeXmlSerializer xmlSerializer = new SafeXmlSerializer();
---
     using (Stream stream = this.GetReadStream())
     {
        return this.xmlSerializer.Deserialize(stream); // CA3075 violation
     }
---
    public class SafeXmlSerializer : XmlSerializer
    {
        /// <summary>
        /// Deserializes the XML document contained by the specified Stream.
        /// </summary>
        /// <param name="stream">The Stream that contains the XML document to deserialize.</param>
        /// <returns>The Object being deserialized.</returns>
        public new object Deserialize(Stream stream)
        {
            XmlTextReader xtr = new XmlTextReader(stream);
            xtr.DtdProcessing = DtdProcessing.Prohibit;
            xtr.XmlResolver = null;
            return base.Deserialize(xtr);
        }
    }

### Expected behavior
This usage is safe. The analyzer needs to check if the XmlSerializer is calling out to a different XmlSerializer and check the state of DtdProcessing/XmlResolver at the point of delegation.

### Actual behavior
CA3075 violation. Analyzer looks at DtdProcessing/XmlResolver on the initial Deserialize call.

**Comment by dotpaul** [comment]
Thanks for the report @bichuga. Unfortunately, an analyzer can't always examine the implementation of an overridden / explicitly hidden method (e.g. if the implementation lives in a different assembly than the calling code).

As a work around for the example in the repro, you could have a SafeDeserialize() method that does what you want, at least for callers that know they're using a SafeXmlSerializer instead of an XmlSerializer.

**Comment by mavasani** [comment]
@dotpaul Close this as by design?
