### ISSUE TITLE
Port FxCop rule CA1303: DoNotPassLiteralsAsLocalizedParameters

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#411]
**Title:** Do not pass literals as localized parameters

**Description:**

An externally visible method passes a string literal as a parameter to a constructor or method in the .NET Framework class library, and that string should be localizable.

**Dependency:** Dataflow

**Notes:**

**Comment by mavasani** [comment]
This rule uses StringContent dataflow analysis and should be implementable once we merge https://github.com/dotnet/roslyn-analyzers/pull/1541

**Comment by mavasani** [comment]
#1541 is merged.
