### ISSUE TITLE
Forward cancellation token codefix passes the cancellation token more than once

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4115]
GIF:

![ForwardCancellationToken](https://user-images.githubusercontent.com/31348972/91975741-285ad800-ed20-11ea-9d04-8aef143474f7.gif)

Note: the preview shows the correct behavior, but when the fix is applied it doesn't match the shown preview.

cc: @carlossanlop

**Comment by mavasani** [comment]
@Youssef1313 Which analyzer package are you using? I believe this was fixed. Can you try the latest pre-release package from https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet5?

**Comment by mavasani** [comment]
Ah, I guess this is in Roslyn.sln? Need a package upgrade in Roslyn: https://github.com/dotnet/roslyn/blob/4eca967f780e307b098e9d76d82e851983e7023f/eng/Versions.props#L31

Need to change to `5.0.0-rc2.20451.1` from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet&version=5.0.0-rc2.20451.1&view=overview

**Comment by Youssef1313** [comment]
> 
> 
> Ah, I guess this is in Roslyn.sln? Need a package upgrade in Roslyn: https://github.com/dotnet/roslyn/blob/4eca967f780e307b098e9d76d82e851983e7023f/eng/Versions.props#L31
> 
> Need to change to `5.0.0-rc2.20451.1` from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet&version=5.0.0-rc2.20451.1&view=overview

Yes it was Roslyn.sln.

Closing as it's external issue. Thanks!
