### ISSUE TITLE
Undocumented rule - CA1416

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4120]
CA1416 is undocumented

<https://docs.microsoft.com/visualstudio/code-quality/ca1416> shows 404.

I don't see the rule Id existing in any RulesMissingDocumentation.md file.

**Comment by mavasani** [comment]
@buyaa-n

**Comment by buyaa-n** [comment]
i have draft PR open for VS doc https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7088, i don't think we need to keep this one
