### ISSUE TITLE
Can GenerateDocumentationAndConfigFiles be replaced with source generator?

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4127]
I haven't dealt with source generators before. But if can be used, that won't require explicit run of `msbuild \t:pack` to generate the required files. Instead, they will be generated when compiling. That will keep the files up-to-date more frequently.

**Comment by mavasani** [comment]
@Youssef1313 That post build tool does not generate any source files, and generated files don't need to be part of the compilation. Source generators are primarily for generating sources.

**Comment by Youssef1313** [comment]
@mavasani Thanks! I thought it's capable of generating any kind of files based on the source code in compilation. Thanks for clearing my misunderstanding. Closing
