### ISSUE TITLE
Update the code fix to respect markdown rules

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4131]
@mavasani FYI, the code that generates this need to be updated to respect markdown rules, i.e. leave blank lines around headings.

See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022---headings-should-be-surrounded-by-blank-lines

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn-analyzers/pull/4126#discussion_r483723333_

**Comment by Evangelink** [comment]
@Youssef1313 Do you want to handle the ticket?

**Comment by Youssef1313** [comment]
@Evangelink I'm not very familiar with this area and how exactly it works. So I think someone else can get it faster than me. But if it became a stale for a while, I'll probably give it a try.

**Comment by Evangelink** [comment]
I'll take care of it :)

**Comment by Evangelink** [comment]
@mavasani Shall I use `Environment.NewLine` or force the `\n` line ending? I am a bit concerned that we might have some errors with non-windows environments. I guess I could probably start with the `NewLine` and wait to see results of the ubuntu pipeline.

**Comment by Youssef1313** [comment]
@Evangelink The fixer currently appends `Environment.NewLine` (it uses StringBuilder.AppendLine):

https://github.com/dotnet/roslyn-analyzers/blob/b148fa89c974a72c28184931767835709f34d1fa/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/AnalyzerReleaseTrackingFix.cs#L438

**Comment by Evangelink** [comment]
Thanks @Youssef1313! I wrote my comment before looking at the code and then thought it was a stupid question but felt weird to delete my comment afterward.

**Comment by Evangelink** [comment]
@Youssef1313 do you recall if there was anything else than the header blank line that wasn't covered?

**Comment by Youssef1313** [comment]
@Evangelink I don't. But we'll know when markdownlint is enabled.
