### ISSUE TITLE
CA2249 codefix menu item text improvement

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/roslyn-analyzers#4134]
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v3.3.0

#### Diagnostic ID

[CA2249](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca2249)

#### Repro steps

![image](https://user-images.githubusercontent.com/350947/92303020-9cada980-efb4-11ea-9199-299646336379.png)

The text "Consider ..." doesn't feel right for this menu. These are directives for action, not contemplation.

Instead it should read as "Use string.Contains instead of string.IndexOf"

**Comment by Evangelink** [comment]
Any preference between:

1. Use 'string.Contains' instead of 'string.IndexOf'
2. Replace with 'string.Contains'

I would go the option 2 as it seems more in line with how the other entries are named but I am open to suggestions.
