### ISSUE TITLE
CA1508 forces to refactor condition - but there is none

### ISSUE THREAD

**Issue by SebastianSchumann** [dotnet/roslyn-analyzers#4140]
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1508?view=vs-2019): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Steps to reproduce

The following minimalized code reports CA1508:

    public static byte[] ToBytes(this Image self)
    {
        _ = self ?? throw new ArgumentNullException(nameof(self));

        // CA1508: ... is never null. Remove or refacter the condition.
        using var stream = new MemoryStream();

        // Unnecessary Code omitted...

        return stream.ToArray();
    }

Another version that doesn't contain that null check is:

    public static byte[] ToBytes(Image self)
    {
        // CA1508: ... is never null. Remove or refacter the condition.
        using var stream = new MemoryStream();

        _ = self?.GetHashCode();
        return stream.ToArray();
    }

Any usage of this parameter (an extension method is not needed, any normal parameter will cause that error) is needed. If the parameter is not used, the problem disappears.

### Expected behavior

CA1508 should not be reported.

### Actual behavior

CA1508 is reported.

**Comment by mavasani** [comment]
@SebastianSchumann Seems like you are on an older VS/compiler toolset. I cannot repro your issue when using VS2019 16.7:

![image](https://user-images.githubusercontent.com/10605811/92502252-76565c80-f1b4-11ea-868f-c2c1c5b430e8.png)

**Comment by SebastianSchumann** [comment]
Nope. I'm using 16.7.2. That is current Version.

I'm currently at Home and can't test anything.

My Code does not contain the second null equality Check. Try the Code that I Provider.

**Comment by mavasani** [comment]
Second equality check is not required, that was added just to confirm that the analyzer is running, and is not producing the reported false positive here.

**Comment by SebastianSchumann** [comment]
I've new information:

* Today was an update for VS2019 available 16.7.3 - I installed it but the problem still remains.
* The problem ist not reproducable if you build an executable - a class library is required.
* There is also an `.editorconfig` needed that forces CA1508 to be an error.

I attached a project that causes this error. Please don't be distracted by the project name but I startet to reproduce is using a console application and switched to class library.

The project uses the following settings:

* Build against .Net Framework 4.7.2
* Add language support to _latest_ to activate C#8 features (default is C# 7.3).
* Using package references.
* Run code analysis at build.
* `.editorconfig` that causes CA1508 to be an error.
* Treat warnings as errors is set to `true`.

![image](https://user-images.githubusercontent.com/53967752/92559625-3f924c00-f271-11ea-94a3-f24d5bfc92b5.png)

 
[ConsoleApp1.zip](https://github.com/dotnet/roslyn-analyzers/files/5192835/ConsoleApp1.zip)

**Comment by SebastianSchumann** [comment]
It seams that the problem is fixed in 3.3.1 using VS 16.7.7.
