### ISSUE TITLE
CA2214: false positive

### ISSUE THREAD

**Issue by SebastianSchumann** [dotnet/roslyn-analyzers#4142]
### Analyzer

**Diagnostic ID**: [CA2214](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214): `Do not call overridable methods in constructors`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

I'm using [The Asynchronous Initialization Pattern from Stephen Cleary](https://blog.stephencleary.com/2013/01/async-oop-2-constructors.html) that encapsulates an init method into a `Task` to be awaited in every public async method.

### Steps To Reproduce

The following code produces a report of CA2214 for `InitializeAsync`. But this method is not called in ctor. It is called in a `Task.Run` that is created at first access.

    private readonly Lazy<Task> _initialization;

    protected Ctor()
    {
        // CA2214 is reported for "InitializeAsync" but it is not called in ctor.
        Task RunInit() => this.InitializeAsync(this.DisposeCts.Token);
        this._initialization = new Lazy<Task>(() => Task.Run(RunInit, this.DisposeCts.Token), isThreadSafe: true);
    }
    
    protected CancellationTokenSource DisposeCts { get; } = new CancellationTokenSource();
    
    protected Task Initialization => this._initialization.Value;
    
    protected virtual async Task InitializeAsync(CancellationToken cancellationToken)
    {
        // Content doesn't matter
    }

### Expected behavior

CA2214 should not be reported.

### Actual behavior

CA2214 is reported.

## Additional context

If the ctor-code changes to

    this._initialization = new Lazy<Task>(() => Task.Run(InitializeAsync, this.DisposeCts.Token), isThreadSafe: true);

the report disappears. But this does not allow to forward a CancellationToken. Yes the code above does not need to forward a CancellationToken because we can access `DisposeCts` directly. The presented code is simplyfied. Please keep in mind that there might be a need to forward an external CancellationToken.

**Comment by mavasani** [comment]
Seems like a simple fix. We should change the call from `IsInsideAnonymousFunction` to `IsWithinLambdaOrLocalFunction`:

Current: https://github.com/dotnet/roslyn-analyzers/blob/6dea9b867e32607bc02f958efe46d4b2d1220e45/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/DoNotCallOverridableMethodsInConstructors.cs#L68

Should instead call this extension: https://github.com/dotnet/roslyn-analyzers/blob/6dea9b867e32607bc02f958efe46d4b2d1220e45/src/Utilities/Compiler/Extensions/IOperationExtensions.cs#L500
