### ISSUE TITLE
CA2100 crashes during build on seemingly unrelated code

### ISSUE THREAD

**Issue by alexrp** [dotnet/roslyn-analyzers#4150]
### Analyzer

**Diagnostic ID**: [CA2100](https://docs.microsoft.com/visualstudio/code-quality/ca2100): `Review SQL queries for security vulnerabilities`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

Crashes during build.

### Steps To Reproduce

```csharp
class Program
{
    static void Main()
    {
        foreach (System.Diagnostics.ProcessModule mod in System.Diagnostics.Process.GetCurrentProcess().Modules)
            System.Console.WriteLine(mod.FileName);
    }
}
```

### Expected behavior

No warnings/errors.

### Actual behavior

```
CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Users\alex\source\repos\tests\tests.csproj]
CSC : warning AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Data.ReviewSqlQueriesForSecurityVulnerabilities' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\Users\alex\source\repos\tests\tests.csproj]
```

**Comment by Evangelink** [comment]
I cannot reproduce the error with your snipped and v3.3.0 of the analyzer.

@Youssef1313 I see that you have done a PR with a test which doesn't fail, have you been able to reproduce the error?

**Comment by Youssef1313** [comment]
@Evangelink I haven't tried locally. Only added a test which doesn't fail.

**Comment by mavasani** [comment]
I too verified this and it doesn't repro locally for me. @alexrp Can you please try to do a build with `msbuild /v:diag`, which should dump the full exception stack trace in the build output?

**Comment by alexrp** [comment]
@mavasani well... I would love to give you a stack trace, but I just went to compile the (unaltered) repro and it no longer happens. There's been absolutely no change in my .NET environment since yesterday. I actually can't explain that.

@Youssef1313 the project file is:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.0" />
  </ItemGroup>

</Project>
```

Not sure what to make of this situation. 😕

**Comment by mavasani** [comment]
It could very well be a race condition. However, we will need a dump, exception stack trace or a repro project to investigate further. Feel free to reopen the issue if you can get any of these in future. Thanks!
