### ISSUE TITLE
[loc][query] Assistance with translation

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/roslyn-analyzers#4152]
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/visualstudio/code-quality/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-preview.8](https://dotnet.microsoft.com/download/dotnet/5.0)

_OR_

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

String Resource ID | 0; "AvoidExcessiveInheritanceMessage"
-- | --
Source String | '{0}' has an object hierarchy '{1}' levels deep within the defining module. If possible, eliminate base classes within the hierarchy to decrease its hierarchy level below '{2}': '{3}'.
Subtenant | dotnet_roslyn_analyzers
Source Control Link |  
Filename | NetAnalyzers\Core\Microsoft.CodeQuality.Analyzers\xlf\MicrosoftCodeQualityAnalyzersResources.xlf
Question | Would you please clarify the placeholders?

**Comment by mavasani** [comment]
Does the below help?

![image](https://user-images.githubusercontent.com/10605811/92655725-b39b1700-f2a6-11ea-9e38-a89674a5edf3.png)
