### ISSUE TITLE
Consider mentioning the default rule severity in the rule reference

### ISSUE THREAD

**Issue by roji** [dotnet/roslyn-analyzers#4179]
The [.NET Code Analysis Rules section](https://docs.microsoft.com/visualstudio/code-quality/code-analysis-for-managed-code-warnings) lists information about each rule, but its default severity isn't left out (as specified in in the predefined ruleset/editorconfig files).

**Comment by Evangelink** [comment]
I think this issue shall be moved to the vs-docs repo, could you confirm @mavasani ?

**Comment by mavasani** [comment]
> I think this issue shall be moved to the vs-docs repo

@gewarren soon plans to move all the ported CA analyzer docs to dotnet docs repo. I think we need to first decide if we feel the default severity and enabled by default value needs to be added to the CA rule docs or not. If we decide to add + maintain this info, then it makes sense to port it to one of the docs repo.
