### ISSUE TITLE
Port FxCop rule CA1402: AvoidOverloadsInComVisibleInterfaces

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#418]
**Title:** Avoid overloads in ComVisible interfaces

**Description:**

When overloaded methods are exposed to COM clients, only the first method overload retains its name. Subsequent overloads are uniquely renamed by appending to the name an underscore character '_' and an integer that corresponds to the order of declaration of the overload.

**Dependency:** None

**Notes:**

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
