### ISSUE TITLE
PlatformCompatibilityAnalyzer seems to prevent compilation from completing

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn-analyzers#4182]
### Analyzer

**Diagnostic ID**: I think this is the PlatformCompatibilityAnalyzer but I'm not sure as the build never complete

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: 5.0.100-rc.1.20452.10

### Describe the bug

The build never completes. It uses lots of CPU and the memory keeps increasing (> 2GB) when I add the `[SupportedOSPlatform]` attribute in the following code.

![image](https://user-images.githubusercontent.com/509220/93718538-1e700c00-fb4b-11ea-9a19-985e2f21c6c5.png)

### Steps To Reproduce

Compile the following code using `dotnet build`:

````csharp
#nullable disable
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace Repro
{
    public static partial class ProcessExtensions
    {
        public static int? GetParentProcessId(this Process process)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                foreach (var entry in GetProcesses())
                {
                }
            }
            else
            {
                string line = "";
                while (true)
                {
                    if (line.StartsWith("", StringComparison.Ordinal))
                    {
                        if (true)
                        {
                        }
                    }
                }
            }

            return null;
        }

        [SupportedOSPlatform("windows")]
        public static IEnumerable<int> GetProcesses() => throw null;
    }
}
````

````xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
````

### Expected behavior

The compilation should complete

### Actual behavior

The compilation doesn't complete.

- If you remove the `[SupportedOSPlatform("windows")]`, the code compiles.
- If you remove a statement from the method, it compiles.

**Comment by mavasani** [comment]
Thanks, I will investigate.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/4185 in RC2 branch.
