### ISSUE TITLE
Port FxCop rule CA1403: AutoLayoutTypesShouldNotBeComVisible

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#419]
**Title:** Auto layout types should not be ComVisible

**Description:**

Auto layout types are managed by the common language runtime. The layout of these types can change between versions of the .NET Framework, which will break COM clients that expect a specific layout. Note that if the StructLayoutAttribute attribute is not specified, the C#, Visual Basic, and C++ compilers specify the Sequential layout for value types.

**Dependency:** None

**Notes:**

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
