### ISSUE TITLE
SyntaxTree.DiagnosticOptions has actually been deprecated in future Roslyn versions and always returns empty options. I need to fix up the logic here.

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#4224]
SyntaxTree.DiagnosticOptions has actually been deprecated in future Roslyn versions and always returns empty options. I need to fix up the logic here.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/4222#discussion_r494944018_

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/4402
