### ISSUE TITLE
Are the FlowAnalysis.Utilities / AnalyzerUtilities APIs ready to be consumed by 3rd party analyzers?

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [dotnet/roslyn-analyzers#4239]
Analyzer package
[Microsoft.CodeAnalysis.FlowAnalysis.Utilities](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FlowAnalysis.Utilities/) / [Microsoft.CodeAnalysis.AnalyzerUtilities](https://www.nuget.org/packages/Microsoft.CodeAnalysis.AnalyzerUtilities/)

We are considering the option to use the data flow analysis engine from `Microsoft.CodeAnalysis.FlowAnalysis.Utilities`/ `Microsoft.CodeAnalysis.AnalyzerUtilities` and we have a few questions:

1. Is the package meant to be used as a library by 3rd party analyzers? Is the API stable enough for this? I've noticed that there is a [PublicAPI.Shipped.txt](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.AnalyzerUtilities/PublicAPI.Shipped.txt) empty file and a [PublicAPI.Unshipped.txt](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.AnalyzerUtilities/PublicAPI.Unshipped.txt) file with all APIs, but I don't know how these are used and whether before each release you move the APIs from Unshipped to Shipped?
2. We've seen that the package doesn't declare explicit dependencies, however we were wondering what dependencies there are between the package and the Roslyn lifecycle?
3. Do you have more documentation about the APIs (more than the one on[ Writing dataflow analysis based analyzers](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Writing%20dataflow%20analysis%20based%20analyzers.md))?

Note: we've also asked this [on discord](https://discord.com/channels/143867839282020352/143867839282020352/760168344204083200), and were guided to post the question here. Please let me know if we need to use a different channel to ask this sort of questions.

Thank you.

**Comment by Evangelink** [comment]
Tagging @mavasani

**Comment by andrei-epure-sonarsource** [comment]
Thank you, @mavasani . I have some additional questions, mainly from the context of backwards compatibility. To give some context, our analyzers are currently compatible with VS 2015 Update 3 and higher, and historically we have tried to keep backwards compatibility with what VS versions are still supported by Microsoft.

By checking the sources we have noticed that `Microsoft.CodeAnalysis.FlowAnalysis.Utilities` implicitly relies on Roslyn 2.9.0 (Microsoft.CodeAnalysis) and that `Microsoft.CodeAnalysis.AnalyzerUtilities` relies on Roslyn 3.3.0.

1. Does this mean that by using the latest version of `AnalyzerUtilities` we will only be able to offer support for Visual Studio 2019 version 16.3, and newer?
2. Are there plans in the future to have a Roslyn minimum supported version? Or can we expect drops of compatibility between versions?

> This package only depends on the core Microsoft.CodeAnalysis NuGet package and the version of the package will always match the version of Microsoft.CodeAnalysis NuGet package that it is built against, and it will work fine on whichever VS/compiler versions that the corresponding Microsoft.CodeAnalysis NuGet package works on.

Regarding forward-compatibility, is there a possibility that the `Microsoft.CodeAnalysis.AnalyzerUtilities` may rely on Roslyn CFG API functionalities that may change in future versions of Roslyn (does the Roslyn CFG API design consider backwards compatibility with older versions)?

Thank you.

**Comment by mavasani** [comment]
> Does this mean that by using the latest version of AnalyzerUtilities we will only be able to offer support for Visual Studio 2019 version 16.3, and newer?

Yes, that is correct. `Microsoft.CodeAnalysis.AnalyzerUtilities` needs  Visual Studio 2019 version 16.3 (16.8 recommended) and `Microsoft.CodeAnalysis.FlowAnalysis.Utilities` needs Visual Studio 2019 version 15.9

> Are there plans in the future to have a Roslyn minimum supported version? Or can we expect drops of compatibility between versions?

There are no plans as of now to publish a fully supported package with guaranteed no API breaks in future. This package is mainly a helper package which will likely have APIs breaks as you move forward.

**Comment by mavasani** [comment]
> does the Roslyn CFG API design consider backwards compatibility with older versions

I believe that is the case, the CFG will not have any breaking API changes, though the underlying CFG operations and basic block structure can change between Roslyn versions. Feel free to file a new issue on Roslyn repo if you have more questions about CFG API or structure itself.

**Comment by Evangelink** [comment]
@andrei-epure-sonarsource I will let you close this ticket if you think all your questions have been answered.

**Comment by andrei-epure-sonarsource** [comment]
thank you @mavasani for the answers and @Evangelink for the help!
