### ISSUE TITLE
Port FxCop rule CA1408: DoNotUseAutoDualClassInterfaceType

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#424]
**Title:** Do not use AutoDual ClassInterfaceType

**Description:**

Types that use a dual interface enable clients to bind to a specific interface layout. Any changes in a future version to the layout of the type or any base types will break COM clients that bind to the interface. By default, if the ClassInterfaceAttribute attribute is not specified, a dispatch-only interface is used.

**Dependency:** None

**Notes:**

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
