### ISSUE TITLE
How to share rule settings?

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/roslyn-analyzers#4250]
I have multiple git repositories and I'd like to share my CA rule settings among them. At the moment I have my rules configured via `.editorconfig` and on every configuration change, I manually copy the .editorconfig to all my repositories - but this is not actually ideal.

So, I was wondering if the Roslyn Analyzers have any means (or recommendations) on how to share rule settings across repositories.

Ideally I would include the rules as git submodule into every repository.

I've found this [section in the Analyzer Configuration document](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#enabling-editorconfig-based-configuration-for-a-project) and while the text under **Prior to VS2019 16.3 or using an analyzer package version prior to 3.3.x** seems to describe what I need, it sound very much like "we support this for legacy reasons but you should not use it". (Also, just from the description, it's not really clear what the side effects would be of using this solution.)

I personally like configuring stuff through `.editorconfig`. However, (as far as I can see it) `.editorconfig` files can't be shared because they don't have an "include contents of another file" concept (like `include MySharedCodeStyle/ca-rulesettings`).

**Comment by mavasani** [comment]
I think you want to use global analyzer config: https://github.com/dotnet/roslyn/issues/47707

**Comment by skrysmanski** [comment]
@mavasani Yes, this sounds exactly like what I want. So, I'm closing this issue in favor of the other one.
