### ISSUE TITLE
Find a better name for MicrosoftCodeAnalysisForShippedApisVersion

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4257]
If you need new bits only for test you can bump up the below: https://github.com/dotnet/roslyn-analyzers/blob/193a3b623223f6c4a015d9faafb874fd739dff61/eng/Versions.props#L28

We should probably rename that property name to suggest that is for tests.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/4256#r497693691_

**Comment by Youssef1313** [comment]
Something like `MicrosoftCodeAnalysisForShippedApisVersionUsedForUnitTesting` seems super long.

**Comment by mavasani** [comment]
`MicrosoftCodeAnalysisForTests`?

**Comment by Youssef1313** [comment]
Sounds good. Even shorter than the original name.

**Comment by Youssef1313** [comment]
Fixed in #4260
