### ISSUE TITLE
Setup markdown linter for CI

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#4258]
> This is a one-off change. Regarding the various documentation files this is a manual modification but we don't have any automatic linter that would prevent new errors to be introduced.

@mavasani @Evangelink Do you want a linter workflow for PRs?
dotnet/docs is using one, it should be copy/paste to set the workflow for this repo.

https://github.com/dotnet/docs/blob/master/.github/workflows/markdownlint.yml
https://github.com/dotnet/docs/blob/master/.github/workflows/markdownlint-problem-matcher.json

We can temporarily exclude `AnalyzerReleases.*.md`.

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn-analyzers/pull/4141#issuecomment-701539631_

**Comment by Evangelink** [comment]
@Youssef1313 Yes I think that would be valuable. Is it based upon these [rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md)?

**Comment by Youssef1313** [comment]
Yes it's based on them. You can also have a json configuration file like [this](https://github.com/dotnet/docs/blob/master/.markdownlint.json) -- (It's not only used to enable/disable specific rules, most rules have other configuration settings)

**Comment by Evangelink** [comment]
Could you create a PR for it?
