### ISSUE TITLE
Port FxCop rule CA1410: ComRegistrationMethodsShouldBeMatched

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#426]
**Title:** COM registration methods should be matched

**Description:**

A type declares a method that is marked by using the System.Runtime.InteropServices.ComRegisterFunctionAttribute attribute but does not declare a method marked by using the System.Runtime.InteropServices.ComUnregisterFunctionAttribute attribute, or vice versa.

**Dependency:** None

**Notes:**

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
