### ISSUE TITLE
RS1014: DoNotIgnoreReturnValueOnImmutableObjectMethodInvocation false positive

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4265]
### Analyzer

**Diagnostic ID**: RS1014: `Do not ignore return value on immutable object method invocation`

### Describe the bug

When the method invocation is inside initializer, a false positive warning is produced.

### Steps To Reproduce

I don't have minimal repro, but something like the following should reproduce:

![image](https://user-images.githubusercontent.com/31348972/94824828-b6041300-0405-11eb-9894-c52f90da5451.png)

### Expected behavior

No warning

### Actual behavior

> Warning	RS1014	'SyntaxNode' is immutable and 'WithTriviaFrom' will not have any effect on it. Consider using the return value from 'WithTriviaFrom'.

**Comment by Evangelink** [comment]
@Youssef1313 I think the issue comes from the fact you have a semicolon at the end of the creation of your list.

**Comment by Youssef1313** [comment]
@Evangelink Yeah just noticed this and was going to close. :smile:

**Comment by Evangelink** [comment]
I don't know if that's something that does happen a lot but maybe we could write an analyzer for this kind of mistake (i.e. a code block right after a collection creation).

cc @mavasani
