### ISSUE TITLE
Manually changing generated files doesn't cause build failure

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4266]
@Youssef1313 I marked this as a draft. For generated files, you have two options:

1. Exclude the files from analysis, revert the changes made to them, and file bug(s) to fix the generation process
2. Fix the generation process here and generation the files using the updated tool

If you notice any case where a generated file was changed but did not result in a build failure (i.e. you had to learn about it during code review or separately), it would help to file issues for us to improve the build process so you are alerted directly from the build.

_Originally posted by @sharwell in https://github.com/dotnet/roslyn-analyzers/pull/4259#issuecomment-702198618_

**Comment by Youssef1313** [comment]
@sharwell @mavasani If I wrote a console app that returns 0 on valid state, and other number (or throw exception) on invalid state, will it be suitable that the CI runs it and fail the build if 0 isn't returned?

I'm not familiar with those infrastructure things, so I'm not sure if what I'm saying is possible or not. Or if possible, is it the preferred approach or not.

Can you provide some guidelines if I want to work on this? Thanks.

**Comment by sharwell** [comment]
@Youssef1313 Yes that would be fine. We use that approach in dotnet/roslyn (e.g. BuildBoss).
