### ISSUE TITLE
Port FxCop rule CA1411: ComRegistrationMethodsShouldNotBeVisible

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#427]
**Title:** COM registration methods should not be visible

**Description:**

A method marked by using the System.Runtime.InteropServices.ComRegisterFunctionAttribute attribute or the System.Runtime.InteropServices.ComUnregisterFunctionAttribute attribute is externally visible.

**Dependency:** None

**Notes:**

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
