### ISSUE TITLE
Update help uri to point to docs.microsoft.com/dotnet

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4286]
The documentation for CA rules has moved to .NET docs instead of Visual Studio docs. The help uri for them should point to the new location.

**Comment by mavasani** [comment]
Yep 👍

**Comment by Youssef1313** [comment]
@mavasani GitHub doesn't seem to auto-close the issues when the PR doesn't target the default branch. Manually closing as fixed in #4291.
