### ISSUE TITLE
Port FxCop rule CA1413: AvoidNonpublicFieldsInComVisibleValueTypes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#429]
**Title:** Avoid non-public fields in ComVisible value types

**Description:**

Non-public instance fields of COM visible value types are visible to COM clients. Review the content of the field for information that should not be exposed, or will have unintended design or security impact. By default, all public value types are visible to COM. However, to reduce false positives, this rule requires the COM visibility of the type to be explicitly stated; the containing assembly must be marked with the System.Runtime.InteropServices.ComVisibleAttribute set to false and the type must be marked with the ComVisibleAttribute set to true.

**Dependency:** None

**Notes:**

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
