### ISSUE TITLE
Port FxCop rule CA1415: DeclarePInvokesCorrectly

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#431]
**Title:** Declare PInvokes correctly

**Description:**

A platform invoke method accesses unmanaged code and is defined by using the Declare keyword in Visual Basic or the System.Runtime.InteropServices.DllImportAttribute. Currently, this rule looks for platform invoke method declarations that target Win32 functions that have a pointer to an OVERLAPPED structure parameter and the corresponding managed parameter is not a pointer to a System.Threading.NativeOverlapped structure.

**Dependency:** None

**Notes:**

**Comment by AaronRobinsonMSFT** [comment]
Interop team doesn't think this is useful. This can be closed.

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
