### ISSUE TITLE
Some places still have the old visualstudio documentation link

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4317]
For example: https://github.com/dotnet/roslyn-analyzers/blob/8bada5442ce7d25d564404b1f6e7cd91206610f2/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md

I believe this should be a bug in the release tracking analyzer, it should report a diagnostic when the documentation link (or anything in the entry) is outdated.

**Comment by mavasani** [comment]
It will be difficult to flag such invalid doc links inside an analyzer as analyzers are designed to work offline and have no dependency on network connectivity. I think instead we can narrow this issue to just our repo and add such a validation in our post-build tooling that runs on pack and generates rules missing documentation link.

**Comment by Youssef1313** [comment]
@mavasani That's not about validating that the link actually work. But to validate the link is identical to what is tied to the analyzer.

Isn't the analyzer already getting the link *offline* when it's being added for the first time?

**Comment by mavasani** [comment]
> That's not about validating that the link actually work. But to validate the link is identical to what is tied to the analyzer.

Ah correct, that seems reasonable to flag and can be done in the analyzer.

**Comment by Youssef1313** [comment]
While writing a new analyzer, I found that the codefix tries to add the documentation link from visualstudio docs.

![image](https://user-images.githubusercontent.com/31348972/95872854-95c24580-0d6f-11eb-9af3-c86637fc336b.png)

So, this issue now turns to figure out why the codefix is using visualstudio link.

**Comment by Youssef1313** [comment]
The link was updated in:

https://github.com/dotnet/roslyn-analyzers/blob/f71ee3c7517d39cce1fde6560ddea63a9a56973f/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L36

but not in:

https://github.com/dotnet/roslyn-analyzers/blob/6dea9b867e32607bc02f958efe46d4b2d1220e45/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ReleaseTracking.cs#L369

That's it ;-)

**Comment by mavasani** [comment]
@Youssef1313 Thanks for finding the root cause :-)

**Comment by Youssef1313** [comment]
@mavasani The currently used version in the repository seems to have the fix, but there is still an issue as there is no warning due to outdated links.

See:

https://github.com/dotnet/roslyn-analyzers/blob/126490755be34c24351341b896b4efb84a1de1fe/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md#L123-L125

CA2014 has the correct link (because it was recently updated due to another modification), but others still have the old link.

I expect the analyzer to automatically detect any change in doc link, default severity, or category. (Currently it doesn't detect changes in doc link, but I'm not sure whether it detects changes in default severity and category or not).

**Comment by mavasani** [comment]
@Youssef1313 Analyzer allows manual changes to last column (NOTES), any changes to first three columns will be verified. It seems fine to update all the analyzer releases file to have up-to-date doc links.
