### ISSUE TITLE
Ban language-specific symbols in language-agnostic layers

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4323]

**Comment by Evangelink** [comment]
@Youssef1313 Could you provide some example and/or more description please.

**Comment by Youssef1313** [comment]
@Evangelink https://github.com/dotnet/roslyn-analyzers/tree/master/src/NetAnalyzers/Core

The above folder is for implementations shared between both C# and VB. Any type specific to one language shouldn't be used there. This should be guaranteed by either banning or by somehow make these types inaccessible from this layer.

If I remember correctly, in dotnet/roslyn, they're completely inaccessible (probably they reference a package that contain only language-agnostic types?).

**Comment by Evangelink** [comment]
Thank you.

The project is currently referencing `Microsoft.CodeAnalysis` version `3.3.1` which links to both C# and VB workspace packages. I think that's where the error is, it should be only a reference to the common part.
