### ISSUE TITLE
CA2100 - False Positive - Rule flagged even when procedure name is explicitly checked.

### ISSUE THREAD

**Issue by aaronmcdavid** [dotnet/roslyn-analyzers#4336]
### Analyzer

**Diagnostic ID**: [CA2100](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2100): `Review SQL queries for security vulnerabilities`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

CA2100 is incorrectly flagged when constructing a SqlCommand using:

1. CommandType set to StoredProcedure
2. an explicitly checked procedure name

### Steps To Reproduce

Use the following code.

```
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;

namespace RuleTest {
    class CA2100_Test {
        private static readonly string[] ValidProcedureNames = { "ValidProc1", "ValidProc2" };
        private static void InvokeProcedure(string connString, string name, IEnumerable<SqlParameter> parameters) {
            if (!ValidProcedureNames.Contains(name)) {
                throw new System.ArgumentOutOfRangeException(nameof(name), "Invalid stored procedure name");
            }
            using (var conn = new SqlConnection(connString))
            using (var cmd = new SqlCommand(name, conn) { CommandType = CommandType.StoredProcedure }) {
                conn.Open();
                parameters.ToList().ForEach(p => cmd.Parameters.Add(p));
                cmd.ExecuteNonQuery();
            }
        }
    }
}
```

### Expected behavior

Do not flag with CA2100

### Actual behavior

Flagged with CA2100

**Comment by mavasani** [comment]
This is a known limitation of dataflow analysis rules. Please add a source suppression for this case.
