### ISSUE TITLE
Port FxCop rule CA1502: AvoidExcessiveComplexity

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#434]
**Title:** Avoid excessive complexity

**Description:**

This rule measures the number of linearly independent paths through the method, which is determined by the number and complexity of conditional branches.

**Dependency:** MetricsPackage

**Notes:**

VS is the better place to experience this. You don't want to add one more "if" to a method, "fall off the cliff", and have your RI blocked.

**Comment by mavasani** [comment]
Re-opening as there have been customer requests for enabling Code metrics rules in CI.
See comments within https://developercommunity.visualstudio.com/content/problem/142328/code-metrics-powertool-missing-for-vs2017.html and https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33459643--netcore-code-metrics
