### ISSUE TITLE
warning CA9999: Version mismatch between the analyzer package '3.3.1' and Microsoft.CodeAnalysis '3.3.0.0'

### ISSUE THREAD

**Issue by ike86** [dotnet/roslyn-analyzers#4344]
### Analyzer

**Diagnostic ID**: CA9999 Analyzer version mismatch

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

### Describe the bug

During build server builds I see the warning below:
> CSC : warning CA9999: Version mismatch between the analyzer package '3.3.1' and Microsoft.CodeAnalysis '3.3.0.0'. Certain analyzers in this package will not run until the version mismatch is fixed. Refer to https://docs.microsoft.com/visualstudio/code-quality/install-fxcop-analyzers#fxcopanalyzers-package-versions to install the correct analyzer version. [C:\jenkins\workspace\...\...csproj]

### Steps To Reproduce

I cannot provide reproduction steps, as I cannot reproduce it locally, neither with Visual Studio or Rider.

### Expected behavior

To not see a warning about a version (`3.3.1`), which does not exist yet and is not referenced by any of the projects in the solution.

### Actual behavior

I can see the warning.

## Additional context

- This causes my build to fail, as I'm treating warnings as errors
- In the build server (where the issue is reproducible) we are using
  - msbuild version '16.3.2.50909' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'
  - Windows

**Comment by ike86** [comment]
Please note, that the help link in the warning says

Visual Studio version | FxCop analyzer package version
-- | --
Visual Studio 2019 (all versions) | latest

which we satisfy, but still get the warning.

**Comment by mavasani** [comment]
It seems like the issue is that the compiler toolset in the MSBuild/VS version on your build server is older then the version required by the analyzer package. Please upgrade your build server to a newer MSBuild/VS toolset to fix this issue.

**Comment by ike86** [comment]
Thank you for your help.
