### ISSUE TITLE
Remove the pragma suppression added to 'SymbolNamesWithValueOption'

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#4350]
Remove the pragma suppression added to `SymbolNamesWithValueOption` to unblock https://github.com/dotnet/roslyn-analyzers/pull/4347

**Comment by mavasani** [comment]
Revert https://github.com/dotnet/roslyn-analyzers/pull/4347/commits/2e6b79b402e2b7ee21831fb3693ee5b3b7ebe471 and fix the warning.

**Comment by mavasani** [comment]
@Evangelink

**Comment by Youssef1313** [comment]
@mavasani The warning looks like a compiler bug to me?
`TValue` has a notnull constraint (`where TValue : notnull`). Can't see why the warning is reasonable.

**Comment by mavasani** [comment]
@Youssef1313 Would you be able to create a minimal repro and file an issue on Roslyn?

**Comment by Youssef1313** [comment]
Got it while creating a repro. The reason for the warning is the default value of the optional parameter, which is null for reference types.

**Comment by Evangelink** [comment]
There are 2 questions opened here:

- I think the compiler should not allow the use of `default` for a generic type with only the `notnull` constraint as it does not prevent the use of a reference type for which `default` is `null`. Where can I create this ticket? `dotnet/runtime`? `dotnet/roslyn`? other?

- Get rid of the optional value and force the caller to pass a value.

**Comment by Youssef1313** [comment]
It should be dotnet/roslyn. But as this change can be breaking, it might be introduced as a compiler warning in a warning wave.

**Comment by mavasani** [comment]
@Evangelink are you able to address the second part in your above comment and make the changes to this repo to remove the suppression?

@Youssef1313 can you point out the Roslyn issue?

**Comment by Youssef1313** [comment]
@mavasani https://github.com/dotnet/roslyn/issues/49866

The conclusion from it was:

> Behavior was changed recently, at one point we handled `T t = default` in some cases by not giving a diagnostic and instead updating the default state of the parameter. Updating the compiler should result in behavior where we give a warning on the parameter default value, and not at the use site of the parameter within the method body.
