### ISSUE TITLE
Port FxCop rule CA1505: AvoidUnmaintainableCode

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#436]
**Title:** Avoid unmaintainable code

**Description:**

A type or method has a low maintainability index value. A low maintainability index indicates that a type or method is probably difficult to maintain and would be a good candidate for redesign.

**Dependency:** MetricsPackage

**Notes:**

VS is the better place to experience this. You don't want to add one more operand to an expression, "fall off the cliff", and have your RI blocked.

**Comment by mavasani** [comment]
Re-opening as there have been customer requests for enabling Code metrics rules in CI.
See comments within https://developercommunity.visualstudio.com/content/problem/142328/code-metrics-powertool-missing-for-vs2017.html and https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33459643--netcore-code-metrics
