### ISSUE TITLE
Port FxCop rule CA1506: AvoidExcessiveClassCoupling

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#437]
**Title:** Avoid excessive class coupling

**Description:**

This rule measures class coupling by counting the number of unique type references that a type or method contains.

**Dependency:** MetricsPackage

**Notes:**

VS is the better place to experience this. You don't want to add one more class-valued field to a class, "fall off the cliff", and have your RI blocked.

**Comment by mavasani** [comment]
Re-opening as there have been customer requests for enabling Code metrics rules in CI.
See comments within https://developercommunity.visualstudio.com/content/problem/142328/code-metrics-powertool-missing-for-vs2017.html and https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33459643--netcore-code-metrics
