### ISSUE TITLE
FxCopAnalyzer 3.0.0 or later with VS2017 shows many warnings of 'CS8032'

### ISSUE THREAD

**Issue by kharada7** [dotnet/roslyn-analyzers#4371]
### Diagnostic ID

Example: CS8032 An instance of analyzer Microsoft.CodeQuality.Analyzers.QualityGuidelines.[SomeRule] cannot be created from MyProject\packages\Microsoft.CodeQuality.Analyzers.3.0.0\analyzers\dotnet\cs\Microsoft.CodeQuality.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.0.0 or later

### Visual Studio version

Visual Studio 2017 Version 15.9.28

### Describe the bug

FxCopAnalyzers  2.9.11 shows no warnings on my Visual Studio solution.
But when I update FxCopAnalyzer to 3.0.0, Visual Studio 2017 shows many warnings of 'CS8032'.

### Steps To Reproduce

1. Launch Visual Studio 2017
2. Create new .NET Framework Class Library Project (.NET Framework 4.7.2)
3. Install FxCopAnalyzers 2.9.11 from NuGet
4. Confirm no warnings are shown
5. Update FxCopAnalyzers to 3.0.0
6. Build solution

### Expected behavior

Same as FxCopAnalyzer 2.9.11, there are no warnings.

### Actual behavior

203 warnings of CS8032 appear.

## Additional context

This problem is like [Issue 1825](https://github.com/dotnet/roslyn-analyzers/issues/1825), but the project doesn't reference Microsoft.CodeDom.Providers.DotNetCompilerPlatform and Microsoft.Net.Compilers.
I think there are some incompatibility in FxCopAnalyzers 3.0.0 and Visual Studio 2017 , but I can't find related documents.

**Comment by sharwell** [comment]
The 3.0 release requires Roslyn 3.0, which first shipped in Visual Studio 2019.

**Comment by kharada7** [comment]
@sharwell I understand. Thank you.
