### ISSUE TITLE
CA1812: Avoid uninstantiated internal classes should account for DynamicDependencyAttribute

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4396]
### Analyzer

**Diagnostic ID**: [CA1812](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1812)

### Describe the improvement

From the docs:

> This rule tries to locate a call to one of the constructors of the type and reports a violation if no call is found.

If the constructor is referenced in DynamicDependencyAttribute, the rule shouldn't report a diagnostic for it.

### Additional context

This is related to the suggested enhancement for IDE0051 (https://github.com/dotnet/roslyn/issues/48206).

cc: @stephentoub to confirm whether CA1812 should do that.

**Comment by huoyaoyuan** [comment]
Should be effectively a duplicate of #4243

**Comment by Youssef1313** [comment]
yep, closing.
