### ISSUE TITLE
Port FxCop rule CA1700: DoNotNameEnumValuesReserved

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#440]
**Title:** Do not name enum values 'Reserved'

**Description:**

This rule assumes that an enumeration member that has a name that contains ""reserved"" is not currently used but is a placeholder to be renamed or removed in a future version. Renaming or removing a member is a breaking change.

**Dependency:** None

**Notes:**

**Comment by jjhayworth** [comment]
Check the source code for the [SonarSource implementation of this rule](https://rules.sonarsource.com/csharp/RSPEC-4016)
