### ISSUE TITLE
CA1014 can't be turned off in editorconfig

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn-analyzers#4400]
### Analyzer

**Diagnostic ID**: [CA1014](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1014): `Mark assemblies with CLSCompliantAttribute`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0)

### Steps To Reproduce

Using `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`:

`dotnet_diagnostic.CA1014.severity = none` has no effect.
`<NoWarn>$(NoWarn);CA1014</NoWarn>` works.

## Additional context

I'm not sure about this analyzer itself. It's some sort of old-school practice. `CLSCompliance` has no effective meaning for new .NET versions.

It may be turned off by default. But it should be tunable in `editorconfig`.

**Comment by mavasani** [comment]
`CA1014` is a diagnostic with no source file location, hence cannot be configured in editorconfig, but needs to be configured via global config: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files. We had a workaround in the analyzer itself to workaround this and appropriately respect setting in editorconfig, but this relied on Roslyn internal APIs and is broken as of now (fixing it is tracked by https://github.com/dotnet/roslyn-analyzers/issues/4224). I'll work on a PR today to fix the workaround.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/4402

**Comment by huoyaoyuan** [comment]
@mavasani Tried to use globalconfig, and I'm getting the following diagnostics:
Since I've set `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`, it complains about duplicated severity items in `.globalconfig` and SDK provided `AnalysisLevel_5_AllEnabledByDefault.editorconfig`. This doesn't happen with `.editorconfig`, where local defined value gets preferred.
