### ISSUE TITLE
CA1508 FP when using an extension method that returns IDisposable

### ISSUE THREAD

**Issue by neoscie** [dotnet/roslyn-analyzers#4426]
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
**Version**: v3.3.1

### Describe the bug

Another one to the CA1508 FP's pile... I've set up a standalone repo, see below.

### Steps To Reproduce

Clone and run my [repro repo](https://github.com/neoscie/repro-CA1508)

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/4358
