### ISSUE TITLE
CA1416: Consider supporting guard clauses like IsThreadStartSupported

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/roslyn-analyzers#4428]
Consider supporting guard clauses like IsThreadStartSupported in Platform compatibility analyzer

I'd have hoped the analyzer would be able to understand the guard clauses like IsThreadStartSupported just as the linker can.  Is that not possible?

_Originally posted by @stephentoub in https://github.com/dotnet/runtime/pull/43363#discussion_r520598687_

**Comment by Evangelink** [comment]
@buyaa-n could you please give a little more detail about the issue? As far as I understand the idea is to fix a false positive with the rule CA1416, is it more global? If not, maybe the title should state the rule and the label might be `False-Positive` instead of `Enhancement`.

**Comment by buyaa-n** [comment]
> @buyaa-n could you please give a little more detail about the issue? As far as I understand the idea is to fix a false positive with the rule CA1416, is it more global? If not, maybe the title should state the rule and the label might be False-Positive instead of Enhancement.

It is not a fix for a false positive, it would be an enhancement for the analyzer to support this scenario. Yes, it is related to CA1416 only, updated the title, thanks!

**Comment by buyaa-n** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/5087
