### ISSUE TITLE
Port FxCop rule CA1704: IdentifiersShouldBeSpelledCorrectly

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#443]
**Title:** Identifiers should be spelled correctly

**Description:**

The name of an externally visible identifier contains one or more words that are not recognized by the Microsoft spelling checker library.

**Dependency:** NamingService

**Notes:**

See if StyleCop has implemented it

**Comment by crazycrank** [comment]
We would be interested in how far this is along and if this will ever be implemented, as according to [this PR comment](https://github.com/dotnet/roslyn-analyzers/pull/1111#pullrequestreview-95427830) it's being considered to use a different approach or at least use a different CA Rule then originally. Has there been any internal discussions and decisions about the issue of spell checking with the Roslyn analyzers or is the decision making progress currently postponed?

We would be glad to not have to use a third party tool to achieve this functionality, but this depends on how long we would have to wait for this rule.

**Comment by RobSiklos** [comment]
Any ETA for this one?

**Comment by EvilPingu** [comment]
Hi @lgolding, @mavasani,

still no ETA for this one? This rule is very important for us!

EvilPingu

**Comment by FreeAndNil** [comment]
May be fixed by #1111
