### ISSUE TITLE
Port FxCop rule CA1707: IdentifiersShouldNotContainUnderscores

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#444]
**Title:** Identifiers should not contain underscores

**Description:**

By convention, identifier names do not contain the underscore (_) character. This rule checks namespaces, types, members, and parameters.

**Dependency:** None

**Notes:**

See if StyleCop has implemented it

**Comment by srivatsn** [comment]
Analyzer has been implemented. Marking it as "Needs-Fixer"
