### ISSUE TITLE
[CA1801] False positive on top-level code in .NET 5/C#9

### ISSUE THREAD

**Issue by Flynn1179** [dotnet/roslyn-analyzers#4446]
### Analyzer

**Diagnostic ID**: [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801): `Do not use ReferenceEquals with value types`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

False positive when using top level code that doesn't refer to the 'args' parameter. 
![image](https://user-images.githubusercontent.com/10530157/99797540-55e93d80-2b27-11eb-8469-54dc0fe097e6.png)

### Steps To Reproduce

This complete program raises a warning, in a .NET 5 Console App (This the entirety of the only code file in the project, 'Program.cs'):

    System.Console.WriteLine(@"Hello World!");

**Comment by Youssef1313** [comment]
This was fixed in #4066.

**Comment by Flynn1179** [comment]
Fair enough... forgot to check closed issues as well. Oops!
