### ISSUE TITLE
Useless enforcement of CG.SuppressFinalize

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn-analyzers#4482]
---
**Issue moved from dotnet/docs#21734**
- Please respond to @ericbl.

---

_From @ericbl on Thursday, November 26, 2020 2:52:59 PM_

The rules CA1816 and CA1063 are annoying me for a small detail for over 10 years: why is the CA1816 and CA1063 still forcing a call to the CG.SuppressFinalize method when the class do NOT have any finalizer?
As stated  in the IDispose snippet in VS, by Stephen Cleary in his blog here:
https://blog.stephencleary.com/2009/08/second-rule-of-implementing-idisposable.html
a class implementing IDisposable with only **managed objects** should NOT have any finalizer, and do NOT need a call to  CG.SuppressFinalize 

Adding CG.SuppressFinalize will not harm since 
https://docs.microsoft.com/en-us/dotnet/api/system.gc.suppressfinalize?redirectedfrom=MSDN&view=net-5.0#System_GC_SuppressFinalize_System_Object_
> If obj does not have a finalizer or the GC has already signaled the finalizer thread to run the finalizer, the call to the SuppressFinalize method has **no effect**.

but this is just useless: every .NET developer dealing mostly with managed code is adding a line of code for nothing in his code. 

IMHO, it would be much better to detect if the class has a finalizer, and if no finalizer, do not ask for SuppressFinalize !
Even better would be to detect for unmanaged ressources and only then ask for a finalizer and possibly SuppressFinalize as in the 3rd rule of implementing IDisposable:
https://blog.stephencleary.com/2009/08/third-rule-of-implementing-idisposable.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd3e94e-7b6f-21ad-4c90-460e60482ab5
* Version Independent ID: 15958b42-33bb-4925-2d78-eb72113ba3eb
* Content: [CA1816: Call GC.SuppressFinalize correctly (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1816)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1816.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1816.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/docs#21734**
- Please respond to @Evangelink.

---

_From @Evangelink on Thursday, November 26, 2020 4:34:03 PM_

I am wondering if there are cases where it brings something. 

@mavasani if this ticket moves forward the analyzer should be updated.

**Comment by KrisVandermotten** [comment]
> why is the CA1816 and CA1063 still forcing a call to the CG.SuppressFinalize method when the class do NOT have any finalizer?

Because, unless the type is a struct or a sealed class, someone might derive from it and add a finalizer in the derived class.

That being said, there is no need to call CG.SuppressFinalize in a sealed class without a finalizer.

**Comment by ericbl** [comment]
> > why is the CA1816 and CA1063 still forcing a call to the CG.SuppressFinalize method when the class do NOT have any finalizer?
> 
> Because, unless the type is a struct or a sealed class, someone might derive from it and add a finalizer in the derived class.

I got that too, but then, IMHO, the derivated class with a finalizer should care about CG.SuppressFinalize, not the parent class (without finalizer)!

**Comment by KrisVandermotten** [comment]
> I got that too, but then, IMHO, the derivated class with a finalizer should care about CG.SuppressFinalize

Unfortunately, the Dispose method that is supposed to call CG.SuppressFinalize is typically not `virtual`, so derived classes have no way to override it.

**Comment by sharwell** [comment]
The `IDisposable` pattern covered by the code analysis rules accounts for the possibility of derived types adding a finalizer if the base type does not have one. Since under this pattern `GC.SuppressFinalize` is the final line of the non-virtual implementation of `IDisposable.Dispose()`, it needs to be added in the base class whether or not a finalizer is added.

Derived types which override `Dispose(bool)` should assume that the base class has already made a call to `GC.SuppressFinalize()` as part of the implementation of `Dispose()`, and do not need to add it again.

**Comment by justcoding121** [comment]
I wondered after reading the answers here, will calling `GC.SuppressFinalize(this)` on base class' `public void Dispose()` suppress Finalizer on its derived class? I would assume it does, otherwise it would be meaningless. So `this` in base class will be always pointing to derived class.
