### ISSUE TITLE
CA1508 false positive after a switch statement

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#4520]
TODO

_Originally posted by @Evangelink in https://github.com/dotnet/roslyn-analyzers/pull/4503#r536903494_

**Comment by Evangelink** [comment]
It could have been fixed but I don't recall it.

> @Youssef1313 Could you try to remove the following 2 pragma and see if the PR is still good:
> 
> * [#4503 (files)](https://github.com/dotnet/roslyn-analyzers/pull/4503/files#diff-90aae54e7df965c0f40519c6bb9788313706e66add821fccca090afbb863eb87R159)
> * [#4503 (files)](https://github.com/dotnet/roslyn-analyzers/pull/4503/files#diff-49cd14348fe3ac56e5a1198cc5bd92120f89b86484462972ea4270ee156c1884R289)

Could you try that ^^^^ please?
