### ISSUE TITLE
Document Microsoft.CodeQuality.Analyzers et al. usage on .NET 5

### ISSUE THREAD

**Issue by kevinoid** [dotnet/roslyn-analyzers#4521]
### Analyzer

**Diagnostic ID**: [CA1010](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1010): `Type '{0}' directly or indirectly inherits 'IEnumerable' without implementing 'IEnumerable<T>'.`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

The [NuGet package description for Microsoft.CodeQuality.Analyzers](https://github.com/dotnet/roslyn-analyzers/blob/v3.3.2/nuget/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.Package.csproj#L9), [Microsoft.NetCore.Analyzers](https://github.com/dotnet/roslyn-analyzers/blob/v3.3.2/nuget/Microsoft.NetCore.Analyzers/Microsoft.NetCore.Analyzers.Package.csproj#L9), and [Microsoft.NetFramework.Analyzers](https://github.com/dotnet/roslyn-analyzers/blob/v3.3.2/nuget/Microsoft.NetFramework.Analyzers/Microsoft.NetFramework.Analyzers.Package.csproj#L9) state:

> This package is included as a part of Microsoft.CodeAnalysis.FxCopAnalyzers NuGet package and does not need to be installed separately.

However, Microsoft.CodeAnalysis.FxCopAnalyzers is deprecated in favor of analyzers included in the .NET SDK.  To me, this suggests the packages would be included in the .NET SDK, which does not appear to be the case.

### Steps To Reproduce

1. In an empty directory, create `MyEnumerable.cs` with content:
    ```csharp
    using System.Collections;
    
    public class MyEnumerable : IEnumerable
    {
        public IEnumerator GetEnumerator()
        {
            yield break;
        }
    }
    ````
2. Create `Example.csproj` with content:
    ```xml
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
      </PropertyGroup>
    </Project>
    ```
3.  Create `.editorconfig` with content:
    ```editorconfig
    root = true
    [*]
    dotnet_diagnostic.CA1010.severity = error
    ```
4.  Run `dotnet build`.

### Expected behavior

Maybe CA1010, maybe not?

### Actual behavior

No errors.

## Additional context

I would suggest changing Microsoft.CodeAnalysis.FxCopAnalyzers to Microsoft.CodeAnalysis.NetAnalyzers in the package descriptions and one of the two following actions:
1. If Microsoft.CodeQuality.Analyzers et al. will be shipped with .NET, note that in the descriptions.
2. If not, [Enable or install first-party .NET analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-net-analyzers) should document that installing Microsoft.CodeAnalysis.NetAnalyzers is the recommended way to use these analyzers, even on .NET 5.

Thanks for considering,
Kevin

**Comment by mavasani** [comment]
Thanks @kevinoid - Those three packages included as part of FxCopAnalyzers package are also deprecated. Let me update the repo docs + also ensure the NuGet packages are marked deprecated as well. All the first-part .NET CA analyzers are now part of a single package `Microsoft.CodeAnalysis.NetAnalyzers`

**Comment by kevinoid** [comment]
Thanks @mavasani!  Can you confirm that it is still necessary to install `Microsoft.CodeAnalysis.NetAnalyzers` when building with .NET 5 SDK to check rules like CA1010 and whether I should file a separate issue to note that in [Enable or install first-party .NET analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-net-analyzers)?

**Comment by mavasani** [comment]
Regarding your example repro, you need to do either of the following steps in addition to the steps you mentioned:
- Move to .NET 5.0 SDK (if you haven't alread) + set MSBuild property `EnableNETAnalyzers` to `true` in your project or props file OR
- Install the NuGet package `Microsoft.CodeAnalysis.NetAnalyzers`

**Comment by mavasani** [comment]
@kevinoid Analyzers are enabled by default in .NET 5.0 SDK only for projects targeting `net5` or later. For other platforms you have to explicitly enable the analyzers by doing one of the things mentioned in my prior comment.

**Comment by kevinoid** [comment]
Thanks again @mavasani!  Sorry for the confusion.  You are quite right.  I was jumping to the wrong conclusion.  Sounds great about the docs/deprecation!

**Comment by mavasani** [comment]
Repo README is now updated.
