### ISSUE TITLE
BannedApiAnalyzers breaks configuration of AnalysisMode for built-in NetAnalyzer

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/roslyn-analyzers#4540]
### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.101](https://dotnet.microsoft.com/download/dotnet/5.0)

_AND_

**NuGet Package**: [Microsoft.CodeAnalysis.BannedApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 3.3.1

### Describe the bug

In a project, install `BannedApiAnalyzers`, and configure `AnalysisMode` to `AllEnabledByDefault`.

### Expected behavior

The two analyzers works together.

### Actual behavior

`NetAnalyzer` doesn't get correct config.

When viewing msbuild log, I've found `_GlobalAnalyzerConfigFile` has been resolved into `BannedApiAnalyzers` directory.

NetAnalyzer only:
![image](https://user-images.githubusercontent.com/5644458/101601781-07e59c80-3a38-11eb-8939-888f616fd56a.png)

BannedApiAnalyzers installed:
![image](https://user-images.githubusercontent.com/5644458/101601856-1fbd2080-3a38-11eb-9ec1-8c11ba59a5ce.png)

**Comment by mavasani** [comment]
Thanks. I believe this was fixed with latest stable versions of both packages. Can you please upgrade and try again?

**Comment by mavasani** [comment]
You will need to install the 5.0.1 NuGet package for Microsoft.CodeAnalysis.NetAnalyzers as the latest .NET SDK still is on 5.0.0 of the package.

**Comment by huoyaoyuan** [comment]
I can confirm it's fixed in BannedApiAnalyzers 3.3.2.
