### ISSUE TITLE
CA9998 warning when no reference to FxCopAnalyzers

### ISSUE THREAD

**Issue by abbotware** [dotnet/roslyn-analyzers#4558]
### Analyzer

**Diagnostic ID**: [CA9998 ] warning CA9998: FxCopAnalyzers package has been deprecated in favor of 'Microsoft.CodeAnalysis.NetAnalyzers

### Analyzer source

**SDK**: [SDK 3.1.404]

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Describe the bug

I just updated to the newest analyzers and I am getting a warning that I am still using FxCopAnalyzers even though they are not part of the project

### Steps To Reproduce

check out and build in vs2019 (16.8.3)
https://github.com/abbotware/abbotware

### Expected behavior

no warnings

### Actual behavior

warning CA9998 appears numerous times per project

**Comment by abbotware** [comment]
here is a screen shot
![image](https://user-images.githubusercontent.com/2100564/101860424-c9390a80-3b3b-11eb-8045-da039e0fb817.png)

**Comment by mavasani** [comment]
@abbotware You are directly referencing the constituent packages of FxCopAnalyzers package, which are also deprecated now: https://github.com/dotnet/roslyn-analyzers/blob/master/README.md#the-following-are-subpackages-or-nuget-dependencies-that-are-automatically-installed-when-you-install-the-microsoftcodeanalysisfxcopanalyzers-package

**Comment by abbotware** [comment]
OK! - I did read that page, but somehow missed the line:

"Starting version 3.3.2, Microsoft.CodeQuality.Analyzers, Microsoft.NetCore.Analyzers and Microsoft.NetFramework.Analyzers have also been deprecated in favor of Microsoft.CodeAnalysis.NetAnalyzers" 

Perhaps the should also be marked deprecated?

**Comment by mavasani** [comment]
> Perhaps the should also be marked deprecated (in nuget.org)?

They should already be marked deprecated.

**Comment by abbotware** [comment]
@mavasani  - you are right!
