### ISSUE TITLE
Port FxCop rule CA1725: ParameterNamesShouldMatchBaseDeclaration

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#457]
**Title:** Parameter names should match base declaration

**Description:**

Consistent naming of parameters in an override hierarchy increases the usability of the method overrides. A parameter name in a derived method that differs from the name in the base declaration can cause confusion about whether the method is an override of the base method or a new overload of the method.

**Dependency:** None

**Notes:**

See if StyleCop has implemented it

**Comment by basoundr** [comment]
StyleCop has a [PR](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2015) submitted for this
