### ISSUE TITLE
CA1062 false positive with params arguments

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#4572]
### Analyzer

**Diagnostic ID**: [CA1062](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1062): `Validate arguments of public methods`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Describe the bug

CA1062 false positive with params arguments.

### Steps To Reproduce

See attached project.

### Expected behavior

CA1062 should not fire.

### Actual behavior

CA1062 fires.

[CA1062.ZIP](https://github.com/dotnet/roslyn-analyzers/files/5691321/CA1062.ZIP)

**Comment by mavasani** [comment]
This is by-design. Please see https://github.com/dotnet/roslyn-analyzers/issues/4502 for context.
