### ISSUE TITLE
Port FxCop rule CA1801: ReviewUnusedParameters

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#459]
**Title:** Review unused parameters

**Description:**

A method signature includes a parameter that is not used in the method body.

**Dependency:** None, can be based on: https://github.com/dotnet/roslyn/blob/master/src/Samples/CSharp/Analyzers/CSharpAnalyzers/CSharpAnalyzers/StatefulAnalyzers/CodeBlockStartedAnalyzer.cs

**Notes:**

Don't fire if the parameter comes from an interface you're implementing or a virtual method you're overriding.

**Comment by lgolding** [comment]
Items with the Needs-Fixer label need to be left open.

**Comment by mavasani** [comment]
Removing my assignment till we get to the fixers..

**Comment by DarkBond** [comment]
I don't know what the status of this is, but I have the latest StyleCop on 3/22/2016 and I'm getting a CA1801 violation on an interface implementation.  As we have no choice when implementing an interface and it's parameters, CA1801 on an interface method appears to be less than  useless.

**Comment by lgolding** [comment]
Hi @DarkBond, could you please attach a source code sample that shows this problem. Also, could you please tell us exactly how/where you got the analyzer package you are running. Did you get it from NuGet.org, or MyGet? What is its name and version number? The Roslyn analyzer for rule CA1801 is implemented in a NuGet package named Microsoft.Maintainability.Analyzers.

Thanks,
Larry

@mavasani @srivatsn FYI

**Comment by DarkBond** [comment]
Larry,

                I thought I was up to rev. on StyleCop.Analyzers, but last night when I went to repro, I found some new updates available.  I pulled down the new package and a batch of new violations popped out (e.g. warning SA1625).  I'll let you know if it’s still an issue after I’ve cleaned out the new warnings.  I wasn’t able to repro on a fresh version of the interface, so it likely has been resolved.

 

Don Airey

**Comment by lgolding** [comment]
Dan, I think there is some confusion. The StyleCop  analyzers don't come from the roslyn-analyzers repo. They come from the repo https://github.com/DotNetAnalyzers/StyleCopAnalyzers, which is produced by @sharwell and his team.

The StyleCop analyzers use rule ids starting with "SA". The roslyn-analyzers use rules starting with "CA". So I'm about confused what you mean by saying that the StyleCop analyzers rule CA1801 is misbehaving, because StyleCop doesn't have a rule with that id. I searched their repo and that string does not appear.

If you could tell me exactly how and where you got the analyzer package you are running, and the name and version number of that package, that would help.

If it turns out that the problem you're having really is with the StyleCop analyzers, then you'll want to file the issue in the repo https://github.com/DotNetAnalyzers/StyleCopAnalyzers.

Hope that helps,
Larry

**Comment by lgolding** [comment]
I looked at the current [implementation](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.Maintainability.Analyzers/Core/ReviewUnusedParameters.cs) of our rule CA1801, and it correctly handles interfaces (see [Line 75](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.Maintainability.Analyzers/Core/ReviewUnusedParameters.cs#L75)). There is a [unit test](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.Maintainability.Analyzers/UnitTests/ReviewUnusedParametersTests.cs#L245) for this case. So if it does turn out that the problem really is in the latest implementation of CA1801 in the Microsoft.MaintainabilityGuidelines.Analyzers, we'll certainly fix it.

**Comment by DarkBond** [comment]
Larry,

                I’m terribly sorry, but it was my mistake.  I had a method that was almost identical to the one in the interface.  I was so blind with fatigue I couldn’t see the extra letters.

                Please remove the item as non-reproducable.  Sorry to have wasted your time chasing this.

 

Regards,

 

Don Airey

**Comment by lgolding** [comment]
Don, that's quite alright! 

Just to remove my remaining confusion, are you in fact using the Microsoft Roslyn analyzers from the NuGet package Microsoft.MaintainabilityGuidelines.Analyzers? And are you _also_ using the StyleCop analyzers from https://github.com/DotNetAnalyzers/StyleCopAnalyzers? And did that cause you confusion about which package the diagnostic "CA1801" came from?

Larry

**Comment by DarkBond** [comment]
I'm using the integrated Code Analysis in Visual Studio 2015 (formerly known as FxCop, I believe) and the 'Microsoft All Rules' setting.  I am using the StyleCop analyzer from https://github.com/DotNetAnalyzers/StyleCopAnalyzers, so 'yes' to the second question.  The reason for the confusion was that I googled 'CA1801' and it brought me to this page so I mistakenly thought it was a StyleCop issue without even digesting the fact that the warning it began with 'CA'.

**Comment by lgolding** [comment]
That's ok, we all have days like that :-) Glad I could help!

**Comment by jinujoseph** [comment]
Address https://github.com/dotnet/roslyn/issues/20405 once fixer is available

**Comment by mavasani** [comment]
This needs a fixer.
