### ISSUE TITLE
DoNotUseStackallocInLoopsAnalyzer should exist in C# layer only

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4599]
It's currently defined here:

https://github.com/dotnet/roslyn-analyzers/blob/126490755be34c24351341b896b4efb84a1de1fe/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotUseStackallocInLoopsAnalyzer.cs#L10

with a single class that sub-types it.

**Comment by mavasani** [comment]
This was done to ensure single AnalyzerReleases file in the core layer has all rules.

**Comment by mavasani** [comment]
Closing out..
