### ISSUE TITLE
Port FxCop rule CA1802: UseLiteralsWhereAppropriate

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#460]
**Title:** Use literals where appropriate

**Description:**

A field is declared static and read-only (Shared and ReadOnly in Visual Basic), and is initialized by using a value that is computable at compile time. Because the value that is assigned to the targeted field is computable at compile time, change the declaration to a const (Const in Visual Basic) field so that the value is computed at compile time instead of at run?time.

**Dependency:** None

**Notes:**

Does it fire on publics? That has versioning implications. Consider only firing on symbols not visible outside assembly.

**Comment by basoundr** [comment]
This needs the new Roslyn bits that will have the issue https://github.com/dotnet/roslyn/issues/7293 fixed.

**Comment by basoundr** [comment]
issue https://github.com/dotnet/roslyn/issues/7293 has been fixed. This is no longer blocked

**Comment by basoundr** [comment]
#906 implements the analyzers. Adding Needs-Fixer
