### ISSUE TITLE
Review RS1004 suppressions

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4600]
There are some RS1004 suppressions currently, all of them are in "Core" layer. Consider moving these analyzers to the language-specific layers and see if the warning will go away.

**Comment by mavasani** [comment]
> Consider moving these analyzers to the language-specific layers and see if the warning will go away.

I do not think we want to move analyzers to language-specific layers just to workaround suppressions. In fact, I feel the suppression comments that @Evangelink added on each RS1004 suppression acts as a valid documentation on why the support was not added for the second language.

**Comment by Youssef1313** [comment]
@mavasani If I understood correctly, that means that analyzers in language-specific layers shouldn't sub-type DiagnosticAnalyzer directly, but should instead sub-type an abstract DiagnosticAnalyzer in the "Core" layer. That's currently not maintained for some analyzers. So the Shipped analyzers file in "Core" layer contains "some" language-specific analyzers, but not all.

For example, CA2224 is only included in the VB AnalyzerReleases.Shipped only but not in the Core one.

Should DiagnosticAnalyzer class be banned in the language-specific layers?
