### ISSUE TITLE
Port FxCop rule CA1804: RemoveUnusedLocals

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#461]
**Title:** Remove unused locals

**Description:**

Unused local variables and unnecessary assignments increase the size of an assembly and decrease performance.

**Dependency:** None

**Notes:**

See if the compiler warns of this. At the least, it should have a fixer.

**Comment by basoundr** [comment]
Awaiting the issue https://github.com/dotnet/roslyn/issues/8032  to be addressed before continuing

**Comment by srivatsn** [comment]
Removing the blocked tag since @JohnHamby suggested a way of implementing this without needing IsLValue

**Comment by basoundr** [comment]
#894 implements the analyzer. Adding the Needs-Fixer label
