### ISSUE TITLE
Add analyzer to support Microsoft coding guidelines about when not to use implicit typing

### ISSUE THREAD

**Issue by stortina** [dotnet/roslyn-analyzers#4618]
Analyzers for these Microsoft coding conventions:

- _Do not use var when the type is not apparent from the right side of the assignment._
- _Do not use implicit typing to determine the type of the loop variable in foreach loops._

Found here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

**Comment by Youssef1313** [comment]
This should fall into the IDE `var` preferences rule. Related issue https://github.com/dotnet/roslyn/issues/29657

**Comment by sharwell** [comment]
This is implemented as [IDE0007 and IDE0008](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008) in [dotnet/roslyn](https://github.com/dotnet/roslyn).
