### ISSUE TITLE
Port FxCop rule CA1806: DoNotIgnoreMethodResults

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#462]
**Title:** Do not ignore method results

**Description:**

A new object is created but never used; or a method that creates and returns a new string is called and the new string is never used; or a COM or P/Invoke method returns an HRESULT or error code that is never used.

**Dependency:** None

**Notes:**

Consider having a whitelist, like immutable types (including string), and also look for the Pure attribute

**Comment by mavasani** [comment]
Ported with https://github.com/dotnet/roslyn-analyzers/commit/57fa0965bd10d2a98eef235d7d5c01c190d2da6e
