### ISSUE TITLE
CA2225: named alternates, allow 'As' instead of 'To'

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/roslyn-analyzers#4630]
### Analyzer

**Diagnostic ID**: [CA2225](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2225)

### Describe the improvement
It appears that using `As` as prefix for methods that convert an object is used increasingly in .NET (AsSpan, AsMemory, AsReadOnlySpan, etc.). So, the rule should allow methods named ToObject and AsObject.

### Describe suggestions on how to achieve the rule
Add `As` as a valid prefix to fulfill the rule

### Additional context
None

**Comment by Youssef1313** [comment]
That sounds reasonable to me.

@Evangelink @mavasani What are your opinions?

**Comment by Evangelink** [comment]
I would say this makes sense too but I am wondering if we should always allow `As` or if we should do it only for some types. I can't say if that's the rule but it seems that all `AsXXX` are related to either `struct` or non-concrete types (there is a specific word which I forgot about) like `AsEnumerable`.

Let's wait for @mavasani or @sharwell

**Comment by sharwell** [comment]
It seems like `As` is used more for extension methods where concession operators do not apply. Are there clear examples of the BCL adopting the new prefix in place of `To` in the context of this rule?

**Comment by mavasani** [comment]
Sounds good - won't fix as per Sam's comment above.

**Comment by mavasani** [comment]
If someone finds counter examples in the BCL, we can reopen this issue.
