### ISSUE TITLE
Port FxCop rule CA1811: AvoidUncalledPrivateCode

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#464]
**Title:** Avoid uncalled private code

**Description:**

A private or internal (assembly-level) member does not have callers in the assembly; it is not invoked by the common language runtime; and it is not invoked by a delegate.

**Dependency:** IOperation

**Notes:**

Implementation: Create a dictionary at compilation start; add to it each time you see a function call.

**Comment by srivatsn** [comment]
FxCop implementation has a bug when a type has methods involving 'dynamic' as reported by an user:

The CA1811 code analysis rule seems to not work with classes that use dynamic types.

 This class:

 internal static class Class1
 {
 private static void Method1() { }

 private static int Method2(dynamic value) => value;

 private static void Method3() { }
 }

 should have these code analysis warnings:

 CA1811 'Class1.Method1()' appears to have no upstream public or protected callers.
 CA1811 'Class1.Method2()' appears to have no upstream public or protected callers.
 CA1811 'Class1.Method3()' appears to have no upstream public or protected callers.

 but it doesn't show any code analysis warnings. it works correctly if you remove Method2.

**Comment by wizofaus** [comment]
This isn't working for me at all actually with the latest FxCopAnalyzers (2.6.2).  I can get CA1801 (unused parameter) to trigger, but not CA1811, regardless of what ruleset/pragma settings I use.

**Comment by mavasani** [comment]
Yes, this hasn’t been ported to FxCop analyzers. Dev16 preview1 will have an implementation for flagging unused private members in the box by default. The member name will be faded out and there is a code fix to remove such members.

**Comment by mavasani** [comment]
@Dennis-Petrov https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

**Comment by strawd** [comment]
@mavasani you mention the built-in unused private member detection in Visual Studio 2019 above, but as far as I can tell there's no way to find all such methods across the solution using that feature. Is a port of CA1811 in plan at some point?

**Comment by Dennis-Petrov** [comment]
@mavasani : VS2019 is here, but as it implemented, it's not a replacement of CA1811. We have a lot of code and several solutions. Nobody will open source files one-by-one to detect and remove unused private code.

**Comment by wizofaus** [comment]
Is there any timeline yet for a version of an FxCop or other build-time analyzer that will fail the build on CA1811 violations?

**Comment by mavasani** [comment]
Please see the update at https://github.com/dotnet/roslyn/issues/33558#issuecomment-605974524. We now have a CodeStyle NuGet package that can be installed to the project for built enforcement. Please follow the below steps:

1. Install the Code Style NuGet package to your project
2. Notice the IDE0051/IDE0052 suggestions for unused/unread private members respecitively.
3. Configure severity of both these diagnostics to be warning/error in editorconfig. You can use the UI gestures for configuration documented here: https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#configure-from-light-bulb-menu
4. Build your project and see warnings/errors on command line for all unused/unread private members.

**Comment by mavasani** [comment]
CLosing this issue as Won't fix as per the last comment - there is a build enforcable IDE analyzer that is the replacement for CA1811..

**Comment by wizofaus** [comment]
But I've tried that and my build is still succeeding despite having unused private members.

These are the package version I have installed:

    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.7.0" />
    <PackageReference Include="Microsoft.CodeQuality.Analyzers" Version="3.0.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0" />

**Comment by mavasani** [comment]
Please try `Microsoft.CodeAnalysis.CSharp.CodeStyle` package: https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.CSharp.CodeStyle&protocolType=NuGet&version=3.7.0-3.20271.4

**Comment by wizofaus** [comment]
Yep, I eventually got it working using v 3.7.0-1.20208.4, after much trial and error!
