### ISSUE TITLE
Microsoft.CodeAnalysis.NetAnalyzers doesn't work on old csproj projects after migrating to PackageReference

### ISSUE THREAD

**Issue by austinw-fineart** [dotnet/roslyn-analyzers#4640]
### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Describe the bug

Microsoft.CodeAnalysis.NetAnalyzers doesn't work on old csproj projects.

### Steps To Reproduce

1. Create new ASP.NET Web Application (.NET Framework)
2. Add the Microsoft.CodeAnalysis.NetAnalyzers package
3. Try violating one of the default rules such as [CA2200](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2200)

### Expected behavior

Should be a drop-in replacement for Microsoft.CodeAnalysis.FxCopAnalyzers

### Actual behavior

No CA rules are applied.

**Comment by Evangelink** [comment]
Seems to be working for me for ASP.NET, console and WPF projects (I haven't tried others).

**Comment by austinw-fineart** [comment]
Oh that's right, it's been migrated to PackageReferences as well.

**Comment by austinw-fineart** [comment]
Hm, I can't actually reproduce this with a clean project setup so something else is likely causing it. I'll be closing this then.
