### ISSUE TITLE
PureAttribute in another assembly ignored by DoNotIgnoreMethodResultsAnalyzer CA1806 during the build

### ISSUE THREAD

**Issue by rcatley** [dotnet/roslyn-analyzers#4657]
This is an update on https://github.com/dotnet/roslyn-analyzers/issues/3265.
While I haven't tested against v3.3.0, it is still an issue in 3.3.1.
3.3.2 is deprecated in favour of .NETAnalyzers integrated into the 5.0 SDK. (Visual studio 2019 version 16.8 or higher required)
For this new approach, reproduction here: https://github.com/rcatley/CrossAssemblyAnalysisMissed

**Comment by Youssef1313** [comment]
I tried to write a test for this and it passed.

```csharp
        [Fact]
        [WorkItem(4657, "https://github.com/dotnet/roslyn-analyzers/issues/4657")]
        public async Task UnusedPureMethodInDifferentAssembly()
        {
            var dependencyProjectCode = @"
using System.Diagnostics.Contracts;

namespace Dependency
{

    public class C
    {
        [Pure]
        public int Returns1() => 1;
    }
}";

            var code = @"
using Dependency;

public class D
{
    public void DoesNotUseResult()
    {
        {|#0:new C().Returns1()|};
    }
}
";
            await new VerifyCS.Test
            {
                TestState =
                {
                    Sources = { code },
                    AdditionalProjects =
                    {
                        ["HasPure"] =
                        {
                            Sources = { ("C.cs", dependencyProjectCode) }
                        }
                    },
                    AdditionalProjectReferences = { "HasPure" },
                    ExpectedDiagnostics =
                    {
                        VerifyCS.Diagnostic(DoNotIgnoreMethodResultsAnalyzer.PureMethodRule).WithLocation(0).WithArguments("DoesNotUseResult", "Returns1")
                    }
                }
            }.RunAsync();
        }
```

Maybe I'm not writing the test in the correct way?

**Comment by Youssef1313** [comment]
@mavasani It appears that "ISymbol.GetAttributes" method is returning an empty ImmutableArray. Hence, `IsPureMethod` is returning false. Is it a roslyn bug?

**Comment by Youssef1313** [comment]
Alright! Finally found the issue. The attribute is conditionally compiled:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Contracts/Contracts.cs#L31-L35

When I define `CONTRACTS_FULL`, it works as expected.

**Comment by Youssef1313** [comment]
Based on https://github.com/dotnet/roslyn/pull/50601#issuecomment-762832098, it seems that defining `CONTRACTS_FULL` isn't a good/correct solution for this.

**Comment by rcatley** [comment]
Excellent work Youssef1313. Thank you for your efforts.
While the change you have in mind for the roslyn source may not become an accepted solution, it has provided a (permanent?) workaround. -Any library using a PureAttribute needs to be compiled with CONTRACTS_FULL defined. This definition works at project level. I have updated https://github.com/rcatley/CrossAssemblyAnalysisMissed to show it working.
Thank you everyone.

**Comment by Youssef1313** [comment]
Closing as the analyzer is behaving as expected. Note that using `Pure` isn't recommended. See https://github.com/dotnet/runtime/issues/47157
