### ISSUE TITLE
CA1825 - Avoid unnecessary zero-length array allocations deemed dangerous in expression trees

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn-analyzers#4665]
```csharp
Expression<Func<int[]>> f = () => new int[0];
```

suggests changing to using `Array.Empty<int>()` which LINQ query providers may not expect. In fact, the C# compiler avoids optimization of `new int[0]` to `Array.Empty<int>()` for empty `params` arrays inside expression trees, see https://github.com/dotnet/roslyn/issues/1103. Therefore it's questionable than any analyzer suggests such a rewrite, even for manual empty "new array initialization" because whatever library that consumes the expression tree at runtime may not be hardended to expect a `MethodCallExpression` where a `NewArrayExpression` occurred before.

**Comment by mavasani** [comment]
@Evangelink Another case you may want to handle excluding in expression tree context.
