### ISSUE TITLE
Missing CA5394 rule

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#4673]
It looks like Microsoft.CodeAnalysis.NetAnalyzers is missing [CA5394](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5394).

**Comment by Youssef1313** [comment]
The rule is disabled by default, have you enabled it?

**Comment by mavasani** [comment]
I do see this rule include in the package. Can you double check?

**Comment by avivanoff** [comment]
Just. It has to do with "inheritance" of global analyzer config, or to be correct, the luck of inheritance the way it works with rulesets.

**Comment by mavasani** [comment]
@avivanoff To be clear, you were able to enable the rule and this issue can be closed?

**Comment by avivanoff** [comment]
Yes.
