### ISSUE TITLE
Port FxCop rule CA1819: PropertiesShouldNotReturnArrays

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#469]
**Title:** Properties should not return arrays

**Description:**

Arrays that are returned by properties are not write-protected, even when the property is read-only. To keep the array tamper-proof, the property must return a copy of the array. Typically, users will not understand the adverse performance implications of calling such a property.

**Dependency:** None

**Notes:**

**Comment by srivatsn** [comment]
Transitions bootcamp project.
