### ISSUE TITLE
Feature: Adhere to ContractVerification attribute

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4710]
I found [ContractVerification](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.contractverificationattribute?view=net-5.0) attribute by chance :smile:

The description says:

> Instructs analysis tools to assume the correctness of an assembly, type, or member without performing static verification.

So I believe we should adhere to it, or at least, have an option to that.

This should be applied to most (all?) analyzers.

**Comment by Youssef1313** [comment]
This could even be a Roslyn feature, that is all analyzers (first-party and third-party) are configurable to whether to adhere to the attribute or not.

**Comment by Youssef1313** [comment]
Tagging @terrajobst @stephentoub since this is related to .NET API usage.

**Comment by stephentoub** [comment]
This attribute is specific to the System.Diagnostics.Contract system and rewriter. It is not related to Roslyn analyzers.

**Comment by Youssef1313** [comment]
@stephentoub Should `Pure` attribute be the same? It's currently checked by CA1806.

**Comment by stephentoub** [comment]
Personally,  I don't think CA1806 should be paying attention to it. 
https://github.com/dotnet/runtime/issues/34098#issuecomment-604439020

**Comment by Youssef1313** [comment]
> it encourages further use of the attribute, which in my opinion is misguided.

Yes, I'm one of those who wanted to add the attribute anywhere it could benefit from CA1806.

@mavasani Are you okay with dropping Pure from CA1806?

Tagging @sharwell @333fred as well (https://github.com/dotnet/roslyn-analyzers/issues/1164 https://github.com/dotnet/roslyn-analyzers/pull/1171)

@stephentoub I think it also makes sense for the API docs of Pure to be clear about the actual intent of the attribute

**Comment by mavasani** [comment]
We are not going to add support for ContractVerification.
