### ISSUE TITLE
Fix editorconfigs for Microsoft.CodeAnalyzis.NetAnalyzers

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/roslyn-analyzers#4715]
Comparing microsoft.codeanalysis.netanalyzers\5.0.3\editorconfig\AllRulesEnabled\.editorconfig with microsoft.codeanalysis.fxcopanalyzers\3.3.2\editorconfig\AllRulesEnabled\.editorconfig shows that, while the severity is `warning` for all diagnistics in Microsoft.CodeAnalyzis.FxCopAnalyzers, it is `silent` or `suggestion` for several diagnostics in Microsoft.CodeAnalyzis.NetAnalyzers.

That defeats **AllRulesEnabled**.

/cc @mavasani

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn-analyzers/blob/4ce9cd5efe21ab9e0eabfd4eb3565cd2dde76b35/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs#L1052

I haven't went into debugging this, but the above line is suspicious. It indicates that the default severity will be used:

https://github.com/dotnet/roslyn-analyzers/blob/4ce9cd5efe21ab9e0eabfd4eb3565cd2dde76b35/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs#L1061-L1064

**Comment by mavasani** [comment]
Yes, that sounds correct. This tooling was primarily designed for FxCopAnalyzers package where the rules were all Warning by default, some enabled and others disabled. This is no longer the case with NetAnalyzers, so we now need to bump up the severity to warning for enabled editorconfigs and rulesets.

**Comment by paulomorgado** [comment]
If I can get a specification of what would be a good strategy, I can add it to https://github.com/paulomorgado/dotnet-analyzer-docmtr
