### ISSUE TITLE
Consider enabling CA2100 (security analyzer) against generated code

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4744]
### Analyzer

**Diagnostic ID**: [CA2100](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2100)

Consider enabling CA2100 against generated code. It's currently not enabled:

https://github.com/dotnet/roslyn-analyzers/blob/b148fa89c974a72c28184931767835709f34d1fa/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Data/ReviewSqlQueriesForSecurityVulnerabilities.cs#L41

Also consider moving it from `Data` directory to `Security` directory.

**Comment by mavasani** [comment]
@dotpaul What do you think?

**Comment by Youssef1313** [comment]
Also applies to:

https://github.com/dotnet/roslyn-analyzers/blob/b148fa89c974a72c28184931767835709f34d1fa/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/MarkVerbHandlersWithValidateAntiforgeryTokenAnalyzer.cs#L101

https://github.com/dotnet/roslyn-analyzers/blob/60fec5c28143441c2311e14c77f032a7c21cc19b/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/ReviewVisibleEventHandlers.cs#L38

https://github.com/dotnet/roslyn-analyzers/blob/028d9e0c1ad9e5e80ad503d35a804bd62210ecbb/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs#L39

**Comment by dotpaul** [comment]
CA2100 and CA3147 sound fine to me. The last two might need to be removed, so I wouldn't want to make them also analyze generated code.

**Comment by Youssef1313** [comment]
Closing as fixed.
