### ISSUE TITLE
PublicAPIAnalyzer CodeFix does not respect existing newline style

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-analyzers#4749]
https://github.com/dotnet/roslyn-analyzers/blob/62f71ea5c1ad04f9c4e5579c5c2b97fab16ff967/src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs#L110

Instead of reading the line endings that already exist in the file, the public API analyzers use the default from the environment. This is a problem on Windows when autocrlf is off, or when the source is shared with a Linux partition (such as WSL or when running Windows in a VM) and the line endings are set to just `\n`. Instead, it should be looking at the existing line endings in the file and, if they are just `\n`, only using that, instead of unconditionally using the environment-default newline.

**Comment by Youssef1313** [comment]
The same should apply to `AnnotatePublicApiFix` and `NullableEnablePublicApiFix`.
