### ISSUE TITLE
CSharpDoNotUseInsecureXSLTScriptExecutionAnalyzer is slow

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn-analyzers#4754]
### Analyzer

**Diagnostic ID**: [CA3076](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA3076): `Insecure XSLT Script Execution`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.102](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

Enabling analyzers for [our solution](https://github.com/linq2db/linq2db/pull/2789) resulted in huge performance impact on build time. After checking for culprit using [`ReportAnalyzer`](https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Report%20Analyzer%20Format.md) option I've found that depending on project this diagnostic takes 50-97 % of time used by all analyzers.

### Steps To Reproduce

Checkout [linq2db](https://github.com/linq2db/linq2db) solution and run `CA3076` diagnostic on it.

### Expected behavior

Slight performance impact on build time

### Actual behavior

main linq2db.csproj project
```
  Total analyzer execution time: 135.190 seconds.
  NOTE: Elapsed time may be less than analyzer execution time because analyzers can run concurrently.
  Time (s)    %   Analyzer
  131.483   97   Microsoft.CodeAnalysis.CSharp.NetAnalyzers, Version=5.0.3.2303, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  130.474   96      Microsoft.NetFramework.CSharp.Analyzers.CSharpDoNotUseInsecureXSLTScriptExecutionAnalyzer
  0.589   <1      Microsoft.NetFramework.CSharp.Analyzers.CSharpDoNotUseInsecureDtdProcessingInApiDesignAnalyzer

```

**Comment by Youssef1313** [comment]
@Evangelink Have you rewritten this analyzer recently using IOperation? Does that fix the perf issue?

**Comment by mavasani** [comment]
Yes, this is correct. Kindly try the latest NuGet package at https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet

**Comment by MaceWindu** [comment]
looks good
```
  3.528    2   Microsoft.CodeAnalysis.NetAnalyzers, Version=6.0.4.10107, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  0.466   <1      Microsoft.NetFramework.Analyzers.DoNotUseInsecureXSLTScriptExecutionAnalyzer

```
