### ISSUE TITLE
RS0027 shouldn't warn if the other overload is obsolete

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn-analyzers#4766]
### Analyzer

**Diagnostic ID**: [RS0027](https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md)

### Describe the improvement

When the overload with longer parameter list is obsolete, RS0027 shouldn't be triggered.

See https://github.com/dotnet/roslyn/pull/50911#discussion_r568877953

**Comment by Youssef1313** [comment]
@genlu Should this apply to RS0026 as well?

**Comment by Evangelink** [comment]
It would makes sense IMO. @mavasani?
