### ISSUE TITLE
doc of CA1711 should be update to unlist `System.Enum` from Flag(s)

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/roslyn-analyzers#4778]
### Analyzer

**Diagnostic ID**: [CA1711](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1711): `Identifiers should not have incorrect suffix`

### Describe the bug

Seems #3360 already update CA1711 to report enum with Flag or Flags suffix. But the doc is not updated, and still say it's ok to use Flag(s) with Enum. 
The doc should be update to match what it actual works to make it more clear, and `Flag(s)` should be an part of `In addition, the following suffixes should not be used:`.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/docs/pull/22649
