### ISSUE TITLE
Port FxCop rule CA2004: RemoveCallsToGCKeepAlive

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#479]
**Title:** Remove calls to GC.KeepAlive

**Description:**

If you convert to SafeHandle usage, remove all calls to GC.KeepAlive (object). In this case, classes should not have to call GC.KeepAlive. This assumes they do not have a finalizer but rely on SafeHandle to finalize the OS handle for them.

**Dependency:** None

**Notes:**

**Comment by AaronRobinsonMSFT** [comment]
Interop team doesn't think this is useful. This can be closed.

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
