### ISSUE TITLE
Port FxCop rule CA2006: UseSafeHandleToEncapsulateNativeResources

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#480]
**Title:** Use SafeHandle to encapsulate native resources

**Description:**

Use of IntPtr in managed code might indicate a potential security and reliability problem. All uses of IntPtr must be reviewed to determine whether use of a SafeHandle, or similar technology, is required in its place.

**Dependency:** None

**Notes:**

**Comment by AaronRobinsonMSFT** [comment]
Interop team doesn't think this is useful. This can be closed.

**Comment by Evangelink** [comment]
Closing this issue as won't be ported as per https://github.com/dotnet/runtime/issues/61964#issuecomment-1007687223.
