### ISSUE TITLE
Incorrect CA1508 when variable is captured by local function

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#4824]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Incorrect-CA1508-when-variable-is-captur/1334856)._

---
[severity:It bothers me. A fix would be nice]
The code analysis reports incorrectly that a variable captured by a local function which is not called directly is always `null`.

```cs
namespace Demo
{
    class Test
    {
        static void MaybeCall(System.Action action) => action ();
        public static void F()
        {
            string? x = null;
            void Local() { x = "foo"; }
            Test.MaybeCall (Local);
            if (x is null) // CA1508 'x is null' is always 'true'
            {
                throw new System.InvalidOperationException ();
            }
        }
    }
}
```

---
#### Feedback Bot on 2/9/2021, 06:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn-analyzers/issues/4145 (not sure if it's a dupe or not).

**Comment by epsitec** [comment]
I tried adding this to the `.editorconfig` file at the root of the solution, but I did not see any change with the generated warnings:
```
[*.cs]
dotnet_code_quality.interprocedural_analysis_kind = ContextSensitive
```

**Comment by genlu** [comment]
@epsitec adding "ContextSensitive" to editorconfig should change the diangostic from `'x is null' is always 'true'` to `'x is null' is always 'false'`. Closed as duplication.

**Comment by epsitec** [comment]
@genlu but event `'is is null' is always 'false'` would be an incorrect warning, since the code does not know what will happen (i.e. if the `Local()` function gets called or not). I feel that this issue should not have been closed.

**Comment by genlu** [comment]
@epsitec Not sure I'm following. `Test.MaybeCall (Local)` would always invoke `Local`, based on its definition, right?

```cs
static void MaybeCall(System.Action action) => action ();
```
