### ISSUE TITLE
New rule: Avoid possible dependency confusion in NuGet.config

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#4852]
### Describe the problem you are trying to solve

See <https://www.msn.com/en-us/money/other/microsoft-warns-enterprises-of-new-dependency-confusion-attack-technique/ar-BB1dynJl>.

Also https://github.com/xamarin/xamarin-android-tools/pull/105

### Describe suggestions on how to achieve the rule

The rule should be capable of reading NuGet.config file, and analyzing it for any possible dependency confusion.

**Note:** Not sure if it's possible to implement this reliably. If the implementation could have false positives, it should be disabled by default.

**Comment by Youssef1313** [comment]
@dotpaul This vulnerability appears to be *very common*.

**Comment by dotpaul** [comment]
Thanks @Youssef1313. This isn't an issue that a Roslyn analyzer can catch. Installing NuGet packages happens before compilation.
