### ISSUE TITLE
Memory Leak Persists

### ISSUE THREAD

**Issue by adraut** [dotnet/roslyn-analyzers#4859]
![image](https://user-images.githubusercontent.com/6654075/108111248-0ea51700-705a-11eb-8ec9-afb93f86ae40.png)

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.3 (Latest)

### Describe the bug

Every build with the analyzers enabled increases memory usage by a few hundred MB.

### Steps To Reproduce

Have a solution with 10+ projects.
Enable latest analyzers.
Run a few builds.
Watch the memory usage grow and grow.

### Expected behavior
Memory usage grows with the first build and stays fairly consistent there after or has minimal growth.

### Actual behavior
Memory usage grows quite a bit with each build.

## Additional context
Project is targeting net472 and netstandard2.0

**Comment by sharwell** [comment]
To review this performance feedback, we would need it submitted through the Report a Problem tool in Visual Studio. Here is the reply I give for requesting this performance information:

> Thank you for providing feedback, and we're sorry to hear it's not behaving as you expect. Based on your description so far, it sounds like you are experiencing a problem which is historically hard to diagnose and resolve using the normal "steps to reproduce". We created a set of instructions for providing additional information which will help us track down the true source of the problems.
>
> Based on the information provided so far, the most likely scenario to follow is for "Slowness and High CPU Issues". Please look at the following document to provide the feedback most relevant for the problems you would like to see fixed: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#slowness-and-high-cpu-issues

**Comment by Youssef1313** [comment]
@sharwell This will (most likely) be in the data flow analysis.

For example the following `GetExitBlockOutputData`:

https://github.com/dotnet/roslyn-analyzers/blob/2741c0a80528b1d022aab53643c37235371eec89/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs#L2259

I think in most cases (if not all), the method returns IDisposable, but as this is a non-constraint generic type, it doesn't seem to get disposed anywhere. (this wouldn't be the only case).

I'm unfortunately lacking knowledge in DFA area and also unable to investigate more today. Would you be able to check?

**Comment by sharwell** [comment]
> it doesn't seem to get disposed anywhere

This is typically fine. Correctly written types will not leak in the steady state (over time) whether or not they are disposed.

The information requested above will immediately reveal the source of the retained data through parallel GC root analysis.
