### ISSUE TITLE
CA2016: Code fix removes generic type parameter from message

### ISSUE THREAD

**Issue by DavidBoike** [dotnet/roslyn-analyzers#4870]
### Analyzer

**Diagnostic ID**: [CA2016](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2016): Forward the CancellationToken parameter to methods that take one

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.103](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

Consider the following code snippet, which will highlight CA2016 on the `reader.GetFieldValueAsync` method:

```
static async Task<Guid> Foo(SqlDataReader reader, CancellationToken cancellationToken)
{
    return await reader.GetFieldValueAsync<Guid>(0)
        .ConfigureAwait(false);
}
```

Using the fixer will result in this code, with the generic type `<Guid>` stripped from the method call:

```
static async Task<Guid> Foo(SqlDataReader reader, CancellationToken cancellationToken)
{
    return await reader.GetFieldValueAsync(0, cancellationToken)
        .ConfigureAwait(false);
}
```

Because of the removal of the generic type from the method call, the code now has this compile error:

> CS0411 The type arguments for method 'SqlDataReader.GetFieldValueAsync<T>(int, CancellationToken)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

### Steps To Reproduce

1. Create a project targeting `net5.0`.
1. Add a package reference to `Microsoft.Data.SqlClient`.
1. Add the code above.
1. Use the code fix on `reader.GetFieldValueAsync`.
1. See error.

### Expected behavior

Should add the cancellation token to the method arguments without modifying the type argument.

### Actual behavior

Type argument is removed.

**Comment by eskye** [comment]
I will like to work on this issue

**Comment by mavasani** [comment]
@eskye Feel free to pick it up. @carlossanlop can guide you if you need any help.

**Comment by eskye** [comment]
> @eskye Feel free to pick it up. @carlossanlop can guide you if you need any help.

Okay, thanks. I think I'll surely need a guide @carlossanlop

**Comment by eskye** [comment]
@carlossanlop Please I need help.

**Comment by DavidBoike** [comment]
@eskye What do you need help with exactly? I have some analyzer/fixer experience and reported the bug thinking maybe soon I'd have time to look at it myself, but of course I haven't. :wink: The fixer itself is [implemented here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Fixer.cs) but looks pretty complex compared to what it actually needs to do, but then again I've never done a fixer that targets both C# and VB. Here's the [analyzer](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocations.Analyzer.cs) it's attached to. Here are the [tests](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/ForwardCancellationTokenToInvocationsTests.cs).

Conceptually, the fixer needs to find the ArgumentList of the invocation, add the CancellationToken in the right spot (which creates a new object since everything is immutable) and then replace the node representing the argument list with the new argument list. I'm honestly not sure why the scope of the change is wide enough to affect the generic type argument in the first place.

**Comment by eskye** [comment]
@DavidBoike Thank you for taking the time to explain. I've checked the files you shared, but I still can't relate exactly to what I need to do. but I'll be glad if you can further walk through it with me.

**Comment by carlossanlop** [comment]
@eskye how familiar are you with writing Roslyn analyzers? Have you followed the [official tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)?

This bug is in the fixer code. The fixer takes all the original symbol reported by the diagnostic, makes the necessary changes to it, and then replaces the symbol with the updated one.

The current fixer code does not detect if the [method is generic](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generic-methods), so the updated symbol has its type parameter removed.

The fix consists in determining if a method is generic, in which case, the type parameter needs to be extracted, and then re-added in the updated symbol.

Hope that helps.

**Comment by DavidBoike** [comment]
This issue is fixed by https://github.com/dotnet/roslyn-analyzers/pull/4974 which is ready for review.

**Comment by carlossanlop** [comment]
@DavidBoike thanks for sending a PR.

@eskye we have other issues you can help with if you still would like to learn. Ping me if you want to take one.

**Comment by eskye** [comment]
> @DavidBoike thanks for sending a PR.
> 
> @eskye we have other issues you can help with if you still would like to learn. Ping me if you want to take one.

@carlossanlop I'll like to pick other issues, let me know how I can go about it. thank you. @DavidBoike  Well done, I was actually struggling to understand the Roslyn analyzer code. I've not work with it before.
