### ISSUE TITLE
CA2250: Add support for VB.NET

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#4875]
### Analyzer

**Diagnostic ID**: [CA2250](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2250)

### Describe the improvement

Implement VB.NET counterpart.

**Comment by Youssef1313** [comment]
@Evangelink The analyzer was dropped per https://github.com/dotnet/roslyn-analyzers/pull/4868#issuecomment-782933140, so this can be closed.
