### ISSUE TITLE
Port FxCop rule CA2111: PointersShouldNotBeVisible

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#489]
**Title:** Pointers should not be visible

**Description:**

A pointer is not private, internal, or read-only. Malicious code can change the value of the pointer, which potentially gives access to arbitrary locations in memory or causes application or system failures.

**Proposed analyzer:** Microsoft.QualityGuidelines

**Dependency:** None

**Notes:**

@nguerrera  to validate this decision

**Comment by nguerrera** [comment]
We should cut this. It only fires on visible fields non-readonly fields, which would already trigger the API design rule against them in general.

**Comment by lgolding** [comment]
The FileIssues tool re-opened this issue because it was closed manually but the spreadsheet wasn't updated. Updated the spreadsheet. Closing this issue again manually (the next run of the tool, if any, would have closed it).
