### ISSUE TITLE
Incorrect CA1508 in using block

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#4912]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Incorrect-CA1508-in-using-block/1350676)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.9.0 Preview 5.0]
Since upgrading to Visual Studio 16.9.0 Preview 5.0 I am getting warnings (CA1508) which just don't make sense to me:

! [image.png] (https://aka.ms/dc/image?name=B212630ee292e40409f6d047e753c69b6637499226979609936_20210226-085137-image.png&tid=212630ee292e40409f6d047e753c69b6637499226979609936)

Why does the analyzer think that I am checking for `null` here?

---
#### Feedback Bot on 2/28/2021, 06:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/1/2021, 09:36 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
Likely a duplicate

**Comment by Youssef1313** [comment]
This was fixed in the NuGet package but probably didn't yet ship with the SDK.

**Comment by mavasani** [comment]
Can you please verify the fix by adding a NuGet Package reference to latest Microsoft.CodeAnalysis.NetAnalyzers NuGet package?

**Comment by Youssef1313** [comment]
I'm going to close the issue as fixed.
