### ISSUE TITLE
CA2213 does not recognize an IAsyncDisposable implementaton as sufficient.

### ISSUE THREAD

**Issue by MartyIX** [dotnet/roslyn-analyzers#4950]
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

### Describe the bug

CA2213 seemingly does not consider [DisposeAsyncCore](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#disposeasync-and-disposeasynccore) method. 

```csharp
/// <summary>State object for <see cref="RestClient"/>.</summary>
private readonly RestClientContext restContext; // <<<< CA2213: WARNING EMMITED HERE.

// ...

/// <summary>
/// Frees managed resources used by the object.
/// </summary>
/// <returns>A <see cref="ValueTask">task</see> that represents the asynchronous dispose operation.</returns>
protected virtual async ValueTask DisposeAsyncCore()
{
    this.log.Debug("*");

    lock (this.disposedValueLock)
    {
        if (this.disposedValue)
        {
            this.log.Debug("$<ALREADY_DISPOSED>");
            return;
        }

        this.disposedValue = true;
    }

    this.log.Debug("Dispose REST context.");
    this.restContext.Dispose(); // // This does not make the warning go away!

    this.log.Debug("$");
}

/// <inheritdoc/>
public async ValueTask DisposeAsync()
{
    // this.restContext.Dispose(); // THIS MAKES THE WARNING GO AWAY.
    await this.DisposeAsyncCore().ConfigureAwait(false);
    GC.SuppressFinalize(this);
}
```

### Steps To Reproduce

Please see the source code above.

### Expected behavior

No warning is emitted when `this.restContext.Dispose();` is called in `DisposeAsyncCore`.

### Actual behavior

A warning is emitted when `this.restContext.Dispose();` is called in `DisposeAsyncCore`.

**Comment by MartyIX** [comment]
@Youssef1313 Would this be something worthwhile for you? 🙏

**Comment by sharwell** [comment]
@mavasani this appears to be a case where a field is not being disposed directly within `Dispose()`, but instead within a non-patterned helper method. Do you know the degree to which this interprocedural analysis is supported under the default configuration?

**Comment by MartyIX** [comment]
@sharwell But the name is standard-ish according to https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#disposeasync-and-disposeasynccore, isn't it?
