### ISSUE TITLE
CA1508 - 'ReferenceEquals(firstClient, secondClient)' is always 'true'

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/roslyn-analyzers#4953]
### Analyzer

CA1508

### Analyzer source

**NuGet Package**: Microsoft.CodeAnalysis.NetAnalyzers

**Version**: 5.0.3 (Latest)

### Describe the bug

The analyser says that the result is always true, but this test passes (when I disable the error)

![image](https://user-images.githubusercontent.com/16697547/111265545-5b8e0480-867d-11eb-8dee-7802349a9e9b.png)

### Steps To Reproduce

Clone this repo:
- https://github.com/MelbourneDeveloper/RestClient.Net
- Check out branch RemoveHttpClientFromResponse (commit 0c48c92d16021b1837029b49f533bef05460b9ca)
- Run the test and notice that it passes

- Remove #pragma warning disable CA1508 at [line 1602](https://github.com/MelbourneDeveloper/RestClient.Net/blob/0c48c92d16021b1837029b49f533bef05460b9ca/src/RestClient.Net.UnitTests/MainUnitTests.cs#L1602) of MainUnitTests
- Notice that you see the Roslyn error

### Expected behavior

No error

### Actual behavior

Error

### Additional Information

Yes, I'm aware that this unit test is no good and could give false positives. I'm just logging it for the point of explaining the issue.

**Comment by mavasani** [comment]
This is fixed with #6811. Please let us know if this still repros on the upcoming .NET 8 preview SDK.
