### ISSUE TITLE
Incorrect RS1024 analysis when calling GetHashCode(ReadOnlySpan<char>, StringComparison)

### ISSUE THREAD

**Issue by pranavkm** [dotnet/roslyn-analyzers#4956]
### Analyzer

RS1024

### Analyzer source

**Version**: 3.10.0-2.21166.52

### Steps To Reproduce

1. Reference the 3.10.0-2.21166.52 of Roslyn binaries in a console app
2. Code:
```C#
ReadOnlySpan<char> foo = default;
int hashCode = string.GetHashCode(foo, StringComparison.OrdinalIgnoreCase);
```

### Actual behavior

```
error RS1024: Compare symbols correctly
```

**Comment by pranavkm** [comment]
FYI @sharwell

**Comment by Youssef1313** [comment]
This is where the bug should be:

https://github.com/dotnet/roslyn-analyzers/blob/dc515b0412abf13d9d2b8e34543c61c9abbee87b/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs#L183-L184
