### ISSUE TITLE
No clear guidance on what analyzers to use for .net452

### ISSUE THREAD

**Issue by ColinM9991** [dotnet/roslyn-analyzers#4957]
Hi,

I have been through several Microsoft guides trying to figure out exactly which analyzers should be used for a .NET 452 project. All documents have been circular and have led to deprecated NuGet packages (FxCop) which cause warnings to appear in Visual Studio. I have also attempted to use `Microsoft.CodeAnalysis.NetAnalyzers` which causes many warnings to appear, some of which are:

>An instance of analyzer Microsoft.NetFramework.CSharp.Analyzers.CSharpDoNotUseInsecureXSLTScriptExecutionAnalyzer cannot be created from C:\source\git\project\packages\Microsoft.CodeAnalysis.NetAnalyzers.5.0.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

>An instance of analyzer Microsoft.NetCore.CSharp.Analyzers.Runtime.CSharpAvoidZeroLengthArrayAllocationsAnalyzer cannot be created from C:\source\git\project\packages\Microsoft.CodeAnalysis.NetAnalyzers.5.0.3\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified

I would appreciate if you could be specific on what package exactly should be used to enable code analysis for a .NET 452 project?

**Comment by Youssef1313** [comment]
@ColinM9991 As @jmarolf stated, `Microsoft.CodeAnalysis.NetAnalyzers` is the recommended package. FxCopAnalyzers package is deprecated. It would be helpful if you can attach a project where you're having issues.

**Comment by Youssef1313** [comment]
I'm going to close as answered. @ColinM9991 If you are having any issues with `Microsoft.CodeAnalysis.NetAnalyzers`, please open a new issue.
