### ISSUE TITLE
AvoidDeadConditionalCode slows down build

### ISSUE THREAD

**Issue by JohanLarsson** [dotnet/roslyn-analyzers#4960]
![image](https://user-images.githubusercontent.com/1640096/111797568-92f0f100-88c9-11eb-8f67-81c6120caa87.png)

Small project.

Repro: https://github.com/DotNetAnalyzers/WpfAnalyzers/tree/768fea89c90b27fd052d778f065852f49275bc70

**Comment by Youssef1313** [comment]
Related: https://github.com/dotnet/roslyn-analyzers/issues/4914

**Comment by Youssef1313** [comment]
Duplicate of #4914
