### ISSUE TITLE
Port FxCop rule CA2119: SealMethodsThatSatisfyPrivateInterfaces

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#497]
**Title:** Seal methods that satisfy private interfaces

**Description:**

An inheritable public type provides an overridable method implementation of an internal (Friend in Visual Basic) interface. To fix a violation of this rule, prevent the method from being overridden outside the assembly.

**Dependency:** None

**Notes:**

**Comment by srivatsn** [comment]
Implemented by #757
