### ISSUE TITLE
Suppress CA1303 for exception constructor parameters by default

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#4977]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suppress-CA1303-for-exception-constructo/1378444)._

---
[severity:It bothers me. A fix would be nice]
When using an exception constructor with a string parameter, a string literal within the parameter triggers CA1303 (do not pass literals as localized parameters) in the Globalization analyzer.

Take the case below, inside the setter for the property `Callsign.Sign`, where the string literal parameter within the ArgumentException triggers CA1303:

```csharp
class Callsign
{
    private string sign;
    public string Sign
    {
        get => sign;
        private set
        {
            if (string. IsNullOrWhiteSpace(value)) throw new ArgumentException($"{nameof(Sign)} cannot be null or whitespace.", nameof(Sign));
            sign = value;
        }
    }
}
```

Within the constructor of an exception, application state is not guaranteed (after all, exceptions often occur when the application is in an unexpected state). As a result, accessing the string from a resource table may not be possible: the stack may be all that’s available. Therefore, CA1303 should not be triggered within exception constructors by default.

---
#### Feedback Bot on 3/22/2021, 10:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
This is actually by design, you should be using a localized argument here.
