### ISSUE TITLE
Port FxCop rule CA2120: SecureSerializationConstructors

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#498]
**Title:** Secure serialization constructors

**Description:**

This type has a constructor that takes a System.Runtime.Serialization.SerializationInfo object and a System.Runtime.Serialization.StreamingContext object (the signature of the serialization constructor). This constructor is not secured by a security check, but one or more of the regular constructors in the type are secured.

**Proposed analyzer:** Desktop

**Notes:**

**Comment by Menyus777** [comment]
Could you put up a note why this rule was deprecated?
