### ISSUE TITLE
False positive for CA1508 in generic code

### ISSUE THREAD

**Issue by mookid** [dotnet/roslyn-analyzers#4990]
### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.3 (Latest)

### Describe the bug

source [here](https://github.com/mookid/reproductionVsBugs/tree/CA1508)

the following code reports twice CA1508, it is twice a false positive.

![image](https://user-images.githubusercontent.com/7757342/113325447-bc256e80-9318-11eb-9c8e-31033414350d.png)

The non-generic code with the same method body does not trigger it: 
![image](https://user-images.githubusercontent.com/7757342/113325502-d3fcf280-9318-11eb-9887-853c8ced318b.png)

**Comment by mookid** [comment]
Another funny example (same repository, the code is the same between the 2 methods):  
![image](https://user-images.githubusercontent.com/7757342/113327773-a5cce200-931b-11eb-8475-96f6a9c72a52.png)

**Comment by mavasani** [comment]
No repro on latest .NET 8 preview SDK
