### ISSUE TITLE
CA1822 (Mark member as static) fires for NUnit is not fully covered.

### ISSUE THREAD

**Issue by watsonsong** [dotnet/roslyn-analyzers#4995]
### Analyzer

**Diagnostic ID**: [CA1822](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822)

### Describe the improvement

This issue is reslove and closed at: https://github.com/dotnet/roslyn-analyzers/issues/1399
But I met this problem in Unity3D environment:
https://forum.unity.com/threads/is-there-a-way-suppress-the-ca1822-when-using-unitytestattribute.1084388/#post-6992105

### Describe suggestions on how to achieve the rule

Check the test not only by match the WellKnownTypes. If any attribute inherit from the [ITestBuilder](https://docs.nunit.org/articles/nunit/extending-nunit/ITestBuilder-Interface.html), this issue should be ignored.

**Comment by jnm2** [comment]
All my NUnit test methods are static on purpose fwiw.

**Comment by watsonsong** [comment]
Maybe skip this issue is not hardcode but provide an extensive way.
