### ISSUE TITLE
Migrate AnalyzerPowerPack to roslyn-analyzers

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn-analyzers#50]
This includes moving the following projects in the [dotnet/roslyn](http://github.com/dotnet/roslyn/) repo:
* AnalyzerPowerPack.Common
* AnalyzerPowerPack.CSharp
* AnalyzerPowerPack.Setup
* AnalyzerPowerPack.Test
* AnalyzerPowerPack.VisualBasic

**Comment by sharwell** [comment]
For those unaware, these are the start of the FxCop analyzers written for Roslyn.

I believe these analyzers should be moved out of dotnet/roslyn, but this is the wrong home for them. They should be placed in their own repository dedicated to the ongoing implementation of FxCop rules using the .NET Compiler Platform.

My vote is :-1: on the issue as-written.

**Comment by sharwell** [comment]
:bulb: I'm going to go ahead and suggest the name FxCopAnalyzers for the new repository, in line with the existing StyleCopAnalyzers project. :smile:
