### ISSUE TITLE
CA1065 Enhancement: Report on more operators

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#5021]
### Analyzer

**Diagnostic ID**: [CA1065](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1065)

### Describe the improvement

Currently, the rule reports `==` and `!=` operators that throw exceptions. I think it makes sense to extend that to `>`, `<`, `>=`, and `<=`.

**Comment by mavasani** [comment]
This looks to be a reasonable enhancement.
