### ISSUE TITLE
OWASP Top 10

### ISSUE THREAD

**Issue by jgcjoec** [dotnet/roslyn-analyzers#5024]
Is Microsoft.CodeAnalysis.NetAnalyzers an appropriate set of analyzers for organizations looking for static code analysis that covers the OWASP top 10?

https://owasp.org/www-project-top-ten/

In my research, it seems that the answer to this question is "yes", but was looking for confirmation.

Thanks,

- Joe

**Comment by Youssef1313** [comment]
You can find a list of the security rules [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/security-warnings). Might not include all the top 10.

**Comment by jgcjoec** [comment]
Yeah, it would be helpful to know "for sure" as a lot of infosec frameworks, such a SOC-2, talk about OWASP Top 10.

**Comment by dotpaul** [comment]
There are rules that can be categorized into some of the OWASP top 10, but some of the top 10 are more about design (e.g. for A3:2017-Sensitive Data Exposure, you must define what constitutes sensitive data) and not easily detected by code-level analysis.

Using Microsoft.CodeAnalysis.NetAnalyzers can help reduce risk.
