### ISSUE TITLE
RS2002 false-positive when using source generators

### ISSUE THREAD

**Issue by FiniteReality** [dotnet/roslyn-analyzers#5032]
### Analyzer

**Diagnostic ID**: [RS2002](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.Analyzers/ReleaseTrackingAnalyzers.Help.md): `Do not add removed analyzer diagnostic IDs to unshipped analyzer release`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers)

**Version**: 3.3.2 (Latest)

### Describe the bug

Using the release tracking analyzers in a source generator appears to consistently lead to RS2002, despite declaring the the `DiagnosticDescriptor` in a private static field with the same diagnostic ID.

### Steps To Reproduce

1. Create a source generator
2. Define a DiagnosticDescriptor with a rule
3. Add that rule to the unshipped analyzer releases
4. Try to build
5. Receive RS2002 error

### Expected behavior

RS2002 does not appear and the build succeeds

### Actual behavior

The build fails with error `RS2002: Rule 'SG0001' is part of the next unshipped analyzer release, but is not a supported diagnostic for any analyzer`.

## Additional context

I'm currently using OmniSharp, and so have had to manually populate `AnalyzerReleases.Unshipped.md` due to https://github.com/OmniSharp/omnisharp-roslyn/issues/1592 but as far as I can tell from reading the code, it seems to be formatted correctly and is indeed picked up correctly.

A more complete project containing a source generator which reproduces the error can be found here: https://github.com/FiniteReality/Finite.Commands/tree/issue/10/tools/SourceGenerators/Models/AttributedModel

**Comment by Youssef1313** [comment]
@FiniteReality Can you try moving the AnalyzerReleases files inside `AttributedModel` directory?

**Comment by FiniteReality** [comment]
...I'm an idiot. I need to drink more coffee before reading error messages, maybe I'll actually pay attention :sweat_smile:

**Comment by Youssef1313** [comment]
> ...I'm an idiot. I need to drink more coffee before reading error messages, maybe I'll actually pay attention 😅

It took me a while to figure it out 😄

**Comment by mavasani** [comment]
Thank you @Youssef1313 for helping out here!
