### ISSUE TITLE
CA2016 fixer removes generic parameter

### ISSUE THREAD

**Issue by meziantou** [dotnet/roslyn-analyzers#5051]
### Analyzer

**Diagnostic ID**: [CA2016](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2016): `Forward the CancellationToken parameter to methods that take one`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: SDK 6.0.100-preview.3.21202.5

### Describe the bug

The CA2016's fixer removes the generic parameters in some cases.

### Steps To Reproduce

````
public class Class1
{
    async Task Repro(CancellationToken cancellationToken)
    {
        var instance = new Class1();
        instance.A<int>(); // BUG:      instance.A(cancellationToken);
                           // Should be instance.A<int>(cancellationToken);

        this.A<int>(); // BUG: this.A(cancellationToken);
                       // Should be this.A<int>(cancellationToken);

        A<int>(); // OK: A<int>(cancellationToken);
    }

    void A<T>() => throw null;
    void A<T>(CancellationToken cancellationToken) => throw null;
}
````

### Expected behavior

CA2016's fixer doesn't remove the generic parameters

### Actual behavior

It removes the generic parameters, so the code doesn't compile

**Comment by mavasani** [comment]
Tagging @carlossanlop - I thought there was a PR already out for this?
