### ISSUE TITLE
CA1822 not work with preprocessor directives

### ISSUE THREAD

**Issue by watsonsong** [dotnet/roslyn-analyzers#5053]
### Analyzer

**CA1822**: [CA1822](https://docs.microsoft.com/zh-cn/dotnet/fundamentals/code-analysis/quality-rules/ca1822)

### Describe the improvement
If the member data access is warpped in some define, it will report this rule.
```
public void Foo()
{
#if SOME_DEFINE
    System.Console.WriteLine(this.data);
#endif
}
```

### Describe suggestions on how to achieve the rule
Some workaround better than just supress it.

**Comment by Youssef1313** [comment]
At the analyzer level, nothing could be done. See https://github.com/dotnet/roslyn-analyzers/issues/4998#issuecomment-813487643.

**Comment by mavasani** [comment]
Agreed with @Youssef1313. This is by design.
