### ISSUE TITLE
RS0017: No information on how to "remove" public API

### ISSUE THREAD

**Issue by RussKie** [dotnet/roslyn-analyzers#5058]
### Analyzer

**Diagnostic ID**: [RS0017](https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md#rs0017-remove-deleted-types-and-members-from-the-declared-api)

### Describe the improvement

The docs are sorely lacking information on how to address RS0017 rule. 
> C:\Development\winforms\src\System.Windows.Forms.Design\src\PublicAPI.Shipped.txt(795,1,795,160): warning RS0017: Symbol 'virtual System.Windows.Forms.Design.Behavior.Behavior.OnMouseUp(System.Windows.Forms.Design.Behavior.Glyph g, System.Windows.Forms.MouseButtons button) -> bool' is part of the declared API, but is either not public or could not be found

The suggestion to remove "_corresponding entry in PublicAPI.txt_" in most scenarios where PublicApiAnalyzers are used would be incorrect, as such change in most scenario won't be shipped until later.

I had a vague recollection that there was a procedure to record _unshipped_ removals, but I had to employ a significant bing-fu to eventually stumble on a [note in thr Roslyn repo](https://github.com/dotnet/roslyn/blob/main/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md#note).

> _Public API Analyzer complains about it, you should copy the entry for your change from PublicAPI.Shipped.txt and then put that entry in PublicAPI.Unshipped.txt with \*REMOVED\* prefix._

### Describe suggestions on how to achieve the rule

The docs must clearly articulate how to remove an API, and address RS0017.

I'm happy to update the docs but would like to get guidance on where the most appropriate place is.

E.g. this page seems logical, and if I understand it correctly it gets generated from 
https://github.com/dotnet/roslyn-analyzers/blob/9b41160da7c50dfa361a8869de7d0d5357aceced/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.sarif#L31-L49
Is "fullDescription" the right place to add more information?

**Comment by Youssef1313** [comment]
Shouldn't the codefix do its job?

**Comment by RussKie** [comment]
I don't think there's one since it's in a text file. At least I found no way to invoke it.

**Comment by Youssef1313** [comment]
> I don't think there's one since it's in a text file. At least I found no way to invoke it.

Ah yes. The codefix works for additional files *only if* the diagnostic location is in source. RS0017 isn't supported in a codefix.

**Comment by mavasani** [comment]
> Is "fullDescription" the right place to add more information?

Yes, that sounds correct. Feel free to even add information to the diagnostic message itself.

**Comment by tobias-tengler** [comment]
Is it planned to included codefixes for removals and updates in the future?

**Comment by RussKie** [comment]
As a workaround you can resue the work of @tmat from https://github.com/dotnet/roslyn/blob/main/scripts/PublicApi/ to ease the pain of shipping API each release.
