### ISSUE TITLE
AD0001 Analyzer 'Microsoft.CodeAnalysis.PublicApiAnalyzers.DeclarePublicApiAnalyzer' threw an exception of type 'System.NullReferenceException'

### ISSUE THREAD

**Issue by mayerj** [dotnet/roslyn-analyzers#5061]
### Analyzer

RS0016: Public API analyzer

### Analyzer source

**NuGet Package**: Microsoft.CodeAnalysis.PublicApiAnalyzers

**Version**: 3.3.2, and tip of main branch

### Describe the bug

Unexpected AD0001 when you have a csproj file that includes the "PublicAPI.Shipped.txt" or "PublicAPI.Unshipped.txt" explicitly via:

```
  <ItemGroup>
    <AdditionalFiles Include="PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
  </ItemGroup>
```

### Steps To Reproduce

Create a new project file using the content below:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

Do not create "PublicAPI.Shipped.txt" or "PublicAPI.Unshipped.txt" on disk.

Compile csproj

### Expected behavior

Either a warning saying the files couldn't be read, or RS0048 "file missing"

### Actual behavior

AD0001 NullReferenceException here:

https://github.com/dotnet/roslyn-analyzers/blob/90660a6b270c5b9a46be6bea6f83885de829f4d2/src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs#L264

(sourceText.Lines was null).

Edit: sourceText was null.

shippedText.GetText(cancellationToken) can return null.

## Additional context

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.CodeAnalysis.PublicApiAnalyzers
  StackTrace:
   at Microsoft.CodeAnalysis.PublicApiAnalyzers.DeclarePublicApiAnalyzer.ReadApiData(String path, SourceText sourceText, Boolean isShippedApi) in C:\repositories\dotnet\roslyn-analyzers\src\PublicApiAnalyzers\Core\Analyzers\DeclarePublicApiAnalyzer.cs:line 264

```

**Comment by Youssef1313** [comment]
When fixing this, keep in mind whether this should respect `dotnet_public_api_analyzer.require_api_files` or not.

https://github.com/dotnet/roslyn-analyzers/blob/3344b723fb90e3525bc7c3a1116856127f295070/src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs#L35-L38

**Comment by mayerj** [comment]
This is #5070
