### ISSUE TITLE
configure rule severity  in .EditorConfig is not working for category level

### ISSUE THREAD

**Issue by Ankhimes** [dotnet/roslyn-analyzers#5077]
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

_OR_

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.3 (Latest)

**Comment by Ankhimes** [comment]
[*.cs]

dotnet_analyzer_diagnostic.category-design.severity = error

is not working

**Comment by Youssef1313** [comment]
@Ankhimes Have you tried "Design" instead of "design"?
I think the category may be case-sensitive.

**Comment by Ankhimes** [comment]
![categoryRuleapplied](https://user-images.githubusercontent.com/73706845/116649424-d6e11680-a99c-11eb-82c1-c15236127a32.png)

As clear in the screenshot...Indiviadual rule ID rule works but Category Rule is not working

**Comment by mavasani** [comment]
@Ankhimes Your issue here is that CA1031 is disabled by default, and `dotnet_analyzer_diagnostic.category-XXX.severity` entries only apply to analyzers which are enabled by default. Please see the `Important` note section in https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-options#scope for details and how to configure this correctly.

**Comment by Ankhimes** [comment]
Thanks for updates. But I did tried that option by updating the csproj file and its not working. Is there any other setting I need to try with.

![image](https://user-images.githubusercontent.com/73706845/116651876-c41d1080-a9a1-11eb-9d5e-518e71307802.png)

**Comment by Ankhimes** [comment]
> @Ankhimes Your issue here is that CA1031 is disabled by default, and `dotnet_analyzer_diagnostic.category-XXX.severity` entries only apply to analyzers which are enabled by default. Please see the `Important` note section in https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-options#scope for details and how to configure this correctly.

Thanks for updates. But I did tried that option by updating the csproj file and its not working. Is there any other setting I need to try with.
![image](https://user-images.githubusercontent.com/73706845/116651985-ea42b080-a9a1-11eb-80d5-5ed2971994d4.png)

**Comment by mavasani** [comment]
Can you share your project as a zip or at least the screenshot of entire project file?

**Comment by Ankhimes** [comment]
> Can you share your project as a zip or at least the screenshot of entire project file?

![image](https://user-images.githubusercontent.com/73706845/116652243-6dfc9d00-a9a2-11eb-87cb-af61cfb3b2b5.png)

**Comment by mavasani** [comment]
Ah, I get the core issue now. `AnalysisMode` property works by adding a [globalconfig](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig) to the project that explicitly sets severity for every rule by rule ID as a warning. This means that the category based bulk configuration setting has lower precedence and never works. In short, `AnalysisMode` and `dotnet_analyzer_diagnostic.category-<rule category>.severity = <severity value>` can never work together in the current implementation of auto-generated global config files for `AnalysisMode`.

I know how we can fix this, I'll have a PR out for this sometime today/tomorrow. Meanwhile, I suggest you explicitly escalate each rule by rule ID instead of doing it by category.

**Comment by Youssef1313** [comment]
@mavasani Isn't this the same issue as https://github.com/dotnet/roslyn/issues/51225 which got fixed?

**Comment by mavasani** [comment]
@Youssef1313 This is a different issue - the compiler is working as expected, the global config from AnalysisMode has ruleID based entry which will always override all category based entries. The solution is to change the config file generation for AnalysisMode to use category based entries.

**Comment by Youssef1313** [comment]
Got it thanks.

Switching to the globalconfig generation to category based entries can affect other analyzers if they use the same category though, will that be intended?

**Comment by mavasani** [comment]
So, I put more thought into this and I believe this scenario cannot be supported based on the current compiler and AnalsisMode design.

1. Only way to enable a disabled by default rule is with a ruleID based dotnet_diagnostic entry.
2. Even if you specify `<AnalysisMode>AllEnabledByDefault</AnalysisMode>` in the the project file, the auto-generated global config has to specify a ruleID based entry, category based entry will not enable a disabled by default rule.
3. Now, as a ruleID based entry has been specified, there is no way to use a category based bulk configuration entry as it can never override ruleID based entry.

The only possible solution here could be if we introduce parallel group of auto-generated editorconfigs for enabling rules as warnings vs enabling them as errors. This is a much bigger work item, and we probably need more customer feedback before attempting any such changes. @Ankhimes - do you think just using `<CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>` to bump all CA warnings to errors will suffice your scenario?

**Comment by Ankhimes** [comment]
@mavasani Thanks for your support. Unfortunately we don't have requirement to convert all warnings as error.
We only need to configure severity based on the category

**Comment by mavasani** [comment]
@Ankhimes In that case you will need to do the following:

1. Use the category based entry to escalate all the enabled by default rules in categories to errors.
2. Use rule ID based entries to escalate individual disabled by default rule to error.
3. Wait for https://github.com/dotnet/roslyn/issues/47046#issuecomment-678474546 so we can use category based entries to apply on disabled by default rules.

**Comment by mavasani** [comment]
Closing this out as there is not much we can do here. You need to follow the suggestion above.

**Comment by Dubzer** [comment]
Hi. Just to share my use case: I ran into this limitation when I wanted to disable the analyzers for a specific directory, and I created an .editorconfig file in it:
```editorconfig
[*.cs]
dotnet_analyzer_diagnostic.severity = none
```

I know that `generated_code = true` exists, but unfortunately it disables all warnings, including the rules for nullability.
And I don't really want to enable all categories separately, as they may be added in a future update
