### ISSUE TITLE
CA1812 cannot be suppressed

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#5134]
![image](https://user-images.githubusercontent.com/31348972/119708142-3e836800-be5c-11eb-880d-482775e18200.png)

Quick actions doesn't show suppression options, and manually writing a suppression line doesn't suppress the diagnostic.

Notes:

- No idea if this is related to roslyn or roslyn-analyzers.
- This analyzer is compilation end.
- I'm treating warnings as errors, but it seems this failed CI for Windows and Mac only, but not for Linux (this unlikely to be a roslyn-analyzers issue):

    ![image](https://user-images.githubusercontent.com/31348972/119708860-de40f600-be5c-11eb-9010-6da791cea3a4.png)

https://github.com/MSDocsBuild/build-verifier/pull/2/checks?check_run_id=2677795196
https://github.com/MSDocsBuild/build-verifier/pull/2/commits/f957eca97f050d356c3c9248fa4c0e91c4221909

**Comment by Youssef1313** [comment]
This was a "stuck" diagnostic. Cleaning and rebuilding fixed that.

But code actions are not offered:

![image](https://user-images.githubusercontent.com/31348972/119709772-de8dc100-be5d-11eb-8963-3bdbaf873992.png)

@mavasani Should likely move to roslyn?

**Comment by mavasani** [comment]
This is by design. Compilation End diagnostics do not participate in code fix computation due to performance reasons.
