### ISSUE TITLE
CA1002: Do not expose generic lists: Sealed classes

### ISSUE THREAD

**Issue by Hottemax** [dotnet/roslyn-analyzers#5139]
### Analyzer

**Diagnostic ID**: [CA1002](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1002)

### Describe the improvement

I don't see why suggestion is raised for classes that are declared as _public sealed_
They can not be inherited from, so why is this rule relevant?

**Comment by jmarolf** [comment]
@mavasani does this make sense as a configuration option

**Comment by mavasani** [comment]
This rule is candidate for deprecation, we are not doing any further work on this.
