### ISSUE TITLE
Any reason not to have DiagnosticDescriptor readonly

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#5169]
Hi there,

I was browsing the code base and realized that the `DiagnosticDescriptor` declared are `internal static` but not `readonly` while they are not expected to change. Is there a technical (perf?) reason to do so?

**Comment by Youssef1313** [comment]
@Evangelink The repo isn't consistent on this matter, but the majority are not `readonly`. So I don't think there is a reason.

**Comment by Evangelink** [comment]
If there are no technical consideration, it might be worth to fix it (and add an analyzer).

**Comment by Youssef1313** [comment]
There is already IDE0044 for that.

**Comment by Evangelink** [comment]
I forgot about it. That's weird because the issue is turned on but not raised on my VS (is it on yours?), it's caught by a different analyzer.

**Comment by mavasani** [comment]
IDE0044 only works for private fields, not internal ones.

**Comment by mavasani** [comment]
@Evangelink These should be converted to `private static readonly` fields

**Comment by Youssef1313** [comment]
@mavasani Probably this is no longer relevant with changes from #5406 (we no longer have these fields)?

**Comment by Evangelink** [comment]
You are right @Youssef1313. I am closing the ticket.

**Comment by Youssef1313** [comment]
@Evangelink Sorry I was wrong :smile:

#5406 eliminated the LocalizableString fields, not the DiagnosticDescriptor fields. Found this while creating https://github.com/dotnet/roslyn-analyzers/pull/5734
