### ISSUE TITLE
false positive for CA1801 for "args" in top level statements

### ISSUE THREAD

**Issue by adamralph** [dotnet/roslyn-analyzers#5184]
### Analyzer

**Diagnostic ID**: [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801): `Review unused parameters`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.302](https://dotnet.microsoft.com/download/dotnet/5.0)

Note: I was [informed](https://github.com/dotnet/roslyn-analyzers/pull/4066#issuecomment-870757087) by @jmarolf that SDK 5.0.301 should have the bug fix for https://github.com/dotnet/roslyn-analyzers/pull/4066 so I did not investigate whether latest NuGet package has this bug.

### Describe the bug

The diagnostic is reported for the implicit `args` parameter for top level statements.

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Clone https://github.com/adamralph/dotnet-roslyn-analyzers-4066
2. Build the solution

### Expected behavior

CA1801 is not reported.

### Actual behavior

[CA1801 is reported.](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/3059177109?check_suite_focus=true#step:5:11)

## Additional context

The problem is shown [here](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/3059177109?check_suite_focus=true#step:5:11) when [using SDK 5.0.302](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/3059177109?check_suite_focus=true#step:4:7).

The problem is shown [here](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/2922284878?check_suite_focus=true#step:5:11) when [using SDK 5.0.301](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/2922284878?check_suite_focus=true#step:4:7).

**Comment by Youssef1313** [comment]
@adamralph Can you try the latest prelease from [dotnet6 feed](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet)?

**Comment by adamralph** [comment]
@Youssef1313 sure, I'll give it a try. That doesn't explicitly answer my question but given the version you linked to is `6.0.0-rc1.21356.1` I assume this will be included in SDK 6.

**Comment by Youssef1313** [comment]
@adamralph The compiler was using `$Main` at first for the synthesized entry point, which at a later point was changed to `<Main>$`. The PR you're mentioning doesn't handle the newer name, which was handled in https://github.com/dotnet/roslyn-analyzers/pull/4256.

The reason I suggested using the prerelease is that they're more frequent, and it mostly will indicate if the bug still exists or not.

In case you're still seeing the issue with the prerelease, then the bug still exists and will need investigation. Otherwise, you need to wait until the fix flows into .NET 5 SDK

@jmarolf for which version of the .NET 5 SDK includes the fix from #4256.

**Comment by adamralph** [comment]
@Youssef1313 I tried testing Microsoft.CodeAnalysis.NetAnalyzers 6.0.0-rc1.21362.2 from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet but I'm afraid I didn't get very far. I can't get the package to report _any_ diagnostics at all, so I think I'm doing something wrong.

If you know how to do it, then please feel free to try it on https://github.com/adamralph/dotnet-roslyn-analyzers-4066

**Comment by Youssef1313** [comment]
@adamralph You don't seem to be using this version currently in the repo (your last commit is 17 days ago actually). Did you make changes locally but forgot to push them?

**Comment by adamralph** [comment]
@Youssef1313 I didn't push anything because I didn't know if I was on the right track. There are a few things I'm unsure about, e.g.:

- How do I ensure that the analyzers in the installed package are used instead of those built into the SDK?
- Do I have to remove the [`AnalysisMode` attribute](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/blob/a24f0dc60fd11ea31414c9d77f230fefbc01e2f5/dotnet-roslyn-analyzers-4066.csproj#L4)?
  - AFAIK that enables the analyzers built into the SDK. Does it affect the analyzers in the package in any way?
- Do I have to change the [TFM](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/blob/main/dotnet-roslyn-analyzers-4066.csproj#L7)?
- Do I have to change the [SDK version](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/blob/main/global.json#L3)?

**Comment by adamralph** [comment]
FWIW I've confirmed that [the problem still exists](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/3059177109?check_suite_focus=true#step:5:11) in [SDK 5.0.302](https://github.com/adamralph/dotnet-roslyn-analyzers-4066/runs/3059177109?check_suite_focus=true#step:4:7).

**Comment by Youssef1313** [comment]
@adamralph Can you check with https://github.com/adamralph/dotnet-roslyn-analyzers-4066/pull/1?

**Comment by Youssef1313** [comment]
@jmarolf Can you help here which .NET 5 SDK version contains or will contain #4256 (the rule was deleted in .NET 6 - so the ask is specifically for .NET 5).

**Comment by adamralph** [comment]
As per https://github.com/adamralph/dotnet-roslyn-analyzers-4066/pull/1#issuecomment-879301319, we figured out that this issue is irrelevant for .NET 6 since CA1801 has been removed from that version.

This is still a problem for .NET 5, but TBH I'm not really too bothered, since I know that .NET 6 will not have the problem.

**Comment by mavasani** [comment]
Closing based on last comment
