### ISSUE TITLE
Configure severity of security related rules by category

### ISSUE THREAD

**Issue by yifanbian-msft** [dotnet/roslyn-analyzers#5189]
Hi, we would like to enable all security related rules in our projects, but I found that `dotnet_analyzer_diagnostic.category-Security.severity = error` doesn't work. After digging into .NET Analyzer source code, I found that [`RuleLevel.Disabled` documentation states that these rules can't be enabled using the category based bulk configuration](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/RuleLevel.cs#L42).
Could you help me on understanding this design, or make it bulk-configurable? Thanks.

**Comment by Youssef1313** [comment]
Related to: https://github.com/dotnet/roslyn/issues/47046

**Comment by eatdrinksleepcode** [comment]
Same issue for e.g. CA2000 in Reliability.

**Comment by mavasani** [comment]
You should be able to do this via the new category specific bulk configuration MSBuild property in .NET6, documentation being added in https://github.com/dotnet/docs/pull/25562

```xml
  <AnalysisLevelSecurity>latest-all</AnalysisLevelSecurity>
```
