### ISSUE TITLE
New rule for private field names requiring an underscore

### ISSUE THREAD

**Issue by DrGriff** [dotnet/roslyn-analyzers#5191]
### Describe the problem you are trying to solve
From [C# Coding Style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md) it states that:

> 3. We use `_camelCase` for internal and private fields and use `readonly` where possible. Prefix internal and private instance fields with `_`, static fields with `s_` and thread static fields with `t_`. When used on static fields, `readonly` should come after `static` (*e.g.* `static readonly` not `readonly static`). Public fields should be used sparingly and should use PascalCasing with no prefix when used.

I'm not seeing a rule that requires private fields to be prefixed with an underscore. 

### Describe suggestions on how to achieve the rule
So the rule should find all private/internal fields that don't start with an underscore (+ camelCased maybe too?) name and flag them.  Ideally have a helper that will fix this instance, all instances in this document/project/solution.

There is an existing rule [https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1707](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1707) which might conflict - not sure.

**Comment by Youssef1313** [comment]
I think this can be done with [naming rules](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules).

See for example:

https://github.com/dotnet/runtime/blob/184a5b103ca9fec1e7e7e0d3a411a6d15f1bb867/.editorconfig#L65-L82

**Comment by DrGriff** [comment]
> I think this can be done with [naming rules](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules).
> 
> See for example:
> 
> https://github.com/dotnet/runtime/blob/184a5b103ca9fec1e7e7e0d3a411a6d15f1bb867/.editorconfig#L65-L82

Worked like a dream - thank you so much!

**Comment by DrGriff** [comment]
FYI - also had to add
># IDE1006: Naming Styles
dotnet_diagnostic.IDE1006.severity = none

It was showing as `Disabled` but still coming as a Warning (which I promote to Error).
