### ISSUE TITLE
CA1840 error link broken

### ISSUE THREAD

**Issue by allisonchou** [dotnet/roslyn-analyzers#5197]
CA1840 links to [this webpage](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1840), which is broken, so I cannot find more information out about the diagnostic. The screenshot below is from working in the [aspnetcore-tooling](https://github.com/dotnet/aspnetcore-tooling) repository in VS2022.

![image](https://user-images.githubusercontent.com/16968319/124206960-3fca3500-da99-11eb-8009-157767195197.png)

**Comment by mavasani** [comment]
@stephentoub @carlossanlop @buyaa-n

**Comment by Youssef1313** [comment]
Tracked by https://github.com/dotnet/docs/issues/23900.

**Comment by stephentoub** [comment]
The link is now working.
