### ISSUE TITLE
Migrate analyzer samples to roslyn-analyzers

### ISSUE THREAD

**Issue by tmeschter** [dotnet/roslyn-analyzers#52]
This includes moving projects under the following paths in the [dotnet/roslyn](http://github.com/dotnet/roslyn/) repo:
* src\Samples\CSharp\Analyzers
* src\Samples\VisualBasic\Analyzers

**Comment by srivatsn** [comment]
The analyzer samples should stay together with the other samples wherever they end up. Currently there are in the roslyn repo along with the other docs. We could move all the samples elsewhere but it would be odd to move just those samples here.
