### ISSUE TITLE
Are .analyzerconfig supported targeting .netstandard 2.1?

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/roslyn-analyzers#5200]
### Analyzer
Microsoft.CodeAnalysis.NetAnalyzers

SDK: 3.1.410 

Version: 5.0.3 (Latest)

### Describe the bug
We have a library that supports .net5 and .netstandard2.1, "dotnet build" with the SDK 5.0.301 runs correctly, but using the SDK  3.1.410 the rules in analyzerconfig are ignored

### Expected behavior
configuration in analyzerconfig is respected
### Actual behavior
configuration in analyzerconfig is ignored

**Comment by mavasani** [comment]
Can you please more details? Which rules are you talking about? Did you mean .editorconfig instead of .analyzerconfig? A repro project would be helpful

**Comment by Youssef1313** [comment]
@JuanZamudioGBM Can you please provide more info?
