### ISSUE TITLE
CA1416 does not recognise built-in guards for macOS-specific types

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/roslyn-analyzers#5205]
### Analyzer

**Diagnostic ID**: [CA1416](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416): `Validate platform compatibility`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: SDK 6.0.100-preview.5.21302.13 (included in VS2022 Preview 1)

### Describe the bug

CA1416 triggers when I try to use a type annotated as supporting `"osx"` or `"macos"`, when I guard the calls with `RuntimeInformation.IsOSPlatform(OSPlatforms.OSX)`.

### Steps To Reproduce

Compile the following code example:

```csharp
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace DemoSupportedPlatformLib
{
    public abstract class PlatformSpecificFunction
    {
        public static PlatformSpecificFunction GetProvider()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return new WindowsSpecificFunction();
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                return new OSXSpecificFunction();
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                return new LinuxSpecificFunction();
            }
            else
            {
                return new DefaultFunction();
            }
        }
    }

    [SupportedOSPlatform("windows")]
    class WindowsSpecificFunction : PlatformSpecificFunction
    {
    }

    [SupportedOSPlatform("macos")]
    class OSXSpecificFunction : PlatformSpecificFunction
    {
    }

    [SupportedOSPlatform("linux")]
    class LinuxSpecificFunction : PlatformSpecificFunction
    {
    }

    class DefaultFunction : PlatformSpecificFunction
    {
    }
}
```

### Expected behavior

No build warnings or errors.

### Actual behavior

> warning CA1416: This call site is reachable on: 'OSX'. 'OSXSpecificFunction' is only supported on: 'macOS/OSX'.

**Comment by Youssef1313** [comment]
cc @buyaa-n

**Comment by buyaa-n** [comment]
@yaakov-h thank you for reporting the bug, we will fix it, meanwhile please use `RuntimeInformation.IsOSPlatform(OSPlatform.Create("macos"))` as a workaround

**Comment by buyaa-n** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/5495
