### ISSUE TITLE
Port FxCop rule CA2147: SecurityTransparentCodeShouldNotAssert

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#524]
**Title:** Transparent methods may not use security asserts

**Description:**

This rule analyzes all methods and types in an assembly that is either 100 percent?transparent or mixed transparent/critical, and flags any declarative or imperative use of Assert.

**Proposed analyzer:** System.Runtime

**Notes:**

**Comment by srivatsn** [comment]
Dupe of #629
