### ISSUE TITLE
Port FxCop rule CA2202: DoNotDisposeObjectsMultipleTimes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#528]
**Title:** Do not dispose objects multiple times

**Description:**

A method implementation contains code paths that could cause multiple calls to System.IDisposable.Dispose or a Dispose equivalent (such as a Close() method on some types) on the same object.

**Dependency:** Dataflow

**Notes:**

**Comment by LMLB** [comment]
Please look at this: http://blogs.msdn.com/b/tilovell/archive/2014/02/12/the-worst-code-analysis-rule-that-s-recommended-ca2202.aspx

**Comment by lgolding** [comment]
Thank you @LMLB. We will take a look.

**Comment by lgolding** [comment]
@LMLB  You'll be happy know we've cut this!

**Comment by LMLB** [comment]
Thank you!

**Comment by mavasani** [comment]
We are going to implement this.

**Comment by mavasani** [comment]
Lets put this rule port on hold given the negative feedback on the rule above and the fact that implementing it needs path sensitive flow analysis (which is not yet implemented in the features/dataflow branch). We will reconsider this if we get customer requests.
