### ISSUE TITLE
Bug 4845 does not appear to be fixed in any publicly released nuget package.

### ISSUE THREAD

**Issue by groogiam** [dotnet/roslyn-analyzers#5280]
### Analyzer

**Diagnostic ID**: [CA2013](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

Microsoft.CodeAnalysis.Analyzers version 3.3.2

### Steps To Reproduce

Please see the https://github.com/dotnet/roslyn-analyzers/issues/4845

This bug was closed referencing that it was fixed 3.3.3-beta.xxx

However there does not appear to be any non preview package released on Nuget with the fix. This will manifest for anyone referencing Microsoft.CodeAnalysis.Common 3.10.0

**Comment by Youssef1313** [comment]
@mavasani @jmarolf When will 3.3.3 be released on NuGet?

**Comment by groogiam** [comment]
@Youssef1313 @mavasani @jmarolf Any update on when this will be released. Thanks.

**Comment by jmarolf** [comment]
Thanks for the ping. I'll see if we can get the 3.3.3 packages out

**Comment by Youssef1313** [comment]
Closing as 3.3.3 is already released and there is no action needed here.


> Will it also be possible to add a tag, release, and perhaps a short summary of what 3.3.3 contains

https://github.com/dotnet/roslyn-analyzers/issues/5926
