### ISSUE TITLE
DoNotUseInsecureDtdProcessingAnalyzer is using one bar OR

### ISSUE THREAD

**Issue by Evangelink** [dotnet/roslyn-analyzers#5313]
I have noticed that there are a couple of places in `DoNotUseInsecureDtdProcessing` where we use the one bar or `|` (not sure what's the official name). Which forces the evaluation of both sides, I am wondering if there is any specific thing forcing this behavior?

Here are the examples:
- https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs#L203
- https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs#L212
- https://github.com/dotnet/roslyn-analyzers/blob/main/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs#L213

Ping @dotpaul

**Comment by dotpaul** [comment]
Hrm, I don't think there's any reason for using only one `|`. Feel free to change to `||`.

**Comment by Youssef1313** [comment]
Fixed in https://github.com/dotnet/roslyn-analyzers/pull/5317
