### ISSUE TITLE
Port FxCop rule CA2211: NonConstantFieldsShouldNotBeVisible

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#533]
**Title:** Non-constant fields should not be visible

**Description:**

Static fields that are neither constants nor read-only are not thread-safe. Access to such a field must be carefully controlled and requires advanced programming techniques to synchronize access to the class object.

**Dependency:** None

**Notes:**

**Comment by twsouthwick** [comment]
I'll take this one

**Comment by lgolding** [comment]
Assigned to me, but work will be done by @twsouthwick.

**Comment by srivatsn** [comment]
The right fix is to convert the field to a property and invoking the lightbulb on a field will bring up the "Encapsulate field" refactoring. So no fixer has been implemented for this rule and the stubs have been deleted.
