### ISSUE TITLE
New rule for "is not null" similar to IDE0041

### ISSUE THREAD

**Issue by stap123** [dotnet/roslyn-analyzers#5337]
Are there plans to have a similar code style rule/analyser for the not null version of the syntax with pattern matching? 

This would essentially be the same as the `is null` rule with IDE0041 but for `is not null`.

**Comment by Youssef1313** [comment]
@jinujoseph or @mavasani to move to dotnet/roslyn

**Comment by carlossanlop** [comment]
Thanks for your suggestion, @stap123. Please share your thoughts on this in the [dotnet/runtime issue](https://github.com/dotnet/runtime/issues/57961). We propose new analyzers there.

**Comment by carlossanlop** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/57961
