### ISSUE TITLE
Port FxCop rule CA2215: DisposeMethodsShouldCallBaseClassDispose

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#535]
**Title:** Dispose Methods Should Call Base Class Dispose

**Description:**

If a type inherits from a disposable type, it must call the Dispose method of the base type from its own Dispose method.

**Dependency:** Dataflow

**Notes:**

**Comment by mavasani** [comment]
We have decided to implement an initial version of this rule without DFA. https://github.com/dotnet/roslyn-analyzers/issues/1654 tracks enhancing it with DFA.
