### ISSUE TITLE
Improve CA2017 to detect bool[]

### ISSUE THREAD

**Issue by pgovind** [dotnet/roslyn-analyzers#5353]
https://github.com/dotnet/roslyn-analyzers/pull/5242/files implements CA2017 to tag calls to `Buffer.BlockCopy` with a warning about the last `count` parameter. Currently the analyzer excludes `Buffer.BlockCopy` calls that pass in `byte[]` or `sbyte[]` as the source and destination parameters because `count` makes sense for these calls. Source and destination parameters of type `bool[]` must also be excluded from this check.

cc @mahdiva @jeffhandley @buyaa-n

**Comment by Evangelink** [comment]
@pgovind Could you confirm this issue was fixed by the related PR? (trying to confirm that the ticket can be closed).

**Comment by buyaa-n** [comment]
Yes this is fixed with https://github.com/dotnet/roslyn-analyzers/pull/5373
