### ISSUE TITLE
Global analyzer config files in Microsoft.CodeAnalysis.NetAnalyzers aren't applied on Unix because of caps issue

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/roslyn-analyzers#5360]
The global analyzer config files aren't added to the `EditorConfigFiles` msbuild item because the file name doesn't exist on Unix platforms. That's because [this line](https://github.com/dotnet/roslyn-analyzers/blob/d0663cca11722045b9aeabb5d0d5335042084e13/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs#L1390) adds the mode without a `ToLowerInvariant` operation: `$(_GlobalAnalyzerConfigAnalysisMode_{trimmedPackageName})`.

The mode portion in the generated config files which are part of the package are all lowercase, i.e.: `AnalysisLevelDesign_5_default.editorconfig` but the msbuild `Exists` task checks for `...\AnalysisLevelDesign_5_Default.editorconfig`.

Link to the package: https://nuget.info/packages/Microsoft.CodeAnalysis.NetAnalyzers/5.0.3. Look into the "build/config" folder to find the generated editorconfig files.

cc @danmoseley @stephentoub

**Comment by Youssef1313** [comment]
The parallel file in dotnet/roslyn https://github.com/dotnet/roslyn/blob/main/src/CodeStyle/Tools/Program.cs should also be checked in case it has a similar issue.

**Comment by ViktorHofer** [comment]
Yes, it has the exact same issue: https://github.com/dotnet/roslyn/blob/06495a2bf3813e13cff59d2cdf30c24c99966d8e/src/CodeStyle/Tools/Program.cs#L237

**Comment by ViktorHofer** [comment]
cc @sharwell as this is a pretty bad bug. I.e. in dotnet/runtime only on Windows these via the nuget package delivered editorconfig files get applied.

**Comment by ViktorHofer** [comment]
cc @sharwell @jaredpar as it looks like the bug still exists in the product.

**Comment by uweigand** [comment]
Looks like this is still not correct, and in particular is causing this problem: https://github.com/dotnet/source-build/issues/2483

Apparently the file name that is being accessed is now *completely* lowercased, e.g. `analysislevel_6_default.editorconfig` (that's what I see with strace), but the file on disk is called `AnalysisLevel_6_default.editorconfig`.   This causes the file to be not found and the settings to be ignored.
