### ISSUE TITLE
Port FxCop rule CA2219: DoNotRaiseExceptionsInExceptionClauses

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#537]
**Title:** Do not raise exceptions in exception clauses

**Description:**

When an exception is raised in a finally or fault clause, the new exception hides the active exception. When an exception is raised in a filter clause, the run time silently catches the exception. This makes the original error difficult to detect and debug.

**Dependency:** None

**Notes:**

**Comment by genlu** [comment]
This one would benefit from an `IOperation` walker type, suggest to wait until it is created

**Comment by srivatsn** [comment]
Analyzer implemented by #907. There's no good fix that we can offer here. Just removing the throw is probably not correct and instead the error needs to be handled differently.
