### ISSUE TITLE
CA1508 dead code: false positive when checking an expression a second time

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#5378]
[This code](
https://github.com/aarnott/pclcommandbase/blob/91f346e07eb627a75f7f4f188afd4eb11721261b/test/PCLCommandBase.Tests/CommandBaseTests.cs#L154-L154) produces CA1508 (dead code) when not suppressed.

**Version Used**: VS 16.11 Preview 4 (31605.320.d16.11)

**Steps to Reproduce**:

```
git clone https://github.com/aarnott/pclcommandbase
cd pclcommandbase
git checkout 91f346e07eb627a75f7f4f188afd4eb11721261b
pclcommandbase.sln
```

**Expected Behavior**:

No warnings

**Actual Behavior**:

> Warning	CA1508	'(await eventsQueue.DequeueAsync(this.TimeoutToken)).PropertyName != nameof(this.command.IsExecuting)' is always 'false'. Remove or refactor the condition(s) to avoid dead code.	PCLCommandBase.Tests (net472)	D:\git\pclcommandbase\test\PCLCommandBase.Tests\CommandBaseTests.cs

I haven't been able to reproduce it in a simpler case.

**Comment by mavasani** [comment]
Verified this repros on .NET 7 SDK, but does not repro in the latest .NET 8 preview SDK.
