### ISSUE TITLE
Port FxCop rule CA2220: FinalizersShouldCallBaseClassFinalizer

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#538]
**Title:** Finalizers should call base class finalizer

**Description:**

Finalization must be propagated through the inheritance hierarchy. To guarantee this, types must call their base class Finalize method in their own Finalize method.

**Proposed analyzer:** System.Runtime

**Notes:**

The compiler automatically chains to the base class. @nguerrera: Does the VB compiler do that?>

**Comment by nguerrera** [comment]
The VB compiler does not do this, but I still think this rule has limited value because if you follow all of the other guidelines you won't hit it. The base should have overridable Dispose(bool) and only that should ever be overridden.
