### ISSUE TITLE
AnalysisMode flag is not being honored when using the Microsoft.CodeAnalysis.NetAnalyzers NuGet package

### ISSUE THREAD

**Issue by DavidZidar** [dotnet/roslyn-analyzers#5388]
### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.3 (Latest)

### Describe the bug

The conditions in the `Microsoft.CodeAnalysis.NetAnalyzers.targets` file will only set the relevant properties if the `Design` properties are already prepopulated.

Take the first condition for the target `AddGlobalAnalyzerConfigForPackage_MicrosoftCodeAnalysisNetAnalyzersDesign`:
```
'$(SkipGlobalAnalyzerConfigForPackage)' != 'true' and ('$(AnalysisLevelDesign)' != '' or '$(AnalysisModeDesign)' != '')
```

This target will only run and set it's properties if `AnalysisLevelDesign` or `AnalysisModeDesign` is non empty.

I have worked around this issue by adding the following lines to my csproj file, but as I understand it this should not be necessary.
```xml
<AnalysisModeDesign>$(AnalysisMode)</AnalysisModeDesign>
<AnalysisModeDocumentation>$(AnalysisMode)</AnalysisModeDocumentation>
<AnalysisModeGlobalization>$(AnalysisMode)</AnalysisModeGlobalization>
<AnalysisModeInteroperability>$(AnalysisMode)</AnalysisModeInteroperability>
<AnalysisModeMaintainability>$(AnalysisMode)</AnalysisModeMaintainability>
<AnalysisModeNaming>$(AnalysisMode)</AnalysisModeNaming>
<AnalysisModePerformance>$(AnalysisMode)</AnalysisModePerformance>
<AnalysisModePublish>$(AnalysisMode)</AnalysisModePublish>
<AnalysisModeReliability>$(AnalysisMode)</AnalysisModeReliability>
<AnalysisModeSecurity>$(AnalysisMode)</AnalysisModeSecurity>
<AnalysisModeUsage>$(AnalysisMode)</AnalysisModeUsage>
```

### Steps To Reproduce

1. Install NuGet package in an old non SDK-style .NET Framework project
2. Set `AnalysisMode` to `AllEnabledByDefault`

### Expected behavior

Most analyzers should be enabled.

### Actual behavior

Nearly all analyzers are disbled.

**Comment by jmarolf** [comment]
> Install NuGet package in an old non SDK-style .NET Framework project

yep this is by design. The intent was never that these worked in non SDK-style projects.

**Comment by DavidZidar** [comment]
@jmarolf That is extremely surprising. The FxCopAnalyzers package is deprecated and [the documentation](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview) makes no mention of this not being supported on non SDK-style projects. In fact, the documentation even says that it is supposed to work.

> If you don't want to move to the .NET 5+ SDK, **have a non-SDK-style .NET Framework project**, or prefer a NuGet package-based model, the analyzers are also available in the Microsoft.CodeAnalysis.NetAnalyzers NuGet package.
