### ISSUE TITLE
Add analyzers for Microsoft.IdentityModel.Tokens (Wilson) Security Issues

### ISSUE THREAD

**Issue by TimHannMSFT** [dotnet/roslyn-analyzers#5419]
### Describe the problem you are trying to solve

An open source MSFT produced library (Microsoft.IdentityModel.Tokens (Wilson)) has some best practices we'd like to enforce with analyzers. I've been working with @dotpaul, and he suggested adding it to the roslyn-analyzers repo directly (specifically 2.9.x)

### Describe suggestions on how to achieve the rule

Add analyzers for Microsoft.IdentityModel.Tokens (Wilson) Security Issues

    Ensure key validation isn't explicitly disabled by setting the relevant setter on the validation object to false:
    * RequireExpirationTime
    * ValidateAudience
    * ValidateIssuer
    * ValidateLifetime

    Ensure key validation isn't implicitly disabled by having the relevant delegate always return true:
    * AudienceValidator
    * LifetimeValidator

    NOTE: There's another key implicit case for IssuerValidator, however the logic there is more complex and would require Data Flow Analysis (DFA). Since DFA has a different performance profile anyways, shipping these analyzers first which can be accomplished via static analysis. We also have CodeQL work in the pipe separately from this to address more complicated DFA flows.

**Comment by dotpaul** [comment]
FWIW, sounds good to me

**Comment by mavasani** [comment]
This was merged into 2.9.x
