### ISSUE TITLE
Port FxCop rule CA2231: OverloadOperatorEqualsOnOverridingValueTypeEquals

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#544]
**Title:** Overload operator equals on overriding value type Equals

**Description:**

In most programming languages there is no default implementation of the equality operator (==) for value types. If your programming language supports operator overloads, you should consider implementing the equality operator. Its behavior should be identical to that of Equals

**Dependency:** None

**Notes:**

**Comment by twsouthwick** [comment]
I'll take a look at this one

**Comment by lgolding** [comment]
Assigned to me, but work will be done by @twsouthwick

**Comment by srivatsn** [comment]
@twsouthwick - looks like this rule has already been [implemented](https://github.com/dotnet/roslyn-analyzers/blob/805488ca77226b7cbc360e7b5a8019635b332274/src/Microsoft.ApiDesignGuidelines.Analyzers/Core/OverloadOperatorEqualsOnOverridingValueTypeEquals.cs) and that we've created this issue by mistake. Sorry about that. There are other rules that are similar to this one that haven't been implemented that you could look at.

**Comment by twsouthwick** [comment]
Ok - I'll find another one :)

**Comment by srivatsn** [comment]
Closing this issue since the rule's already been implemented.
