### ISSUE TITLE
CA1829:Use Length/Count property instead of Count() when available false positive

### ISSUE THREAD

**Issue by stap123** [dotnet/roslyn-analyzers#5449]
**Diagnostic ID**: [CA1829](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1829)

This rule shows as a warning when `Count()` is used inside an EF Core queries `.Select` block. But if you apply the fix and use the `Count` property the query then breaks.

Is there some way to stop this happening because currently this rule suggesting that I break my app?

**Comment by mavasani** [comment]
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5299
