### ISSUE TITLE
Separate CA1704 for single letter identifiers

### ISSUE THREAD

**Issue by FreeAndNil** [dotnet/roslyn-analyzers#5473]
### Analyzer

**Diagnostic ID**: [CA1704](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1704)

### Describe the improvement

The current implementation of #443 (#1111) also checks for single-letter identifiers.
This check should be separated in an own diagnostic ID so that people can decide whether the want warnings for those cases or not.

### Describe suggestions on how to achieve the rule

The existing analyzer will provide a new diagnostic ID for those cases.

### Additional context

See discussion at the end of #1111 with @pakdev & @mavasani

**Comment by Youssef1313** [comment]
Duplicate of #5183
