### ISSUE TITLE
Port FxCop rule CA2236: CallBaseClassMethodsOnISerializableTypes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#548]
**Title:** Call base class methods on ISerializable types

**Description:**

To fix a violation of this rule, call the base type GetObjectData method or serialization constructor from the corresponding derived type method or constructor.

**Dependency:** IOperation

**Notes:**

**Comment by jeffhandley** [comment]
This rule will not be ported since we are on a path toward having BinaryFormatter fully deprecated and removed from .NET.
See also: [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md)
