### ISSUE TITLE
Port FxCop rule CA2238: ImplementSerializationMethodsCorrectly

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#549]
**Title:** Implement serialization methods correctly

**Description:**

A method that handles a serialization event does not have the correct signature, return type, or visibility.

**Dependency:** None

**Notes:**

**Comment by jeffhandley** [comment]
This rule will not be ported since we are on a path toward having BinaryFormatter fully deprecated and removed from .NET.
See also: [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md)
