### ISSUE TITLE
Port FxCop rule CA2239: ProvideDeserializationMethodsForOptionalFields

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#550]
**Title:** Provide deserialization methods for optional fields

**Description:**

A type has a field that is marked by using the System.Runtime.Serialization.OptionalFieldAttribute attribute, and the type does not provide deserialization event handling methods.

**Dependency:** None

**Notes:**

**Comment by jeffhandley** [comment]
This rule will not be ported since we are on a path toward having BinaryFormatter fully deprecated and removed from .NET.
See also: [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md)
