### ISSUE TITLE
Port FxCop rule CA2240: ImplementISerializableCorrectly

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#551]
**Title:** Implement ISerializable correctly

**Description:**

To fix a violation of this rule, make the GetObjectData method visible and overridable, and make sure that all instance fields are included in the serialization process or explicitly marked by using the NonSerializedAttribute attribute.

**Dependency:** None

**Notes:**

**Comment by jeffhandley** [comment]
This rule will not be ported since we are on a path toward having BinaryFormatter fully deprecated and removed from .NET.
See also: [BinaryFormatter Obsoletion Strategy](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md)
