### ISSUE TITLE
Code Analysis does not respect <AnalysisMode>AllEnabledByDefault</AnalysisMode>

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/roslyn-analyzers#5516]
https://github.com/SteveDunn/ca-bug

Above is a repo to demonstrate what I think is a bug in the latest 6.0 SDKs with Code Analysis. The project targets net5.0 and has the 'opt-out' setting for code analysis (<AnalysisMode>AllEnabledByDefault</AnalysisMode>)

If built with a 6.0 SDK, there are no code analysis errors produced with dotnet build

BUT... If locked to a 5.0 SDK with a global.json, then code analysis errors are produced.

To reproduce, run dotnet build on this repo and observe errors. Then delete global.json to force it to use a 6.0 SDK, and rebuild and observe no code analysis results.

@jaredpar has reproduced

**Comment by jmarolf** [comment]
@mavasani it appears we are not generating the correct editorconfig files for all the different analysis levels. I do not really understanding how all of this is intended to work [here](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs). I do no think we have any tests for this but I may be missing something?

**Comment by mavasani** [comment]
@jmarolf Thanks, I'll investigate.

**Comment by mavasani** [comment]
@jmarolf I just build `Microsoft.CodeAnalysis.NetAnalyzers.nupkg` locally from `release/6.0.1xx` branch and that seems to work fine and all AnalysisModes are respected. I believe [this](https://github.com/dotnet/roslyn-analyzers/commit/951dc4657155b7bce63738117727ea8161917fb3#diff-bbd965856c65adbd362b6c714d543a9dbdd1aa0939f6a00a85ca32dca27dfab6) change ensure we generate `AnalysisLevel_6_*.editorconfig` files within the `build\config` folder in the NuGet package. Prior to this change, we only generated `AnalysisLevel_5_*.editorconfig` files in that folder, so things were not working as expected. Has your above change been inserted into the .NET 6 SDK? If so, I expect things to work.

**Comment by mavasani** [comment]
Ah, I just checked that your change that adds the new .NET 6 release rules table to `AnalyzerReleases.Shipped.md` is **not present** in [release/6.0.1xx-rc1](https://github.com/dotnet/roslyn-analyzers/blob/release/6.0.1xx-rc1/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md), but **is present** in [release/6.0.1xx-rc2](https://github.com/dotnet/roslyn-analyzers/blob/release/6.0.1xx-rc2/src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md). I expect things to work fine in .NET 6.0 RC2 and later.
