### ISSUE TITLE
Port FxCop rule CA2241: ProvideCorrectArgumentsToFormattingMethods

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#552]
**Title:** Provide correct arguments to formatting methods

**Description:**

The format argument that is passed to System.String.Format does not contain a format item that corresponds to each object argument, or vice versa.

**Dependency:** Dataflow

**Notes:**

**Comment by srivatsn** [comment]
Implemented by https://github.com/dotnet/roslyn-analyzers/pull/752
