### ISSUE TITLE
Port FxCop rule CA2242: TestForNaNCorrectly

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#553]
**Title:** Test for NaN correctly

**Description:**

This expression tests a value against Single.Nan or Double.Nan. Use Single.IsNan(Single) or Double.IsNan(Double) to test the value.

**Dependency:** IOperation

**Notes:**

**Comment by dpoeschl** [comment]
This is blocked due to an issue that I just spoke with @JohnHamby about.

**Comment by dpoeschl** [comment]
Assigning to @JohnHamby for triage / further processing.

**Comment by srivatsn** [comment]
Clearing the Blocked field since we've updated to a new drop now.

**Comment by lgolding** [comment]
Analyzer is done. Added Needs-Fixer label.
