### ISSUE TITLE
Implement automation rule "Label community pull requests"

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#5565]
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/1408396/135517746-56ca3a6d-4df9-4dcc-a711-03880984f0b5.png)

**Comment by sharwell** [comment]
@Evangelink this rule should now be working. Can you submit a new PR to this repository as a test?

**Comment by Youssef1313** [comment]
@sharwell It's working 🎉 

https://github.com/dotnet/roslyn-analyzers/pull/5584
