### ISSUE TITLE
Port FxCop rule CA3061: DoNotAddStringsToXmlSchema

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#564]
**Title:** Do not add strings to Xml schema

**Description:**

Do not use unsafe overloads of System.Xml.Schema.XmlSchemaCollection.Add. This API internally enables DTD processing on the XML reader instance used, and uses UrlResolver for resolving external XML entities. The outcome is information disclosure. Content from file system or network shares for the machine processing the XML can be exposed to attacker. In addition, an attacker can use this as a DoS vector.

**Proposed analyzer:** System.Xml

**Notes:**

These will be consolidated into two or three new rules

**Comment by xtqqczze** [comment]
This was added in https://github.com/dotnet/roslyn-analyzers/pull/2223, label `Resolution-Won't Fix` can be removed.
