### ISSUE TITLE
Microsoft.CodeAnalysis.Metrics has wrong license on NuGet.org

### ISSUE THREAD

**Issue by jaredpar** [dotnet/roslyn-analyzers#5653]
The LICENSE for this repository is listed as MIT yet the listed license for Microsoft.CodeAnalysis.Metrics on nuget.org is Apache. Possible this is a hold over from before the switch but seems like an item to correct. 

![image](https://user-images.githubusercontent.com/146967/137805995-66a7deee-819a-481b-aeb7-3daacf0d48c5.png)

**Comment by Evangelink** [comment]
@jaredpar It seems that this was fixed.

![image](https://user-images.githubusercontent.com/11340282/142728898-0095fee8-9b34-499a-9e29-ca16baf56c88.png)

**Comment by jaredpar** [comment]
@mavasani ?

**Comment by mavasani** [comment]
Yes, should be good to close this issue.
