### ISSUE TITLE
CA2254 appears when using a string from *.resx file

### ISSUE THREAD

**Issue by arthuredgarov** [dotnet/roslyn-analyzers#5661]
### Analyzer

**Diagnostic ID**: [CA2254](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2254): `Template should be a static expression`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 6 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.100-rc.2.21505.57](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug

Analyzer reports the message when using a string from the `*.resx` file.

### Steps To Reproduce

1. Create a class library project using the mentioned .NET SDK version.
2. Add `Microsoft.Extensions.Logging` NuGet package.
3. Add `*.resx` file and put there any format string, for example `"Log message: {0}"`.
4. Declare the `ILogger` variable in the C# class and use it to call the `ILogger.LogError` method (or any other) with any parameters and previously created format string from the `*.resx` file.

### Expected behavior

The analyzer message does not appear when using a format string from `*.resx` file.

### Actual behavior

The analyzer message appears when using a format string from `*.resx` file.

**Comment by SteveDesmond-ca** [comment]
Duplicate of #5626 ?

**Comment by arthuredgarov** [comment]
@SteveDesmond-ca Yes, thanks.
