### ISSUE TITLE
Flag source generator I/O

### ISSUE THREAD

**Issue by chsienki** [dotnet/roslyn-analyzers#5669]
### Describe the problem you are trying to solve

We know that potentially bad-things™ happen when generators perform I/O, so we should flag any generators that do so.

### Describe suggestions on how to achieve the rule

We'll look for obvious uses of `File.Write` etc. from within any class marked with `[Generator]`. 

### Additional context

We won't be able to get all instances, but it should be enough to dissuade authors from doing so, along with a link to more info to explain why they shouldn't.

**Comment by AraHaan** [comment]
Ok, what if they Process.Start a program (like git) to retrieve information (where git does I/O to look at stuff like commit information)? Would that be considered I/O for an analyzer/source generator?

**Comment by Youssef1313** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/6115
