### ISSUE TITLE
Port FxCop rule CA3064: UseXmlReaderForDataSetReadXmlSchema

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#567]
**Title:** Use XmlReader for DataSet ReadXmlSchema

**Description:**

Do not use unsafe overloads of System.Data.DataSet.ReadXmlSchema. This API internally enables DTD processing on the XML reader instance used, and uses UrlResolver for resolving external XML entities. The outcome is information disclosure. Content from file system or network shares for the machine processing the XML can be exposed to attacker. In addition, an attacker can use this as a DoS vector.

**Dependency:** None

**Notes:**

**Comment by genlu** [comment]
@qinxgit is working on this as part of #705

**Comment by lgolding** [comment]
Closing this one, because it will be done as part of PR #705.
