### ISSUE TITLE
no code actions available using VSCODE 

### ISSUE THREAD

**Issue by KitCarson03** [dotnet/roslyn-analyzers#5675]
I'm using vscode with new .net 6 rc1 version but the same issue is present also with .net 5 officiale release.
VSCode doesn't display any available fixes also for simple errors like a missing semicolon at the end of a single line of code like removing it from the default console template project.

here it is the Omnisharp Log:
https://pastebin.com/Bk90SKpG

**Comment by Evangelink** [comment]
@KitCarson03 Are you still experiencing the issue?
