### ISSUE TITLE
.Net SDK 6.0 RC2 has incorrect editor config files for AnalysisLevel 5

### ISSUE THREAD

**Issue by sfoslund** [dotnet/roslyn-analyzers#5679]
---
**Issue moved from dotnet/sdk#22276**
- Please respond to @ArturDorochowicz.

---

_From @ArturDorochowicz on Friday, October 22, 2021 5:36:15 PM_

### Describe the bug
I think that SDK 6.0 RC2 ships incorrect editorconfig files for AnalysisLevel 5. They are basically the same as for level 6, with just changes in comments from string '5.0' to '6.0'.

I'll use Docker image `mcr.microsoft.com/dotnet/sdk:6.0.100-rc.2` for examples.

These files are located here `/usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/analyzers/build/config/`
```
docker run --rm mcr.microsoft.com/dotnet/sdk:6.0.100-rc.2 ls -la /usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/analyzers/build/config/
```

We can compare file for AnalysisLevel = 5-recommended with equivalent for 6:
```
docker run --rm mcr.microsoft.com/dotnet/sdk:6.0.100-rc.2 diff /usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/analyzers/build/config/AnalysisLevel_5_recommended.editorconfig /usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/analyzers/build/config/AnalysisLevel_6_recommended.editorconfig 
3,4c3,4
< # Rules from '5.0' release with 'Recommended' analysis mode
< # Description: Rules with enabled-by-default state from '5.0' release with 'Recommended' analysis mode. Rules that are first released in a version later than '5.0' are disabled.
---
> # Rules from '6.0' release with 'Recommended' analysis mode
> # Description: Rules with enabled-by-default state from '6.0' release with 'Recommended' analysis mode. Rules that are first released in a version later than '6.0' are disabled.
```
The files are basically the same. Similar problem is with other files there as well.

### To Reproduce
The following shows an example of a problem that the issue causes.

Create a project that builds fine in .Net SDK 5.
```
dotnet new globaljson --sdk-version 5.0.400
dotnet new web
echo class C { C() { ((ILogger)null).LogDebug("{Value}", 0); } } >> Program.cs
dotnet build -p:EnableNETAnalyzers=true -p:AnalysisLevel=5-recommended
```
The project builds without errors or warnings.

Now try building that same project with 6.0 rc2 SDK while preserving the analysis level.
```
dotnet new globaljson --force --sdk-version 6.0.100-rc.2
dotnet build -p:EnableNETAnalyzers=true -p:AnalysisLevel=5-recommended
```
This builds with warning `CA1848: For improved performance, use the LoggerMessage delegates instead of calling [...]`. As far as I understand this should not happen.

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by davidegiacometti** [comment]
> I think we should try for servicing. There is no such branch yet, but I will make one now.

Any news on this? Still impacting VS 17.1.2 and .NET SDK 6.0.201.
