### ISSUE TITLE
Port FxCop rule CA3065: ReviewDataViewCollectionString

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#568]
**Title:** Review DataView CollectionString

**Description:**

Review code to insure that usage of System.Data.DataViewManager.DataViewSettingCollectionString input is sanitized to not contain DTD. Enabling DTD processing on the XML reader and using UrlResolver for resolving external XML entities may lead to information disclosure. Content from file system or network shares for the machine processing the XML can be exposed to attacker. In addition, an attacker can use this as a DoS vector.

**Dependency:** None

**Notes:**

**Comment by genlu** [comment]
@qinxgit is working on this as part of #705

**Comment by lgolding** [comment]
Closing this one, because it will be done as part of PR #705.
