### ISSUE TITLE
CA1850 (ComputeHash) code fix eats starting ifdef

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#5683]
### Analyzer

**Diagnostic ID**: [CA1850](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1850): 'Prefer HashData over ComputeHash`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 7.0.0-preview1.21523.2

### Describe the bug

If there's a `#if ` before the code being replaced, the code fixer eats it as part of the fix, leaving the code in a non-compilable state.

### Steps To Reproduce

```C#
internal sealed class Repro
{
    public static byte[] M(byte[] data)
    {
#if !SOMETHING
        using (var sha = SHA256.Create())
        {
            return sha.ComputeHash(data);
        }
#else
        return Array.Empty<byte>();
#endif
    }
}
```
Then run the code fix for CA1850.

### Expected behavior

```C#
internal sealed class Repro
{
    public static byte[] M(byte[] data)
    {
#if !SOMETHING
        return SHA256.HashData(data);
#else
        return Array.Empty<byte>();
#endif
    }
}
```

### Actual behavior

```C#
internal sealed class Repro
{
    public static byte[] M(byte[] data)
    {
        return SHA256.HashData(data);
#else
        return Array.Empty<byte>();
#endif
    }
}
```

**Comment by buyaa-n** [comment]
> We want to preserve all the trivia?

I believe that is better

**Comment by wzchua** [comment]
It introduces newlines in the resulting codefix for code without comments and such
