### ISSUE TITLE
.rtf license files in nuget packages flagged as security risk

### ISSUE THREAD

**Issue by beauvankirk** [dotnet/roslyn-analyzers#5689]
Per request from @jmarolf, I'm posting a linked issue here as well as [the original](https://github.com/dotnet/roslyn/issues/57385) on [dotnet/roslyn](https://github.com/dotnet/roslyn).

Original post:

_Based on a security bulletin issued by Microsoft, the enterprise context I work in adopted the (overly?) conservative strategy of blocking all .rtf files (and compressed files that contain them). This includes the Microsoft.CodeAnalysis and Microsoft.CodeAnalysis.Analyzers packages.
This naturally has led issues in developer experience, sometimes in ways that are not immediately apparent and/or take time to identify (especially for new team members).
I see other instances of license/third-part-notices files in this repo using plaintext (.txt) rather than .rtf. Would it be possible to consider (at least for nuget publishing) sticking to .txt or any format other than .rtf?_

**Comment by jmarolf** [comment]
@mavasani do you have any objection to converting these files to be *.txt?

**Comment by mavasani** [comment]
@jmarolf Sounds good.
