### ISSUE TITLE
Official builds failing with OneBuildLoc

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn-analyzers#5697]
The official builds have been failing since Saturday with a `DirectoryNotFoundException`: https://dev.azure.com/dnceng/internal/_build/results?buildId=1452438&view=logs&j=6aa31087-d1b8-5ee1-af29-f0fe63353381&t=f5f0ecb8-e09a-5b29-99cb-311e048f2c1c 

It appears that the tool `OneBuildLoc` is not creating a subdirectory it's expecting to be there.

**Comment by jonfortescue** [comment]
This was an error caused by a long path issue that OneLocBuild has now hotfixed. Future runs should now succeed.

**Comment by twsouthwick** [comment]
Things are working #5702
