### ISSUE TITLE
Port FxCop rule CA3072: UseXmlReaderForDataTableReadXmlSchema

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#575]
**Title:** Use XmlReader for DataTable ReadXmlSchema

**Description:**

Checks for usage of an unsafe overload of  System.Data.DataTable.ReadXmlSchema. This API internally enables DTD processing on the XML reader instance used, and uses UrlResolver for resolving external XML entities. The outcome is information disclosure. Content from file system or network shares for the machine processing the XML can be exposed to attacker. In addition, an attacker can use this as a DoS vector.

**Dependency:** None

**Notes:**

**Comment by genlu** [comment]
@qinxgit is working on this as part of #705

**Comment by lgolding** [comment]
Closing this one, because it will be done as part of PR #705.
