### ISSUE TITLE
Disable CA1050 for `partial class Program` declarations with top level statements

### ISSUE THREAD

**Issue by halter73** [dotnet/roslyn-analyzers#5769]
### Analyzer

**Diagnostic ID**: [CA1050](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1050)

### Describe the improvement

We recommend adding `public partial class Program { }` declaration outside of a namespace to make the generated normally-internal Program class visible to test projects in situations where `InternalsVisibleTo` isn't suitable. In this case, suggesting moving the declaration into a namespace isn't helpful.

### Describe suggestions on how to achieve the rule

I think we can disable this rule for types that contain entry points. If there is a way to more specifically disable it in top-level statements scenarios, that would also be fine.

### Additional context

See https://github.com/dotnet/aspnetcore/issues/38474

**Comment by Youssef1313** [comment]
Fix should be very simple, add `&& !type.IsTopLevelStatementsEntryPointType()` to this:

https://github.com/dotnet/roslyn-analyzers/blob/e101c379c6e3c7011562ee3af3e3de066da0048f/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DeclareTypesInNamespaces.cs#L45-L47
