### ISSUE TITLE
false-positive for CA1810

### ISSUE THREAD

**Issue by elachlan** [dotnet/roslyn-analyzers#5784]
### Analyzer

**Diagnostic ID**: [CA1810](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1810): `Initialize reference type static fields inline`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.100](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug

False Positive. Static constructor sets static class fields.
(https://github.com/dotnet/msbuild/blob/797fd829a374a880f63fd4eea4ea6990404c48f4/src/Build/BackEnd/Components/RequestBuilder/IntrinsicTasks/ItemGroupLoggingHelper.cs#L39-L49)

### Steps To Reproduce
Run the analyzer on the above mentioned code.

## Additional context
Using the analyzer on msbuild the related issue is [#7179](https://github.com/dotnet/msbuild/pull/7179)

**Comment by sharwell** [comment]
I'm not certain this is a false positive. Even though the types are defined in a different class, they can still be initialized at a declaration site instead of in this static constructor.

**Comment by elachlan** [comment]
I am closing the issue, because I think the analyzer pointing this out helps highlight code that can be better optimized. Which is the point of the Analyzer.

**Comment by Evangelink** [comment]
@sharwell Let me know when you are done with your investigation.
