### ISSUE TITLE
AnalysisMode.All doesn't really enable all rules

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#5793]
It enables rules with `EnabledRuleInAggressiveMode` tag. For example, CA1005 isn't enabled.

If this is by design, then a doc change may be needed

**Comment by Youssef1313** [comment]
@mavasani Can you confirm what's the correct behavior?

**Comment by mavasani** [comment]
@Youssef1313 only a very handful rules which are either marked for deprecating or extremely noisy are not enabled, rest all are enabled.

**Comment by Youssef1313** [comment]
Yeah I see there are very few rules that are passing false for `isEnabledByDefaultInAggressiveMode`.
Do we need to document this or it's not important?

**Comment by mavasani** [comment]
I think it is fine to not document given these are completely low priority rules. If customers complain about certain missing rules, we should probably have to consider enabling them with this flag rather than documenting it.

**Comment by Youssef1313** [comment]
@mavasani I should probably have added the original customer report on Discord when I opened this issue. It was mainly a confusion of `Minimum` and `Recommended`, and if they have anything to do with `EnabledRuleInAggressiveMode`:

![image](https://user-images.githubusercontent.com/31348972/149655653-7540fb07-1aee-40f6-a611-84dbd0d41795.png)

I sent the following as a response to the question, which answers the `Minimum` and `Recommended` question.

https://github.com/dotnet/roslyn-analyzers/blob/c1736d0da9501e135f0410b5a831528f699d6e60/src/Tools/GenerateDocumentationAndConfigFiles/Program.cs#L1217-L1245

If you think there is no documentation action needed, we can close the issue.

**Comment by mavasani** [comment]
Yes, sounds good to me to close the issue.
