### ISSUE TITLE
RS1024 (Compare symbols correctly): SupportedDiagnostics doesn't include all descriptors

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#5801]
https://github.com/dotnet/roslyn-analyzers/blob/c3145214555afda60a74da31f9096a788348e4fc/src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs#L28-L58

**Comment by Youssef1313** [comment]
I think diagnostics from other descriptors are still being reported even though they're not added in `SupportedDiagnostics`.

Is that because they'll have the same ID? If so, why `SupportedDiagnostics` is not simply an `ImmutableArray<string>`?

**Comment by Evangelink** [comment]
> I think diagnostics from other descriptors are still being reported even though they're not added in `SupportedDiagnostics`.

Yes that's the case! That got me fooled a couple of times.

> Is that because they'll have the same ID? If so, why `SupportedDiagnostics` is not simply an `ImmutableArray<string>`?

I don't know, I guess it's to ease future changes (having more complex scenarios where not only the ID would be used). @sharwell  might know more.

**Comment by Youssef1313** [comment]
Makes sense. Thanks. Closing
