### ISSUE TITLE
Microsoft.DotNet.Analyzers.Compatibility.Deprecated analyzer pushes build time from 10s to 2 minutes

### ISSUE THREAD

**Issue by RobSwDev** [dotnet/roslyn-analyzers#5838]
Apologies if this is the wrong forum for this issue.

One of the projects in my solution takes over 2 minutes to compile when it targets netstandard2.0, but just 10 seconds when it targets net472. 
I started looking into this, and according to the logs (screenshot below), nearly all this time is spent in the analyzer Microsoft.DotNet.Analyzers.Compatibility.

Specifying `<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>` does get compilation back to 10 seconds. However, disabling all analyzers seems like the nuclear option.

* Why does (assuming the log is accurate) this analyzer take so long? Almost 30 minutes! (albeit spread across 12 cores)
* Is there some way I can turn off only this analyzer, but let the others run?
 
(We target NetStandard2.0 in this project because it is used both in NetFramework and in Net Core/Net5/6. So upgrading the target framework isn't currently an option)

![image](https://user-images.githubusercontent.com/26545948/152154009-5ae36abb-d807-4046-821b-9cd09d93c5de.png)

**Comment by Youssef1313** [comment]
@RobSwDev Are you referencing the package `Microsoft.DotNet.Analyzers.Compatibility`? I think you can remove this reference. It doesn't appear to be maintained anymore. The [repository](https://github.com/dotnet/platform-compat) is archived.

**Comment by RobSwDev** [comment]
Yes - that's the analyzer. 
On further investigation, it seems we've accidentally included a reference to it in Directory.Build.targets. Will remove.
Apologies - did not realise the package was obsolete.

**Comment by Therzok** [comment]
@terrajobst @jmarolf sorry for the ping, but is there a way we could deprecate the package on nuget.org?

https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

**Comment by jmarolf** [comment]
I believe @terrajobst has the permissions but is on vacation. I'll ping him when he is back.

**Comment by RobSwDev** [comment]
Is there a replacement in Net5 then for the "Deprecated" DE000x analyzers from Microsoft.DotNet.Analyzers.Compatibility?
E.g. if I reference `ArrayList` with the obsolete analyzer, I get a warning. But without this analyzer, there's no warning - even when targeting Net5 or Net6.

**Comment by terrajobst** [comment]
I've marked the packaged as deprecated. It'll probably take a while for the NuGet index to reflect tht.
