### ISSUE TITLE
CA1021 triggered for overrides

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/roslyn-analyzers#5854]
### Analyzer

**Diagnostic ID**: [CA1021](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1021): `Avoid out parameters`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers 6.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/6.0.0)

### Describe the bug

Rule reported for implementation/override of base class method with `out` parameters which user cannot fix.

### Steps To Reproduce

```cs
public class Test : UriParser
{
    protected override string? Resolve(Uri baseUri, Uri? relativeUri, out UriFormatException? parsingError)
    {
        return base.Resolve(baseUri, relativeUri, out parsingError);
    }
}
```
### Expected behavior

No `CA1021` reports

### Actual behavior

`CA1021` reported for `Resolve` override

**Comment by Youssef1313** [comment]
This may apply to CA1045 as well.
