### ISSUE TITLE
CA2208: Allow the parameter name to be a parameter name or a parameter's property name (recursive)

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/roslyn-analyzers#5905]
### Analyzer

**Diagnostic ID**: [CA2208](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2208)

### Describe the improvement

Currently, only parameter names are allowed, otherwise the CA2208 raises its warning. I suggest that in future also properties and fields of arguments are allowed (recursively).

### Describe suggestions on how to achieve the rule

```
    public void DoSomething(Client client) {
        if (client is null) throw new ArgumentNullException(nameof(client)); //Okay, already accepted today
        if (client.SomeObject is null) throw new ArgumentNullException($"{nameof(client)}.{nameof(client.SomeObject)}"); //Currently not okay, in future accepted
        if (client.SomeObject.SomeOtherObject is null) throw new ArgumentNullException($"{nameof(client)}.{nameof(client.SomeObject)}.{nameof(client.SomeObject.SomeOtherObject)}"); //Currently not okay, in future accepted
        if (client.SomeObject.SomeOtherObject.WhatEver is null) throw new ArgumentNullException($"{nameof(client)}.{nameof(client.SomeObject)}.{nameof(client.SomeObject.SomeOtherObject)}.{nameof(client.SomeObject.SomeOtherObject.WhatEver)}"); //Currently not okay, in future accepted
        if (client.SomeObject is null) throw new ArgumentNullException("client.NonExistent"); //Must raise the CA2208 message
        //The same applies for ArgumentException, ArgumentOutOfRangeException and DuplicateWaitObjectException
    }

```

### Additional context

What concerns the visibility I think all in the method that throws the exception accessible properties and fields of given arguments should be allowed. Such that are not accessible (private and depending the context protected, internal and both combinations of protected and internal) should raise the CA2208 message similar to non-existing properties/fields.

If this is too complicated to implement, accept everything that is non-private.

**Comment by mavasani** [comment]
I don’t think we should make the proposed changes here. ArgumentNullException should only be thrown when the argument itself is null. For argument’s field/property being null when non-null is expected, the code should throw an ArgumentException, with the message for the exception stating which field/property is null when expected to be non-null.

**Comment by Evangelink** [comment]
I even believe it should throw `InvalidOperationException` because that's a state exception and not something related to the argument.

**Comment by Evangelink** [comment]
@mavasani Do you want to keep this ticket open?

**Comment by HugoRoss** [comment]
Yes please. InvalidOperationExceptions I don't like to use for such cases,
as that cannot be distinguished anymore from objects that are in an invalid
state (a connection that is closed, an object that was set to read-only
etc.) but this is clearly an argument that was provided incorrectly. An
ArgumentException instead of an ArgumentNullException could work but is
also loss of clarity. I do not want to convince anybody that they have to
do it like this but it would be nice if it would be supported.

Thank you.

**Comment by mavasani** [comment]
Tagging @sharwell @jmarolf @genlu - any more views here?

**Comment by Youssef1313** [comment]
I agree this is by-design.

**Comment by KUTlime** [comment]
> I don’t think we should make the proposed changes here. ArgumentNullException should only be thrown when the argument itself is null. For argument’s field/property being null when non-null is expected, the code should throw an ArgumentException, with the message for the exception stating which field/property is null when expected to be non-null.

I disagree here.

Please, review this code:

```csharp
public static async Task UpdateActionCompletionTime(IRidesRepository ridesRepository, UpdateActionCompletionTimeCommand command, CancellationToken cancellationToken)
{
    var ride = await ridesRepository.GetRideById(command.RideId, cancellationToken);
    var rideRequestId = ride?.Request.Id ?? throw new ArgumentNullException($"Ride '{ride?.Id}' does not have a mandatory ride request.", nameof(ride.Request));
    switch (command.RideStatus)
    {
        case RideStatus.Ongoing:
            await SetActionCompletionTime(
                ridesRepository,
                command.ActionCompletionTime,
                x => x.PickUps != null && x.PickUps.Contains(rideRequestId),
                cancellationToken);
            break;
        case RideStatus.Finished:
            await SetActionCompletionTime(
                ridesRepository,
                command.ActionCompletionTime,
                x => x.DropOffs != null && x.DropOffs.Contains(rideRequestId),
                cancellationToken);
            break;
        case RideStatus.New:
        case RideStatus.ConfirmedByDriver:
        case RideStatus.Boarding:
        case RideStatus.Canceled:
        case RideStatus.Rejected:
            break;
        default:
            throw new ArgumentOutOfRangeException(nameof(command.RideStatus), command.RideStatus, "Ride status is outside of mapping range");
    }
}
```

![image](https://github.com/dotnet/roslyn-analyzers/assets/8374320/6f142da4-b2dc-4864-96b8-6da6103cdd0f)

This code raises CA2208 warning despite the fact that "more or less" used in the right way.

Raising this warning **is confusing** and the current implementation **is inconsistent** (_see first null check_).

And... Yes, I do know that `InvalidEnumArgumentException` exists but since it is poorly designed, if I want to avoid throwing `InvalidCastException`, I have to go with

```csharp
throw new InvalidEnumArgumentException(nameof(command.RideStatus), Enum.GetUnderlyingType(typeof(RideStatus)) == typeof(int) ? (int)command.RideStatus : default, typeof(RideStatus));
```

which is ehm... crazy. 🤦🏿‍♀️

**Comment by sharwell** [comment]
I agree that this is by design. Projects which deviate from these practices could implement a `DiagnosticSuppressor` if other cases are common in their code.
