### ISSUE TITLE
Suggest to use extension method where applicable

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn-analyzers#5924]
Considering an extension method like:

```cs
public static string ToDateFormat(this DateTime date) => date.ToString("yyyy-MM-dd");
```

Suggest to use it where the code matches the method body.

```cs
var v = d.ToString("yyyy-MM-dd");
```
->
```cs
var v = d.ToDateFormat();
```

**Comment by Evangelink** [comment]
That's an interesting suggestion but I don't think this is something possible with the current way of working as we would need 2 passes (first to load extension methods tree and second to compare/raise/replace).

cc @mavasani @buyaa-n

**Comment by mavasani** [comment]
I agree with @Evangelink - I don't think we can meet the performance requirements for implementing such an analyzer/code fix pair. Such an analysis would require analyzing the entire compilation, and currently we do not support code fixes for diagnostics that require whole compilation analysis (for example, compilation end diagnostics do not support code fixes and are build-only diagnostics). If you disagree, feel free to prototype such a feature in your own custom third party NuGet package/VSIX.

**Comment by mavasani** [comment]
Having said the above, I believe this requests falls into a category of project/solution wide analyzers, that if implemented in future would allow users to explicitly invoke all such analyzers, and the reported issues in the error list (or a different window) should be fixable via a context menu command on each entry.

**Comment by alrz** [comment]
Where would you suggest to cache extension method trees (and possibly incrementally update) so we can reuse the first pass?

I guess the tricky part is that for N extension methods we probably don't want to walk each syntax tree N times. Ideally we should be able to convert all trees into a single automaton and run that on the entire syntax tree in one pass. No clue how to do that.
