### ISSUE TITLE
Add warning if ! (d*mn it) operator is used. 

### ISSUE THREAD

**Issue by kjpgit** [dotnet/roslyn-analyzers#5934]
I would like to set an option in my .csproj to warn if the '!' operator is used to assume something is not null without runtime checks.   If there are certain sections of code where I need it (for performance?) I would put pragmas around that section to silence the warning.

The ! operator appears to be intended to be low friction for existing codebases, which is understandable, but it is not desired for my green field project.   I want my greenfield project to be safe by default, and have low cognitive load.  I do not want my callees simple invariants (e.g. I need a string) violated.  I want errors to be trapped as soon as possible, meaning if not at compile time, than as early at runtime as possible.  "Errors should not pass silently", "Principle of least surprise", etc.  Honestly, if I wanted to YOLO I'd go back to python or c++, because those are "trust the programmer" languages.

Also, ! has a very different meaning in c# than another language my team might be familiar with (Swift does a runtime check), so warning on its use in our project could prevent accidents.

Example code:

```
class Storage
{
    public Storage(string required_table_name) { }
}

// I would like this to be a warning, because ! isn't checking that it is really non-null, before calling the constructor
// Honestly I can hardly see the ! here, buried between two parenthesis.
new Storage(Environment.GetEnvironmentVariable("CPS_TABLE_NAME")!);


// This would not throw a warning,
// and would error at runtime before calling the Storage constructor.
using static correctness_is_always_job_one;  // can also be a global using, with static=True
class correctness_is_always_job_one
{
    public static T __unwrap<T>(T? obj) {
        if (obj is null) {
            throw new ArgumentNullException();
        }
        return obj;
    }
}
new Storage(__unwrap(Environment.GetEnvironmentVariable("CPS_TABLE_NAME")));
```

**Comment by kjpgit** [comment]
In case anyone searches this
https://github.com/tom-englert/Nullable.Extended#roslyn-analyzer
https://stackoverflow.com/questions/70406775/prevent-null-forgiving-operator-usage

**Comment by mavasani** [comment]
Agree with @sharwell. Such an analyzer wouldn’t be part of any analyzer package shipped out of this repo. Feel free to author your own analyzer package for such an analyzer. We should close this issue as Won’t Fix.

**Comment by kjpgit** [comment]
Neither of you have given an actual reason why this shouldn't be fixed.  Isn't the goal to warn on unsafe usage?

Regardless, let's talk about this analyzer you suggest I write.  Where are docs on how to write an analyzer using .net cli on linux, and have it work with 'dotnet build'?  How do I verify what analyzers being run by dotnet build?  I have tried and it is utterly frustrating.  I do not use visual studio.

**Comment by mavasani** [comment]
> Neither of you have given an actual reason why this shouldn't be fixed

@kjpgit Sorry if the context wasn’t clear. Sam did mention why this request would not qualify for an analyzer that ships inside VS/.NET SDK:

_ This is a request to outright ban the use of a language feature, which is not something the compiler team (who implemented said feature) is interested in doing._

**Comment by kjpgit** [comment]
I made absolutely no such request to ban a feature.  I requested an optional warning (off by default), which could still be suppressed by pragmas around code blocks.

**Comment by kjpgit** [comment]
Anyway, I tried using this analyzer https://www.nuget.org/packages/Nullable.Extended.Analyzer/ which has 7000 downloads (so I'm NOT the only person running into this safety issue), but I can't get it to work in dotnet build.  I find zero documentation on creating or using analyzers with CLI / dotnet build, as mentioned above.

**Comment by kjpgit** [comment]
I got the above analyzer working after adding a .editorconfig to change it from info to warning for `dotnet build`, per a stackoverflow person who helped me.  Don't really like relying on a random nuget package, but happy to have a solution finally.

**Comment by sharwell** [comment]
> I made absolutely no such request to ban a feature. I requested an optional warning (off by default), which could still be suppressed by pragmas around code blocks.

This feature has been considered in the past, and we believe it would be _interpreted_ as saying the `!` feature is not intended for use, even if the rule is optional or can be disabled. We therefore opted to not implement the feature as part of the built-in analyzer package, but it can of course be implemented separately (or obtained from a separate analyzer package).
