### ISSUE TITLE
Remove rule CA2109

### ISSUE THREAD

**Issue by gewarren** [dotnet/roslyn-analyzers#5974]
Because [code access security is dead](https://docs.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib0003), we should no longer ship rule CA2109, because it doesn't have any meaning. See https://github.com/dotnet/docs/pull/25046#issuecomment-1097268401.

**Comment by Evangelink** [comment]
@buyaa-n I don't think `SYSLIBXXXX` rules are coming from this repository. Could you move the issue to the right repo?

cc @mavasani

**Comment by Evangelink** [comment]
@buyaa-n I would suggest not to remove the rule in case some people in .NET Framework are still relying on it. Instead I would update the documentation to say this is no longer relevant on .NET/.NET Core.

We could also tweak the rule to never report on .NET/.NET Core but as it's disabled by default I wouldn't do so.

**Comment by gewarren** [comment]
cc @GrabYourPitchforks

I believe the rule isn't relevant, even on .NET Framework.

**Comment by Evangelink** [comment]
Ah right maybe I misunderstood the comment. Let's wait for relevant reply :)

**Comment by mavasani** [comment]
I thought we retained this rule as a disabled rule for legacy code bases running older frameworks. I am fine with removing the rule completely OR at the minimum it's descriptor should pass `false` for below flag so it does not get bulk enabled by `AnalysisLevel = all` value: https://github.com/dotnet/roslyn-analyzers/blob/ca6f78474bad2298b47f2aeea16d5fa74b1d2b0f/src/Utilities/Compiler/DiagnosticDescriptorHelper.cs#L23

**Comment by x789** [comment]
I would like to try to fix the problem. So far, two possible solutions have been discussed. Which one should be implemented?
1. Delete CA2109
2. Prevent CA2109 from being activated when `AnalysisLevel` is set to `all`?

**Comment by mavasani** [comment]
@dotpaul for his views

**Comment by dotpaul** [comment]
Agree with @gewarren with removing CAxxxx rules related to CAS

**Comment by buyaa-n** [comment]
Not opposing with removing CAxxxx rules related to CAS, but it seems the rule CA2109 doesn't seem related to CAS  [CA2109: Review visible event handlers](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2109), expect it used `SecurityPermissionAttribute` in the [example](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2109#example). Why don't we just remote the attribute from example? Am I missing something else?

**Comment by x789** [comment]
@buyaa-n, you are right that the code of CA2109, apart from the example, does not refer directly to CAS.
But if I understood it correctly, since CAS was dropped, the attack vector that CA2109 is supposed to warn about no longer exists. Therefore, the rule became obsolete.

**Comment by buyaa-n** [comment]
> But if I understood it correctly, since CAS was dropped, the attack vector that CA2109 is supposed to warn about no longer exists.

Thanks @x789, confirmed that is correct, please go ahead and remove CA2109

**Comment by GrabYourPitchforks** [comment]
Spoke with Buyaa offline. Specifically, the problem that CA2109 was trying to warn against (an untrusted intermediary hooking a privileged event handler to a privileged event invoker) was addressed before .NET Framework 4.5 even shipped. Even putting aside all of the "CAS as a whole is obsolete" discussion, this specific Code Analysis rule is outdated and tries to detect something that hasn't been an issue for ages.

**Comment by x789** [comment]
Thank you for the clarification, @buyaa-n and @GrabYourPitchforks.

I will remove the analyzer rule. 

Can someone please assign this issue to me?
