### ISSUE TITLE
.editorconfig and code quality CAxxx analyzers

### ISSUE THREAD

**Issue by martinkoslof** [dotnet/roslyn-analyzers#5984]
Hello, I have spent more then a day trying to figure this out, I feel the more online documentation I read, the less I understand. My goal is to migrate our solutions code analysis to roslyn and we want to use Roslynator and also the built-in analyzers which come with modern versions of the .Net ecosystem. What I am trying to accomplish is a **single** .editorconfig file which can set all severities and options.

1) While not relevant to this ticket I can set all RCS (Rosylnator) severities via editor config and the build breaks or shows an error. I also see the red underlines in the IDE, all works as I expect.

2) In addition, I can set the IDExxx rules via my editorconfig. For example:

`dotnet_diagnostic.IDE0079.severity = error`

With this set, I get build errors and the IDE show me the red error.

However, I am unable to get a clear understanding how the code quality (CAxxx) rules work with .editorconfig.  From what I can see, no matter what I do, the IDE does not show a red error and the build simply succeeds.  For example:

`dotnet_diagnostic.CA2227.severity = error`

This seems to have no effect on the build process at all, the violation in the code seems to be totally ignored. It appears none of my CAxxx rules in my editor config "break" the build or display as errors in the IDE. I am using Visual Studio 2022 and .net5 at the moment. I have scanned over some other documentation, and its not clear if I am missing something in my .editorconfig, or if this simply doesn't work.

I have tried setting `dotnet_code_quality.api_surface = all`. It doesn't seem to have any effect. I have tried switching from:

`dotnet_diagnostic.CA2227.severity = error`  to:  `dotnet_code_quality.CA2227.severity = error` and I see no difference.

Am I doing something wrong? Is this simply NOT supported from editorconfig and we have to use global analysis configs instead? I also do **not** have `<TreatWarningsAsErrors>` set as true within my Build.props file because I was trying to build a comprehensive editorconfig file and explicitly name all our error severities.

I'm hoping someone can help me figure out the direction I need to take. It seems very odd to me that IDExxx rules can be totally driven by editorconfig (and break the build and show errors in the IDE) but the CA rules seem to be acting totally different.

**Comment by Youssef1313** [comment]
Can you upload a sample "Hello world" project where you can reproduce this?

**Comment by Youssef1313** [comment]
As a guess:

- You could be missing `<EnableNETAnalyzers>true</EnableNETAnalyzers>` in csproj (if you don't want to use the NuGet package)
- Or you could just add the NuGet package.

**Comment by martinkoslof** [comment]
Hi Youssef, I wound up doing the following:

1) Keeping all formating and style semantics in my root level . editorconfig

2) Moved ALL code style and code quality rules (IDE, CS, CA, etc) to a root level .globalconfig

This has resolved a bunch of inconsistencies for us. Honestly, the documentation is very confusing and if .globalconfig is supposed to be the recommended "replacement" for old rulesets that needs to be more clear. Also documentation which puts dotnet_diagnostics.CAxxx  = error is very confusing, given it does not break the build or show as errors *for all of them* or even ones where it supposedly works.

I will close this ticket as resolved, but I do feel documentation and examples are lacking. I only figured my issues by reading through tons of GitHub tickets and dialogs being had by various contributors and participants.
