### ISSUE TITLE
I am getting flaky error when testing analyzers.

### ISSUE THREAD

**Issue by voroninp** [dotnet/roslyn-analyzers#6006]
Analyzer tests pass in CI/CD, but locally I have (not always) this error: 

> NuGet.Packaging.Core.PackagingException : The package is missing the required nuspec file. Path: C:\Users\vorop\AppData\Local\Temp\test-packages\Microsoft.NETCore.App.Ref.3.1.0

Test project is targeting `.net6.0`
Folder contains `Microsoft.NETCore.App.Ref.3.1.0.nupkg` file, and package itself has `Microsoft.NETCore.App.Ref.nuspec` file.

If I remove the folder, on the next test run it is recreated with all the files:
![image](https://user-images.githubusercontent.com/9202028/169708748-b3e8f7b5-3a23-4193-b863-8f571c083d95.png)

Yet after some time, this error appears again.

**Comment by Evangelink** [comment]
Hi @voroninp, would you mind sharing a reproducing project?

**Comment by voroninp** [comment]
the probable reason for failure is having such tests:

```CSharp
[Fact]
public async Task Discarded_result_causes_error()
{
    await new CSharpAnalyzerTest<ResultNotDiscardedAnalyzer, XUnitVerifier>
    {
        ReferenceAssemblies = new ReferenceAssemblies(
            "net6.0", new PackageIdentity("Microsoft.NETCore.App.Ref", "6.0.0"), Path.Combine("ref", "net6.0")),
        TestState =
        {
            Sources = { _discardedResult },
            AdditionalReferences = { typeof(Result).Assembly.Location },
            ExpectedDiagnostics = 
            { 
                Verify.Diagnostic(ResultNotDiscardedAnalyzer.DiagnosticId)
                    .WithSpan(6, 18, 6, 29)
                    .WithArguments("Result.Ok()")
            }
        }
    }.RunAsync();
}
```

**Comment by Evangelink** [comment]
I am not sure to follow your problem. You are talking about v3.1.0 and your code sample references v6.0.0. Do you have a small buildable project that reproduces the issue?

Also I am not entirely sure about the problem but most likely if there is an issue it's more of a testing sdk issue (so would need to be transfered to https://github.com/dotnet/roslyn-sdk).

**Comment by voroninp** [comment]
@Evangelink , I'll try to make such solution, but cannot guarantee. 

Yes, it's quite weird because none of my projects reference .net core 3.1

**Comment by Evangelink** [comment]
Is your project open source? If so can you point it out to me?

**Comment by voroninp** [comment]
Alas, company gitlab server.

**Comment by csMACnz** [comment]
I had this issue as well.
Deleting the temp folder `C:\Users\<username>\AppData\Local\Temp\test-packages` solved it for me.

**Comment by Youssef1313** [comment]
Deleting `%TEMP%\test-packages` is the correct solution here. I'm going to close as answered, butif you still have questions, open a new issue on dotnet/roslyn-sdk (this is the repo that has testing library implementation)

**Comment by ericburcham** [comment]
> the probable reason for failure is having such tests:
> 
> ```cs
> [Fact]
> public async Task Discarded_result_causes_error()
> {
>     await new CSharpAnalyzerTest<ResultNotDiscardedAnalyzer, XUnitVerifier>
>     {
>         ReferenceAssemblies = new ReferenceAssemblies(
>             "net6.0", new PackageIdentity("Microsoft.NETCore.App.Ref", "6.0.0"), Path.Combine("ref", "net6.0")),
>         TestState =
>         {
>             Sources = { _discardedResult },
>             AdditionalReferences = { typeof(Result).Assembly.Location },
>             ExpectedDiagnostics = 
>             { 
>                 Verify.Diagnostic(ResultNotDiscardedAnalyzer.DiagnosticId)
>                     .WithSpan(6, 18, 6, 29)
>                     .WithArguments("Result.Ok()")
>             }
>         }
>     }.RunAsync();
> }
> ```

OK.  But _why_ is this the probable reason?

**Comment by voroninp** [comment]
@ericburcham , I vaguely remember that all these strings were used by me without clear understanding why I have to reference .NET 6 like that, so I just suspected I was doing something wrong.
