### ISSUE TITLE
Shouldn't there be a tag or a branch for Microsoft.CodeAnalysis.NetAnalyzers version 6.0.0?

### ISSUE THREAD

**Issue by hilari0n** [dotnet/roslyn-analyzers#6007]
NuGet.org for the Microsoft.CodeAnalysis.NetAnalyzers package leads to this repository as source.
I'm interested into looking at what source went into that NuGet package version 6.0.0 (the current newest stable version).
The releases page (https://github.com/dotnet/roslyn-analyzers/releases) lists the 5.0.3 as the latest released version.
I can't find any tags or branches which would match the 6.0.0 version number.
Could anyone point me in the right direction?

**Comment by mavasani** [comment]
@jmarolf

**Comment by hilari0n** [comment]
For me, that's enough info and thank you very much for bringing the nuget.info to my attention - I was unaware of that tool.
For others it might be beneficial to have the 6.0.0 on the list of releases, with the release notes, etc.

**Comment by Youssef1313** [comment]
> For others it might be beneficial to have the 6.0.0 on the list of releases, with the release notes, etc.

I definitely agree. In fact, the [post release documentation](https://github.com/dotnet/roslyn-analyzers/blob/main/PostReleaseActivities.md) mentions it:

> Please follow the below steps after publishing analyzer NuGet packages from this repo onto NuGet.org:
>
> 1. Create a new release OR Update an existing draft release:
>   1. Draft: Either click [here](https://github.com/dotnet/roslyn-analyzers/releases/new) to draft a new release OR update an [existing draft release](https://github.com/dotnet/roslyn-analyzers/releases). For reference, you can look at any of the existing releases, say [v2.9.3](https://github.com/dotnet/roslyn-analyzers/releases/edit/v2.9.3).
>   2. Release notes: Follow the steps in the *Steps to generate Release Notes* below to generate Release notes and copy the generated notes to the description section of the new release.
>   3. Publish: Mark the release as a pre-release if appropriate and click "Publish Release".

**Comment by mavasani** [comment]
Tagging @JoeRobich @jmarolf - something we may want to include in our steps to be done post publishing of Microsoft.CodeAnalysis.NetAnalyzers package on nuget.org.

**Comment by JoeRobich** [comment]
I added a release and branch for the NetAnalyzers 6.0.0 release. https://github.com/dotnet/roslyn-analyzers/releases/tag/6.0.0

**Comment by hilari0n** [comment]
That seems to address everything.
