### ISSUE TITLE
CA2241 should respect new StringSyntaxAttribute.CompositeFormat

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#6012]
### Analyzer

**Diagnostic ID**: [CA2241](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2241)

### Describe the improvement

"CA2241: Provide correct arguments to formatting methods" has a hardcoded list of methods that accept a composite format string.  But in .NET 7, the new StringSyntaxAttribute exists and includes a StringSyntaxAttribute.CompositeFormat, which has been used to annotate many string parameters that are expected to be passed a composite format string.  CA2241 should ideally apply to any parameter that accepts such a format string, at least in terms of validating the correctness of the syntax of the string.

### Describe suggestions on how to achieve the rule

For any method invocation, look at the parameters to see if any is attributed with `[StringSyntax(StringSyntaxAttribute.CompositeFormat)]`, and if it is, validate that the argument being passed for that parameter is correctly formed (as it does today for the hardcoded list).

**Comment by Evangelink** [comment]
@stephentoub I have a couple of questions:
- Is it possible to have more than 1 parameter with this attribute on a method call? 
- If defined on an interface/abstract, is user forced to redefined it or is it "inherited"?

**Comment by stephentoub** [comment]
> Is it possible to have more than 1 parameter with this attribute on a method call?

Yes, though that would be extremely rare. We have hundreds of parameters attributed now in .NET 7 and I don't believe we have any such cases.

> is user forced to redefined it or is it "inherited"?

From a reflection standpoint, it's not inherited.

**Comment by manfred-brands** [comment]
@stephentoub Can I put my hand up for this one?

**Comment by stephentoub** [comment]
Go for it. Thanks!
