### ISSUE TITLE
CA1854 Improve suggested variable name and/or type of the fixer

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/roslyn-analyzers#6022]
### Analyzer

**Diagnostic ID**: CA1854 Prefer the 'IDictionary.TryGetValue(TKey, out TValue)' method

### Describe the improvement

The fixer now suggests to use `TryGetValue(key, out var value)`, some repos prefer concrete type over var, it would be great to add some improvements to resolve this. Also the variable name value might already defined within the scope, it could suggest a bit modified name like `value1` when a variable named `value` is already defined within the scope

### Describe suggestions on how to achieve the rule

- [x] Analyzer could try to determine the concrete type of the `value` and add another option for fixer suggestion: one option with var, another with the concrete type
- [ ] When a variable named `value` is already defined within the scope suggest a bit modified name like `value1` etc

### Additional context

Related to https://github.com/dotnet/runtime/pull/70157#discussion_r888126273

**Comment by Youssef1313** [comment]
I think Roslyn will apply `CSharpVarReducer` after running a codefix. This reducer converts explicit types with `var` if the user prefers that. So the codefix should use explicit type, and the result could be magically turned into `var` by `CSharpVarReducer`. For this reducer to work, I think the node should have a simplifier annotation.

**Comment by buyaa-n** [comment]
> I think Roslyn will apply CSharpVarReducer after running a codefix. This reducer converts explicit types with var if the user prefers that. So the codefix should use explicit type, and the result could be magically turned into var by CSharpVarReducer.

Interesting, if that is the case suggesting only explicit type sounds good to me

> For this reducer to work, I think the node should have a simplifier annotation.

Did not understood this part, when the reducer would convert to var?

**Comment by Youssef1313** [comment]
@buyaa-n I got a PR ready. https://github.com/dotnet/roslyn-analyzers/pull/6023

**Comment by Youssef1313** [comment]
The reamining work here is:

> When a variable named `value` is already defined within the scope suggest a bit modified name like `value1` etc

This was reported in https://github.com/dotnet/roslyn-analyzers/issues/6287
