### ISSUE TITLE
Install analyzers as a VSIX extension?

### ISSUE THREAD

**Issue by Donaut** [dotnet/roslyn-analyzers#6030]
Hello,

Sharing these analyzers as a nuget packages is a problem for me. I would like to use them on my workplace but the problem is if they didn't like the idea i cannot just push a new nuget reference into the project, so evryone uses these analyzers or no one. Is it possible to install the analyzer only on my machine?

**Comment by Evangelink** [comment]
Hi @Donaut, vsix package for the analyzers were retired a couple of years ago. I don't think there is any easy/out-of-the-box way for you to achieve that.

Maybe @buyaa-n, @Youssef1313 or @mavasani would have some idea?

**Comment by Youssef1313** [comment]
If the problem is that you don't want to have an explicit package reference from NuGet, you can still consume these analyzers from the .NET SDK.

**Comment by Evangelink** [comment]
I think the problem is more to not "impose" the rules on other devs of his team. Only option I see would be to use the analyzers from SDK, disable all rules by default and use a local (ignored from source control) .editorconfig/ruleset to enable the rules locally.

**Comment by Youssef1313** [comment]
@Evangelink Another thought: Clone roslyn-analyzers locally, build it in Release mode, there should be a vsix produced in `artifacts\VSSetup\Release`. To get updates, there will be no way other than pulling latest changes and building the repository again.

**Comment by Donaut** [comment]
Awesome, thank you.

**Comment by Donaut** [comment]
Sorry for reopening the issue, I tried to use the .vsix installer but the installer doesn't support visual studio 2022. Can you help me with how I can enable it to support?

**Comment by Evangelink** [comment]
Hi @Donaut,

The VSIX is no longer supported. We now recommend to user either NuGet packages (see readme) or if you are using .NET 5+ sdk it's already built-in and you only need to enable rules.
