### ISSUE TITLE
RS0034 misfires on MEF importing constructor's attribute, claiming we need one

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#6037]
### Analyzer

**Diagnostic ID**: RS0034: 

### Analyzer source

**NuGet Package**: [Roslyn.Diagnostics.Analyzers](https://www.nuget.org/packages/Roslyn.Diagnostics.Analyzers)

**Version**: 3.3.3 (Latest)

### Describe the bug

A false positive: 
> RS0034	'DesignTimeBuildService' is MEF-exported and should have a single importing constructor of the correct form
Exported parts should be marked with 'ImportingConstructorAttribute'.

Ironically it highlights the very attribute it claims we should add:
![image](https://user-images.githubusercontent.com/3548/175976411-f803b9f7-2f69-429a-bd15-93f251bd02f9.png)

I wonder if this is because the analyzer expects the attribute from the `System.Composition` namespace whereas this one comes from the `System.ComponentModel.Composition` namespace.

This happens on [the ProjectServices repo](https://dev.azure.com/devdiv/DevDiv/_git/ProjectServices) after upgrading the analyzers.

**Comment by Youssef1313** [comment]
It looks like there is a requirement by the analyzer that the constructor should be public:

https://github.com/dotnet/roslyn-analyzers/blob/7e77cc9f8eef068e3125041fbc280681d3d8cf51/src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructor.cs#L124-L131

The message should be updated to reflect that.

**Comment by Evangelink** [comment]
@sharwell Is there any hard requirement to have the ctor public?

**Comment by jasonmalinowski** [comment]
> I wonder if this is because the analyzer expects the attribute from the System.Composition namespace whereas this one comes from the System.ComponentModel.Composition namespace.

We had a bug here I think we saw before (I don't know if we fixed it), but the assumption was the other analyzer we have for flagging mixed MEF versions should have fired too.

**Comment by jasonmalinowski** [comment]
@AArnott Any chance you had mixed MEF attributes happening in that part, some from MEFv1 and some from MEFv2?

**Comment by AArnott** [comment]
I confirmed the diagnostic goes away when I make the constructor public. Sounds like the analyzer's diagnostic message is misleading as to what it really wants you to do, which is unnecessary BTW since MEFv1 and VS-MEF can access non-public members just fine. Only MEFv2 struggles with it.

**Comment by sharwell** [comment]
> Only MEFv2 struggles with it.

MEF 2 also struggles with silent part rejection, but it turned out that MEF 2 needed to be a supported scenario so we can't just ignore it. Either way, the rule was created for the purpose of code consistency so in some cases it's more strict than what MEF requires.

**Comment by AArnott** [comment]
I think it's fine for this analyzer to include whatever you need it to. But can the message be updated to make clear what it expects to be changed? That way I can either address or suppress rather than be confused by it asking for something that's already there.

**Comment by sharwell** [comment]
Yes, the message could be updated. The analyzer implementation is here for someone that wants to send a PR for this:
https://github.com/dotnet/roslyn-analyzers/blob/main/src/Roslyn.Diagnostics.Analyzers/Core/ExportedPartsShouldHaveImportingConstructor.cs
