### ISSUE TITLE
How is BannedApiAnalyzers intended to be used?

### ISSUE THREAD

**Issue by dao-net** [dotnet/roslyn-analyzers#6068]
I cannot find any information on how the Microsoft.CodeAnalysis.BannedApiAnalyzers are intended to be used.

Do they have a hard-coded list of "illegal" members/type to call? When adding the analyzer to my project I do not get any additional errors or warnings at least.

Or do they provide a mechanism with which I can mark members in my code with an attribute (similar to `[Obsolete("Use GetDateTimeOffsetChanged() instead.", error: true)]`) which yield an error if I mistakenly call these members from somewhere in my own code or when when my library is referenced?

In my case the later would be the interesting case since I am searching for an alternative to `Obsolete` which I use to mark members which I have to declare due to requirements of third-party deserialization libraries but which I do not want to be called by anyone else because they work only when used/called in the right order (like the third-party-libraries do).

**Comment by mavasani** [comment]
@dao-net Please refer to https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md for the documentation

**Comment by dao-net** [comment]
Thanks for the hint. That's the info I was looking for.

I suggest [https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisbannedapianalyzers](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysisbannedapianalyzers) gets updated with a paragraph similar to the one under [https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysispublicapianalyzers](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysispublicapianalyzers) saying 

     For instructions on using this analyzer, see [Instructions](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md).

**Comment by mavasani** [comment]
Thank you @dao-net! Are you able to submit a quick PR for the fix? Thanks.

**Comment by dao-net** [comment]
Let's say I tried to: #6070
