### ISSUE TITLE
Platform compatibilty analyzer doesn't treat "windows" as "windows7.0" by default

### ISSUE THREAD

**Issue by jonathanou** [dotnet/roslyn-analyzers#6098]
### Description

I have a multi-target project that targets to both `net6.0` and `net6.0-windows`.  The project has an API that is `[SupportOSPlatform("windows")]` whose implementation references a cross-platform type.  When building `net6.0-windows` though, I'm getting CA1416 about the API accessing a windows 7 or later type.

It appears the analyzer treats code defined under `net6.0-windows` as windows 7.0, but doesn't treat `SupportedOSPlatform("windows")` as windows 7.0.

I don't get CA1416 when building `net6.0`.

### Reproduction Steps

```cs
public static class Class1
{
    public static void Caller()
    {
        if (OperatingSystem.IsWindows())
        {
            DoStuff();
        }
    }

    [SupportedOSPlatform("windows")]
    public static void DoStuff()
    {
        var type = new MyType();
        WinApi(type);
    }

    [SupportedOSPlatform("windows")]
    public static void WinApi(MyType type)
    {
        // call win-specific APIs here
    }
}

public class MyType
{
    // this is a cross-platform type
}
```

### Expected behavior

No CA1416

### Actual behavior

CA1416 flagged on `var type = new MyType();`

![image](https://user-images.githubusercontent.com/1291962/182773093-831884ec-92fa-4c05-abb8-cca7b8b1bbfc.png)

### Known Workarounds

Need to specify "windows7.0" explicitly

```cs
[SupportedOSPlatform("windows7.0")]
public static void DoStuff()
{
    var type = new MyType();
    WinApi(type);
}

[SupportedOSPlatform("windows7.0")]
public static void WinApi(MyType type)
{
    // call win-specific APIs here
}
```

**Comment by buyaa-n** [comment]
@jonathanou actually you could overwrite the default MSBuild version with `<SupportedOSPlatformVersion>0.0</SupportedOSPlatformVerison>` property, then it would produce `[assembly:SupportedOSPlatform("windows")]` attribute instead of `[assembly:SupportedOSPlatform("windows7.0"])`. Therefore I don't think the analyzer need to special case this scenario

**Comment by jonathanou** [comment]
I can give that a shot but it sounds like a workaround rather than a fix to me?

Is it possible for the analyzer to read the `SupportedOSPlatform` attribute value to decide what the version of "windows" should be?

**Comment by buyaa-n** [comment]
It is not a workaround, it is the design, I was just forgot how we were planning to solve this

> Is it possible for the analyzer to read the SupportedOSPlatform attribute value to decide what the version of "windows" should be

Not sure what you mean, the analyzer reads the attribute value to evaluate the platform and version compatibility

We could special case `windows7.0` -> `windows` (0.0) but that could cause issue when the API was really for windows 7.0 not for windows (0.0). With that being said, I am closing this issue with not planned
