### ISSUE TITLE
Platform compatibility analyzer doesn't recognize operating system checks that return or throw

### ISSUE THREAD

**Issue by jonathanou** [dotnet/roslyn-analyzers#6100]
### Description

I have a project targeted to `net6.0` that is calling an API that is supported on windows only.  I am throwing `PlatformNotSupportedException` if `OperatingSystem.IsWindows() == false`, but still getting CA1416.

I also get CA1416 if I `return` instead of `throw PlatformNotSupportedException`.

### Reproduction Steps

```cs
public static void Caller()
{
    if (OperatingSystem.IsWindows() == false)
    {
        throw new PlatformNotSupportedException();
    }

    WinApi();
}

[SupportedOSPlatform("windows")]
public static void WinApi()
{
}
```

### Expected behavior

No CA1416 warning.

### Actual behavior

`WinApi()` is flagged with CA1416.

![image](https://user-images.githubusercontent.com/1291962/182769211-4f524ff1-6e68-4be6-acf2-eeabf28ef72e.png)

### Known Workarounds

Need to write this instead:

```cs
if (OperatingSystem.IsWindows())
{
    WinApi();
}
else
{
    throw new PlatformNotSupportedException();
}
```

**Comment by buyaa-n** [comment]
> That was just a simplified example. Perhaps this example may be more convincing:

Thanks, that scenario should be covered by https://github.com/dotnet/roslyn-analyzers/issues/5771

Closing as duplicate
