### ISSUE TITLE
No Tag for v3.3.3

### ISSUE THREAD

**Issue by WalkerCodeRanger** [dotnet/roslyn-analyzers#6108]
The [VERSIONING.md](https://github.com/dotnet/roslyn-analyzers/blob/main/VERSIONING.md) document says that the tag for version 3.3.3 is `v3.3.3` and points to commit [2771ee3](https://github.com/dotnet/roslyn-analyzers/commit/2771ee33883320861d72cdd23bf09a8da7fa8e5e). There is no tag `v3.3.3` in this repo even though there are tags for many previous versions like `v3.3.2`. However, version 3.3.3 has been released. For example https://www.nuget.org/packages/Microsoft.CodeAnalysis.BannedApiAnalyzers/3.3.3

**Comment by mavasani** [comment]
@JoeRobich You may want to do this as a follow-up to https://github.com/dotnet/roslyn-analyzers/pull/5670. Probably also update https://github.com/dotnet/roslyn-analyzers/blob/main/PostReleaseActivities.md to mention this step.

**Comment by JoeRobich** [comment]
Release and tag v3.3.3 were created. No need to update the post release activities. Creating the release will create the tag.
