### ISSUE TITLE
CS1852 warns on generated Program for top-level statements

### ISSUE THREAD

**Issue by kronic** [dotnet/roslyn-analyzers#6141]
### Description

Can't get rid of error  CS1852

### Reproduction Steps

Create default console project.
add .editorconfig with 
dotnet_diagnostic.CA1852.severity = error

### Expected behavior

genrate program class sealed

### Actual behavior

genrate program class no sealed

**Comment by julealgon** [comment]
@stephentoub do you have any idea about when this patch will be released?

**Comment by stephentoub** [comment]
I don't know. @mavasani?

**Comment by mavasani** [comment]
Tagging @jmarolf

**Comment by cremor** [comment]
This is still not fixed in SDK 7.0.102. But installing the NuGet package "Microsoft.CodeAnalysis.NetAnalyzers" 7.0.0 manually fixes it. Does the SDK not contain the release version of the NuGet package?

**Comment by jhartmann123** [comment]
@mavasani @jmarolf The issue still appears with SDK 7.0.200. It looks like the fix from #6278 is only on main, but not on the 7.x release branch.  

Current main with check for the top level statements:
https://github.com/dotnet/roslyn-analyzers/blob/50f62a926806bc75f294b5f738bc6694e0941361/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs#L58-L67

Current branch release/7.0.1xx without this check:
https://github.com/dotnet/roslyn-analyzers/blob/897aa840ae62ff058adedb2f3b64077b32f43eb7/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs#L58-L66

**Comment by buyaa-n** [comment]
FYI it is only fixed in .NET 8, never ported to 7.0 before except the https://github.com/dotnet/roslyn-analyzers/pull/6504, we will try to add that fix in next 7.0 release.

**Comment by dotnetshadow** [comment]
Looks like this has been fixed

**Comment by mavasani** [comment]
@buyaa-n - did the code flow/branching into dotnet/sdk repo break?

**Comment by JamieMagee** [comment]
Here are some examples highlighting the regression:
- [`7.0.203` passes][1]
- [`7.0.302` fails][2]

[1]: https://github.com/octokit/webhooks.net/actions/runs/4916874277/jobs/8781202805#step:3:15
[2]: https://github.com/octokit/webhooks.net/actions/runs/4996945731/jobs/8950737735#step:3:17

**Comment by buyaa-n** [comment]
> @buyaa-n - did the code flow/branching into dotnet/sdk repo break?

I don't really know how it is supposed to flow, I don't see [the change added in 7.0.2](https://github.com/dotnet/sdk/pull/31138) included in [7.0.3 ](https://github.com/dotnet/sdk/blob/ee7f317468f5a8030578a45b5262ac1b8b8c6330/eng/Versions.props#L105)

**Comment by QuintinWillison** [comment]
I've also seen this (private repository, so I can't share a link). For what it's worth, I don't get this failing locally (Windows) but do get it failing in CI (Linux GitHub runner).

**Comment by menees** [comment]
One workaround is to add this `#pragma` at the top of the Program.cs file:

``` cs
// CA1852 Type 'Program' can be sealed because it has no subtypes in its containing assembly and is not externally visible
#pragma warning disable CA1852
```

**Comment by buyaa-n** [comment]
Update: we are working on adding this to the next 7.0.3 release
