### ISSUE TITLE
Bug in fixer for CA1836 

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/roslyn-analyzers#6145]
### Analyzer

**Diagnostic ID**: [CA1836](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1836): `Prefer IsEmpty over Count when available`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.400](https://dotnet.microsoft.com/download/dotnet/6.0)

_OR_

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 6.0.0 (Latest)

### Describe the bug

Given code such as `if (queue.Count > 0)`, CA1836 correctly highlights that one should use `IsEmpty`.  The correct fix would be `if (!queue.IsEmpty)`, but the fixer for CA1836 ignores the operator and replaces with `if (queue.IsEmpty)` - negating the intention of the original code.

### Steps To Reproduce

Create a new .NET 6 console app in Visual Studio.

In the project properties page, on the code analysis tab, set the analysis level to "Latest Recommended".  (Alternatively, set `<AnalysisLevel>latest-recommended</AnalysisLevel>` in the csproj.)

Add this code:

```csharp
using System.Collections.Concurrent;

var queue = new ConcurrentQueue<string>();
queue.Enqueue("test");

if (queue.Count > 0)
{
    // test
}
```

Note that `queue.Count > 0` is highlighted by the analyzer.  Apply the suggested fix.

### Expected behavior

The fix should be `if (!queue.IsEmpty)`

### Actual behavior

The fix is incorrectly applied as `if (queue.IsEmpty)`

## Additional context

The same result also occurs with equality operators.  In general, I would expect the following:

| original code | correct replacement | notes |
|---|---|---|
| `queue.Count == 0` | `queue.IsEmpty` | works already |
| `queue.Count <= 0` | `queue.IsEmpty` | works already |
| `queue.Count < 1` | `queue.IsEmpty` | works already |
| `queue.Count != 0` | `!queue.IsEmpty` | broken, wrong replacement |
| `queue.Count > 0` | `!queue.IsEmpty` | broken, wrong replacement |
| `queue.Count >= 1` | `!queue.IsEmpty` | not detected, but logically should |

**Comment by mattjohnsonpint** [comment]
Any update here?

**Comment by Youssef1313** [comment]
@mattjohnsonpint It works correctly for me.

![image](https://user-images.githubusercontent.com/31348972/207143308-ea70fc2a-260f-492f-9192-489c7da22024.png)

**Comment by mattjohnsonpint** [comment]
Hmmm.. I can't reproduce it now either, and it was super easy to repro previously.  I don't see any recent changes in the source code for this analyzer, so I'm not sure what was going on.  Somehow I must have had an older version.

Thanks.
