### ISSUE TITLE
CA1508 False positive for "'o as T' is always 'null'"

### ISSUE THREAD

**Issue by bartdesmet** [dotnet/roslyn-analyzers#6165]
### Steps To Reproduce

```csharp
class Base
{
}

class Derived1 : Base
{
}

class Derived2 : Base
{
}

class Derived3 : Base
{
}

class Program
{
    static void Main() { }

    static void Bar(Base obj)
    {
#if REPRO
        Derived1 res = obj as Derived1 ?? Foo(obj as Derived2 ?? throw new InvalidOperationException("A"));
//                                            ~~~~~~~~~~~~~~~
//                                            CA1508: 'obj as Derived2' is always 'null'. Remove or refactor the condition(s) to avoid dead code.
#else
        Derived1 res = obj is Derived1 d ? d : Foo(obj as Derived2 ?? throw new InvalidOperationException("A"));
#endif
    }

    static Derived1 Foo(Derived2 obj)
    {
        // Omitted logic
        throw new InvalidOperationException("B");
    }
}
```

### Expected behavior

No warning.

### Actual behavior

Warning about an `as` conversion that can produce a non-`null` value.

## Additional context

Original code uses `MemberInfo` for `Base` and `PropertyInfo` and `MethodInfo` for `Derived1` and `Derived2`. The `Foo` method is some `GetProperty` helper function.

Also note that the IDE suggests another change that would change the meaning of the code (i.e. throw another exception type)

![image](https://user-images.githubusercontent.com/7324746/190467553-2b1fdc0b-de67-4d65-8a63-72cef7061a7d.png)

so maybe the analysis of type checks using `as` in conjunction with `??` has some undesirable gaps.

**Comment by mavasani** [comment]
Verified this no longer repros on the latest NuGet package: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet8/NuGet/Microsoft.CodeAnalysis.NetAnalyzers/overview/8.0.0-preview.23364.2. Likely fixed with one of the latest CA1508 fixes.
