### ISSUE TITLE
CA1052 is generating warnings for PublicResXFileCodeGenerator-generated code

### ISSUE THREAD

**Issue by flcdrg** [dotnet/roslyn-analyzers#618]
Updating to the latest analyzers (after installing VS 2015 Update 1), and I'm now getting a bunch of warnings from *.Designer.cs files that are being generated by the resx `PublicResXFileCodeGenerator` custom tool.

The classes are already annotated with `GeneratedCodeAttribute` and `CompilerGeneratedAttribute`. I would expect these classes to be ignored by this analyzer.

**Comment by srivatsn** [comment]
Once the workitem to skip reporting results generated code in the compiler is implemented this wouldn't be a problem .That work is tracked by https://github.com/dotnet/roslyn/issues/6998 for the next update.
