### ISSUE TITLE
AnalysisModeSecurity does not allow to setup default severity for all security rules ?

### ISSUE THREAD

**Issue by fforjan** [dotnet/roslyn-analyzers#6188]
### Analyzer

**Diagnostic ID**: [CA5401](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5401): `Symmetric encryption uses non-defaul initialization vector, which could be potentially repeatable`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 6.0.0 (Latest)

### Describe the bug
we've added  <AnalysisModeSecurity>All</AnalysisModeSecurity> to enable all security rules and we want them to be set as error by default so that developers must fix it (or ignore with comment in code).
We try to setup dotnet_analyzer_diagnostic.category-Security.severity = error into a .globalconfig but the error still appears as a warning.

### Steps To Reproduce

clone https://github.com/fforjan/AnalysisModeSecurityVsErrorSeverity and simply do a dotnet build

### Expected behavior

we should have an error for CA5401

### Actual behavior

we  have an warning for CA5401

**Comment by Youssef1313** [comment]
I think this is by-design. [Documentation](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/categories):

> Setting the severity for a category of rules using the `dotnet_analyzer_diagnostic.category-<category>.severity` syntax doesn't apply to rules that are disabled by default. However, starting in .NET 6, you can use the [AnalysisMode<Category>](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysismodecategory) project property to enable all the rules in a category.

CA5401 is disabled by default, so category-based configuration doesn't work.

The documentation page for [CA5401](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5401) and all disabled-by-default rules should be clear about that.

I created a doc issue https://github.com/dotnet/docs/issues/32954
