### ISSUE TITLE
Analyzer to convert Regex usage to [GeneratedRegex]

### ISSUE THREAD

**Issue by timmydo** [dotnet/roslyn-analyzers#6216]
### Describe the problem you are trying to solve

We are trying to reduce JIT compilation at startup in our application. We have over 200 regexes defined in over 100 files. (Those are a sample of random/manually defined ones--we have 10s of thousands source generated in other DLLs). We would like to reduce JIT compilation at startup.

### Describe suggestions on how to achieve the rule

Replace `private static readonly Regex MyRegex = new Regex("abc", RegexOptions.Compiled);` 
with `[GeneratedRegex("abc")] private static partial Regex MyRegex()`. and `this.MyRegex` with `this.MyRegex()`

@EgorBo @stephentoub

**Comment by timmydo** [comment]
looks like dupe of https://github.com/dotnet/runtime/issues/68147

**Comment by stephentoub** [comment]
This analyzer and fixer already exists in .NET 7.
