### ISSUE TITLE
`EnforceExtendedAnalyzerRules` warning even though I specified it

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#6229]
I get

> `warning RS1036: 'YAnalyzers.CSharp.CSharpUseImplicitOrExplicitTypeAnalyzer': A project containing analyzers or source generators should specify the property '<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>'`

I don't see `EnforceExtendedAnalyzerRules` in `YAnalyzers.CSharp.GeneratedMSBuildEditorConfig.editorconfig` even though my project specifies the property.

I have `Microsoft.CodeAnalysis.Analyzers` in language-agnostic analyzers project, and it's flowing transitively to language-specific analyzers project. I guess in this case `.targets` from the doesn't get picked by this project? Should we consider shipping `.targets` and `.props` in `buildTransitive`?

cc @RikkiGibson

**Comment by RikkiGibson** [comment]
> I guess in this case .targets from the doesn't get picked by this project? Should we consider shipping .targets and .props in buildTransitive?

Weird! Does this mean that directly referencing MS.CA.Analyzers from the CSharp project would make the warning go away? In this case it definitely sounds like an msbuild authoring issue we should fix.

**Comment by Youssef1313** [comment]
> > I guess in this case .targets from the doesn't get picked by this project? Should we consider shipping .targets and .props in buildTransitive?
> 
> Weird! Does this mean that directly referencing MS.CA.Analyzers from the CSharp project would make the warning go away? In this case it definitely sounds like an msbuild authoring issue we should fix.

Yes. Explicitly referencing MS.CA.Analyzers fixes it. You can checkout https://github.com/Youssef1313/YAnalyzers/tree/6cafbb9f566025a9d40a67ab5b92ec79eda760d2 for a repro

**Comment by Youssef1313** [comment]
NOTE: For some reason, I see some duplicate keys in `GeneratedMSBuildEditorConfig.editorconfig` after the explicit reference:

![image](https://user-images.githubusercontent.com/31348972/198699071-9ed94df5-8788-44fc-aa6c-022ea5be07bb.png)

**Comment by RikkiGibson** [comment]
@mavasani @jmarolf do you know what change needs to be made here to ensure the msbuild property gets propagated to the generated editorconfig?

**Comment by mavasani** [comment]
I am presuming this issue is not specific to MS.CA.Analyzers but any analyzer package that is being pulled transitively and has an embedded targets/props in its build folder that specifies such CompilerVisible property? I think this is definitely a @jmarolf question on how to get this fixed up.

**Comment by Youssef1313** [comment]
@eerhardt That is my initial thought as well. Though there are concerns with this. https://github.com/dotnet/roslyn-analyzers/pull/6325#discussion_r1053257315

**Comment by Odonno** [comment]
I have the same issue currently. Did anyone find a solution for this?

**Comment by villelaitila** [comment]
Same here. I assume that the fix has not been released yet. (Jan 10, 2023, https://github.com/dotnet/roslyn-analyzers/pull/6325)

**Comment by RikkiGibson** [comment]
Last release to nuget was [a month ago](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers/3.11.0) at time of writing. Please file a new bug if things are not working here, ideally along with a reproducer project.
