### ISSUE TITLE
CA1854: Prefer the IDictionary.TryGetValue  Fixer produces wrong code

### ISSUE THREAD

**Issue by randyshoopman** [dotnet/roslyn-analyzers#6256]
### Analyzer

**Diagnostic ID**: [CA1854](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1854): `CA1854: Prefer the IDictionary.TryGetValue(TKey, out TValue) method`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: [7.0.0-preview1.22518.1](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/7.0.0-preview1.22518.1)

### Describe the bug

The fixer produces incorrect code when you have **two** ContainsKey and indexers together.

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Code fixer trying to fix:

```
if (webHookData.EventData.userVariables.ContainsKey("cid") && webHookData.EventData.userVariables.ContainsKey("emailID"))
                {
                    customerIdentifier = webHookData.EventData.userVariables["cid"];
                    emailId = Convert.ToInt32(webHookData.EventData.userVariables["emailID"]);
                }
```

2. Code after fixer applied to first ContainsKey:
```
if (webHookData.EventData.userVariables.TryGetValue("cid", out string value) && webHookData.EventData.userVariables.ContainsKey("emailID"))
                {
                    customerIdentifier = webHookData.EventData.userVariables["cid"];
                    emailId = Convert.ToInt32(value);
                }
```

3. Error.   The wrong indexer was replaced.   The "cid" indexer should have been replaced by value.

### Expected behavior

Correct code:

```
if (webHookData.EventData.userVariables.TryGetValue("cid", out string value) && webHookData.EventData.userVariables.ContainsKey("emailID"))
                {
                    customerIdentifier = value;
                    emailId = Convert.ToInt32(webHookData.EventData.userVariables["emailID"]);
                }
```

### Actual behavior

See above

## Additional context

None

**Comment by gregbradley** [comment]
Just [reported](https://developercommunity.visualstudio.com/t/Visual-Studio-1741-with-NET-70-autof/10202859) another very similar problem.

**Comment by gregbradley** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/4851

**Comment by Miizukii** [comment]
I took a look at the analyzer and would like to fix it if no one is working on it.
The main problem is that the analyzer only compares if the signature of the contains and indexer match but not if its the same dictionary object or key, so this:
```c#
var key = "key";
var otherKey = "other";
var data = new Dictionary<string, int>();
var otherData = new Dictionary<string, int>();
if (data.ContainsKey(key))
    return otherData[otherKey] + data[key];
```
will currently be replaced with
```c#
if (data.TryGetValue(key, out var value))
    return value + data[key];
```
i would also like to add handling for more than one access per guard and early out / guarded add before use
```c#
//Before
if (!data.ContainsKey(key))
    return; // or data.Add(key, 2);
 DoSomething(data[key]);
 DoSomething(data[key]);

//After
if (!data.TryGetValue(key, out var value))
    return; // or value = 2; data.Add(key, value);
 DoSomething(value);
 DoSomething(value);
```

**Comment by mavasani** [comment]
@Miizukii thanks, feel free to pick it up.
