### ISSUE TITLE
Port FxCop rule CA1026: DefaultParametersShouldNotBeUsed

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#626]
**Title:** Default parameters should not be used

**Description:**

Methods that use default parameters are allowed under the CLS; however, the CLS lets compilers ignore the values that are assigned to these parameters. To maintain the behavior that you want across programming languages, methods that use default parameters should be replaced by method overloads that provide the default parameters.

**Proposed analyzer:** Microsoft.ApiDesignGuidelines

**Notes:**

Replace with a "breaking change" analyzer

**Comment by JiriCepelkaFirstLineSoftware** [comment]
Why is this rule deprecated? Issue https://www.reddit.com/r/csharp/comments/8xz6ez/method_overloading_vs_default_parameters/ no longer exists? Where is more complex information on this?

**Comment by Uzivatel919** [comment]
Why is this rule deprecated? Issue https://www.reddit.com/r/csharp/comments/8xz6ez/method_overloading_vs_default_parameters/ no longer exists? Where is more complex information on this?

**Comment by jjhayworth** [comment]
I would also like more information on this
