### ISSUE TITLE
Port FxCop rule CA1805: DoNotInitializeUnnecessarily

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#627]
**Title:** Do not initialize unnecessarily

**Description:**

The common language runtime initializes all fields to their default values before running the constructor. In most cases, initializing a field to its default value in a constructor is redundant, which degrades performance and adds to maintenance costs. One case where it is not redundant occurs when the constructor calls another constructor of the same class or a base class constructor and that constructor initializes the field to a non-default value. In this case, changing the value of the field back to its default value can be appropriate.

**Dependency:** None

**Notes:**

**Comment by lgolding** [comment]
This is no longer necessary (and in fact, it hasn't shipped since Dev10, per @michaelcfanning), because the JITter now eliminates redundant initializations for reference and primitive value types (and sometimes but not always for user-defined value types).

**Comment by xtqqczze** [comment]
This was added in https://github.com/dotnet/roslyn-analyzers/pull/3772, label `Resolution-Won't Fix` can be removed.
