### ISSUE TITLE
Microsoft.CodeAnalysis.NetAnalyzers branded confusingly in RTM .NET SDK

### ISSUE THREAD

**Issue by mmitche** [dotnet/roslyn-analyzers#6279]
The analzyers in the SDK appear continually branded as "preview1" on both NuGet.org and within the SDK version numbers: https://github.com/dotnet/sdk/blob/release/7.0.1xx/eng/Versions.props#L105

https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/7.0.0-preview1.22518.1

It makes it somewhat difficult to tell whether the version in the SDK is out of date. I suggest:
- Removing the "1" from the version label. If it's always going to be 1, then there is no reason for it to be there.
- For versions flowing into the servicing branches, change the suffix to "servicing".

**Comment by Youssef1313** [comment]
@mmitche The release of 7.0.0 stable on NuGet got delayed, but it happened today. Does updating the version in https://github.com/dotnet/sdk/pull/29463 addresses this?

**Comment by mmitche** [comment]
Yep.
