### ISSUE TITLE
Add RSxxxx diagnostic for compilation end diagnostic descriptors without CompilationEnd custom tag

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#6282]
Add a new RSxxxx diagnostic to our MS.CA.Analyzers package to flag descriptors being used to report a diagnostic that do not have the CompilationEnd custom tag: https://github.com/dotnet/roslyn/blob/440b6fc370f0ddcea68b445e183f1383c0d1bc6e/src/Compilers/Core/Portable/Diagnostic/WellKnownDiagnosticTags.cs#L56 custom tag 

See https://github.com/dotnet/roslyn/issues/65304#issuecomment-1309882140 for details

**Comment by mavasani** [comment]
@Youssef1313 Are you interested in taking this up? Otherwise, I can work on it. The corresponding user facing issue was again reported by a customer at https://developercommunity.visualstudio.com/t/Error-List-warnings-disappears-when-file/10235352

**Comment by Youssef1313** [comment]
@mavasani Sorry, I won't be able for now as my exams start tomorrow :(
