### ISSUE TITLE
Port FxCop rule CA5351: DoNotUseBrokenCryptographicAlgorithms

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#634]
**Title:** Do Not Use Broken Cryptographic Algorithms

**Description:**

An attack making it computationally feasible to break this algorithm exists. This allows attackers to break the cryptographic guarantees it is designed to provide. Depending on the type and application of this cryptographic algorithm, this may allow attackers to read enciphered messages, tamper with enciphered? messages, forge digital signatures, tamper with hashed content, or otherwise compromise any cryptosystem based on this algorithm. Replace encryption uses with the AES algorithm (AES-256, AES-192 and AES-128 are acceptable) with a key length greater than or equal to 128 bits. Replace hashing uses with a hashing function in the SHA-2 family, such as SHA512, SHA384, or SHA256. Replace digital signature uses with RSA with a key length greater than or equal to 2048-bits, or ECDSA with a key length greater than or equal to 256 bits.

**Proposed analyzer:** System.Security.Cryptography.Algorithms

**Notes:**

**Comment by srivatsn** [comment]
This has been implemented.
