### ISSUE TITLE
Constant expected analyzer (CA1856) was approved as "Info" but implemented as **Error**

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#6342]
https://github.com/dotnet/roslyn-analyzers/blob/fde49330aa324d488fe6f02a5d7cd5c4870d2534/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/ConstantExpectedAnalyzer.cs#L30

Implemented in https://github.com/dotnet/roslyn-analyzers/pull/5766

Runtime issue: https://github.com/dotnet/runtime/issues/33771

> **Severity:** Info

Was that intended, or just a mistake?

**Comment by Youssef1313** [comment]
@buyaa-n Can you please take a look?

**Comment by buyaa-n** [comment]
> > Severity: Info
> 
> Was that intended, or just a mistake?

That is the proposed severity, by the [approved API ](https://github.com/dotnet/runtime/issues/33771#issuecomment-970633087) it is `Error`:

> - Category: Performance
> - The default diagnostic for passing a non-constant value: Warning
> - The default diagnostic for a constant that's out of range: Warning
> - The default diagnostic for a constant that's out of range by composition with another ConstantExpected attribute: Warning
> - The default diagnostic for passing min/max that make no sense (wrong type, inverted, is a reference type, etc): Error

**Comment by Youssef1313** [comment]
@buyaa-n Thanks for clarifying!
