### ISSUE TITLE
Make sure `DoNotUseInsecureXSLTScriptExecution` handles target-typed new

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#6394]
Also this one may have the same bug:

https://github.com/dotnet/roslyn-analyzers/blob/7c544ae66c44f1705ef583b112def4db52c0179a/src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureXSLTScriptExecution.cs#L230

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn-analyzers/pull/5831#pullrequestreview-868985275_

**Comment by kandicst** [comment]
@Youssef1313 I think I have figured how to fix this one. 

Only issue is that I'm getting a diagnostic `CS8370: Feature 'target-typed object creation' is not available in C# 7.3. Please use language version 9.0 or greater.`  when using target-typed new in a unit test. Any idea how to disable this?

**Comment by Youssef1313** [comment]
@kandicst Great! You can set the language version like in this test:

https://github.com/dotnet/roslyn-analyzers/blob/253bcd3395e205895c4495558a56da86fafca4b5/src/Roslyn.Diagnostics.Analyzers/UnitTests/DoNotCopyValueTests.cs#L19-L39
