### ISSUE TITLE
CA1801 is missing in configuration files

### ISSUE THREAD

**Issue by avivanoff** [dotnet/roslyn-analyzers#6399]
### Analyzer

**Diagnostic ID**: [CA1801](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801): `Review unused parameters`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 7.0.0 (Latest)

### Describe the bug

CA1801 is missing in configuration files in the `rulesets` and` editorconfig` folders.

### Steps To Reproduce

1. Install Microsoft.CodeAnalysis.NetAnalyzers version 7.0.0 into a project.
2. Check the configuration files in `rulesets` and` editorconfig` folders in NuGet local cache.

### Expected behavior

CA1801 should be defined in the configuration files.

### Actual behavior

 None of them configuration files have CA1801 defined.

**Comment by Youssef1313** [comment]
CA1801 was [removed and deprecated in favor of IDE0060](https://github.com/dotnet/roslyn-analyzers/pull/4535). This is documented in [CA1801](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801).
