### ISSUE TITLE
Exclude partial method signatures from CA1859 warnings

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#6414]
### Analyzer

**Diagnostic ID**: CA1589

### Analyzer source

https://github.com/dotnet/roslyn-analyzers/commit/6ae2683c5033dfde0b73d4e73b372f00ca6ceacd

### Describe the bug

Partial methods are often used as mechanism for implementing platform abstraction layers (PAL).  For example, we might have a central file Foo.cs that's compiled into all builds and that calls a private method `private static partial IBar Create();`, and then a Foo.Windows.cs, a Foo.Linux.cs, a Foo.Apple.cs, etc., each of which provides a different implementation of IBar specific to that OS.  The return type of the partial method definition and declaration must match exactly, but CA1589 will fire for each build recommending that the partial definition replace the return type, and then that causes the partial declaration to have a mismatch of the return type and cause errors.

Partial methods are also often used as a mechanism for keeping the consumer separated from the producer of a function, and a similar situation can arise there.

We should exclude diagnostics on partial method signatures from CA1859.

cc: @geeknoid, @buyaa-n

**Comment by Youssef1313** [comment]
Closing as fixed per https://github.com/dotnet/roslyn-analyzers/pull/6418#issuecomment-1385520293
