### ISSUE TITLE
InternalsVisibleTo disables CA1852

### ISSUE THREAD

**Issue by siewers** [dotnet/roslyn-analyzers#6438]
### Analyzer

**Diagnostic ID**: [CA1852](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1852)

### Describe the improvement

We have a lot of projects that have internals visible to the test projects. Currently, adding `InternalsVisibleTo` disables _CA1852: Seal internal types_ because it cannot know if the internal types are derived from in the other projects, which makes sense.
We would like to have the analyzer enabled in our case, where we only expose internals to our own projects.

### Describe suggestions on how to achieve the rule

When we know exactly what projects we expose our internal types to, it would be great if we had the option to ignore `InternalsVisibleTo` completely. 

https://github.com/dotnet/roslyn-analyzers/blob/e43952404107333565f1f603fc015e3d7abf9845/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypes.cs#L42

If we make a change that is only affecting our own test projects, we will know by running the tests. We can then manually disable the warning on the affected type.

An option on the analyzer like `dotnet_diagnostic.CA1852.ignore_internals_visible_to = true` could make the analyzer run on all types and allow us to handle the warnings case-by-case.

### Additional context

I would argue that projects that expose their internal types to other projects _should_ know exactly how those types are being used. If not, the type should not be internal in the first place and be made public instead.
The default behavior is most likely fine and a good safeguard, but I believe most projects that have `InternalsVisibleTo` is exactly test projects, where you have control over the consumers.
There are situations where using mocking libraries like NSubstitute requires internals made available to `DynamicProxyGenAssembly2`. However, in such cases I believe it's a code smell and suppressing the warning would be fine.

**Comment by Youssef1313** [comment]
I believe this is tracked by https://github.com/dotnet/roslyn-analyzers/issues/5973

**Comment by mavasani** [comment]
Yes, we should add an option for all IVT based rules. @Youssef1313 would you like to pick up that feature work?

**Comment by Youssef1313** [comment]
I can take a look if a design is approved.
