### ISSUE TITLE
CA1859 incorrectly recommends changing return type when a return doesn't work with it

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#6440]
### Analyzer

**Diagnostic ID**: [CA1859](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Change return type for improved performance`

### Analyzer source

https://github.com/dotnet/roslyn-analyzers/commit/c7812f1cfd01307cfb03ee4db98269e6eafe670d

### Describe the bug

Multiple return statements of different types in the method, and the analyzer recommends changing the return type of the method to one of them even though some aren't compatible.

### Steps To Reproduce

```C#
[Fact]
public static async Task Repro()
{
    const string Source = @"
        using System;

        class C
        {
            private object Foo(int i)
            {
                C c = new C();
                if (i == 0)
                {
                    return false;
                }
                return c;
            }
        }
        ";

    await TestCSAsync(Source);
}
```

### Expected behavior

No warning.

### Actual behavior

```
    Diagnostics:
    // /0/Test0.cs(6,36): info CA1859: Change return type of method 'Foo' from 'object' to 'C' for improved performance
    VerifyCS.Diagnostic(UseConcreteTypeAnalyzer.CA1859).WithSpan(6, 36, 6, 39).WithArguments("Foo", "object", "C"),
    
    
    Assert.Equal() Failure
    Expected: 0
    Actual:   1
```

cc: @geeknoid, @buyaa-n

**Comment by julealgon** [comment]
@stephentoub can you fix the link in the issue description there? It is pointing to a completely different CA article.

**Comment by stephentoub** [comment]
I removed the link.
