### ISSUE TITLE
CA1859 reported incorrectly when method parameter is assigned

### ISSUE THREAD

**Issue by marek-safar** [dotnet/roslyn-analyzers#6451]
### Analyzer

CA1859

### Analyzer source

https://github.com/dotnet/runtime/blob/8798c0459a36463bf3355f1059ad97fdd890c99e/eng/Versions.props#L40

### Describe the bug

It seems like the analyzer ignores assignments to parameter when suggesting more specific type for it.

### Steps To Reproduce

```c#
class Foo
{
		static void Main ()
		{
			Test(typeof(Foo));
		}

		private static void Test(object elementType)
		{
			elementType = elementType.ToString();
		}
}
```

### Expected behavior

No CA1859 reported

### Actual behavior

```
CA1859: Change type of parameter 'elementType' from 'object' to 'System.Type' for improved performance 
```

**Comment by stephentoub** [comment]
cc: @geeknoid
