### ISSUE TITLE
C# no warning for assignment of property to itself 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6482]
Given the following code

        public CAccountContract(CAccount account, DateTime signDate, DateTime inceptionDate, decimal registrationFee)
        {
            Requires.That(account != null, &quot;account is required, to create contract!&quot;);
            Requires.That(inceptionDate &gt; signDate, &quot;inception date must be &gt;= sign date, to create contract!&quot;);
            Requires.That(signDate &gt;= new DateTime(2019, 1, 1), &quot;sign date must be &gt;= 2019-01-01, to create contract!&quot;);
            Requires.That(registrationFee &gt; 0m, &quot;registration fee must be &gt;= 0, to create contract!&quot;);

            Account = account;
            SignDate = signDate;
            InceptionDate = InceptionDate;
            RegistrationFee = registrationFee;
        }

It is not obvious that there is an error in this code. The compiler should have warned that the second last statement was asigning a variable to itself, and perhaps also warned that the variable passed to the function was not used.

Specifically, the error here is that

       InceptionDate = InceptionDate;

should actually read

            InceptionDate = inceptionDate;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/420322/c-no-warning-for-assignment-of-property-to-itself.html
VSTS ticketId: 761249_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by mavasani** [comment]
We already have https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2245 for this. Don’t you see an IDE suggestion/message for this? The rule is not warning by default.

**Comment by mavasani** [comment]
Closing based on the last comment
