### ISSUE TITLE
After upgrading VS to 17.5.0 I'm getting CA1825 warnings in attributes

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/roslyn-analyzers#6500]
### Analyzer

**Diagnostic ID**: [CA1825](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825): `Avoid zero-length array allocations`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 6 SDK](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.406](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug
Updated my installation to 17.5.0 then restarted my PC, after that I compiled my solution and saw CA1855 warnings on the Controllers in the Produce attributes:
`[Produces(MediaTypeNames.Application.Json)]`

### Expected behavior
No warnings

### Actual behavior
CA1825 warnings on attributes.

## Additional context
Building the solution with the CLI using `dotnet build` builds correctly.
I'm targeting net6 using the lang version 10.

**Comment by yaakov-h** [comment]
Me too, I'm seeing this in my Analyzers projects when declaring `[DiagnosticAnalyzer(LanguageNames.CSharp)]`. How ironic.

**Comment by yaakov-h** [comment]
hmm, it looks like this should have been fixed in #6114, and the Analyzer already bails out if the array allocation is in an attribute or is a compiler-generated `params` array, and all three examples above meet both criteria.

@333fred is this perhaps a Roslyn issue rather than an Analyzer bug?

**Comment by 333fred** [comment]
See the note on false positives in https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825#when-to-suppress-warnings.

**Comment by 333fred** [comment]
You'll need to either upgrade the version of analyzers you are using, or suppress these false positives.
