### ISSUE TITLE
Port FxCop rule CA1014: MarkAssembliesWithClsCompliant

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#652]
**Title:** Mark assemblies with CLSCompliant

**Description:**

The Common Language Specification (CLS) defines naming restrictions, data types, and rules to which assemblies must conform if they will be used across programming languages. Good design dictates that all assemblies explicitly indicate CLS compliance by using CLSCompliantAttribute . If this attribute is not present on an assembly, the assembly is not compliant.

**Proposed analyzer:** Microsoft.ApiDesignGuidelines

**Notes:**

**Comment by sharwell** [comment]
@lgolding this indicates fixed, but I don't see a PR where it was fixed and it isn't linked here.

**Comment by mavasani** [comment]
@sharwell - the analyzer is implemented [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MarkAssembliesWithAttributesDiagnosticAnalyzer.cs#L11)
