### ISSUE TITLE
Ban of Attribute Constructor Not Enforced on Attribute Declarations

### ISSUE THREAD

**Issue by WalkerCodeRanger** [dotnet/roslyn-analyzers#6524]
### Analyzer

**Diagnostic ID**: [RS0030](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md): `The symbol 'X' is banned in this project`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.BannedApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.BannedApiAnalyzers)

**Version**: 3.34 (Latest)

### Describe the bug

If you ban a specific constructor of an attribute, the banned API analyzer does not report a use of the attribute constructor to declare an attribute as a banned operation (e.g. `[Ignore()]`). It will report for constructing the attribute in code (e.g. `_ = new IgnoreAttribute()`).

### Steps To Reproduce

1. Have an attribute constructor you want to ban. In this case, I have referenced the `MSTest.TestFramework` NuGet package and am using `Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute`
2. Ban the specific constructor. In this example `M:Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute.#ctor(); Provide a reason for ignoring this test.`
3. Apply this attribute to a method using the given constructor. In this example `[Ignore()]` or `[Ignore]`

### Expected behavior

RS0030 should be reported on the attribute declaration (e.g. `[Ignore()]`) because it is effectively a call to the constructor. Though I do understand attributes work differently than regular constructor calls.

### Actual behavior

RS0030 is not reported.

## Additional context

The ban will apply to calls of the attribute constructor inside of code (e.g. `_ = new IgnoreAttribute();`). If you ban the whole type (e.g. `T:Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute`) then RS0030 will be reported on the attribute declaration. However, in this case, I want to ban only a specific constructor. The use of other constructors is required.

**Comment by mpidash** [comment]
There are two changes that need to be made to allow banning of specific attribute constructors.

Adapt `ShouldAnalyzeAttributes`
---

This method decides when attributes should be analyzed.
The following must also check the `ContainerName` (`SymbolName` contains `ctor` in this case):

https://github.com/dotnet/roslyn-analyzers/blob/45879f0b46557886b8d553d121a81866f67ce08a/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzerBase.cs#L183-L184

And here we must allow declarations starting with `M` and change the `entry.Symbols.Any` check:

https://github.com/dotnet/roslyn-analyzers/blob/45879f0b46557886b8d553d121a81866f67ce08a/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/Core/SymbolIsBannedAnalyzerBase.cs#L188-L189

Adapt `VerifyAttributes`
---

This method should also check the attribute constructor against the banned symbols.

---

I would like to contribute a PR with the proposed changes.
