### ISSUE TITLE
Port FxCop rule CA1018: MarkAttributesWithAttributeUsage

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#655]
**Title:** Mark attributes with AttributeUsageAttribute

**Description:**

When you define a custom attribute, mark it by using AttributeUsageAttribute to indicate where in the source code the custom attribute can be applied. The meaning and intended usage of an attribute will determine its valid locations in code.

**Dependency:** None

**Notes:**

**Comment by mavasani** [comment]
This needs a fixer.

**Comment by Evangelink** [comment]
Shall we default to `AttributeTargets.All` for the `validOn` ctor argument?
