### ISSUE TITLE
Rule for async methods name

### ISSUE THREAD

**Issue by BrunoRM** [dotnet/roslyn-analyzers#6551]
### Describe the problem you are trying to solve
I could not find any rule that validates cases in which if you are returning a `Task` or `Task<T>` from a method, this method name must end with Async suffix.

### Describe suggestions on how to achieve the rule
Validates that the names of the methods returning `Task` or `Task<T>` ends with Async suffix.

**Comment by mavasani** [comment]
This is already implemented as https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD200.md. You should reference that NuGet package. Note that even though the analyzer package has `VS` in its name, there is nothing VS specific, it runs fine on all hosts that the compiler and analyzers can run in, including command line builds.

Note that we do have plans to port some of these Async/Threading related analyzers over to the .NET SDK, but that work isn't funded yet.
