### ISSUE TITLE
IDE0251 error in error list has no description

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6552]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/IDE0251-error-in-error-list-has-no-descr/10312916)._

---
[severity:It bothers me. A fix would be nice]
I just opened my project and noticed in the Error List window I have two IDE0251 errors with no descriptions. If I click to go to the location of the error, I see code is fine. Also, the link to the documentation around that error seems to be broken, I get a 404 on it (https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0251)

---
#### Feedback Bot on 3/16/2023, 05:46 PM: 

(private comment, text removed)
#### Feedback Bot on 3/17/2023, 06:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I think this was unintentionally moved to this repo. It belongs to dotnet/roslyn.

**Comment by DanTravison** [comment]
Is there a link to the issue in dotnet/Roslyn? I can't find it.

**Comment by Youssef1313** [comment]
@DanTravison Apparently this was forgotten to be moved. I opened https://github.com/dotnet/roslyn/issues/67949 and will close this.
