### ISSUE TITLE
CA1014 is not reported when explicitly enabled

### ISSUE THREAD

**Issue by drieseng** [dotnet/roslyn-analyzers#6563]
### Analyzer

**CA1014**: [CA1014](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1014): `Mark assemblies with CLSCompliantAttribute`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 8.0.0-preview1.23121.1

### Describe the bug

When a given assembly is not marked with a **CLSCompliantAttribute**, **CA1014**¨should be reported when this rule is enabled.

I'm aware that this rule is disabled by default which is why we explicitly enable the rule in .editorconfig:

`dotnet_diagnostic.CA1014.severity = error`

Visual Studio shows the rule as enable with severity error:

![image](https://user-images.githubusercontent.com/312863/229272091-5037b002-f7e2-47e8-8ec9-3fe6a27e8391.png)

I verified that the produced assembly indeed does not have a CLSCompliantAttribute.

Other diagnostics are reported just fine.

**Comment by mavasani** [comment]
CA1014 is a project level diagnostic, that cannot be enabled via editorconfig. You need to enable in a ruleset or globalconfig file: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig

**Comment by mavasani** [comment]
Please re-open if the above does not answer your query.
