### ISSUE TITLE
Microsoft.CodeAnalysis.ResxSourceGenerator generates nullable string properties, causing frequent warnings

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-analyzers#6577]
### Analyzer

Microsoft.CodeAnalysis.ResxSourceGenerator 3.3.3-beta1.21417.2

### Describe the bug

The generated static string property claims to return a nullable string, causing CS8604 warnings whenever passing the string to a function that requires a non-null string.

```cs
internal static string? @Argument_NotEnum => GetResourceString("Argument_NotEnum");
```

### Expected behavior

I want to see a non-nullable string property.

### Actual behavior

A nullable string property, leading to a CS8604 warning when I use the string in a string.Format call like this:
```cs
throw new ArgumentException(string.Format(Strings.Argument_EmptyArray, parameterName), parameterName);
```

## Additional context

During code generation, the source generator _knows_ that the string exists in the resx file, so why shouldn't it indicate in the generated API that the string will not be null at runtime?
Yes, at runtime it could be pulling strings from a satellite assembly instead, but if the string isn't found there, the neutral fallback resource will be used instead, so it shouldn't ever be null.

**Comment by sharwell** [comment]
> Yes, at runtime it could be pulling strings from a satellite assembly instead, but if the string isn't found there, the neutral fallback resource will be used instead, so it shouldn't ever be null.

Isn't it possible to configure the build so the neutral language fallback is also in a satellite assembly?

**Comment by sharwell** [comment]
Looks like a failure to find the satellite assembly would result in an exception and not just return null values. I'll need confirmation from the runtime team but it might be possible to make these all return non-null.
