### ISSUE TITLE
Port FxCop rule CA1033: InterfaceMethodsShouldBeCallableByChildTypes

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#659]
**Title:** Interface methods should be callable by child types

**Description:**

An unsealed externally visible type provides an explicit method implementation of a public interface and does not provide an alternative externally visible method that has the same name.

**Dependency:** None

**Notes:**

**Comment by srivatsn** [comment]
Need to implement a fixer for this rule.
