### ISSUE TITLE
Analyzers should not try to fix non-local diagnostics

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn-analyzers#6598]
>              Can we file an issue to track fixing all analyzers reporting non-local diagnostics?
>
> _Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/6560#discussion_r1172789018_

**Comment by mavasani** [comment]
FYI: EnumsShouldHaveZeroValueAnalyzer is currently being affected by https://github.com/dotnet/roslyn/issues/68654
