### ISSUE TITLE
Port FxCop rule CA1053: StaticHolderTypesShouldNotHaveConstructors

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#662]
**Title:** Static holder types should not have constructors

**Description:**

A public or nested public type declares only static members and has a public or protected default constructor. The constructor is unnecessary because calling static members does not require an instance of the type. The string overload should call the uniform resource identifier (URI) overload by using the string argument for safety and security.

**Proposed analyzer:** Microsoft.ApiDesignGuidelines

**Notes:**

**Comment by gewarren** [comment]
@lgolding @mavasani This rule shows as "Fixed" but I don't see it here: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md Should this be "won't fix"?

**Comment by mavasani** [comment]
@gewarren - Larry added a detailed comment explaining this here: https://github.com/dotnet/roslyn-analyzers/blob/f611403633e62721711bb4c04b699f7c8c75937b/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/StaticHolderTypes.cs#L17. Seems like CA1052 and CA1053 have been combined.
