### ISSUE TITLE
Can't build the repo: Unable to find file Microsoft.CodeAnalysis.CSharp.PerformanceSensitiveAnalyzers.CodeFixes.GeneratedMSBuildEditorConfig.editorconfig

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/roslyn-analyzers#6632]
Clean clone of the repo. Latest bits in main (71f45f3d826c7597cdbcfe94c220c77317413e3f). I run `build.cmd` and I get this error:

```
C:\.tools\.nuget\packages\microsoft.net.compilers.toolset\4.5.0\tasks\net472\Microsoft.Managed.Core.targets(190,5): error : Could not find a part of the path 'C:\Users\calope\source\repos\roslyn-analyzers\artifacts\obj\Microsoft.CodeAnalysis.CShar
p.PerformanceSensitiveAnalyzers.CodeFixes\Debug\netstandard2.0\Microsoft.CodeAnalysis.CSharp.PerformanceSensitiveAnalyzers.CodeFixes.GeneratedMSBuildEditorConfig.editorconfig'. [C:\Users\calope\source\repos\roslyn-analyzers\src\PerformanceSensitiv
eAnalyzers\CSharp\CodeFixes\Microsoft.CodeAnalysis.CSharp.PerformanceSensitiveAnalyzers.CodeFixes.csproj]
    0 Warning(s)
    1 Error(s)
```

The attached msbuild.binlog ([msbuild.zip](https://github.com/dotnet/roslyn-analyzers/files/11493028/msbuild.zip)) shows the error comes from C:\.tools\.nuget\packages\microsoft.net.compilers.toolset\4.5.0\tasks\net472\Microsoft.Managed.Core.targets :

```xml
    <!-- Transform the collected properties and items into an editor config file -->
    <GenerateMSBuildEditorConfig
      PropertyItems="@(_GeneratedEditorConfigProperty)"
      MetadataItems="@(_GeneratedEditorConfigMetadata)"
      FileName="$(GeneratedMSBuildEditorConfigFile)">
    </GenerateMSBuildEditorConfig>
```

**Comment by carlossanlop** [comment]
Found the root cause: Needed to enable long paths. They are not enabled by default.

It took me way too long to determine the root cause. The error isn't helpful. Here is a related issue: https://github.com/dotnet/msbuild/issues/8123

For anyone seeing this issue, there are two ways to enable long paths in Win10/Win11:

regedit
- Go to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
- Set `LongPathsEnabled ` to `true`.

gpedit
- Go to `Local Group Policy > Computer Configuration > Administrative Templates > System > Filesystem`
- Click on `Enable Win32 long paths` and enable it.

You might have to restart afterwards.

**Comment by astw** [comment]
I modified on regedit,  and restart the computer, the issue is still there.
