### ISSUE TITLE
Set ConfigureAwait(bool) on IAsyncEnumerators in await foreach loops

### ISSUE THREAD

**Issue by ScottRosenberg2** [dotnet/roslyn-analyzers#6652]
### Describe the problem you are trying to solve
Currently CA2007 requires ConfigureAwait(bool) to be set on all instances of awaiting a task.
It does not currently catch cases where you have awaited an IAsyncEnumerator in an await foreach loop.
If you write:
`await foreach (var x in someIAsyncEnumerator) { }`
I'd like to see it suggest:
`await foreach (var x in someIAsyncEnumerator.ConfigureAwait(someBool)) { }`

Currently: It does not recognize missing ConfigureAwait on IAsyncEnumerators

### Describe suggestions on how to achieve the rule
Create a rule similar to CA2007, or modify CA2007 to correctly identify `await foreach IAsyncEnumerators`

### Additional context

Not having this rule lead to having deadlocks in our code, until manually fixed.

**Comment by mavasani** [comment]
> Create a rule similar to CA2007, or modify CA2007 to correctly identify await foreach IAsyncEnumerators

@buyaa-n @jeffhandley @stephentoub

**Comment by stephentoub** [comment]
I think we should just update CA2007 for this.  It's the same case, it's just that the underlying awaits are hidden behind code gen and so you need to lift the ConfigureAwait to be specified in a different location.
