### ISSUE TITLE
False Positive for CA1802 when using readonly with enum Flags

### ISSUE THREAD

**Issue by TheBigNeo** [dotnet/roslyn-analyzers#6681]
### Analyzer

**Diagnostic ID**: [CA1802](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1802): `Use Literals Where Appropriate`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 7.0.1

### Describe the bug

CA1802: Field 'BindingFlags' is declared as 'readonly' but is initialized with a constant value. Mark this field as 'const' instead.
But this does not work for `enum`

### Steps To Reproduce

* New class
* Add `using System.Reflection;`
* Add `private static readonly BindingFlags BindingFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;`
* See error: CA1802: Field 'BindingFlags' is declared as 'readonly' but is initialized with a constant value. Mark this field as 'const' instead.

### Expected behavior
No Error/Warning for CA1802

### Actual behavior
CA1802: Field 'BindingFlags' is declared as 'readonly' but is initialized with a constant value. Mark this field as 'const' instead.

**Comment by CollinAlpert** [comment]
This is an edge case, since `const` does work for enums and also flag enums. In your case, the field's name matches the enum's name and that is when `const` cannot be used.
