### ISSUE TITLE
CA5395 not working

### ISSUE THREAD

**Issue by ghosttie** [dotnet/roslyn-analyzers#6699]
### Analyzer

**Diagnostic ID**: [CA5395](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/CA5395): `Miss HttpVerb attribute for action methods`

### Analyzer source

**SDK**: Built-in CA analyzers in .NET 7 SDK or later

**Version**: SDK 7.0.400-preview.23225.8

### Describe the bug

CA5395 doesn't trigger when an action method on a controller is missing its HttpVerb attribute.

### Steps To Reproduce

1. Create an Asp.NET Core MVC Controller
2. Add action method with no HttpVerb attribute

### Expected behavior

CA5395 should identify the method as a violation.

### Actual behavior

Nothing happens.

**Comment by Youssef1313** [comment]
- Did you enable the analyzer explicitly via `dotnet_diagnostic.CA5395.severity = warning`?
- Did you do an explicit build?

**Comment by ghosttie** [comment]
Yes I added `dotnet_diagnostic.CA5395.severity = error` to `.editorconfig` and did a `Run Code Analysis` build

**Comment by ghosttie** [comment]
Also the message is bad English, but that's not as important as it just not working :)

**Comment by mavasani** [comment]
> Run Code Analysis

I am not able to reproduce this:

![CA5395](https://github.com/dotnet/roslyn-analyzers/assets/10605811/7db08084-a52f-4cb1-853e-7abea3de8840)
