### ISSUE TITLE
Lots of allocations of state machine of `GetDisposableFieldCreations`

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/roslyn-analyzers#6734]
![image](https://github.com/dotnet/roslyn-analyzers/assets/31348972/dde20cbc-bae1-4214-9e78-7dca2e1de794)

![image](https://github.com/dotnet/roslyn-analyzers/assets/31348972/cc93bf67-6d4f-4a3b-87ca-3ddc396063b4)

**Comment by mavasani** [comment]
@CollinAlpert @Youssef1313 Do we want to still keep this issue open given that #6741 has been merged?

**Comment by Youssef1313** [comment]
No, this can be closed given the performance concern is addressed.
I can file new issues if I found any more performance issues.
