### ISSUE TITLE
CA1305 producing false positives

### ISSUE THREAD

**Issue by javiercn** [dotnet/roslyn-analyzers#6745]
### Analyzer

**Diagnostic ID**: [CA1305](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2013): `Do not use ReferenceEquals with value types`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](8.0.100-preview.7.23356.2)

**Version**: [SDK 5.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

_OR_

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.3 (Latest)

### Describe the bug

The analyzer seems to be producing false positives.
![Image](https://user-images.githubusercontent.com/6995051/251519144-02ff1d75-68b4-4c6c-ace3-c0018c8d6559.png)

### Steps To Reproduce

* Clone the branch from https://github.com/dotnet/aspnetcore/pull/49034
* run eng\build.cmd
* observe the errors.

### Expected behavior

Does not produce false positives.

### Actual behavior

The rule produces some false positives.

**Comment by javiercn** [comment]
This is blocking our SDK update

**Comment by mavasani** [comment]
Tag @CollinAlpert

**Comment by CollinAlpert** [comment]
I'll take a look now.
