### ISSUE TITLE
CA1822 is incorreclty reported for classes with primary constructors

### ISSUE THREAD

**Issue by hankovich** [dotnet/roslyn-analyzers#6786]
### Analyzer

**Diagnostic ID**: CA1822 Mark members as static

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 8.0.0-preview1.23165.1

### Steps To Reproduce

```c#
class A(int i)
{
    void Foo() // <- says Foo can be marked as static
    {
        Console.WriteLine(i); // it uses i, to it can't
    }
}
```

**Comment by mavasani** [comment]
This was recently fixed by @CyrusNajmabadi
