### ISSUE TITLE
Suppress CA1823 and related analyzers in [InlineArray] types

### ISSUE THREAD

**Issue by stephentoub** [dotnet/roslyn-analyzers#6789]
.NET 8 introduces the new InlineArrayAttribute, which is put onto a type to indicate that its sole field should be replicated the specified number of times.  C# then provides automatic helpers for indexing into these types and getting at their data as spans.  As a result, the field declared inside the type isn't actually referenced by the developer, and so various analyzers that warn about that end up firing false positives, e.g. CA1823 "Avoid unused private fields".  Such analyzers should skip types marked as InlineArrayAttribute.

**Comment by sharwell** [comment]
I'm almost done with this change.
