### ISSUE TITLE
CA1708 does not always work on `file` scoped types

### ISSUE THREAD

**Issue by RenderMichael** [dotnet/roslyn-analyzers#6800]
### Analyzer

**Diagnostic ID**: [CA1708](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1708): `Identifiers should differ by more than case`

### Analyzer source

**SDK**: .NET 8 preview 5

### Describe the bug

I use `file`-scoped extension classes, often with names like `Extensions`. When I have more than 1 in the same namespace, this analyzer fires.

Error message is `Names of 'Types' and 'MyNamespace.Extensions, MyNamespace.Extensions, MyNamespace.Extensions should differ by more than case`

### Steps To Reproduce

1. Use Visual Studio (17.7 Preview 4.0).
2. Make two `file`-scoped classes with the same name and namespace.
3. See error appear.
4. Note the associated file is the .csproj file. 
5. Navigate to the associated file, observe the warning disappear.

### Expected behavior
No warning.
### Actual behavior
Warning

**Comment by svick** [comment]
This looks like a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6514.

**Comment by RenderMichael** [comment]
Thanks, glad the issue is filed. I’ll close this as duplicate
