### ISSUE TITLE
IndexOutOfRangeException in UseConcreteTypeAnalyzer (CA1859)

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#6852]
### Analyzer

**Diagnostic ID**: [CA1859](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1859): `Use concrete types when possible for improved performance`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 8 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: `SDK 8.0.0-preview.23364.2`

### AD0001 analyzer exception diagnostic

Exception seen while working on Roslyn.sln

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.Workspaces
IOperation: Invocation
SyntaxTree: C:\roslyn\src\Workspaces\Core\Portable\Storage\SQLite\v2\SQLitePersistentStorage_Threading.cs
SyntaxNode: vt.Item1() [InvocationExpressionSyntax]@[3489..3499) (59,16)-(59,26)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Analyzer.Utilities.AnalyzerOptionsExtensions.TryGetSyntaxTreeForOption(ISymbol symbol, SyntaxTree& tree)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.<>c__DisplayClass9_1.<Initialize>b__4(ISymbol symbol)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.Collector.HandleInvocation(IInvocationOperation op)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: CA1859	Microsoft.CodeAnalysis.Workspaces (netstandard2.0)	C:\roslyn\src\Workspaces\Core\Portable\Microsoft.CodeAnalysis.Workspaces.csproj	1	Active

```

**Comment by geeknoid** [comment]
This looks like a bug in Roslyn:

The HandleInvocation function [here](https://github.com/dotnet/roslyn-analyzers/blob/755a4f888d64fc7c0f2802adca731f301a53283d/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs#L90) calls the CanUpgrade function ([here](https://github.com/dotnet/roslyn-analyzers/blob/755a4f888d64fc7c0f2802adca731f301a53283d/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs#L631) or [here](https://github.com/dotnet/roslyn-analyzers/blob/755a4f888d64fc7c0f2802adca731f301a53283d/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs#L648) or [here](https://github.com/dotnet/roslyn-analyzers/blob/755a4f888d64fc7c0f2802adca731f301a53283d/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.Collector.cs#L654)). This invokes the delegate created [here](https://github.com/dotnet/roslyn-analyzers/blob/755a4f888d64fc7c0f2802adca731f301a53283d/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseConcreteTypeAnalyzer.cs#L137). This finally ends up calling MatchesConfiguredVisibility in the infrastructure, all with straightforward arguments. Then inside this function eventually calls TryGetSyntaxTreeForOption which is where things head south and trigger the array-of-bounds access.

Can this be reassigned to someone that can look at the behavior inside this infrastructure code where the crash actually occurs?

**Comment by mavasani** [comment]
Thanks @geeknoid, I’ll investigate

**Comment by Youssef1313** [comment]
Probably `MatchesConfiguredVisibility` is designed to be only called for symbols from source, not from metadata? So I **guess** what could be happening is `HandleInvocation` calls `CanUpgrade(op.TargetMethod)` and then the `TargetMethod` is something from metadata, which might end up being something without locations? Or will it be a bug in the compiler if we have a symbol with zero locations?

**Comment by mavasani** [comment]
> Probably `MatchesConfiguredVisibility` is designed to be only called for symbols from source, not from metadata? So I **guess** what could be happening is `HandleInvocation` calls `CanUpgrade(op.TargetMethod)` and then the `TargetMethod` is something from metadata, which might end up being something without locations? Or will it be a bug in the compiler if we have a symbol with zero locations?

Thanks @Youssef1313 - this seems to be the reason. Fetching options for a specific syntax tree should only be invoked on symbols we know are from source. Specifically, `MatchesConfiguredVisibility` is only designed to be called for the symbols exposed off the symbol analysis contexts, which are guaranteed to be source symbols. It should not be invoked for other symbols.

**Comment by jlaanstra** [comment]
@mavasani do you know of any workarounds for this? I'm seeing this in a project targeting .NET 8 (Recent RC2 build).

**Comment by mavasani** [comment]
@jlaanstra Thanks for the ping. This issue just slipped off my radar, for some reason I thought @Youssef1313 had a PR out for fixing this. I can take a look at fixing this issue today.

Tagging @carlossanlop as an FYI - I am not sure if want to try to fix this in .NET 8 RC2 or not.
