### ISSUE TITLE
Suggestion to use GeneratedRegex also includes some irrelevant changes

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6854]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Suggestion-to-use-GeneratedRegex-also-in/10438634)._

---
Please see attached screenshot. VS is suggesting to use GeneratedRegex (green) but is also trying to change some of my excess parentheses at the same time.

I am trying to create a minimal reproduction of this problem and will attach it if I am successful. 

---
#### Feedback Bot on 8/13/2023, 08:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
This belongs to dotnet/runtime

**Comment by stephentoub** [comment]
This was already fixed for .NET 8.
