### ISSUE TITLE
Port FxCop rule CA2200: RethrowToPreserveStackDetails

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#692]
**Title:** Rethrow to preserve stack details

**Description:**

An exception is rethrown and the exception is explicitly specified in the throw statement. If an exception is rethrown by specifying the exception in the throw statement, the list of method calls between the original method that threw the exception and the current method is lost.

**Dependency:** None

**Notes:**

**Comment by mavasani** [comment]
This needs a fixer.

**Comment by mavasani** [comment]
Fixer added with https://github.com/dotnet/roslyn-analyzers/pull/2873
