### ISSUE TITLE
Replace temporary code once `Microsoft.CodeAnalysis.Analyzer.Testing` version is bumped

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/roslyn-analyzers#6923]
#6898 required testing against .NET 8 reference assemblies and added a workaround for the lack of a `ReferenceAssemblies.Net.Net80`.

https://github.com/dotnet/roslyn-analyzers/blob/38ffb6da8ca3906dc7caea18a51ae2c3deaba2e5/src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/UseSearchValuesTests.cs#L1002-L1021

The implementation is copied from the `roslyn-sdk` repo:
https://github.com/dotnet/roslyn-sdk/blob/6535e67cdb25ee0fb131a25be20cf82968f326ab/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs#L1022

Once the `Microsoft.CodeAnalysis.Analyzer.Testing` package ships a new version with this API, we should remove the workaround.

**Comment by taylorchasewhite** [comment]
Hit this as well, for what its worth.
