### ISSUE TITLE
ProvideCorrectArgumentsToFormattingMethodsAnalyzer throws an System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by craigktreasure** [dotnet/roslyn-analyzers#6936]
### Analyzer

**Diagnostic ID**: [CA2241](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2241): `Provide correct arguments to formatting methods`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 8 RC1 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 8.0.100-rc.1.23455.8](https://dotnet.microsoft.com/download/dotnet/8.0)

### Describe the bug

Builds encountering an exception when running the Microsoft.NetCore.Analyzers.Runtime.ProvideCorrectArgumentsToFormattingMethodsAnalyzer analyzer:

```error
CSC : error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.ProvideCorrectArgumentsToFormattingMethodsAnalyzer'
threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
```

### Steps To Reproduce

Encountering this in a small project ([SlnUp](https://github.com/craigktreasure/SlnUp)) I'm upgrading to .NET 8.

1. Clone SlnUp: `git clone https://github.com/craigktreasure/SlnUp.git`
2. Checkout the `craig/dotnet-8.0` branch.
3. Build using `dotnet build` and observe the analyzer error.

```error
CSC : error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.ProvideCorrectArgumentsToFormattingMethodsAnalyzer'
threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
[C:\Users\craig\repos\slnup\src\SlnUp\SlnUp.csproj::TargetFramework=net8.0]
```

### Expected behavior

The analyzer shouldn't throw an exception.

### Actual behavior

The analyzer is throwing an exception:

```error
CSC : error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.ProvideCorrectArgumentsToFormattingMethodsAnalyzer'
threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
[C:\Users\craig\repos\slnup\src\SlnUp\SlnUp.csproj::TargetFramework=net8.0]
```

## Additional context

Not really sure. It must be tripping over something in my code at some point.

**Comment by buyaa-n** [comment]
Thanks for reporting it @craigktreasure this bug fixed with https://github.com/dotnet/roslyn-analyzers/pull/6885
