### ISSUE TITLE
CA1065 does not consider explicit interface implementations

### ISSUE THREAD

**Issue by Tinister** [dotnet/roslyn-analyzers#6978]
### Analyzer

**Diagnostic ID**: [CA1065](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1065): `Do not raise exceptions in unexpected locations`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 7.0.401](https://dotnet.microsoft.com/download/dotnet/7.0)

### Describe the bug

CA1065 does not consider explicit interface implementations.

### Steps To Reproduce

This property triggers CA1065:

    public int Count { get { throw new ApplicationException(); } }

And same with this method:

    public bool Equals(Program? other) { throw new ApplicationException(); }

But this property does not:

    int IReadOnlyCollection<string>.Count { get { throw new ApplicationException(); } }

Nor does this method:

    bool IEquatable<Program>.Equals(Program? other) { throw new ApplicationException(); }

### Expected behavior

All of the above should trigger CA1065.

**Comment by mavasani** [comment]
Both the below methods will need to handle explicit interface implementations: https://github.com/dotnet/roslyn-analyzers/blob/80ac9265df5c8d70cbb25b57057b0f2772ed7d2a/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs#L235-L300
