### ISSUE TITLE
In VS2022, the Chinese translation of CA1827 is wrong

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-analyzers#6992]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-中，-CA1827-的中文翻译错误。/10107805)._

---
According to the actual meaning of CA1827, the translation in the red box in the screenshot should be changed to "If you can use Any(), do not use Count() to improve performance"

The current translation, the meaning is contradictory. Since Any can be used, Count should not be used instead. And the hint itself is for Count or LongCount.

---
#### Feedback Bot on 8/1/2022, 07:31 AM: 

(private comment, text removed)
#### Feedback Bot on 8/5/2022, 00:37 AM: 

(private comment, text removed)
#### Feedback Bot on 11/3/2022, 11:26 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mavasani** [comment]
@buyaa-n @carlossanlop Do we know a LOC contact for the .NET SDK analyzers? Can we loop them in?

**Comment by carlossanlop** [comment]
@cristianosuzuki77

**Comment by cristianosuzuki77** [comment]
Tickets like this needs to go through https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md#filing-issues-for-translation-issues

**Comment by carlossanlop** [comment]
As suggested by @cristianosuzuki77 , I opened a ticket in the right place: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/930699
