### ISSUE TITLE
[Doc] Release Notes after 7.0.1

### ISSUE THREAD

**Issue by archerzz** [dotnet/roslyn-analyzers#7005]
## Question

I kept getting warning messages like:
> warning : The .NET SDK has newer analyzers with version '7.0.4' than what version '7.0.1' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference.

So, I decided to upgrade to version `7.0.4`. However, the [latest release notes](https://github.com/dotnet/roslyn-analyzers/releases/tag/7.0.1) only cover version `7.0.1`. Where can I find the relese notes after that? Thanks.

**Comment by mavasani** [comment]
Thanks @archerzz. Now tracked with #6964
