### ISSUE TITLE
Make `AnalyzerOptionsExtensions` public

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [dotnet/roslyn-analyzers#7008]
Hi there,

I am trying to provide some options to my own analyzers. The extensions in [`AnalyzerOptionsExtensions`](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs) provide everthing one could possibly need to implement this, even caching is implemented. Sadly those extensions are internal and I cannot use them.

Can you make this public? If not, why? Otherwise I basically need to copy the file to have a solid foundation for options handling.

So lonG

Daniel

**Comment by mavasani** [comment]
@ViRuSTriNiTy It seems reasonable to mark [AnalyzerOptionsExtensions](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs) as a public type - we will welcome a PR here. Note that this type is already shipped in a NuGet package: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9/NuGet/Microsoft.CodeAnalysis.AnalyzerUtilities. So, once the above PR is merged, next available package on this feed should have the public API you require.

**Comment by eriawan** [comment]
@mavasani 
Thanks! A draft PR #7085 is submitted. Please review, as I have more questions there.
