### ISSUE TITLE
How to access `AnalyzerConfigOptions` in a  `CodeFixProvider`?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [dotnet/roslyn-analyzers#7009]
Hi there,

I have an analyzer that checks all fields in a named type for a) being in a specific section of code and b) for alphabetic order.

Now, I want to provide an option to allow this or that project to disable the check for alphabetic oder. I can read the option in the analyzer via `AnalyzerConfigOptions`, but I don't see an API to access an option in `CodeFixProvider`. Is it even possible to read analyzer options in a code fix provider? If not, how to proceed? Split the analyzer into one checking for a) and the other one checking for b)?

So lonG

Daniel

**Comment by mavasani** [comment]
@ViRuSTriNiTy You can fetch the option value in the analyzer just before reporting a diagnostic, and add a custom property to the reported diagnostic that can then be read in the code fix provider by reading `Diagnostic.Properties` dictionary. Let us know if this addresses your issue or you need further assistance on how to accomplish this.

**Comment by ViRuSTriNiTy** [comment]
Thank you @mavasani, using the `Properties` dictionary works as expected, therefore issue closed.
