### ISSUE TITLE
CA1849 "Call async methods when in an async method" false positive on IDbContextFactory<TContext>.CreateDbContext()

### ISSUE THREAD

**Issue by wertzui** [dotnet/roslyn-analyzers#7036]
### Analyzer

**Diagnostic ID**: [CA1849](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1849): `Call async methods when in an async method`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 8.0.100](https://dotnet.microsoft.com/download/dotnet/8.0)

### Describe the bug

Using `IDbContextFactory<TContext>.CreateDbContext()` reports a warning and suggests using `IDbContextFactory<TContext>.CreateDbContextAsync()`.

However the `CreateDbContextAsync()` method exists only for very special edge cases and should not be used by default,

This is simmilar to https://github.com/dotnet/roslyn-analyzers/issues/6684

### Steps To Reproduce

Use `IDbContextFactory<TContext>.CreateDbContext()` in an `async` method.

### Expected behavior

The rule is not triggered.

### Actual behavior

The rule is triggered.

## Additional context

The false positive got possibly introduced in https://github.com/dotnet/roslyn-analyzers/pull/6858 while fixing https://github.com/dotnet/roslyn-analyzers/issues/6684

**Comment by CollinAlpert** [comment]
@wertzui As far as I know the `CreateDbContextAsync` is generally an acceptable way to create a `DbContext` asynchronously. Can you link to documentation stating otherwise?

**Comment by wertzui** [comment]
The default `IDbContextFactory<TContext>` does not perform any IO work when `CreateDbContext()` is calledand therefor does not need to be `async`.

Some more insights can be found in https://github.com/dotnet/efcore/issues/26630 where @ajcvickers statet that `CreateDbContextAsync()` is probably not needed, but that it is now too late to revert the change which might break custom implementations.
> In retrospect, it's possible we should not have added this; it might turn out to be YAGNI.

> We discussed, and while maybe we should not have added this API (time will tell), we don't think making a breaking change to remove it would be the best thing to do now.

**Comment by CollinAlpert** [comment]
Thanks for the explaination! As far as I know, the EF team [wants to add a suppressor to EF](https://github.com/dotnet/roslyn-analyzers/pull/6858#issuecomment-1681147338), so I don't know how likely the issue will be fixed in the analyzer itself.

**Comment by wertzui** [comment]
If I got that thread correctly, the idea was to suppress this here and in EF Core to have it fixed no matter which package you update.

**Comment by mu88** [comment]
@mavasani how will this fix ship? I'm still seeing the build warning with .NET `8.0.101`

**Comment by mavasani** [comment]
@mu88 The fix will ship in .NET 9 SDK and version 9.x.x of Microsoft.CodeAnalysis.NetAnalyzers Nuget package on nuget.org

**Comment by mu88** [comment]
So we'll have to live with this bug for almost one year? Don't get me wrong and with all due respect, but this is extremely annoying - why can't it be shipped with a .NET 8 fix?

**Comment by CollinAlpert** [comment]
You can always install the Microsoft.CodeAnalysis.NetAnalyzers package before the .NET 9 release.

**Comment by mu88** [comment]
But it will probably be a pre-release package, no? We're striving to only use officially released packages

**Comment by CollinAlpert** [comment]
Yes, it will be a pre-released package version, which does not mean it is of a lower quality. You will get new rules and fixes quicker. Otherwise you will need to wait for the .NET 9 release.

**Comment by mu88** [comment]
And do you have a rough estimate of when this pre-release package will be released?

**Comment by CollinAlpert** [comment]
I personally do not, but maybe someone from the team can comment on that.

**Comment by mu88** [comment]
Do you or your colleagues have an update about this, @CollinAlpert ?

**Comment by CollinAlpert** [comment]
Preview versions usually get released in February, however the first v8.0.0 preview wasn't released until in May.

**Comment by CollinAlpert** [comment]
@mu88 Can you post a reproduction so I can take a look?
