### ISSUE TITLE
RS1039 Reported for a call to `SemanticModel.GetDeclaredSymbol` with a `LocalFunctionStatementSyntax` but the call can return non-`null`

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/roslyn-analyzers#7061]
### Analyzer

**Diagnostic ID**: RS1039: `A call to 'SemanticModel.GetDeclaredSymbol(LocalFunctionStatementSyntax)' will always return 'null'`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers)

**Version**: 3.11.0-beta1.23579.3

### Describe the bug

The analyzer reports a diagnostic on calls to `SemanticModel.GetDeclaredSymbol` with a `LocalFunctionStatementSyntax`. These calls will return an `IMethodSymbol`, not `null`, so the analyzer should not fire here.

### Steps To Reproduce

1. Write a call to `SemanticModel.GetDeclaredSymbol` with a `LocalFunctionStatementSyntax` object.

### Expected behavior

No diagnostic

### Actual behavior

Diagnostic

## Additional context

Found in dotnet/runtime.

**Comment by mavasani** [comment]
@CollinAlpert
