### ISSUE TITLE
Upgrade to .NET 9 SDK

### ISSUE THREAD

**Issue by mthalman** [dotnet/roslyn-analyzers#7066]
This repo should be targeting the .NET 9 SDK from the global.json file. This is a requirement necessary for .NET source build in order to target the `net9.0` TFM. If necessary, this change can be made after the first public preview release.

Related to https://github.com/dotnet/source-build/issues/3770

**Comment by mavasani** [comment]
@mthalman Is there a corresponding version of publicly released Visual Studio preview build that supports the .NET 9 SDK? Otherwise, how do you recommend our community contributors deal with this change?

**Comment by mthalman** [comment]
There isn't yet. That's why I said this change could be made after the first public preview release.

**Comment by ViktorHofer** [comment]
This issue can now be closed.
