### ISSUE TITLE
Port FxCop rule CA2218: OverrideGetHashCodeOnOverridingEquals

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#707]
**Title:** Override GetHashCode on overriding Equals

**Description:**

GetHashCode returns a value, based on the current instance, that is suited for hashing algorithms and data structures such as a hash table. Two objects that are the same type and are equal must return the same hash code.

**Dependency:** None

**Notes:**

Fixer should create method that throws NotImplementedException. Implementer should check if the compiler gives this warning.

**Comment by amcasey** [comment]
This appears to be the same as CS0661.

**Comment by amcasey** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/743

**Comment by amcasey** [comment]
https://github.com/dotnet/roslyn-analyzers/commit/4c237021bbed3bdc572b99c468d0045ab4943ea6
