### ISSUE TITLE
Port FxCop rule CA2224: OverrideEqualsOnOverloadingOperatorEquals

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#708]
**Title:** Override Equals on overloading operator equals

**Description:**

A public type implements the equality operator but does not override Object.Equals.

**Dependency:** None

**Notes:**

Fixer should create method that throws NotImplementedException. Implementer should check if the compiler gives this warning.

**Comment by amcasey** [comment]
This appears to be the same as CS0660.

**Comment by amcasey** [comment]
https://github.com/dotnet/roslyn-analyzers/pull/743

**Comment by amcasey** [comment]
https://github.com/dotnet/roslyn-analyzers/commit/4c237021bbed3bdc572b99c468d0045ab4943ea6
