### ISSUE TITLE
CA1510 (Use ArgumentNullException throw helper) shows up in netstandard2.0 projects that don't have the throw helper

### ISSUE THREAD

**Issue by maltalex** [dotnet/roslyn-analyzers#7082]
### Description

[CA1510: Use ArgumentNullException throw helper](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1510) doesn't seem to take the target framework of the project into account and can show up in projects that target a framework that don't have the [ArgumentNullException.ThrowIfNull](https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull) method (e.g. netstandard2.0).

This effectively creates a warning that cannot be fixed, only suppressed.

### Reproduction Steps

Create a project targeting netstandard2.0 with a snippet like

```
void Dummy(string arg)
{
    if (arg is null)
    {
        throw new ArgumentNullException(nameof(arg));
    }
}
```

Add the following to the project file:
`<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" />`
and 
`<AnalysisLevel>8.0-Recommended</AnalysisLevel>`

Build, and observe CA1510 being displayed.

### Expected behavior

CA1510 not displayed in projects that target a framework that does not have `ArgumentNullException.ThrowIfNull`.

### Actual behavior

CA1510 displayed in projects that target netstandard2.0

**Comment by maltalex** [comment]
@stephentoub You're right. The bare-bones reproduction I suggested doesn't work. But I still get the warning in a project targeting netstandard2.0 and net8. And the warning comes from the netstandard build: 

![image](https://github.com/dotnet/roslyn-analyzers/assets/10195391/ead379f2-9542-40a3-a829-54ab4ec5adf7)

On that note, it may be a good idea to disable this warning completely in multi-targeted projects that include a target without `ArgumentNullException.ThrowIfNull`. The fix in such projects is worse than the problem, similar what's done [here](https://github.com/dotnet/aspnetcore/blob/52364da7f2d8e8956085a92c2f6b9dae48ac130d/eng/targets/CSharp.Common.targets#L34-L35).

Anyway, something else is going on here. I'll see if I can nail it down further.

**Comment by mavasani** [comment]
> On that note, it may be a good idea to disable this warning completely in multi-targeted projects that include a target without ArgumentNullException.ThrowIfNull

This problem is not specific to this analyzer, but it reproduces for any analyzer that works off a new .NET API that is available on newer target frameworks. If the multi-targeted project is targeting an older framework as well, this issue will occur. The general recommendation here for the users is to either add a source suppression with a source comment for the justification OR use `#if` pragma directives in source to ensure the code based off the new .NET API is only compiled for newer TFMs.
