### ISSUE TITLE
`CA2021` reports for `net471` but not `net6`, but Exception is thrown in both cases

### ISSUE THREAD

**Issue by LukasGelke** [dotnet/roslyn-analyzers#7102]
### Analyzer

**Diagnostic ID**: [CA2021](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2021): `Don't call Enumerable.Cast<T> or Enumerable.OfType<T> with incompatible types`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 8.0.0 (Latest)

### Steps To Reproduce
- use new/empty project, with example:
```cs
using System.Collections.Generic;
using System.Linq;

namespace ClassLibrary1;

#pragma warning disable CS1591

public class Comp { }

public class Column : Comp { }
public class Column2 : Column { }


public class Band : Comp { }
public class Band2 : Band { }

public class Class2
{

  public IEnumerable<Column> Columns { get; set; } = [new()];
  public void Do()
  {
    var x = Columns.Cast<Band2>().ToList(); // Warning here in net471 only
    _ = x;
  }
}
```
- run in `net471` and `net6`
- observe `InvalidCastException`

### Expected behavior
same warning for `net471` and `net6`

### Actual behavior
warning only in `net471`

## Additional context

as we are "currently" in the process of transitioning from `net471` to `net6+`, we would never gotten this waring in `net6`-only builds/projects

**Comment by sharwell** [comment]
Since I wasn't able to reproduce this in tests, I looked deeper and found that the difference appears to be these files that get passed for `net8.0` and `net6.0`, respectively:

```
c:\dev\roslyn\artifacts\packages\microsoft.codeanalysis.netanalyzers\8.0.0\buildTransitive\config\analysislevel_8_default.globalconfig
c:\dev\roslyn\artifacts\packages\microsoft.codeanalysis.netanalyzers\8.0.0\buildTransitive\config\analysislevel_6_default.globalconfig
```

It appears that CA2021 is disabled by default for the net6.0 target. You can manually enable it (and other newer rules) by adding the following to your project:

```
<PropertyGroup>
  <AnalysisLevel>8</AnalysisLevel>
</PropertyGroup>
```
