### ISSUE TITLE
CA1859: Not triggering when concrete type is ImmutableArray

### ISSUE THREAD

**Issue by tfadler** [dotnet/roslyn-analyzers#7127]
### Analyzer

**Diagnostic ID**: [CA1859](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1859): `Use concrete types when possible for improved performance`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 8 SDK](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 8.0.100](https://dotnet.microsoft.com/download/dotnet/8.0)

### Describe the bug

CA1859: Not triggering when concrete type is ImmutableArray

### Steps To Reproduce

Note I set my editorconfig to
```
[*.cs]
dotnet_diagnostic.CA1859.severity = warning
```

```

using System.Collections.Immutable;

var class1 = new Class1();
var list = class1.CreateList();
var immuttableArray = class1.CreateImmutableArray();
var immuttableList = class1.CreateImmutableList();

public class Class1
{
    public IEnumerable<int> CreateList()
    {
        return CreateListPrivately();
    }

    public IEnumerable<int> CreateImmutableArray()
    {
        return CreateListPrivately();
    }

    public IEnumerable<int> CreateImmutableList()
    {
        return CreateListPrivately();
    }

    private IEnumerable<int> CreateListPrivately()
    {
        return new List<int>
        {
            1, 2, 3, 4
        };
    }

    private IEnumerable<int> CreateImmutableArrayPrivately()
    {
        return new ImmutableArray<int>
        {
            1, 2, 3, 4
        };
    }

    private IEnumerable<int> CreateImmutableListPrivately()
    {
        var temp = ImmutableList.Create<int>(1, 2, 3, 4);

        return temp;
    }
}

```

### Expected behavior

Private methods CreateListPrivately(), CreateImmutableArrayPrivately(), and CreateImmutableListPrivately() trigger CA1859

### Actual behavior

Only private methods CreateListPrivately() and CreateImmutableListPrivately() trigger CA1859

## Additional context

Maybe this is related to https://github.com/dotnet/roslyn-analyzers/issues/6667

**Comment by geeknoid** [comment]
This happening because the analyzer currently explicitly ignores struct types (which ImmutableArray is). I'll look to see if this constraint can be relaxed, I don't remember why I put that in there in the first place...
