### ISSUE TITLE
Microsoft.CodeAnalysis.PublicApiAnalyzers 3.3.4 does not work with .NET 8 projects

### ISSUE THREAD

**Issue by bitbonk** [dotnet/roslyn-analyzers#7135]
The latest stable version of Microsoft.CodeAnalysis.PublicApiAnalyzers, version 3.3.4 does not generate any analyzer warnings in .NET 8 projects. At the current time 3.3.4 is the latest stable version. 

Are there plans to ship a stable version of Microsoft.CodeAnalysis.PublicApiAnalyzers that supports .NET 8 in the coming weeks?

**Comment by mavasani** [comment]
Unable to reproduce this:

![image](https://github.com/dotnet/roslyn-analyzers/assets/10605811/b2902034-535b-40e0-8b24-881aad3fbbea)

Can you please double check and provide a repro?
