### ISSUE TITLE
ResxSourceGenerator should only generate code for the main file

### ISSUE THREAD

**Issue by taooceros** [dotnet/roslyn-analyzers#7155]
### Analyzer

ResxSouceGenerator

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 3.11.0-beta

### Describe the bug

I am not sure whether I use it wrongly. Though, if I have a main Resource file (e.g. `Resource.resx`) and a set of sub resource file containing localization translation (e.g. `Resource.es.resx`), each of the resx file got its own copy of the designer.cs, while only the first one should be generated. Further, the later files are weird and conflict with the main one, as it will have a namespace `{ProjectBase}.Resource` (which conflict with the class name of the main file) and classname as `cs` which don't make any sense.

### Expected behavior

Any variant of the resource file should not generate its code-behind.

### Actual behavior

Every `resx` file got a `cs` file generated.

**Comment by sharwell** [comment]
This was fixed by #6970, which is included in version 3.11.0-beta1.23503.1 and newer.
