### ISSUE TITLE
New analyzer: Do not call ToList on variable which is already a List

### ISSUE THREAD

**Issue by DanAvni** [dotnet/roslyn-analyzers#7177]
I have the code below, The function foo returns a list of strings. Calling ToList on the returned value is redundant (except for a case that for some reason I want to replace the List instance with a new one). The same applies to other Linq ToX functions and their respective types (Array, HashSet, etc). 

Please add a new analyzer and a fix for that
```
void Main()
{
	List<string> fooList = foo().ToList(); //ToList is redundant
}
List<string> foo(){
	List<string> result = new List<string>();
	result.Add("bar");
	return result;
}
```

**Comment by CollinAlpert** [comment]
Since this is an analyzer targeting a .NET API, please open an issue in [dotnet/runtime](https://github.com/dotnet/runtime/issues), as described in https://github.com/dotnet/roslyn-analyzers/blob/main/GuidelinesForNewRules.md

**Comment by fowl2** [comment]
Calling `.ToList()` is a very common pattern to shallow clone (copy) a List, and removing a copy can very often change the meaning/behavior of the code.

**Comment by DanAvni** [comment]
@fowl2 , I agree but it could also be a issue if for example I have a function `IEnumerable<int> foo()` and a caller used `foo().ToList()` and then the function foo is changed to `List<int> foo()`. Now the call `foo().ToList()` wastes CPU building a new list without a reason. Not exactly what I am facing but close enough where going over all calls to foo to see if any are using ToList is not doable easily.

Also I think that if the intent is to have a shallow clone the developer should be more explicit about it and not use ToList for it (I would use `new List(oldList)`. But that depends on coding style

**Comment by DanAvni** [comment]
@CollinAlpert , Issue opened there. Thanks

**Comment by fowl2** [comment]
(it was briefly https://github.com/dotnet/runtime/issues/98146, for those playing along at home)
