### ISSUE TITLE
Conflict between CA1515 and CA1064 for Exception types

### ISSUE THREAD

**Issue by jamesgurung** [dotnet/roslyn-analyzers#7191]
### Analyzers

* [CA1515](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1515): `Consider making public types internal`
* [CA1064](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1064): `Exceptions should be public`

### Analyzer source

**Version**: [SDK 9.0.100-preview.1](https://dotnet.microsoft.com/en-us/download/dotnet/9.0)

### Describe the bug

Setting the visibility of an `Exception` class to `public` causes a CA1515 warning, whereas setting it to `internal` causes a CA1064 warning.

### Steps To Reproduce

**ConsoleApp1.csproj**

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
</Project>
```

**Program.cs**
```cs
throw new ExampleException("Test");

public sealed class ExampleException : Exception // or internal
{
  public ExampleException(string message) : base(message) { }
  public ExampleException(string message, Exception innerException) : base(message, innerException) { }
}
```

### Expected behavior
One of the visibility modifiers (`public` or `internal`) should compile without either compiler warning.

### Actual behavior
Both options result in a compiler warning.

**Comment by buyaa-n** [comment]
We might want to exclude diagnostic for [CA1064 Exceptions should be public:](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1064) in this case, doesn't feel exceptions need to be public for executable, what you think @stephentoub?

**Comment by stephentoub** [comment]
> We might want to exclude diagnostic for [CA1064 Exceptions should be public:](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1064) in this case, doesn't feel exceptions need to be public for executable, what you think [@stephentoub](https://github.com/stephentoub)?

Yeah, I agree.

(Though honestly I find https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1064 a bit suspect, anyway.)
