### ISSUE TITLE
Where are release notes? Last one is 7.0.1

### ISSUE THREAD

**Issue by lflender** [dotnet/roslyn-analyzers#7203]
Releases and release notes found on https://github.com/dotnet/roslyn-analyzers/releases stop at 7.0.1.

Latest ones should be properly published and documented too.

Thank you.

**Comment by mavasani** [comment]
@buyaa-n @carlossanlop we should publish release notes for each of the subsequent .NET releases: https://github.com/dotnet/roslyn-analyzers/blob/main/PostReleaseActivities.md#steps-to-generate-release-notes

**Comment by carlossanlop** [comment]
@lflender I added the missing tags and release notes for the missing releases:

- https://github.com/dotnet/roslyn-analyzers/releases/tag/7.0.3
- https://github.com/dotnet/roslyn-analyzers/releases/tag/7.0.4
- https://github.com/dotnet/roslyn-analyzers/releases/tag/8.0.0
- https://github.com/dotnet/roslyn-analyzers/releases/tag/9.0.0

The [script](https://github.com/dotnet/roslyn-analyzers/blob/main/PostReleaseActivities.md#steps-to-generate-release-notes) provided in the above comment was obsolete, unforunately. So I opened a PR updating the instructions to the steps I followed: https://github.com/dotnet/roslyn-analyzers/pull/7503

@arunchndr it's my understanding that the task of generating release notes falls on the owner of the repo, which would be your team. Feel free to create the remaining release notes for previews if needed.

**Comment by lflender** [comment]
Awesome, thank you.
