### ISSUE TITLE
CA2022 Special-case MemoryStream and UnmanagedMemoryStream and don't issue diagnostic

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/roslyn-analyzers#7268]
Special-case `MemoryStream` and `UnmanagedMemoryStream` where if we can prove the target Stream is one of those we don't issue diagnostic. Those, in particular the former, are commonly used and we know they are actually safe for this usage; I'd like to avoid causing a lot of noise around them. While we don't necessarily document it's safe, we also don't need to cause folks to do a lot of work in response.

              Can we special-case MemoryStream and UnmanagedMemoryStream where if we can prove the target Stream is one of those we don't issue diagnostics?  Those, in particular the former, are commonly used and we know they are actually safe for this usage; I'd like to avoid causing a lot of noise around them. While we don't necessarily document it's safe, we also don't need to cause folks to do a lot of work in response.

_Originally posted by @stephentoub in https://github.com/dotnet/roslyn-analyzers/pull/7208#discussion_r1539468864_

**Comment by paulomorgado** [comment]
Make sure [Microsoft.IO.RecyclableMemoryStream](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream) is not excluded.

/cc @benmwatson
