### ISSUE TITLE
Which version users with `EnableNETAnalyzers` actually use?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/roslyn-analyzers#7278]
@buyaa-n @mavasani My PR #6976 was merged a while ago but I can still see that in my .NET 8 project, the warnings are still produced. 

I [use](https://github.com/dotnet/roslyn-analyzers/?tab=readme-ov-file#microsoftcodeanalysisnetanalyzers) `<EnableNETAnalyzers>true</EnableNETAnalyzers>` to enable Roslyn analyzers.

How do I determine which version of .NET Analyzers I'm actually using, please?

Thank you!

**Comment by buyaa-n** [comment]
The fix is not ported to .NET 8 SDK, should be available in .NET 9 SDK.
