### ISSUE TITLE
Where's the logic?!

### ISSUE THREAD

**Issue by voroninp** [dotnet/roslyn-analyzers#7352]
Here's [the statement](https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md):

Configuration: If you would prefer the public API analyzer to bail out silently for projects with missing public API files, you can do so by setting the following .editorconfig option:
```
[*.cs]
dotnet_public_api_analyzer.require_api_files = true
```

`require_api_files = true` vs `bail out silently`. WTF?

**Comment by voroninp** [comment]
In code it is called **BailOnMissingPublicApiFiles**EditorConfigOptionName but the setting in `.editorconfig` is called `require_api_files` ='(

**Comment by sharwell** [comment]
The name may be strange, but the documentation appears to be correct so closing this one out.

**Comment by voroninp** [comment]
@sharwell Would you mind, if I create a PR with yet another setting with better naming?

**Comment by sharwell** [comment]
@voroninp In my experience, the addition of new options with the same meaning ends up strictly worse than a state like we have today, so we would not be likely to make that change.

**Comment by voroninp** [comment]
Ok, you are the owner.

Just imagine the confusion of the developer who sees this setting without first looking at documentation.

Epsecially when it is:
```
[*.cs]
dotnet_public_api_analyzer.require_api_files = false
```
