### ISSUE TITLE
Allow specifying access modifier for ResxSourceGenerator generated code

### ISSUE THREAD

**Issue by jeremy-visionaid** [dotnet/roslyn-analyzers#7367]
I'd like to add Microsoft.CodeAnalysis.ResxSourceGenerator to an existing project, but the project is currently using PublicResXFileCodeGenerator, and ResxSourceGenerator appears to be hard-coded to use "internal". Would be great to add a configuration option to specify the desired access modifier.

**Comment by jeremy-visionaid** [comment]
Ah, my bad. I missed a duplicate issue (#6827) had been marked as closed.

So, it can be enabled with `Public="true"`, but the `Format*` methods from `EmitFormatMethods="true"`  are declared `internal` due to #6579

**Comment by jeremy-visionaid** [comment]
@alexspirou Take a look at Andrew Arnott's article here: 
https://blog.nerdbank.net/2023/04/get-rid-of-your-designer-cs-code-behind-for-resx
It references the code so you can find the configuration parameters yourself. Just put them on the EmbeddedResource element like so:

```
<ItemGroup>
    <EmbeddedResource Update="*.resx" GenerateSource="false" />
    <EmbeddedResource Update="Properties/Resources.resx" GenerateSource="true" Public="true" />
</ItemGroup>
```

**Comment by alexspirou** [comment]
@jeremy-visionaid  Thanks a lot. 

One more question. Do you know if there is a way to not generated as a static class?

**Comment by jeremy-visionaid** [comment]
@alexspirou I don't believe so, but I provided everything you should need to check for yourself.

**Comment by jeremy-visionaid** [comment]
@alexspirou Though I thought that sounded familiar: #7332

**Comment by alexspirou** [comment]
Thanks.

**Comment by alexspirou** [comment]
> @alexspirou Take a look at Andrew Arnott's article here: https://blog.nerdbank.net/2023/04/get-rid-of-your-designer-cs-code-behind-for-resx It references the code so you can find the configuration parameters yourself. Just put them on the EmbeddedResource element like so:
> 
> ```
> <ItemGroup>
>     <EmbeddedResource Update="*.resx" GenerateSource="false" />
>     <EmbeddedResource Update="Properties/Resources.resx" GenerateSource="true" Public="true" />
> </ItemGroup>
> ```

`    <ItemGroup>
        <EmbeddedResource Update="*.resx" GenerateSource="false" />
        <EmbeddedResource Update="Resources\ClientPrivateLocalization.resx" GenerateSource="true" Public="true"  />
    </ItemGroup>`
    
    
    Here is my setup. Still the file is generated as internal.
