### ISSUE TITLE
The analyzers projects in the repo should use the analyzers from this repo 

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#741]
Atleast the roslyn.diagnostic.analyzers and the configureawait rules are needed.

**Comment by sharwell** [comment]
The latter is related to #211, where the package provides a [UseConfigureAwait](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/blob/master/AsyncUsageAnalyzers/AsyncUsageAnalyzers/Usage/UseConfigureAwaitAnalyzer.cs) rule that can be enabled in relevant projects.

**Comment by mavasani** [comment]
Done
