### ISSUE TITLE
Descriptors with the same id should only differ in messageformat.

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#745]
FXCop seems to have many cases where it reports completely different messages with same ID (though related in some way). The stub generator seems to generate different descriptors with same ID that differ just by message format. This will cause issues when seeing the rules in the ruleset editor. We should fix the stub generator to generate a single descriptor with a placeholder messge format `"{0}"` and a comment stating that the analyzer author should pass the entire formatted message as a format argument to Diagnostic.Create when creating a diagnostic to report. We should also add a helper to AnalyzerUtilities for the same.

/cc @genlu @srivatsn

**Comment by srivatsn** [comment]
Having {0} would make the messages non-localizable. We can maybe write an analyzer to enforce that only messageformats can differ between descriptors when they have the same id.

**Comment by mavasani** [comment]
Done
