### ISSUE TITLE
F5ing *.Setup projects doesn't hit some RegisterOperationAction callbacks

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn-analyzers#770]
`analysisContext.RegisterOperationAction(context => { var BREAKPOINTHERE = 7; }, OperationKind.BinaryOperatorExpression);` doesn't hit the lambda body, I believe due to a semi-recent change in the OperationKind enum. I thought this was fixed, but I'm still hitting this problem.

/cc: @srivatsn @jmarolf @JohnHamby

**Comment by srivatsn** [comment]
We've updated the roslyn packages to 1/6's build. This issue should now be fixed for you.
