### ISSUE TITLE
Cannot build due to unresolvable dependency: Microsoft.CodeAnalysis-1.2.0-beta-20151118-02

### ISSUE THREAD

**Issue by brettfo** [dotnet/roslyn-analyzers#771]
Building on a clean machine fails because the `1.2.0-beta-20151118-02` version of the `Microsoft.CodeAnalysis.*` packages cannot be restored and they are not listed on [NuGet.org](http://www.nuget.org/packages/Microsoft.CodeAnalysis/).

Manually copying these packages from another machine that had them enables restore/build to succeed.

**Comment by srivatsn** [comment]
We've updated to 1/6's build of Roslyn and we can build the repo again,
