### ISSUE TITLE
Unit tests are failing strong name validation for System.Reflection.Metadata

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn-analyzers#785]
I did a pull to get all the recent changes, and am encountering tons of test failures with the same stack trace:

```
Microsoft.ApiDesignGuidelines.Analyzers.UnitTests.TypesThatOwnDisposableFieldsShouldBeDisposableAnalyzerTests.CA10
  01CSharpTestWithFieldInitAndNoDisposeMethod [FAIL]
        System.TypeInitializationException : The type initializer for 'Microsoft.CodeAnalysis.UnitTests.DiagnosticAnaly
  zerTestBase' threw an exception.
        ---- System.IO.FileLoadException : Could not load file or assembly 'System.Reflection.Metadata, Version=1.2.0.0
  , Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Excep
  tion from HRESULT: 0x8013141A)
        -------- System.Security.SecurityException : Strong name validation failed. (Exception from HRESULT: 0x8013141A
  )
        Stack Trace:
              at Microsoft.CodeAnalysis.UnitTests.DiagnosticAnalyzerTestBase..ctor()
              at Microsoft.ApiDesignGuidelines.Analyzers.UnitTests.TypesThatOwnDisposableFieldsShouldBeDisposableAnalyz
  erTests..ctor()
           ----- Inner Stack Trace -----
              at Microsoft.CodeAnalysis.UnitTests.DiagnosticAnalyzerTestBase..cctor()
           ----- Inner Stack Trace -----
```

When I look at the System.Reflection.Metadata version number on the assembly in the binary drop folder, it is 4.6.23629.0

**Comment by srivatsn** [comment]
I just tried this and I'm not running into this issue. The unit test is referencing the 4.6.23629 version of S.R.Metadata. Maybe you have a stale binary from a previous build? Can you clean your binaries directory and try a full rebuild?

**Comment by lgolding** [comment]
@twsouthwick are you still seeing this, and is it still blocking your work on #740? Sorry, I've been OOF for 2-1/2 days.

**Comment by twsouthwick** [comment]
I tried what @srivatsn  suggested and I'm still seeing this. I did a `git clean -xfd` and reran `src\.nuget\NuGetRestore.ps1`. I alos tried clearning my nugget cache at `~\.nuget\packages`

**Comment by lgolding** [comment]
@twsouthwick I am investigating now. @srivatsn FYI

**Comment by lgolding** [comment]
@twsouthwick, the following worked for me, after the changes I just merged in #797:

* `git fetch upstream`
* `git rebase upstream/master`
* `git clean -xdf`
* From the repo root directory: `cibuild.cmd`.

`cibuild.cmd` is the "official" way to build: It restores NuGet packages, builds, and runs the unit tests. Please try this and let us know if you're fixed.

**Comment by twsouthwick** [comment]
I have tried this multiple ways and keep coming up with it. I'll try it on another (clean) machine tomorrow if no one else has seen this issue.

**Comment by lgolding** [comment]
@twsouthwick Just to be clear, this repros when you follow the exact set of steps I gave above?

**Comment by twsouthwick** [comment]
Yes - I tried your steps. By "multiple ways" I actually meant "multiple times". I just tried in cmd vs powershell vs developer cmd prompt just to verify those environments weren't affecting it and it failed in the same way each time.

**Comment by duracellko** [comment]
Have you had any luck solving this problem? I am facing the same issue. I checked strong-name of the System.Reflection.Metadata and it said "a delay-signed or test-signed assembly". Is this supposed to be correct?

**Comment by srivatsn** [comment]
I just remembered that my machine has signing verification turned off. The interim build of System.Reflection.Metadata that's currently consumed is not fully signed and so if you try running `sn -Vr *` from an admin command prompt and then run the tests, does that fix the issue for you?

**Comment by duracellko** [comment]
Command `sn -Vr *` works. Thank you.

**Comment by JoshVarty** [comment]
Can we get a signed build of `System.Reflection.Metadata` or at least delay sign it? 

Failing that, the `sn -Vr *` step should be added to the README.

**Comment by lgolding** [comment]
@JoshVarty, I added the following to the [README](https://github.com/dotnet/roslyn-analyzers/blob/master/README.md):

**NOTE** The current build of System.Reflection.Metadata (from NuGet package System.Reflection.Metadata.1.2.0-rc2-23629) is unsigned. This causes unit tests to fail. To work around this problem until a new, signed version is available, give the command
```
sn -Vr System.Reflection.Metadata,B03F5F7F11D50A3A
```
which will cause the CLR to skip strong name verification for that assembly.

When a properly signed version of this assembly becomes available, reenable strong name verification with the command
```
sn -Vu System.Reflection.Metadata,B03F5F7F11D50A3A
```

**Comment by JoshVarty** [comment]
:+1:

**Comment by srivatsn** [comment]
Closing this issue since the readme entry has been added,

**Comment by nguerrera** [comment]
Hang on. Where did that build come from? I'm very surprised there was an unsigned version being used. cc @tmat, @ericstj.

**Comment by srivatsn** [comment]
From the myget feed. We snapped to some intermediate build. If the latest binaries on MyGet are signed then this will get fixed when we update package references.

**Comment by Tiliavir** [comment]
System.Reflection.Metadata 1.2.0 seems to be signed again, so the comment in Getting Started can be removed I guess ...
