### ISSUE TITLE
CA2104 reports on immutable readonly field

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#793]
The example below reports:
```
Remove the read-only designation from 'AlertSoundSourceItem.None' or change the field to one that is an immutable reference type. If the reference type 'AlertSoundSourceItem' is, in fact, immutable, exclude this message.
```

```csharp
public sealed class AlertSoundSourceItem : AlertSourceItem
{
    /// *****
    public static readonly AlertSoundSourceItem None = new AlertSoundSourceItem(false, null);

    public AlertSoundSourceItem(bool isEnabled, string soundPath)
        : base(isEnabled, soundPath)
    {
    }
}

public abstract class AlertSourceItem
{
    public bool IsEnabled { get; }
    public string Path { get; }

    public string EffectivePath => !IsEnabled ? null : Path;

    protected AlertSourceItem(bool isEnabled, string path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            if (isEnabled)
            {
                Guard.NotNullNorEmpty(path, nameof(path));
            }
        }
        else
        {
            Path = path;
        }

        IsEnabled = isEnabled;
    }
}
```

This seems like a bug to me, because all members of the base class are readonly, which makes the class immutable. So, `None` would be immutable also, in which case the warning does not apply.

**Comment by bkoelman** [comment]
Simpler repro (v1.1.0):

```csharp
    public sealed class Demo
    {
        public static readonly Demo Default = new Demo(0, TimeSpan.Zero);

        public int SomeInt { get; }

        public TimeSpan SomeTime { get; }

        private Demo(int someInt, TimeSpan someTime)
        {
            SomeInt = someInt;
            SomeTime = someTime;
        }
    }
```

Reports:
```
Remove the read-only designation from 'Demo.Default' or change the field to one that is an immutable reference type. If the reference type 'Demo' is, in fact, immutable, exclude this message.
```

**Comment by srivatsn** [comment]
FxCop's implementation of CA2104 basically had a list of type that were known to have immutable semantics and it considered anything else mutable. It didnt really check for immutability of a type which requires complicated analysis. We've decided to not reimplement CA2104 as an analyzer (see https://github.com/dotnet/roslyn-analyzers/issues/716) since in it's current form it is very noisy.

**Comment by bkoelman** [comment]
Ah, I did not know about the hard-coded list. Thanks for the update.

**Comment by kinloongTong** [comment]
> FxCop's implementation of CA2104 basically had a list of type that were known to have immutable semantics and it considered anything else mutable. It didnt really check for immutability of a type which requires complicated analysis. We've decided to not reimplement CA2104 as an analyzer (see #716) since in it's current form it is very noisy.

Should the implementation change the list of a known mutable type, rather obsolete it?
