### ISSUE TITLE
Main readme contains broken link for Microsoft.CodeAnalysis.Analyzers

### ISSUE THREAD

**Issue by epsitec** [dotnet/roslyn-analyzers#796]
The Microsoft.CodeAnalysis.Analyzers seem to have moved. The link https://github.com/dotnet/roslyn-analyzers/blob/master/src/CodeAnalysis/Microsoft.CodeAnalysis.Analyzers.md is broken.

**Comment by srivatsn** [comment]
Thanks. Fixed the link.

**Comment by epsitec** [comment]
Thank you, but the link now seems to point to an empty page.
