### ISSUE TITLE
CodeDom Analysis Bug on Form Controls

### ISSUE THREAD

**Issue by Routess** [dotnet/roslyn-analyzers#810]
Happens every time you want to add a vb.net theme to your project and set your project to in in 64x CPU mode. 

Error code(s):
AD0001	Die Analyse 'Microsoft.CodeAnalysis.VisualBasic.CodeFixes.SimplifyTypeNames.VisualBasicSimplifyTypeNamesDiagnosticAnalyzer' hat eine Ausnahme vom Typ 'System.ArgumentNullException' mit der Meldung 'Der Wert darf nicht NULL sein.
Parametername: source' ausgelöst.	WindowsApplication1		1	Aktiv

video : https://www.youtube.com/watch?v=eGN4H_ODr3A

**Comment by srivatsn** [comment]
Seems like a dupe of https://github.com/dotnet/roslyn/issues/6682
