### ISSUE TITLE
current install scripts in generated NuGet package will not be executed in projects managed by project.json 

### ISSUE THREAD

**Issue by genlu** [dotnet/roslyn-analyzers#812]
As documented at 
https://docs.nuget.org/create/creating-and-publishing-a-package

[Roslyn](https://github.com/dotnet/roslyn) is an example. We need to add prop files similar to the following to provide a better experience in such scenario.

```
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Condition="'$(ProjectLanguage)' == 'CSharp'">
    <Analyzer Include="$(MSBuildThisFileDirectory)..\tools\Roslyn.Diagnostics.Analyzers.dll" />
    <Analyzer Include="$(MSBuildThisFileDirectory)..\tools\Roslyn.Diagnostics.Analyzers.CSharp.dll" />
  </ItemGroup>
  <ItemGroup Condition="'$(ProjectLanguage)' == 'VB'">
    <Analyzer Include="$(MSBuildThisFileDirectory)..\tools\Roslyn.Diagnostics.Analyzers.dll" />
    <Analyzer Include="$(MSBuildThisFileDirectory)..\tools\Roslyn.Diagnostics.Analyzers.VisualBasic.dll" />
  </ItemGroup>
</Project>
```

**Comment by srivatsn** [comment]
For projects with project.json, analyzers are picked up by convention - the tooling that understands project.json will looks for an analyzers directory and will looks for dlls under that per [this convention](https://docs.nuget.org/create/analyzers-conventions). All packages in this repo already follow the convention and therefore would work with project.json based projects.
