### ISSUE TITLE
Provide NuGet packages for all analyzer projects

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#833]
Make NuGet packages for the following analyzer projects available on http://nuget.org:

* [ ] ApiReview.Analyzers
* [ ] Desktop.Analyzers
* [ ] Microsoft.ApiDesignGuidelines.Analyzers
* [ ] Microsoft.CodeAnalysis.Analyzers
* [ ] Microsoft.Composition.Analyzers
* [ ] Microsoft.Maintainability
* [ ] Microsoft.QualityGuidelines.Analyzers
* [ ] Roslyn.Diagnostics.Analyzers
* [ ] System.Collections.Immutable.Analyzers
* [ ] System.Resources.Analyzers
* [ ] System.Runtime.Analyzers
* [ ] System.Runtime.InteropServices.Analyzers
* [ ] System.Security.Cryptography.Hashing.Algorithms.Analyzers
* [ ] System.Threading.Tasks.Analyzers
* [ ] Text.Analyzers
* [ ] XmlDocumentationComments.Analyzers

**Comment by Dresel** [comment]
+1

**Comment by mavasani** [comment]
We now have a public myget feed for analyzers: https://www.myget.org/F/roslynanalyzers/api/v3/index.json

This feed has 1.2.0-beta1 build, which has IOperation based analyzers. Consumers must add IOperation feature flag to their projects to use these analyzers.

We should create the nuget feed when we are ready to release 1.2.0 build.

**Comment by mavasani** [comment]
Also note that you need VS2015 Update2 to see intellisense diagnostics from IOperation analyzers.

**Comment by Dresel** [comment]
Great, thanks for letting us know.

**Comment by srivatsn** [comment]
This is now done.

**Comment by flcdrg** [comment]
Where did the myget feed go? Would be nice to have it for builds off of trunk.
