### ISSUE TITLE
make RS1008 to ignore nested struct as well

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn-analyzers#845]
right now, if nested class in diagnostic analyzer has roslyn symbols as field, we don't issue RS1008 but it looks like we missed struct case.

**Comment by heejaechang** [comment]
once it is fixed we can remove supress on https://github.com/dotnet/roslyn-analyzers/pull/844/files

**Comment by duracellko** [comment]
when it is fixed, suppress warning can be removed on https://github.com/dotnet/roslyn-analyzers/pull/866/files

**Comment by bkoelman** [comment]
Perhaps we should add detection for storing fields of type `IOperation`, next to the existing `Compilation` and `ISymbol` warnings.

**Comment by srivatsn** [comment]
Makes sense.

**Comment by Evangelink** [comment]
I see that the ticket is up for grabs but I am not sure which of the 2 points discussed in this thread shall be addressed.
