### ISSUE TITLE
CA1802 false positive when initializer contains expression with constant

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#848]
Ported from https://github.com/dotnet/roslyn/issues/8600

Consider the following field on some class `C`:

    static readonly int F = DateTime.Now.Second == 0 ? 1 : 2;

It generates the following Code Analysis warning:

> Warning CA1802: Field 'C.F' is declared as 'static readonly' but is initialized with a constant value '1'. Mark this field as 'const' instead.

**Comment by srivatsn** [comment]
Presumably this was reported on the Fxcop rule - we need to ensure that the analyzer doesnt have this problem.

**Comment by srivatsn** [comment]
Verified that the analyzer implementation doesn't report an issue in this scenario.
