### ISSUE TITLE
Analyzer 'Microsoft.ApiDesignGuidelines.Analyzers.ExceptionsShouldBePublicAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null. Parameter name: item'

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#849]
1. Clean RoslynDev hive on your machine
2. Get latest sources of roslyn and build
3. Get latest sources of roslyn-analyzers and build
4. devenv /rootsuffix RoslynDev
5. Open Roslyn.sln

Got the following AD0001 in the error list:

```

Severity    Code    Description Project File    Line    Source  Tool    Detail Description
Error   AD0001  Analyzer 'Microsoft.ApiDesignGuidelines.Analyzers.ExceptionsShouldBePublicAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: item'.  CodeAnalysis        1   IntelliSense    Microsoft.ApiDesignGuidelines.Analyzers Analyzer 'Microsoft.ApiDesignGuidelines.Analyzers.ExceptionsShouldBePublicAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis
ISymbol: IPEDeltaAssemblyBuilder (NamedType)

System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Immutable.ImmutableHashSet`1.Contains(T item)
   at Microsoft.ApiDesignGuidelines.Analyzers.ExceptionsShouldBePublicAnalyzer.<>c__DisplayClass9_0.<AnalyzeCompilationStart>b__2(SymbolAnalysisContext saContext) in C:\roslyn-analyzers\src\Microsoft.ApiDesignGuidelines.Analyzers\Core\ExceptionsShouldBePublic.cs:line 68
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass37_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by natidea** [comment]
Well, this is quite odd. The [offending line](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs#L68) is:

```c#
if (symbol.BaseType != null && exceptionTypes.Contains(symbol.BaseType)) 
{ 
      saContext.ReportDiagnostic(symbol.CreateDiagnostic(Rule)); 
} 

```
Somehow symbol.BaseType is null. Is this some kind of multi threading issue?

**Comment by mavasani** [comment]
@natidea were you able to repro it locally? The repro call stack was collected a while back and it is likely the source file has changed since. I know @nguerrera fixed a bunch of NREs when doing his testing, this might be one of them?

**Comment by mavasani** [comment]
Can you check the source file history?

**Comment by nguerrera** [comment]
Yes. I fixed a few places where the assumption of BaseType != null was wrong. That looks like one of them: https://github.com/dotnet/roslyn-analyzers/commit/3af1625c2bf4efb66c0e35a89e7347c4476a26e0

**Comment by nguerrera** [comment]
Perhaps that fixed this?

**Comment by natidea** [comment]
Yes, I think it likely has been fixed. I'll confirm it does not repro locally and close this bug.

**Comment by mavasani** [comment]
You can probably close it outwithout attempting to repro if the fix was explicitly adding a null check. I plan to re-run the repro with all analyzers enabled pretty soon.

**Comment by mavasani** [comment]
I am closing this out - if we run into this again, I will re-open the bug.
