### ISSUE TITLE
Create a script to execute Roslyn-analyzers signed build and upload/pin the nuget packages to myget

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#869]
Feed details: https://www.myget.org/feed/Details/roslynanalyzers

**Comment by mavasani** [comment]
FYI @lgolding

**Comment by srivatsn** [comment]
Let's track this as part of #278

**Comment by mavasani** [comment]
I am re-opening this bug and closing #278 as the part that is really left is just this script.

**Comment by mavasani** [comment]
Already being done now.
