### ISSUE TITLE
Cleanup the namespaces for C# and VB analyzer/fixer projects

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#872]
We seem to follow different conventions for namespaces in C# and VB analyzer projects. For example, all the analyzers in `System.Runtime.CSharp.Analyzers` and `System.Runtime.VisualBasic.Analyzers` are under namespace `System.Runtime.Analyzers` which doesn't have the CSharp or VisualBasic suffix. On the other hand, the analyzers in `CSharpCodeAnalysisDiagnosticAnalyzers` and `BasicCodeAnalysisDiagnosticAnalyzers` are under namespaces `Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers` and `Microsoft.CodeAnalysis.VisualBasic.Analyzers.MetaAnalyzers` respectively.

We should clean this up soon as ruleset entries need to specify the rule namespace, and we don't want the inconsistencies to sneak into public rulesets consuming these packages.

**Comment by srivatsn** [comment]
Rule namespaces in the ruleset is not the source namespace of the rule. It's a namespace used to disambiguate rules in the ruleset editor. It's not used as far as I know. 

That's not an argument against cleaning this up though.

**Comment by bkoelman** [comment]
I would be happy to submit a PR for this. Along with namespace alignment, I believe we should also rename the projects in folder `Microsoft.CodeAnalysis.Analyzers`, which are missing dots in their name (for example: `CodeAnalysisDiagnosticAnalyzers.csproj`).

However I recently submitted some PRs (#1040 and #1041) that will cause conflicts, so I'll hold this off until those have been merged.
