### ISSUE TITLE
CA2235: Remove special case code for primitive types

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#875]
#### Analyzer package

Desktop.Analyzers
#### Analyzer

MarkAllNonSerializableFields
#### Repro steps
1. Create a class
2. Mark it `[Serializable]`
3. Add a member of a serializable .NET class such as `Regex`
#### Expected behavior

CA2235 should not issue a diagnostic for the `Regex` member.
#### Actual behavior

CA2235 issues a diagnostic for the `Regex` member.
#### Explanation

CA2235 does not issue a diagnostic for types that are marked with `[Serializable]`. But that attribute is not persisted in the metadata; instead, the metadata just sets a bit to indicate that a type is serializable. So when CA2235 sees a member of a type that is defined in metadata, and queries the member's type for `SerializableAttribute`, it does not find it, concludes that the type is not serializable, and issues a diagnostic.

Recently, in response to dotnet/roslyn#4592, we added special case code to CA2235 so that it would not issue diagnostics for primitive types such as `int`. But that didn't prevent it from issuing diagnostics for other serializable types defined in metadata.

A compiler fix is planned for this (dotnet/roslyn#3898): Roslyn will synthesize a `SerializableAttribute` for any metadata type that has the appropriate bit set. Once that happens, the special case code for primitive types will no longer be necessary and should be removed. Also, we should add unit tests for a couple of non-primitive serializable types, such as `Regex`, to verify the fix.

**Comment by jvandertil** [comment]
I believe this issue can now be fixed since roslyn#3898 has been shipped in VS 15.7?

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn-analyzers/pull/1758
