### ISSUE TITLE
Analyzers project is misnamed

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#883]
The project file src\System.Security.Cryptography.Hashing.Algorithms.Analyzers\CSharp\System.Security.Cryptography.Hashing.CSharp.Algorithms.csproj is misnamed. It should be named System.Security.Cryptography.Hashing.Algorithms.CSharp.Analyzers.csproj to match the assembly it builds.

The misnamed project file does build the correct assembly. The corresponding VisualBasic project file is correctly named, as are other project files I spot-checked.

**Comment by bkoelman** [comment]
This is fixed in PR #1041.

**Comment by bkoelman** [comment]
Can we close this? PR has been merged.

**Comment by srivatsn** [comment]
Sure. Thanks
