### ISSUE TITLE
Hide language-dependent code behind an interface

### ISSUE THREAD

**Issue by lgolding** [dotnet/roslyn-analyzers#888]
In PR #885, I introduced language-dependent utility assemblies to hold methods such as `IsAssignableTo`, which are not exposed by Roslyn's language-agnostic APIs.

@mavasani suggests that we define an interface `ISemanticFactsService` with methods such as `IsAssignableTo` in the core utilities assembly. He [wrote](https://github.com/dotnet/roslyn-analyzers/pull/885/files/849300414b81e3dabe90698141ae0cb50d947423#r57389951):

> ... if IsAssignableTo was an interface method, just like the Roslyn implementation ISemanticFactsService.IsAssignableTo ...[t]hen a client at language independent layer can invoke this method (see [here ](https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fsource.roslyn.io%2f%23Microsoft.CodeAnalysis.Features%2fGenerateMember%2fGenerateConstructor%2fGenerateConstructorHelpers.cs%2c75&data=01%7c01%7cLaurence.Golding%40microsoft.com%7c0811cdc9aa5748ab0dd608d3542a6617%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=IZFI1bSm6W8jBg3NLW89%2fnCH6mFlk6JTmA2KKry2%2bE4%3d)for an example). 
We can probably create our own ISemanticFactsService deriving from ILanguageService in the core AnalyzerUtilities project and the CSharp and VB implementations of this interface can MEF export the language service.

**Comment by srivatsn** [comment]
How will this work in the compilers where there's no MEF?

**Comment by lgolding** [comment]
I didn't know the compilers didn't have MEF. Does that kill this idea?

**Comment by srivatsn** [comment]
I think so. There's no form of dependency injection in the compilers.

**Comment by srivatsn** [comment]
@mavasani - am I missing something?

**Comment by lgolding** [comment]
OK, closing. @mavasani FYI.

**Comment by mavasani** [comment]
Probably some day compiler will support MEF :)

**Comment by srivatsn** [comment]
:) We tried the last release and gave up.
