### ISSUE TITLE
System.Security.Cryptography.Hashing.Algorithms.Analyzers has misleading name

### ISSUE THREAD

**Issue by bartonjs** [dotnet/roslyn-analyzers#916]
System.Security.Cryptography.Hashing.Algorithms was merged into System.Security.Cryptography.Algorithms back in the beta 7 timeframe.

We finally delisted the old package today, and noticed https://www.nuget.org/packages/System.Security.Cryptography.Hashing.Algorithms.Analyzers/, which uses the old name in both its title and description.

**Comment by srivatsn** [comment]
Assigning to @lgolding since #883 is related as well.

**Comment by 333fred** [comment]
@jinujoseph, is the issue here just that the project needed to be renamed? If so, we just need to clean up the docs folder and this should be good.

**Comment by mavasani** [comment]
@333fred we merged this analyzer package into NetFramework analyzers package. Can you confirm if the namespace name for the analyzers in this package is as expected and close it out?

**Comment by 333fred** [comment]
It appears correct. We just need to update the README file on the analyzers in the NetCore package, as it still has the old namespace.
