### ISSUE TITLE
CA1051 is missing a few cases that FxCop used to cover

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-analyzers#919]
#### Analyzer package

Example: Microsoft.ApiDesignGuidelines.Analyzers
#### Analyzer

Example: DoNotDeclareVisibleInstanceFields

See https://github.com/dotnet/roslyn-analyzers/pull/740#discussion_r58753591 for more details

**Comment by mavasani** [comment]
Fixed with #1530
