### ISSUE TITLE
Enable VB Fixer for CA2119 when SyntaxGenerator is updated

### ISSUE THREAD

**Issue by mattwar** [dotnet/roslyn-analyzers#920]
The SyntaxGenerator does not correctly convert VB statement form declarations into block form declarations when you add statements to them.  This is keeping the language agnostic fixer for CA2119 from working, so it has been disabled.  When the SyntaxGenerator is fixed, enable VB for this fixer.

**Comment by mattwar** [comment]
Added issue #920 to enable VB fixer when Roslyn VB SyntaxGenerator is fixed.

**Comment by mavasani** [comment]
Closing this issue, until we receive a feedback on needing to do this..
