### ISSUE TITLE
Installing MS.CA.FxCopAnalyzers 1.2.0-beta1 shows low of duplicate AnalyzerUtilities nodes in solution explorer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#932]
Not sure if this is a VS bug or the FXCop analyzer package needs to be modified to handled this case.

![installedanalyzers](https://cloud.githubusercontent.com/assets/10605811/14577379/0131d1c0-0328-11e6-9d0f-3b7c0e45f1fe.png)

**Comment by srivatsn** [comment]
I think this is a VS bug. I mentioned this to @davkean yesterday. When we implement the analyzers node in CPS, we should fix this. We should probably fix it in the current implementation as well. Can you open the bug in roslyn?
