### ISSUE TITLE
AvoidUnusedPrivateFieldsAnalyzer CA1823 false report for const field used in collection initializer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#933]
#### Repro steps
1. Open Analyzers.sln
2. Change Dependencies\CodeAnalysis\project.json to include: `"Microsoft.CodeAnalysis.FxCopAnalyzers": "1.2.0-beta1"`
3. Restore NuGet packages for solution
4. Open BasicInvokeTheCorrectPropertyToEnsureCorrectUseSiteDiagnostics.vb

![falsereportca1823](https://cloud.githubusercontent.com/assets/10605811/14577461/39de7054-0329-11e6-8a9c-6ae884e644e3.png)

Seems like an IOperation bug (analyzer is just looking for all FieldReferenceExpressions), but someone should confirm before porting it to Roslyn repo.

@JohnHamby @genlu  do you know if this is fixed in latest bits of Roslyn?

**Comment by JohnHamby** [comment]
It's either an straightforward IOperation bug or a more subtle issue. If the compiler is replacing uses of a named constant with its value in the bound trees, then we will have to get clever to retain the knowledge that the constant came from a symbol.

This is almost certainly not fixed.

**Comment by mavasani** [comment]
Thankhs John, I'll port this bug to Roslyn repo.

**Comment by mavasani** [comment]
NOTE to the person resolving this issue: Please remove all the suppressions for this warning ID in Analyzers.sln (not yet checked in) once this issue is fixed.

**Comment by alejandro5042** [comment]
This issue also manifests with this (uncommitted) test in `src\Microsoft.Maintainability.Analyzers\UnitTests\AvoidUnusedPrivateFieldsTests.cs`:

```c#
        [Fact(Skip="https://github.com/dotnet/roslyn-analyzers/issues/933")]
        public void CA1823_CSharp_AttributeUsage_Diagnostic()
        {
            VerifyCSharp(@"
[System.Obsolete(Message)]
public class Class
{
    private const string Message = ""Test"";
}
");
        }
```

Do you want me to submit a pull request that documents this issue in code?

Do we have any progress on this issue? I could not find a relevant issue in the main Roslyn repository, @mavasani.

It is not immediately clear to me how we would fix this. It seems like `RegisterOperationAction(action, FieldReferenceExpression)` does not fire for these sorts of field references (like @JohnHamby said).

**Comment by alejandro5042** [comment]
Another fail case is interpolated strings. There is a related issue here: https://github.com/dotnet/roslyn/issues/17307

I've updated the pull request to document collection initializers and interpolated strings.

**Comment by mavasani** [comment]
Ported this issue to https://github.com/dotnet/roslyn/issues/18509

**Comment by mavasani** [comment]
@alejandro5042 We hope to fix this in Roslyn soon

**Comment by mavasani** [comment]
@333fred Another issue that should be fixed with Roslyn 2.3.0 bits. Please remove the suppressions for this rule in our repo when we move to newer Roslyn bits.

**Comment by 333fred** [comment]
Fixed with #1248.

**Comment by 333fred** [comment]
Reproing in FxCopAnalyzersPackage.cs.

**Comment by 333fred** [comment]
Whoops, misread this. This is a different scenario.
