### ISSUE TITLE
Package restore fails with "input file does not exist"

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#946]
Following instructions on https://github.com/dotnet/roslyn-analyzers#getting-started to build master branch. Package restore fails with:

```
Input file does not exist: E:\Bart\Source\Repos\roslyn-analyzers\src\.nuget\packages.config.
```

Then building in VS 2015 Update2 fails with lots of errors. First error:
```
1>------ Rebuild All started: Project: CodeAnalysis, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: xUnit, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : The package Microsoft.CodeAnalysis.Common with version 1.2.0 could not be found in C:\Users\Bart\.nuget\packages. Run a NuGet package restore to download the package.
```

Alternatively, tried to install NuGet package from https://www.nuget.org/packages/Microsoft.ApiDesignGuidelines.Analyzers/1.2.0-beta1

After rebuild, it shows lots of failures like:

```
Error	AD0001	Analyzer 'Microsoft.ApiDesignGuidelines.Analyzers.DoNotDirectlyAwaitATaskAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Feature 'IOperation' is disabled.'.
```

Is there any way I can try these analyzers in VS 2015 Update2?

**Comment by bkoelman** [comment]
I fixed the NuGet issue by putting `<Features>IOperation</Features>` in .csproj files.

Still looking for a way to build from source.

**Comment by bkoelman** [comment]
Meanwhile, I got the code to build a bit more, by first running (from Developer Command Prompt):

```
E:\Bart\Source\Repos\roslyn-analyzers\src\.nuget>nuget restore E:\Bart\Source\Repos\roslyn-analyzers\src\Dependencies\CodeAnalysis\project.json
E:\Bart\Source\Repos\roslyn-analyzers\src\.nuget>nuget restore E:\Bart\Source\Repos\roslyn-analyzers\src\Dependencies\xUnit\project.json
E:\Bart\Source\Repos\roslyn-analyzers\src\.nuget>nuget restore e:\Bart\Source\Repos\roslyn-analyzers\src\Test\Utilities\project.json
```

Now build fails on project DiagnosticsTestUtilities, which cannot access the output assemblies from "Dependencies\CodeAnalysis (Portable)" project. Where should these DLLs come from? The CodeAnalysis project references ProducesNoOutput.Imports.targets so I'm lost here.

**Comment by bkoelman** [comment]
@mavasani @srivatsn @basoundr Any thoughts on how I can solve this?

**Comment by mavasani** [comment]
@bkoelman Can you run `cibuild` at the root of the repo?

` <Features>IOperation</Features> ` has already been added to all projects via the imported targets file: https://github.com/dotnet/roslyn-analyzers/blob/master/build/Targets/Analyzers.Imports.targets#L61. Are you somehow not using latest sources to build?

**Comment by mavasani** [comment]
Even references to `\src\.nuget\packages.config` have been removed, so seems like you have some stale source files around.

**Comment by bkoelman** [comment]
@mavasani Thanks for helping. I've synced to latest sources. 

Still getting error in package restore. I guess it comes from here: https://github.com/dotnet/roslyn-analyzers/blob/master/src/.nuget/NuGetRestore.ps1#L4.

Running cibuild helps. It succeeds but also populates my NuGet cache correctly. 
`msbuild src\Analyzers.sln` still fails, but I'm getting a bit further now. First error:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsS
DK.targets(655,5): error VSSDK1040: There was a problem enabling the extension
with a VSIX identifier of "ff0534a8-2c66-4c4d-9cf6-ffb15add1cfc". Access to the
 path 'C:\Users\Bart\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev\Extensi
ons\extensionSdks.en-US.cache' is denied. [E:\Bart\Source\Repos\roslyn-analyzer
s\src\System.Runtime.InteropServices.Analyzers\Setup\System.Runtime.InteropServ
ices.Analyzers.Setup.csproj]
```

The workaround from https://github.com/dotnet/roslyn/issues/10407#issuecomment-207771495 does not help for msbuild (even with /m:1), but it works for build in VS2015 Update2.

So build from source now works and debugging an analyzer also!

To clarify, I had to add `<Features>IOperation</Features>` to the .csproj files that the analyzer package would run on, so those were external sources.

**Comment by mavasani** [comment]
@bkoelman you are correct, I missed fixing NuGetRestore.ps1 - will do so now.

The extension cache issue can be worked around by just deleting your RoslynDev hive (`c:\Users\<%USER_NAME%>\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev`) and rebuilding Analyzers.sln.

**Comment by bkoelman** [comment]
Thanks, #969 makes the restore error go away plus makes running cibuild first no longer needed.

The .cache access denied errors remain, even after clearing hives and NuGet cache. But if I understand correctly, a specific fix in the repo is needed to work around that (see https://github.com/dotnet/roslyn/issues/10407#issuecomment-215205628).

**Comment by bkoelman** [comment]
Did you intend to close this? I'm asking because multicore build still
fails.

**Comment by mavasani** [comment]
Can you open a separate issue for that? Thanks

**Comment by bkoelman** [comment]
Created #973.
