### ISSUE TITLE
The code for DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer no longer exists

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#954]
The code for DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer and PartsExportedWithMEFv2MustBeMarkedAsShared no longer exists in Roslyn-Analyzers.

We should bring it back.

**Comment by mavasani** [comment]
Other rules which also seem to have been affected by this:

1. AvoidUsingCrefTagsWithAPrefixAnalyzer
2. DoNotCallToImmutableArrayOnAnImmutableArrayValueAnalyzer
3. DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyAnalyzer
4. DoNotCreateTasksWithoutPassingATaskSchedulerAnalyzer

**Comment by mavasani** [comment]
This blocks https://github.com/dotnet/roslyn/pull/10312

**Comment by mavasani** [comment]
Unfortunately quite a few of these rules did not have any tests (even before their code got lost). I'll try to add a few unit tests.

**Comment by mavasani** [comment]
@davkean This has now been fixed - you can now fix the issue you were seeing in the Project system solution.
