### ISSUE TITLE
DoNotMixAttributesFromDifferentVersionsOfMEFAnalyzer fires when a metadata attribute is marked from both versions of MEF

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-analyzers#955]
In CPS the AppliesToAttribute is marked with MetadataAttributeAttribute from MEF1 and MEF2, the rule is confused by this and fires on it.

We hit this in http://github.com/dotnet/roslyn-project-system.

When this is fixed, please remove the associated suppressions from that repro.

**Comment by mavasani** [comment]
Tagging @jasonmalinowski as he originally wrote this analyzer. The analyzer is causing false reports on project system repo on any type has the CPS AppliesToAttribute.

For example, see [this](http://index/?query=AppliesToAttribute&rightProject=RoslynProjectSystem(Repo)&file=src%5CMicrosoft.VisualStudio.ProjectSystem.CSharp.VS%5CProjectSystem%5CVS%5CImaging%5CCSharpProjectImageProvider.cs&line=14) type which has a System.ComponentModel.Composition.ExportAttribute and an [AppliesToAttribute](http://index/?query=AppliesToAttribute&rightProject=Microsoft.VisualStudio.ProjectSystem&file=Composition%5CAppliesToAttribute.cs&line=16), which has both System.ComponentModel.Composition.MetadataAttribute and System.Composition.MetadataAttribute applied to it.

**Comment by mavasani** [comment]
I am going to special case this Attribute to unblock the project system repo.
