### ISSUE TITLE
Write code fix for DoNotCallToImmutableArrayOnAnImmutableArrayValueAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#960]
#### Analyzer package

System.Collections.Immutable.Analyzers
#### Analyzer

DoNotCallToImmutableArrayOnAnImmutableArrayValueAnalyzer

https://github.com/dotnet/roslyn-analyzers/pull/956 adds the analyzer, Fixer is NYI

**Comment by TKharaishvili** [comment]
To whomever it might concern, here's the PR - https://github.com/dotnet/roslyn-analyzers/pull/2238

**Comment by TKharaishvili** [comment]
@mavasani the PR was merged in. This issue can probably be closed.

**Comment by Youssef1313** [comment]
Ping @mavasani or @Evangelink for closing this already-fixed issue.

**Comment by Evangelink** [comment]
Fixed by #2238 (thanks for the ping)
