### ISSUE TITLE
Write code fix for DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyAnalyzer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-analyzers#961]
#### Analyzer package

System.Runtime.Analyzers
#### Analyzer

DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyAnalyzer

https://github.com/dotnet/roslyn-analyzers/pull/956 adds the analyzer, Fixer is NYI

**Comment by Youssef1313** [comment]
Related to (or dupe of) https://github.com/dotnet/roslyn-analyzers/issues/1932)

**Comment by Youssef1313** [comment]
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/1932

**Comment by Youssef1313** [comment]
Note, fixer is already implemented, but only for `Enumerable.First`, `Enumerable.Last`, and `Enumerable.Count`.
