### ISSUE TITLE
Build fails with "Access to the  path '...\extensionSdks.en-US.cache' is denied."

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#973]
#### Repro steps

1. Follow steps at https://github.com/dotnet/roslyn-analyzers#getting-started on VS 2015 Update2
2. First error output for `msbuild src\Analyzers.sln`:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsS
DK.targets(655,5): error VSSDK1040: There was a problem enabling the extension
with a VSIX identifier of "8ea2cb5d-390d-4b56-b9b5-8d3175368d69". Access to the
 path 'C:\Users\Bart\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev\Extensi
ons\extensionSdks.en-US.cache' is denied. [e:\Bart\Source\Repos\roslyn-analyzer
s\src\ApiReview.Analyzers\Setup\ApiReview.Analyzers.Setup.csproj]
```

The roslyn repository had [a similar failure](https://github.com/dotnet/roslyn/issues/10407); that fix can possibly be applied here too.

**Comment by srivatsn** [comment]
It'll be good to switch over to using the VS SDK NuGet packages to remove dependency on VS for building as well. If it fixes this bug that's an added bonus.

**Comment by AmadeusW** [comment]
*this issue is a top search result, so FYI:*
the solution to this problem is to clear `%localappdata%\Microsoft\VisualStudio\14.0Roslyn` directory and rebuild your analyzer.

**Comment by bkoelman** [comment]
@AmadeusW That does not work for me. Please note that this issue is very specific to the https://github.com/dotnet/roslyn-analyzers repo, not for custom analyzer projects in general. 

Building from `msbuild src\Analyzers.sln` causes these errors, while running `cibuild.cmd` does not.

**Comment by AmadeusW** [comment]
I'm sorry. Thanks for letting us know!

**Comment by bkoelman** [comment]
Closing this issue, because it does not occur in VS2015 Update3.
