### ISSUE TITLE
[Request for help] using DeclarePublicAPIAnalyzer in third-party code?

### ISSUE THREAD

**Issue by ig-sinicyn** [dotnet/roslyn-analyzers#976]
Copied from Roslyn's [#11167](https://github.com/dotnet/roslyn/issues/11167)

Hi! I've noted that [this page](https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md) mentions analyser that uses PublicAPI.Shipped.txt and PublicAPI.Unshipped.txt to detect breaking public API changes. As far I can see it's a DeclarePublicAPIAnalyzer.

We have a project with a large public API surface that we want to freeze. Is it possible to use the DeclarePublicAPIAnalyzer in our case? If yes, what steps should I perform?

Hi! I've noted that [this page](https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md) mentions analyser that uses PublicAPI.Shipped.txt and PublicAPI.Unshipped.txt to detect breaking public API changes. As far I can see it's a DeclarePublicAPIAnalyzer.

We have a project with a large public API surface that we want to freeze. Is it possible to use the DeclarePublicAPIAnalyzer in our case? If yes, what steps should I perform?

**UPD:** AS @jaredpar wrote:

>this analyzer was designed specifically for Roslyn and it has a couple of assumption about our versioning model baked in. It probably needs a bit of work before it could be made more general purpose.

Well, we're trying to follow SemVer conventions and  we want to be notified if we've made any breaking changes.

As far as I can see the most detailed description of what is breaking change and what is not is located [here](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md). 

However, the idea to detect automatically all violations from the list above sounds too unrealistic. So, let's start with a definition "breaking change is the change that breaks the binary compatibility". This one should be much easier to detect.

**Comment by mavasani** [comment]
@ig-sinicyn You can follow the below steps to get this analyzer working for you:

1. Add Nuget package reference to https://www.nuget.org/packages/Roslyn.Diagnostics.Analyzers/1.2.0-beta1 to your project(s), which will enable the declare public API analyzer (and the [supported rules](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs#L107)).
2. Follow the workaround [here](https://github.com/dotnet/roslyn/issues/5104#issuecomment-215792030) to allow adding additional files to your project from VS.
3. Add 2 text files to your project(s): PublicAPI.Shipped.txt and PublicAPI.Unshipped.txt (see [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs#L17). Set the `Build Action` for these files to be `Additional Files` from the properties window.

**Comment by ig-sinicyn** [comment]
@mavasani 
Wow, thanks!

**Comment by ig-sinicyn** [comment]
@mavasani 
Thanks, it works. 
One question though: does it detect changes on shipped API (e.g. method renaming/removal)? If yes - how can it be enabled? :confused:

**Comment by mavasani** [comment]
> does it detect changes on shipped API 

No, the idea is you should never change your shipped public API. If you are forced to, then the only way is to leave the original public API entry for shipped API and add its cloned entry with a [Remove Prefix](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Roslyn.Diagnostics.Analyzers/Core/DeclarePublicAPIAnalyzer.cs#L23). Basically you should never delete any existing entries from shipped public API file.

**Comment by ig-sinicyn** [comment]
@mavasani 

>No, the idea is you should never change your shipped public API

Yes, agreed. But what about accidental changes made by mistake?
E.g, if someone from team accidentally added a new arg or change return type of the method.

I'd thought that DeclarePublicAPIAnalyzer should warn about lines in shipped/unshipped.txt that have no matches in the code.

**Comment by mavasani** [comment]
Yes, it will. Basically shipped API file should stay unchanged, except for releases. All in flight public API changes between releases must happen in unshipped public API file.

**Comment by ig-sinicyn** [comment]
@mavasani 

>Yes, it will

Well, it looks like I'm doing something wrong.

[Here's](https://github.com/dotnet/roslyn-analyzers/files/268929/ConsoleApplication1.zip)
a sample project with two public methods, `TestMethod1` and `TestMethod2`, both included in Shipped.txt.

No compiler warnings emitted after TestMethod2 removal. What I've missed?

**Comment by javierdlg** [comment]
@ig-sinicyn The files you linked are no longer available. Is this still an issue? If so I recommend opening a new issue.

**Comment by ig-sinicyn** [comment]
@javierdlg  the files [are available](https://github.com/dotnet/roslyn-analyzers/files/268929/ConsoleApplication1.zip) still but the issue is closed and unactual as we've implemented same analyser by ourselves :)

Thanks for asking!
