### ISSUE TITLE
Revert workaround for skipping generated code in CompilationEndAction

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#983]
We should revert the workaround from https://github.com/dotnet/roslyn-analyzers/commit/550eaa6634186a0a97e54733beeb0e3977b4bae3 once https://github.com/dotnet/roslyn/pull/11225 becomes available.

**Comment by mavasani** [comment]
We have decided that until we need a new API from future Microsoft.CodeAnalysis packages, we will compile the analyzers repo against 1.2 package. This enables us to keep executing our analyzers on Update2. This bug is blocked till we upgrade to newer Microsoft.CodeAnalysis packages.
