### ISSUE TITLE
TODO depends on closed bug

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#992]
https://github.com/dotnet/roslyn-analyzers/blob/master/src/System.Runtime.Analyzers/Core/ProvideCorrectArgumentsToFormattingMethods.cs#L70 contains:

```csharp
// TODO: due to a bug - https://github.com/dotnet/roslyn/issues/7346
//       vararg case is disabled.
//       we might check this only for C# since __arglist is not supported in VB
//
//       we need to implement proper support for __arglist once the bug is fixed.
if (invocation.TargetMethod.IsVararg)
{
    // can't deal with this for now.
    return;
}
```

The mentioned bug https://github.com/dotnet/roslyn/issues/7346 is closed, though, without having a fix, I think.

What is needed to move forward?

**Comment by mavasani** [comment]
We should replace TODO with just a comment that this is not supported
