### ISSUE TITLE
Add unittest for IOperation

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn-analyzers#999]
Once https://github.com/dotnet/roslyn/pull/11246 is available, we should add a unittest next to https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.Analyzers/Test/InternalImplementationOnlyTests.cs#L177 to verify that `InternalImplementationOnlyAnalyzer` works correctly for `IOperation`:

``` csharp
        [Fact]
        public void CSharp_VerifyIOperation()
        {
            var source = @"
public class Foo : Microsoft.CodeAnalysis.IOperation { }
public class Bar : Microsoft.CodeAnalysis.Semantics.IInvocationExpression { }
";
            DiagnosticResult[] expected = new[] { GetCSharpExpectedDiagnostic(2, 14, "Foo", "IOperation"), GetBasicExpectedDiagnostic(5, 14, "Bar", "IInvocationExpression") };

            // Verify that IOperation is not implementable.
            VerifyCSharp(source, addLanguageSpecificCodeAnalysisReference: true, expected: expected);
        }
```

**Comment by mavasani** [comment]
We have decided that until we need a new API from future Microsoft.CodeAnalysis packages, we will compile the analyzers repo against 1.2 package. This enables us to run our analyzers on Update2.

**Comment by bkoelman** [comment]
@mavasani Thanks for the update.
